### ISSUE TITLE
OSX vapor build  vapor xcode error

### ISSUE THREAD

**Issue by jh235** [vapor/vapor#1004]
* Vapor Version:  Vapor Toolbox v1.0.9
* OS: macOs
* OS Version:  10.12.4
* swift Version:
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9

### Expected Behavior

$ vapor build
Fetching Dependencies [Failed]
Error: swift-package: error: unknown command: --enable-prefetching

$ vapor xcode
Fetching Dependencies [Failed]
Error: swift-package: error: unknown command: --enable-prefetching

Describe what you expect to happen.
I can do it in Ubuntu 14.04.5

**Comment by tanner0101** [comment]
Toolbox 1.0.9 requires Swift 3.1.
