### ISSUE TITLE
https://apt.vapor.sh: 404: Not Found

### ISSUE THREAD

**Issue by TofPlay** [vapor/vapor#1016]
* Vapor Version: 2.0.0
* OS: Ubuntu 
* OS Version: 16.10

### Expected Behavior

Run https://apt.vapor.sh

### Current Behavior

Generate error 404

### How to Reproduce

Open a browser and enter https://apt.vapor.sh
or
Open Terminal and run:
```bash
eval "$(curl -sL https://apt.vapor.sh)"
```

**Comment by tanner0101** [comment]
Works for me: 
```
Gyda:Web tanner$ curl -sL https://apt.vapor.sh
function add_vapor_apt() {
...
```

Also on 16.10

```
tanner@ubuntu:~$  curl -sL https://apt.vapor.sh
function add_vapor_apt() {
    eval "$(cat /etc/lsb-release)"
...
```

It may take some time for the cURL redirect cache to expire. Maybe this will help: http://stackoverflow.com/questions/31653271/curl-command-without-using-cache

Please re-open if this ends up not being cache related.
