### ISSUE TITLE
Use of unresolved identifier in 'Droplet' and 'Config'

### ISSUE THREAD

**Issue by RobertTheProfessional** [vapor/vapor#1017]
* Vapor Version: 2.0.1
* OS: macOS
* OS Version: 10.12.5

### Expected Behavior

Expected to scaffold a new Vapor 2.x application using the Vapor Toolkit as well as generating a Xcode project for development. 

### Current Behavior

Once the application and Xcode project are generated, on build of the `Run` target I receive a build error stating `Use of unresolved identifier in 'Droplet'` and `Use of unresolved identifier in 'Config'`.

### How to Reproduce

```
vapor new Hello --template=api
cd Hello/
vapor xcode
vapor build
```

**Comment by tanner0101** [comment]
Works fine for me on the same macOS version. Make sure you have the latest Vapor toolbox version.

```sh
Gyda:Hello tanner$ vapor version
Vapor Toolbox: 2.0.2
Vapor Framework: 2.0.0
Gyda:Hello tanner$ 
```

Attempting to reproduce:

```sh
Last login: Thu May 18 20:08:26 on ttys001
Gyda:~ tanner$ vapor new Hello --template=api
cd Hello/
vapor xcode
vapor build
Cloning Template [Done]
Updating Package Name [Done]
Initializing git repository [Done]

                                                  **
                                                **~~**
                                              **~~~~~~**
                                            **~~~~~~~~~~**
                                          **~~~~~~~~~~~~~~**
                                        **~~~~~~~~~~~~~~~~~~**
                                      **~~~~~~~~~~~~~~~~~~~~~~**
                                     **~~~~~~~~~~~~~~~~~~~~~~~~**
                                    **~~~~~~~~~~~~~~~~~~~~~~~~~~**
                                   **~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
                                   **~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
                                   **~~~~~~~~~~~~~~~~~~~~~++++~~~**
                                    **~~~~~~~~~~~~~~~~~~~++++~~~**
                                     ***~~~~~~~~~~~~~~~++++~~~***
                                       ****~~~~~~~~~~++++~~****
                                          *****~~~~~~~~~*****
                                             *************
                                    
                                    _       __    ___   ___   ___
                                   \ \  /  / /\  | |_) / / \ | |_)
                                    \_\/  /_/--\ |_|   \_\_/ |_| \
                                      a web framework for Swift

                                  Project "Hello" has been created.
                           Type `cd Hello` to enter the project directory.
                                                Enjoy!

Gyda:~ tanner$ cd Hello/
Gyda:Hello tanner$ vapor xcode
Generating Xcode Project [Done]
Select the `Run` scheme to run.
Open Xcode project?
y/n> y
Opening Xcode project...
Gyda:Hello tanner$ vapor build
Building Project [Done]
Gyda:Hello tanner$ 
```

![screen shot 2017-05-19 at 11 50 23 am](https://cloud.githubusercontent.com/assets/1342803/26244843/74c8c6fc-3c89-11e7-8c28-1017bb017336.png)

**Comment by RobertTheProfessional** [comment]
You might be my good luck charm, I was able to build my application in Xcode this time around. I had to change the Target Membership of the main.swift file to point to the App module to get it to compile last night but it appears it's working while being point to the Run module

**Comment by nmdias** [comment]
I also had this issue after creating a new project out of the api template (Vapor 2.0 Beta 25). However, I had it fixed immediately after a second build attempt. Never saw it again. I'm now running:

Vapor Toolbox: 2.0.3
Vapor Framework: 2.0.0

I'm unable to replicate this again.

**Comment by mikecole20** [comment]
I'm getting this error when trying to run from Xcode as well.

Vapor Toolbox: 2.0.3
Vapor Framework: 2.0.2

Everything works from the command line, but Xcode doesn't recognize `Config` or `Droplet` inside `main.swift`.

**Comment by tanner0101** [comment]
@mikecole20 is it preventing you from building in Xcode?

**Comment by mikecole20** [comment]
@tanner0101 yes, it is a build failure.

![image](https://cloud.githubusercontent.com/assets/8332399/26408046/c393a010-406a-11e7-81fb-9161830be334.png)

However, I just tried building a new project to reproduce this from scratch and it seems to be working.

**Comment by mikecole20** [comment]
Well I think I've found the root cause. I dug into the `AppName` scheme that is generated for the Xcode project and found that it was also trying to build the `RunExample` scheme which showed up along with SwiftyBeaverProvider.

Of course, I tried to reproduce that with an example project, and the example has no problems building both `Run` and `RunExample`...

**Comment by tanner0101** [comment]
Ah interesting. Possibly an issue should be opened against SwiftyBeaverProvider to exclude executables from its package.

**Comment by ACChe** [comment]
How to resolve it?

**Comment by mikecole20** [comment]
Well I'm still a little confused on the root cause of this. When I found the `RunExample` scheme from SwiftyBeaverProvider, I was able to fix it by selecting the framework scheme and pressing `Edit Scheme...`, selecting the `Build` tab on the left, finding `RunExample` in the list and unchecking all of the boxes.

However, once you regenerate the Xcode project, this will likely show back up as an issue. I just checked the current settings (I've regenerated since) and `RunExample` is checked again, but is no longer causing issues. ¯\_(ツ)_/¯

**Comment by guttentag** [comment]
Hey watchers, I have the same issue, I didn't find 'SwiftyBeaverProvider' nor 'RunExample'.
can you please elaborate more on the fix?

**Comment by nmdias** [comment]
@guttentag Hi, I don't think there is a fix. Are you able to reproduce this?

**Comment by rmda** [comment]
Hi, I'm totally new to developing with Swift and Vapor but I thought I was hitting this. It seems I'm not able to access config within controllers? I used vapor new testproject && cd testproject && vapor xcode. From there you can type 'config' within any of the controller methods such as index, before the return ... statement (line 13).

If I attempt to access config within Droplet+setup.swift it is fine, so I went with that ultimately. I know there is a much better way to do it, would someone mind taking a look and giving me feedback? Much thanks in advance!

https://github.com/rmda/yuubin

**Comment by 0xTim** [comment]
@rmda when you instantiate a controller, just pass the config object into the initialiser

**Comment by rajesh-situ** [comment]
Getting the below error.
`import Vapor

let drop = Droplet()

drop.get('/') { request in
    return "Hello World"
}

drop.run()`
HelloWorld/Sources/Run/main.swift:3:12: error: use of unresolved identifier 'Droplet'

Any suggestions??

**Comment by 0xTim** [comment]
@rajesh-situ how did you create the project? `Droplet` is from the Vapor 2 days so doesn't exist anymore. What documentation are you following?

**Comment by rajesh-situ** [comment]
@0xTim my bad. was referring to a very old article. thanks!
