### ISSUE TITLE
Response redirect via POST request instead GET

### ISSUE THREAD

**Issue by AlanMcKen** [vapor/vapor#1018]
* Vapor Version: 2.0.1 
* OS: macOS
* OS Version: 10.12.4

### Expected Behavior

redirect via GET request

### Current Behavior

redirect via POST request

### How to Reproduce

```
import Vapor

final class Routes: RouteCollection {
    let view: ViewRenderer
    init(_ view: ViewRenderer) {
        self.view = view
    }
    
    func build(_ builder: RouteBuilder) throws {
        builder.post("/login") { req in
            // Login
            return Response(redirect: "/admin")
        }
    }
}
```

**Comment by Joannis** [comment]
Didn't you mean to do this?

```swift
import Vapor

final class Routes: RouteCollection {
    let view: ViewRenderer
    init(_ view: ViewRenderer) {
        self.view = view
    }
    
    func build(_ builder: RouteBuilder) throws {
        builder.get("/login") { req in
            // Login
            return Response(redirect: "/admin")
        }
    }
}
```

**Comment by AlanMcKen** [comment]
Yes, in builder.get("/login") {...} redirect works properly via GET request, but when I try to redirect in form handler and use builder.post or drop.post, its redirects via POST. This is only for example. Before update to vapor 2.0 redirect always worked via GET.

**Comment by 0xTim** [comment]
Can you get some network logs, you won't get a GET or POST on a response. The flow should be:

* Send request to POST
* Server sends response with status code 307 and location in the header
* Browser receives the 307 and then sends a get to the new location

For reference I have this working in my Vapor 2 project. The response code has changed from a 302 to 307 which might explain your issue?

**Comment by vzsg** [comment]
That's where the whole "let's change 302 to 307 because it sounds better" gets complicated.

User agents are expected to retry the same request at the new location with 307, so the POST *will not be* converted into a GET.

**Comment by AlanMcKen** [comment]
GET request to /login

```
Request URL:http://localhost:8080/login
Request Method:GET
Status Code:200 OK
Remote Address:127.0.0.1:8080
```
POST request to /login (form handler)

```
Request URL:http://localhost:8080/login
Request Method:POST
Status Code:307 Temporary Redirect
Remote Address:127.0.0.1:8080
```
... and POST redirect to /admin

```
Request URL:http://localhost:8080/admin/
Request Method: POST
Status Code:200 OK
Remote Address:127.0.0.1:8080
```
Just checked in Chrome, Firefox and Safari

**Comment by vzsg** [comment]
On the other hand, HTTP 303 See Other should be used in this scenario as it *explicitly* means that the new request should be a GET at the new location.

**Comment by tanner0101** [comment]
@AlanMcKen do something like this to replicate the old behavior:

```swift
return Response(status: .seeOther, headers: ["Location": "/admin"])
```

@vzsg perhaps we should consider adding another overload to response for this case? If so, let's open this in https://github.com/vapor/engine where it belongs.

**Comment by vzsg** [comment]
@tanner0101 where is that `Response(redirect:)` defined?

TBH, if the status code is settable, this is more of a potential documentation issue than a code issue.
(Potential, as I have yet to read the docs to check if the expected behavior of redirection is explained.)

**Comment by tanner0101** [comment]
https://github.com/vapor/engine/blob/master/Sources/HTTP/Response/Response.swift#L36-L45
