### ISSUE TITLE
auth template

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1019]
Add an auth template similar to api and web.

**Comment by damirstuhec** [comment]
@tanner0101 I think this "issue" can be closed now since you've done this: https://github.com/vapor/auth-template.

**Comment by damirstuhec** [comment]
It should probably also be listed here: https://docs.vapor.codes/2.0/getting-started/toolbox/#options.

**Comment by tanner0101** [comment]
thanks :)
