### ISSUE TITLE
Can't migrate to Vapor 2 from beta: swift-package: error: unsatisfiable

### ISSUE THREAD

**Issue by agordeev** [vapor/vapor#1022]
Here's how my dependencies looked like:

        dependencies: [
            .Package(url: "https://github.com/vapor/vapor.git", Version(2, 0, 0, prereleaseIdentifiers: ["beta"])),
            .Package(url: "https://github.com/vapor/fluent-provider.git", Version(1, 0, 0, prereleaseIdentifiers: ["beta"])),
            .Package(url: "https://github.com/vapor/mysql-provider.git", Version(2, 0, 0, prereleaseIdentifiers: ["beta"])),
            .Package(url: "https://github.com/BrettRToomey/Jobs.git", Version(1, 0, 0, prereleaseIdentifiers: ["beta"])),
            .Package(url: "https://github.com/tadija/AEXML.git", majorVersion: 4),
            .Package(url: "https://github.com/alexaubry/HTMLString", majorVersion: 3, minor: 0),
            .Package(url: "https://github.com/gperdomor/SwiftyBeaver-Vapor.git", Version(2,0,0, prereleaseIdentifiers: ["beta"]))
        ]

I changed them to this: 

        dependencies: [
            .Package(url: "https://github.com/vapor/vapor.git", Version(2, 0, 1)),
            .Package(url: "https://github.com/vapor/fluent-provider.git", Version(1, 0, 0)),
            .Package(url: "https://github.com/vapor/mysql-provider.git", Version(2, 0, 0)),
            .Package(url: "https://github.com/BrettRToomey/Jobs.git", Version(1, 0, 0, prereleaseIdentifiers: ["beta"])),
            .Package(url: "https://github.com/tadija/AEXML.git", majorVersion: 4),
            .Package(url: "https://github.com/alexaubry/HTMLString", majorVersion: 3, minor: 0),
            .Package(url: "https://github.com/gperdomor/SwiftyBeaver-Vapor.git", Version(2,0,0, prereleaseIdentifiers: ["beta"]))
        ]

Did `vapor clean` and `vapor xcode -y` and got this error:

> No .build folder, fetch may take a while...
> Fetching Dependencies [            •            ]
> Error: backgroundExecute(code: 1, error: "swift-package: error: unsatisfiable\n", output: "Fetching https://github.com/tadija/AEXML.git\nFetching https://github.com/vapor/mysql-provider.git\nFetching https://github.com/gperdomor/SwiftyBeaver-Vapor.git\nFetching https://github.com/BrettRToomey/Jobs.git\nFetching https://github.com/vapor/tls.git\nFetching https://github.com/alexaubry/HTMLString\nFetching https://github.com/vapor/vapor.git\nFetching https://github.com/vapor/fluent-provider.git\nFetching https://github.com/SwiftyBeaver/SwiftyBeaver.git\nFetching https://github.com/vapor/socks.git\n")

**Comment by 0xTim** [comment]
@agordeev I suspect it's to do with SwiftyBeaver which is pointing to Vapor 2.0.0 and you are requesting 2.0.1. Set only your major versions for those that aren't Betas and it should work

**Comment by agordeev** [comment]
Figured out the reason: I had a deleted fork as a dependency (https://github.com/gperdomor/SwiftyBeaver-Vapor.git). Removing it from Package.swift didn't help, I had to remove Package.pins file to get vapor xcode -y working.

Hate SPM for very "informative" messages.
