### ISSUE TITLE
vapor xcode -y asks for Github username

### ISSUE THREAD

**Issue by agordeev** [vapor/vapor#1023]
<img width="483" alt="screen shot 2017-05-21 at 4 26 33 pm" src="https://cloud.githubusercontent.com/assets/2883524/26284404/0411bca0-3e43-11e7-9e6d-2688aff37e72.png">

It's impossible to enter anything, please note the cursor position. When I press Enter, I see `Generating Xcode Project...` message, which is executing forever.

Vapor version: 2.0.3.

**Comment by 0xTim** [comment]
@agordeev if you type `git remote -v` what do you get? Looks like you haven't cloned over SSH

**Comment by agordeev** [comment]
I got nothing. `vapor xcode -y` used to work recently.

**Comment by 0xTim** [comment]
If you run `swift package generate-xcodeproj`?

**Comment by agordeev** [comment]
Figured out the reason: I had a deleted fork as a dependency (https://github.com/gperdomor/SwiftyBeaver-Vapor.git). Removing it from Package.swift didn't help, I had to remove Package.pins file to get `vapor xcode -y` working.
