### ISSUE TITLE
PersistMiddleware persists on every request

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1024]
Currently when using the PersistMiddleware, it will persist the user if authenticated on every request. This then causes the `SessionPersistable` to reset the data on the session, which then sets `shouldCreate` to true.

The knock-on effect is that the SessionsMiddleware will recreate the cookie on every request. Not only will this have a potentially (very small) performance hit, it means that those who use the request in the CookieFactory to set different cookies (such as expiry date) will then have the custom cookie overwritten.

I would expect the `shouldCreate` to only be set when the session is first created.

**Comment by tanner0101** [comment]
I think the solution here could be only setting the cookie if `shouldCreate == true` AND there is no cookie already set.

**Comment by 0xTim** [comment]
How do you tell if a cookie has not been set? An expired session cookie will still exist and be sent with the request even though it isn't valid, so you'd have to check for that as well
