### ISSUE TITLE
Setting Cookie Name

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1026]
* Vapor Version: 2
* OS: MacOS
* OS Version: 10.12.4 
* Vapor Toolbox Version: 2.0.1

### Expected Behavior

Vapor should respect the Cookie Name that is passed into the `cookieFactory` on `SessionsMiddleware`

### Current Behavior

Regardless of what is set in the `cookieFactory`, the name used by the cookie is `vapor-session`. See below: 

```swift
let redisSessions = SessionsMiddleware(CacheSessions(redisCache)) { req -> Cookie in
    return Cookie(
        name: "vapor-auth",
        value: "",
        expires: Date().addingTimeInterval(60 * 60 * 24 * 7), // 7 days
        secure: false,
        httpOnly: true
    )
}
```

The above code still results in the cookie being named `vapor-session`, causing the Identifier of the session to be set differently on every request.

**Comment by 0xTim** [comment]
Yeah this was a slight oversight on my part and there is no easy way to fix it without breaking the API. Ideally you would pass the `cookieName` into the `CookieFactory` but I can't think of a way around this at the moment

**Comment by tanner0101** [comment]
We could at least throw/print an error if the cookie name and middleware name are different.
