### ISSUE TITLE
MYSQL_TYPE_JSON  error when building with mysqlProvider on Ubuntu 16.04 with MariaDB 10.1 

### ISSUE THREAD

**Issue by janslu** [vapor/vapor#1027]
------------------------------------------------------------------------------------------------------
                                                                                   Bug
------------------------------------------------------------------------------------------------------

* Vapor Version: 2.0.2
* OS: Linux
* OS Version: Ubuntu 16.04.2 LTS
* Vapor Toolbox Version: 2.0.3
* Swift: 3.1.1
* CTLS 1.0.1
### Expected Behavior

I'm using MariaDB 10.1 on my server instead of MySQL. I'm trying to build Vapor 2 using rather vanilla mysqlProvider configuration. I have installed  cmysql using apt get and I was successfully using vapor 1.5 application using similar functions...  

### Current Behavior

I get the following error when building

`root@bbwww2:/var/www/vapor/api# vapor build --release
Building Project [Failed]

Command:
build --enable-prefetching --configuration release

Error (1):
<unknown>:0: error: build had 1 command failures
swift-build: error: exit(1): /usr/bin/swift-build-tool -f /var/www/vapor/api/.build/release.yaml

Output:
Compile Swift Module 'Debugging' (1 sources)
Compile Swift Module 'SwiftyBeaver' (8 sources)
Compile Swift Module 'Bits' (19 sources)
Compile Swift Module 'libc' (1 sources)
Compile Swift Module 'Core' (23 sources)
Compile Swift Module 'Random' (6 sources)
Compile Swift Module 'PathIndexable' (2 sources)
Compile Swift Module 'Transport' (10 sources)
Compile Swift Module 'Console' (34 sources)
Compile Swift Module 'Node' (38 sources)
Compile Swift Module 'BCrypt' (9 sources)
Compile Swift Module 'Sockets' (22 sources)
Compile Swift Module 'Crypto' (13 sources)
Compile Swift Module 'TLS' (12 sources)
Compile CSQLite sqlite3.c
Compile Swift Module 'JSON' (9 sources)
Compile Swift Module 'Redis' (11 sources)
Compile CHTTP http_parser.c
Compile Swift Module 'SMTP' (21 sources)
Compile Swift Module 'MySQL' (11 sources)
Linking CHTTP
Compile Swift Module 'URI' (6 sources)
/var/www/vapor/api/.build/checkouts/mysql.git-1709669648610372950/Sources/MySQL/Field/Field+Variant.swift:14:24: error: use of unresolved identifier 'MYSQL_TYPE_JSON'
            if self == MYSQL_TYPE_JSON {
                       ^~~~~~~~~~~~~~~
CMySQL.MYSQL_TYPE_BLOB:1:12: note: did you mean 'MYSQL_TYPE_BLOB'?
public var MYSQL_TYPE_BLOB: enum_field_types { get }
           ^
CMySQL.MYSQL_TYPE_LONG:1:12: note: did you mean 'MYSQL_TYPE_LONG'?
public var MYSQL_TYPE_LONG: enum_field_types { get }
           ^
CMySQL.MYSQL_TYPE_SET:1:12: note: did you mean 'MYSQL_TYPE_SET'?
public var MYSQL_TYPE_SET: enum_field_types { get }
           ^
/var/www/vapor/api/.build/checkouts/mysql.git-1709669648610372950/Sources/MySQL/Bind/Bind+Node.swift:35:31: error: use of unresolved identifier 'MYSQL_TYPE_JSON'
                if variant == MYSQL_TYPE_JSON {
                              ^~~~~~~~~~~~~~~
CMySQL.MYSQL_TYPE_BLOB:1:12: note: did you mean 'MYSQL_TYPE_BLOB'?
public var MYSQL_TYPE_BLOB: enum_field_types { get }
           ^
CMySQL.MYSQL_TYPE_LONG:1:12: note: did you mean 'MYSQL_TYPE_LONG'?
public var MYSQL_TYPE_LONG: enum_field_types { get }
           ^
CMySQL.MYSQL_TYPE_SET:1:12: note: did you mean 'MYSQL_TYPE_SET'?
public var MYSQL_TYPE_SET: enum_field_types { get }
           ^

Toolchain:
/usr/bin/swift

Help:
Join our Slack where hundreds of contributors
are waiting to help: http://vapor.team

Error: Build failed.
`

It builds fine using the following command:
`swift build  -c release -Xswiftc -I/usr/local/mysql/include -Xlinker -L/usr/local/mysql/lib -Xswiftc -DNOJSON`

### How to Reproduce

Build a project that includes mysqlProvider on Linux 16.04 with MariaDB 10.1 installed instead of MySQL.

**Comment by tanner0101** [comment]
You need to include the `-Xswiftc -DNOJSON` if you are using a version of MySQL that does not support the `MYSQL_TYPE_JSON` column type. Looks like MariaDB 10.2 supports this.
