### ISSUE TITLE
Using RedisProvider for less than the value

### ISSUE THREAD

**Issue by king129** [vapor/vapor#1028]
* Vapor Version: 2.0.2
* OS: Mac Ubuntu
* OS Version:  Mac 10.12.4 Ubuntu 16.04
* Vapor Toolbox Version: 2.0.2

### Current Behavior

- I use the `redis-cli` a data store, but through the `try drop.cache.get (" ephemeral ")` out to nil
```
xxxxxxxxxxx> set ephemeral "ephemeral"
OK
xxxxxxxxxxx> get ephemeral
"ephemeral"
xxxxxxxxxxx> keys *
1) "king"
2) "ephemeral"
xxxxxxxxxxx>
```
- But with the following way is normal, but use `redis-cli` do not check the cli and `key` data for the `username`
```
try drop.cache.set("username", 42, expiration: Date(timeIntervalSinceNow: 60))
let value = try drop.cache.get("username")
print(value?.string)
```

**Comment by tanner0101** [comment]
Thanks for contributing!

This bug is missing the expected behavior. Please add a more clear description of what is going wrong here.
