### ISSUE TITLE
Using RedisProvider for less than the value 

### ISSUE THREAD

**Issue by king129** [vapor/vapor#1029]
- Vapor Version: 2.0.2
- OS: Mac Ubuntu
- OS Version: Mac 10.12.4 Ubuntu 16.04
- Vapor Toolbox Version: 2.0.2
### Current Behavior

![5924fca0ce199.png](https://ooo.0o0.ooo/2017/05/24/5924fca0ce199.png)

**Comment by vzsg** [comment]
Let's clarify something. You're storing a raw string in Redis, but in line 35, you expect it to be an `object`. That will never work.

**Comment by king129** [comment]
@vzsg 
```swift
let value = try drop.cache.get("ephemeral")?.string
print(value) // nil
```

**Comment by vzsg** [comment]
Okay. Second thing to check: adding the provider in code is one thing, but did you also update droplet.json? See the end of [this page](https://docs.vapor.codes/2.0/cache/overview/).

**Comment by king129** [comment]
@vzsg 
- `Config/droplet.json`
```
{
"cache": "redis"
}
```

**Comment by tanner0101** [comment]
@king129 try storing the value _from_ Vapor and then fetching it. It's likely you're connecting to different redis servers or databases.

**Comment by king129** [comment]
@tanner0101 
- "Ok" to find the problem, 2.0 the document inside a lot of Droplet sample written in vapor2.0.2 doesn't support, still hope to update
- For example the following code
```swift
drop.middleware += [
    PasswordAuthenticationMiddleware(User.self)
]
```
- Configuration and configuration files this way, it is easy to a problem, the document is not very clear, each component is not related to specific document

![592638149bdb2.png](https://ooo.0o0.ooo/2017/05/25/592638149bdb2.png)

**Comment by tanner0101** [comment]
Are you using the 2.0 docs? That looks like 1.0 code you are pasting in.

https://docs.vapor.codes/2.0/

**Comment by linqingmo** [comment]
```swift
let drop = try Droplet()

drop.preparations += [ExampleUser.self, ExampleToken.self]

let tokenMiddleware = TokenAuthenticationMiddleware(ExampleUser.self)
drop.middleware.append(tokenMiddleware)
```
This is code of 2.0 docs. But middleware is let value, how can we append a middleware here?

**Comment by king129** [comment]
@tanner0101 
![5927773fe5821.png](https://ooo.0o0.ooo/2017/05/26/5927773fe5821.png)

**Comment by tanner0101** [comment]
Oops, thanks for finding that. I'll create an issue on the `vapor/documentation` repo for that.
