### ISSUE TITLE
Make FileMiddleware's file serving logic reusable

### ISSUE THREAD

**Issue by vzsg** [vapor/vapor#1034]
# Enhancement

### Introduction

As downplayed as it is, FileMiddleware is a powerful class that can load/serve static files, add proper content type headers and enable caching through ETag/If-None-Match. It would be nice to make all this functionality available to any route handler or middleware, not just in this very specific error-handling scenario.

### Motivation

I was investigating how to implement a middleware that [serves a predefined file](https://gist.github.com/vzsg/3e693e459b7de6fc73493a73ecbed297) instead of returning a 404 error to support Angular's router, and found that the only way to have all the above listed functionality is to copy the guts of FileMiddleware.

When considering the Single Responsibility Principle, it makes sense to extract the actual file handling logic from FileMiddleware to an independent context and just delegate the call there. This way, other middleware (like mine above) can be reduced to a single function call; and developers can even serve static files in RouteHandlers.

Not to mention that other frameworks usually have a simple function to do the same – for example Express has [sendFile](https://expressjs.com/en/api.html#res.sendFile). Making this change would get Vapor closer to be in feature-parity.

### Proposed solution

I propose adding a new initializer to the Response class through an extension, that takes a file path.

### Code snippets

The extension:

```swift
public extension Response {
    public convenience init(filePath: String) throws {
        // ... FileMiddleware internals ...
        // https://github.com/vapor/vapor/blob/master/Sources/Vapor/File/FileMiddleware.swift#L20-L62
        guard
            let attributes = try? Foundation.FileManager.default.attributesOfItem(atPath: filePath),
            let modifiedAt = attributes[.modificationDate] as? Date,
            let fileSize = attributes[.size] as? NSNumber
        else {
            throw Abort.notFound
        }

        // ...
    }
}
```

Then FileMiddleware becomes:

```swift
public final class FileMiddleware: Middleware {
    // ... initializer omitted ...

    public func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        do {
            return try next.respond(to: request)
        } catch let error as AbortError where error.status == .notFound {
            // Check in file system
            var path = request.uri.path
            guard !path.contains("../") else { throw HTTP.Status.forbidden }
            if path.hasPrefix("/") {
                path = String(path.characters.dropFirst())
            }

            let filePath = publicDir + path
            return try Response(filePath: filePath)
        }
    }
}
```

### Impact

This is a purely additive change from an API standpoint.

**Comment by tanner0101** [comment]
Great idea. Let's shoot for getting this in Vapor 2.1.
