### ISSUE TITLE
structured data wrapper for view data

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1036]
Vapor 2 saw the addition of `makeRow()` and `makeJSON()` in models, making `Node` more of an in-between/generic data type. However, view contexts were forgotten in this transition and still rely on just `Node`. Something like a `ViewData: StructuredDataWrapper` could make the API for creating different representations of your models feel more uniform and minimize confusion about Node's purpose. It would also provide a convenient type for adding view-specific protocol extensions.

**Comment by LoganWright** [comment]
Would this be a breaking change? We could setup view to accept _any_ structured data wrapper and provide the view on top as a work around ...

**Comment by tanner0101** [comment]
I don't think it would. Hence 2.1 milestone.
