### ISSUE TITLE
Vapor University returns 502 Bad Gateway error

### ISSUE THREAD

**Issue by marc-medley** [vapor/vapor#1037]
Issue
-------
The [Vapor University](http://vapor.university) `http://vapor.university` link in the [README.md](https://github.com/vapor/vapor) currently  returns a page with "502 Bad Gateway", "nginx/1.9.3 (Ubuntu) error message.

Where is the appropriate place to report that `vapor.university` is not working?

**Comment by Aaron-A** [comment]
I get the same thing.
