### ISSUE TITLE
Can't Run Hello Vapor Project on Xcode

### ISSUE THREAD

**Issue by jsl303** [vapor/vapor#1038]
Here are the steps I took.  
Type "vapor new Hello" and then "y" in terminal.  
In Xcode, when I clicked run, it builds but doesn't run. Debug console is empty.  
When I executed "vapor build" and "vapor run" in the terminal, it runs though.  
I have Xcode 8.3.2, Swift 3.1, Vapor Toolbox 2.0.3, Vapor Framework 2.0.0.  
Thanks!

**Comment by Aaron-A** [comment]
@jsl303 Can you confirm that you selected "Run" see the attached image for an example. 

<img width="292" alt="screen shot 2017-05-26 at 11 59 32 pm" src="https://cloud.githubusercontent.com/assets/6710841/26517851/72841fd6-426f-11e7-9e6c-945d22933094.png">

**Comment by jsl303** [comment]
Thanks!!! That was what was missing! I don't remember ever checking run 
from the Scheme for my IOS/OSX projects. Maybe it's checked by default 
for those.
Would you be able to add the instruction to Xcode part of the 
documentation for beginners?
Thanks again!

**Comment by Aaron-A** [comment]
@tanner0101 @jsl303 Brings up a good point. We may want to add this to the documentation for beginners.

**Comment by LoganWright** [comment]
@Aaron-A great suggestion, submitted a PR to documentation 👍
