### ISSUE TITLE
MariaDB 10.2 - cannot restart app, exits with tableExistsError

### ISSUE THREAD

**Issue by janslu** [vapor/vapor#1040]
* Vapor Version: 2.0.3
* OS: Ubuntu 16.04.2
* OS Version: Ubuntu 16.04.2
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

I am running a simple app built on Vapor 2. Two models and MySQLProvider. Application starts fine for the first time. But each following run is causing a crash with the following error:

```
fatal error: Error raised at top level: MySQL Error: Table 'ratings' already exists
Identifier: MySQL.MySQLError.1050 (tableExistsError)
```

If I remove the table manually, it starts fine until another app restart/respawn. The same application works fine on MariaDB on my local OSX... 

### Current Behavior

Application crashes on second start... 

### How to Reproduce

I've had troubles getting vapor to work with MariaDB 10.1 and upgraded to MariaDB 10.2. mysqllibclient gave me some errors but got around it by symlinking from /usr/lib/libmysqlclient.so to /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18. It builds fine and starts OK. 

Preparations are fairly simple:

```
extension Rating: Preparation {
    /// Prepares a table/collection in the database
    /// for storing Posts
    static func prepare(_ database: Database) throws {
        try database.create(self) { rating in
            rating.id()
            rating.string("identyfikator")
            rating.int("sumaGlosow")
            rating.int("liczbaGlosow")
        }
    }
    
    /// Undoes what was done in `prepare`
    static func revert(_ database: Database) throws {
        try database.delete(self)
    }
}
```
I have no idea why it crashes so hard and doesn't use existing table data...

**Comment by vi4m** [comment]
What is the contents of 'Fluent' table(which holds history of preparations) ?

**Comment by janslu** [comment]
Two rows, same value for batch, which is different from my dev setup on my Mac...:

`1	Rating	1	2017-05-30 16:30:18	2017-05-30 16:30:18
2	Galeriavote	1	2017-05-30 16:30:18	2017-05-30 16:30:18
`

**Comment by tanner0101** [comment]
Moving to vapor/fluent.
