### ISSUE TITLE
support `text/javascript` header for JSON

### ISSUE THREAD

**Issue by piercifani** [vapor/vapor#1042]
* Vapor Version: 2.0
* OS: macOS
* OS Version: 10.12.5
* Vapor Toolbox Version: v1.0.9

### Expected Behavior

`Response.data` should always parse the HTTP's response body  correctly and make that data accessible via it's APIs.

### Current Behavior

Currently, when verifiying a user's FB token in order to provide some authentication functionality, it looks like FB's `debug_token` response is not being parsed correctly by `Response.data`

### How to Reproduce

Currently, this is how the code looks:

```
  private func handleFBLoginRequest(_ req: Request) throws -> ResponseRepresentable {

    guard
      let fbUserID = req.data["fb_user_id"]?.string,
      let fbToken = req.data["fb_token"]?.string else {
      throw Abort(.badRequest, reason: "No FB ID or Token given")
    }

    let fbResponse: Response
    do {
      fbResponse = try client.get("https://graph.facebook.com/v2.9/debug_token", query: [
        "input_token" : fbToken,
        "access_token": "SomeFacebookAppToken"
        ])
    } catch {
      throw Abort(.failedDependency, reason: "FB request failed")
    }

    print("FB debug_token \(fbResponse)")

    guard let dataResponse = fbResponse.data["data"] else {
      throw Abort(.failedDependency, reason: "Unknown FB Response")
    }

    guard let appID = dataResponse["app_id"]?.string, appID == self.fbAppID else {
      throw Abort(.failedDependency, reason: "FB App IDs don't match")
    }

    guard let userID = fbResponse.data["user_id"]?.string, userID == fbUserID else {
      throw Abort(.failedDependency, reason: "FB User IDs don't match")
    }

    return "Welcome!"
  }
```

Turns out that the print statement shows a correct response from FB:

```
- Version: 1.1.0
- Status: 200
- Headers:
	Transfer-Encoding: chunked
	ETag: "ec3206acdfa5d5cde59d63fb965568bcf3f6dbec"
	Content-Type: text/javascript; charset=UTF-8
	X-FB-Debug: N4Rl+UTTjgrnazir9Bdbz7VC4alREQWhr69u5ww6CRPzWeeP9MO9ihDI4S1S1VnteGTVwXlBo4xEqwarAXe55Q==
	Date: Mon, 29 May 2017 08:46:06 GMT
	x-fb-rev: 3050573
	Expires: Sat, 01 Jan 2000 00:00:00 GMT
	Pragma: no-cache
	x-fb-trace-id: CqbZhHjrRVY
	Connection: keep-alive
	Cache-Control: private, no-cache, no-store, must-revalidate
	Vary: Accept-Encoding
	facebook-api-version: v2.9
	Access-Control-Allow-Origin: *
- Body:
	{"data":{"app_id":"APPID","application":"Foo","error":{"code":190,"message":"Error validating access token: Session has expired on Friday, 26-May-17 13:00:00 PDT. The current time is Monday, 29-May-17 01:46:06 PDT.","subcode":463},"expires_at":1495828800,"is_valid":false,"scopes":["user_friends","publish_actions","public_profile"],"user_id":"USER ID"}}
```

But accessing `fbResponse.data` is always returning `nil`. I have tried with some sample requests to HTTPBIN or other sample HTTP APIs and those are being parsed correctly, but his FB response is not being handled correctly for some reason.

If I do a `let stringResponse = String.init(bytes: fbResponse.body.bytes!)`, this returns the escaped body like this:

`"{\"data\":{\"app_id\":\"APPID\",\"application\":\"Foo\",\"error\":{\"code\":190,\"message\":\"Error validating access token: Session has expired on Friday, 26-May-17 13:00:00 PDT. The current time is Monday, 29-May-17 01:46:06 PDT.\",\"subcode\":463},\"expires_at\":1495828800,\"is_valid\":false,\"scopes\":[\"user_friends\",\"publish_actions\",\"public_profile\"],\"user_id\":\"USER ID\"}}"`

Is there anything I'm missing here, like some configuration for the parser?

Thanks for this great FW and your time!

**Comment by piercifani** [comment]
Parsing manually the JSON seems to work:

```swift
import JSON

guard let bytes = fbResponse.body.bytes, let json = try? JSON(bytes: bytes) else {
  throw Abort(.failedDependency, reason: "FB request failed")
}

guard let dataResponse = json["data"] else {
  throw Abort(.failedDependency, reason: "Unknown FB Response")
}

// It works!

```

**Comment by vzsg** [comment]
The problem seems to be that the server returned the Content-Type header as `text/javascript`, but Vapor's JSON support _expects_ `application/json` instead.

For now, the manual parsing you found is pretty much the only way to work around this.

**Comment by piercifani** [comment]
😢 

Thanks for the explanation! Closing this issue

**Comment by tanner0101** [comment]
If this seems like something common, we could consider adding a check for that header as well.

**Comment by vzsg** [comment]
I support that idea.
