### ISSUE TITLE
Change default Primary Keys to bigint for MySQL and PostgreSQL

### ISSUE THREAD

**Issue by Ybrin** [vapor/vapor#1044]
### Introduction

I feel like the default primary key type should be bigint nowadays as the performance benefit of 32 bit integers are not big enough to justify the hassles when exceeding the maximum value of ints.

### Motivation

Currently there is no convenient way to generate bigint primary keys. The solution I am using right now is a small extension which does the following for primary key:

```Swift
database.custom("id", type: "BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT", optional: false, unique: true, default: nil)
```

as well as a few others as `foreignId` and `parent` conveniences with bigint.

@jmccartie submitted a pull request to rails last year which made bigint the default for all ids. His PR was merged a few months ago and is now included in Rails 5.1. ([Discussion with the community about that](https://github.com/rails/rails/issues/28386)).
Their decision was clear enough. It's just not worth it to use 32 bit integers. Neither for small projects nor for bigger projects. So they made it a convention so that others don't have to deal with it in the future.

I would like us (the vapor community) to think forward and help people who are not sure which type to use as primary key by making 64 bit integers a convention so they never have to deal with problems in the future. And we need to think that way because vapor is much faster than many other web frameworks and for that reason (beside other good reasons to use it) bigger companies are going to use it in the near future and we must be prepared for it.

### Proposed solution

As this is a decision we must make as the vapor community, I posted it here and not to the fluent library, but the actual changes should be made to fluent.

One solution would be to just change the `id()`, `foreignId(...)` and `parent(...)`
 methods inside the `Builder` protocol to use bigint.

### Impact

As this solution would just affect new migrations, there would not be any breaking changes and it could be released in a minor version update. New ids would become bigint and old ones would stay the default int.

To make the migration easier we could also provide a convenient way to change the old ids to bigint so they are consistent with the new ones.

### Alternatives considered

One alternative would be to provide `bigintId()`, `bigintForeignId(...)` and `bigintParent(...)` methods as a convenience for people who want to use bigint ids.
I personally like the idea of going the bigint way but even if we decide to don't change the default type of ids there should be at least some help for people who want to use them.

**Comment by tanner0101** [comment]
I like this idea. Since the changes only affect PostgreSQL and MySQL they should be made at the level of the appropriate drivers. (SQLite for instance does not have this issue).

https://github.com/vapor/mysql-driver
https://github.com/vapor-community/postgresql-driver

For MySQL, it would be as simple as modifying these two lines: https://github.com/vapor/mysql-driver/blob/master/Sources/MySQLDriver/MySQLSerializer.swift#L11-L14

Given that the Rails community has already made the move official I think it makes sense to follow suit.

**Comment by calebkleveter** [comment]
I believe that this is the code of interest for the PostgreSQL Driver:

https://github.com/vapor-community/postgresql-driver/blob/master/Sources/PostgreSQLDriver/PostgreSQLSerializer.swift#L69-L73

**Comment by RayHughes** [comment]
+1

**Comment by tanner0101** [comment]
This is done :)
