### ISSUE TITLE
vapor new project --template=api hangs when trying to initialize git repository

### ISSUE THREAD

**Issue by daVinciCEB** [vapor/vapor#1045]
* Vapor Version: 2.0.3
* OS: OS X El Capitan
* OS Version: 10.11.6
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

I am following along in the Hello World from the Vapor website. When I try to create a new Vapor project, I expected it to finish pretty quickly and be done.

### Current Behavior

After running vapor new project --template=api, the command Clones the Template, and Updates the Package Name perfectly. When attempting to Initialize the Git Repository, it gets stuck for a very long time, and so far has not finished.

### How to Reproduce

Follow the Hello World on the Vapor website.

**Comment by daVinciCEB** [comment]
I'm not sure if this might have any effect on the vapor new project creation, but I am running the commands in an already created git repository. Could this be problematic, if the Toolbox is trying to initialize a git repository in an already created repository?

**Comment by vzsg** [comment]
Your observation is correct, the toolbox tries to initialize a new Git repo. That might cause a conflict... Anyhow, you should just kill the process, it will not resolve with time.

Does it also get stuck if you run `vapor new` in a completely "clean" folder?

**Comment by daVinciCEB** [comment]
I tried running it in a completely clean repository, it's still getting stuck. Is there a way of running it verbosely to see exactly what command it's getting stuck on?

**Comment by LoganWright** [comment]
@daVinciCEB running w/ `--verbose` _should_ help, to clarify, some questions:

- did you install through brew?
- what toolbox version are you on?
- what system are you on?
- what git version?

I'm currently unable to reproduce this issue.

**Comment by calebkleveter** [comment]
What happens if you don't use the `--api` flag? The API template is already default, not using the flag should get you the same result.

**Comment by daVinciCEB** [comment]
Looks like it may have been an issue with my Xcode version. I was running version 8.1 yesterday, when the issue was happening. When I upgraded to 8.3 this morning, the issue was resolved, and the `vapor new` command was able to finish.
