### ISSUE TITLE
vapor xcode Fails

### ISSUE THREAD

**Issue by daVinciCEB** [vapor/vapor#1046]
* Vapor Version: 2.0.3
* OS: OS X El Capitan
* OS Version: 10.11.6
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

I am using the Vapor Toolbox to generate a new Xcode project file to open the code in Xcode.

### Current Behavior

The `vapor xcode` command fails with the error `swift-package: error: unknown command: --enable-prefetching`

### How to Reproduce

Run `vapor xcode` in the vapor project directory

**Comment by vzsg** [comment]
Toolbox 2.x requires you to have Swift 3.1, or in other words, Xcode 8.3 installed and active.

If, for any reason, you don't want to update, call `swift package generate-xcodeproj` manually instead of using the toolbox command.
