### ISSUE TITLE
Slack Archive Bot

### ISSUE THREAD

**Issue by LoganWright** [vapor/vapor#1049]
The 10k limit is creating issues for linking out and creating a reusable knowledge base ... look into a collection type bot that can create more permanent links for people to access.

**Comment by vzsg** [comment]
This might be useful: https://slackarchive.io

**Comment by tanner0101** [comment]
Nice find @vzsg. I've signed us up.

**Comment by LoganWright** [comment]
We've been officially added, and should start seeing data soon https://qutheory.slackarchive.io/
