### ISSUE TITLE
[BUG] query params and percent encoding

### ISSUE THREAD

**Issue by JustinM1** [vapor/vapor#1051]
* Vapor Version: 2.0.5
* OS: Mac
* Vapor Toolbox Version: 2.0.3

### Expected Behavior
Get query data from URI that has `&` encoded as `%26`

### Current Behavior
no value passed to request.query

Sending an sms message with twilio that has a link with multiple query params.  Twilio requires formURLEncoded data. This forces you to encode `&` to `%26`. When you receive the get request with the link, request.query does not contain those values.

`removingPercentEncoding`  from uri.query corrected the issue.

currently as a workaround I am doing this manually after receiving the get request:

`      guard let queryBytes = req.uri.query?.removingPercentEncoding?.makeBytes() else { throw Abort.badRequest }`
      
`let params = Node(formURLEncoded: queryBytes, allowEmptyValues: true)`

**Comment by LoganWright** [comment]
@JustinM1 can you log me some of the raw data that's coming in so we can better write tests around this? We should be able to log the full http message from twilio.

**Comment by JustinM1** [comment]
@LoganWright It's not really an issue with twillio. The issue is when the the link is used which has the `&` sign percentEncoded. Should be able to write up a test similar to this.

This one is normal and works as expected:

<img width="854" alt="screen shot 2017-06-05 at 8 43 00 am" src="https://cloud.githubusercontent.com/assets/18277828/26784352/22192146-49cb-11e7-8c96-db9a4bede893.png">

This one doesn't work, but should:

<img width="856" alt="screen shot 2017-06-05 at 8 44 42 am" src="https://cloud.githubusercontent.com/assets/18277828/26784376/3fd2ab44-49cb-11e7-81f4-8d5cd6c66cd3.png">

This gets the test passing:

<img width="943" alt="screen shot 2017-06-05 at 8 45 36 am" src="https://cloud.githubusercontent.com/assets/18277828/26784403/5ea2b2bc-49cb-11e7-9dfd-6361132beda5.png">

**Comment by vzsg** [comment]
Should the second fragment really work?
If it should, how would you encode an ampersand `&` in a _query value_, for example `a=b&c`?

**Comment by hhanesand** [comment]
@vzsg Wouldn't that just encode to `a%3Db%26c` where `%3Db` is `=` and `%26` is `&`?

**Comment by vzsg** [comment]
No, I mean the key is `a` and the value is `b&c`.

**Comment by tanner0101** [comment]
My understanding of URL percent encoding is that if you encode an ampersand it should be decoded into the _value_ of the previous key, not denote a new key starting.

**Comment by LoganWright** [comment]
Yea, @vzsg you're totally right. Percent encoding of an ampersand is used to allow ampersands within query values, if we were to act as this is suggesting, we would be actively working against the URI spec and not support valid use cases of percent encoded values.

`https://www.endpoint.com/path?id=123&anotherId=345%26thirdId=789` would rightly encode to:

```
[
    "id": "123"
    "anotherId": "345&thirdId=789"
]
```

The `&` represents a token and needs to be included explicitly.
