### ISSUE TITLE
[Bug] Query string parameters encoding []

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#1055]
* Vapor Version: 2.x

### Expected Behavior

Having defined a Node such as:

`["key": ["subKey1": "value1", "subkey2": "value2"]]`

I am expecting `try node.formURLEncoded().makeString()` to return:

`key[subkey1]=value1&key[subkey2]=value2`

### Current Behavior

`key=`

### How to Reproduce

See "Expected behaviour".

**Comment by LoganWright** [comment]
@valeriomazzeo moving this to engine repo since the bug is in that codebase 👍

**Comment by LoganWright** [comment]
I was wrong, it's in Vapor ... my bad

**Comment by valeriomazzeo** [comment]
well done 👍

**Comment by valeriomazzeo** [comment]
Just tried this on my project and my tests are failing.
I receive this:

`http://localhost:80/?page[number]=0&page[size]=10&key=value`

but in fact I am expecting this instead:

`http://localhost:80/?page%5Bnumber%5D=0&page%5Bsize%5D=10&key=value`

`[` and `]` should be encoded too

@LoganWright

**Comment by LoganWright** [comment]
@valeriomazzeo is that part of spec, can you link out where it specifies that those should be encoded?

**Comment by valeriomazzeo** [comment]
@LoganWright  of course.

I suppose you want to look here:
http://tools.ietf.org/html/rfc3986#section-3.4

from http://jsonapi.org/format/#fetching-pagination
>Note: JSON API is agnostic about the pagination strategy used by a server. Effective pagination strategies include (but are not limited to): page-based, offset-based, and cursor-based. The page query parameter can be used as a basis for any of these strategies. For example, a page-based strategy might use query parameters such as page[number] and page[size], an offset-based strategy might use page[offset] and page[limit], while a cursor-based strategy might use page[cursor].

>Note: The example query parameters above use unencoded [ and ] characters simply for readability. In practice, these characters must be percent-encoded, per the requirements in [RFC 3986](http://tools.ietf.org/html/rfc3986#section-3.4).

**Comment by valeriomazzeo** [comment]
@LoganWright I apologise for the inconvenience.

I was reading this https://stackoverflow.com/questions/39862893/should-links-in-json-api-responses-be-encoded and I think your first implementation was correct, they should be encoded only in a request and not in a response.
