### ISSUE TITLE
brew formula is outdated :(

### ISSUE THREAD

**Issue by muescha** [vapor/vapor#1058]
https://github.com/vapor/homebrew-tap/blob/master/vapor.rb is still on version `2.0.3` 
https://github.com/vapor/vapor/releases here is the current version `2.0.7`

**Comment by vzsg** [comment]
The formula is for the Vapor Toolbox, not the framework. And the latest toolbox release is [2.0.3](https://github.com/vapor/toolbox/releases).

**Comment by muescha** [comment]
But when i write `vapor --version` it prints the vapor version `2.0.3`

**Comment by calebkleveter** [comment]
Update the version you set Vapor to in your `Package.swift` and then run `vapor update`.
