### ISSUE TITLE
BUG: testResponse always uses .get

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#1062]
* Vapor Version: 2.0.5

I was trying to write a unit test to test a POST method on a resource, but my `index` function kept getting called. Digging into the code it appears that `testResponse` is hard coded to always use `.get` instead of the `method` passed in.

https://github.com/vapor/vapor/blob/master/Sources/Testing/Responder.swift#L15

**Comment by vzsg** [comment]
I think #1061 will solve this once it's merged and tagged.

**Comment by kgn** [comment]
@vzsg yep 👍
