### ISSUE TITLE
Vapor xcode fail

### ISSUE THREAD

**Issue by AlexChanX** [vapor/vapor#1065]
vapor xcode
Generating Xcode Project [Failed]
swift-package: error: rootManifestFileNotFound

Error: Could not generate Xcode project: swift-package: error: rootManifestFileNotFound

**Comment by vzsg** [comment]
Are you trying to run the command in the correct directory?
You need to be in the same folder as `Package.swift`.

**Comment by AlexChanX** [comment]
oh! thx!

**Comment by davidpasztor** [comment]
@vzsg It would be great if the Vapor docs could be updated with this information, since this is not mentioned anywhere in them and I faced the same issue thinking I could just generate an empty Xcode projects using `vapor xcode` without having to do anything else.

**Comment by vzsg** [comment]
That's a good idea IMHO.

**Comment by Depicus** [comment]
For those looking for "Package.swift" just create a new project first from the command like

`vapor new test001 --template=web`

then cd to test001 and run

`vapor xcode`

**Comment by pjcook** [comment]
This still did not work for me. I'm simply trying to setup a basic project and connect everything to vapor.cloud 
"vapor build" runs successfully, simply not "vapor cloud deploy"

**Comment by 0xTim** [comment]
@pjcook `vapor cloud deploy` issues will be different - what are you seeing?

**Comment by pjcook** [comment]
Running "vapor cloud deploy" in terminal it gets the project from Git then outputs:

Checkout branch 'dev' [Done]
Verifying base folder [Done]
Selected swift version: 3.1.0 [Done]
Selected swift version: 3.1.0 [Done]
Building vapor [Failed]
swift-build: error: rootManifestFileNotFound

Error: deploy failed.

**Comment by 0xTim** [comment]
Does the Git project have a `Package.swift` in? Is it definitely checked in etc?

**Comment by pjcook** [comment]
<groan> THANK YOU!! so much. I had accidentally pushed the files into Master and not the Dev branch. And vapor cloud deploy was looking at the empty Dev branch.

**Comment by mesas978** [comment]
$ swift --version
Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0

$ vapor cloud deploy
...
swift-package: error: Package requires minimum Swift tools version 5.2.0. Current Swift tools version is 3.1.0

**Comment by 0xTim** [comment]
@mesas978 Vapor Cloud shutdown in February. But that issues looks like because you're trying to build something with Swift 5.2 but your Package.swift doesn't specify a tools version so it's picking 3
