### ISSUE TITLE
'vapor run prepare --revert' misleading console output 

### ISSUE THREAD

**Issue by leonidas-o** [vapor/vapor#1067]
------------------------------------------------------------------------------------------------------
                                                                              Bug
------------------------------------------------------------------------------------------------------

* Vapor Version: 2.0.8
* OS: MacOS
* OS Version: 10.12.5
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

running `vapor run prepare --revert` should revert the database and display a proper information inside console.

### Current Behavior
After running the command and looking into the database, all tables are gone except `fluent` table. Don't know if it has been deleted and created new, or just all records deleted from it, but it exists and is empty. If this is intended, then it is just a bug in the output.
Console Output looks like:
```
Are you sure you want to revert batch 1 (Pivot<Category, Item>, ItemImage, Item, Category)?
y/n> y
inside setupLocalization
Usage: .build/debug/Run command

This command line interface is used to serve your droplet, prepare the database, and more.
Custom commands can be added by appending them to the Droplet's commands array.
Use --help on individual commands to learn more.

Commands:
           version Prints out the version of the Vapor framework being used.
            routes Logs the routes of your application
       dump-config Dumps the configuration for a given key.
             serve Boots the Droplet's servers and begins accepting requests.
  provider-install Installs Resources and Public files from providers

Use `.build/debug/Run command --help` for more information on a command.
Error: commandNotFound("prepare")
Error: Run failed.

```

### How to Reproduce

just run `vapor run prepare --revert` or `vapor run prepare --revert --all`

**Comment by tanner0101** [comment]
This should be fixable by adding `"prepare"` to the `"commands"`  array in your `droplet.json` file. 

Let me know if this is still an issue after!

**Comment by leonidas-o** [comment]
no, adding "prepare" to "commands" array fixed it.

**Comment by VinayakDeshpande11** [comment]
Getting this error on running :

> vapor run prepare

Fatal error: Error raised at top level: Configuration error: A Command named 'prepare' (chosen at 'commands' in Config/droplet.json) was not found (available: ).: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.74.1/src/swift/stdlib/public/core/ErrorType.swift, line 187

**Comment by twof** [comment]
What's your `package.swift` look like?

**Comment by VinayakDeshpande11** [comment]
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "App",
    products: [
        .library(name: "App", targets: ["App"]),
        .executable(name: "Run", targets: ["Run"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.1.0")),
        .package(url: "https://github.com/vapor/fluent-provider.git", .upToNextMajor(from: "1.2.0")),
        .package(url: "https://github.com/vapor-community/postgresql-provider.git",.upToNextMajor(from: "2.0.0"))
    ],
    targets: [
        .target(name: "App", dependencies: ["Vapor", "FluentProvider", "PostgreSQLProvider"],
                exclude: [
                    "Config",
                    "Public",
                    "Resources",
                ]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
    ]
)
