### ISSUE TITLE
post form bug

### ISSUE THREAD

**Issue by glennverhalle** [vapor/vapor#1068]
* Vapor Version: 2.1
* OS: OS X
* OS Version: 10.12.5
* Vapor Toolbox Version: 2.0.3

### Expected Behavior
Posting a form with empty fields shouldn't give warning/error in console

### Current Behavior

shows : 
POST /person
Found bad encoded pair hairColor= ... continuing
Found bad encoded pair eyeColor= ... continuing

for each of the empty fields.

### How to Reproduce

See attached file, drop the code into a fresh project and goto 0.0.0.0:8080/person

then push one of the buttons (save / duplicate) or enter when in a field. If a field is left empty then the error pops up

contact me on slack if you need more info @glenn_v
[Archive.zip](https://github.com/vapor/vapor/files/1077678/Archive.zip)

**Comment by LoganWright** [comment]
For now, we're going to be adding a *Workaround* so people can look at this while we investigate whether there are better solutions.

```Swift
import HTTP

extension Request {
    public func prepareData() {
        formURLEncoded = body.bytes.flatMap { Node(formURLEncoded: $0, allowEmptyValues: true) }
    }
}
```

Then, when the form should be interpreted as allowing `nil` values, simply call the function:

```swift
drop.post("foo") { req in 
    req.prepareData()
    ///
}
```
