### ISSUE TITLE
Passing a config file path dynamically

### ISSUE THREAD

**Issue by oleander** [vapor/vapor#1069]
I've embedded Vapor into a Cocoa app. Everything is working great, except that the predefined config path is hard coded and set to the environment the app was build on, in my case travis.io

```
> /Applications/BitBar.app/Contents/MacOS/BitBar                                                                                                                 
'Could not load config files from: /Users/travis/build/oleander/bitbar/Packages/Config/
Try using the configDir flag
ex: .build/debug/Run --configDir=/absolute/path/to/configs
The default hash should be replaced before using in production.
The default cipher should be replaced before using in production.
No command supplied, defaulting to serve...
Starting server on 0.0.0.0:8080
```

How do I pass an absolute path to my `servers.json` config file dynamically, either using `Droplet()` or `drop.run()`? Note that I can't use command line arguments like `--configDir`. `.app`s doesn't support default arguments, otherwise that would be an option.

If that's not possible, just changing the port using the below code would work. 

## Code

``` swift
let drop = try Droplet()
// ...
do {
  try drop.run()
} catch {
  /* Log */
}
```

## Setup

- Swift version: 3.1 (swiftlang-802.0.53 clang-802.0.42)
- Target: x86_64-apple-macosx10.9
- Vapor: 2.0.7

## Resources

- Source code: https://github.com/oleander/bitbar
- App: https://github.com/oleander/bitbar/releases/download/untagged-a8f0ed724701c6d6059f/BitBar.dmg

## Usage

``` swift
guard let path = Bundle.main.path(forResource: "servers", ofType: "json") else {
  preconditionFailure("No config file found")
}

let drop = try Droplet(configPath: path)
```

Thanks for your awesome work!

**Comment by oleander** [comment]
Tried a few things, but they don't seem to work.

This removes the error and it seems (from running `debug(config)`) that the config file is found, but its content is being ignored.

## Try 1

``` swift
guard let path = Bundle.main.resourcePath else {
  preconditionFailure("No config file found")
}
let config = try Config(arguments: ["--workDir=\(path)"])
let drop = try Droplet(config: config)
```

### Config

``` json
{
  "http": {
     "host": "0.0.0.0",
     "port": 8081
   }
}
```

### Resource folder (`path`)

```
├── Config
│   └── servers.json
```

### Output

```
The default hash should be replaced before using in production.
The default cipher should be replaced before using in production.
No command supplied, defaulting to serve...
Starting server on 0.0.0.0:8080
```

## Try 2

``` swift
let config = try Config(arguments: ["--config:servers.default.port=8888"])
let drop = try Droplet(config: config)
```

### Output

```
Could not load config files from: /Users/oleander/Documents/Projekt/bitbar/Packages/Config/
Try using the configDir flag
ex: .build/debug/Run --configDir=/absolute/path/to/configs
The default hash should be replaced before using in production.
The default cipher should be replaced before using in production.
No command supplied, defaulting to serve...
Starting server on 0.0.0.0:8080
```

What am I missing here? Remember trying this and a few other combinations a few weeks back but everything that's being passed in seems to be ignored.

**Comment by oleander** [comment]
Tried version `2.1.0` with the same result.

**Comment by LoganWright** [comment]
@oleander I think part of what's happening is that we're appending `Config/` to the end of the path so if you nest that folder, it should be ok ... alternatively, let's try manually creating the config:

```swift
var config = Config()
try config.set("server.hostname", "0.0.0.0")
try config.set("server.port", 8080)
let droplet = try Droplet(config: config)
```

**Comment by oleander** [comment]
@LoganWright Thanks for your answer. The config path is correct. It points to a directory containing a Config folder as shown in my output above. I also verified this in the terminal. Dumping the config `dump(config)` also suggests that it actually managing to read the servers.json, but that it is ignored.

The output from `dump(config)` shows that it reads everything in that directory (like my font files) so my guess is that the config file isn't suppose to be named `servers.json` but something else. The question is what.

Your example worked great btw. Thanks again.

**Comment by vzsg** [comment]
Are you trying to feed Vapor with `servers.json` (plural)?

It will be ignored, as since v2, the framework no longer supports configuring multiple HTTP servers, and is looking for `server.json` (singular) instead.

Its content should be a JSON object with `host`, `port` and `securityLayer`. (Like the contents of the `default` key in the old version.)
