### ISSUE TITLE
localhost:8080 loads jenkins instead of vapor page

### ISSUE THREAD

**Issue by nitishrana28** [vapor/vapor#1072]
I ran the Xcode project by following [Vapor startup](https://videos.raywenderlich.com/screencasts/509-server-side-swift-with-vapor-getting-started).
However, localhost:8080 loads jenkins. Jenkins was there on my system previously, but I uninstalled it. Still jenkins dashboard loads up.

**Comment by rafaelGuerreiro** [comment]
You should check if there isn't any jenkins (java) process running.

**Comment by nitishrana28** [comment]
Checked all running process using this command :

sudo lsof -i -P

Following are 2 processes on 8080 :

*******************

java       605  spadezfamily3  153u  IPv6 0x12ae328026261303      0t0    TCP localhost:8080 (LISTEN)

Run       3922  spadezfamily3    3u  IPv4 0x12ae328024a00e2b      0t0    TCP *:8080 (LISTEN)

*******************

How should I proceed ?

**Comment by rafaelGuerreiro** [comment]
kill -9 605

**Comment by nitishrana28** [comment]
Did so. Still jenkins loads.
Also tried restarting the system, still jenkins dashboard not going away. Tried with clearing the browser history as well.

**Comment by vzsg** [comment]
You should probably change the port your Vapor application listens on by editing the `port` key in `Config/server.json`. Move it to 8081 so they won't clash anymore.

**Comment by nitishrana28** [comment]
@vzsg Seems to be the working solution. Thanks.

Getting this at the end of Xcode console :

[Abort request error: Not Found] [Identifier: Vapor.Abort.notFound]

Why this might be ? Also, now 8081 is showing a blank page with no icon, something different from that in the video link.

**Comment by vzsg** [comment]
What video?

**Comment by linqingmo** [comment]
Are you using the latest version of Vapor? I saw the video [Vapor Startup](https://videos.raywenderlich.com/screencasts/509-server-side-swift-with-vapor-getting-started), it uses Vapor 1.
Maybe your url doesn't match with your routes? Maybe you forgot to add welcome.leaf? You can read docs at [docs.vapor.codes](https://docs.vapor.codes/2.0/).

**Comment by nitishrana28** [comment]
Yes I downloaded Vapor yesterday only.

**Comment by linqingmo** [comment]
Vapor 2 is very different from Vapor 1. So the video will not help you. If you get [Abort request error: Not Found] [Identifier: Vapor.Abort.notFound], maybe you need to check your routes.

**Comment by nitishrana28** [comment]
Alright. Will search for Vapor 2 resources then. We can close this issue.

**Comment by vzsg** [comment]
When you create a new project, it will be cloned from the "api-template". That would explain why you expect the fancy "It works" graphics, but get a 404 instead. (On the other hand, navigating to http://localhost:8081/info will give you some JSON.)

If you want to try a template with HTML, start the new project like this: `vapor new YourProjectName --template=web`.

And I'm closing the issue as I think we've resolved every question.

**Comment by 0xTim** [comment]
(If you are going to the site in a browser it will try and download a Favicon which is most likely the 404 - the error should contain the path it can't find)

**Comment by nitishrana28** [comment]
@linqingmo : Your official tutorials at http://vapor.university still have the Vapor 1 video links. I suggest these should be updated to Vapor 2.
Also, can I have links for tutorials for Vapor 2 ?

**Comment by linqingmo** [comment]
@nitishrana28 Sorry, I don't know where is tutorials for Vapor 2. You can read [docs](https://docs.vapor.codes/2.0/), or search examples on Github. Vapor 2 was released just one month, I think they need more time to complete docs and tutorials.
