### ISSUE TITLE
URI init default port added twice

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#1076]
Related to #1031 

This is still happening:

```
let uri = URI(scheme: "http", hostname: "localhost:80", query: "key=value")
print(uri.appendingPathComponent("test")
```

Expected behaviour:

`http://localhost:80/test`

Current behaviour:

`http://localhost:80:80/test`

**Comment by LoganWright** [comment]
@valeriomazzeo use this

```Swift
let uri = URI(scheme: "http", hostname: "localhost", port: 80, query: "key=value")
print(uri.appendingPathComponent("test")
```

👍

**Comment by valeriomazzeo** [comment]
Why not add the `parse(host:` function in the `URI` init instead?

This way you get all the cases covered.
