### ISSUE TITLE
Ubuntu Compilation Issue

### ISSUE THREAD

**Issue by hhanesand** [vapor/vapor#1087]
MacOS Sierra 10.12.5
Vapor Toolbox: 2.0.3
Vapor Framework: 2.1.2
Apple Swift version 4.0 (swiftlang-900.0.43 clang-900.0.22.8)
Target: x86_64-apple-macosx10.9

Ubuntu 16.04.2 LTS
Vapor Toolbox: 2.0.3
Vapor Framework: 2.1.2
Swift version 4.0-dev (LLVM a15decabe3, Clang d08a136083, Swift 2edf2b26d0)
Target: x86_64-unknown-linux-gnu

### Expected Behavior

The line `let substring = self.substring(with: range)` in `StructuredData+FormURLEncoded.swift` should compile correctly.

### Current Behavior

The above line successfully compiles on osx, but fails to compile on ubuntu with the following error :

> error: cannot convert value of type 'CountableRange<String.Index>' to expected argument type 'Range<String.Index>'

**Comment by tanner0101** [comment]
Swift 4 isn't supported yet. Track here https://github.com/vapor/vapor/issues/1088.
