### ISSUE TITLE
Apache2 Configuration

### ISSUE THREAD

**Issue by kylefrost** [vapor/vapor#1091]
I see that there is a preference for using Nginx, however myself and I'm sure others would like to use their already-configured Apache2 servers. Are there any plans to add an example/sample Apache2 configuration? Or is there a good place to start with this?

**Comment by tanner0101** [comment]
The method we use with Nginx is called "proxy pass". Looks like Apache has something similar: https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypass.

If that works for you, possibly we could use the Apache configuration code you end up with to create a docs page in the Deploy section.

**Comment by kylefrost** [comment]
Submitted PR to the vapor/documentation repo, [#197](https://github.com/vapor/documentation/pull/197)

**Comment by tanner0101** [comment]
Thanks! Closing here, track at: https://github.com/vapor/documentation/pull/197
