### ISSUE TITLE
a Client generated via droplet ClientFactoryProtocol close stream after some requests

### ISSUE THREAD

**Issue by zarghol** [vapor/vapor#1095]
* Vapor Version: 2
* OS: macOS
* OS Version: 10.12.6
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

A Client generated via the `droplet.client.makeClient` should never close the stream as it is a a res-usable connection, or re-open connection when called again.

### Current Behavior

The call to the same client after a moment fall to an error : `[Stream Error: The stream is closed] [Identifier: Transport.StreamError.closed]`

### How to Reproduce

1. create a client via `try self.client.makeClient(hostname: wsHostname,
                                          port: wsPort.port,
                                          securityLayer: .none)`

2. pass it to a controller (why not a ResourceRepresentable) 
3. Use it when the method is called (I use it on a GET method)

NB : My approach was to build a RESTFul back-end and a another front-end app. In order to retrieve datas from the back-end, I use the client when the GET is called to display it with leaf page. As I need the client fast and ready, I just build one at Routing time then pass it to my controller constructor.
Is this the good way to do this, do I have to pass the client factory instead the make a client each time ?

Thanks !!

**Comment by tanner0101** [comment]
@zarghol this is by design. We originally had logic to dynamically re-open connections, but handling edge cases there is much more difficult.

To solve this problem, you can create a custom class conforming to `ClientFactoryProtocol` or an extension on it that creates the client you need.

**Comment by AgoniNemo** [comment]
@tanner0101  I am same,Can I give me an example?     @zarghol hi,you problem solved?

**Comment by zarghol** [comment]
@AgoniNemo Hi, 
Indeed, I didn't find how to enable keep-alive in my vapor server, and I don't think it was enabled by default..
Here is what I have :

```
extension Droplet {
    var wsHostname: String {
        return self.config["app", "wsHostname"]?.string ?? ""
    }
    
    var wsPort: Int {
        return self.config["app", "wsPort"]?.int ?? 0
    }

    func clientForWS() throws -> ClientProtocol {
        return try self.client.makeClient(hostname: wsHostname,
                                          port: wsPort.port,
                                          securityLayer: .none)
    }
}
```
I originally created the client at route time, et passed it to my controller for calling the WS server to populate the leaf page of datas.
After that, the timeout didn't work, and with Postman, it appears that the server doesn't include keep alive in his headers.
I can't build an extension of `ClientFactoryProtocol` because my host and port are in the droplet conf, and I can't build the same client with just a client in the controller... So, should I pass the entire droplet to the controller. It doesn't seem good for the architecture of the app...
(💡 idea) I could build a `ClientFactoryProtocol` instance with default conf, so it could build directly a client when I need it

**Comment by AgoniNemo** [comment]
@zarghol thanks your example.I used Alamofire to make a request.but the use of Alamofire in the vapor can not get responseJSON.vapor does not seem to support the main thread running method.
