### ISSUE TITLE
Postgresql Index names on fields with the same name in different tables

### ISSUE THREAD

**Issue by dev-affective-de** [vapor/vapor#1096]
If postgresql is used as database, it is not possible to create indices for Vapor / Fluent datamodels on fields / properties that have the same name in different tables / datamodels. 
------------------------------------------------------------------------------------------------------

* Vapor Version: 2.1.2
* Fluent 2.1.2
* OS: MacOS
* OS Version: 10.12.6
* Vapor Toolbox Version: 2.0.3

### Expected Behavior
If the the name of the database table is added to the name of the index, it should work.

### Current Behavior
Only the name of the database field / property is used to creat the name of the index: _fluent_idx_nameOfProperty

### How to Reproduce
Create on two models an index on a field with the same name.

**Comment by 0xTim** [comment]
@dev-affective-de this is a Fluent error, which I also discovered today! Tracking here https://github.com/vapor/fluent/issues/300
