### ISSUE TITLE
don't omit parameter labels

### ISSUE THREAD

**Issue by ScottRobbins** [vapor/vapor#1097]
### Introduction

If you take a look at the `Responder+Helpers.swift` file, you can see the `request`, `makeRequest`, `get`...etc methods omit the parameter name for `uri`, `headers` and `body`. My proposal is that the `headers` and `body` parameter names should be required.

### Motivation

Omitting those parameter names leads to code that looks like this

```swift
let response = try? self.client.post("https://api.somecompany.com",
                                     query: [:],
                                     ["Content-Type": "application/x-www-form-urlencoded"],
                                     Body.data( Node(node: [
                                        "some_key": someValue,
                                        "another_key": anotherValue,
                                     ]).formURLEncoded()))
```

The body and header parameters aren't very clear wheat they are for, and it leaves you with some parameters which do have labels, and `headers` and `body` which don't. I understand the `uri` not needing a label, as it's the first argument and every request must point to a uri. 

Also, [the docs](https://vapor.github.io/documentation/http/client.html#post-as-json) show code snippets that would suggest this is already the case.

### Proposed solution

For those two, require the parameter names.

### Code snippets

So for that one the function definition would look like 

```swift
public func post(
        _ uri: String,
        query: [String: NodeRepresentable] = [:],
        headers: [HeaderKey: String] = [:],
        body: BodyRepresentable? = nil,
        through middleware: [Middleware] = []
    ) throws  -> Response { ... }
```

And that same call would then look like 

```swift
let response = try? self.client.post("https://api.somecompany.com",
                                     query: [:],
                                     headers: ["Content-Type": "application/x-www-form-urlencoded"],
                                     body: Body.data( Node(node: [
                                        "some_key": someValue,
                                        "another_key": anotherValue,
                                     ]).formURLEncoded()))
```

### Impact

This will break source and old projects will not compile until updating.

**Comment by tanner0101** [comment]
This was done to follow Swift's API guidelines for omitting parameter names where there is strong type information.

However, in practice, I agree that it doesn't look great. Vapor 3 will move toward including parameter labels where possible. I'll keep this issue open to track the progress of those changes.

**Comment by ScottRobbins** [comment]
@tanner0101 Would it be helpful for me to make PRs for any of this? I'm not sure if there are larger changes for Vapor 3 planned that would affect this.

**Comment by Joannis** [comment]
This is not a problem in Vapor 3 :)
