### ISSUE TITLE
 error: missing required module 'CTLS'

### ISSUE THREAD

**Issue by AgoniNemo** [vapor/vapor#1098]
* Vapor Version: 2.1.0
* OS Version: 10.12.5 (16F73)
* Vapor Toolbox Version:2.0.3

terminal
vapor new testVapor
vapor xcode -y

Created by the class UserModel inherited from NSObject
import Vapor

run

 error: missing required module 'CTLS'

**Comment by vzsg** [comment]
Do you have openssl installed with Homebrew?

**Comment by AgoniNemo** [comment]
@vzsg openssl 1.0.2l is already installed

**Comment by vzsg** [comment]
What about the second question?

**Comment by mhilscher** [comment]
I can reproduce the error

* Vapor Version: 2.1.0
* OS Version: 10.13 (17A315i)
* Vapor Toolbox Version:2.0.3
* home-brew location: /usr/local/bin/brew

**Comment by linqingmo** [comment]
brew tap vapor/homebrew-tap
brew install ctls

**Comment by mhilscher** [comment]
already tried that
just get a warning that ctls 1.0.0 is already installed

**Comment by AgoniNemo** [comment]
@vzsg brew location: /usr/local/bin/brew

**Comment by AgoniNemo** [comment]
It worked perfectly . take a look at this: https://github.com/vapor/vapor/issues/937

**Comment by jhoughjr** [comment]
still happens on toolchain 3.x.
