### ISSUE TITLE
Use of undeclared type 'Model'

### ISSUE THREAD

**Issue by AgoniNemo** [vapor/vapor#1100]
I follow [here](https://vapor.github.io/documentation/fluent/model.html#full-model), but get the error 
Use of undeclared type 'Model'

vapor vserion:2.1.0
vapor Toolbox vserion:2.0.3
swift version:3.1 (swiftlang-802.0.53 clang-802.0.42)

**Comment by AgoniNemo** [comment]
like this:
![error](https://user-images.githubusercontent.com/13228978/28952846-92d2592e-7906-11e7-8ce1-cef35b5ea1f2.png)

**Comment by linqingmo** [comment]
Do you have import https://github.com/vapor/fluent-provider.git?
The doc you read is Vapor 1.5 not Vapor 2.
https://docs.vapor.codes/2.0/

**Comment by AgoniNemo** [comment]
thanks,The problem is solved
