### ISSUE TITLE
Performance regression on Linux in vapor 2.x

### ISSUE THREAD

**Issue by vi4m** [vapor/vapor#1101]
* Vapor Version: 2.1.2
* OS: Ubuntu
* OS Version: 16.04 (from Docker)

Vapor 2.1.2 on Ubuntu 16.04  gets 150 reqs/sec when tested on simple "plain text" benchmark, tested with default and none middlewares - it doesn't matter. It is more than 30x slower than previous versions.

<img width="604" alt="zrzut_ekranu_2017-08-02_o_12 10 22" src="https://user-images.githubusercontent.com/552398/28967770-fabb3e14-791c-11e7-8595-8b44e51e25a0.png">

<img width="240" alt="zrzut_ekranu_2017-08-02_o_12 11 38_480" src="https://user-images.githubusercontent.com/552398/28967774-004128c6-791d-11e7-8608-031feacc3fb8.png">

I tested it with `-c release`.

Also, on the same Ubuntu system, version 1.5.15 is 33 times faster:

<img width="912" alt="zrzut ekranu 2017-08-04 o 14 23 52" src="https://user-images.githubusercontent.com/552398/28968513-93a80122-7920-11e7-82f9-477d5cc0bccb.png">

 I run everything in Docker containers, so overhead is there, but comparison between versions gives a hint that it's a bug somewhere / regression.

**Comment by Andrewangeta** [comment]
Good grief my confidence is dwindling 😔

**Comment by vzsg** [comment]
I'm getting very similar numbers with the same code, 4 cores and 2 GB RAM dedicated to Docker.

**Comment by vzsg** [comment]
Okay, the lumberjack method works: performance went south between Engine 2.0.0 and Engine 2.1.0. I'm hacking at it to find which version exactly...

**Comment by vzsg** [comment]
Found it: https://github.com/vapor/engine/releases/tag/2.0.3

**Comment by tanner0101** [comment]
Closing here so we can track https://github.com/vapor/engine/issues/153

**Comment by tanner0101** [comment]
This appears to be an issue w/ `wrk`. Check out https://github.com/vapor/engine/issues/153#issuecomment-320798569.
