### ISSUE TITLE
Request.json Cannot read

### ISSUE THREAD

**Issue by AgoniNemo** [vapor/vapor#1102]
* Vapor Version: 2.1.0
* OS Version: 10.12.5 (16F73)
* Vapor Toolbox Version:2.0.3

![json](https://user-images.githubusercontent.com/13228978/29010742-0abd3e6c-7b60-11e7-8bbe-45ab5c9df862.png)

json is nil.but data["name"] has value

**Comment by vzsg** [comment]
`request.json` is *not* supposed to be Any. Vapor has its own JSON structure (which wraps Node), so you should be accessing the name inside the JSON as `json?[“name”]?.string` here.

However, make sure that the client is actually sending JSON, not form-urlencoded values.

**Comment by tanner0101** [comment]
Check out https://docs.vapor.codes/2.0/json/overview/. If you have any specific issues/bugs relating to JSON please feel free to reopen.
