### ISSUE TITLE
extend siblings() method for fetching siblings from current Category and its children

### ISSUE THREAD

**Issue by leonidas-o** [vapor/vapor#1103]
### Introduction

When nesting models, e.g. a model `Category` which can have multiple children and depths, think of a navigation like: `/parent/child1/sub-child1`.
Matching items to a category using a model `Item`, the siblings pivot table should have only one entry for e.g. `Item` in `sub-child1`. Now using fluents `siblings()` method from the `parent` category should fetch all items for `parent`, `child1` and `sub-child1`. So always the current category plus all its children.

### Motivation

The pivot tables would NOT require an entry for each, in this case `item-category` relation, so they wouldn't get bloated so fast.

### Proposed solution

The `siblings()` method could make use of implemented helper functions. Maybe introduce `Nestable` and to conform to it, you have to implement methods for:
`let childrenCategories: Children<Category, Category> = children()` and `let parentCategory: Parent<Category, Category> = parent(id: try Identifier(node: categoryId))`.
When conforming to `Nestable`, 
`let items : Siblings<Category, Item, Pivot<Category, Item>> = siblings()` could go through all given Categories and look up all items.
So if we use `siblings()` from `parent` it would get all items from the pivot for `parent` id, get the children categories from the helper method and use them to get the other items.

**Comment by tanner0101** [comment]
@leonidas-o thanks for the feature request! Although I'm not entirely sure what you mean by this. Could you provide an example of another ORM that does this and also include an "expected" and "actual" so I better understand what Fluent is missing.

Additionally, closing this here since it should be created on vapor/fluent. Please create there w/ the add'l info. Thanks!
