### ISSUE TITLE
SMTP GMail client bug

### ISSUE THREAD

**Issue by Diiaablo95** [vapor/vapor#1108]
------------------------------------------------------------------------------------------------------
SMTP GMail client bug
------------------------------------------------------------------------------------------------------

* Vapor Version: 2
* OS: OS X
* OS Version: Sierra
* Vapor Toolbox Version: 2.0.3

### Expected Behavior

I wanna create and use a SMTP client for GMail.

### Current Behavior

```
let mailer = SMTPMailer.makeGmail(with: SMTPCredentials(user: my_email, pass: my_pass))

//Create the email

do {
    try mailer.send(emailToSend)
    print("Email sent.")
} catch let smtpError as SMTPClientError {
    print("Error: \(smtpError)")
}
```

This is the error I am getting:

**Error: invalidGreeting(code: -1, greeting: "")**

### How to Reproduce

Just follow the lines above, and you should be seeing the same error.

**Comment by tanner0101** [comment]
Thanks for reporting. Track the issue here: https://github.com/vapor/engine/issues/138
