### ISSUE TITLE
How to use PostgreSQL transaction in vapor

### ISSUE THREAD

**Issue by AgoniNemo** [vapor/vapor#1113]
I used the vapor in the [postgresql](https://github.com/vapor-community/postgresql-provider) ,I want to save a lot of data at once ,but I don't how to use postgresql transaction,Who can give an example.

**Comment by vzsg** [comment]
The Fluent `Database` classes have a `transaction` method for this. You need to give it a closure with all the database operations you want to perform inside a single transaction. It's important that all of these calls must use the connection you get as the closure's parameter.

For example, if you have an array of Post models, inserting them in one transaction looks like this:

```swift
let posts: [Post] = ... // your lot of data

database.transaction { conn in
    let query = try Post.makeQuery(conn)
    posts.forEach { post in
        try query.save(post)
    }
}
```

**Comment by AgoniNemo** [comment]
Thank you, that's exactly what I want
