### ISSUE TITLE
Status code 200 == not found?

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1114]
* Vapor Version: 2.2.0
* OS: macOS
* OS Version: 10.13
* Vapor Toolbox Version: No

### Expected Behavior

You create a droplet and open a page that is not registered to a router. You get a 404 not found.

### Current Behavior

The 404 page has a status code 200.

### How to Reproduce

Create a droplet and go to a route that does not exist.

**Comment by tanner0101** [comment]
I can't reproduce this. https://github.com/vapor/vapor/pull/1115

**Comment by Joannis** [comment]
Well, I'm getting this:

<img width="759" alt="screen shot 2017-08-11 at 15 56 56" src="https://user-images.githubusercontent.com/1951674/29232237-d6cdf5e0-7eea-11e7-9479-f6050f4bbbc5.png">

**Comment by vzsg** [comment]
I guess that's because the test @tanner0101 wrote tests the Droplet's default behavior, but incorrect behavior is actually caused by ErrorMiddleware (which renders the fancy error page on the screenshot).

**Comment by Joannis** [comment]
Isn't droplet's default behaviour including middleware?

**Comment by vzsg** [comment]
Not if it was instantiated with `Droplet()`, I think.
