### ISSUE TITLE
The model uses the difference between database and drop using database

### ISSUE THREAD

**Issue by AgoniNemo** [vapor/vapor#1116]
The model uses the difference between database and drop using database

example：

```
try VideoModel.database?.transaction({ (conn) in
                    let query = try VideoModel.makeQuery(conn)
                    try videos.forEach { v in
                        try query.save(v)
                    }
                })
```
and
```
try drop.database?.transaction{ conn in
                    let query = try VideoModel.makeQuery(conn)
                    try videos.forEach { v in
                        try query.save(v)
                    }
                }
```

**Comment by 0xTim** [comment]
How are you preparing the `VideoModel`?

**Comment by AgoniNemo** [comment]
@0xTim follow [here](https://docs.vapor.codes/2.0/fluent/getting-started/) to create.  I want to know the difference between the two

**Comment by 0xTim** [comment]
@AgoniNemo are you saying that the two different code snippets are using different databases or are you saying that you just want to know what the difference between the two code snippets is?

**Comment by AgoniNemo** [comment]
@0xTim I just want to know the difference between the two codes

**Comment by 0xTim** [comment]
I think there isn't actually much difference at all. They should both do exactly the same thing. The difference would be if `VideoModel` was using a different database than the `Droplet` (which is a possible case).

**Comment by tanner0101** [comment]
@AgoniNemo when `VideoModel` is prepared (during application init) the `.database` property will be set to `drop.database`. This is done so that you can call `VideoModel.makeQuery()` without needing access to the droplet. 

The static `.database` property is slated for removal in Fluent 3.
