### ISSUE TITLE
How to use vapor upload files

### ISSUE THREAD

**Issue by AgoniNemo** [vapor/vapor#1117]
The following is the code that uses Alamofire:

```
Alamofire.upload(multipartFormData: { (multipartFormData) in
            
            multipartFormData.append(token.data(using: .utf8)!, withName: "token")
            multipartFormData.append(image!, withName: "file", fileName: "pic", mimeType:"image/jpg")
            
        }, to: "http://up.qiniu.com") { (encodingResult) in
            
            switch encodingResult {
            case .success(let upload, _, _):
                upload.responseJSON { response in
                    debugPrint(response)
                }
            case .failure(let encodingError):
                print(encodingError)
            }
 }
```

Use vapor how to do, give an example?

**Comment by vzsg** [comment]
Your code would be roughly equivalent to:

```swift
// some dummy data, replace with your real token and real image data
let token = "THISISNOTAREALTOKEN"
let fileData = try DataFile().read(at: "sample.jpg")

let request = Request(method: .post, uri: "http://up.qiniu.com")

request.formData = [
    "token": Field(name: "token", filename: nil, part: Part(headers: [:], body: token.bytes)),
    "file": Field(name: "file", filename: "pic", part: Part(headers: ["Content-Type": "image/jpeg"], body: fileData))
]

let response = try client.respond(to: request)
```

**Comment by AgoniNemo** [comment]
@vzsg  How to get "client"？In the main.swift file to get "Droplet" object?

**Comment by 0xTim** [comment]
@AgoniNemo you should pass in the `client` from the `Droplet` into wherever you need it. Global Droplets/clients are a bad idea, makes testing a nightmare

**Comment by AgoniNemo** [comment]
@0xTim look like [this](https://stackoverflow.com/questions/42008299/struggling-with-vapor-client/42009305#42009305)?

**Comment by 0xTim** [comment]
No have you init look something like `init(client: ClientProtocol)` and then call it with `let myController = MyController(client: drop.client)`

**Comment by AgoniNemo** [comment]
@0xTim but using `drop.client` will get an error：
`Stream Error: The stream is closed\n\nIdentifier: Transport.StreamError.closed`

**Comment by 0xTim** [comment]
@AgoniNemo which client are you using? You could try switching to the Foundation client and see if that works

**Comment by AgoniNemo** [comment]
@0xTim you mean using the URLSession ？

**Comment by 0xTim** [comment]
No there's a built in Client based off of Foundation that you could try. You can change it in your `droplet.json`

**Comment by AgoniNemo** [comment]
finally I gave up using droplet .
