### ISSUE TITLE
Using Vapor with High Sierra 

### ISSUE THREAD

**Issue by kavink** [vapor/vapor#1120]
* Vapor Version: 2.0.4
* OS: Mac OS
* OS Version: 10.13
* Vapor Toolbox Version:

### Expected Behavior

Should be able to install and run Vapor on High Sierra 

### Current Behavior

Check vapor returns error : ```eval "$(curl -sL check.vapor.sh)"```

Also API template returns
```
Error (1):
error: missingKey("object")
```

### How to Reproduce

Install latest Mac OS beta.
Install Vapor via homebrew
run following command for error : ``` eval "$(curl -sL check.vapor.sh)" ```
Create a new app Template:``` vapor new my-app --template=api```
then run to see error : ``` $ vapor build && vapor run```

**Comment by 0xTim** [comment]
@kavink make sure you have upgraded your version/installed `ctls` from the Vapor tap, which you will need to map to the new OpenSSL location on High Sierra

**Comment by kavink** [comment]
@0xTim I have this one installed```vapor/tap/ctls 1.1.1``` is there a newer version ?

**Comment by 0xTim** [comment]
No that looks ok

So if you run `swift build` what is the full output?

**Comment by kavink** [comment]
```
⟩ swift
Welcome to Apple Swift version 3.1 (swiftlang-900.0.13 clang-900.0.13). Type :help for assistance.
```

**Comment by 0xTim** [comment]
@kavink did you definitely run `swift build`? That looks like the output from just `swift`

**Comment by kavink** [comment]
@0xTim Sorry I misunderstood your request .

```
⟩ swift build
error: missingKey("object")
```

**Comment by 0xTim** [comment]
@kavink that's the entire output? 🤔 that doesn't seem right
What about `swift package update`?

**Comment by kavink** [comment]
@0xTim Yes, That is the total output. Yeah even I was confused why it barfs out immediately .

```
⟩ swift package update
error: missingKey("object")
```

**Comment by vi4m** [comment]
Looks like broken build or `.build/` directory - can you remove `rm -rf .build` dir  and re-run `swift build` ?

**Comment by 0xTim** [comment]
@kavink Try @vi4m's solution, otherwise it sounds like a dodgy Swift install rather than a Vapor issue. If you are still stuck, try creating a 'Hello World' SPM project and seeing if that works?

**Comment by cyupa** [comment]
@0xTim seems to be right. I had the same issue but then I reinstalled the swift 3.1.1 toolchain and the did a `pip install six` which was messing with lldb. Everything working fine now.

**Comment by miroslavkovac** [comment]
I updated yesterday to High Sierra (not beta) and since then my project doesn't compile. I am getting the following error:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
.../.build/checkouts/ctls.git-9210868160426949823/shim.h:4:10: error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^
.../.build/checkouts/crypto.git-7980259129511365902/Sources/Crypto/Cipher/Cipher+Method.swift:1:8: error: could not build Objective-C module 'CTLS'
import CTLS
       ^
```

I tried deleting all SPM checkouts and repositories and re-downloading them but nothing helped so far.

**Comment by tanner0101** [comment]
@miroslavkovac try doing `brew install vapor/tap/ctls`, `brew upgrade vapor/tap/ctls`

**Comment by miroslavkovac** [comment]
Interesting thing is that I tried setting the `-DXcode -I/usr/local/opt/openssl/include` and `-L/usr/local/opt/openssl/lib` like it was suggested in one other thread, and is solved the problem, but recently it started working even without those flags (even after deleting .build folder and DerivedData).  It looks like it just needed one successful pass, and since then it works again. If I find out more, I will post my findings here.

**Comment by tanner0101** [comment]
Great, thanks!
