### ISSUE TITLE
Vapor 3 "Route" objects

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1137]
When creating a route, return a `Route` object. You could attach metadata to this `Route` such as a description, example requests, expected Requests/Responses and the supported content-types (like `application/json`). The goal would be to create a single source of truth for your backend, which you could export to APIBlueprint, Swagger and other API formats.

Most of the metadata would be implemented in libraries by extending the Route's storage and adding helper methods.

The route would also include the closure handler, middleware, method, route and possible other relevant routing data.

**Comment by steffendsommer** [comment]
I'm a big fan of this suggestion. Keeping external API documentation in sync with one's implementation is an (unnecessary) hassle. I could perhaps help in on this if you're interested.

**Comment by Joannis** [comment]
I'm considering this a possible goal for Vapor 3. But I'll definitely contact you on slack if/when I get to implementing this.

**Comment by tanner0101** [comment]
We've laid the groundwork for this by making `Route: Extendable`. It should be easy for us (or third parties) to build all sorts of functionality on top.
