### ISSUE TITLE
vapor socket

### ISSUE THREAD

**Issue by sunnyNH** [vapor/vapor#1148]
If I use the ios InputStream link vapor socket is always fail, server error: error: dispatch (HTTP) ParserError) invalidMessage), is how to handle it in vapor

**Comment by Joannis** [comment]
Hello @sunnyNH, could you provide some example code? I'm not sure how you're trying/managing to link this.

**Comment by sunnyNH** [comment]
server
import HTTP
import WebSockets
import Transport

final class MyResponder: Responder {
    func respond(to request: Request) throws -> Response {
        return try request.upgradeToWebSocket { ws in
            print("[ws connected]")
            
            ws.onText = { ws, text in
                print("[ws text] \(text)")
                try ws.send("🎙 \(text)")
            }
            
            ws.onClose = { _, code, reason, clean in
                print("[ws close] \(clean ? "clean" : "dirty") \(code?.description ?? "") \(reason ?? "")")
            }
        }
    }
}

let port = 8080
let server = try TCPServer(scheme: "", hostname: "127.0.0.1", port: Port(port), listenMax: 1)

print("Connect websocket to http://localhost:\(port)/")
try server.start(MyResponder()) { error in
    print("Got server error: \(error)")
}

**Comment by sunnyNH** [comment]
ios:
//
//  TcpManager.swift
//  MacOs-YunIM
//
//  Created by 牛辉 on 2017/4/1.
//  Copyright © 2017年 Niu. All rights reserved.
//

import Cocoa
class TcpManager :NSObject, StreamDelegate {
    
    static let share = TcpManager()
    private override init() {}
    var inputStream     :   InputStream?
    var outputStream    :   OutputStream?
    var receiveLock     :   NSLock?          = NSLock()
    var sendLock        :   NSLock?          = NSLock()
    //是否还有未发送的数据
    var noSendData      :   Bool             = true
    var receiveBuffer   :   NSMutableData?   = NSMutableData()
    var sendLastBuffer  :   SendBuffer?      = SendBuffer()
    var sendBuffers     :  [SendBuffer]?     = [SendBuffer]()
    //MARK: 创建socket链接
    func connect(_ ip: String ,_ port: Int32,_ status: Int = 1) {
        
        receiveLock = NSLock()
        sendLock    = NSLock()
        receiveBuffer = NSMutableData()
        sendBuffers   = [SendBuffer]()
        sendLastBuffer = SendBuffer()
        
        Stream.stream(ip, port, input: &inputStream, output: &outputStream)
        inputStream?.delegate = self
        outputStream?.delegate = self
        inputStream?.schedule(in: RunLoop.current, forMode: RunLoopMode.defaultRunLoopMode)
        outputStream?.schedule(in: RunLoop.current, forMode: RunLoopMode.defaultRunLoopMode)
        inputStream?.open()
        outputStream?.open()
    }
    //MARK: 结束socket链接
    func disconnect() {
        receiveLock = nil
        sendLock    = nil
        inputStream?.close()
        outputStream?.close()
        inputStream?.remove(from: RunLoop.current, forMode: RunLoopMode.defaultRunLoopMode)
        outputStream?.remove(from: RunLoop.current, forMode: RunLoopMode.defaultRunLoopMode)
        inputStream = nil
        outputStream = nil
        
        receiveBuffer  = nil
        sendBuffers    = nil
        sendLastBuffer = nil
    }
    func stream(_ aStream: Stream, handle eventCode: Stream.Event) {
        switch eventCode {
        case Stream.Event.openCompleted:// 建立连接完成
            openCompleted()
            break
        case Stream.Event.endEncountered:// 结束事件
            break
        case Stream.Event.errorOccurred:// 发生错误
            break
        case Stream.Event.hasBytesAvailable://接受数据
            receiveData()
            break
        case Stream.Event.hasSpaceAvailable://发送数据
            hasSpaceAvailable(aStream)
            break
        default: break
            
        }
    }
    func receiveData(){
        var buffer = [UInt8](repeating: 0, count: 1024)
        let len = inputStream?.read(&buffer, maxLength: buffer.count)
        if let len = len {
            if len > 0 {
                receiveLock?.lock()
                receiveBuffer?.append(buffer, length: len)
                while (receiveBuffer?.length)! >= 16 {
                    var range = NSRange(location: 0, length: 16)
                    let headerData = receiveBuffer!.subdata(with: range)
                    var inputData = DataInputStream(headerData as NSData)
                    let dataLen = inputData.readInt()
                    if dataLen > Int32(receiveBuffer!.length) {
                        //如果协议头里面包长大于buffer长度 说明数据还没有接收完
                        break
                    }
                    _               = inputData.readShort()
                    _               = inputData.readShort()
                    let serviceId   = inputData.readShort()
                    let commandId   = inputData.readShort()
                    let reserved    = inputData.readShort()
                    _               = inputData.readShort()
                    SLog("收到信息 服务id=\(serviceId) 命令id=\(commandId) 序列号=\(reserved)")
                    range = NSRange(location: 16, length: dataLen - 16)
                    let loadData = receiveBuffer!.subdata(with: range) as NSData
                    let remainLen = Int32((receiveBuffer?.length)!) - dataLen
                    range = NSRange(location: Int(dataLen), length: Int(remainLen))
                    let remainData = receiveBuffer?.subdata(with: range)
                    receiveBuffer?.setData(remainData!)
                    if loadData.length > 0 {
                        APIRouter.manager.receive(loadData, (Int(serviceId),Int(commandId),Int(reserved)))
                    }
                    receiveLock?.unlock()
                }
            }
        } else {
            SLog("没有数据")
        }
    }
    //MARK: 发送数据
    func send(_ data: NSData) {
        sendLock?.lock()
        if noSendData {//如果没有未发送的数据
            let p = data.bytes.assumingMemoryBound(to: UInt8.self)
            SLog(data.length)
            let lenght = outputStream?.write(p, maxLength: data.length)
            if let len = lenght , len < data.length {//如果写入的数据小于数据长度
                let lastData = data.subdata(with: NSMakeRange(len, data.length-len))
                sendLastBuffer = SendBuffer(data: lastData)
                sendBuffers?.append(sendLastBuffer!)
            }
            sendLock?.unlock()
            return
        }
        if let lastBuffer = sendLastBuffer {
            let len = lastBuffer.length
            if len < 1024 {
                sendLastBuffer?.append(data as Data)
                sendLock?.unlock()
                return
            }
        } else {
            sendLastBuffer = SendBuffer(data: data as Data)
            sendBuffers?.append(sendLastBuffer!)
            sendLock?.unlock()
        }
    }
    //MARK: 发送数据时的回调 处理发送后一些异常情况
    private func hasSpaceAvailable(_ aStream: Stream) {
        sendLock?.lock()
        if let count = sendBuffers?.count , count == 0 {
            noSendData = true
            sendLock?.unlock()
            return
        }
        if  let sendBuffer = sendBuffers?[0] {
            if sendBuffer.length == 0 {
                if sendBuffer == sendLastBuffer {
                    sendLastBuffer = nil
                }
                sendBuffers?.removeLast()
                noSendData = true
                sendLock?.unlock()
                return;
            }
            let len = (sendBuffer.length - sendBuffer.consumeLen >= 1024) ? 1024 : sendBuffer.length - sendBuffer.consumeLen
            if len == 0 {
                if sendBuffer == sendLastBuffer {
                    sendLastBuffer = nil
                }
                sendBuffers?.removeLast()
                noSendData = true
                sendLock?.unlock()
                return;
            }
            let p = sendBuffer.bytes.assumingMemoryBound(to: UInt8.self) + sendBuffer.consumeLen
            if let sendLen = outputStream?.write(p, maxLength: len) {
                sendBuffer.consume(sendLen)
            }
            if sendBuffer.length == 0 {
                if sendBuffer == sendLastBuffer {
                    sendLastBuffer = nil
                }
                sendBuffers?.removeLast()
            }
            noSendData = false
            sendLock?.unlock()
        }
    }
    func openCompleted() {
        NotificationCenter.default.post(name: NSNotification.Name.TcpConntectSuccess, object: nil)
    }
}
extension Stream {
    class func stream(_ ip: String ,_ port: Int32, input: inout InputStream? , output: inout OutputStream?){
        var host : CFHost
        var inputStream:  Unmanaged<CFReadStream>?
        var outputStream: Unmanaged<CFWriteStream>?
        host = CFHostCreateWithName(nil, ip as CFString).takeRetainedValue()
        CFStreamCreatePairWithSocketToCFHost(nil, host, port, &inputStream, &outputStream)
        if ((inputStream != nil) && (outputStream != nil)) {
            input = inputStream!.takeUnretainedValue();
            output = outputStream!.takeUnretainedValue();
        }
    }
}

**Comment by sunnyNH** [comment]
There's no problem with the ios code, because this code is used for the im system that golang wrote before, and now I want to write the service of im with a vapor.

**Comment by Joannis** [comment]
So, what are you trying to do? What is the reason you're trying to use Foundation's `InputStream` in Vapor?

Vapor has it's own TCP sockets
