### ISSUE TITLE
[question] Is there a distributed "Actor" model framework to make distributed server cluster on top of vapor?

### ISSUE THREAD

**Issue by avnerbarr** [vapor/vapor#1154]
More of a general question - Since vapor is the most popular server side swift framework , maybe this question belongs else where but  I would love to write server side swift using something similar to Akka Actors and its capabilities in processing "big data". Are there modules like that that perhaps that are built on top of vapor?

**Comment by vzsg** [comment]
No(t yet). Some very basic Actor implementations are floating around for iOS, but they don't do much and aren't even compatible with the Swift Package Manager.
