### ISSUE TITLE
Can not install Vapor via APT

### ISSUE THREAD

**Issue by robinwalterfit** [vapor/vapor#1160]
* Vapor Version: 2.0.4
* OS: Ubuntu
* OS Version: 16.04
* Vapor Toolbox Version: 2.0.4
* Swift Version: 4.0.0

### Expected Behavior

I expected to install Vapor with `sudo apt-get install swift vapor`

### Current Behavior

When I try to use a Toolbox command it just says: `vapor: symbol lookup error: vapor: undefined symbol: _TMSS`

### How to Reproduce

I have not installed Swift or Vapor before on my Ubuntu desktop... just created it in a VirtualBox. Swift will be installed in Version 4.0.0

**Comment by joscdk** [comment]
@robinwalterfit can you try:

```
sudo apt-get remove vapor
sudo apt-get install vapor
vapor --help
```

**Comment by robinwalterfit** [comment]
@joscdk got it!
After removing and reinstalling Vapor for several times I tried another tutorial for installing Swift & Vapor... I think the issue was that I missed a dependency for swift `libicu-dev` :see_no_evil:

Thanks anyway! 👍
