### ISSUE TITLE
Can't send email via SMTP

### ISSUE THREAD

**Issue by Lindemann** [vapor/vapor#1166]
* Vapor Version: 2.2.2
* OS Version: MacOS High Sierra 10.13 Beta
* Vapor Toolbox Version: 2.0.4

I tried to uses the SMPT client to send a Gmail mail. Since I couldn't find any documentation to this topic I tried this:
```
import SMTP

let client = try SMTPClient.makeGmailClient()
let credentials = SMTPCredentials(user: "user@gmail.com", pass: "password")
let email = Email(from: "user@gmail.com", to: "other.user@gmail.com", subject: "Foo", body: "Bar")
try client.send(email, using: credentials)  
```
The result is this error with status code `500`
```
[SMTP.SMTPClientError: invalidGreeting(code: -1, greeting: "")]
Conform 'SMTP.SMTPClientError' to Debugging.Debuggable to provide more debug information.
```

Did I miss something or is the SMPT client currently not working and therefore the lack of documentation?

**Comment by RishabhTayal** [comment]
I am getting the same error. Any ideas on how to fix it?

**Comment by tanner0101** [comment]
@RishabhTayal use the mailgun api if possible. smtp does not work in vapor 2 and is being removed in 3.0.

**Comment by RishabhTayal** [comment]
You mean mailgun REST API or the `SMTPMailer.makeMailgun(with: credentials)`?

**Comment by tanner0101** [comment]
There's a `drop.mail` property you can configure with `"mail": "mailgun"` in `droplet.json` and `mailgun.json`

**Comment by RishabhTayal** [comment]
@tanner0101 Thanks for the help. I am new to Vapor framework. Can you please provide more details on how the `mailgun.json` should look like? Is there a documentation? How can I use the `drop.mail` property in `Controller` file?

**Comment by twof** [comment]
@RishabhTayal Mailgun is a 3rd party mailing service you can find here:
https://documentation.mailgun.com/en/latest/

**Comment by RishabhTayal** [comment]
Actually I figured out how the `mailgun.json` should look like. Here is the example.

```
{
    "domain": "YOUR-MAILGUN-DOMAIN-NAME",
    "key": "YOUR-MAILGUN-API-KEY"
}
```
