### ISSUE TITLE
Unable to push to heroku

### ISSUE THREAD

**Issue by rmaes4** [vapor/vapor#1168]
I can build everything and run it just fine locally. When I try to push I get this

```
remote: Compile Swift Module 'AuthProvider' (10 sources)
remote: /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/checkouts/auth-provider.git--7246305057299524550/Sources/AuthProvider/InverseRedirectMiddleware.swift:10:30: error: use of undeclared type 'RedirectType'
remote:     public let redirectType: RedirectType
remote:                              ^~~~~~~~~~~~
remote: /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/checkouts/auth-provider.git--7246305057299524550/Sources/AuthProvider/InverseRedirectMiddleware.swift:16:23: error: use of undeclared type 'RedirectType'
remote:         redirectType: RedirectType = .normal
remote:                       ^~~~~~~~~~~~
remote: /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/checkouts/auth-provider.git--7246305057299524550/Sources/AuthProvider/InverseRedirectMiddleware.swift:33:16: error: cannot invoke initializer for type 'InverseRedirectMiddleware<U>' with an argument list of type '(U.Type, path: String)'
remote:         return InverseRedirectMiddleware(U.self, path: path)
remote:                ^
remote: /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/checkouts/auth-provider.git--7246305057299524550/Sources/AuthProvider/RedirectMiddleware.swift:10:30: error: use of undeclared type 'RedirectType'
remote:     public let redirectType: RedirectType
remote:                              ^~~~~~~~~~~~
remote: /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/checkouts/auth-provider.git--7246305057299524550/Sources/AuthProvider/RedirectMiddleware.swift:15:23: error: use of undeclared type 'RedirectType'
remote:         redirectType: RedirectType = .normal
remote:                       ^~~~~~~~~~~~
remote: /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/checkouts/auth-provider.git--7246305057299524550/Sources/AuthProvider/RedirectMiddleware.swift:32:16: error: cannot invoke initializer for type 'RedirectMiddleware' with an argument list of type '(path: String)'
remote:         return RedirectMiddleware(path: path)
remote:                ^
remote: <unknown>:0: error: build had 1 command failures
remote: swift-build: error: exit(1): /app/.swiftenv/versions/3.1.1/usr/bin/swift-build-tool -f /tmp/build_c49860a90894a156ae36103fd7ef5c29/.build/release.yaml
remote:  !     Push rejected, failed to compile Swift app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected
```

**Comment by vzsg** [comment]
This is caused by the `vapor/engine` transitive dependency being out of date, and really shouldn't work locally either.

You should run `vapor update` or `swift package update`, and commit the new pinned versions to make sure that Engine is above 2.1.0.

**Comment by rmaes4** [comment]
I ran vapor update and it worked fine but when I try to commit the changes it tells me there are no changes to commit.

**Comment by vzsg** [comment]
Just to be sure, are you pushing the correct branch to Heroku? Unless otherwise specified manually, Heroku will always deploy the master branch, no matter which branch you have active locally.

**Comment by rmaes4** [comment]
The only branch I have is the master branch. I'm using the command `vapor heroku push`

**Comment by rmaes4** [comment]
I could add you as a collaborator to my private repo if you'd like to see my code.

**Comment by vzsg** [comment]
That's okay too. You could also DM me on [vapor.team](http://vapor.team/), same nickname as here.

**Comment by rmaes4** [comment]
@vzsg I added you. I appreciate your help.

**Comment by vzsg** [comment]
Unfortunately I'm not getting emails from the invites, so I have no idea what repo to look for.

**Comment by rmaes4** [comment]
@vzsg here is your invite link https://github.com/rmaes4/Greek-Ride-Web/invitations

**Comment by vzsg** [comment]
Thanks. You can delete the message with the link now if you want.

The problem is that the buildpack uses Swift 3.1.1 by default, but your local system has Swift 4. The Package.resolved file (used by Swift 4) pulls in Engine 2.2.1 (yay!), but Package.pins (used by Swift 3) pulls in Engine 2.0.4 (nay 😢 ).

Here are your options:
- Remove Package.pins from the repository then push again, so Heroku will pull in the latest matching dependencies.
- Create a file called `.swift-version` in the root of the project with `4.0` inside. This will force the buildpack to install Swift 4 and use it for the build. Then delete and ignore Package.pins anyway for good measure.

**Comment by rmaes4** [comment]
@vzsg Thank you so much. I am pushing it right now, I will let you know if it works.

**Comment by rmaes4** [comment]
@vzsg worked great thank you.

**Comment by vzsg** [comment]
You're welcome.
