### ISSUE TITLE
cli command to create new migrations

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1172]
`vapor run create migration AddFooColumn` perhaps?

**Comment by steffendsommer** [comment]
`vapor run migration create AddFooColumn` to have everything grouped under migration?

**Comment by Joannis** [comment]
Is this still relevant?

**Comment by jlalvarez18** [comment]
Is there a reason it’s not relevant anymore?

**Comment by Joannis** [comment]
Because in Fluent v3 the migrations are largely inferred from the model

**Comment by pialjohn** [comment]
hi

**Comment by tanner0101** [comment]
Hi @pialjohn 👋
