### ISSUE TITLE
fluent identifier as protocol instead of concrete type

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1173]
Creating a `Fluent.Identifier` protocol would allow types to implement custom identifiers much more easily.

**Comment by Joannis** [comment]
How does this affect the models? Does it make them require generics? That could complicate things.

**Comment by tanner0101** [comment]
yes, unfortunately that causes the type-erasure problem. but so far it hasn't been an issue. and there are a ton of benefits including not having to rely on `Identifier` struct in your models package.

Models package:
```swift
import Foundation

struct User {
    var id: UUID?
    var name: String
    var age: Int
}
```

Models + Vapor package:

```swift
import Models
import Fluent

extension User: Model { }
```

so easy ❤️
