### ISSUE TITLE
vapor toolbox won't install through Homebrew

### ISSUE THREAD

**Issue by Reclzz** [vapor/vapor#1183]
* Vapor Version: 3.0.0
* OS: macOS Sierra
* OS Version: 10.12.6
* Vapor Toolbox Version: 1.0.9

### Current Behavior

I was trying to install the toolbox through Homebrew.
It downloaded fine but falls short of installing the toolbox.

### How to Reproduce

<img width="802" alt="screen shot 2017-10-06 at 11 51 04" src="https://user-images.githubusercontent.com/12407995/31272921-fefeb9aa-aa8c-11e7-8eb5-dae125fb5a79.png">

**Comment by vzsg** [comment]
The ~`toolbox`~ formula has been deprecated and replaced by `vapor` for a long while now.
Try installing that instead.

**Comment by Reclzz** [comment]
I have installed almost everything in vapor/tap/
vapor, vapor1, vapor-beta, vapor-cmysql.

Maybe I installed too many. However vapor --help doesn't show anything. When I'm done makong dinner I'll fire up my laptop and post again.

**Comment by tanner0101** [comment]
The correct command is:

```sh
brew install vapor/tap/vapor
```

@Reclzz may I ask where you saw the example for installing `~`toolbox`~? If it's in our docs, we should fix it.
