### ISSUE TITLE
Change the way  ENV variable values are specified in config files

### ISSUE THREAD

**Issue by ckd** [vapor/vapor#1191]
Can we change the way ENV variable values are specified in config files? I realize this is a breaking change, but perhaps for 3.0?

I ran into the VERY specific edge case of needing a String value with a $ prefix in my config files (custom log format string for SwiftyBeaver). The current way of doing things drops the leading $, rather unexpectedly, because Config assumes that all such strings are ENV variables.

It's not the biggest problem in the world, but I'm of the opinion that one should be able to specify any String value and not have to worry about any sorta framework magic mangling it.

Thoughts?

**Comment by fooksupachai** [comment]
Is there a way to persist changes in environment value between tasks in Visual Studio Team Services? I'm using Powershell to change it but it only changes it in the task not the whole process.

-------------------------------------------------------------------------------------------------------------------
//script 1

Write-Verbose "Before: $Env:SuperVersion"
$Env:SuperVersion = $NewVersion
Write-Verbose "After: $Env:SuperVersion"

//script 2

Write-Verbose "Final: $Env:SuperVersion"

//I see the change at After but Final is always getting the original value
