### ISSUE TITLE
dash docs integration

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1192]
integrate w/ dash docs. port api.vapor.codes to this.

**Comment by calebkleveter** [comment]
We should probably include [DevDocs](http://devdocs.io/) also.

**Comment by tanner0101** [comment]
@calebkleveter is that link correct? (is broken)

**Comment by vzsg** [comment]
The link above works for me.

**Comment by tanner0101** [comment]
![screen shot 2017-10-11 at 3 20 33 pm](https://user-images.githubusercontent.com/1342803/31442786-cddfeef2-ae97-11e7-8f78-79a74c2cf6ba.png)
why me?

**Comment by calebkleveter** [comment]
Hmm, not sure. Here is the link to the repo: https://github.com/Thibaut/devdocs (not that it would help fix the error, but you can read about it.)

**Comment by Joannis** [comment]
[Jazzy](https://github.com/realm/jazzy) supports both creating an HTML API docs as well as exporting to a dash docset.

**Comment by tanner0101** [comment]
api.vapor.codes supports this now.
