### ISSUE TITLE
SessionsMiddleware and CacheSessions with PostgreSQL

### ISSUE THREAD

**Issue by Joebayld** [vapor/vapor#1194]
* Vapor Version: 2
* OS: 10.13
* OS Version: 17A405
* Vapor Toolbox Version: 2.0.4

### Expected Behavior

Sessions to be persisted in CacheSessions as it does MemorySessions.

### Current Behavior

Vapor throws an issue that you can't store a non null value for the column 'value' in PostgreSQL.

### How to Reproduce

In your config, set the following:

`"cache":"fluent",`

Create the following middleware when creating the droplet. 
```
        let cacheSessions = CacheSessions(cache)
        let sessionsMiddleware = SessionsMiddleware(cacheSessions)
```

If I go into the SessionMiddleware and add the following line when it creates a new Session: 
       ` session.data = ""`
Then it will store an empty string in the cache and throw no errors.

**Comment by tanner0101** [comment]
Please include the code that is throwing the error and the actual error message itself (including id).

**Comment by Joebayld** [comment]
I've gotten this to sorta work. It still prints an error to console but works. The issue here is that the CacheSessions is trying to save a node of the user into the cache. This cannot be saved to PostgreSQL because the value type 'Node' can't be stored in the column. When thinking of how to persist the logged in user, I really only need the session ID and the user ID persisted. So in the database, the key would be the session ID, and the value would be the user ID. I did something like this: 

```
extension User: SessionPersistable {
    func persist(for req: Request) throws {
        let session = try req.assertSession()
        try req.assertSession().data = Node(node: id)
    }
}
```
Without this code, it tries to save a dict to PostgreSQL and fails. 
In the console it shows the following - but still persists to the database.: 
`Unsupported Node type for PostgreSQL binding, everything except for .object is supported.
`

I've looked into what CacheSession is trying to save to PostgreSQL and found this: 
`Setting key: jYB7nohFwsxrCXvIKngVrw==` 
 `
Setting value: Node(wrapped: 1, context: Node.ObjectContext<Swift.String, Swift.Int>)
` 

So clearly I can't set a value of type `Node` without throwing an issue. 


Thoughts?

**Comment by danisev7** [comment]
+1 Same error here...

**Comment by tanner0101** [comment]
Related to https://github.com/vapor/vapor/issues/1246

**Comment by tanner0101** [comment]
This will be supported in Vapor 3.
