### ISSUE TITLE
Routes and Parameters are case-sensitive

### ISSUE THREAD

**Issue by omidgolparvar** [vapor/vapor#1196]
It could be an option or a config (via `droplet.json`) to choose whether routes and parameters be case-sensitive or not.

**Comment by ckd** [comment]
I don't have strong feelings on this one either way, but I just wanted to point out that the current implementation is correct based on the relevant RFC (which I can't remember off the top of my head).

If you do prefer to have case-insensitive paths, it's probably simpler and faster to just have your web server do the rewrite.

**Comment by tanner0101** [comment]
@omidgolparvar you could probably achieve this with a middleware.

**Comment by GrfxGuru** [comment]
I do not have a firm opinion on which is best, but I feel that case-insensitive seems to make safer sense with a recommendation to follow a particular coding practice? I can see where debugging could be easily overlooked based on case sensitivity.

However, I do also agree that this feels like something the server should be configured to handle.

**Comment by tanner0101** [comment]
We should re-hash this discussion as I think Vapor 3 beta routing has already moved to case-insensitive. 

/cc @Joannis

**Comment by Joannis** [comment]
It did not move to case insensitive, I believe. We could make this configurable quite easily, though.

**Comment by Joannis** [comment]
Already fixed in [Engine#209](https://github.com/vapor/engine/pull/209)
