### ISSUE TITLE
tls server

### ISSUE THREAD

**Issue by cxk1992** [vapor/vapor#1199]
* Vapor Version: 2.0
* OS: macOS Sierra
* OS Version: 10.12.6
* Vapor Toolbox Version: 2.0.4

the ServerSocket.swift in TLS module
the function accept()->Self return self
i changed it like this  at the end of the function
```
    let c = InternetSocket(client, context)
    c.cSSL = ssl
    return c
```
but then server always report error like this
```
Server error: dispatch(Transport Layer Security Error: Undefined error: 0

Identifier: TLS.TLSError.SSL_read (0))
GET /info
Server error: dispatch(Transport Layer Security Error: The operation did not complete; the same TLS/SSL I/O function should be called again later.

Identifier: TLS.TLSError.SSL_read (-1))
```

so it can't keep connect alive

**Comment by Joannis** [comment]
Can you post a more complete example of setting up the connection? This issue is very tough to understand.

**Comment by cxk1992** [comment]
`
public func accept() throws -> Self {
        let client = try socket.accept()

        guard let ssl = SSL_new(context.cContext) else {
            throw makeError(functionName: "SSL_new")
        }
        cSSL = ssl

        try assert(
            SSL_set_fd(ssl, client.descriptor.raw),
            functionName: "SSL_set_fd"
        )
        // keep from deallocating
        self.client = client

        try assert(
            SSL_accept(ssl),
            functionName: "SSL_accept"
        )

        try assert(
            SSL_do_handshake(ssl),
            functionName: "SSL_do_handshake"
        )
        
        return self
    }
`

**Comment by cxk1992** [comment]
```
public func accept() throws -> Self {
        let client = try socket.accept()

        guard let ssl = SSL_new(context.cContext) else {
            throw makeError(functionName: "SSL_new")
        }
        cSSL = ssl

        try assert(
            SSL_set_fd(ssl, client.descriptor.raw),
            functionName: "SSL_set_fd"
        )
        // keep from deallocating
        self.client = client

        try assert(
            SSL_accept(ssl),
            functionName: "SSL_accept"
        )

        try assert(
            SSL_do_handshake(ssl),
            functionName: "SSL_do_handshake"
        )
        
        return self
    }
```
these code i find in ServerSocket.swift file in TLS Module,it is really a bug return self when accept ,so i change the code .
```
public func accept() throws -> InternetSocket {
        let client = try socket.accept()

        guard let ssl = SSL_new(context.cContext) else {
            throw makeError(functionName: "SSL_new")
        }
        cSSL = ssl

        try assert(
            SSL_set_fd(ssl, client.descriptor.raw),
            functionName: "SSL_set_fd"
        )
        // keep from deallocating
        self.client = client

        try assert(
            SSL_accept(ssl),
            functionName: "SSL_accept"
        )

        try assert(
            SSL_do_handshake(ssl),
            functionName: "SSL_do_handshake"
        )
        
        let c = InternetSocket(client, context)
        c.cSSL = ssl
        return c
    }
```
i know my usage is not right,but the TLS Module seems not complete yet.

**Comment by Joannis** [comment]
Ah, thanks! Reading this that's definitely a bug.

**Comment by cxk1992** [comment]
haha,welcome

**Comment by Joannis** [comment]
[You can keep track here](https://github.com/vapor/tls/issues/52)

**Comment by Joannis** [comment]
I don't think I can change this without breaking the API significantly. @tanner0101, what do you think we should do here?

**Comment by tanner0101** [comment]
If fix breaks API it must go in next major release unfortunately.

**Comment by vzsg** [comment]
![](https://i.imgflip.com/1zelyq.jpg)

Just kidding.

**Comment by Joannis** [comment]
@vzsg, that is *exactly* the problem with these kinds of things.

**Comment by agreensh** [comment]
So we can't run a production server using vapor 2?

I'm getting "Server error: dispatch(Transport Layer Security Error: The TLS/SSL connection has been closed." after the 1st request, using a certificate signed by a certificate authority. 
Same error on both OS/X and Ubuntu.

**Comment by Joannis** [comment]
You can, but behind an Nginx proxy

**Comment by agreensh** [comment]
That's disappointing.

**Comment by 0xTim** [comment]
But probably advisable for most uses cases since you can't bind to 'normal' ports

**Comment by agreensh** [comment]
I use port-forwarding, so binding to 'normal' ports is not an issue.

Perhaps the TLS section of the server doc should be updated (https://docs.vapor.codes/2.0/http/server/), so no longer "highly recommended" for Nginx, but "mandatory", until it works (and remove TLS selection)?

**Comment by 0xTim** [comment]
What's doing the port-forwarding? Can that not do the TLS termination?

**Comment by agreensh** [comment]
No, just modem port forwarding (port -> local ip:port)

**Comment by popaaaandrei** [comment]
@cxk1992 have you tested your fix? Does it work?

**Comment by Joannis** [comment]
I think we should consider making a second accept function for the Vapor 2 release. That way SSL can be used without breaking an API. 

Maybe name is `vapor_real_ssl_accept()` (just kidding)

**Comment by popaaaandrei** [comment]
Guys, I looked a little into the TLS package.
From what I found it seems that SSL_read is thrown when bytesRead == 0, but actually that also happens when SSL_RECEIVED_SHUTDOWN is beign received. It is in the docs of SSL_read(): `The read operation was not successful. The reason may either be a clean shutdown due to a "close notify" alert sent by the peer (in which case the SSL_RECEIVED_SHUTDOWN flag in the ssl shutdown state is set (see SSL_shutdown(3), SSL_set_shutdown(3)). `


This does the trick in `ReadableSocket.swift`
```
extension ReadableSocket {
    /// Receives bytes from the secure socket.
    ///
    /// - parameter max: The maximum amount of bytes to receive.
    public func read(max: Int, into buffer: inout Bytes) throws -> Int  {
        let bytesRead = SSL_read(cSSL, &buffer, Int32(max))
        
        // SSL_RECEIVED_SHUTDOWN check
        guard SSL_get_shutdown(cSSL) != SSL_RECEIVED_SHUTDOWN else {
            print("SSL_RECEIVED_SHUTDOWN")
            return 0
        }
        
        
        if bytesRead <= 0 {
            throw makeError(
                functionName: "SSL_read",
                returnCode: bytesRead
            )
        }

        return Int(bytesRead)
    }
}
```

**Comment by cxk1992** [comment]
@popaaaandrei 
sorry for such a long time.
my fix can work in tls request, but report many errors. 

i update vapor today, and it seems work good.
but it also can't keepalive. broken by the error. the id is a randon number.(i test it by adding log in basicServer, using chrome browser)
i'm waiting for vapor3.0.

_Starting server on 0.0.0.0:8443
id:4426  set keepalive = true
GET /
id:4426  set keepalive = true
GET /cinqueterre.jpg
id:6224   connect closed keepalive = false
id:8225   connect closed keepalive = false
id:1583   connect closed keepalive = false
Server error: dispatch(Transport Layer Security Error: The operation did not complete; the same TLS/SSL I/O function should be called again later.

Identifier: TLS.TLSError.SSL_read (-1))
id:1268  set keepalive = true
GET /
id:1268  set keepalive = true
GET /cinqueterre.jpg
id:1268  set keepalive = true
GET /favicon.ico
id:4250   connect closed keepalive = false
id:3503   connect closed keepalive = false
id:4871   connect closed keepalive = false
Server error: dispatch(Transport Layer Security Error: The operation did not complete; the same TLS/SSL I/O function should be called again later.

Identifier: TLS.TLSError.SSL_read (-1))_

**Comment by MrLotU** [comment]
As of November 2018 Vapor 2 is no longer supported. Closing this issue. [Version support](https://docs.vapor.codes/3.0/version/support/)
