### ISSUE TITLE
Fluent Entities can give their id as int

### ISSUE THREAD

**Issue by MartinLasek** [vapor/vapor#1212]
## Models can return their id as int

* Author: [Martin J. Lasek](https://github.com/martinlasek)

### Introduction

Models conforming to Model have the ability to return their id as integer

### Motivation

If you built e.g. an api you often need to also return the id of a model as int in order to be able operate on them. Currently I would do `user.id!.int!`. And I `force unwrap` here because of my thinking: if I successfully fetched a user from database, the user must have an id so force unwrapping shouldn't cause any issues here - it still looks/feels not right somehow..

### Proposed solution

The `Entity` protocol could provide something like a helper function to safe unwrap the id and cast it to int before returning it. So at the end one could get the id as int by calling `try user.assertId()`.

### Code snippets

```
extension Entity {
  func assertId() throws -> Int {
    guard let id = self.id?.int else {
      throw EntityError.couldNotCastIdToInt(self)
    }
    return id
  }
}
```

### Impact

It won't break any existing code. It will simplify how to get the id of a model as int.
Peeps wouldn't have to think how to solve that, would not have to force unwrap or at worst write the guard let statement in the place where they need the id as int. Repetitively. At best they would implement the proposed solution on their own writing an extension of the Entity.

**Comment by ckd** [comment]
I can absolutely see how that'd be handy for your use case, but not everybody uses integers for keys and I'm against growing the codebase for things that make broad, and often incorrect, assumptions.

**Comment by Alex293** [comment]
@ckd +1 to keep current state as we mostly use strings for our offline first apps.

**Comment by tanner0101** [comment]
@MartinLasek one thing you might also want to check in that function is whether `exists` is true. This is important b/c the model could have an ID (if you manually set one) even if it's never actually been saved to the database.

Luckily fluent has a function here already for that [`model.assertExists()`](https://github.com/vapor/fluent/blob/0a078d9947fb9fb44c3e8d34f40eaeef362968a0/Sources/Fluent/Entity/Entity.swift#L264-L273). This returns a non-optional identifier. 

You could build on this or add an extension to identifier for casting to int or throwing. However, Identifier is encodable and equatable so you shouldn't need to convert it to an int very often.

**Comment by MartinLasek** [comment]
@tanner0101 now that is nice **and** magic at the same time ✨ ! Thanks 🙌 !
