### ISSUE TITLE
Redis (vapor 3) features

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1221]
- [x] Pub/sub
- [x] Pipelining

**Comment by Joannis** [comment]
Should we implement pipelining? Is it essential? As far as I can read it does nothing more than chaining a set of commands into a single TCP message. It's easily implemented, but the API for adding commands to a pipeline is possibly a bit of a maintenance burden. The Redis should be really fast now, so I don't think it has a huge advantage currently.

**Comment by John-Connolly** [comment]
The performance improvements with pipelining are pretty substantial when there’s high latency.  I have been using it pretty heavily in [SwiftQ](https://github.com/John-Connolly/SwiftQ).  It’s especially useful when needing to do transactions. i.e with out pipelining you would have to wait for the response from the MULTI command before enqueuing any commands to execute.  I think this would have bad performance especially if the Redis is connect via a different host.  I might have time this week to add a PR for this if that would would help?

**Comment by Joannis** [comment]
Thanks for the reply! Good to know it's still really important.

You could pick it up for a PR, sure! If you don't manage to pick it up I'll make sure this is implemented, still. A PR should be based off #1222 since the architecture changed slightly and that could give you some merge errors.

**Comment by John-Connolly** [comment]
Added a pull request for it #1234.  I did some performance tests and noticed it was around 3 times faster when sending a lot of commands.
