### ISSUE TITLE
SPM4: After "vapor update", still getting "No such module"

### ISSUE THREAD

**Issue by acecilia** [vapor/vapor#1229]
* Vapor Version: 2.3.0
* OS: macOS Sierra
* OS Version: 10.12.6
* Vapor Toolbox Version: 3.0.3
* Swift 4
* Xcode 9.0.1

When added a new package to a project and after running "vapor update", importing the package keeps dropping a "no such module" error. The command "vapor update", nor SPM returns any error.

This is because in Swift Package Manager 4 "All targets and their dependencies must be explicitly declared".
The solution is to include the dependency also under .target, as explained here: https://stackoverflow.com/questions/45023201/cant-import-packages-using-swift-4-package-manager

For more information see: https://swift.org/blog/swift-package-manager-manifest-api-redesign/

**Comment by Joannis** [comment]
@acecilia So Vapor toolbox does work, but the returned errors are confusing in this area, right?

**Comment by acecilia** [comment]
@Joannis yes. I think the change is due to the new Packages.swift structure introduced with SPM4, which requires "All targets and their dependencies must be explicitly declared". So you have to add the .package line PLUS add the dependency to the corresponding .target. 
If you do not add the dependency to the .target, it will be downloaded and build, but not resolved, so you get the "no such module" error, and you do not get any error or warning message during the update process.
I spend some hours until I realized it, so I opened this issue in case this can be documented, if you feel it is necessary.

**Comment by cjmao** [comment]
Had the same issue when creating a new app.
Temporary fix: 
add `$(SRCROOT)/.build` to `Import Paths` under `Project Build Settings` **(NOT `Target Build Settings`)**.

**Comment by acecilia** [comment]
@cjmao You do not need a fix. This is a feature introduced in SPM4 on purpose. You just have to make sure to add the dependencies to the targets, as it is explained in https://swift.org/blog/swift-package-manager-manifest-api-redesign/

**Comment by acecilia** [comment]
From https://swift.org/blog/swift-package-manager-manifest-api-redesign/:
> There are three key differences between the Swift 4 manifest above and the previous manifest format:
> 
> 1. The tools version 4.0 is specified using the line // swift-tools-version:4.0.
> 2. **All targets and their dependencies must be explicitly declared.**
> 3. Public targets are vended as products using the new product API. Targets in Swift 4 packages can either depend on products of other packages, or targets of the same package.
