### ISSUE TITLE
Disable client cache

### ISSUE THREAD

**Issue by acecilia** [vapor/vapor#1230]
* Vapor Version: 2.3.0
* OS: macOS Sierra
* OS Version: 10.12.6
* Vapor Toolbox Version: 3.0.3
* Swift 4
* Xcode 9.0.1

I am repetitively making the same request every 10 seconds to another server. I am using the client inside Vapor (`drop.client.get()`). I observed the response is cached somewhere during 60 seconds, but I could not find a way to clear or disable it.

I tried this, but did not work:

```
URLCache.shared.removeAllCachedResponses()
URLCache.shared.diskCapacity = 0
URLCache.shared.memoryCapacity = 0
```

Any suggestions?
Thanks!

**Comment by Joannis** [comment]
Did you customise which HTTP Client Vapor uses?

**Comment by acecilia** [comment]
@Joannis thanks for your answer. No, I did not customize it. I could not find documentation about how to do it, can you point me to it?

Thanks

**Comment by vzsg** [comment]
One thing is certain: unless you change the value of `"client"`to `"foundation"` in Config/droplet.json (defaults to `"engine"`), changing anything around URLCache will have no effect.

That selects a different HTTP client implementation, one that is a wrapper for URLSession – more likely to use URLCache.

**Comment by Joannis** [comment]
@vzsg is right here, I'm not sure where you're getting the cached results from using the standard EngineClient. I skimmed over the EngineClient code and there seem to be no references to caching.

**Comment by acecilia** [comment]
@Joannis I did the same, and got to the same conclusion.
I am not using any special network configuration.

**Comment by acecilia** [comment]
In fact something is caching my request, but seems difficult to guess what. In the end I added an extra query parameter that I change every request, and now it is working as expecting.
Thanks!
