### ISSUE TITLE
Xcode cannot open generated project file after running `vapor xcode -y`

### ISSUE THREAD

**Issue by cjmao** [vapor/vapor#1231]
------------------------------------------------------------------------------------------------------
                                                                              Bug
------------------------------------------------------------------------------------------------------

* Vapor Version: 2.3.0
* OS: macOS
* OS Version: 10.13
* Vapor Toolbox Version: 3.0.3
* Xcode Version: 9.0
* Swift Version: 4.0

### Expected Behavior

After running `vapor xcode -y`, it should open the generated Xcode project.

### Current Behavior

Xcode reports: `Project path/to/Project.xcodeproj cannot be opened because it is missing its project.pbxproject file.`

### How to Reproduce

``` bash
$ vapor new Project
$ cd Project
$ vapor xcode -y
```

**Comment by Joannis** [comment]
It's definitely a bug, but I can't imagine this being a bug inside toolbox. (I'm thinking SPM)

Does it work if you manually open the generated Xcode project?

**Comment by cjmao** [comment]
I just tried deleting `Package.pins` then run `vapor update`.
And now I can open the generated Xcode project.
So I think this might be an issue related to the templates pinning old versions of denpendencies.

**Comment by cjmao** [comment]
Update:
Now I don't have to do anything to make `vapor xcode` work.

Still can't find possible reason.

**Comment by Joannis** [comment]
Strange.. I'll keep an eye out for this.

**Comment by mmick66** [comment]
I still have the issue!

**Comment by cjmao** [comment]
@mmick66 maybe you can try `brew reinstall vapor`.
