### ISSUE TITLE
asfsd

### ISSUE THREAD

**Issue by douglance** [vapor/vapor#1243]
🚀 Thanks for contributing! Choose from one of the templates below. [REMOVE]

Remove whichever sections of the template you do not need and all things labeled [REMOVE]

------------------------------------------------------------------------------------------------------
                                                                              Bug [REMOVE]
------------------------------------------------------------------------------------------------------

* Vapor Version: 
* OS: 
* OS Version: 
* Vapor Toolbox Version:

### Expected Behavior

[REMOVE] Describe what you expect to happen.

### Current Behavior

[REMOVE] Describe what is actually happening (the incorrect behavior).

### How to Reproduce

[REMOVE] Imagine someone is explaining the bug to you: what information do you need to be able to re-create it?

------------------------------------------------------------------------------------------------------
                                                                       Security Issue [REMOVE]
------------------------------------------------------------------------------------------------------

[REMOVE] If you find a security vulnerability, please contact [security@vapor.codes](security@vapor.codes) as soon as possible. Please do not report the vulnerability here as it is a public forum

------------------------------------------------------------------------------------------------------
                                                   Feature, Enhancement, or Optimization [REMOVE]
------------------------------------------------------------------------------------------------------

## Name of Feature

* Author(s): [Developer](https://github.com/<your-username>)

### Introduction

[REMOVE] A short description of what the feature is. Try to keep it to a single-paragraph "elevator pitch" so the reader understands what problem this proposal is addressing.

### Motivation

[REMOVE] Describe the problems that this proposal seeks to address. If the problem is that some common pattern is currently hard to express, show how one can currently get a similar effect and describe its drawbacks. If it's completely new functionality that cannot be emulated, motivate why this new functionality would help Vapor be a better framework.

### Proposed solution

[REMOVE] Describe your solution to the problem. Provide examples and describe how they work. Show how your solution is better than current workarounds: is it cleaner, safer, or more efficient?

### Code snippets

[REMOVE] Give us an idea of what this new idea will look like in code. The more code snippets you provide here, the easier it will be for the community to understand what your idea is.

### Impact

[REMOVE] Describe the impact that this change will have on existing code. Will some Vapor applications stop compiling due to this change? Will applications still compile but produce different behavior than they used to?

### Alternatives considered

[REMOVE] Describe alternative approaches to addressing the same problem, and why you chose this approach instead.

**Comment by tanner0101** [comment]
best issue :)

**Comment by twof** [comment]
I'm leaving Vapor if it doesn't implement asfsd like node.js does

**Comment by tanner0101** [comment]
priority 1 bug! 🚨

**Comment by douglance** [comment]
god damnit guys. 😆 

I was showing someone how to use github and accidentally created this. Sorry!
