### ISSUE TITLE
Vapor 2 peerHostname returning 0.0.0.0

### ISSUE THREAD

**Issue by NerdsGeeksGurus** [vapor/vapor#1244]
* Vapor Version: 2.2.2
* OS: ubuntu
* OS Version: 16.04.3 
* Vapor Toolbox Version: 3.0.0

### Expected Behavior

req.peerHostname should return valid IP address of client that is connecting

### Current Behavior

req.peerHostname is returning 0.0.0.0

### How to Reproduce

for a request (req), log `req.peerHostname`

### Other details
I have a vapor 2 app running on an AWS EC2 instance. Its DNS is routed through Route53. 

When I get a req, I am trying to log the IP address of the client. It always returns as 0.0.0.0 instead of the IP address.

On vapor 1, I had the same setup, but I was using peerAddress and it worked fine.

This is what is in req.headers:
`[Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", Connection: "keep-alive", Accept-Encoding: "gzip, deflate", User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.3.5 (KHTML, like Gecko) Version/11.0.1 Safari/604.3.5", Accept-Language: "en-us", Host: "hostname", Upgrade-Insecure-Requests: "1"]`

Note, I removed the hostname above due to client requirments.

**Comment by Hanfrey** [comment]
Just in case somebody comes here searching for a solution like me, a workaround is using an nginx proxy in front of the vapor application. Then it works like expected.

**Comment by NerdsGeeksGurus** [comment]
Thanks for the information. I will give that a try. I wanted to use nginx as a proxy anyhow, so that is a good excuse to see if that works.

**Comment by tanner0101** [comment]
Seems to be working as expected: https://github.com/vapor/engine/blob/d959474237a5bfe928239fe7b2cd6f62119badf5/Sources/HTTP/Messages/Message.swift#L52-L61
