### ISSUE TITLE
SessionsMiddleware and CacheSessions with MySQL

### ISSUE THREAD

**Issue by danisev7** [vapor/vapor#1246]
* Vapor Version: 2
* OS: macOS
* OS Version: 10.13 
* Vapor Toolbox Version: 3.0.3

### Expected Behavior

Sessions persisted in CacheSessions recover the correct user in fetchPersisted method

### Current Behavior

The fetchPersisted method not recovers the user id correctly.

This line in fetchPersisted Method needs a dictionary en data variable:

guard let id = try request.assertSession().data[sessionEntityId] else {
            return nil
}

But the guard always fails because request.assertSession().data contains a String with this content, not a dictionary:

{"session-entity-id":"1"}

### How to Reproduce

Configure your App Vapor to use MySQL database. 

In your config, set the following:

"cache":"fluent",

Create the following middleware when creating the droplet.

        let passwordMiddleware = PasswordAuthenticationMiddleware(User.self)
        let cacheSessions = CacheSessions(cache)
        let persistMiddleware = PersistMiddleware(User.self)
        let sessionsMiddleware = SessionsMiddleware(cacheSessions)
        let redirect = RedirectMiddleware.login()
        let loginRoutes = self.grouped([sessionsMiddleware, persistMiddleware])
        let protectedRoutes = self.grouped([redirect,sessionsMiddleware, persistMiddleware,passwordMiddleware])
        
        // User Controller
        let users = UserController(view: self.view, drop: self)
        users.setupUnauthenticatedRoutes(to:self)
        users.setupLoginRoutes(to:loginRoutes)
        protectedRoutes.resource("users", users)

When you do the Login, the session is stored in the cache table as is expected with value field equal to {"session-entity-id":"1"}
But when the next request calls to fetchPersisted method it fails always because the guard let id = try request.assertSession().data[sessionEntityId] statement not pass.

**Comment by tanner0101** [comment]
Can you include the code that throws the error (route code) as well as the error thrown?

**Comment by tanner0101** [comment]
This will be supported in Vapor 3.
