### ISSUE TITLE
vapor build failed!

### ISSUE THREAD

**Issue by scauos** [vapor/vapor#1247]
backgroundExecute(code: 1, error: warning: \fetch\ command is deprecated; use \resolve\ instead\nerror: dependency graph is unresolvable; found these conflicting requirements:\n\nDependencies: \n https://github.com/vapor/vapor.git @ 2.1.0..<3.0.0\n, output: Fetching https://github.com/vapor/vapor.git\nFetching https://github.com/vapor/fluent-provider.git\nFetching https://github.com/vapor/sqlite.git\nFetching https://github.com/vapor/tls.git\nFetching https://github.com/vapor/crypto.git\nFetching https://github.com/vapor/json.git\nFetching https://github.com/vapor/fluent.git\nFetching https://github.com/vapor/multipart.git\nFetching https://github.com/vapor/sockets.git\nFetching https://github.com/vapor/bcrypt.git\nFetching https://github.com/vapor/core.git\nFetching https://github.com/vapor/routing.git\nFetching https://github.com/vapor/node.git\nFetching https://github.com/vapor/bits.git\nFetching https://github.com/vapor/debugging.git\nFetching https://github.com/vapor/engine.git\nFetching https://github.com/vapor/console.git\nFetching https://github.com/vapor/ctls.git\nFetching https://github.com/vapor/random.git\n)

what's going on when I try to run vapor build.

**Comment by twof** [comment]
Did you figure it out?

**Comment by scauos** [comment]
yep

**Comment by twof** [comment]
What'd you do to fix it? It's good to talk about your solution incase someone else has the same problem later

**Comment by zerozheng** [comment]
cd to the root direction, and run `vapor build`
