### ISSUE TITLE
Extra Fluent lifecycle method (Vapor 3)

### ISSUE THREAD

**Issue by bygri** [vapor/vapor#1256]
Existing Fluent has the following lifecycle methods:

```swift
/// Called before the entity will be created.
/// Throwing will cancel the creation.
func willCreate() throws

/// Called after the entity has been created.
func didCreate()

/// Called before the entity will be updated.
/// Throwing will cancel the update.
func willUpdate() throws

/// Called after the entity has been updated.
func didUpdate()

/// Called before the entity will be deleted.
/// Throwing will cancel the deletion.
func willDelete() throws

/// Called after the entity has been deleted.
func didDelete()
```

Can we get a `willSave() throws` that is called on both create and update operations?

Something I do frequently in my models is validate before storing to database. Currently I have to call the validation from `makeRow()`, or from both `willCreate()` and `willUpdate()`. This is not the worst thing in the world, but I think it makes more sense to add a new lifecycle method that is called whenever the model is saved to the database, seeing as all the rest of the lifecycle is covered.

**Comment by tanner0101** [comment]
Closing this here since it's related to Fluent, not Vapor. Please feel free to re-open over there if it is still relevant. 👍
