### ISSUE TITLE
MainThread is Blocking - change to non-blocking

### ISSUE THREAD

**Issue by khoogheem** [vapor/vapor#1268]
### Introduction

Currently App.Run() is setup to block the main thread to keep Vapor running.  I would like to see this changed to be non-blocking, so others trying to bring in Frameworks that use Dispatching to the mainThread don't run into issues. 

### Proposed solution

Currently App.Run() uses a DispatchGroup Enter/Wait to block the main thread to keep running.
I suggest that we change that to be ```RunLoop.main.run()```

### Code snippets

Old:

```
    /// Runs the Application's server.
    public func run() throws -> Never {
        // TODO: run console / commands here.
        let server = try make(HTTPServer.self)

        let router = try RouterResponder(
            router: make(Router.self)
        )

        let middleware = try defaultMiddleware() + make(MiddlewareConfig.self).resolve(for: self)
        let chained = middleware.makeResponder(chainedto: router)
        try server.start(with: chained)

        let group = DispatchGroup()
        group.enter()
        group.wait()

        exit(0)
    }
```

New:
```
    /// Runs the Application's server.
    public func run() throws -> Never {
        // TODO: run console / commands here.
        let server = try make(HTTPServer.self)

        let router = try RouterResponder(
            router: make(Router.self)
        )

        let middleware = try defaultMiddleware() + make(MiddlewareConfig.self).resolve(for: self)
        let chained = middleware.makeResponder(chainedto: router)
        try server.start(with: chained)

        RunLoop.main.run()
        exit(0)
    }
```

### Impact

This will allow for Vapor to continue to keep running, but also allow us to use code like:
```
        DispatchQueue.main.async {
            print("hello") 
            // or do something more useful
        }
```

**Comment by Joannis** [comment]
I'm all for this change - if this doesn't impact Linux stability. I think the net performance impact will be positive, too. Saving a thread will improve both API and performance in theory.

**Comment by khoogheem** [comment]
I have not tested in Linux.. just on OSX for now.. will need to put some time under the belt to make sure there are no other side effects.

**Comment by Joannis** [comment]
If you could that'd help :) I still want/need to test it myself using Circle.

**Comment by khoogheem** [comment]
Running: Swift version 4.0.2 (swift-4.0.2-RELEASE) on Ubuntu 16.04.  With 3.0 Alpha 1, for the past few days and have not seen any issues so far.

**Comment by pacowong** [comment]
I have to follow the procedure from `entrypoint.swift` in https://github.com/vapor/template/pull/98/files to fix the issue in ver. 4.8.
