### ISSUE TITLE
Vapor 3 Models don't conform to `Parameter`

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1271]
In Vapor 2, all `Model` objects were automatically conformed to the `Parameter` protocol to allow them to be used in routes easily. This hasn't happened yet in Vapor 3 but makes sense to implement!

**Comment by tanner0101** [comment]
I think the best we'll be able to do here is _free_ conformance. I've seen this pattern used a bit which could help:

```swift
typealias BaseModel = Model & Parameter & SoftDeleteable
```

This way you can define what your application's "base" model is.

**Comment by 0xTim** [comment]
To be honest, now that you can do `extension MyModel: Parameter {}` I think that’s good enough?
