### ISSUE TITLE
There appears to be no way to read individual query parameters in 3.0 alpha 4

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1288]
* Vapor Version: 3.0.0 alpha 4
* OS: macOS
* OS Version: 10.13.1
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

I'd expect to be able to read individual query parameters from a URL. So, for https://example.com/foo?name=bob&age=18 I'd expect to be able to read "name" and "age" values.

### Current Behavior

I can't find a way to access individual query parameters.

Vapor 2.0 had API to access individual query parameters for a request, e.g. `https://docs.vapor.codes/2.0/http/request/#query-parameters`. This appears to be missing in the current alpha of 3.0, which will cause problems for users.

`uri.query` exists as a `String?` but it's not parsed into pieces ready to use.

**Comment by tanner0101** [comment]
Related to #1292

**Comment by tanner0101** [comment]
fixed:

```swift
let foo = req.query["path", "to", "foo"]
```
