### ISSUE TITLE
Docker not restarting after vapor crash

### ISSUE THREAD

**Issue by krazyjakee** [vapor/vapor#1294]
Vapor Toolbox: 3.1.2
Vapor Framework: 2.4.0
Ubuntu: 16.04

### Expected Behavior

When Vapor crashes, docker should detect that error and restart the container.

### Current Behavior

Docker stays stopped

### How to Reproduce

Build and run with the following dockerfile...

```
FROM ubuntu:16.04

RUN apt-get update && apt-get -y install curl && rm -rf /var/lib/apt/lists/*
RUN curl -sL https://apt.vapor.sh | bash
RUN apt-get update && apt-get -y install swift vapor && rm -rf /var/lib/apt/lists/*

COPY Config Config
COPY Sources Sources
COPY Tests Tests
COPY .swift-version .swift-version
COPY Package.swift Package.swift

RUN vapor build

ENTRYPOINT ["vapor", "run", "serve", "--env=production"]
```

Make sure the code throws the following error:
`Fatal error: Unexpectedly found nil while unwrapping an Optional value`

### Proposed solution

Ensure the exit code is 1 (error)

### Impact

Deployments using docker can be more stable

**Comment by vzsg** [comment]
For a quick workaround, change the entrypoint to the following, so the exit code of the binary is not swallowed by the toolbox.

```
ENTRYPOINT [".build/debug/Run", "--env=production"]
```

(Unrelated sidenote: this is a bad practice for production images as the Swift toolchain and the Vapor toolbox add completely unnecessary hundreds of megabytes to the resulting image.)

**Comment by krazyjakee** [comment]
@vzsg thanks!

About your sidenote. How would I go about removing the toolbox in that dockerfile to reduce bloat?

**Comment by vzsg** [comment]
Don't install it in the first place.

Here's a close-to-equivalent Dockerfile that builds on the swift official image instead of installing cruft manually:

```
FROM swift:4.0.2

RUN apt-get update && apt-get -y install libssl-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY Config Config
COPY Sources Sources
COPY Tests Tests
COPY Package.swift Package.swift

RUN swift build -c release
ENTRYPOINT [".build/release/Run", "--env=production"]
```

---

But the best solution is to use a multi-stage build to compile the binary first in one container, and then use a minimal ubuntu image for the application. I don't have an example at hand now.
