### ISSUE TITLE
bcrypt instance methods

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1299]
the bcrypt hasher only contains static methods which makes it impossible to conform to protocols like Auth's `PasswordVerifier` and impossible to register w/ the services system. 

in the interim, a `BCryptHasher` was created in the auth package. we should delete that when this issue is fixed.

**Comment by Joannis** [comment]
I think a separation of concerns needs to take place here. To me, BCrypt doesn't make sense as an instance function. I get that it's useful for `PasswordVerifier`, but I think think you should adapt low-level code to function in high-level concepts this way. I think the current implementation is fine with a wrapper.

**Comment by tanner0101** [comment]
i think having 2 classes that do bcrypt hashing will be a source of confusion for people.

**Comment by Joannis** [comment]
Has this been fixed? If not, I can take it

**Comment by Joannis** [comment]
You assigned this to me @tanner0101 , but I think this is a better task for you. The original API was my design and I still partially stand behind it.

**Comment by tanner0101** [comment]
This has been added.
