### ISSUE TITLE
Vapor 3 Server-Side SSL

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1308]
- Integrate the Server-Side TLS layer into Vapor 3's HTTP server.

## File middleware

We should investigate #1304 's proposed changes to file middleware after TLS has been introduced into the HTTP server. It can improve the performance of Vapor 3 for serving files *significantly* if it's possible with SSL.

**Comment by Joannis** [comment]
Solved in #1332

**Comment by tanner0101** [comment]
This is possible with NIO now, but not a goal of Vapor to support since it's highly recommended to run behind a reverse proxy anyway.
