### ISSUE TITLE
ON UPDATE and ON DELETE foreign key constraint referential actions

### ISSUE THREAD

**Issue by Anakros** [vapor/vapor#1312]
Hi. I couldn't find it in Vapor 2 Fluent implementation, so I think this is very important to implement it if you use foreign key constraints at all. I wrote a rough patch for it and it works for me: https://github.com/Anakros/fluent/commit/23003987c17b9dd8c15e0610f350e559b38548d0 Is there any chance that it will be merged to Fluent 2 if I create a pull request?

And any chance to see it in Vapor 3 in the future?

**Comment by vzsg** [comment]
While the decision is not up to me, I think you should definitely open a PR for this. It looks great IMHO and covers a serious pain point of the current version.

**Comment by tanner0101** [comment]
marking this for inclusion in vapor 3. @Anakros if you're interested, you could try implementing this same feature on the `beta` branch of this repo. that way we can include it in the next version (you are free to make breaking changes there so it will be easier to implement)

**Comment by Anakros** [comment]
@tanner0101 yeah, I probably will, but I still need it in Vapor 2.

**Comment by tanner0101** [comment]
Referential actions have been included in Fluent 3.
