### ISSUE TITLE
Vapor 3 environments cannot be passed via the CLI

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1313]
Vapor 3 currently checks for any extra unused arguments [and throws an error if there are any here](https://github.com/vapor/vapor/blob/beta/Sources/Command/ParsedInput.swift#L90). This works against [the environment detection](https://github.com/vapor/vapor/blob/beta/Sources/Service/Environment.swift#L43).

**Comment by tanner0101** [comment]
this was fixed in 3.0 alpha 12
