### ISSUE TITLE
Vapor 3 - MySQL Int ID database column not set to auto-incrementing ID

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1334]
In Vapor 3 Alpha 12 if you use an `Int` as your ID for your model and then `try builder.field(for: \.id)` in your migration, if you try and save a new model it throws the error

`[ ERROR ] Error: MySQL.Response.Error.remote-error: Field 'id' doesn't have a default value (parseResponse(mysql41:):Packet+Response.swift:38:45)`

It looks like it isn't using the DB to set the ID of the model. This only happens when using MySQL - if using SQLite then the issue doesn't appear to exist.

**Comment by Joannis** [comment]
Did you specify your id as autoimcrementing?

**Comment by 0xTim** [comment]
How do I do that? Should Fluent not infer that automatically?

**Comment by Joannis** [comment]
No, it cannot infer that. During schema creation

**Comment by 0xTim** [comment]
Is there anyway to do that with a migration? I've tried `try builder.field(type: ColumnType.int32(), for: \.id, isOptional: false, isIdentifier: true)` as the closest I could find but that didn't work. It's just strange the for SQLite the DB automatically sets the ID correctly but it doesn't work for MySQL which makes me think it's a DB driver issue instead of Fluent

**Comment by Joannis** [comment]
Ah, that _does_ seem like a bug. I'll look into it.

**Comment by tanner0101** [comment]
Created a failing test case here: https://github.com/vapor/mysql-driver/pull/51. \cc @Joannis

**Comment by twostraws** [comment]
I've tested this and it works great. This can be closed now – thank you!

**Comment by Joannis** [comment]
@0xTim I'll leave closing to you :)

**Comment by 0xTim** [comment]
Yep working for me too! 🎉
