### ISSUE TITLE
Vapor 3 Response Hanging Issue

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1335]
This issue has been present throughout all Vapor 3 alphas and is still existent in Alpha 12.

When sending requests the response will never be returned. This is fairly reproducible with simple applications. Observations so far:

* Happens with both MySQL and SQLite
* Happens with both Leaf and just API calls
* Happens when accessing Fluent routes (it may be a Fluent bug but I think it has happened when touching routes that don't make any Fluent calls)
* The request is processed (I've seen a DELETE request be handled and the item be deleted) but no response is returned
* Current thinking with @Joannis is a threading bug with async responses

**Comment by Joannis** [comment]
My conclusion:

The socket and/or request parser are drained before a router handler has been attached. This should be solved in #1326 with a workaround being possible with a workaround in the framework.

**Comment by gwynne** [comment]
Wanted to note that when this has been happening to me in alpha 12, the blocked request is definitely _not_ being processed. Also worth noting that requests hang _much_ more often when sending requests to `localhost` with `curl` than via Web browser (speed of request matters??).

**Comment by Joannis** [comment]
Yeah. That's an observation that 100% perfectly fits my conclusion

**Comment by verbotenj** [comment]
I have: 
Ubuntu 16.04
Vapor Toolbox: 3.1.2
Swift version 4.0.3

After I did
```
vapor new test --branch=beta
cd test
vapor build
vapor run
# I get this
[codes.vapor.engine.server.worker.5] Booting
[codes.vapor.engine.server.worker.6] Booting
[codes.vapor.engine.server.worker.7] Booting
Server starting on http://localhost:8080
[codes.vapor.engine.server.accept] Booting
```

There is default get router available
`curl -X GET http://localhost:8080/hello`

I don't get any response ever

**Comment by Joannis** [comment]
Haven't heard complaints about this in a while. Feel free to re-open if the issue persists.

One exception currently is #1450

**Comment by verbotenj** [comment]
I repeated the above steps I get the following
This is the response after running 

```vapor run```

```
Running project1 ...
[ [ [ [ ERROR[ Server starting on ERROR[ ERRORERROR ]  ]  ] Server Error: TCP.TCPError.accept: Invalid argumentERRORERROR ] Server Error: TCP.TCPError.accept: Invalid argumentServer Error: TCP.TCPError.accept: Invalid argumenthttp://localhost (Server Error: TCP.TCPError.accept: Invalid argument:8080
 ( ]  (TCPServer.swiftServer Error: TCP.TCPError.accept: Invalid argumentTCPServer.swift:TCPServer.swift (::146 ] ) (146TCPServer.swift146TCPServer.swiftServer Error: TCP.TCPError.accept: Invalid argument:)
):146 (146
TCPServer.swift)
):

146)
```
It hangs there and port 8080 is in LISTEN state

**Comment by Joannis** [comment]
You can get fake errors about failing to accept a client at the moment. You can safely ignore these.
