### ISSUE TITLE
Identifier: Sockets.SocketsError.bindFailed

### ISSUE THREAD

**Issue by DanielMoraCSG** [vapor/vapor#1340]
# Template: **vapor/api-template**

------------------------------------------------------------------------------------------------------
☁  VaporAPI [master] ⚡ vapor run serve
Running VaporAPI ...
Database prepared
Starting server on 0.0.0.0:8080
Serve error: Sockets Error: Failed trying to bind to the address
Identifier: Sockets.SocketsError.bindFailed

------------------------------------------------------------------------------------------------------

* Vapor Version: 2.2.2
* OS: 10.13.1
* OS Version: macOS High Sierra 
* Vapor Toolbox Version: 3.1.2

### Expected Behavior
`vapor run serve`
`Server starting...`

### Current Behavior

When I try to run vapor with `vapor run serve` show this in Terminal
Serve error: Sockets Error: Failed trying to bind to the address
Identifier: Sockets.SocketsError.bindFailed

### How to Reproduce

`vapor run serve`

**Comment by Joannis** [comment]
This is probably because another service is running on port 8080. You can find our which process using `lsof -i :8080`

**Comment by DanielMoraCSG** [comment]
![image](https://user-images.githubusercontent.com/17035060/33858195-6728a3ca-de94-11e7-98e6-8598d54a4c94.png)
-  Ignore The current hash key and The current cipher key (Just for local test)

**Comment by Joannis** [comment]
If your user permitted (by the firewall etc) to bind to this port?
Also; is this macOS or Linux?

**Comment by Jinxiansen** [comment]
@Joannis Obviously, this is the Mac OS .

**Comment by tanner0101** [comment]
@DanielMoraCSG try another port or using `sudo`
