### ISSUE TITLE
Vapor 3 type inference issues with Fluent

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1341]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: 10.13.2 
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

In some places Vapor allows me to use relative keypaths for Fluent properties, like this:

    try MyModel.query(on: req).filter(\.someProperty == "hello")

However, in other places it does not. It would be nice to get the shorter form where possible, for example here:

    let result = MyModel.query(on: req).average(\MyModel.someProperty)
    let result = MyModel.query(on: req).filter(\MyModel.someProperty, .contains, "hello")

In both places the `MyModel` is required, but it would be nice to lose it.

**Comment by twostraws** [comment]
Another place where it happens:

    MyModel.query(on: req).sort(\MyModel.someProperty, .descending)

**Comment by tanner0101** [comment]
This was added a while back 👍
