### ISSUE TITLE
Vapor 3: Please allow Future<Double> to be returned from routes

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1342]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: macOS 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

It's not possible to return `Future<Double>` from routes, even though `Future<Double>` is the default return type from Fluent methods such as `average()`. I would expect this to be possible, particularly given that `Future<Int>` *can* be returned.

**Comment by Joannis** [comment]
#1332 should fix this once it's merged and tagged 🙂

**Comment by Joannis** [comment]
This has been implemented
