### ISSUE TITLE
Vapor 3: Fluent ranges should behave like the rest of Swift

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1344]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

The following two Fluent queries compile to different SQL:

    Post.query(on: req).range(0..<10).all()
    Post.query(on: req).range(..<10).all()

The former compiles to `LIMIT 10 OFFSET 0` and the latter compiles to `LIMIT 9 OFFSET 0`. This raises a larger question about what the ideal result should be from both of those, and I suspect "do what the rest of Swift does" is a sensible default at this point.

So, `range(0..<10)`/`range(..<10)` should return 10 rows, and `range(0...10)`/`range(...10)` should return 11 rows, matching how arrays work.

**Comment by tanner0101** [comment]
see https://github.com/vapor/vapor/blob/beta/Sources/Fluent/Query/QueryRange.swift#L23-L47

**Comment by twostraws** [comment]
Also see https://github.com/vapor/vapor/blob/1a319f892c9bac4228b6ccbcba7bc5de0103ae66/Sources/Fluent/Query/Builder/QueryBuilder%2BExecute.swift#L25

**Comment by Joannis** [comment]
I agree with @twostraws here, <10 is max 9. But we should treat position `0` as an entity, too. So `..<10` is 10 entities

**Comment by twostraws** [comment]
Any further thoughts on this?

**Comment by tanner0101** [comment]
This was fixed a while back.

**Comment by tanner0101** [comment]
Sorry, this was not actually fixed yet. Tagging an issue in vapor/fluent: https://github.com/vapor/fluent/issues/517

**Comment by calebkleveter** [comment]
vapor/fluent#517 has been closed.
