### ISSUE TITLE
Redis in Vapor 3 doesn't handle Null Array response

### ISSUE THREAD

**Issue by shanehsu** [vapor/vapor#1361]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: 10.13.2 
* Vapor Toolbox Version: N/A

### Expected Behavior

Issuing the command `BRPOP someList 5` with `Redis` library, if nothing is popped after the timeout, the `Future` should resolve.

### Current Behavior

Issuing the command `BRPOP someList 5` with `Redis` library, the `Future` is never resolved.

### How to Reproduce

```swift
client.run(command: "BRPOP", with: [.bulkString("someList"), .bulkString("5")])
      .do { print($0) }
      .catch { print($0) }
```

### Preliminary Analysis

I traced the issue to,

- The socket did receive the message `*-1\r\n`
- The parser did try parsing
- The parser throw the error to `RedisClient`
- The `RedisClient` did nothing (threw it to a `BasicStream`)

**Comment by Joannis** [comment]
I _should_ have already fixed this for the next release 👍 thanks for the report, though. I'll keep this open until we verified this as working

**Comment by Joannis** [comment]
Thanks for the thorough analysis of the situation, by the way. A really good issue report

**Comment by Joannis** [comment]
This is fixed in the latest version 🎉
