### ISSUE TITLE
IsEmail validation validates anything that contains an email address somewhere

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1363]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

The current `IsEmail` validator allows any strings that contain one or more email addresses, which I expect isn't likely to be useful to developers. If we have an `emailAddress` field we would expect it contain something like sophie@example.com and nothing more.

### Current Behavior

With the current validation a string could be set to "Recently I changed my email address. It used to be sophie@example.com, but now it's sophie@sophie.com" and still pass. I would expect that string to fail.

### How to Reproduce

You don't need to create a full Fluent model, just try this:

    let test = ValidationData.string("a@a.com")
    try IsEmail().validate(test)

There are several ways this could be fixed in IsEmail.swift, but I would suggest this is a good starting point:

    // check that we have a basic match for email addresses
    if let matchRange = s.range(of: "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}", options: [.regularExpression, .caseInsensitive]) {
        // check that our match is the full string
        if matchRange == s.startIndex ..< s.endIndex {
            // it's a full match; exit
            return
        }
    }

    // either of our checks failed; throw an error
    throw BasicValidationError("is not a valid email address")

Alternatively, perhaps add anchors to check for the start and end of the regex?

**Comment by tanner0101** [comment]
This was fixed in Validation 2.0.0
