### ISSUE TITLE
IsASCII validator fails to validate strings with line breaks

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1364]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

I would expect the `IsASCII` validator to successfully validate strings that contain line breaks.

### Current Behavior

Multi-line strings currently fail validation.

### How to Reproduce

You can test the problem like this:

    let test = ValidationData.string("""
    This is a test
    Of long lines
    In Swift
    """)
    try IsASCII().validate(test)

Line breaks are valid ASCII characters and I would expect that string to validate successfully.

**Comment by Hejki** [comment]
I add PR to vapor/validation with fix: https://github.com/vapor/validation/pull/19
