### ISSUE TITLE
Vapor 3 Middleware not Configurable

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1371]
* Vapor Version: 3.0.0-alpha.12

It appears that you can't configure the application wide middleware at all. See the [Vapor Security Header tests](https://github.com/brokenhandsio/VaporSecurityHeaders/blob/a1ce0d740aefb5933b2784372daac18ebbdadb6b/Tests/VaporSecurityHeadersTests/HeaderTests.swift#L493) as an example, but essentially I configured by middleware with:

```swift
var services = Services.default()
var middlewareConfig = MiddlewareConfig()
middlewareConfig.use(myMiddleware)
services.register(middlewareConfig)

let app = try Application(services: services)
```

However it will always use the default middleware and there is no way to override this and my middleware won't be hit. These tests all pass if you add the middleware to a `RouteGroup` and pass requests through that

### Expected Behavior

My middleware to be hit

### Current Behavior

See above

### How to Reproduce

Try and add some middleware - see link above for failing test suite

**Comment by siemensikkema** [comment]
@0xTim This seems to be fixed now, can you confirm?

**Comment by 0xTim** [comment]
Yes appears fixed!
