### ISSUE TITLE
Compiler error when trying to use parameters in router at 3.0.0-alpha.12

### ISSUE THREAD

**Issue by fima2016** [vapor/vapor#1373]
* Vapor Version: 3.0.0-alpha.12
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

I have some problem with parameterized class in alpha12.
At first I am creating class:

```
Final class Device: codable {
…
}
```

After that create extension:

```
Extension Device: Parameter {

    typealias ResolvedParameter = String

    // The unique (prefixed) identifier for this type
    static var uniqueSlug = «my-app:device"

    // Creates a new user from the raw `parameter`
    static func make(for parameter: String, using container: Container) throws -> String {
        return parameter
    }
}
```

And I am using example from docs v 3.0-alpha

```
        router.on(.get, to: "device", Device.parameter) { request in
            let user = try request.parameters.next(Device.self)
            
        }
```

But I get error «**Extra argument in cal**l»

Can I use parameters in Vapor 3.0.0-alpha.12?

**Comment by twostraws** [comment]
I don't think this is a bug; please try using `try request.parameter(Device.self)` to fetch your parameter data.

**Comment by fima2016** [comment]
Thank, it work, but how I can encode, multiple parameters string in Vapor 3?
for ex: my-app.io/user?id=123?param1=123?param2=123?param3=name
And when I am try to parse multiple parameters string, i am get data before first "?".
I must using FormURLEncoded or something different?

**Comment by twostraws** [comment]
That's a separate problem; you might want to ask that on the Vapor Slack channel and close this issue.

**Comment by fima2016** [comment]
Ok! Thank!
