### ISSUE TITLE
services.register(SomeMiddleware()) no longer works in beta 1

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1376]
* Vapor Version: 3.0.0-beta.1
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

In alpha 12 we could write `services.register(SomeMiddleware())` to register middleware. In beta 1 this no longer works, and we need to write the following:

    services.register { _ in 
        SomeMiddleware()
    }

Given that this doesn't appear in the release notes, it seems likely this is a regression.

**Comment by Joannis** [comment]
Could you try `services.instance(SomeMiddleware())`?

**Comment by twostraws** [comment]
Thank you!
