### ISSUE TITLE
Please add a `String` initializer for `URI`

### ISSUE THREAD

**Issue by twostraws** [vapor/vapor#1382]
* Vapor Version: 3.0.0-beta.1
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

Please add the following initializer for `URI`:

    public init(_ value: String) {
        self = URIParser().parse(data: Data(value.utf8))
    }

It allows us to create `URI` objects from strings more easily. Even though `URI` conforms to `ExpressibleByStringLiteral`, that doesn't help it conform to strings that use interpolation. As a result, we need to write `URI(rawValue: "...")`, which isn't pleasant – the above initializer would be much appreciated.

**Comment by Joannis** [comment]
[Fixed in this engine PR](https://github.com/vapor/engine/pull/177)
