### ISSUE TITLE
Resources/Views  - Not Found 

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1385]
<img width="1087" alt="2" src="https://user-images.githubusercontent.com/16829428/34318869-b22ea74e-e80c-11e7-9f82-6da7768628f7.png">

When I looked at the vapor document, I did not find it in the <Vapor demo>.
https://docs.vapor.codes/2.0/vapor/views/

> English is not my native language; please excuse typing errors.

**Comment by cjmao** [comment]
You can try `vapor new --web AppName`.
This uses a different template which contains `Resources/Views` folder.

**Comment by Jinxiansen** [comment]
@cjmao  thanks !
So how do I add to the existing template?

**Comment by calebkleveter** [comment]
You can just run `mkdir -p Resources/Views` in your project root. Then add your `.leaf` file there.

**Comment by cjmao** [comment]
Yeah like calebkleveter said, you can just create them manually.

**Comment by Jinxiansen** [comment]
@calebkleveter  @cjmao    
Alright, thanks for the advice of two big brothers! 😘
