### ISSUE TITLE
Vapor can use plist / userdefault such a lightweight storage?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1386]
Can I use lightweight storage like plist / userDefault for some very small data types in the Vapor project?

I would like to briefly count the number of calls to an interface and call time.

😬

**Comment by 0xTim** [comment]
UserDefaults does not exist on Linux. You’re best bet is to probably use something like Redis or just an in memory store

**Comment by Jinxiansen** [comment]
@0xTim  Oh,so do si nei... 
 Thanks !
