### ISSUE TITLE
Fallback routes in V3 

### ISSUE THREAD

**Issue by skyweb07** [vapor/vapor#1389]
## Fallback routes in V3 

I'm in the making of a tool like Netflix [zuul](https://github.com/Netflix/zuul) proxy gateway for Vapor toolset, the thing is that I would need the [fallback](https://docs.vapor.codes/2.0/routing/overview/#fallback) parameters that were available in V2 to do the redirection based on path components, right now I can't make it work cause there is no way of doing something like this on V3

```swift

router.get("anything", "*") { request in
    return Future("something") "Matches anything after /anything"
}
```

I'm opening the issue to see if there are any possibilities to make this happen, thanks!

**Comment by tanner0101** [comment]
Seems this was fixed in the referenced router issue 👍
