### ISSUE TITLE
Unit Test helpers

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#1390]
Add helpers for setting up a testing environment to test an application relatively simply.

```swift
let tester = ApplicationTester(...)

tester.get("/users") { response in
  let users = try response.content.decode([User].self)
  XCTAssertEqual(users.count, 4)
}

try tester.awaitResults()
```

**Comment by MrLotU** [comment]
@tanner0101 I think we should scope this towards Vapor 4 in the way that the Vapor TIL app from RW implements it [here](https://github.com/raywenderlich/vapor-til/blob/master/Tests/AppTests/Application%2BTestable.swift)

**Comment by MrLotU** [comment]
With Vapor 4 in Beta, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
