### ISSUE TITLE
cookie parsing

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1396]
There appears to be an issue when parsing more than 1 cookie from a request (only the first cookie is parsed). This happened in Safari.

- [ ] create a test case for this
- [ ] fix if indeed not working

**Comment by Joannis** [comment]
I'll test if this bug is still present. HTTP header storage has been rewritten ~2 times since then.

**Comment by Joannis** [comment]
Not an issue (anymore)

**Comment by Joannis** [comment]
```swift
router.get("headers") { req in
    return req.http.headers[valuesFor: .cookie]
}
```
