### ISSUE TITLE
Routing Groups

### ISSUE THREAD

**Issue by MaximBazarov** [vapor/vapor#1398]
After lots of discussions we produced the following functions:
# Create new group

```swift
let users = router.group("user")
users.get("auth", use: userAuthHandler)
users.get("profile", use: userProfileHandler)
```
I named it `group` instead of `grouped` because function returns new, just created, group rather than modified router

### Create a new group and configure it in-place 
```swift
router.grouped(with: "user") { group in
    group.get("auth", use: userAuthHandler)
    group.get("profile", use: userProfileHandler)
}
```
Here `grouped` does make sense because function modifies the router

## Using middleware (old-fashioned)
```swift
let users = router.group("user").using(SomeMiddleware())
users.get("auth", use: userAuthHandler)
```
In this case `using` makes sense for both cases
### Using middleware (old-fashioned) and configure a group which use this middleware in-place
```swift
router.using(AuthorizationMiddleware()) { group in
    group.get("profile", use: userProfileHandler)
}
```

# Using function as a middleware
Swift is a functional language, and I think that is the best to use this style naturally. Instead of caring the responsibility to store references to a middleware instances it is possible to simply store pure functions which apply to requests

```swift
let users = router.group("user").using({ req, next in
    return try userService.authorized(user)
})
users.get("auth", use: userAuthHandler)
```
### Using a function as a middleware and configure it in-place
```swift
func userMustBeAuthorized(request: Request, next: Responder) throws -> Future<Response> {
    return try userService.authorized(user)
}

router.using(userMustBeAuthorized) { group in
    group.get("profile", use: userProfileHandler)
}
```

**Comment by MaximBazarov** [comment]
Guys please let's create a perfect naming here

**Comment by Joannis** [comment]
I think we should look into `Middleware`s more, specifically regarding thread safety. If we inject a route within a middleware (as with Vapor 3 currently, and this proposal), accessing instance variables can crash. I so like the `using` (and other) naming, although `using` with a trailing closure is an awesome but confusingly named helper to me. I'm not using a closure, I'm using the closure _as a middleware_ that maps a Request.

**Comment by MaximBazarov** [comment]
we can also remove the `using(_ middleware: Middleware..., ` functions and only keep `using(_ respond: @escaping MiddlewareFunction.Respond` functions. We'll still be able to use old middleware just passing `Middleware.respond` function:
```swift
// register in services or somewhere
let someMiddleware = SomeMiddleware()

//...
router.using(someMiddleware.respond) { group in
    group.get("profile", use: userProfileHandler)
}
```

And downside is: we need to warn user to not use approach with in-place instantiation:

```swift
router.using(SomeMiddleware().respond) { group in
    group.get("profile", use: userProfileHandler)
}
```

but better to do it once and change the docs than have issues with threads all the time

**Comment by 0xTim** [comment]
I don't like that lack of safety that this would give you - warning users not to use it isn't really ideal if it is going to crash the application, especially given it looks like the same thing and compiles without any warnings etc

**Comment by MaximBazarov** [comment]
@0xTim I totally agree with you, but in this case it's impossible to move on and keep it compile time safe

**Comment by MaximBazarov** [comment]
Merged
