### ISSUE TITLE
How do I determine in the vapor project is the current system is mac os or Ubuntu?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1399]
**As mentioned above, I developed on the mac, and then run from Ubuntu, but some configurations are different, I want to distinguish the system and change the relevant configuration.**

> English is not my native language; please excuse typing errors.

**Comment by twof** [comment]
Does this work?
https://stackoverflow.com/questions/42588842/swift-system-version-checking-on-ubuntu

**Comment by Jinxiansen** [comment]
@twof 

![1](https://user-images.githubusercontent.com/16829428/34467803-3e9176aa-ef36-11e7-897a-df2ab38765c1.png)

**Yes ! 
This is exactly what I want, I tried to use the perfect solution to my problem !
thank you very much ! 
Big brother !**
