### ISSUE TITLE
Vapor 3 only receives first request from a websocket

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1400]
------------------------------------------------------------------------------------------------------
                                                                              Bug
------------------------------------------------------------------------------------------------------

* Vapor Version: beta
* OS: macOS 
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

Websockets should be able to receive multiple consecutive requests after opening

### Current Behavior

The first request is received, but every request after that never reaches the route callback

### How to Reproduce

Here is the test route I'm using:

```swift
        router.websocket("ping") { (req, ws) in
            print("open")
            ws.onData({ (ws, data) in
                print("data", data)
            })
            ws.onString({ (ws, msg) in
                print("string")
                if msg == "ping" {
                    ws.send(string: "pong")
                }
            })
            ws.onByteBuffer({ (ws, byte) in
                print("byte", byte)
            })
        }
```

I'm using this client for testing
https://chrome.google.com/webstore/detail/simple-websocket-client/pfdhoblngboilpfeibdedpjgfnlcodoo?hl=en

Config:
Open socket: ws://localhost:8080/ping
Request: ping

Once the socket is open, I send the request twice. This is the client-side output:

```
ping
pong
ping
```

This is the server-side output:

```
[codes.vapor.application] Booting
Migrating mysql DB
Migrations complete
[codes.vapor.engine.server.worker.0] Booting
[codes.vapor.engine.server.worker.1] Booting
[codes.vapor.engine.server.worker.3] Booting
[codes.vapor.engine.server.worker.2] Booting
[codes.vapor.engine.server.worker.4] Booting
[codes.vapor.engine.server.worker.5] Booting
[codes.vapor.engine.server.worker.7] Booting
[codes.vapor.engine.server.worker.6] Booting
Server starting on http://localhost:8080
[codes.vapor.engine.server.accept] Booting
open
string
```

**Comment by tiwoc** [comment]
According to recent changes to `Development/main.swift`, it is necessary to set the expected request count on the result of the `onString` call:
https://github.com/vapor/vapor/blob/beta/Sources/Development/main.swift#L285

**Comment by twof** [comment]
Closing this. Potentially related issue:
https://github.com/vapor/vapor/issues/1438
