### ISSUE TITLE
Auto-Conformance to ResponseEncodable for Encodable Types

### ISSUE THREAD

**Issue by calebkleveter** [vapor/vapor#1405]
I think it would helpful to automatically conform `Encodeable` types to `ResponseEncodable`, allowing you to return any model from a route. Currently, you have to conform your types yourself, leading to what I call a [line 49](https://qutheory.slack.com/archives/C4QRYJ6DD/p1515015113000217?thread_ts=1514985798.000268&cid=C4QRYJ6DD), a block of code that gets repeated in every project, sometimes in multiple places. I think we should try to reduce that amount of these that we have

**Caveat:** We would have to figure out the `Content-Type` header somehow.

**Comment by Joannis** [comment]
We did this before, it had some nasty side effects for types such as `String`

**Comment by calebkleveter** [comment]
What if we did it to type that conform to `Content`? That way we wouldn't have to do anything weird to decide what the `Content-Type` header should be. Or does `String` also conform to `Content` 🙂

**Comment by tanner0101** [comment]
Content conforms to ResponseEncodable :)
