### ISSUE TITLE
Vapor 3 Build Error: Could not build Objective-C Module 'Foundation'

### ISSUE THREAD

**Issue by mikeKane** [vapor/vapor#1409]
* Vapor Version: 3
* OS: macoS
* OS Version: 10.13.3
* Vapor Toolbox Version: 3.1.2

### Expected Behavior
Vapor Build success

### Current Behavior
Errors when running build 

<unknown>:0: error: too many errors emitted, stopping now
<unknown>:0: error: could not build Objective-C module 'CoreFoundation'
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/xx/Xcode/serverSideSwift/server/project1/.build/debug.yaml main

### How to Reproduce
vapor new projectName --branch=beta
cd projectName
vapor build

**Comment by mikeKane** [comment]
Vapor build seems to be pointing to swift 4.0 and not 4.0.3 does that matter? Also looks like it's pulling macOSX10.10 not 10.13, does that matter?

**Comment by vzsg** [comment]
Can you post the complete build output instead of just the final (and completely useless) lines?

**Comment by mikeKane** [comment]
<img width="970" alt="vaporbuild" src="https://user-images.githubusercontent.com/7225808/34642270-5d071684-f2de-11e7-97d1-61c06684cd65.png">

**Comment by mikeKane** [comment]
Too many lines to copy and paste

**Comment by mikeKane** [comment]
Mikes-MBP:project1 _kane7161$ vapor build --verbose
No .build folder, fetch may take a while...
Fetching Dependencies ...
Fetching https://github.com/vapor/vapor.git
Fetching https://github.com/vapor/leaf.git
Fetching https://github.com/vapor/crypto.git
Fetching https://github.com/vapor/service.git
Fetching https://github.com/vapor/engine.git
Fetching https://github.com/vapor/console.git
Fetching https://github.com/vapor/async.git
Fetching https://github.com/vapor/core.git
Cloning https://github.com/vapor/vapor.git
Resolving https://github.com/vapor/vapor.git at beta
Cloning https://github.com/vapor/core.git
Resolving https://github.com/vapor/core.git at beta
Cloning https://github.com/vapor/engine.git
Resolving https://github.com/vapor/engine.git at beta
Cloning https://github.com/vapor/service.git
Resolving https://github.com/vapor/service.git at beta
Cloning https://github.com/vapor/crypto.git
Resolving https://github.com/vapor/crypto.git at beta
Cloning https://github.com/vapor/async.git
Resolving https://github.com/vapor/async.git at beta
Cloning https://github.com/vapor/console.git
Resolving https://github.com/vapor/console.git at beta
Cloning https://github.com/vapor/leaf.git
Resolving https://github.com/vapor/leaf.git at beta
warning: 'fetch' command is deprecated; use 'resolve' instead
Fetching Dependencies [Done]
Building Project ...
Compile CHTTP http_parser.c
Compile Swift Module 'COperatingSystem' (1 sources)
Compile Swift Module 'Debugging' (6 sources)
Compile Swift Module 'Async' (38 sources)
Compile Swift Module 'Bits' (5 sources)
Compile Swift Module 'Logging' (3 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/CoreFoundation.h"

**Comment by mikeKane** [comment]
I have Version 9.2 beta (9C32c) and Version 9.2 (9C40b) installed.

**Comment by vzsg** [comment]
And which one is the active one for the command line tools? `xcode-select -p` or the Locations tab in Xcode's Preferences will tell you that. If it's the beta, you should switch to the release version instead.

**Comment by mikeKane** [comment]
/Applications/Xcode.app/Contents/Developer

**Comment by twostraws** [comment]
It might be relevant to remind everyone that macOS 10.13.3 is currently in beta. Although I'd like to think that isn't the culprit here, it's worth keeping in mind. It's also worth checking that you don't have any custom toolchains installed in your Xcode version.

Elsewhere it looks like [some folks](https://stackoverflow.com/questions/34985106/compiling-a-swift-script-into-an-executable) are hitting problems where the macOS SDK isn't being selected for some reason.

**Comment by mikeKane** [comment]
The above link worked to build. I just had to add xcrun -sdk macosx in front of vapor build. However vapor run just throws up errors.

[vaporRun.txt](https://github.com/vapor/vapor/files/1609807/vaporRun.txt)

**Comment by vzsg** [comment]
Maybe a beta Xcode is needed to complement the beta macOS?
Which isn't available yet, so anything can happen...

**Comment by Jinxiansen** [comment]
oh...

**Comment by mikeKane** [comment]
I switched paths to beta Xcode and no change.

**Comment by twof** [comment]
Looks like this is a problem that's cropped up across multiple versions of XCode

https://stackoverflow.com/questions/25999754/could-not-build-module-foundation

https://github.com/box/box-ios-sdk/issues/282

So it's not Vapor specific.

**Comment by mikeKane** [comment]
New machine, 10.3 did build but received this error on command 

vapor run 

`Server starting on http://localhost:8080
Fatal error: Error raised at top level: ⚠️ TCP Error: Undefined error: 0
- id: TCP.TCPError.getAddressInfo

File: /Users/_kane7161/Xcode/serverSideSwift/server/project1/.build/checkouts/engine.git-3311994267206676365/Sources/TCP/Socket/TCPServer.swift
 - func: bind(hostname:port:)
 - line: 99
 - column: 33

Here are some possible causes: 
- The address that binding was attempted on does not refer to your machine.

These suggestions could address the issue: 
- Bind to `0.0.0.0` or to your machine's IP address`
