### ISSUE TITLE
Client mishandles some HTTP headers

### ISSUE THREAD

**Issue by gwynne** [vapor/vapor#1410]
`Client` should:

* Not send a second copy of a header if the header was already provided in the `HTTPRequest` object used to create the `Request`. Example: If `Content-Type: application/json` was specified, `Request.content.encode()` with JSON content will add a _second_ `Content-Type: application/json; charset=utf-8` header to Request. Both will ultimately be sent, in violation of the HTTP spec. Whether the desired behavior here is to use the one generated by `Request` or keep the caller-specified one is up for discussion.

* Provide a default value for the `Host` header if none was already provided, based on `URI.hostname`; failing to provide one can result in an HTTP/1.1 request with no `Host` header, which is in violation of the HTTP spec.

**Comment by gwynne** [comment]
Additionally, there could be some discussion on how to handle manually-specified `Set-Cookie` headers and other such "there _can_ be more than one of these by spec" cases. In general I feel like the Client and HTTP APIs don't express the minimum range of control desirable in a compliant HTTP implementation.

**Comment by tanner0101** [comment]
- @Joannis can you check out the double header thing? I was also seeing that.
- Will make sure the Host header is set. 
- The set-cookie thing always manages to open pandora's box. I thought we had finally cracked it this time, can you clarify more what it's lacking?

**Comment by gwynne** [comment]
I didn't run into the Set-Cookie one directly; I was spitballing a bit on that one. At the moment the only _direct_ complaint I have with the API is that it's not immediately obvious how to leverage it to produce the intended results.

**Comment by Joannis** [comment]
[Hostnames are implemented here](https://github.com/vapor/vapor/pull/1525)

Set-Cookie was taken into account.

**Comment by tanner0101** [comment]
Fixed by #1529
