### ISSUE TITLE
`request.content.decode()` can not disambiguate `MediaType`s

### ISSUE THREAD

**Issue by gwynne** [vapor/vapor#1411]
When decoding a `Request`'s content, it is sometimes desirable to override the `MediaType` which would otherwise be chosen by the `ContentConfig` - particularly when more than one decoder exists for a given MIME type. `application/xml` is especially misused by a plethora of implementations for which more specific decoders than the general XML decoder can easily be written; SOAP and its predecessors are just one example.

However, `defaultMediaType` on `Content` objects is not respected when decoding, and it is not possible to override the choice made by `ContentContainer` even when it is desirable to explicitly require a specific decoder (or for that matter, a specific request encoding). The only current solution is to fall back to manually handling `request.body`.

I suggest adding optional parameters to `ContentContainer.decode()` which allow forcing the `MediaType` used for decoding.

**Comment by gwynne** [comment]
Additional: Having the same `MediaType` registered to multiple encoders also causes issues with encoding; the `ContentContainer` will pick the first registered one, since it's not sensible to use object identity on `MediaType` (not the least because it's a `struct`!).

This makes it clear to me that my suggested solution for decoding is not viable, as it would suffer from the same "just picks the first one" flaw. I'm at a loss, short of making parameters significant for comparisons, which would mean introducing extraneous data into generated HTTP headers - and if you can affect the server's `Content-Type`, you can just change it outright!

I'm back to being open to suggestions on this one.

**Comment by tanner0101** [comment]
@gwynne maybe a meta-decoder that handles the inconsistencies between XML and passes off to the proper, real decoder? Then you could just register that meta decoder and it would get all xml media type content.

**Comment by gwynne** [comment]
Yeah, that was basically what I ended up with.
