### ISSUE TITLE
Vapor 3 Stuck on 'Migrating DB'

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1412]
As discussed in Slack, current Vapor 3 applications seem to be getting stuck on Migrating the database. The issue is in the [`syncFlatten` call](https://github.com/vapor/fluent/blob/beta/Sources/Fluent/Service/Provider.swift#L58) - the futures that are created in here in the `do` https://github.com/vapor/async/blob/beta/Sources/Async/Futures/Array%2BFuture.swift#L16 are never executed. They hit the `addAwaiter` call https://github.com/vapor/async/blob/beta/Sources/Async/Futures/FutureType.swift#L40 but then are never picked up. I'm not sure if it has anything to do with the fact that the application is currently booting up so may not have a thread to pick up these closures?

Currently unsure as to if this is specific to SQLite or MySQL (and other DBs) are affected too, will do some digging

**Comment by tanner0101** [comment]
This was fixed here https://github.com/vapor/fluent/pull/343
