### ISSUE TITLE
If I can develop vapor project(deploy on Ubuntu) using Xcode without writing cross platform code?

### ISSUE THREAD

**Issue by mrdundun** [vapor/vapor#1416]
I'm trying to develop vapor project .

I want to develop with Xcode and deploy on Ubuntu.

The different between MacOS(dev env) and Ubuntu(product env) make something trouble.

For example:

        var reslut = ""
        #if os(Linux)
            ran = Int(random() % self.count)
            reslut = String(ran)
        #else
            let max32 = UInt32(Byte.max)
            let ran = arc4random_uniform(max32)
            reslut = String(ran)
        #endif
        return reslut 

In the previous code, I must write code for both MacOS and Ubuntu.
I can't debug the Ubuntu part via Xcode.

If I can develop vapor project(deploy on Ubuntu) using Xcode without writing cross platform code?
Or if there's some tools(instead Xcode) make developing more effective on Ubuntu?

* Vapor Version: 2.2.2
* OS: MacOS High Sierra
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

**Comment by twof** [comment]
XCode uses LLDB for debugging which should also be available on Ubuntu. Here's a SO question similar to yours:

https://softwarerecs.stackexchange.com/questions/29797/gui-for-lldb-preferably-most-resembling-xcode

If you're not a fan of the GUI suggested in the answer, there are many many others you could give a shot.
https://github.com/snare/voltron
https://github.com/ant4g0nist/vegvisir

VSCode might be a good option too if you want a cross platform editor that supports LLDB:

https://github.com/vadimcn/vscode-lldb

**Comment by 0xTim** [comment]
See @joscdk's [post](https://medium.com/@joscdk/develop-server-side-swift-on-linux-a9ea56e805cc) on developing on Linux.

I think most people develop on Xcode and deploy on Linux, things should be mostly similar. Just make sure you run tests (from the start!) on Linux with CI.

PS Vapor has a Random class that you can use to avoid doing the above code
