### ISSUE TITLE
How to inherit from the Model class, custom MySQL table table name.

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1417]
🚀 Thanks for contributing! Choose from one of the templates below. [REMOVE]

* OS: macOS 10.13.2
* Vapor Toolbox Version:3.1.2
 

I want to inherit the Model class, custom MySQL table table name, 

![3](https://user-images.githubusercontent.com/16829428/34778809-5ea330ee-f659-11e7-9ff3-fb2f54ca31ad.png)

![4](https://user-images.githubusercontent.com/16829428/34778852-789b5026-f659-11e7-9156-68cc709cd808.png)

**I created a class named `PK1Model`, but it automatically generates `p_k1_models` in MySQL when I run the project, but this is not the name of the table I want.
but I do not know what to do?**

Please give me some pointers! Thank you! 🍋

> English is not my native language; please excuse typing errors.

**Comment by vzsg** [comment]
In your model subclass, add this:

```
static let entity = "the_table_name_you_want"
```

This will replace the default name Fluent generates for your model. [[Docs]](https://docs.vapor.codes/2.0/fluent/model/#entity_1)

**Comment by Jinxiansen** [comment]
@vzsg 

This write really solved my problem,
But at any time there is a new problem:
`[MySQL Error: Table 'pythondb.pkmodel' does not exist]` , is it necessary to manually create pkmodel in MySQL this table name?
![5](https://user-images.githubusercontent.com/16829428/34779967-bcc33644-f65c-11e7-8c48-99868a13045a.png)
![6](https://user-images.githubusercontent.com/16829428/34779969-bd067a94-f65c-11e7-842b-8245658d59a1.png)

**Comment by 0xTim** [comment]
@Jinxiansen you will need to wipe your database if you are changing the model like that

**Comment by Jinxiansen** [comment]
Okay, thank you!

**Comment by Jinxiansen** [comment]
@0xTim  Do you know how to convert utf8? Please give me a little advice
