### ISSUE TITLE
Can you provide detailed advanced instructions on how to use MySQLProvider?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1418]
* Vapor Toolbox Version: 3.1.2

I only found on **https://docs.vapor.codes/2.0/mysql/package/** how to configure MySQLProvider, but for further use there is no detailed instructions,
English is not my native language, so read the official document a bit difficult,but I very much like to use vapor, I wonder if there is a reference on the use of **MySQLProvider Demo** ?
thank you very much!

> English is not my native language; please excuse typing errors.

**Comment by twof** [comment]
Can you describe what you're trying to do?

**Comment by Jinxiansen** [comment]
Add, delete, change, check, local MySQL data, and convert to vapor json back to the user.

**Comment by twof** [comment]
Most of that is going to be done though Fluent
https://docs.vapor.codes/2.0/fluent/query/

Returning JSON

https://docs.vapor.codes/2.0/http/response-representable/#json

**Comment by 0xTim** [comment]
@Jinxiansen I wrote a post on how to use the MySQL Provider [here](https://geeks.brokenhands.io/blog/posts/fluent-part-4-persistence-with-mysql-and-fluent-patterns/) - if you need to learn how to use Fluent and Vapor, start at the beginning of the tutorial series
