### ISSUE TITLE
uri query update infinite loop

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1419]
setting `req.http.uri.query` to a new value result in an infinite loop here:

![screen shot 2018-01-10 at 8 56 33 pm](https://user-images.githubusercontent.com/1342803/34804888-dfb8941e-f648-11e7-9290-6ad89e9f1d81.png)

**Comment by Joannis** [comment]
Is this still a problem?

**Comment by tanner0101** [comment]
yes

**Comment by Joannis** [comment]
[Fixed in Engine/230](https://github.com/vapor/engine/pull/230) where I found some other URI related bugs. I'll fix those, too.
