### ISSUE TITLE
How to parse this data for json?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1421]
<img width="606" alt="12" src="https://user-images.githubusercontent.com/16829428/34833188-c90380da-f729-11e7-81ce-521c41de9e44.png">
 
![s](https://user-images.githubusercontent.com/16829428/34833315-18f79b3a-f72a-11e7-847b-25c0942648e6.png)

How to parse this data for json?
Thanks !

> English is not my native language; please excuse typing errors.

**Comment by twof** [comment]
Can you describe what you mean by parse? Do you want to interact with the JSON you provided from the client side?

**Comment by Jinxiansen** [comment]
Support to support Chinese display, I want to convert to unicode encoding.

**Comment by Jinxiansen** [comment]
@0xTim  Do you know how to convert utf8? Please give me a little advice !

**Comment by Jinxiansen** [comment]
@

**Comment by Jinxiansen** [comment]
@vzsg   
![success](https://user-images.githubusercontent.com/16829428/34907666-00b17318-f8bd-11e7-9639-61f43e4df68e.png)

Thank you very much brother for your help! By writing, you can solve this problem!

Thank you! 🤩
