### ISSUE TITLE
does it make sense to implement thread-safety to MemoryCache?

### ISSUE THREAD

**Issue by popaaaandrei** [vapor/vapor#1422]
Guys, currently MemoryCache is implemented as a pure Swift dictionary:
`private var _storage: [String: (Date?, Node)]` with normal get/get operations.

Should we add sync blocks or NSLock?

**Comment by tanner0101** [comment]
Did you get a bad access crash there? MemoryCache is only really meant for development, which is probably why locks were never added. But they sure wouldn't hurt. 

I think a private DispatchQueue w/ sync blocks would work well 👍

**Comment by Joannis** [comment]
Redis is also single-threaded, so that's equivalent to a DispatchQueue with sync blocks on a separate machine/process.

**Comment by popaaaandrei** [comment]
It didn't crash. Was just an observation. What I ended up doing is something like this:

```
class Cache {
    
    static let shared = Cache()
    private let _queue = DispatchQueue(label: "cacheQueue", attributes: .concurrent)
    private var _storage: [String: String]
   
    private init() {
        _storage = [:]
    }
    
    subscript(key: String) -> String? {
        get {
            var result: String? = nil
            
            _queue.sync {
                result = self._storage[key]
            }
            return result
        }
        set(newValue) {
            _queue.async(flags: .barrier) {
                self._storage[key] = newValue
            }
        }
    }

}
```

**Comment by Joannis** [comment]
@popaaaandrei you'll want both reading and switing to be `.sync()`, and without a concurrent queue for this to work 100% without crashes.

Also, dispatchQueue has a pretty neat thing where you can pass variables out of `.sync` blocks

```
get {
  return _queue.sync { self._storage[key] }
}
```

**Comment by popaaaandrei** [comment]
Why would it cause a crash with `.async(flags: .barrier)`?
The idea was to allow concurrent reads but using barrier for any write/append/delete operation.

**Comment by Joannis** [comment]
Concurrent reads are the reason you need thread-safety to prevent race conditions (and thus crashes)
