### ISSUE TITLE
How to configure vapor project .gitignore file?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1423]
**How to configure vapor project. Gitignore file? After each configuration I have compiled these two files have been produced, submitted after the other computer clone will fail to compile, it is too annoying!**

![a](https://user-images.githubusercontent.com/16829428/34877350-a5c439e0-f7e0-11e7-800f-70471fe668e1.png)
<img width="873" alt="ss" src="https://user-images.githubusercontent.com/16829428/34877354-a9f5d42e-f7e0-11e7-94b6-3c642d469355.png">

> English is not my native language; please excuse typing errors.

**Comment by 0xTim** [comment]
The template should include a gitignore, but you can view it [here](https://github.com/vapor/api-template/blob/master/.gitignore)
