### ISSUE TITLE
Why add a JSON Extension, but when prompted to use Type 'JSON' has no member 'result' ？

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1424]
![1](https://user-images.githubusercontent.com/16829428/34882911-f621a0d2-f7f2-11e7-9965-05f094375714.png)
![3](https://user-images.githubusercontent.com/16829428/34882912-f6639d8e-f7f2-11e7-8a01-0c197be2d580.png)

as the picture shows.

> English is not my native language; please excuse typing errors.

**Comment by Jinxiansen** [comment]
@vzsg Ok, but I wonder what the reason is?

**Comment by twof** [comment]
If you ask in the help channel on slack, you'll get a lot more answers than you would here :)

**Comment by linkfei** [comment]
@twof @vzsg   I have this problem too, can you tell me?

**Comment by vzsg** [comment]
It's probably a target membership issue - if the extension is not in the App target, it will not be visible in other files (and probably never compile either).

Another problem could be that you must add `try` before the call to JSON.result (line 20 in the first screenshot).

**Comment by Jinxiansen** [comment]
@vzsg  I tried, but it didn't work.😔
