### ISSUE TITLE
[Vapor 2] Routes can interfere with the serving of public files

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1427]
* Vapor Version: 2.3.0
* OS: macOS
* OS Version: 10.13.2 
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

Routes should not interfere with the serving of public files

### Current Behavior

Routes can interfere with the serving of public files.

### How to Reproduce

Create a new project with `vapor new foo --web`

Add this route to `routes.swift`:

```
builder.get(String.parameter, Int.parameter) { req in
    let langId = try req.parameters.next(String.self)
    let year = try req.parameters.next(Int.self)
    return "langId: \(langId) / year: \(year)"
}
```

Run the server and attempt to access `0.0.0.0:8080`

## Results

Rather than successfully serving the "It Works!" page, the image can't be found because the above route is triggered instead.

**Comment by tanner0101** [comment]
This is a known issue in Vapor 2. That's why we moved the FileMiddleware before the router in 3. 

Fixing this in 2.0 is likely to break code that relies on this behavior. Feel free to re-open if you want to discuss further.
