### ISSUE TITLE
Sessions Middleware

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1428]
Currently, Vapor 3's `SessionsMiddleware` does not allow the user to specify cookie options. Vapor 2 allows behavior like: 

```swift
let redisSessions = SessionsMiddleware(CacheSessions(redisCache)) { req -> Cookie in
    return Cookie(
        name: "vapor-session",
        value: "",
        expires: Date().addingTimeInterval(60 * 60 * 24 * 7), // 7 days
        secure: false,
        httpOnly: true,
        sameSite: .lax
    )
}
```

However, `SessionsMiddleware` now only allows for a `cookieName`. Vapor 3 should support the ability to change Cookie options, perhaps through a more "vapor way" like a service.

**Comment by 0xTim** [comment]
To add to this, it should be possible to make it dynamic. One use case is for an expiry time to be set if a user clicks 'Remember Me', but leave it empty (so it expires at the end of the session) if they don't tick it. Another thing I tend to do is set the `secure` flag when running in production but leave it as false for dev

**Comment by mcdappdev** [comment]
Agreed! I do the same thing with the secure flag.

**Comment by mcdappdev** [comment]
This actually already exists, as seen here: https://github.com/vapor/vapor/blob/beta/Sources/Vapor/Sessions/MemorySessions.swift. The `Sessions` protocol is now responsible for it based on the actual implementation (memory, redis, etc).

**Comment by 0xTim** [comment]
Hmm I'm going to reopen this - I feel like this is a bit of a code smell. You should be able to swap out the `Sessions` implementation and keep the same behaviour, the `Sessions` implementation should just be worried about where you save and retrieve the cookie. Also as a library (SteamPress) - I do not have control over what `Sessions` implementation an app is using so I would either have to provide an implementation for all of them or possibly degrade the user experience.

Open for discussion!

**Comment by mcdappdev** [comment]
Hmm ok, I see that point!

**Comment by tanner0101** [comment]
@0xTim idk how that old impl was left on memory session. The `SessionsConfig` struct is actually responsible for configuring cookies. It works exactly how you described. That old cruft will be removed in RC 2.
