### ISSUE TITLE
exclude file middleware by default

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1429]
File middleware should be excluded by default given:
- It's slow
- Most production use-cases will (and should) serve files via a reverse proxy or load balancer.
- It can be re-enabled in the web-template when `isRelease == false` to ease development where its needed

**Comment by 0xTim** [comment]
Would this just be a case of adding it to the middleware config if we want it?

**Comment by Joannis** [comment]
I prefer sticking to the last one. It's as bare as it gets and makes sense. The rest just feels like unnecessary amounts of sugar at this point. If we end up making more changes between API and Web configurations we could look into the a `MiddlewareConfig.default(for: .web)` solution.

**Comment by 0xTim** [comment]
Works for me to - that's the way I've done it in the videos
