### ISSUE TITLE
[Vapor 3] Memory leak when serving static files.

### ISSUE THREAD

**Issue by John-Connolly** [vapor/vapor#1434]
* Vapor Version: beta branch
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.0.3

### Current Behavior
The memory increases on every request.

### How to Reproduce
Serve a static file from a route.

**Comment by tanner0101** [comment]
cc @Joannis. I imagine the streaming File APIs will help this :)

**Comment by Joannis** [comment]
They sure will, they're in the works!

**Comment by Joannis** [comment]
#1449 aims to fix this

**Comment by tanner0101** [comment]
We've switched to foundation for the time being which definitely shouldn't leak anymore 👍
