### ISSUE TITLE
Restore `Extendable` conformance in `Request`

### ISSUE THREAD

**Issue by gwynne** [vapor/vapor#1436]
Being able to add arbitrary properties to `Request` is extremely useful for a number of use cases, most commonly associating additional contextual data with a request from middleware. Please put `Extendable` conformance back, even if Vapor itself doesn't use it anymore :)

**Comment by gwynne** [comment]
Per @tanner0101, it is possible to achieve the same result more performantly by registering singleton services with a `Request`'s `privateContainer`.

**Comment by gwynne** [comment]
Reopening for tracking ways of making the common case (adding stored properties) more concise, possibly evolving `Extendable`. Also per @tanner0101

**Comment by mcdappdev** [comment]
Thanks for the updates. I'm not sure I quite understand the solution that @tanner0101 presented. Does anyone have a code example?

**Comment by gwynne** [comment]
As posted by @tanner0101 (slightly edited for readability):

Step 1, create service:
```swift
final class AuthenticationCache: Service {
/// The internal storage.
```
Step 2, register as singleton:
```swift
services.register(isSingleton: true) { container in
    return AuthenticationCache()
}
```
Step 3, profit $$$:
```swift
extension Request {
    /// Authenticates the supplied instance for this request.
    public func authenticate<A>(_ instance: A) throws
        where A: Authenticatable
    {
        let cache = try privateContainer.make(AuthenticationCache.self, for: Request.self)
        cache[A.self] = instance
    }
```

The complement to authenticate:
```swift
/// Returns the authenticated instance of the supplied type.
/// note: nil if no type has been authed, throws if there is a problem.
public func authenticated<A>(_ type: A.Type) throws -> A?
    where A: Authenticatable
{
    let cache = try privateContainer.make(AuthenticationCache.self, for: Request.self)
    return cache[A.self]
}
```

**Comment by mcdappdev** [comment]
Hm. There has to be a better way to do it for simpler use cases

On Wed, Jan 17, 2018 at 6:45 PM, Gwynne Raskind <notifications@github.com> wrote:
As posted by @tanner0101 [https://github.com/tanner0101] (slightly edited for readability):

Step 1, create service:

finalclassAuthenticationCache: Service {
/// The internal storage.

Step 2, register as singleton:

services.register(isSingleton: true) { container inreturnAuthenticationCache()
}

Step 3, profit $$$:

extensionRequest {
    /// Authenticates the supplied instance for this request.publicfuncauthenticate<A>(_instance: A) throwswhere A: Authenticatable
    {
        let cache =try privateContainer.make(AuthenticationCache.self, for: Request.self)
        cache[A.self] = instance
    }

The complement to authenticate:

/// Returns the authenticated instance of the supplied type./// note: nil if no type has been authed, throws if there is a problem.publicfuncauthenticated<A>(_type: A.Type) throws-> A?where A: Authenticatable
{
    let cache =try privateContainer.make(AuthenticationCache.self, for: Request.self)
    return cache[A.self]
}

**Comment by 0xTim** [comment]
To add to this, once common use case I use this for is to save something in the request handler that is later used by a piece of middleware, such as how to long store a cookie for etc.

This would generally be fine unless you are writing a piece of middleware to release that relies on this - e.g. VaporSecurityHeaders. To allow per-page CSP to be used, you could save the configuration to the request's storage, which the middleware would then pick up later. The way things are currently is that I would require users to register this service, or release a provider to do this, which would have to be used, _only_ if they want per-page CSP. This may not necessarily be a bad thing, but it could cause confusion 🤷‍♂️ I'm torn!

**Comment by calebkleveter** [comment]
Why don't we have a default service that contains a dictionary of type `[String: Codable]` or something that has a couple of helper methods or subscripts with `Request`, so we can use the same syntax, but get the benefits of using Services?

**Comment by tanner0101** [comment]
What are the thoughts on this still? I know @calebkleveter created a package for this. Do we still need support on `Request`?

**Comment by mcdappdev** [comment]
I don’t need it anymore, I’d be interested to hear other people’s opinions

**Comment by calebkleveter** [comment]
It's a [line 49](https://codevapor.slack.com/archives/C4QRYJ6DD/p1515015290000160?thread_ts=1514985798.000268&cid=C4QRYJ6DD). Please, for the sake of my future sanity, add it 😉. It would take me about 10 minutes to submit a PR. Anything against me doing that?

**Comment by mcdappdev** [comment]
The "line 49" reference is out of date with that repo's current progress and will soon be lost to the Slack paywall. For historical purposes, Caleb is referring to an old discussion about extending `Request` with `DatabaseConnectable` conformance. In that case, it was one line of code.

**Comment by calebkleveter** [comment]
I'm trying to turn it into a Vapor community catchphrase/meme 😁.

**Comment by MrLotU** [comment]
👋 With #1822 and #1711 do we still need this issue? Especially since there are talks about not having Requests/Responses hold containers at all anymore in Vapor 4. (Trying to clean up some old/outdated ones)

**Comment by tanner0101** [comment]
I think it makes sense to close this in favor of #1822

**Comment by calebkleveter** [comment]
Closed in favor of https://github.com/vapor/vapor/issues/1822
