### ISSUE TITLE
[Vapor 3] WebSockets only send once in some use cases

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1438]
* Vapor Version: beta
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior
WebSocket should send string every time it executes 

### Current Behavior
String is only sent the first time

### How to Reproduce

Route where `ws.send()` works every time:

```
router.websocket("ping") { (req, ws) in
    ws.onString({ (ws, msg) in
        if msg == "ping" {
            ws.send(string: "pong")
        }
    })
}
```

Route where `ws.send()` only works the first time:

```
/// Example
/*
 {
     "date":537802942,
     "body":"hello!",
     "sender":"Me"
 }
*/
router.websocket("message") { (req, ws) in
    ws.onString { (ws, msg) in
        let decoder = JSONDecoder()
        let encoder = JSONEncoder()
        
        let allMessages
            = try decoder.decode(Message.self, from: msg.data(using: .utf8)!)
                .save(on: req)
                .await(on: req)
                .query(on: req)
                .all()
                .await(on: req)
        
        let allJSONMessages = try encoder.encode(allMessages).toString() ?? "error"
        
        ws.send(string: allJSONMessages)
    }
}
```

Note  that `ws.send(string: allJSONMessages)` is hit every time a string is sent to the route. Execution is not ending prematurely and `allJSONMessages` contains the correct string.

**Comment by tiwoc** [comment]
Have you tried adding a `ws.onError` block to see if there are errors while processing the data?

``` swift
ws.onError { ws, error in
    print("Error: \(error)")
}
```

In my case, I often get the following error:

> ⚠️ [WebSocket.WebSocketError.invalidMask: Masks must be 4 bytes, no more, no less] [/Users/redacted/.build/checkouts/engine.git-3311994267206676365/Sources/WebSocket/FrameParser.swift:213:39] [Possible causes: The mask provided was not 4 bytes long as per standard] [Suggested fixes: Generate 4 random bytes using any Random Number Generator for clients,Leave the mask empty (`nil`) for servers]

**Comment by twof** [comment]
@Joannis Suggested in Slack that the issue might be that I'm using `.await()` which should be avoided. I've updated my route to use `.map()` instead, but I'm seeing the same results.

@tiwoc Thanks for the suggestion! I am using `ws.onError()`, but it's never triggering.

```
router.websocket("message") { (req, ws) in
    ws.onString { (ws, msg) in
        let decoder = JSONDecoder()
        let encoder = JSONEncoder()
        let message = try decoder.decode(Message.self, from: msg.data(using: .utf8)!)
        
        message
            .save(on: req)
            .flatMap(to: [Message].self) { (_) -> Future<[Message]> in
                return Message.query(on: req).all()
            }.map(to: Void.self) { (allMessages) in
                let allJSONMessages = try encoder.encode(allMessages).toString() ?? "error"
                ws.send(string: allJSONMessages)
            }.catch({ (err) in
                print(err)
            })
    }

    ws.onError({ (ws, err) in
        print(err)
    })

    ws.onClose({ (ws, buff) in
        print(buff)
    })
}
```

**Comment by twof** [comment]
@Joannis I'm still experiencing this. Now the first `ws.send()` isn't going through either. The `ping` route however is still doing fine.
