### ISSUE TITLE
Add overloads for Client to accept HTTPRequest as well as Request types

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/vapor#1442]
### Motivation

It is a bit inconsistent when reading code, for a `Client` to accept a `Request` container with an additional `HTTPRequest`

### Code snippets

We can go from this
```Swift
let request = HTTPRequest()
httpClient.respond(to: Request(http: request, using: httpClient.container))
```
to this
```Swift
let request = HTTPRequest()
httpClient.respond(to: request)
```

**Comment by tanner0101** [comment]
this will be added to `Client` in 3.0.0!
