### ISSUE TITLE
`Request` -> `RequestContext`

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1443]
For better clarity between `Request` and `HTTPRequest`

**Comment by 0xTim** [comment]
Should this be `Request` -> `RequestContext` or is it just `Response` or is it both?

**Comment by twof** [comment]
It should definitely be `Request` -> `RequestContext`

**Comment by mcdappdev** [comment]
Oh yeah good catch, thanks.

**Comment by 0xTim** [comment]
@mcdappdev I've updated the title, feel free to change if it is something else!

**Comment by mcdappdev** [comment]
No that's perfect, thank you!

**Comment by tanner0101** [comment]
We'll need to postpone discussion on this one until Vapor 4. Even if we acted on this in January it would have been a bit too late. I'm open for other ideas on how we can clarify the difference between `Vapor.Request` and `HTTP.HTTPRequest` via docs or otherwise. Thanks @mcdappdev.

**Comment by mcdappdev** [comment]
No problem 👍🏻
