### ISSUE TITLE
Production should bind to port 8080, not 80

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1455]
Binding to port 80 makes the process privileged which is unsafe

**Comment by pedantix** [comment]
I think 8080 is a much better port to bind to by default. This, of course, can and should be overridable via arguments and configuration, that said port 80 should be "opt in" not "opt out". I actually contemplated a "forceSSL" flag as a configuration option but figured that it probably was somewhere that I just could not find.

**Comment by tanner0101** [comment]
This was changed back to 8080 a while back. 👍
