### ISSUE TITLE
Error import AppKit

### ISSUE THREAD

**Issue by narlei** [vapor/vapor#1456]
How can I import AppKit?

````
Compile Swift Module 'App' (5 sources)
/vapor/swiftapi-staging/code/Sources/App/Routes/Routes.swift:2:8: error: no such module 'AppKit'
import AppKit
       ^
error: terminated(1): /swift/4.0.2/usr/bin/swift-build-tool -f /vapor/swiftapi-staging/code/.build/release.yaml main
````

**Comment by 0xTim** [comment]
@narlei at the moment with Swift Package Manager there isn't an easy way to add AppKit to your projects. What's the reason for needing it?

**Comment by narlei** [comment]
I'm starting work with Machine learning and trying to use `NSLinguisticTagger` but need import AppKit

**Comment by calebkleveter** [comment]
It is important to note that the modules such as `AppKit`, `CoreML`, and other are only supported on macOS. `Foundation` is the only built-in module that is supported on Linux, so if you do use one of the other modules, you will have to host on macOS.

**Comment by narlei** [comment]
@calebkleveter very thank's!
