### ISSUE TITLE
Redis Pooling

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1457]
The Redis library should use connection pooling when handling requests

**Comment by Joannis** [comment]
I think it should be learning on pipelining instead

**Comment by mcdappdev** [comment]
@tanner0101 thoughts?

**Comment by tanner0101** [comment]
> I think it should be learning on pipelining instead

This does not make sense.

@mcdappdev moving here: https://github.com/vapor/redis/issues/84
