### ISSUE TITLE
Vapor 3's Client needs support for HTTP proxy configuration

### ISSUE THREAD

**Issue by gwynne** [vapor/vapor#1460]
There is currently no support whatsoever for HTTP/HTTPS/SOCKS proxies in the Vapor 3 codebase (at least not that I can find). This is not trivial to implement. Nor could one use `URLSession` to cheat because there's no proxy support in `swift-corelibs-foundation` yet either (the Linux build is using `libcurl` for URL sessions, which _does_ know about proxies, but so far the implementation is not passing the proxy parameters down the line).

Simple HTTP proxying requires nothing more than making the appropriate additions to the URI. HTTPS proxying sometimes requires massaging the `Request` to use the `CONNECT` method, processing the proxy's initial response, and then restarting the request over the proxied connection, typically if the proxy is plain HTTP but the desired URL is HTTPS. I know this process holds true for HTTP/1.x, I don't know if there's something different in HTTP/2 - I would tend to assume so.

SOCKS proxying is more complicated by far and is probably not in common enough use to be worth it, at least not right away.

Dropping this in the 3.0.0 milestone because while SOCKS is definitely out of scope, it doesn't seem like it'd be too hard to do the HTTP/HTTPS proxying support.

(Worth noting, Vapor 2's "support" for proxies was imperfect; it only did the URI part, never a `CONNECT` method.)

**Comment by tanner0101** [comment]
Fixed by #1529
