### ISSUE TITLE
Vapor cloud deploy failed: Sockets Error: Failed trying to connect to http://redis.eu.vapor.cloud:6379

### ISSUE THREAD

**Issue by setoelkahfi** [vapor/vapor#1465]
* Vapor Version: 2.4.2
* OS: macOS High Sierra
* OS Version: 10.13.3
* Vapor Toolbox Version: 3.1.3

I setup Vapor project manually with swift package manager. I follow the documentation. 
It build and runs successfully in my local machine, both for debug and release build.

But it failed to deploy to vapor cloud:

```
    ....
    ....
    env: development
    db: none
    replicas: 1
    replica size: free
    branch: development
    build: clean
    Creating deployment [Done]
    Connecting to build logs ...
    Waiting in Queue [Failed]
    Error: Sockets Error: Failed trying to connect to http://redis.eu.vapor.cloud:6379
    
    Identifier: Sockets.SocketsError.connectFailed
    
    Here are some possible causes: 
    - The hostname or port is not valid    
```

Anyone knows what caused this error?

[SO thread](https://stackoverflow.com/q/48459487/1137814).

**Comment by joscdk** [comment]
Hi, It's usually caused by either a firewall, or a proxy preventing connection to our Redis cluster, that is providing log feedback to the terminal.

We have seen it a couple of times, and are working on allowing to see log output in the dashboard, for these kind of situations :)

**Comment by setoelkahfi** [comment]
Hi @joscdk , so what should I do to overcome this issue?

**Comment by nhatlee** [comment]
After deploy successful I got the link didn't work [Link](https://swiftwithlove-swiftwithlove.vapor.cloud). Please help me :(

**Comment by nhatlee** [comment]
The result in my terminal:
<img width="601" alt="screen shot 2018-04-19 at 9 00 01 am" src="https://user-images.githubusercontent.com/7148482/38967188-1e8af178-43b0-11e8-967a-625cf3655491.png">

**Comment by setoelkahfi** [comment]
What's is the status in the vapor dashboard?

**Comment by nhatlee** [comment]
What did you mean with vapor dashboard? how to check it's status?

**Comment by nhatlee** [comment]
@vzsg could you help me?

**Comment by vzsg** [comment]
No, Vapor Cloud is not my strong suit. But listen, could you join [Vapor's Slack community](https://vapor.team), then the cloud-help channel? It would be much more effective then resurrecting long-closed issues.

**Comment by joscdk** [comment]
@nhatlee the app seem to be working: https://swiftwithlove-swiftwithlove.vapor.cloud/nhatlee :)

**Comment by nhatlee** [comment]
@joscdk : Yes, I am missing `/nhatlee` before reported :|.

**Comment by n0an** [comment]
@joscdk how did you solve this? got the same error, when trying to run vapor cloud deploy command

**Comment by joscdk** [comment]
@n0an which error do you get?

**Comment by n0an** [comment]
Error: Error: Sockets Error: Failed trying to connect to https://api.vapor.cloud:443
Identifier: Sockets.SocketsError.connectFailed
Here are some possible causes: 
- The hostname or port is not valid

**Comment by setoelkahfi** [comment]
For my case back then, it's because of my internet connection at my office. I change it to my mobile data plan and it's worked.

**Comment by n0an** [comment]
Yes, it was due to internet connection for me either. From home all working ok.
