### ISSUE TITLE
Updating apt.sh to Support Linux Mint

### ISSUE THREAD

**Issue by MCDELTAT** [vapor/vapor#1471]
## Updating apt.sh to Support Linux Mint

* Author: [Aaron Chamberlain](https://github.com/MCDELTAT)

### Introduction

Vapor only supports Ubuntu 14.04, 16.04 and 16.10, due to Swift Support on Linux. I have tested Vapor compatibility in Linux Mint 18.0-18.3, all derivatives of Ubuntu 16.04. My patch updates apt.sh so that a Linux Mint user can simply run the instructions on the website without any changes.

### Motivation

I use Linux Mint as my daily driver while programming and keep having to remind myself to manually setup the Vapor repo. This change allows me to just run apt.sh like everyone else without extra steps. Linux Mint reports it's $DISTRIB_CODENAME as the actual [codename](https://en.wikipedia.org/wiki/Linux_Mint_version_history) like "sarah" or "sonya", and thus break URLs to the main repositories. They are however completely compatible with the "xenial" repo, since they are Ubuntu 16.04. 

### Proposed solution

I tried to be as clean as possible in the new version of the Bash script, by simply making an array of all Mint versions that I've tested and found working (by installing and getting at least to the CLI). The script now checks for a longer list of Ubuntu and Linux Mint compatible distros and if one of the Mint CODENAME's are present, changes it to "xenial" to use the regular repository. My method should also make it easy to update in the future when we deprecate or add newly supported distros because we can just add them to the array.

### Code snippets

If accepted, I'll go ahead and submit a pull request with my modified script immediately. Note that I did leave out the 4 other Codenames for the 17.x (14.04) variants, but they can easily be added if we want it. My modified version is as follows:
```
function contains() {
  local n=$#
  local value=${!n}
  for ((i=1;i < $#;i++)) {
      if [ "${!i}" == "${value}" ]; then
        echo "y"
        return 0
      fi
  }
  echo "n"
  return 1
}

function add_vapor_apt() {
  systems=( "xenial" "yakkety" "trusty" "sarah" "serena" "sonya" "sylvia" )
  xenial=( "sarah" "serena" "sonya" "sylvia" )
  eval "$(cat /etc/lsb-release)"

  # if your distrib codename isn't in systems, we haven't tested it as working
  if [ $(contains "${systems[@]}" "$DISTRIB_CODENAME") == "n" ]; then
    echo "Only Ubuntu 14.04, 16.04, and 16.10 are supported."
    echo "You are running $DISTRIB_RELEASE ($DISTRIB_CODENAME) [`uname`]"
    return 1;
  fi

  # if mint change CODENAME to xenial so that repos are pointed to correct URL
  if [ $(contains "${xenial[@]}" "$DISTRIB_CODENAME") == "y" ]; then
    DISTRIB_CODENAME="xenial"
  fi
  export DEBIAN_FRONTEND=noninteractive

  if ! [ $(id -u) = 0 ]; then
      export SUDO=sudo
  fi

  $SUDO apt-get -q update
  $SUDO apt-get -q install -y wget software-properties-common python-software-properties apt-transport-https
  wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | $SUDO apt-key add -
  echo "deb https://repo.vapor.codes/apt $DISTRIB_CODENAME main" | $SUDO tee /etc/apt/sources.list.d/vapor.list
  $SUDO apt-get -q update

  unset DEBIAN_FRONTEND
  unset SUDO
}

add_vapor_apt;
```

### Impact

Nothing should stop compiling, it just needs to be tested by other users to make sure I didn't break the install, which would be bad. The good part is that I and hopefully a few Linux Mint users will be happy. Easier toolchain setup makes happy devs.

### Alternatives considered

None but I'd welcome feedback since I'm not that great at BASH.

**Comment by 0xTim** [comment]
@MCDELTAT the best place to raise this issue would be the Vapor APT repo - https://github.com/vapor/apt

**Comment by MCDELTAT** [comment]
@0xTim Why would that be? The file that needs to be updated is here in Utilities/apt.sh and thus my pull request would be against this repo. The apt repo you sent me to is just the version control of swift and vapor releases along with the build configs that get run after apt.sh is run.

**Comment by 0xTim** [comment]
@MCDELTAT ignore me then! I misread your issue, Move along, nothing to see here.... 😝

**Comment by MCDELTAT** [comment]
Any update on this? Also I was wondering how compatible this is since Array support varies between shells.

**Comment by tanner0101** [comment]
Tagging @joscdk. Would this have any unintended side effects for/ our APT repos?

**Comment by MCDELTAT** [comment]
Any update on this? This will probably have to be discussed sooner or later since Ubuntu 18.04 is coming out and Swift Support may change around the same time at WWDC. It's been working peachy for me though.

**Comment by joscdk** [comment]
Hmm github didn't want to notify me before now :)

Great addition, I am a fan :)

@tanner0101 no since it just uses xenial no changes to apt should be required.

**Comment by joscdk** [comment]
@MCDELTAT closing this issue based on inactivity, you seem to have a pretty good idea how to make this work, so if you want, feel free to open a PR to change the file, if you still need this change.

If you want this feature but can't open PR, reopen and we will see if others are up for making the change.

**Comment by dev01d** [comment]
Misunderstood this issue. The above PR does not address the Linux Mint compatibility.
