### ISSUE TITLE
Server crashed on about 300 websocket connections

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/vapor#1472]
### Environment

* Vapor Version: 2.4.4
* OS: Ubuntu (DigitalOcean Droplet $5 1024Mb RAM)
* OS Version: 16.04.3
* Vapor Toolbox Version: 3.1.2

### Expected Behavior

Stable work

### Current Behavior

Server crashes on ~300 connections with message

```javascript
Identifier: Sockets.SocketsError.acceptFailed

Here are some possible causes: 
- `bind` has not been called first
- `listen` has not been called first)
```

### How to Reproduce
Configure Vapor API project with socket route at path `/primus` and run it
```swift
extension Droplet {
    func setupRoutes() throws {
        socket("primus") { (req, ws) in
            background {
                while ws.state == .open {
                    try? ws.ping()
                    self.console.wait(seconds: 10) // every 10 seconds
                }
            }
            
            ws.onText = { ws, text in
                print("Text received: \(text)")
            }
            
            ws.onClose = { ws, code, reason, clean in
                print("Closed.")
            }
        }
    }
}
```

Then from another machine with node.js install `websocket-bench` from https://github.com/M6Web/websocket-bench

```javascript
npm install -g websocket-bench
```

And run the benchmark with the following example command

```javascript
websocket-bench -a 500 -c 300 -t primus -p websockets -k ws://VAPOR_IP_HERE:8080
```

or

```javascript
websocket-bench -a 1000 -t primus -p websockets -k ws://VAPOR_IP_HERE:8080
```

First several minutes Vapor will serve requests normally, but then it will crash.

**Comment by Joannis** [comment]
Hello @MihaelIsaev, thanks for the report. I can't promise when we'll look into it with the upcoming Vapor 3 release on the agenda. If you're looking for a high performance websocket connection I think you'll have a lot more luck with Vapor 3.

**Comment by vishnuag05** [comment]
@MihaelIsaev Hi , Can you please help me with deploying this to digital ocean. I have working code of vapor installed in my macbook and I have server address , droplet and rsa id for digital ocean. Now being a ios developer , I never worked with swift so I request you to point me into right direction.

**Comment by MihaelIsaev** [comment]
Hey @vishnuag05 have you tried [this instruction](https://www.digitalocean.com/community/tutorials/how-to-install-swift-and-vapor-on-ubuntu-16-04)? 🙂

**Comment by vishnuag05** [comment]
hey thanks for reverting back. 
No I havent tried it , I will check this thanks.

**Comment by Joannis** [comment]
@tanner0101 this issue is assigned to Vapor 3 but is reported for Vapor 2.

**Comment by Joannis** [comment]
I can _try_ to solve this for Vapor 2, but it's more of an architectural problem as far as my knowledge of Vapor 2's internals go.

**Comment by tanner0101** [comment]
This was very likely fixed with NIO, thanks!
