### ISSUE TITLE
Vapor 3 ambiguous module naming

### ISSUE THREAD

**Issue by Obbut** [vapor/vapor#1478]
Modules like TCP are likely to collide

CC @Joannis

**Comment by mikecsh** [comment]
SQLite and Mustache are additional examples where I have encountered collisions

**Comment by tanner0101** [comment]
> likely to collide
smells like premature optimization to me
> have encountered collisions
please link any examples of you of naming collisions!

**Comment by Joannis** [comment]
@tanner0101 regardless of premature optimization, this is not something that can be fixed as an afterthought

**Comment by mikecsh** [comment]
@tanner0101 for example, GRMustache.swift (https://github.com/groue/GRMustache.swift) declares a package called Mustache, which conflicts with Vapor's Mustache library created by TemplateKit. Additionally, SQLite.swift (https://github.com/stephencelis/SQLite.swift) declares a target called SQLite which conflicts with Vapor's SQLite.

For us, this causes an issue as we have an internal package that uses these dependencies, which we want to use Vapor as a front-end for, but as it is we seem to need to maintain separate forks with altered package names which is less than ideal.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion since February 2018, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
