### ISSUE TITLE
Client Post Request has a content length of 0

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1481]
* Vapor Version: 51e85d8fde64b7f1a402d43096ab1b1a4477a1f8\
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox Version: 3.1.2

### Expected Behavior
Content length should be set automatically based on size of content

### Current Behavior
Content Length is always 0

### How to Reproduce
Here's my route. It hits MailGun, and returns the response from MailGun

```swift
router.get("mail") { (req) -> Future<Response> in
    struct MailgunFormData: Content {
        static let defaultMediaType: MediaType = MediaType.urlEncodedForm
        
        let from: String
        let to: String
        let subject: String
        let text: String
    }

    let client = try req.make(Client.self)
    let encode: (String) -> String = Base64Encoder(encoding: .base64).encode
    let authKey = encode("api:key-redacted")

    let headers = HTTPHeaders(dictionaryLiteral:
        (HTTPHeaderName.authorization, "Basic \(authKey)"),
        (HTTPHeaderName.contentType, "application/x-www-form-urlencoded")
    )

    let mailgunURL = "https://api.mailgun.net/v3/mg.redacted.me/messages"

    let content: MailgunFormData = MailgunFormData(
        from: "postmaster@twof.me",
        to: "redacted@gmail.com",
        subject: "Newsletter",
        text: "This is a newsletter"
    )

    return client
        .post(mailgunURL, headers: headers, content: content)
        .map(to: Response.self) { (response) in
            return response
        }.catch { (err) in
            print(err)
        }
}
```

Any requests to the route hang, but I think that's already been reported. Inspecting `response` at `return response` shows that Mailgun doesn't believe it ever received a "from" parameter. Stopping execution at `Client.swift` line 40, shows that the Content Length of the request being sent out is 0.

**Comment by johnbona** [comment]
On Vapor 3 beta 3.1, the request no longer hangs for HTTPS requests however, I too am seeing the Content-Length header being set to 0 for any Client method that calls `send()` with content.

If you rewrite the request to the below, the Content-Length header is set correctly:
```swift
let content = MailgunFormData(
	from: "postmaster@twof.me",
	to: "redacted@gmail.com",
	subject: "Newsletter",
	text: "This is a newsletter"
)

let body = try JSONEncoder().encodeBody(from: content)
let httpRequest = HTTPRequest(method: .post, uri: URI(mailgunURL), headers: headers, body: body)

return try client
	.respond(to: Request(http: httpRequest, using: client.container))
	.map(to: Response.self) { (response) in
		return response
	}.catch { (err) in
		print(err)
	}
```

**Comment by johnbona** [comment]
After doing some more digging, think I found the source of the issue in [Client.swift#22](https://github.com/vapor/vapor/blob/be9a2681e06b5d29419c14c493e48032d0c08743/Sources/Vapor/Engine/Client.swift#L22).

The headers right before `req.http.headers = headers` are: 
```
Content-Length: 93
Content-Type: application/json; charset=utf-8
```

But since `req.http.headers` is being reassigned to the `headers` parameter, they're overwritten:
```
Content-Length: 0
Authorization: Basic ...
```

**Comment by tanner0101** [comment]
Ah, I see. Two problems:
- `let headers: HTTPHeaders = [:]` should not contain `Content-Length: 0`. 
- The client should set the headers iteratively
- There should probably be some validation that the Content-Length header is correct during the serialization step, but this has huge performance implications.

**Comment by tanner0101** [comment]
Fixed: https://github.com/vapor/vapor/pull/1502
