### ISSUE TITLE
techempower benchmark

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1496]
Get Vapor 3 passing on Techempower benchmarks. 
- https://github.com/TechEmpower/FrameworkBenchmarks/pull/3242
- https://github.com/TechEmpower/FrameworkBenchmarks/pull/3210
- https://github.com/TechEmpower/FrameworkBenchmarks/issues/3181

**Comment by fafhrd91** [comment]
Test results available on https://tfb-status.techempower.com

**Comment by bre7** [comment]
On it with Vapor3 GM: https://github.com/TechEmpower/FrameworkBenchmarks/pull/3683

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
