### ISSUE TITLE
Can't have an HTTP and Websocket route with the same path

### ISSUE THREAD

**Issue by twof** [vapor/vapor#1504]
* Vapor Version: 3.0.0-beta.3.1.2
* OS: macOS
* OS Version: 10.13.2
* Vapor Toolbox: 3.1.4

### Expected Behavior
Websocket and HTTP routes should be treated separately, allowing one of each with the same path.

### Current Behavior
If you have one of each with the same path, it's impossible to connect to the Websocket

### How to Reproduce

```
router.websocket("joe") { (req, ws) in
}

router.get("joe") { (req) in
  return Future("Hello")
}
```

Attempt to connect to `ws://localhost:8080/joe` and it should fail

**Comment by Joannis** [comment]
WebSocket routes are a GET route that gets upgraded. The machanism you describe would require 2 handlers on the same route (one being a fallback), that would require a signficant workaround to be developed in Vapor 3 which I'm not fond of. Instead, you could check for and upgrade the websocket inside your GET route manually.

**Comment by twof** [comment]
Ahhh gotchya. I wasn't clear on the interaction between HTTP and websockets. Thanks! Feel free to close this then.
