### ISSUE TITLE
Different syntax for specifying params should work too

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#1514]
when launching from bash I believe all this should work:
```ruby
--port 9090
--port=9090
--port="9090"
```

**Comment by Joannis** [comment]
I agree with this. I tend to mix the different methods like above.

**Comment by tanner0101** [comment]
```sh
--port 9090
--port "9090"
```

Those two should work. For any discussion about changing the argument parsing, please open on vapor/console repo.
