### ISSUE TITLE
Beta branch doesn't build

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1516]
The beta branch doesn't compile any longer.  I'm following a raywenderlich.com tutorial showing how to use vapor 3 to build and API and they use the --branch=beta flag.

### Steps to reproduce

vapor new foo --branch=beta
cd foo
vapor xcode -y
Change the target to Run and My Mac
Hit build.

### Expected behavior

Should compile cleanly.

### Actual behavior

Get's 98 compile time errors.

### Environment

* Vapor Framework version: 3.0.0-rc.1
* Vapor Toolbox version: 3.1.4
* OS version: 10.13.3

**Comment by joscdk** [comment]
Which Swift version are you using?

**Comment by grosch** [comment]
The default for an Xcode 9.2 project.  I also tried adding a .swift-version file with 4.1 and that didn't make things any better.

**Comment by grosch** [comment]
I just tried with 4.0 as well, same results.  I see the Package.swift has a swift-tools-version:4.0 comment in there.

**Comment by grosch** [comment]
Looks like the only "real" errors are coming from the Async dependency.  The rest all fail because that fails.

![screen shot 2018-02-24 at 10 48 24 am](https://user-images.githubusercontent.com/315966/36633807-4c743d72-1950-11e8-9b8a-40269be58000.png)

**Comment by joscdk** [comment]
Vapor 3 need Swift 4.1, so you need to setup the Swift 4.1 toolchain in Xcode, you can find the toolchain on swift.org

**Comment by grosch** [comment]
Apologies.  I have that installed and just forgot I needed to use it.
