### ISSUE TITLE
JSON Response Hangs infinitely

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1518]
**Note:** The source code for this project was provided to Tanner and Joannis privately. 

When trying to parse a JSON response from a `EngineClient` `get` call, the program hangs infinitely when the JSON payload is around Content-Length 8000. Smaller payloads (Content-Length 500ish) seem to resolve just fine. 

@Joannis thinks it has something to do with the second half of the body not making its way to the HTTP Parser (feel free to correct me if I got that wrong, Joannis). 

Thanks!

**Comment by tanner0101** [comment]
Looks like a regression. Fixed here: https://github.com/vapor/vapor/pull/1519
