### ISSUE TITLE
404 for any requests in RC1

### ISSUE THREAD

**Issue by KieranHarper** [vapor/vapor#1521]
Hey I'm newish to Vapor - been successfully playing around with the v3 alpha/beta versions that could run on swift 4.0, but now that I'm on RC1 (and Swift 4.1) suddenly all of my requests 404. Not sure if this is a Vapor problem or something with this particular Swift snapshot?

Just gave RC 1.1 a go and it doesn't change anything for me :(

### Steps to reproduce

Here's a stripped back demo project that exhibits the problem for me:
[RC1Test.zip](https://github.com/vapor/vapor/files/1760267/RC1Test.zip)

Install swift 4.1 snapshot from Feb 25 (current latest)
Unpack the attached demo project files
Run vapor xcode
Open Xcode project
Check that 4.1 toolchain is selected
Build and run
Use a browser/postman etc to GET http://0.0.0.0:8080/ping

### Expected behavior

Should 200 and return a string of "123"

### Actual behavior

404 not found

### Environment

* Swift version: 4.1-dev (LLVM 1c8b50929b, Clang 420ae40df6, Swift 4ebcde867a)
* Vapor Framework version: 3.0.0-rc.1.1
* Vapor Toolbox version: 3.1.4
* OS version: 10.13.2

**Comment by 0xTim** [comment]
@KieranHarper the way the router should be registered has changed - have a look at the [current API template](https://github.com/vapor/api-template/blob/beta/Sources/App/configure.swift#L16) for how to register the router - your `boot()` function should be empty

**Comment by KieranHarper** [comment]
Ah yes, that's sorted it out. Thanks!
