### ISSUE TITLE
While waiting on breakpoint, TLSSocketSink.swift falls on try! socket.handshake() 

### ISSUE THREAD

**Issue by givip** [vapor/vapor#1527]
While waiting on breakpoint, TLSSocketSink.swift falls on try! socket.handshake() 

### Steps to reproduce

Put breakpoint on marked _return_ statement and **wait 1-2 minutes**

```swift
let request = Request(http: httpRequest, using: client.container)
let response = try client.respond(to: request)

⛔️return response.flatMap(to: BlahModel.self) { (response) -> Future<BlahModel> in
	return try response.content.decode(BlahModel.self)
     }
```

### Expected behavior

If TLS not established, waiting for correct error of automatically retry.

### Actual behavior

TLSSocketSink.swift falls on try! socket.handshake() line 128

> Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ Apple TLS Error: connection closed via error
> - id: AppleTLSError.-9806
> 
> File: /Users/givi/Documents/ServerSide/Vapor3/Telegrammer/.build/checkouts/tls.git-2678149690400510061/Sources/AppleTLS/AppleTLSSocket.swift
>  - func: handshake()
>  - line: 89
>  - column: 66
> : file /Users/buildnode/jenkins/workspace/oss-swift-4.1-package-osx/swift/stdlib/public/core/ErrorType.swift, line 184
> 2018-02-27 22:33:38.889687+0300 Run[41113:1202991] Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ Apple TLS Error: connection closed via error
> - id: AppleTLSError.-9806
> 
> File: /Users/givi/Documents/ServerSide/Vapor3/Telegrammer/.build/checkouts/tls.git-2678149690400510061/Sources/AppleTLS/AppleTLSSocket.swift
>  - func: handshake()
>  - line: 89
>  - column: 66
> : file /Users/buildnode/jenkins/workspace/oss-swift-4.1-package-osx/swift/stdlib/public/core/ErrorType.swift, line 184

### Environment

* Vapor Framework version: 3.0.0-rc.1
* Vapor Toolbox version: 3.1.4
* OS version: macOS 10.13.3 (17D102)

**Comment by tanner0101** [comment]
Moved to https://github.com/vapor/tls/issues/67
