### ISSUE TITLE
3.0 RC: String parameter type does not work

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#1531]
Using a `String.parameter` does not work.

```swift
router.get("cores", String.parameter, "solar", use: solarController.getSolarForCoreByDeviceID)
```

### Steps to reproduce

Create a route that takes a string parameter:

```
router.get("cores", String.parameter, "solar", use: solarController.getSolarForCoreByDeviceID)
```

Calling the endpoint (e.g. `{{ url  }}/cores/somestring/solar`) will lead to the following error:

```
[ ERROR ] RoutingError.invalidParameterType: Invalid parameter type. Expected String got [99, 111, 114, 101] (ParameterContainer.swift:69)
```

### Expected behavior

I expect a `String.parameter` to not fail when called with a string :)

### Actual behavior

The request fails with:

```
Oops: Invalid parameter type. Expected String got [99, 111, 114, 101]
```

### Environment

* Vapor Framework version: 3.0 RC
* Vapor Toolbox version: n/a
* OS version: High Sierra

**Comment by 0xTim** [comment]
@4np can you post the route handler code as well? `solarController.getSolarForCoreByDeviceID`

**Comment by 4np** [comment]
@0xTim : when I set a breakpoint on the implementation in the controller it does not get hit at all. But adding the (wip) implementation here as well:

```
    func getSolarForCoreByDeviceID(_ req: Request) throws -> Future<SolarInfo> {
//        let deviceID = try req.parameters.next(String.self)
        let deviceID = try req.parameter(String.self)
        print("device id: \(deviceID)")
        
        return Core.query(on: req).filter(\Core.deviceID == deviceID).first().flatMap(to: SolarInfo.self) { (core) -> Future<SolarInfo> in
            guard let core = core else {
                throw Abort(.notFound, reason: "No such core")
            }
            
            let solarInfo = SolarInfo(sunrise: core.sunrise, sunset: core.sunset)
            return Future<SolarInfo>(solarInfo)
        }
    }
```

**Comment by 0xTim** [comment]
Just verified this - does not work at all. This guard is not succeeding:
```swift
guard current.slug == [UInt8](P.uniqueSlug.utf8) else { ...
```

**Comment by 4np** [comment]
Looks like the `[UInt8]` doesn't get transformed into a string? 
https://github.com/vapor/routing/blob/master/Sources/Routing/ParameterContainer.swift#L65

**Comment by 0xTim** [comment]
@4np can you open this bug in that repo?

**Comment by 4np** [comment]
Yeah, I'll move it... 👍

**Comment by 4np** [comment]
Closing in favour of [Routing #36](https://github.com/vapor/routing/issues/36)
