### ISSUE TITLE
3.0-RC: Command line arguments don't work

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#1533]
Supplying command line arguments doesn't work, even though [the code](https://github.com/vapor/vapor/blob/bcc324449ed828ab55cf4bb0b662ccc1e7206165/Sources/Vapor/Commands/CommandConfig.swift#L71) seems to suggest the should.

### Steps to reproduce

1. Add the following lines to dump the environment in `configure.swift`:

```
    print("environment:")
    dump(env)
```

2. Build and run with arguments:

```
$ swift build
$ .build/x86_64-apple-macosx10.10/debug/Run serve     
environment:
▿ Service.Environment
  - name: "development"
  - isRelease: false
Running on macOS in debug environment
Migrating psql DB
Migrations complete
Server starting on http://127.0.0.1:8080
$ .build/x86_64-apple-macosx10.10/debug/Run --env=prod
environment:
▿ Service.Environment
  - name: "development"
  - isRelease: false
Running on macOS in debug environment
Migrating psql DB
Migrations complete
Fatal error: Error raised at top level: ⚠️ CommandError: Too many arguments or unsupported options were supplied: ["--env=prod"]
- id: CommandError.excessInput

File: /path/to/.build/checkouts/console.git--2431895819212044213/Sources/Command/CommandContext.swift
 - func: make(from:console:for:)
 - line: 80
 - column: 33
: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-902.0.41/src/swift/stdlib/public/core/ErrorType.swift, line 191
Illegal instruction: 4
$ 
```

3. Note that supplying command line arguments fails and the environment remains `development` with `isRelease` set to `false`

4. Build for release and run:

```
$ swift build --configuration release
...
$ .build/x86_64-apple-macosx10.10/release/Run serve
environment:
▿ Service.Environment
  - name: "development"
  - isRelease: false
Running on macOS in release environment
Migrating psql DB
[PostgreSQL] dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "Cannot initialize PostgreSQLAuthenticationType from invalid Int32 value 8", underlyingError: nil))
^C$ .build/x86_64-apple-macosx10.10/release/Run serve --env=prod
environment:
▿ Service.Environment
  - name: "development"
  - isRelease: false
Running on macOS in release environment
Migrating psql DB
[PostgreSQL] dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "Cannot initialize PostgreSQLAuthenticationType from invalid Int32 value 8", underlyingError: nil))
^C$
```

5. Note that when build for release, `isRelease` remains `false` and additional command line arguments don't seem to work.
6. Additionally, note that `PostgreSQL` does not work when supplying a password (see [fluent-postgresql issue #22](https://github.com/vapor/fluent-postgresql/issues/22))

### Expected behavior

1. when building for release I expect `isRelease` to be true
2. when supplying command line arguments for `environment` (like so: `--env=prod`) I expect them to be set properly in the application's environment.

### Actual behavior

Command line arguments don't seem to work.

### Environment

* Vapor Framework version: 3.0-RC
* Vapor Toolbox version: idem
* OS version: Mac OS High Sierra & Ubuntu 16.04

**Comment by 4np** [comment]
Update, without `=` this `does` seem to work:

```
.build/x86_64-apple-macosx10.10/release/Run serve --env prod
environment:
▿ Service.Environment
  - name: "production"
  - isRelease: true
```

Although I would still expect the release build to `always` have `isRelease: true`, regardless of the environment arguments.

**Comment by tanner0101** [comment]
`--key=val` format is no longer supported in Vapor 3. We're trying to match Unix standards better.

> Although I would still expect the release build to always have isRelease: true, regardless of the environment arguments:

We print a warning if you are in dev mode w/ release build, but I don't think the framework should force that. It's very common to need release build for some performance reasons, but you still want dev config.
