### ISSUE TITLE
Need to do migration at a later stage

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#1541]
I would like to do an installer where the user goes through a "setup wizard" to put in database and other details, tests the connection, smtp ... etc.

It would be amazing if we could do the configuration/migrations at any time we need.

**Comment by SandorDobi** [comment]
You can use/make a custom provider like MyInstallServiceProvider...
register this BEFORE any other service.

Write the setup logic in the boot section. Configure database etc. 
After that the Fluent***Provider will run and do the migration.
Is this enough for this purpose?

**Comment by tanner0101** [comment]
See https://github.com/vapor/service/issues/16. Also see https://github.com/vapor/vapor/blob/master/Sources/Vapor/Services/VaporProvider.swift. :)
