### ISSUE TITLE
Docs for Hello, World > Routing are ambiguous

### ISSUE THREAD

**Issue by blwinters** [vapor/vapor#1544]
The first line of the [section on Routing](https://docs.vapor.codes/2.0/getting-started/hello-world/#routing) has me a little confused, perhaps the method name has changed since the docs were written. 

It says: "In the scope of the `build` method, look for the following statement." However, the only method inside Routes.swift is `setupRoutes()`. This is probably just an outdated method name, but please let me know if I am misunderstanding it. Thanks for all your hard work!

**Comment by bojanstef** [comment]
You're right, `build` was renamed to `setupRoutes`
It looks like [this commit](https://github.com/vapor/documentation/commit/35c4db048e233549b575458262c750271855b9e9#diff-450b99a92576d28423772e1d70b872d7) is where that was changed.
