### ISSUE TITLE
Is there any documentation about Facebook and Google login?

### ISSUE THREAD

**Issue by cikpis** [vapor/vapor#1549]
Hey guys! Awesome work! 

I was just wondering if there is any documentation about Facebook and Google login. 

Any tips?

**Comment by calebkleveter** [comment]
Maybe look at [Imperial](https://github.com/vapor-community/Imperial)? It uses Vapor 3, so you would have to be on that version and isn't quite updated yet (I hope to get that done in ~1h). Also that documentation hasn't been updated and it only supports Google and Facebook.

If that sounds to complicated, you can look at the routes for authenticating:
- https://github.com/vapor-community/Imperial/blob/master/Sources/Imperial/Services/Google/GoogleRouter.swift#L24
- https://github.com/vapor-community/Imperial/blob/master/Sources/Imperial/Routing/FederatedServiceRouter.swift#L61

And work it out from there.

**Comment by cikpis** [comment]
I’ve read something about Turnstile. Is that outdate too?

**Comment by calebkleveter** [comment]
Yes, it was remove in v2, so unless your still on v1 , that's not something that can be used.

**Comment by cikpis** [comment]
Just looking at Imperial and yes, it’s quite unfriendly for a newbie xD

How come there is no well documented guide about Facebook and Google login? Any particular reason? I’m just wondering if make sense to my company invest time on Vapor or not.

**Comment by calebkleveter** [comment]
If you are asking about Vapor 2, I am not really sure. I guess it wasn't really in scope for the Vapor docs and no one in the community ever looked at creating a tutorial or anything for it.

For Vapor 3 documentation is incomplete and tutorials are more or less scarce.

**Comment by cikpis** [comment]
Do you know when the docs for Vapor 3 about those social login will be updated?

**Comment by calebkleveter** [comment]
I don't. There is a good chance that there won't be any even when the docs are complete.

I will keep working on Imperial and do my best to add support for more OAuth providers, at which point social auth will be trivial to implement.

**Comment by 0xTim** [comment]
Just to add to this - there is a planned chapter on Facebook/Google authentication in the upcoming Ray Wenderlich book

**Comment by cikpis** [comment]
@0xTim are you referring to this? https://store.raywenderlich.com/products/server-side-swift-with-vapor

Because in base of the Proposed Table of Contents the login with social seems not to be included :)

**Comment by 0xTim** [comment]
@cikpis yeah that's the one - I can tell you it's definitely planned. Source: I'm writing it!

**Comment by cikpis** [comment]
@0xTim Bought it already 👍  Do you have already an idea when it will be released? 🤔

**Comment by cikpis** [comment]
Make sense, thanks!

**Comment by cikpis** [comment]
@calebkleveter Will the auth-provider replaced in favour of Imperial? 🤔

**Comment by 0xTim** [comment]
@cikpis auth-provider is no more in Vapor 3. Imperial should probably depend on the Auth package to provide a nice integration

**Comment by cikpis** [comment]
Basically there are a lot of breaking changes from version 2 to 3 😅 At this point I guess I have to wait the stable release in order to start with Vapor before I will end up to waste time 😄 

Looking forward to have the book 👍

**Comment by cikpis** [comment]
@calebkleveter will the auth-provider feature be in Imperial?

**Comment by calebkleveter** [comment]
I'll take a look at it once it is updated for the RC release. I am not sure how it would integrate, but there should be some places that a helper method would be nice.

**Comment by cikpis** [comment]
That would be nice because the current auth-provider is quite good and would be pity don't have a valid alternative in Vapor 3.

**Comment by calebkleveter** [comment]
Oh, I was thinking of the Auth package that Tim mentioned. I don't have any plans to support Vapor 2 in Imperial. There will be some similar helper methods to those in the Auth Provider package though.

**Comment by 0xTim** [comment]
To be clear, the current Auth package works for Vapor 3 and includes everything that Vapor 2 had in the Auth Provider. OAuth login is separate

**Comment by cikpis** [comment]
@0xTim interesting because I couldn't make it work. I'll try again then. Which version should I use btw?

I'm using this:
```swift
// Auth
        .package(url: "https://github.com/vapor/auth-provider.git", from: "1.0.0"),
        
        // MongoDB
        .package(url: "https://github.com/vapor/mongo-provider.git", from: "2.0.0"),
```

Are they correct for Vapor 3?

**Comment by 0xTim** [comment]
@cikpis the providers are no more in Vapor 3. So you just need:

```swift
.package(url: "https://github.com/vapor/auth.git", from: "2.0.0-rc")
```

Note that Mongo isn't really integrated at the moment, so if you have to use that you might need to wait. Finally, Auth in Vapor 3 has changed somewhat, I think the only up to date example is in the [RW videos](https://videos.raywenderlich.com/courses/115-server-side-swift-with-vapor/lessons/26)

**Comment by cikpis** [comment]
I've already paid the book so I guess I'll wait xD 

Thanks

**Comment by cikpis** [comment]
BTW, @calebkleveter could you please send me a Slack invitation? I'm still waiting to receive it :)

My email is work@carmelogallo.com, thanks!

**Comment by calebkleveter** [comment]
Looks like your already in 🙂.
<img width="351" alt="screen shot 2018-03-16 at 11 59 46 am" src="https://user-images.githubusercontent.com/13837190/37534022-8e2b4082-2911-11e8-91f1-a2166c02b758.png">

**Comment by cikpis** [comment]
Ah! I was registered with a password that I have never put xD

I just reset it, thanks!

**Comment by joscdk** [comment]
I am closing this ticket as it seem to be resolved. Facebook/Google auth is in the Imperial package. If all questions aren't answered, feel free to reopen

**Comment by calebkleveter** [comment]
Just to keep the record straight, Imperial doesn't support Facebook at the moment because the maintainer (me) doesn't have a Facebook account. PRs are welcome 😄.

**Comment by rafiki270** [comment]
HOW CAN YOU LIVE?!?!?!

**Comment by calebkleveter** [comment]
It's probably how I do live 😁.
