### ISSUE TITLE
How to create new swift file by Xcode ?

### ISSUE THREAD

**Issue by hulk10425** [vapor/vapor#1550]
### Steps to reproduce

I new a file by Xcode and that seems the file doesn't in normal situation.

Because when I create Model called "Order", the color of the class a little weird and cant be used by other class.

The step I do is 1.choice a folder 2.clicked the right button, choice New File... 3.select swift file.

And another thing is the file created by me, there is an 'A' Character next to the file.

anyone can help me , thanks

**Comment by twof** [comment]
Every time you add a new file to your project, it needs to be regenerated by running `vapor xcode` from the command line.

**Comment by hulk10425** [comment]
It's works for me. Thank you, @twof

**Comment by twof** [comment]
No problem! Good luck!

**Comment by vzsg** [comment]
You can also create new files in Xcode, but there are two important things to watch out for:

1. The file must be created under Sources/App (replace App with the module you want to add the file to). This is critical for command line builds (incl. Linux), where the folder structure dictates target membership.
1. And when you're creating the file, there's a list of targets and checkboxes. You must check App and uncheck everything else.

That "A" character is just a status from source control. It means this is a new file that was added to the project.
