### ISSUE TITLE
No such module Found

### ISSUE THREAD

**Issue by miralmas** [vapor/vapor#1551]
After creating a new web template { vapor new Hello --template=web >> vapor xcode } I am getting a error " No such module 'LeafProvider' "
I also tried to  `vapor update/swift package update`  but it didn't fix that , I am running toolbox 3.1.4. how to fix that ?   Thanks

![screen shot 2018-03-16 at 10 33 46 am](https://user-images.githubusercontent.com/31250069/37504016-ff68cdd4-2905-11e8-9182-8399565a02a8.png)
![screen shot 2018-03-16 at 10 34 04 am](https://user-images.githubusercontent.com/31250069/37504021-0ac0f22e-2906-11e8-92e4-a092683d7714.png)

**Comment by 0xTim** [comment]
@miralmas have you actually built it yet in Xcode? Sometimes it takes a build before Xcode can pick up the symbols?

**Comment by miralmas** [comment]
I build this another time and it works perfectly. Thanks @0xTim  👍

**Comment by 0xTim** [comment]
🎉
