### ISSUE TITLE
Pivot tables -  add Unique protocol for a Pivot table to only contain unique rows

### ISSUE THREAD

**Issue by mihaelamj** [vapor/vapor#1553]
### Steps to reproduce

Add a pivot between 2 fields.
Insert same values twice.
Same values will be inserted if a Model does not implement a Unique (may be added) protocol.

### Expected behavior

Same values should not be inserted, if

`extension Model : Unique {}`

### Actual behavior

Pivot currently allows many identical rows in a table, because there is not Unique protocol, yet.

`http://localhost:8080/api/flavors/1/tastes

[
{"id":1,"name":"Sweet","shortDescription":"Sweet as honey"},
{"id":1,"name":"Sweet","shortDescription":"Sweet as honey"},{"id":1,"name":"Sweet","shortDescription":"Sweet as honey"}
]`

### Environment

Vapor 3.RC1
Fluent 3.0.0-rc.1.0

* Vapor Framework version:
* Vapor Toolbox version:
* OS version:

**Comment by 0xTim** [comment]
I think this should be an option rather than forced. Maybe something you can do in the migration. There are use cases where you may want to allow duplicates

**Comment by mihaelamj** [comment]
Maybe I should transform this into a feature request 
`extension Acronym : Unique {}`

**Comment by tanner0101** [comment]
@mihaelamj could you move this one to vapor/fluent? That's where the relevant code is.
