### ISSUE TITLE
PostgreSQL withConnection issue (3.0.0-rc)

### ISSUE THREAD

**Issue by theguild** [vapor/vapor#1555]
Hello,

I have an issue to implement CRUD with Fluent-PostgreSQL (actually I can't create the database connection).

Here is the code in **boot.swift** according to
https://docs.vapor.codes/3.0/fluent/querying/

```swift
public func boot(_ app: Application) throws {
    // your code here
    app.withConnection(to: .psql) { db in
        // use the db here
    }
}
```

The error I get is:

```
server/Sources/App/boot.swift:13:29: Member 'psql' in 'DatabaseIdentifier<_>' 
produces result of type 'DatabaseIdentifier<PostgreSQLDatabase>', 
but context expects 'DatabaseIdentifier<_>'
```

It will be great if you provide a real example how to make CRUD in the new Vapor 3.
Thanks!

### Environment

XCode 9.3 beta 4

* Vapor Framework version: 3.0.0-rc
* Vapor Toolbox version: 3.1.4
* OS version:  macOS 10.13.3

**Comment by 0xTim** [comment]
@theguild the docs are massively out of date unfortunately. What are you trying to achieve?

**Comment by theguild** [comment]
Thanks for your response! I'd like to have simple CRUD with PostgreSQL using the new Promise / Future logic.

**Comment by theguild** [comment]
Thanks anyway.

I guess I have to wait (and no time for waiting) OR use Vapor 2 (bad solution in long term) OR switch to another Swift server solution.

**Comment by 0xTim** [comment]
What are you trying to do with the database when the application boots? If you are just trying to use the DB in routes you don’t need to create your own connection

**Comment by yura-voevodin** [comment]
I have the same issue, but in `Command` subclass for console command.

**Comment by kliron** [comment]
I have the same issue in a route. 

`router.get("stuff", "count") { req -> Future<[Int64]> in
        return req.withPooledConnection(to: .psql) { conn in
            return try conn.query("SELECT COUNT(*) AS count FROM stuff;").map(to: Int64.self) { rows in
                return try rows[0].firstValue(forColumn: "count")?.decode(Int64.self) ?? 0
            }
        }
    }` 

I get the error `Member 'psql' in 'DatabaseIdentifier<_>' produces result of type 'DatabaseIdentifier<PostgreSQLDatabase>', but context expects 'DatabaseIdentifier<_>'` No idea what context expects DatabaseIdentifier<_> and why. Documentation does not help at all.

**Comment by jl311888** [comment]
@theguild I had same problem in boot.swift and got it working using the following.

```
app.newConnection(to: .psql)
                .map { db in
                    // use the db here
            }
```

**Comment by kliron** [comment]
It seems the compiler needs a little more help. My issue is solved by specifying the `conn` parameter type annotation in the first closure:

`router.get("stuff", "count") { req -> Future<Int64> in
        return req.withPooledConnection(to: .psql) { (conn: PostgreSQLDatabase.Connection) in
            return conn.query("SELECT COUNT(*) AS count FROM stuff;").map(to: Int64.self) { rows in
                return try rows[0].firstValue(name: "count")?.decode(Int64.self) ?? 0
            }
        }
    }`
