### ISSUE TITLE
Vapor 3.1.2 cannot get value from request

### ISSUE THREAD

**Issue by nhatlee** [vapor/vapor#1564]
Hi all,
I try to test `vapor 3` branch `beta` but got the error when try to get value from `get` request. The snippet code and the error like the image below:
Even I get the `username` by the code `let username = try req.parameter(String.self)` OR `let username = try request.parameters.next(String.self)` -> still got the same error. Please help to correct me.
<img width="1363" alt="screen shot 2018-03-23 at 11 45 12 am" src="https://user-images.githubusercontent.com/7148482/37812009-1a636d4e-2e90-11e8-9868-04b6de84eb0f.png">

**Comment by linqingmo** [comment]
```swift
router.get("name", String.parameter) { req -> String in
    let username = try req.parameter(String.self)
    return "Hello \(username)"
}
```
If there are more than one line code in closure, you need to add the type of returned value.

**Comment by nhatlee** [comment]
@linqingmo: Thanks for your help

**Comment by Cellane** [comment]
@nhatlee FYI, 3.1.2 is the version of Vapor Toolbox, not Vapor. Vapor will soon™️ hit the 3.0.0 milestone, Vapor 3.1.x is quite far in the future I suppose 😄The versions of Toolbox and Vapor may differ as their respective development processes are mostly unrelated to each other.
