### ISSUE TITLE
HTTP Client returns custom error code on 401

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#1566]
When I call Mailgun API using:
```swift
let client = try req.make(Client.self)
return client.post(..)
```
 I get this response:
```text
HTTP/1.1 401 
Content-Length: 9
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Www-Authenticate: Basic realm="MG API"
Server: nginx
Date: Fri, 23 Mar 2018 14:41:25 GMT
Forbidden
```
printing:
```
(lldb) po response.http.status
▿ HTTPResponseStatus
  ▿ custom : 2 elements
    - code : 401
    - reasonPhrase : ""
```

I think the `response.http.status` should be of type `HTTPStatus.unauthorized`

**Comment by twof** [comment]
Kind of unrelated, but did you figure out why Mailgun was spitting out 401s?

**Comment by rafiki270** [comment]
@twof 401's were coming because I was sending api key with `key-` already prefixed so it was being attached twice, I have handled that now with a check if key is there

**Comment by tanner0101** [comment]
I think this is related to #1552 which we can merge now because NIO 1.3.0 is out. Closing this one in favor of the other one. Thanks @rafiki270 !
