### ISSUE TITLE
Can't Install vapor

### ISSUE THREAD

**Issue by krircc** [vapor/vapor#1572]
The Swift 4.1 Development Snapshots works well , but I can't install vapor. The swift can run some more other linux than office support, so how can i try vapor on other linux as my debian os.

* Vapor Framework version: 3.0 RC2
* OS version: debian testing

**Comment by 0xTim** [comment]
@krircc do you mean the Vapor toolbox? You may need to build it from source on other OS platforms, or run it inside a Docker container.

Just an FYI - you don't actually need it to be able to build Vapor application, you could just build your application with `swift build`

**Comment by krircc** [comment]
@0xTim ok I try it now
