### ISSUE TITLE
Client overrides content type header

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#1573]
When making a request with `Client`, header "content-type" passed into the request is ignored and swapped for "application/json" unless you specify:
```swift
static var defaultMediaType: MediaType = MediaType.urlEncodedForm
```
on the model passed in. I believe the default behaviour should be to only set content-type if there is none passed in.

**Comment by 0xTim** [comment]
@rafiki270 are you setting the request body? If so, how?

**Comment by rafiki270** [comment]
@0xTim https://github.com/twof/VaporMailgunService/blob/cf470cf732d4ab270440c5e6fdb7219c898ff284/Sources/Mailgun/Mailgun.swift#L100

**Comment by 0xTim** [comment]
Cool just checking, definitely sounds like a bug then!

**Comment by tanner0101** [comment]
Closing this one in favor of https://github.com/vapor/vapor/issues/1583 which will be a good solution to this problem 👍
