### ISSUE TITLE
Run release with environment

### ISSUE THREAD

**Issue by ilyahal** [vapor/vapor#1576]
I'm trying to run release build on Ubuntu, I executed the following steps:

$ cd path/to/project
$ vapor build --release
Building Project [Failed]

Command:
build --enable-prefetching --configuration release

Error (1):
error: unknown option --enable-prefetching; use --help to list available options

Output:

Toolchain:
/root/swift/usr/bin/swift

Help:
Join our Slack where hundreds of contributors
are waiting to help: http://vapor.team

Error: Build failed.

Then I try this:
$ swift build -c release // ok
$ .build/release/Run --env=production
Migrating sqlite DB
Migrations complete
⚠️ [CommandError.excessInput: Too many arguments or unsupported options were supplied: ["--env=production"]] [/home/ilyahal/files/demo/.build/checkouts/console.git--7720180488165027522/Sources/Command/CommandContext.swift:80:33]

How I can fix it?

### Environment

Vapor Framework version: 3.0.0 RC2.2
Vapor Toolbox: 3.1.4

Swift version 4.1-dev (LLVM 260a172ffb, Clang cd84be6c42, Swift 364c296101)
Target: x86_64-unknown-linux-gnu
Ubuntu 16.04

**Comment by tanner0101** [comment]
The proper syntax is `--env production`. Although a patch has been added recently to add backward-compat support for the old syntax.
