### ISSUE TITLE
documentation: benchmarks for network IO?

### ISSUE THREAD

**Issue by gaming-hacker** [vapor/vapor#1577]
Hello All,

I was poking around in the documentation as I'm interested in websockets, tor, ssl, http requests.  Has anyone done any benchmarks for your Async, etc against other libraries? like alamofire for html? or socketrocket for wss?  I'm a proponent of neither just want to know if your implementation has a lighter footprint? handles async requests speed? queueing?

Thanks

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
