### ISSUE TITLE
Convenience method for making responses.

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/vapor#1587]
### Steps to reproduce

Currently when making a response that can be decoded as `Content` and setting a status code on that response it takes a few lines to achieve that.

```swift
let response = req.makeResponse()
try response.content.encode(MyResponse())
response.http.status = .internalServerError
return response
```

### Proposed solution

Ideally this would be achieved like this

```swift
return req.makeResponse(content: MyResponse(), httpStatus: .internalServerError)
```

Simple clean and fast.

**Comment by damirstuhec** [comment]
@Andrewangeta You can already do the same thing in one line:
`return try req.content.decode(MyResponse.self).transform(to: .internalServerError)`

**Comment by damirstuhec** [comment]
Oh, now I saw that you are actually trying to encode and not decode. So you can ignore my comment above. I'll leave it there for the sake of it though.

**Comment by tanner0101** [comment]
This will be added in 3.0.0 👍 

```swift
req.makeResponse(http: .init(status: .notFound))
```
