### ISSUE TITLE
Run error: FluentError.reflectProperty 

### ISSUE THREAD

**Issue by Dove2** [vapor/vapor#1588]
I download the template with `vapor new Hello --branch=beta`, and I run it. Then I get a result shown as below:
"⚠️ [FluentError.reflectProperty: No property reflected for Swift.WritableKeyPath<App.Todo, Swift.Optional<Swift.Int>>]"

### Steps to reproduce

The code is from template. And I didn't modify it at all.
### Environment

* Vapor Framework version:3.0.0-rc.2.2.1
* Vapor Toolbox version:3.1.4
* OS version:macOS High Sierria 10.13.3

**Comment by tanner0101** [comment]
@Dove2 run `vapor update` and try it again, an issue related to this was fixed recently. That should do it 👍
