### ISSUE TITLE
Procfile example for Vapor 3?

### ISSUE THREAD

**Issue by midtownkc** [vapor/vapor#1591]
I have access to a deployment system similar to Heroku.

I've successfully deployed a Vapor 2 framework app using the Swift Heroku Buildpack, but I'm having issues getting Vapor 3 running.

Successful Vapor 2 Procfile is:

```
web: ./.build/release/Run
```

Is there a good example of a working Procfile for a simple Vapor 3 App?

I have tried:

```
web: ./.build/release/Run --env prod
web: ./.build/release/Run --port $PORT --hostname $IP_ADDRESS
web: ./.build/release/Run
```

I'm using:
```
Vapor Toolbox: 3.1.4
Vapor Framework: 3.0.0-rc.2.2.1
Apple Swift version 4.1-dev (LLVM 260a172ffb, Clang cd84be6c42, Swift 05b1b2be7c)
```

When trying to set env to prod I get:

```
Illegal instruction
```

Attempting to set hostname & port, I get:

```
[CommandError.excessInput: Too many arguments or unsupported options were supplied: ["--port", "31013", "--hostname", "x.x.x.x"]]
``` 
( I edited out ip address to x.x.x.x)

If I run it without specifying env or port/hostname it simply won't launch, but if I SSH into an ephemeral instance I can run command, however it doesn't bind to the port or IP: it runs on 0.0.0.0:8080

Any ideas on how to specify port/hostname?

Your help is much appreciated.

**Comment by joscdk** [comment]
The command should be something like:

```
(..)Run serve --port $PORT --hostname 0.0.0.0
```

**Comment by midtownkc** [comment]
🎉Thanks so much for the assist.🎉
