### ISSUE TITLE
How to change mysql Collation with vapor code

### ISSUE THREAD

**Issue by Dove2** [vapor/vapor#1592]
### Steps to reproduce

Excuse me. I want to insert data to  mysql tables. But got a error code:1366 because of there is Chinese characters in my data.However, I can convert character set to `utf8_general_ci `manually and solve it. But I expect I can convert it whenever I create the table with vapor code

### Expected behavior

I expect there are ways to convert character set in code.

### Actual behavior

mysql error (code: 1366) happened .

### Environment

* Vapor Framework version:2.0
* Vapor Toolbox version:3.1.4
* OS version:macOS High Sierra 10.13.3

**Comment by tanner0101** [comment]
There are issues open on the vapor/mysql repo for this, closing here since its unrelated to vapor/vapor.
