### ISSUE TITLE
vapor build in ubuntu 16.04 error: use of undeclared type 'SSL'

### ISSUE THREAD

**Issue by Dove2** [vapor/vapor#1593]
### Steps to reproduce

I run `sudo vapor update` and `sudo vapor build` and finally got an error like title.
I can run the serve in macOS with Xcode.
what my package.swift is shown as
```
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "Stockphet",
    products: [
        .library(name: "App", targets: ["App"]),
        .executable(name: "Run", targets: ["Run"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.1.0")),
        .package(url: "https://github.com/vapor/fluent-provider.git", .upToNextMajor(from: "1.2.0")),
        .package(url: "https://github.com/vapor/mysql-provider.git", .upToNextMajor(from: "2.0.0")),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: ["Vapor", "MySQLProvider", "FluentProvider"],
            exclude: ["Config", "Public", "Resources"]
        ),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
    ]
)
```
### Expected behavior

I wish to build successfully
### Actual behavior

error: use of undeclared type 'SSL'
### Environment

* Vapor Framework version: actually I can't see, it throw an error
* Vapor Toolbox version:3.1.2
* OS version:ubuntu 16.04

**Comment by 0xTim** [comment]
@Dove2 you shouldn't need to run as `sudo`! But make sure you have `libssl-dev` installed - `sudo apt-get install libssl-dev`

**Comment by Dove2** [comment]
@0xTim I do have `libssl-dev` installed. And I got error like this without sudo call:
```
Command:
build --enable-prefetching

Error (1):
error: invalidAccess
error: product dependency 'Vapor' not found
error: product dependency 'MySQLProvider' not found
error: product dependency 'FluentProvider' not found
error: product dependency 'Testing' not found
```

btw: I saw the question #1165 and try installing openssl 1.0.2g but failed because every time I install vapor then openssl get upgraded to 1.1.0

**Comment by Dove2** [comment]
@0xTim Thanks.I have my system reinstall and build it successfully. It seems something wrong in ubuntu. Maybe the problem is that I install swift manually from swift.org, or something else.
