### ISSUE TITLE
API Providers should not have to rely on the applications content configs

### ISSUE THREAD

**Issue by PitchLabsAsh** [vapor/vapor#1595]
### Issue

When writing an API service provider its not possible to change the content config of a Client, it uses the application's config.

### Suggested enhancement

It would be very helpful to be able to override the config when creating a client

    var contentConfig = ContentConfig.default()
    contentConfig.use(decoder: JSONDecoder.myinit, for: .json)
    contentConfig.use(encoder: JSONEncoder.myinit, for: .json)

    let client = try req.make(Client.self, withConfig:contentConfig)

**Comment by tanner0101** [comment]
The most a provider can do here is register a default `ContentConfig` to make default behavior easy and provide an extension on `ContentConfig` for users to opt-in to enabling those coders. Service-provider configuration is out of scope for 3.0.0 release, but should be considered for Service 2.0.0. An issue on vapor/service to discuss this would be merited 👍
