### ISSUE TITLE
Archive Vapor in favour of PHP

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1597]
Vapor has had a good run, become fairly popular and made server-side Swift popular. However it is time to recognise the inevitable and archive Vapor in favour of PHP.

PHP's performance is far superior, the language is nicer and safer and generally everyone would be better off. 

Would also consider Javascript instead

**Comment by Andrewangeta** [comment]
10/10 would recommend

**Comment by gwynne** [comment]
Can't argue it anymore, Swift just hasn't lived up to its promises. See also https://github.com/apple/swift/pull/15664

**Comment by twof** [comment]
👏Good job everyone! I'm didn't think we would be able to keep the joke going as long as we did. The fact that over 13 thousand people fell for it too hahahaha. Why would anyone create a web server side framework in Swift when there are already so many options built on top of the only good language to come out in the past 50 years, PHP? 😂

**Comment by proyb6** [comment]
Nah, I would write shell script and CURL for for static pages, we never have to worry what languages to use again. :)

**Comment by 0xTim** [comment]
Closing as obviously an April Fools! :trollface:
