### ISSUE TITLE
ubuntu 16.04 install vapor success,but ....

### ISSUE THREAD

**Issue by karmaios** [vapor/vapor#1602]
step:
1、eval "$(curl -sL https://apt.vapor.sh)"
2、sudo apt-get install swift vapor
3、curl -sL check.vapor.sh -o check.vapor.sh
4、less check.vapor.sh
5、bash ./check.vapor.sh
✅  Swift 4.1 is compatible with Vapor 2.
✅  Swift 4.1 is compatible with Vapor 3.
6、vapor --version
vapor: symbol lookup error: vapor: undefined symbol: _T0s19_emptyStringStorages6UInt32Vv

**Comment by bsuvorov** [comment]
@karmaios  - running into the same issues, how did you resolve it?

**Comment by 0xTim** [comment]
@bsuvorov make sure you update your toolbox

**Comment by fadylateef** [comment]
I've been retrying and getting the same problem on four different VPS machines running Ubuntu 16.0, Then tried a fresh install of Ubuntu 16.0 and it worked !!

**Comment by balazs630** [comment]
Have the very same problem under Ubuntu 14.04. On `vapor build` I got:
`vapor: symbol lookup error: vapor: undefined symbol: T0s27_ContiguousArrayStorageBaseC16countAndCapacitys01_B4BodyVvpWvd`

**Comment by fadylateef** [comment]
Seems the problem still persist , I've tried with a Ubuntu 16.0 Server on Digital Ocean and it works like charm .

**Comment by balazs630** [comment]
Yes, with Ubuntu 16 or 18 versions it works fine, thank you. If it’s a known problem for a long time, how about removing 14.04 support on this page: https://docs.vapor.codes/3.0/install/ubuntu/

It’s quite misleading, and in practice it’s not supported, not working on 14.04

**Comment by tanner0101** [comment]
The `symbol lookup error` is an issue with the Swift ABI breaking between releases for vapor/toolbox. We need to release an update for 14.04. You should still be able to use Vapor there with SPM directly (`swift  build`)
