### ISSUE TITLE
Failure of route auto content-decoding hangs infinitely 

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1609]
I have a route, defined like this:

```swift
build.post(RegisterRequest.self, at: "/register", use: handleRegisterPost)
```

And a corresponding function that looks like this:

```swift
private func handleRegisterPost(req: Request, content: RegisterRequest) throws -> Future<Response> {
//logic
}
```

`RegisterRequest` looks like this:

```swift

struct RegisterRequest: Content {
    var csrf: String?
    var doesnotexist: Double
}
```

`doesnotexist` does not exist in the form (as the name notes) but is not optional. As a result, the decoding should fail (and it does). When it fails to decode, the route hangs infinitely with no indication that the decoding was the problem.

**Comment by mcdappdev** [comment]
Upon further investigation it appears that the reason for this lies in the implementation here:

https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/Responder.swift#L48

**Comment by damirstuhec** [comment]
I’m seeing similar issue in my tests, but only after I execute two requests one after another.

*Example* (`response2` never completes, until it times out):
```
var headers = HTTPHeaders()
headers.replaceOrAdd(name: .contentType, value: ContentType.json.description)
headers.bearerAuthorization = BearerAuthorization(token: adminToken.token)

let response1 = try app.make(Client.self).send(.GET, headers: headers, to: "http://localhost:8080/api/partners/\(UUID().uuidString)").wait()
let response2 = try app.make(Client.self).send(.GET, headers: headers, to: "http://localhost:8080/api/partners/\(try partner.requireID())").wait()
```

This `flatMap` never seems to complete in my case: https://github.com/vapor/vapor/blob/8a81713d84b4547c2fe47b21fbdfed0d0ed6d8f3/Sources/Vapor/Routing/Router%2BMethod.swift#L41
_Note: nothing is printed to the console._

I found out that *any* request that follows a request where I test “wrong UUID situtation”, like so: `http://localhost:8080/api/partners/\(UUID().uuidString)"` hangs. The "wrong UUID" test on its own works fine.

**Comment by mcdappdev** [comment]
Interesting. I don’t think that’s directly related to my issue but I saw something similar in my project earlier

**Comment by tanner0101** [comment]
Added a test for this using the code in the original message and everything appears to be working. Must be a bug that has been fixed since. 👍 Let me know if everything looks good on your end once 3.0.0 is tagged.

**Comment by damirstuhec** [comment]
One of the last versions seems to have fixed this issue for me. @mcdappdev please check yourself too.

**Comment by mcdappdev** [comment]
Yeah it works great for me! Thanks @tanner0101
