### ISSUE TITLE
FoundationClient not properly handling HTTPResponse types.

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/vapor#1610]
### Steps to reproduce

When using a `Client` to respond to requests like so 

```swift
 try httpClient.respond(to: Request(http: request, using: httpClient.container))
```

upon receiving the response I'm unable to perform a switch case over the status type which is defined as an enum in Swift NIO as such

<img width="730" alt="screen shot 2018-04-08 at 4 02 53 pm" src="https://user-images.githubusercontent.com/12012815/38471954-5c06693c-3b46-11e8-9323-2771eb7b703e.png">

so for example in the SendGridProvider I expect to be able to throw an error based on the responses' status code like so:

```swift
switch response.http.status {
                case .ok, .accepted: return
                default:
                    let decoder = JSONDecoder()
                    decoder.dateDecodingStrategy = .secondsSince1970
                    let error = try decoder.decode(SendGridError.self, from: response.http.body.data ??  Data())
                    
                    throw error
                }
```

but when using the debugger to print out the status we get a custom type

<img width="246" alt="screen shot 2018-04-08 at 4 06 23 pm" src="https://user-images.githubusercontent.com/12012815/38471976-d2678d4a-3b46-11e8-8ce8-d344bf8c9175.png">

even though when creating this response we're supposed to be setting the correct type and not a custom one given the status code matches one. In this case 202 does match one `.accepted`

<img width="472" alt="screen shot 2018-04-08 at 4 07 03 pm" src="https://user-images.githubusercontent.com/12012815/38471990-0f16f14a-3b47-11e8-8006-ba8d133a6d34.png">

Turns out that in `FoundationClient.swift` we're _always_ using a custom init for HTTPResponses
<img width="1064" alt="screen shot 2018-04-08 at 4 11 21 pm" src="https://user-images.githubusercontent.com/12012815/38472032-b4393cc8-3b47-11e8-954d-dcff70767ae7.png">

When ideally we should be using the normal initializer.

So this:
```swift
var res = HTTPResponse(status: .custom(code: UInt(httpResponse.statusCode), reasonPhrase: ""))
```

Should become this:
```swift
var res = HTTPResponse(status: HTTPResponseStatus(statusCode: httpResponse.statusCode))
```

**Comment by Andrewangeta** [comment]
Apparently this is resolved in master but not tagged?
https://github.com/vapor/vapor/blob/8a81713d84b4547c2fe47b21fbdfed0d0ed6d8f3/Sources/Vapor/HTTP/FoundationClient.swift#L80-L81

**Comment by Andrewangeta** [comment]
it was committed here 
https://github.com/vapor/vapor/commit/61c7bbfbe623cff841b63abd94408d06b4f9f464

**Comment by tanner0101** [comment]
There have been quite a few tags since then, I'm assuming this one is closed 👍
