### ISSUE TITLE
Adding fluent-postgresql causes hang.

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1611]
vapor just hangs trying to generate xcode project.  You can see below my Package.swift.  As soon as I add that fluent-postgresql one it does the updates it shows and then just sits forever and does nothing else.

### Steps to reproduce

% cat Package.swift 
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "dtsapi",
    products: [
        .library(name: "App", targets: ["App"]),
        .executable(name: "Run", targets: ["Run"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.1.0")),
        .package(url: "https://github.com/vapor/fluent-provider.git", .upToNextMajor(from: "1.2.0")),
	.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc")
    ],
    targets: [
        .target(
            name: "App",
            dependencies: ["Vapor", "FluentProvider", "FluentPostgreSQL"],
            exclude: ["Config", "Public", "Resources"]
        ),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
    ]
)

% vapor xcode --verbose -y
Generating Xcode Project ...
Updating https://github.com/vapor/sockets.git
Updating https://github.com/vapor/routing.git
Updating https://github.com/vapor/sqlite.git
Updating https://github.com/vapor/core.git
Updating https://github.com/vapor/crypto.git
Updating https://github.com/vapor/bcrypt.git
Updating https://github.com/vapor/node.git
Updating https://github.com/vapor/tls.git
Updating https://github.com/vapor/debugging.git
Updating https://github.com/vapor/console.git
Updating https://github.com/vapor/fluent-postgresql.git
Updating https://github.com/vapor/engine.git
Updating https://github.com/vapor/multipart.git
Updating https://github.com/vapor/vapor.git
Updating https://github.com/vapor/bits.git
Updating https://github.com/vapor/ctls.git
Updating https://github.com/vapor/json.git
Updating https://github.com/vapor/random.git
Updating https://github.com/vapor/fluent.git
Updating https://github.com/vapor/fluent-provider.git
Updating https://github.com/vapor/postgresql.git
Updating https://github.com/vapor/async.git

### Environment

* Vapor Framework version: 2.4.4
* Vapor Toolbox version: 3.1.4
* OS version: MacOS High Sierra

**Comment by twof** [comment]
The issue is that you're trying to combine Vapor 2, with the RC of the Fluent Postgres package which is meant to work with Vapor 3. 

You're going to want to use

`.package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc.1.1"),`

and get rid of the Fluent Provider dependency. You won't need that anymore.

**Comment by twof** [comment]
```swift
// swift-tools-version:4.0

import PackageDescription

let package = Package(
name: "dtsapi",
products: [
.library(name: "App", targets: ["App"]),
.executable(name: "Run", targets: ["Run"])
],
dependencies: [
.package(url: "https://github.com/vapor/vapor.git", from: "3.0.0-rc.1.1"),
.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc")
],
targets: [
.target(
name: "App",
dependencies: ["Vapor", "FluentPostgreSQL"],
exclude: ["Config", "Public", "Resources"]
),
.target(name: "Run", dependencies: ["App"]),
.testTarget(name: "AppTests", dependencies: ["App", "Testing"])
]
)
```

This ought to work for you.

**Comment by twof** [comment]
You should probably be using Vapor 3 to start any new projects. It's relatively stable now, and it's a big change from Vapor 2 so if you opt to start with Vapor 2, any migration later will include at least a partial rewrite of your app.

Edited the package.swift above. There was an extra dependency under the "AppTests" target. Go ahead and give it another shot :)

**Comment by grosch** [comment]
Ah, I see you removed  the Testing.  It's popping up Xcode now.  Thank you!

**Comment by twof** [comment]
Excellent! Feel free to join https://vapor.team and drop by the #beta channel if you get stuck 👍 
Good luck!

**Comment by grosch** [comment]
One quick question.  The default seems to still be vapor 2.  What's the command to create a new project defaulting to version 3?

**Comment by twof** [comment]
`vapor new <name> --branch=beta` 

A few packages have been tagged for release, but the rest should be tagged (including the Vapor 3 tagging) next week, and I assume the Vapor 3 template will get merged to `master` at that point.
