### ISSUE TITLE
Discussion: Discourage State in RouteCollection

### ISSUE THREAD

**Issue by Mordil** [vapor/vapor#1613]
In the documentation, and in other tutorials, route controllers are described with a (final) class or struct conforming to the `RouteCollection` protocol with an empty constructor as the protocol requires an _instance_ method `boot(router:)`.

However, I think this leaves the possibility of users shooting themselves in the foot, to me, seeing an initializable type defined leaves the option open for adding stored properties and additional initializers.

The code, when using this type and feature, also isn't as "clean" or comparable to other APIs in Vapor 3 such as migrations of models, `Future` type mapping, route parameters, etc.

For example:
```swift
let routeController = MyRouteController() // which conforms to `RouteCollection`
try router.register(collection: routeController)
```

One thing that I've done to try and clean up my code, and remove the concept of an object representing a route, is to use zero cased `enums` with static methods.

I've started preferring this, as it adds compiler enforcement for the concept of controllers (and factories), without needing to add `private init() { }` or other protections to strengthen the concepts.

This is possible with Vapor 3 since all of the dependencies for controllers are now passed through the method and taken off of the `request` property.

For example:
```swift
enum MyRouteController {
    static func list(_ request: Request) throws -> ...
    static func show(_ request: Request) throws -> ...
    static func create(_ request: Request) throws -> ...
    static func delete(_ request: Request) throws -> ...
    static func update(_ request: Request) throws -> ...
    ...
}
```

## Proposal
Change `RouteCollection` to require a static method, and use that for registering RouteCollections

```swift
public protocol RouteCollection {
    static func boot(on router: Router) throws
}

extension Router {
    // further discussion is whether or not a label is really necessary for a Swift-y API
    public func register(collection: RouteCollection.Type) throws {
        try collection.boot(on: self)
    }
}
```

This will make it more readable when registering:

```swift
try router.register(collection: MyRouteCollection.self)
// alternative:
// try router.register(MyRouteCollection.self)
```

or can be called directly if someone desired:

```swift
let myRoutes = router.grouped("/api")
try MyRouteCollection.boot(on: myRoutes)
```

## Impact
This is source-breaking.

**Comment by 0xTim** [comment]
@Mordil what happens if you want to initialise your `RouteCollection` with properties? Let's say I pass a string down that is used in the controller - having it as a static method wouldn't allow this and would remove any compiler safety.

**Comment by Mordil** [comment]
@0xTim I'd ask what the purpose of the properties are? Why aren't they used in a Middleware, a Service, Config, etc.?

I could be wrong about this, as I haven't done enough digging just yet - but if I'm capable of adding properties to my `RouteController`, would I potentially have concerns of thread-safety that I'll be left managing on my own?

I don't think there's anything wrong with a framework being a bit more opinionated in this regard.

I do agree that this limits the possibility of perhaps "custom controllers" where it might be namespaced in some capacity, but perhaps that might be up to individual users to implement?

**Comment by Mordil** [comment]
At the base level, this is more of a broader discussion on perhaps the opinion on how to structure routing that I thought was worth having.

Just as I've seen examples of `RouteCollection` that have empty initializers but with static methods for the handlers, given that most routes use the Service Locating pattern that Vapor provides for practically all dependencies.

**Comment by calebkleveter** [comment]
If the properties are constant, then threading won’t be an issue. Variables might be a problem.

If you want an example, I have used properties for creating route paths before.

**Comment by Mordil** [comment]
@calebkleveter Sure, I'd like to see use cases I'm not envisioning.

**Comment by tanner0101** [comment]
@Mordil I agree with what you're saying here. There really is no reason you should be having stored properties on a route collection. That's just a recipe for race conditions. The API here is mostly carry-over from Vapor 2 where that _was_ recommended. 

I will make sure to take a look at what can be done here before the 3.0 tag goes out. I don't think we can break route collection as it stands, but I do think potentially Vapor could provide an alternative that discourages state and if that existed the documentation and templates could lean toward that method.

**Comment by tanner0101** [comment]
It's also worth noting that creating a `RESTfulController` protocol is still on the todo list and if/when that exists, it should also discourage shared state.

**Comment by Mordil** [comment]
Copying over discussion from the #1635 PR:

From **Tanner**
> re: restfulcontroller, not yet. Just lots of ideas floating around in my head so far on the most convenient API for it. I'd love to hear any ideas you might have.
> 
>I think there could be some use to an instance-based route collection. For example:

```swift
let fooRoutes = FooCollection(enableDevRoutes: false)
router.register(fooRoutes)
```

> Not sure how valuable that is though.
> 
> It's also worth bringing up controllers in general. Currently there is no protocol for them, you can do it however you want:

```swift
final class FooController {
    static func hi(_ req: Request) -> String { ... }
}
final class BazController {
    func hi(_ req: Request) -> String { ... }
}

router.get("foo", FooController.hi)
router.get("baz", BazController().hi)
```

> For FooController you would want StaticRouteCollection and for BazController RouteCollection.
>
> Would be nice to push people toward designing their controllers like FooController however possible, but again I think there is potentially value in both methods.

**Comment by Mordil** [comment]
From **Myself**

> I think if we provided a way to use a Config object to modify a controller's behavior would bridge the gap of two protocols.
>
>That's a much deeper change, though. Since there's no mechanism for it currently with the Router.
>
> Something like

```swift
struct FooControllerConfig {
    devRoutesEnabled: Bool
    // ...
}

// this proposes a rename of `RouteCollection` to `RouteController`
final class FooController: RouteController {
    typealias RouteControllerConfig = FooControllerConfig

    static func boot(on router: Router, with config: RouteControllerConfig) throws
}

// somehow router would need to receive the config to pass
router.register(FooController.self)
```

**Comment by tanner0101** [comment]
I see the logic here, but not sure conflating controllers + route collections is a great thing. I think `RouteCollection` as it stands currently is more flexible than `RouteController` would be.

I'm leaning toward the solution of doing `StaticRouteCollection` and `RouteCollection`. With the docs leaning toward using `StaticRouteCollection` and defining controllers statically. That would provide the most flexility for users of Vapor to set things up how they want and not break any API.

**Comment by 0xTim** [comment]
One thing I use stored properties is passing in strings from a provider package - e.g. https://github.com/brokenhandsio/SteamPress/blob/vapor3/Sources/SteamPress/Controllers/FeedController.swift#L8

This may be the wrong approach, but is the best way I've found from passing information down

**Comment by Mordil** [comment]
So, I've done some more thinking and this is what I'm proposing now:

1. `RouteCollection` stays as is (_maybe_ rename to `RouteController` so it's not perhaps confused with the next point)
2. Create the new `RouteHandlerCollection`
3. Provides a `ResourceController` protocol that inherits from `RouteHandlerCollection`, with the following other requirements:

```swift
protocol ResourceController: RouteHandlerCollection {
    associatedtype Resource: Model where Model: Parameter

    static func index(_ req: Request) throws -> Future<[Resource]>
    static func store(_ req: Request) throws -> Future<Resource>
    static func show(_ req: Request) throws -> Future<Resource>
    static func replace(_ req: Request) throws -> Future<Resource>
    static func update(_ req: Request) throws -> Future<Resource>
    static func destroy(_ req: Request) throws -> Future<HTTPStatus>
    static func clear(_ req: Request) throws -> Future<HTTPStatus>
}
```

`ResourceController` would have default implementations for all required methods, and for `boot(on:)` would by default register all methods in the following way:

```swift
static func boot(on router: Router) throws {
    router.get("/", use: index)
    router.post("/", use: store)
    router.delete("/", use: clear)
    router.get(Resource.self, use: show)
    router.put(Resource.self, use: replace)
    router.patch(Resource.self, use: update)
    router.delete(Resource.self, use: destroy)
}
```

This would allow conformance to be easy as:
```swift
internal enum TodoController: ResourceController {
    typealias Resource = Todo.self
}

// later while registering
router.register(TodoController.self)
```

If people want to customize the methods, or which methods are registered, they just provide implementations that override the defaults.

There's obviously some dependency issues to resolve in order to do this, since `Request` is defined in `Vapor`, but `Model` is defined in `Fluent`, and `Parameter` is in `Routing`.

**Comment by abbasmousavi** [comment]
My proposal as described here: https://github.com/vapor/api-template/pull/51 is something like this

``` swift
import Vapor
import Foundation
import FluentSQLite

/// Controlers basic CRUD operations

protocol RESTController: :RouteCollection {
    associatedtype T: PostgreSQLModel & Parameter & Content
}

extension RESTController {

   func boot(router: Router) throws {
        router.get(use: index)
        router.get(T.parameter, use: find)
        router.post(use: create)
        router.put(T.parameter, use: update)
        router.delete(T.parameter, use: delete)
    }
    
    /// Returns a list of all `T`s.
    func index(_ req: Request) throws -> (Future<[T]>) {
        return T.query(on: req).all()
    }

    /// Saves a decoded `T` to the database.
    func create(_ req: Request) throws -> Future<T> {
        return try req.content.decode(T.self).flatMap(to: T.self) { model in
            return model.save(on: req)
        }
    }

    /// Deletes a parameterized `T`.
    func delete(_ req: Request) throws -> Future<HTTPStatus> {
        return try (req.parameter(T.self) as! EventLoopFuture<T>).flatMap(to: Void.self) { model in
            return model.delete(on: req)
        }.transform(to: .ok)
    }

    func update(_ req: Request) throws -> Future<T> {

        return try req.content.decode(T.self).flatMap(to: T.self) { model  in
            return model.update(on: req)
        }
    }

    func find(_ req: Request) throws -> Future<T> {
            return try req.parameter(T.self) as! EventLoopFuture<T>
    }
}
```
then for every model just

```swift
final class TodoController: RESTController {
    
    typealias T = Todo
}
```
and the router code will be

```swift
try router.grouped("todos").register(collection: TodoController())
```

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
