### ISSUE TITLE
macOS Deployment Target keeps resetting to 10.10

### ISSUE THREAD

**Issue by axello** [vapor/vapor#1615]
I have a working and fairly new project. Actually: project2 from Paul Hudson's book.
When I do an Xcode build, the deployment target is 10.10, which is not working and I get 122 errors. I have to set the deployment target to 10.13 again before the project compiles and runs. This happens every time I do an `vapor xcode`
### Steps to reproduce
See below

Start new project. add some working code. Do a `vapor build` to assure it runs.
Now do a `vapor xcode -y` and open Xcode. Try to run. There are errors of the sort "Module file's minimum deployment target is OS X v10.13", because the project's macOS Deployment Target was somehow set to 10.10

Vapor Toolbox: 3.1.4
Vapor Framework: 3.0.0-rc.2.2.4
Xcode Version 9.3 (9E145)

### Expected behavior
At least have a default deployment target which supports swift 4 or the default libraries like CNIO.

Set or *keep* the current deployment target when you do a `vapor xcode`. Not everyone is using Atom, Sublime, VIM or BBEdit for development.
For newbies, or hundreds of newbies, these are countless wasted hours in a new environment, and might discourage them from further exploring Vapor.

### Actual behaviour
Deployment target is changed every time you change the project by including services or providers.

I have not looked into the code for the vapor toolkit, but maybe it's lurking somewhere near the --now fixed-- `vapor update` bug?

### Environment
Terminal, Xcode 9.3 release, macOS 10.13.3, High Sierra

* Vapor Framework version: Vapor Framework: 3.0.0-rc.2.2.4
* Vapor Toolbox version:Vapor Toolbox: 3.1.4
* OS version: macOS 10.13.3, High Sierra

**Comment by axello** [comment]
But I don't do an `swift package build`, I do a `vapor xcode -y`, so the Vapor toolbox should be able to indeed patch the xcode project created.
This seems like a similar shortcoming to the `// swift-tools-version:4.0` hack to indicate swift 4.

But I'm definitely no expert on the SPM.

I'll see if I can create a simple sed script which patches the xcode file, but I don't think vapor has post-command capabilities?

**Comment by vzsg** [comment]
`vapor xcode -y` calls `swift package generate-xcodeproj` to do the heavy lifting.

I don't see how a header comment is a hack TBH.

SPM doesn't have any post-processing capabilities, but the vapor toolbox could be extended to do the transformations.

---

You didn't really answer the question which files you're seeing the errors in.

**Comment by axello** [comment]
Sorry, you're right. But it's past my bedtime now. 

Sent from the road, so beware of bumps in the text!

**Comment by axello** [comment]
Sorry, it took a while, as suddenly I got only errors on brand new projects, even with deployment set to 10.13. Xcode bug or so. Restarted Mac; still errors. Another project worked great this morning and yesterday. Apart from pulled dependencies I don't see a difference.

I created a new project using @twostraws Vapor3 template:
`vapor new project4 --template=twostraws/vapor-clean`

When I consequently run this --default-- template with `vapor build` the following yaml is created:
[vapor_build_output.txt](https://github.com/vapor/vapor/files/1899407/vapor_build_output.txt)
[debug.yaml.zip](https://github.com/vapor/vapor/files/1899417/debug.yaml.zip)

and I get 29 errors.

I also ran the xcode project and put the compile errors in this gist:

https://gist.github.com/axello/9605fce514553bb80ff5a82a5fa1312e

All of the errors disappeared yesterday when I changed the deployment target from 10.10 (when swift just came out?) to 10.13, when swift 4 came out.
Now, it keeps generating 
The Vapor 2 project generated by `vapor new` still work and give no errors. But I'm working with Vapor 3.

I'm gonna post this comment as I already spent 3 hours figuring out where the new errors come from and I haven't the foggiest idea.

**Comment by twof** [comment]
@axello That's an unrelated problem that's the result of a newly discovered Swift compiler bug that got triggered by a NIO update today. It should get fixed pretty quick, but if you want to, you could fork Vapor and pin NIO to 1.3.1. That should fix it.

**Comment by twof** [comment]
According to one of NIO's authors though, it should be less than an hour before it's resolved.

**Comment by twof** [comment]
@axello Should be resolved if you update
https://github.com/apple/swift-nio/releases/tag/1.4.1

**Comment by axello** [comment]
Thanks @twof. Always 'fun' when new errors appear just when you want to make a better bug report.

**Comment by axello** [comment]
Okay, just did a `vapor update` and `vapor build` and I don't get any compile or run errors, not even when 10.10 is the deployment target.
I'm a happy camper, issue closed!

**Comment by twof** [comment]
Good to hear! Good luck!
