### ISSUE TITLE
Server hangs on response

### ISSUE THREAD

**Issue by patchthecode** [vapor/vapor#1616]
If i do 
1. http://localhost:8080/city/1   (valid and gives valid response)  followed by 
2. http://localhost:8080/city/12 (does not exist and gives valid response)    followed by
3. http://localhost:8080/city/1 (valid but `server hangs here` )

### Steps to reproduce
Do the steps above to reproduce.

Here is my code
```swift

    let authRoute = router.grouped([tokenMiddleware])
    authRoute.get("city", City.parameter, use: cityControlleer.getCity)

    func getCity(_ req: Request) throws -> Future<GetCityOutput> {
        return try req.parameter(City.self)
            .map(to: GetCityOutput.self) { city in
                let data = GetCityOutput.Data(id: city.regionId.description,
                                              name: city.name,
                                              regionId: city.regionId.description)
                return GetCityOutput(status: "1",
                                     message: "success",
                                     data: data)
            }
    }

    struct GetCityOutput: Content {
        struct Data: Content {
            let id: String
            let name: String
            let regionId: String
        }
        let status, message: String
        let data: Data
    }
```

### Expected behavior
http://localhost:8080/city/1   (valid and gives valid response) 
gives 
```
{
    "status": "1",
    "message": "success",
    "data": {
        "id": "1",
        "name": "San Jose",
        "regionId": "1"
    }
}
```

http://localhost:8080/city/12     (which does not exist)
gives
```
{
    "error": true,
    "reason": "No model with ID 12 was found"
}
```

This works correctly in all circumstances until i do the combination
http://localhost:8080/city/1 
http://localhost:8080/city/12
http://localhost:8080/city/1  `It hangs here`

I have checked the error both in `Postman` and `Rested` app

When I enable logging this is the logs i get
1. http://localhost:8080/city/1 

```
[sqlite] [2018-04-11 14:17:01 +0000] SELECT * FROM `tokens` WHERE (`tokens`.`value` = ?) LIMIT 1 OFFSET 0 ["C8CA32A9-CF41-4ECA-8CAE-99067E6ECBA0"]
[sqlite] [2018-04-11 14:17:01 +0000] SELECT * FROM `users` WHERE (`users`.`id` = ?) LIMIT 1 OFFSET 0 ["A603D83E-A465-4AAC-9292-05646EC75ECE"]
[sqlite] [2018-04-11 14:17:01 +0000] SELECT * FROM `cities` WHERE (`cities`.`id` = ?) LIMIT 1 OFFSET 0 ["1"]
```
2. http://localhost:8080/city/2
```
[sqlite] [2018-04-11 14:17:52 +0000] SELECT * FROM `tokens` WHERE (`tokens`.`value` = ?) LIMIT 1 OFFSET 0 ["C8CA32A9-CF41-4ECA-8CAE-99067E6ECBA0"]
[sqlite] [2018-04-11 14:17:52 +0000] SELECT * FROM `users` WHERE (`users`.`id` = ?) LIMIT 1 OFFSET 0 ["A603D83E-A465-4AAC-9292-05646EC75ECE"]
[sqlite] [2018-04-11 14:17:52 +0000] SELECT * FROM `cities` WHERE (`cities`.`id` = ?) LIMIT 1 OFFSET 0 ["12"]
[ ERROR ] FluentError.modelNotFound: No model with ID 12 was found (Model.swift:265)
```

3. http://localhost:8080/city/1 
```
[sqlite] [2018-04-11 14:18:21 +0000] SELECT * FROM `tokens` WHERE (`tokens`.`value` = ?) LIMIT 1 OFFSET 0 ["C8CA32A9-CF41-4ECA-8CAE-99067E6ECBA0"]
[sqlite] [2018-04-11 14:18:21 +0000] SELECT * FROM `users` WHERE (`users`.`id` = ?) LIMIT 1 OFFSET 0 ["A603D83E-A465-4AAC-9292-05646EC75ECE"]
```

### Environment
* Vapor Framework version: 3.0.0-rc.2.2.4
* Vapor Toolbox version: Vapor Toolbox: 3.1.4
* OS version: High Sierra

**Comment by damirstuhec** [comment]
I can replicate the same issue every time as well. Exactly the same scenario.

**Comment by damirstuhec** [comment]
@tanner0101 Can we add this one to the 3.0 milestone as well? 🙏 It's such a pain in the butt. Let me know if I can help anyhow.

**Comment by vzsg** [comment]
I'm pretty sure that a complete project that exhibits this issue would help a lot.

**Comment by damirstuhec** [comment]
@vzsg True. Will provide.

**Comment by damirstuhec** [comment]
While building a sample project with the latest Vapor version, this issue seems to have been fixed. @patchthecode Please test again yourself.

**Comment by tomwildcat9** [comment]
I seem to be having this problem with ubuntu but not with mac.

**Comment by tomwildcat9** [comment]
I can definitely reproduce this on the linux side but not on macOS. @tanner0101 or @vzsg  any idea why this would be on the linux side and not the mac? This bug is killing, everything else in Vapor 3 is running fantastic!

**Comment by MrLotU** [comment]
Due to inactivity and no newer reports of this happening, this issue will be closed.
