### ISSUE TITLE
Can't generate xcode project after adding redis

### ISSUE THREAD

**Issue by xiaoyifan** [vapor/vapor#1622]
I'm trying to add redis into my vapor project.

By following the doc, 

create a new app using:
vapor new hello

in package.swift, add
.package(url: "https://github.com/vapor/redis.git", .upToNextMajor(from: "3.0.0")),
which is exactly the same as: https://docs.vapor.codes/3.0/redis/getting-started/

then run: vapor xcode --verbose

then it will run a bunch of frameworks updating like: 

Updating https://github.com/vapor/node.git
Updating https://github.com/vapor/debugging.git
Updating https://github.com/vapor/console.git
Updating https://github.com/vapor/tls.git
Updating https://github.com/vapor/routing.git
Updating https://github.com/vapor/sqlite.git
....

Then it will stuck.

### Environment

Vapor Toolbox: 3.1.4
Vapor Framework: 2.4.4
Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
Target: x86_64-apple-darwin17.5.0
OS: 10.13.4 (17E199)

**Comment by vzsg** [comment]
You are trying to add a 3.0 package to a Vapor 2 project.

**Comment by xiaoyifan** [comment]
I re-created a project using beta branch, but there're still a bunch of compiling issues from SQL package. is there something wrong with the template?

**Comment by tanner0101** [comment]
@xiaoyifan clean out all temporary files and update. 👍
