### ISSUE TITLE
Bring back BCryptService

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#1626]
Related to https://github.com/vapor/crypto/issues/50

Being able to do `try req.make(BCrypt.self)` to get a hasher with a properly set count for debug will reduce code and stop confusing people as to why their hashes are taking so long.

Discuss!

**Comment by vzsg** [comment]
Replacing the Swift implementation of BCrypt with a C module could probably also fix this issue without changing/extending the public interface.

**Comment by bre7** [comment]
Fixed in Crypto 3.1.0 ?

**Comment by tanner0101** [comment]
Yup Crypto 3.1.0 should mean you can just use the same cost everywhere without issue. @0xTim what do you think?
