### ISSUE TITLE
Vapor 3 cannot load image and css from `Public images (images resources)` and `Public  styles (css resources)`

### ISSUE THREAD

**Issue by nhatlee** [vapor/vapor#1629]
### Steps to reproduce

I load a leaf file with content is html, html content load image like below:
```
<div class="title">My's Homepage</div>
<p><a href="images/nhatle.jpg">
<img align="right" width="204" height="153" src="images/nhatle.jpg" alt="photo">
</a></p>
```
I have image with this name into folder `Public->images`

### Expected behavior

Should display image on the website

### Actual behavior

<img width="431" alt="screen shot 2018-04-18 at 9 28 49 pm" src="https://user-images.githubusercontent.com/7148482/38938370-8b785a2a-434f-11e8-83da-89915e02dc3e.png">

### Environment
I use `Swift 4.1`

* Vapor Framework version:3.0 beta
* Vapor Toolbox version: `Vapor Toolbox: 3.1.4`
* OS version: 10.13.4

**Comment by nhatlee** [comment]
Here is the folder structure of my project:
<img width="1045" alt="screen shot 2018-04-18 at 9 31 35 pm" src="https://user-images.githubusercontent.com/7148482/38938563-ff51db1a-434f-11e8-98ed-82b4f99bb91c.png">

**Comment by vzsg** [comment]
Did you enable the FileMiddleware by uncommenting [this line](https://github.com/vapor/api-template/blob/beta/Sources/App/configure.swift#L22)?

**Comment by nhatlee** [comment]
I am not change the `configure` file. So it comment out by default when I create new project. 
Thanks so much for your help.

**Comment by bellebethcooper** [comment]
I also had this problem because I missed that I needed to uncomment that line. Maybe it would be worth mentioning this [in the docs about using Public for serving files](https://docs.vapor.codes/3.0/getting-started/structure/#public)?

**Comment by 0xTim** [comment]
Sounds like a worthy PR!
