### ISSUE TITLE
Server crashes on release build when encoding a Date as JSON

### ISSUE THREAD

**Issue by C0deH4cker** [vapor/vapor#1631]
I think we have another bug similar to https://github.com/vapor-community/node/issues/45. I've tracked down a server crash that only happens on release builds of my Vapor 3 app to encoding a `Date` field in an object that conforms to `Content` to JSON. It is 100% reproducible on my project. Just commenting out the Date field in the Content object fixes the server crash. I unfortunately don't get any error messages when the server crashes so I can't tell you anything more.

This might be related to https://github.com/vapor/vapor/issues/1628.

### Steps to reproduce

Create an object that conforms to Content:

```swift
/// Data fields accessible to API routes and Leaf templates
struct UserProfile: Content {
	let id: Int
	let email: String
	let name: String
	let city: String
	let joinedAt: Date //DANGER!
}
```

In my case, I have a `final class UserAccount: MySQLModel` which is the database representation. I've created a convenience method that returns the externally accessible fields (excluding the password hash, etc):

```swift
extension UserAccount {
	/// Return the user's profile information
	func getProfile() throws -> UserProfile {
		return try UserProfile(
			id: requireID(),
			email: email,
			name: name,
			city: city,
			joinedAt: joinedAt //DANGER!
		)
	}
}
```

Then, during route processing, I get the UserAccount object from the currently authenticated user session (using the Authentication module) like so:

```swift
	let profile: UserProfile?
	if let userOpt = try? req.authenticated(UserAccount.self),
		let user = userOpt,
		let userProfile = try? user.getProfile()
	{
		profile = userProfile
	}
	else {
		profile = nil
	}
```

This profile then gets added to a struct that's used as the context for leaf template rendering. For debugging purposes, I have created an extension to Router that allows me to append /json to any Leaf route to have the template context returned as JSON.

```swift
struct CategoryContext: TemplateContext {
	var user: UserProfile?
	//more
}
```

And TemplateContext is simply:

```swift
protocol TemplateContext: Content {
	var user: UserProfile? { get set }
}
```

I've verified that my route does correctly return a `Future<CategoryContext>` without error, and that the server crash occurs after my route handler has returned. I've also confirmed that just commenting out the `let jonedAt: Date` line (and the corresponding line in the constructor where I pass it the joinedAt value), the server crash goes away. Also, when I run swift build without `-c release` and run the vapor app without `--env production`, there is no crash.

### Expected behavior

I expect this to properly format the Date as JSON without crashing the server.

### Actual behavior

The server crashes without an error message.

### Environment

I'm running a release build with the production environment in a Docker container.

* Vapor Framework version: 3.0.0-rc.2.5
* Vapor Toolbox version: 3.1.6
* OS version: Ubuntu 16.04.4 LTS (in Docker)

**Comment by 0xTim** [comment]
If you build and run as release in Xcode do you get a stack trace?

**Comment by tanner0101** [comment]
Yeah stack trace would be helpful to see where this is coming from. I will try to create a test case for this either way to see if it is reproducible.

**Comment by tanner0101** [comment]
Let’s re-open if we can get an actual crash log or small repro case. 👍
