### ISSUE TITLE
Discussion: error logging

### ISSUE THREAD

**Issue by damirstuhec** [vapor/vapor#1633]
`ErrorMiddleware` currently logs errors only [when _not_ in production](https://github.com/vapor/vapor/blob/5f2cb6b2efd1ee7dfcf7ed1a996fb6d45ba8acbf/Sources/Vapor/Middleware/ErrorMiddleware.swift#L39).
IMO, some kind of error logging would definitely help developers track down errors, even when in production, but let's discuss what are your thoughts about if/what/how you think we should log errors in different environments.

* Vapor Framework version: 3.0.0-rc.2.6

**Comment by tanner0101** [comment]
Log.reportError should probably be moved to the console package and expanded to support some basic verbosity levels

**Comment by tanner0101** [comment]
This method has been publicized in #1647
