### ISSUE TITLE
rename Content.defaultMediaType to defaultContentType

### ISSUE THREAD

**Issue by bre7** [vapor/vapor#1636]
### Steps to reproduce

Specified `defaultContentType` isn't used in custom Responses.

Code:

```swift
    func uploadFile(_ req: Request) throws -> Future<Response> {

        struct TestFileRequest: Content {
            static let defaultContentType: MediaType = .formData
            let data: Core.File
        }

        return try req.content.decode(TestFileRequest.self)
            .map(to: Response.self) { fileReq in
                let res = req.makeResponse()
                try res.content.encode(fileReq)  // issue, same as `return try fileReq.encode(for: req)`
                return res
            }
    }
```

If `try res.content.encode(fileReq, as: .formData)` is specified instead, it will work as intended.

### Expected behavior

Multipart/Form-Data encoded response:
```HTTP
-----vaporBoundary2331d396484b40b8533394d1c36d361c
Content-Disposition: form-data; filename=test.pdf; name=data
Content-Type: application/pdf

%PDF-1.3
```

### Actual behavior

JSON enocded response (which is the default media type)
```json
{"data":{"filename":"test.pdf","data":"JVBERi0xLjMKJc..."}}
```

### Environment

* Vapor Framework version: 3.0.0-rc.2.7
* Vapor Toolbox version: 3.1.4
* OS version: macOS HS 10.13.4

**Comment by tanner0101** [comment]
Hmm... that's weird. Definitely a bug.

**Comment by bre7** [comment]
BP on ContentContainer => encode shows `mediaType` being json 😕

**Comment by tanner0101** [comment]
Hmmm....I think it's a typo there. `s/defaultMediaType/defaultContentType`

**Comment by bre7** [comment]
🤦‍♂️  wow...ignore this issue

**Comment by tanner0101** [comment]
It really should be `C.defaultContentType` though.... that needs to be changed. Current name is confusing.
