### ISSUE TITLE
restore `ViewRenderer`

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1637]
This was accidentally replaced by TemplateRenderer which is not suitable for mocking or more generalized view renderers.

**Comment by bre7** [comment]
Removed _Aug 20, 2017_: https://github.com/vapor/vapor/commits/master/Sources/Vapor/View/ViewRenderer.swift
Last updated version: https://github.com/vapor/vapor/blob/7e9bf867791e9a42ee6d46e99985f77208dfd169/Sources/Vapor/View/ViewRenderer.swift

**Comment by tanner0101** [comment]
Yup that's basically exactly what we need, just should be in the template-kit repo instead. 👍

**Comment by bre7** [comment]
https://github.com/vapor/template-kit/pull/15
