### ISSUE TITLE
Vapor 3 docs wrong for leaf tags

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1641]
The docs at https://docs.vapor.codes/3.0/leaf/custom-tags/ seem completely invalid for custom leaf tags.  `Leaf.LeafTag` doesn't exist, nor does `ParsedTag`

* Vapor Framework version: 3.0.0-rc.2.6
* Vapor Toolbox version: 3.1.4
* OS version: mac High Sierra

**Comment by tanner0101** [comment]
@grosch leaf 3.0 is still unreleased so the docs are still unfinished/out of date. They will be updated with the official tag. Closing here since this repo is unrelated.
