### ISSUE TITLE
support http/2

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1650]
Once SwiftNIO implements HTTP2 support, we can add to Vapor.

**Comment by anthonycastelli** [comment]
👍 I'm desperately waiting for this 😝

**Comment by dougonecent** [comment]
Any thought about creating a branch for the current beta of swift-nio-http2?

**Comment by kylebrowning** [comment]
Linked here. https://github.com/apple/swift-nio-http2

**Comment by kylebrowning** [comment]
@tanner0101 Any chance we could get a beta branch of this. I'm waiting on this for so many things. 

Id be happy to help test as well.

**Comment by tanner0101** [comment]
@kylebrowning this is high on my list of todos, but it's going to require a fair amount of work to find an API that makes sense and works alongside existing HTTP/1 stuff. 

AFAIK, if you reverse proxy your vapor app behind nginx (which we highly recommend), [nginx will handle HTTP/2](https://serverfault.com/questions/765258/use-http-2-0-between-nginx-reverse-proxy-and-backend-webserver) and communicate with your app in HTTP/1. This is a win-win since you get the benefits of HTTP/2 (multiplexing, etc) but the performance and simplicity of using HTTP/1 in Vapor.

**Comment by kylebrowning** [comment]
@tanner0101 Im mainly waiting on it so I can use [this](https://github.com/vapor-community/apns) with vapor 3.

Since Apple uses a HTTP/2 for APNS  to accept requests its more on sending the requests from Vapor not receiving them.

(You'll note that you're mentioned here as well, https://github.com/vapor-community/apns/issues/1)

**Comment by kylebrowning** [comment]
@tanner0101  Off topic from this thread but I guess the idea is, since there's no DB storage in NIO. Id need to support the storage and registration of subscriptions/devices inside of Vapor (ie the device id's, and channels) and then setup something separate on Swift-NIO that actually communicates with Apple, but my Vapor App communicates with the NIO stack?

**Comment by tanner0101** [comment]
@kylebrowning Vapor's `Request` gives you access to a SwiftNIO `EventLoop` (`req.eventLoop`). That is the key to all of this really. Vapor's HTTP client for example is just a wrapper around SwiftNIO channel handlers. When you make an HTTP request using Vapor, a new set of NIO HTTP client handlers are initialized on the current event loop, and the request is sent. So for the case of APNS, you would create a wrapper around NIO HTTP/2 client handlers that know how to interact with APNS. That wrapper would just need to accept an event loop upon init. Then, to use this code from Vapor, you would just initialize an instance of that wrapper, passing in the current event loop. Whatever data you need to send to APNS you can get normally using Fluent or whatever you like. 

```swift
import Vapor
import NIOAPNS

func fooAPNS(_ req: Request) -> Future<HTTPStatus> {
    let apns = APNSClient(on: req.eventLoop)
    let messages = Message.query(on: req).all()...
    for message in messages {
        apns.send(text: message.text)
    }
}
```

There's a very rough idea of what it could look like, not accounting for futures or anything of course.

**Comment by crontab** [comment]
> @kylebrowning ah, yeah that package. I can't remember where I posted this (probably in Discord), but my recommendation with that library is to build it directly on top of SwiftNIO. IMO, It doesn't make sense for the library to use Vapor's convenience HTTP clients for that kind of work. It would be much more performant and memory efficient to use NIO directly. Especially in the case of push notifications, where one is often sending thousands (sometimes even millions), that could make a huge difference.
> 
> Once a pure NIO implementation exists for that lib, it will be trivial to make a nice Vapor wrapper for it. Whether or not Vapor itself provides any HTTP/2 support out of the box.

Could someone please clarify: does the above mean you may end up with two versions of NIO in your app? I.e. Vapor depends on NIO1, while the mentioned APNS library depends on NIO2. If so, that's probably not a great idea (to my understanding) as NIO creates thread pools per processor core and therefore it should be done only once.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
