### ISSUE TITLE
additional toolbox templates

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1651]
SQLite is probably never going to be the actual database somebody uses.  Can we instead default to something like PostgreSQL, or at least provide a flag to the `vapor new` command where we can specify the database type to use?

**Comment by twof** [comment]
Are you talking about the template?

**Comment by twof** [comment]
Ahhh yeah that shouldn't be too hard. Calling `vapor new` with a template just clones https://github.com/vapor/api-template right now, so if you want to, you can create your own template and use that instead. If you don't though, I'm sure someone else will eventually. 

I assume the reason for using SQLite though is that it's already enabled on most OSs and doesn't need any configuration.

**Comment by tanner0101** [comment]
It's the goal to have templates for each db driver 👍

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
