### ISSUE TITLE
[Doc] Incorrect behavior in req.session

### ISSUE THREAD

**Issue by bre7** [vapor/vapor#1652]
https://github.com/vapor/vapor/blob/master/Sources/Vapor/Sessions/Request%2BSession.swift#L3:

```swift
/// Returns the current session or creates one. `nil` if no session exists.
public func session() throws -> Session {
    // ...
}
```

The comment, as it is now is, is incorrect: the function returns a new one or the current one, no nil.

Should it return nil instead of an empty session ?

**Comment by tanner0101** [comment]
This comment has already been fixed in #1647. The behavior of the function is intended to create a new session if none exists. 👍
