### ISSUE TITLE
Remove trailing whitespaces in circle.yml file

### ISSUE THREAD

**Issue by Stephanyan** [vapor/vapor#1653]
Just noticed these trailing whitespaces in the ci config file.

![trailing-whitespaces-gif](https://user-images.githubusercontent.com/5939522/39475689-7ca954f4-4d59-11e8-964a-cd69554e279c.gif)

It's not a big issue but I can help cleaning that file by removing those trailing whitespaces.

**Comment by tanner0101** [comment]
Fixed in #1647
