### ISSUE TITLE
Add helper to set HTTP status without losing response body

### ISSUE THREAD

**Issue by wattson12** [vapor/vapor#1654]
This is a suggestion for an enhancement to allow simply setting a response status code, without losing the existing body when working with future content 

I would like to take a `Future<SomeContentType>` and return that same future, with the status code modified

A typical example would be creating a new model: I would want to return the newly created value as JSON, with the status code set to 201 / created

### Current behaviour:

```swift
final class ModelController {

    func create(_ req: Request) throws -> Future<Model> {
        return try req.content
            .decode(Model.self)
            .save(on: req)
    }

}
```

This controller will return the model correctly, with a status of 200

### What I would like

```swift
final class ModelController {

    func create(_ req: Request) throws -> Future<Model> {
        return try req.content
            .decode(Model.self)
            .save(on: req)
            .withStatus(.created)
    }

}
```

This would return the same JSON, with the correct 201 code

### My current workaround

This is what I am currently using, but I'm not sure about its efficiency 

```swift
extension Future where T: Content {

    func withStatus(_ status: HTTPStatus, using request: Request) -> Future<Response> {

        return self.map { value in
            let response = request.makeResponse()
            response.http.status = status
            try response.content.encode(value)
            return response
        }
    }
}
```

```swift
final class ModelController {

    func create(_ req: Request) throws -> Future<Model> {
        return try req.content
            .decode(Model.self)
            .save(on: req)
            .withStatus(.created, using: req)
    }

}
```

### Environment

* Vapor Toolbox: 3.1.4
* Vapor Framework: 3.0.0-rc.2.8.1
* OS version: macOS 10.13.4

**Comment by tanner0101** [comment]
I like this idea. Could be even more useful as an extension to `ResponseEncodable` directly.

```swift
extension ResponseEncodable {
    public func encode(with status: HTTPStatus, for req: Request) -> Future<Response> { ... }
}
```

**Comment by tanner0101** [comment]
Added in #1647, thanks!
