### ISSUE TITLE
Routing with path arrays

### ISSUE THREAD

**Issue by timvermeulen** [vapor/vapor#1658]
`Router`'s public routing methods all have a `PathComponentsRepresentable...` parameter. I wrote a custom type with a method that takes a `PathComponentsRepresentable...` parameter which I want to forward to `Router.post`, but that's currently not possible due to a language limitation ([SR-128](https://bugs.swift.org/browse/SR-128)).

Is there a workaround I can use? Or are there any plans to add `get`/`post`/`put`/etc overloads to the `Router` type that take a `[PathComponentsRepresentable]` parameter?

My current workaround is to copy the implementation of the `_on` method and use that, but that needless to say isn't ideal.

**Comment by tanner0101** [comment]
Good catch. We should expose an array accepting method. Freakin variadics....
