### ISSUE TITLE
Vapor 2 and swift 4.1

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/vapor#1659]
Thank you for Vapor!

Do you have any plan to adopt Vapor 2 to swift 4.1. It compiles and works fine, but I have like 50 warnings during compilation. Not sure I have time in nearest future to adopt project to Vapor 3. As it changed significantly.

I think a lot of projects will use Vapor 2 for long time. As really Vapor 3 looks like absolutely other framework. And currently there is no instruction/tool how to migrate it. As I see still not all modules (e.g. CSRF) are migrated to Vapor 3.

Sure in future I will migrate. As Vapor 3 looks great. For now, it is good if we can use old one without warnings.

Thanks in advance

**Comment by rpinz** [comment]
[Upgrading Versions](https://docs.vapor.codes/3.0/version/upgrading/)

**Comment by tanner0101** [comment]
Yes, we should get rid of warnings in Vapor 2. I will look into this, thanks @Igor-Palaguta.

**Comment by Igor-Palaguta** [comment]
@tanner0101 Thank you! I promise will migrate to Vapor 3), when I have time. As it is really very cool!

**Comment by MrLotU** [comment]
Fixed by #1814
