### ISSUE TITLE
SessionsMiddleware doesn't clear session from cache

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1661]
When calling:

```swift
try req.unauthenticateSession(User.self)
try req.destroySession()
```

The session cookie is successfully unattached from the user but the previous session is not removed from the Redis cache.

**Comment by mcdappdev** [comment]
This is also the case for when a cookie expires - it unattaches the request from that cookie successfully but then it's left in the cache

**Comment by rafiki270** [comment]
merged
