### ISSUE TITLE
Vapor 3 Fluent provider for mongodb

### ISSUE THREAD

**Issue by absinha18** [vapor/vapor#1664]
I was trying to migrate from Vapor 2 -> 3 and could not find any updates to MongoDB Fluent provider for Vapor 3? Is it not supported ? What's the best option to be able to use MongoDB with Vapor 3?

**Comment by twof** [comment]
@Joannis

**Comment by tanner0101** [comment]
@absinha18 Vapor recommends using PostgreSQL with Vapor 3: https://github.com/vapor/postgresql

This package is officially maintained and documented by the Vapor core team and should work great 👍
