### ISSUE TITLE
Future Async call wait() crashed

### ISSUE THREAD

**Issue by kingiol** [vapor/vapor#1669]
* Vapor Framework version: 3.0.2
* Vapor Toolbox version: 3.1.7
* OS version: MacOS 10.13.4

code in controller like this:

``` swift
let conn = try req.requestPooledConnection(to: .psql).wait()
defer { try? req.releasePooledConnection(conn, to: .psql) }
```

then on wait() line, crashed:

> NIO-ELT-#1 (4): Precondition failed: wait() must not be called when on the EventLoop

``` swift 
public func wait() throws -> T {
        if !(self.eventLoop is EmbeddedEventLoop) {
            precondition(!eventLoop.inEventLoop, "wait() must not be called when on the EventLoop")
        }
... etc
```

**Comment by twof** [comment]
You shouldn't be using `.wait()` in any code being touched by routes. As nice as it is, you should be using `map()` or `flatMap()` if you need to get access to the future value.

**Comment by rustymagnet3000** [comment]
@twof good pointer.  Shame the docs still suggest `wait`

https://docs.vapor.codes/3.0/http/client/
