### ISSUE TITLE
Returning a Response directly from Client.get in Heroku throws an error

### ISSUE THREAD

**Issue by ghost** [vapor/vapor#1670]
Returning a `Response` directly from `client.get` returns the following error in Heroku:
```http_error="Bad chunk" at=error code=H17 desc="Poorly formatted HTTP response"```

However, if you were to modify the code slightly, it will not return an error, and it will work.

### Steps to reproduce

Pre-requisites:
- To replicate my problem, you will need to obtain an API Key from the Riot Games API, available at: https://developer.riotgames.com/

1. Create a new route:

 ```swift
router.get("test") { req -> Future<Response> in 
    let API_KEY = "INSERT API KEY HERE"

   let url = URL(string: "https://euw1.api.riotgames.com/lol/summoner/v3/summoners/by-name/test?api_key=\(API_KEY)")
   return try send(toURL: url!, request: req, API_KEY: API_KEY)
}

func send(toURL url: URL, request: Request, API_KEY: String) throws -> Future<Response> {
    let client = try request.make(Client.self)
    return client.get(url, headers: ["X-Riot-Token" : API_KEY])
}
```

2. Commit the changes, and upload to Heroku

3. Using Paw / Postman / Rested app, send a request to Heroku for that route, and it will return the error: `error socket closed by remote peer`

4. On the terminal, go to the directory of the project hosted on Heroku, and enter `Heroku logs`. That will return you the error  `http_error="Bad chunk" at=error code=H17 desc="Poorly formatted HTTP response"`

=========================
The problem is fixed if you replace the `send` function with the following

``` swift
func send(toURL url: URL, request: Request, API_KEY: String) throws -> Future<Response> {
    let client = try request.make(Client.self)
    return client.get(url, headers: ["X-Riot-Token" : API_KEY]).map(to: Response.self, { clientResponse in 
     let response = request.makeResponse()
     response.http.status = clientResponse.http.status
     response.http.body = clientResponse.http.body
     return response
     })
}

```

If you then commit the changes, upload to Heroku, and make a request to the same route, it will return the correct response: 200 OK

### Expected behavior

Returning a `Response` directly from `client.get` should return a 200 OK response, given the code above. 

### Actual behavior

Returning a `Response` directly from `client.get` in Heroku is throwing an error.

### Environment
* Vapor Framework version: 3.0.1
* Vapor Toolbox version: 3.1.4

**Comment by vinamelody** [comment]
Hi, I'm interested to know a possible (similar) behavior with my code too

This works:

```swift
router.get("example") { req -> Future<Response> in
    // Fetch an HTTP Client instance
    let client = try req.make(Client.self)
    
    // Send an HTTP Request to example.vapor.codes/json over plaintext HTTP
    // Returns `Future<Response>`
    let response = client.get("http://example.vapor.codes/json")    
    return response
}
```

But this gave me error `cannot decode raw data NSURLErrorDomain:-1015`

```swift
router.get("luke") { req -> Future<Response> in
    let client = try req.make(Client.self)
    
    let response = client.get("https://swapi.co/api/people/1/?format=json")
    return response
}
```

**Comment by instig** [comment]
Good catch! I almost forgot something related!

Earlier this year I posted an issue: https://github.com/vapor/vapor/issues/1596

About FoundationClient not using URL correctly.

Well, it turns out, if I use 

```swift
 func send(toURL url: URL, request: Request, API_KEY: String) throws -> Future<Response> {
    let client = try request.make(Client.self)
    return client.get(url, headers: ["X-Riot-Token" : API_KEY])
}

```
In postman, it will return `Could not get any response`

However, if you modified the `send` function to now be: 

``` swift
func send(toURL url: URL, request: Request, API_KEY: String) throws -> Future<Response> {
    let client = try request.make(Client.self)
    return client.get(url, headers: ["X-Riot-Token" : API_KEY]).map(to: Response.self, { clientResponse in 
     let response = request.makeResponse()
     response.http.status = clientResponse.http.status
     response.http.body = clientResponse.http.body
     return response
     })
}

```

Postman will return the correct response. By adding

 ```swift 
.map(to: Response.self, { clientResponse in 
     let response = request.makeResponse()
     response.http.status = clientResponse.http.status
     response.http.body = clientResponse.http.body
     return response
     })
```

Has fixed the issue. So there IS a problem when returning data using a `get` request.

**Comment by instig** [comment]
@vinamelody That's the bug I am reporting above. It should work without using `map`, but it isn't.

**Comment by tanner0101** [comment]
@ghost the solution you mentioned here seems correct:
```swift
func send(toURL url: URL, request: Request, API_KEY: String) throws -> Future<Response> {
    let client = try request.make(Client.self)
    return client.get(url, headers: ["X-Riot-Token" : API_KEY]).map(to: Response.self, { clientResponse in 
     let response = request.makeResponse()
     response.http.status = clientResponse.http.status
     response.http.body = clientResponse.http.body
     return response
     })
}
```
That will avoid forwarding any headers like `transfer-encoding` that may be causing this issue. Let me know if that makes sense, thanks.
