### ISSUE TITLE
Harmonization of *[eE]qual and *[eE]quals in enum cases and static constants.

### ISSUE THREAD

**Issue by mixio** [vapor/vapor#1675]
Vapor modules sometimes use ".equal" and sometimes ".equals" in enums cases and static constants.

equal vs. equals,
lessThanEqual vs. lessThanEquals,
greaterThanEqual vs. greaterThanEquals,
notEqual vs. notEquals
etc.

Swift APIs seem to use exclusively the "*[eE]qual" form (no "s").

### Preferred behavior

Harmonization to the  "*[eE]qual" form. **Without "s".**

### Actual behavior

Mix of both forms.

For example in /Fluent/Query/Filter/QueryFilter.swift
```
    enum QueryFilterTypeStorage: Equatable {
        case equals //<--
        case notEquals //<--
        case greaterThan
        case lessThan
        case greaterThanOrEquals //<--
        case lessThanOrEquals //<--
        case `in`
        case notIn
        case custom(Database.QueryFilter)
    }

```
and in Core-3.1.6/Bits/Byte+Control.swift

```
    /// =
    public static let equals: Byte = 0x3D
```

### Environment

* Fluent 3.0.0-rc.2.4.1
* Core 3.1.6
* and probably other modules.

**Comment by LoganWright** [comment]
This seems to be resolved, if you find some strays missed, we'll add them into 4.0 since unfortunately it's a breaking change.

Thanks for the support 🙌
