### ISSUE TITLE
vapor 3 config document miss.

### ISSUE THREAD

**Issue by zerozheng** [vapor/vapor#1678]
After try to find how to config my Vapor 3 project, I found that the new version of Vapor do not contain the config Folder, and the document of how to config port and host is also miss in https://docs.vapor.codes/3.0

**Comment by vinamelody** [comment]
@zerozheng  how about this one https://docs.vapor.codes/3.0/http/server/#start ?

**Comment by tanner0101** [comment]
Would you mind re-opening this issue here: https://github.com/vapor/documentation? That will help it get resolved quicker 👍

**Comment by zerozheng** [comment]
@tanner0101 Thanks! This issue is reopened in https://github.com/vapor/documentation/issues/328
