### ISSUE TITLE
Incorrect documentation for Vapor router parameters

### ISSUE THREAD

**Issue by azamsharp** [vapor/vapor#1680]
Instead of 

try req.parameter(Int.self)

Is should be 

try req.parameters.next(Int.self)

### Environment

* Vapor Framework version:
* Vapor Toolbox version:
* OS version:

**Comment by 0xTim** [comment]
Which page is this on?

**Comment by 0xTim** [comment]
Was fixed in https://github.com/vapor/documentation/commit/5c241fc05cee60debf76bfbf6f3b63013f9f4505
