### ISSUE TITLE
Fresh project does not compile

### ISSUE THREAD

**Issue by kaunteya** [vapor/vapor#1681]
I am trying out Vapor for first time. I am following the steps mentioned in `Getting Started → Hello World` section of docs.

When I open the project in Xcode and try to run it, it gives me error saying `Use of Undeclared type 'Process'`. Clearly it is not able to locate the `struct Process`

### Steps to reproduce

```
vapor new test1
cd test1
vapor xcode
```
Select `Run` target in Xcode and hit run button.

### Expected behavior

Fresh app must show 'Hello World' on http://localhost:8080

### Actual behavior

Xcode gives error `Use of Undeclared type 'Process'` in Process+Execute.swift

### Environment

* Vapor Framework version: 3.0.1
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13.4
* Xcode version: 9.3.1

**Comment by kaunteya** [comment]
@anthonycastelli Yes. It fails on `Run` target

**Comment by rafiki270** [comment]
@kaunteya this happens whe you build against ios or apple tv, run on a mac and you’ll be fine. Please reopen is this won’t fix your issue.
