### ISSUE TITLE
Vapor Cloud: "product dependency 'Vapor' not found"

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [vapor/vapor#1682]
* Vapor Framework version: 3
* Vapor Toolbox version:
* OS version:10.13.4

build: clean
Creating deployment [Done]
Connecting to build logs ...
Waiting in Queue [Done]
Checkout branch 'master' [Done]
Verifying base folder [Done]
Selected swift version: 4.1.0-beta [Done]
Building vapor (release) [Failed]
/vapor/pjt-til-production/code/.build/checkouts/vapor.git-5492988889259800272: error: noManifest(baseURL: "https://github.com/vapor/vapor.git", version: Optional("3.0.0-rc.2.2.4"))
/vapor/pjt-til-production/code/.build/checkouts/fluent-sqlite.git--5503918280859119093: error: noManifest(baseURL: "https://github.com/vapor/fluent-sqlite.git", version: Optional("3.0.0-rc.2.1"))
'TILApp' /vapor/pjt-til-production/code: error: product dependency 'FluentSQLite' not found
'TILApp' /vapor/pjt-til-production/code: error: product dependency 'Vapor' not found

Error: deploy failed.

**Comment by zhuiyizhiqiu** [comment]
macbookpro:TILApp pengjuntao$ vapor cloud deploy
app: TIL
You have uncommitted changes!
Would you like to commit changes now?
y/n> 

I should select y or n?

**Comment by zhuiyizhiqiu** [comment]
I want not to change my Vapor Cloud, so I select no.
Then I find the fellow line code
    macbookpro:TILApp pengjuntao$ vapor cloud deploy
app: TIL
You have uncommitted changes!
Would you like to commit changes now?
y/n> n
Are you sure you'd like to continue?
y/n> y
Rogue mode enabled ...
git: https://github.com/zhuiyizhiqiu/vapor-til.git
env: production
db: none
replicas: 1
replica size: free
branch: master
build: clean
Creating deployment [Done]
Connecting to build logs ...
Waiting in Queue [Done]
Checkout branch 'master' [Done]
Verifying base folder [Done]
Selected swift version: 4.1.0-beta [Done]
Building vapor (release) [Failed]
/vapor/pjt-til-production/code/.build/checkouts/vapor.git-5492988889259800272: error: noManifest(baseURL: "https://github.com/vapor/vapor.git", version: Optional("3.0.0-rc.2.2.4"))
/vapor/pjt-til-production/code/.build/checkouts/fluent-sqlite.git--5503918280859119093: error: noManifest(baseURL: "https://github.com/vapor/fluent-sqlite.git", version: Optional("3.0.0-rc.2.1"))
'TILApp' /vapor/pjt-til-production/code: error: product dependency 'FluentSQLite' not found
'TILApp' /vapor/pjt-til-production/code: error: product dependency 'Vapor' not found

Error: deploy failed.

The error has show again!

**Comment by 0xTim** [comment]
Run `swift package update` and commit _only_ `Package.resolved`. It looks like it can't find the hash. Or run an `update` build type

**Comment by zhuiyizhiqiu** [comment]
Thank you so much!
The error has been again.
Maybe my vapor's version is vapor beta 3?

**Comment by 0xTim** [comment]
Does it work locally?

**Comment by zhuiyizhiqiu** [comment]
It work will in the Xcode  at my Mac.
I fellow chapter 5 of the book which is name Server Side Swift with Vapor.
Then the error is showing!
So, I don't  know how to resolve .

**Comment by 0xTim** [comment]
@zhuiyizhiqiu hmm I recommend you join the Discord chat and try and get help from the Vapor Cloud team. Other option is to delete your app in Vapor Cloud and try again

**Comment by zhuiyizhiqiu** [comment]
Thank you very very very much! 
Thank you give me so much suggestions!
Thank you give me so much help!
I will try it again!

**Comment by LinusGeffarth** [comment]
@tanner0101 / @0xTim / @zhuiyizhiqiu  has this been resolved? I'm experiencing the same issue...

**Comment by 0xTim** [comment]
It's normally a GH hiccup or you've checked your `.build` directory into source control

**Comment by LinusGeffarth** [comment]
You're right though, I've now removed the .build folder and now it builds... Thanks for this awesome framework btw!
