### ISSUE TITLE
Vapor Hello does not build

### ISSUE THREAD

**Issue by apistachio** [vapor/vapor#1683]
In my first experience, I wanted to run first demo. Should have been heaven...

Building hello per the docs yielded compiler time issues:

1) a protocol missing method to support Equatable func ==(....) {}
public enum DataPredicateComparison: Equatable { 
}

2) two methods in extension Collection  are missing parameter labels...

what I expected: 
 the first demo worked, I just want to show it off!

### Steps to reproduce

Follow these 4-5 steps:
brew vapor/tap/vapor
vapor --help
vapor hello
"click y to open xcode"
command-b to build

### Expected behavior

Clean build

### Actual behavior

Compiler errors 

### Environment

% vapor --version

* Vapor Framework version: 3.1.7
* Vapor Toolbox version: 3.0.1
* OS version: 10.13.3

<img width="889" alt="extensionmethodsmissinglabel" src="https://user-images.githubuserc
ontent.com/13409603/40091806-bab61334-586e-11e8-9a65-c2a6393af2c2.png">

**Comment by 0xTim** [comment]
@apistachio you need to upgrade Xcode. Vapor 3 requires Swift 4.1
