### ISSUE TITLE
Failed to fetch `Redis` dependencies.

### ISSUE THREAD

**Issue by Mioke** [vapor/vapor#1685]
I'm new to Vapor.

There's a weird thing that I want to import `Redis` in project, and my `package.swift` is:

```swift
let package = Package(
    name: "Server",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0-rc.2"),
        
        .package(url: "https://github.com/vapor/redis.git", .upToNextMajor(from: "3.0.0"))
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor", "Redis"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```
And when I run `vapor build` and it start to fetch dependencies. But it got stuck when fetching `Async`

```shell
...
Updating https://github.com/apple/swift-nio-ssl.git
Fetching https://github.com/vapor/redis.git
Updating https://github.com/vapor/fluent-sqlite.git
Fetching https://github.com/vapor/async.git
```
I copy the code from [document](https://docs.vapor.codes/3.0/redis/getting-started/).

And then I try to change the version from `3.0.0` to `3.0.0-rc` and it pass the build. I just wonder why it would happened and what version of dependencies I should use exactly.

### Environment

* Vapor Framework version: 3.0.1
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.4 (17E199)

**Comment by 0xTim** [comment]
@Mioke you can see the different releases in https://github.com/vapor/redis/releases

For now you'll need to use the `3.0.0-rc` as there is no `3.0.0` release

**Comment by Mioke** [comment]
I see, thank you @0xTim
