### ISSUE TITLE
Request Query Strings Percent Encoded Twice

### ISSUE THREAD

**Issue by DavidBrunow** [vapor/vapor#1687]
Query parameters encoded in QueryContainer.encode are being double-url-encoded so spaces are being changed to `%2520` instead of `%20`

### Steps to reproduce

Create a request and add a query string like so:
```swift
let client = try container.client()
let urlString = "https://apple.com"
let response = client.send(
            .GET,
            headers: HTTPHeaders(),
            to: urlString,
            beforeSend: { req in
                let myQuery = SearchProductRequest(query: "iphone 7", sort: "popularity")
                try req.query.encode(myQuery)
            })
```
```swift
struct SearchProductRequest: Content {
    var query: String
    var sort: String
}
```

The query string will be `query=iPhone%25207&sort=popularity`

The issue seems to be that setting the `.query` property of a `URLComponents` handles the percent encoding (per the documentation) but that percent encoding has already been done by the `.urlEncodedForm` data encoder.

### Expected behavior
I would expect that the query string be `query=iPhone%207&sort=popularity`

### Actual behavior
The query string is `query=iPhone%25207&sort=popularity`

### Environment

* Vapor Framework version: 3.0.2
* Vapor Toolbox version: 3.1.4
* OS version: macOS 10.13.4

**Comment by DavidBrunow** [comment]
Looking at it more, line 30 of `QueryContainer` needs to use the `percentEncodedQuery` property instead of `query` property. 

Want a pull request with that change?

**Comment by rafiki270** [comment]
@DavidBrunow PR is always appreciated :)

**Comment by DavidBrunow** [comment]
Address in PR: https://github.com/vapor/vapor/pull/1692

**Comment by bre7** [comment]
Did you notice the issue just now ? (i.e. after updating Vapor) Trying to find out if my PR broke it:  https://github.com/vapor/url-encoded-form/pull/8

**Comment by DavidBrunow** [comment]
Noticed it 5 days ago, but I don't think your change caused the problem. I only changed the name of 1 property and it doesn't look like you changed that.

**Comment by tanner0101** [comment]
@bre7 I think vapor/url-encoded-form#8 might be related. Before that I don't think the URL-Encoded Form stuff was ever getting percent-encoded so using `.query` here was fine. But now that we are percent encoding the output there (as we should be, since it has the information necessary to properly do that) we need to use `url. percentEncodedQuery`.

Thanks for patching that @DavidBrunow!
