### ISSUE TITLE
Support for NIO client

### ISSUE THREAD

**Issue by RR12** [vapor/vapor#1695]
So I'm just getting started with Vapor. And find out that I can't make Vapor client to ignore certificate verification. 

Since current client implementation is using URLSession (Foundation), can we add support for NIO Client since it provide more configuration including one that related to certificate verification (https://github.com/apple/swift-nio-ssl/blob/0adc938bc8de3d3829b842f9767d81c7480b8403/Sources/NIOOpenSSL/TLSConfiguration.swift#L112-L142) ? 

And I think It will be great if we can expose more configuration like this, so it can be passed through easily.

**Comment by bre7** [comment]
Similar to https://github.com/vapor/http/issues/283

**Comment by LoganWright** [comment]
I think this is no longer relevant, if I'm mistaken, please reopen.

Thanks so much for participating 🙌
