### ISSUE TITLE
How to synchronize the vapor added field to the corresponding table in the local MySQL database?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1699]
Hi !
I use **Vapor 3** to create a **User** that inherits from **MySQLModel**. When I add a **hobby** attribute to **User**, how can I **synchronize** the new hobby to the corresponding table in the local **MySQL database** on the MacOS computer? 

thanks !

> English is not my native language; please excuse typing errors.

**Comment by rafiki270** [comment]
Hi, this seems more of an implementation question than an issue. Would you mind asking on our Discord chat and possibly closing this issue?

**Comment by Jinxiansen** [comment]
@rafiki270  Oh no! This is a very confusing question! I haven’t been thinking about rice for a long time! 😭😭😭

**Comment by rafiki270** [comment]
?

**Comment by Jinxiansen** [comment]
Are there any relevant examples to refer to? How to add 1 attribute to MySQLMoel subclasses automatically increases in MySQL databases.

**Comment by mcdappdev** [comment]
@Jinxiansen It sounds like you're asking about Migrations. You should read up on the docs here: https://docs.vapor.codes/3.0/fluent/migrations/ or ask in the Discord chat: vapor.team. There are lots of people who will be happy to help in there, but I'm going to go ahead and close this issue as we try and keep the issues clean for bug reports :)

**Comment by Jinxiansen** [comment]
@mcdappdev   
I'm sorry, I would like to solve, but I do not know how to operate.

**Comment by mcdappdev** [comment]
You can create an account at https://discordapp.com/invite/vapor
