### ISSUE TITLE
Issue with large uploads and hosting videos

### ISSUE THREAD

**Issue by adiwajshing** [vapor/vapor#1700]
First off, vapor is awesome. I really like being able to code for the web in swift.
However, I'm experiencing two issues:

1. ->Hosting a video in the public folder: If I put a video in the public folder and enter the url to it in a web browser (for eg. http://localhost:8080/vid.mp4), the video almost starts to play but then I get a crossed play icon. This happens even when I use the AVPlayer

2. ->Uploading large files: I've set the maxBodySize to 1GB since my app will need to support large video uploads. However, when I do upload using a data task or AFNetworking, the server side code gets executed but I get a request timed out error.

### Steps to reproduce

For issue 1. ->Just place a video in the public folder and try to access it using a web browser
For issue 2. ->Try uploading a large file and sending back the client a response

### Expected behavior

Well, the video should play and the upload request shouldn't time out.

### Environment

* Vapor Framework version:
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13

**Comment by adiwajshing** [comment]
1. Yes, I simply register FileMiddleware.self. Other files, like images are served fine from the public folder.
2. I'm using the basic router.post for now, I get the video as Data, save it and return a success or failure string.

**Comment by rafiki270** [comment]
1) check what mime and other headers are being sent to the client app, it could be a problem if not video headers
2) could you please post the code? :)

**Comment by adiwajshing** [comment]
'check what mime and other headers are being sent to the client app, it could be a problem if not video headers' 
how do I get this?

Here's the code, there isn't a lot though.
I just use a content to store the file in as a data object and then save it through another function.

struct AddVideoDataRequest: Content {
    
    var user: String
    var pass: String
    var name: String
    var path: String
    var tags: String
    var video: Data
}

do {
            try file.write(to: vidUrl)
        } catch let error {
            print(error)
        }

**Comment by mcdappdev** [comment]
Hi @adiwajshing! Glad to hear you're enjoying Vapor. I see a few problems here:

1. You definitely should not try and serve that video file using the FileMiddleware. FileMiddleware should really only be used in development to test out serving public folders. You should route all of your public files through either a reverse proxy such as Nginx or a CDN like Cloudfront when in production. Serving public files really isn't an application responsibility and things like Nginx are battle tested for exactly this purpose. My guess is that this will solve that problem :) 

2. I would suggest uploading a large video using the Multipart library. You can read more here: https://docs.vapor.codes/3.0/multipart/overview, but the general gist is that you can do something like this:

```swift
import Vapor
import Multipart

struct AddVideoDataRequest: Content, Multipart {
    var video: File
    //your other properties here, same as other struct
}
```

That is more equipped to handle large file uploads and is the preferred format. 

3. I noticed you are attempting to write the file to disk. I'm not sure what your production setup is going to look like so I won't comment on that too much, but be aware that if you do any kind of horizontal scaling this is going to become a problem very quickly. I would suggest S3 or GCP file storage as an alternative. 

Hope this helps clear things up!

**Comment by adiwajshing** [comment]
1. Is there a workaround for FileMiddleware? The server I'm building will only be used locally

2. It says use of undeclared type 'Multipart'. using File instead of Data doesn't work.

3.  It's fine, the file would max be 80 or a 100 megs. 

Thanks!

**Comment by mcdappdev** [comment]
Not sure if there’s a workout for FileMiddleware locally. You could always run it in a docker container and stick it behind Nginx, I think that would work. 

In regards to Multipart, it’s a separate package so you’ll need to add it to your Package file and then import the module after regenerating the Xcode file

**Comment by tanner0101** [comment]
It's possible this is related to some bugs that were fixed recently in Vapor's HTTP package. See https://github.com/vapor/http/releases/tag/3.1.4.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
