### ISSUE TITLE
[Feature Request] Detecting vapor itself in build time and package resolving.

### ISSUE THREAD

**Issue by omochi** [vapor/vapor#1701]
I want a feature that detecting vapor itself in build time and package resolving.

# Problem

In my project, I am sharing some source files between server side with vapor and client side on iOS.
Sometimes code contains a feature which can be only implemented in vapor or iOS.
In real world, all library does not support all platforms,
The one only supports Linux, the other does only iOS.
So I need to split sharable code into a package and unsharable code into platform dedicated package using extensions etc.
But this package splitting approach is not enough for actual development.
For example, type definition itself must be written in common package.
In my case, I made the logic which calculates distance in two geo location and represent it as `GLKVector2` in `GLKit`.
But `GLKit` does not provided in Linux so I need handwritten implementation of `GLKVector2`.
To solve these situation, I need some method to determine if this code is build for vapor.
Not only that, sometimes I want to use another library for same purpose in each platforms.
For example, asynchronous operation in vapor should be represent with `Future` in `vapor/core`.
But in client side, I want to use `RxSwift.Single` for this.
In such situtaiton, I need method to change package dependency definition when it resolve.

# Feature request

In short, I request feature that two functionality to vapor.

- (1) detecting vapor in build time
- (2) detecting vapor in package resolving time

# My proposal

## Detecting vapor in build time

To produce feature (1), vapor should pass build flag to compiler such like `-DVapor`.
With this flag, I detect it by using `#if` preprocessor.
Example in below.

```swift
#if Vapor
public struct GLKVector2 {
	public var x: Float
	public var y: Float
}
#else
import GLKit
#endif
```

Currently vapor toolbox has `vapor.json` feature.
So I can do this manually like below.

```json
{
    "name": "myproj-vapor",
    "flags": {
        "build": {
            "mac": [
                "-Xswiftc", "-DVapor"
            ],
            "linux": [
                "-Xswiftc", "-DVapor"
            ]
        },
        "test": {
            "mac": [
                "-Xswiftc", "-DVapor"
            ],
            "linux": [
                "-Xswiftc", "-DVapor"
            ]
        }
    }
}
```

Unfortuntely it is clearly too verbose.
I want to support this flag natively by vapor toolbox.

## Detecting vapor in package resolving time

To produce feature (2), vapor should pass a shell environment variable
to internal `swift-package` command in vapor toolbox.

With this flag, I detect it by writing dynamic controlled `Package.swift` like below.

```swift
// swift-tools-version:4.0

import PackageDescription
import Foundation

var dependencies: [Package.Dependency] = [
]

if let str = ProcessInfo.processInfo.environment["VAPOR"],
    let value = Int(str), value != 0
{
    // Use Future in Vapor
} else {
    // Use RxSwift in iOS
    dependencies.append(.package(url: "https://github.com/ReactiveX/RxSwift.git", from: "4.1.2"))
}

let package = Package(
    name: "myproj-common",
    products: [
        .library(name: "MyProjCommon", targets: ["MyProjCommon"]),
    ],
    dependencies: dependencies,
    targets: [
        .target(name: "MyProjCommon", dependencies: []),
    ]
)
```

And in source code, I can use it with (1) feature.

```swift
#if Vapor
import Vapor
#else
import RxSwift
typealias Future<T> = RxSwift.Single<T>
#endif

public func download(url: URL) -> Future<Data> {
	// in implementation, 
	// I may need branching macro here.
	// But I also can reduce it by implement
	// abstraction layer to hide undelying library.
	...
}
```

# Implementation

If vapor development team agree my opinion,
I can implement them and submit pull request of them.

**Comment by rafiki270** [comment]
hi @omochi, do you know of:
```swift
if os(Linux)
   import Glibc
#else
   import Darwin
#endif
```

Also, not sure about the package resolve time, that's all handled by the SPM and has nothing to do with Vapor ...

**Comment by omochi** [comment]
@rafiki270 Thanks for advice. Of course I know.
But I also split vapor server on mac (debugging with Xcode) and cocoa app client.
Linux server and linux client (its may CUI tool)  
This story is a just example and I need to know if vapor or not.
Yes SwiftPM does not support iOS now,
Actually I use carthage for this so `Package.swift` for vapor and `Cartfile` for iOS in my repository.
Its just run but completely broken semantically.
SwiftPM now supports macOS so server on mac and client on mac are problem.
And SwiftPM project is progressing towards iOS support I know.

**Comment by rafiki270** [comment]
well, at least I would wait till the WWDC in a few days before making any PR's on this :)

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
