### ISSUE TITLE
How to count API access times, time, IP and other information to the database 🦄🦄🦄

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1702]
I want to count API access times, time, IP and other information to the database. I don't know if Vapor 3 has any framework support.

> English is not my native language; please excuse typing errors.

**Comment by alexsteinerde** [comment]
You closed the issue. 
Did you find any solution for your problem? If you have please share your solution, because I am also interested in this feature.
Thanks.

**Comment by alexsteinerde** [comment]
Thanks @joscdk. Sounds like a good solution.

**Comment by Jinxiansen** [comment]
Hey hey, I would like to try the Kibana ！

**Comment by joscdk** [comment]
@Jinxiansen it require a bit of setup, but you could consider a hosted elasticsearch e.g. AWS ElasticSearch which comes with Kibana out of the box

There is a gist here for setting up ELK with FileBeat (To send logs) https://gist.github.com/Dev-Dipesh/2ac30a8a01afb7f65b2192928a875aa1 .. (I havn't personally tested that particular guide)
