### ISSUE TITLE
Add Xcode Project template for starting Vapor 3 projects

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/vapor#1703]
See the sample of why this might look like here https://twitter.com/helje5/status/1001552223267180545?s=21

**Comment by LoganWright** [comment]
Hey, so I looked into what it would take to add the xcode templates and it's quite a bit of work to go into Xcode files and configure it to kick out new project templates. This would make it pretty hard to distribute to users and I don't think we'll be able to support it.

Cool idea though, maybe if there's more explicit xcode support for distributing in the future, it would be fun. For now, the template from GH will have to work. 

Thanks!
