### ISSUE TITLE
vapor new "project" --web

### ISSUE THREAD

**Issue by mynona** [vapor/vapor#1708]
The command 

`vapor new "project" --web`

does not generate a valid Vapor 3 project.

The installed framework version is **2.3.0** and **not 3.0.x**

Updating the project manually fails, as the current "Leaf Provider" package is not accepted with Vapor 3.

Creating an XCode-Project with

`vapor xcode`

still includes the old frameworks.

This issue also breaks deployment to heroku.

**Comment by vzsg** [comment]
The core issue is that the web template is not updated for Vapor 3 yet. Hopefully it will happen in the future.

Upgrading the v2 template is more elaborate than just changing a few version numbers. For example, there's no "leaf-provider" anymore, only the Leaf package is needed. But that's not final yet, so you'd need to specify an RC version. Then you need to clear out a lot of crap that's not relevant for v3...

---

You should instead start from the api-template and add Leaf.

**Comment by 0xTim** [comment]
(The web template is waiting for Leaf to exit beta status before getting an update)

**Comment by dewib** [comment]
Would this (need for update to web template) explain the error I'm getting building under ubuntu 16.04.4.

> /home/frank/Demo/.build/checkouts/vapor.git--7337820407347537864/Sources/Configs/Config+Directory.swift:51:20:
> 
>  error: cannot convert return expression of type 'ObjCBool' to return type 'Bool'
>             return isDirectory
>                    ^~~~~~~~~~~

**Comment by vzsg** [comment]
Probably. Try running `swift package update` to pull in Vapor 2.4.4 at least – this incompatibility issue should have been resolved since 2.3.0.

**Comment by joscdk** [comment]
Closing this issue, since web template have been updated for Vapor 3
