### ISSUE TITLE
thread-safe controllers

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1711]
This issue proposes a new method of registering controllers to your application that would allow for creation of thread-safe controllers. Currently Vapor 3 provides thread-safe access to the services your application requires (such as databases, clients, etc) by using the `Request` as a container. Like so:

```swift
func routes(_ router: Router) throws {
    router.get("test") { req in
        return req.withPooledConnection(to: .psql) { ... }
    }
}
```

By using the Request to initialize services, Vapor can ensure that each EventLoop gets its own Container and each Container is only used on its specific EventLoop.

However, using this model it is impossible to store any variables on controllers in a thread-safe manner. Take the following example:

```swift
final class UserController {
    var test: [String: String]
    
    func test(_ req: Request) -> String {
        let name = try req.parameters.next(String.self)
        return test[name] ?? "n/a"
    }
}
```

Because the `test(_:)` method may be called across multiple threads, and it is accessing shared memory, this code creates a race condition. This is typically solved in Vapor 3 by creating a service to hold the `[String: String]` data (via a reference wrapper) and accessing it via the Request Container. This works, but it's not immediately obvious to new developers, especially those coming from iOS. Another solution would be to wrap the `[String: String]` in semaphores / locks, but that would introduce a lot of unnecessary overhead.

A third solution to this problem would be to allow for registering thread-safe controllers. The best way to depict how this would work is with a code example:

```swift
func routes(_ container: Container) throws -> EngineRouter {
    let router = EngineRouter.default()
    router.get("test") { req in
        return container.withPooledConnection(to: .psql) { ... }
    }
    return router
}
```

Instead of registering a single `Router` to the `Application`, you would provide a function that accepts a container and returns a router. This container would be a sub-container of application--one for each event loop.

In this way, your application's routes would be registered once _per_ event loop, allowing for sharing of local variables within the `routes(_:)` method. You are guaranteed that all routes registered in the same method will always be called on the same thread.

Using this method, you could continue to create controllers like you could in Vapor 2:

```swift
final class FooController {
    let client: Client
    init(client: Client) { self.client = client }
    func foo(_ req: Request) -> Future<Response> {
        return client.get("http://vapor.codes/foo") 
    }
}

func routes(_ container: Container) throws -> EngineRouter {
    let router = EngineRouter.default()
    let controller = FooController(client: container.make())
    router.get("foo", use: controller.foo)
    return router
}
```

Really the only changes required to utilize this are in the structure of your application. If you don't opt in to creating one router per event loop, your application will continue to exhibit the old behavior. Thread-safe controllers could potentially be an interesting concept to try out in a future version of Vapor.

*HTTPRequest/ Request simplification*

With thread safe controllers, `Request` will no longer need to be a `Container` (since the container will be accessible at the route registration / controller phase. This will mean that HTTPRequest and Request can be combined, simplifying the middleware and router layers.

**Comment by tanner0101** [comment]
Another example worth sharing is how this change would make it much easier to implement the repository pattern. The below example illustrates how this could work. It's also worth noting that `Model.defaultDatabase` is not required in this example since the type information about `.sqlite` comes during the configuration process. 

```swift
final class UserController {
    let users: UserRepository
    init(users: UserRepository) {
    	self.users = users
    }

    func index(_ req: Request) throws -> Future<[User]> {
    	return users.getAll()
    }
}

protocol UserRepository {
	func getAll() -> Future<[User]>
}

struct FluentUserRepository {
	let pool: SQLiteDatabase.ConnectionPool
	init(pool: SQLiteDatabase.ConnectionPool) {
		self.pool = pool
	}

	func getAll() -> Future<[User]> {
		return User.query(on: pool).all()
	}
}



func routes(_ container: Container) throws -> EngineRouter {
    let router = EngineRouter.default()

    let users: UserRepository
    switch container.environment {
	case .testing: // use test user repo
	default: users = try FluentUserRepository(pool: container.connectionPool(to: .sqlite))
    }

    let controller = UserController(users: users)
    router.get("users", use: controller.index)

    return router
}
```

**Comment by tanner0101** [comment]
After looking into this a bit more, it seems this could be achieved without any internal changes to Vapor. Just one change to the API template.

### Current

Currently the router is registered as a singleton and shared across all sub-containers.

```swift
let router = EngineRouter.default()
try routes(router)
services.register(router, as: Router.self)


public func routes(_ router: Router) throws {
    router.get("client") { req in 
        return req.client().get(...)
    }
}
```

### Updated

By registering the router as a factory, and passing in the subcontainer, services could be created outside of route closures. 

```swift
services.register(Router.self) { container -> EngineRouter in
    let router = EngineRouter.default()
    try routes(router, container)
    return router
}

public func routes(_ router: Router, _ app: Container) throws {
    // we can create services here now because the container passed to this function
    // is the same container passed to the route closures
    let client = app.client()
    router.get("client") { req in 
        return client.get(...)
    }
}
```

This change would allow us to do things like:

```swift
let mysql = try app.connectionPool(to: .mysql)
let planets = PlanetController(mysql)
router.get("planets", use: planets.index)

final class PlanetController {
    let mysql: MySQLDatabase.ConnectionPool
    init(_ mysql: MySQLDatabase.ConnectionPool) {
        self.mysql = mysql
    }
    
    func index(_ req: Request) throws -> Future<[Planet]> {
        return mysql.withConnection { conn in
            return Planet.query(on: conn).all()
        }
    }
}
```

This has the advantage of improving performance a bit (~5%) since we don't need to store and release cached connection on the request. It's also a bit simpler to reason about.

We could also expand Fluent to accept connection pools in the `query(on:)` method to make the API even simpler.

```swift
Planet.query(on: mysql).all()
```

### Minor Update

This change could be made in a minor update to Vapor (perhaps 3.1). It would be backward compatible while at the same time allowing us to test out this idea of thread-safe controllers.

If it ends up seeming like a good option, we could slowly deprecate methods that require the `Request` as a container and move fully toward thread-safe controllers in a future major release.

**Comment by tanner0101** [comment]
### Note on Dangling Futures

An interesting shortcoming of Fluent's connection pool APIs was brought up by @vzsg:

```swift
func index(_ req: Request) throws -> Future<View> {
    let models = SomeModel.query(on: req).all()

    guard someCondition else { throw SomeError(...) } // !!!

    return req.view().render("someView", ["models": models])
}
```

In this case, Vapor / Fluent are expecting that `SomeModel.query(on: req).all()` will complete asynchronously (either success or failure) before the route completes. But, because an error is being thrown synchronously, the route is going to complete before the query does.

This leads to undefined behavior in the database connection pool implementation, usually causing connections to be leaked. 

Another example of this would be a more obvious "dangling future":

```swift
router.get("work") { req -> String in
    _ = Todo.query(on: req).all().map { todos in
        print(todos)
    }
    return "done"
}
```

Again, the Vapor / Fluent expect the route to complete _after_ all database work is done. But, in this case, the route will complete before the query to Todos has run. This will result in undefined behavior, and could crash or leak connections.

While it's generally not recommended to leave "dangling futures", i.e., using `_ = `, Vapor / Fluent can and should handle this error better. I'm bringing this up here because the ideas in this thread would be a great solution to the problem. Take the following code using thread-safe controllers for example:

```swift
let db = try container.connectionPool(for: .sqlite)
router.get("work") { req -> String in
    _ = Todo.query(on: db).all().map { todos in
        print(todos)
    }
    return "done"
}
```

Here, each call to `query(on: )` will pull out a new connection from the pool and return it once the query is complete. Because this connection pool logic does not rely on request lifecycle, we are free to leave a dangling future here and return the response early. The connection will be returned to the pool naturally after the query is complete.

**Comment by mcdappdev** [comment]
So just to clarify - if we request a connection pool as it stands today instead of using a request, using the current version of Vapor, and pass it into a dangling future, it’ll be ok?

**Comment by tanner0101** [comment]
@mcdappdev yup. The problem with dangling futures stems from how `Request` caches connections to the database.

**Comment by mcdappdev** [comment]
Great! Thanks :)

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.

**Comment by tonyarnold** [comment]
This is unlikely to be addressed for Vapor 3, is it? 

I'm seeing quite a number of database connections not closing, and I think they're coming from situations like those described above. 

In terms of the example where an Error is thrown directly from the method, and not from within a future, is the answer to do something like:

```swift
return request.future().flatMap {
   throw MyError.errorrororor
}
```

**Comment by valeriomazzeo** [comment]
Moving from Vapor 3 to Vapor 4, how would the following translate? It looks like there's only one router available in the Application.

```swift
    services.register(Router.self) { container -> EngineRouter in

        let authMiddlewares: [Middleware] = [...]

        let router = EngineRouter.default()
        router.get(...
```

cc/ @tanner0101
