### ISSUE TITLE
Can't build project

### ISSUE THREAD

**Issue by ildar-gilfanov** [vapor/vapor#1712]
I was able to build my project, but now it fails with error. I created new template api project and it is not compiled too. I have tried to reinstall Vapor, update brew, update Xcode to latest version, update macOS, run xcode-select --install, but nothing helps.

Btw generated xcode project is compiled and works correctly.

### Steps to reproduce

1. Install Vapor
2. Create new template api project
3. Run `vapor build --verbose`

### Expected behavior

buld command finish successfully.

### Actual behavior

It fails with error:
https://gist.github.com/ildar-gilfanov/d96a9c4304603c22347c4f93ad84f2c4

### Environment

* Vapor Framework version: 3.0.1
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.5
* xcode-select -p: /Applications/Xcode.app/Contents/Developer

**Comment by vzsg** [comment]
What is the output of `which swift` and `swift -version`?
And do you have Xcode 9.4 installed at `/Application/Xcode.app`?

**Comment by ildar-gilfanov** [comment]
```
which swift
/usr/bin/swift
```

```
swift -version
Apple Swift version 4.1.2 (swiftlang-902.0.54 clang-902.0.39.2)
Target: x86_64-apple-darwin17.6.0
```

Yes. It is installed at `/Application/Xcode.app`

**Comment by vzsg** [comment]
Those outputs seem fine. I have never seen such a build failure before... But it seems to be trying to include headers in the build that should not be there – `/usr/local/include/v1` doesn't normally exist on macOS.

Have you installed libstdc++ manually in the past?

**Comment by ildar-gilfanov** [comment]
No. I don't remember installing this. There is my `~/.bash_profile`
```
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.fastlane/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```

It seems like my local problem. I asked my colleague to build my project and it was build successfully. So I think this issue could be closed as non related to Vapor if nobody has idea how to fix it.

**Comment by 0xTim** [comment]
Have you used macPorts before? I've had that completely screw up my builds before

**Comment by ildar-gilfanov** [comment]
@0xTim No. I don't have macPorts. And I don't remember using it before.
