### ISSUE TITLE
Codable default encoding/decoding strategy

### ISSUE THREAD

**Issue by avitruk** [vapor/vapor#1713]
### Expected behavior

In Swift 4.1 we can set encoding/decoding strategies on `JSONEncoder` and `JSONDecoder` in order to automatically convert coding keys between camelCase and snake_case.
It would be great to add some option to change default coding\encoding strategy. It can help create DB entities (during migrations), json for responses etc in snake_case with camelCased properties.

```swift
do {
       let encoder = JSONEncoder()
       encoder.keyEncodingStrategy = .convertToSnakeCase
       let encoded = try encoder.encode(<Codable>)
       print(String(decoding: encoded, as: UTF8.self))
} catch {
       print(error)
}

do {
       let decoder = JSONDecoder()
       decoder.keyDecodingStrategy = .convertFromSnakeCase
       let decoded = try decoder.decode(<Codable>, from: Data(jsonString.utf8))
       print(decoded)
} catch {
       print(error)
}
```

### Actual behavior

Currently, we need to create in the model CodingKeys enum to define properties naming style. 

### Environment

* Vapor Framework version: 3.0.4
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13.5 | Ubuntu 16.0.4

**Comment by 0xTim** [comment]
You can actually override this, though I can't remember how!

The main issue however is that key encoding strategies aren't implemented on Linux and crash at runtime, so it's pointless until 4.2

**Comment by avitruk** [comment]
Ah... So we need to wait a bit =)
But I believe that is a great small improvement for the future releases. Flexible configuration is a pleasant and important part of other web frameworks (e.g, laravel, etc.)

**Comment by vzsg** [comment]
A little correction for the above: unlike your everyday Foundation landmine, `keyEncodingStrategy` doesn't even compile on Linux, so you are told at build time that there's a problem, don't need to wait for it to crash at runtime.

**Comment by LoganWright** [comment]
@avitruk 

You can add this to your `configure.swift` file:

```swift
    var content = ContentConfig.default()
    let encoder = JSONEncoder()
    encoder.keyEncodingStrategy = .convertToSnakeCase
    let decoder = JSONDecoder()
    decoder.keyDecodingStrategy = .convertFromSnakeCase
    content.use(encoder: encoder, for: .json)
    content.use(decoder: decoder, for: .json)
    services.register(content)
```

Let us know if that doesn't work for some reason 👍

**Comment by natanrolnik** [comment]
What @loganwright suggested above compiles and works on Linux in Swift 5.0  👍 😃
