### ISSUE TITLE
request content Decoding help for JSON content

### ISSUE THREAD

**Issue by sankarsubramanian** [vapor/vapor#1714]
### Steps to reproduce

I am new to vapor. Please help me to resolve this issue.
With Vapor 3.0.0, I am trying to decode the below content. using struct  
`struct PollRequestData: Codable {
    var subscriptions : [String : [Dictionary<String, String>]]
}`

**JSON body:**
  `{
   "subscriptions":
   [
     {
       "subscriptionId":"Test",
       "callbackData":"Test",
       "expiresIn": "100",
       "notificationEvents":[
         {
          "sessionId":"Test",
          "type":"Test",
          "sessionStatus":"Test"
          } 
        ]
      }, 
      {
       "subscriptionId":"1111",
       "callbackData":"Test",
       "notificationEvents":[
         {
          "type":"Test",
          "percentLevel":50
          } 
        ]
       }
      ]
}`

But getting the error as **[ ERROR ] DecodingError.typeMismatch: Value of type 'Dictionary<String, Any>' required for key 'subscriptions'.**
If I use the struct as Any instead of string getting the compilation issue as "Type 'PollRequestData' does not conform to protocol 'Decodable'"
`struct PollRequestData: Codable {
    var subscriptions : [String : [Dictionary<String, Any>]]
}`

### Expected behavior

JSON needs to be decoded properly

### Environment

* Vapor Framework version: 3.0.0
* Vapor Toolbox version:
* OS version: 10.13.4

**Comment by sankarsubramanian** [comment]
Yes Tim you are correct. My JSON is having Int.
Is it possible to create content like struct PollRequestData: Codable { var subscriptions : [String : [Dictionary<String, Any>]] }

**Comment by vzsg** [comment]
No, Codable doesn't support that. You either need to come up with `struct`-s that map to your JSON input perfectly (probably with a bunch of optional fields), or you need to use JSONSerialization directly (like in the old days).

**Comment by LoganWright** [comment]
Closing this since it seems stale, reopen, or join us in discord to continue 😄
