### ISSUE TITLE
Replace Slack with Discord in the README

### ISSUE THREAD

**Issue by revolter** [vapor/vapor#1715]
This image:

![Vapor](https://user-images.githubusercontent.com/1342803/36581122-643e5298-1839-11e8-8927-522bdc3a7205.png)

says Slack instead of Discord.

**Comment by vzsg** [comment]
(Discord, actually)

**Comment by revolter** [comment]
Sorry, mixed them up.

**Comment by ArkadiuszBanas** [comment]
![vapor-header](https://user-images.githubusercontent.com/1742140/43008225-c0671b98-8c3a-11e8-8ded-2352b9e0f7b0.png)
Hi Guys. I've just prepared new header for you :)

**Comment by calebkleveter** [comment]
I might note that 'Discord server' would probably be more correct.

**Comment by joscdk** [comment]
@ArkadiuszBanas feel free to open a PR to change it :)

**Comment by ArkadiuszBanas** [comment]
@calebkleveter I guess you're right :)
![vapor-header](https://user-images.githubusercontent.com/1742140/43014701-5ad8f7de-8c4d-11e8-86d2-4db3d71581aa.png)
