### ISSUE TITLE
vapor update always prints out error message.

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1717]
vapor update returns an error

### Steps to reproduce

```bash
% vapor update
```
> Error: backgroundExecute(code: 128, error: "fatal: ambiguous argument \'origin/form...form\': unknown revision or path not in the working tree.\nUse \'--\' to separate paths from revisions, like this:\n\'git <command> [<revision>...] -- [<file>...]\'\n", output: "")

```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "dts",
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.1"),
	.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc.2"),
	.package(url: "https://github.com/vapor/leaf.git", from: "3.0.0-rc.2")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentPostgreSQL", "Vapor", "Leaf"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

### Environment

* Vapor Framework version: 3.0.3
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.4

**Comment by vzsg** [comment]
That error is printed due to a bug in the vapor toolbox. I don't remember the exact cause (something about git branches), but for now, the quick workaround is running `swift package update` and `swift package generate-xcodeproj` (if needed) instead.

**Comment by grosch** [comment]
Thanks, @vzsg

**Comment by siempay** [comment]
` vapor --version` 
`Vapor Toolbox: 3.1.7
Vapor Framework: 2.4.4`

**But still have that error**

`Error: backgroundExecute(code: 128, error: "fatal: ambiguous argument \'origin/vapor3...vapor3\': unknown revision or path not in the working tree.\nUse \'--\' to separate paths from revisions, like this:\n\'git <command> [<revision>...] -- [<file>...]\'\n", output: "")`

**Comment by 0xTim** [comment]
@siempay that doesn't look like the output from `swift package update` - what command did you run?

**Comment by LoganWright** [comment]
Closing this since it seems resolved and it's pretty stale. Reopen if this is still happening with latest tools 👍

**Comment by EricWVGG** [comment]
I have just encountered this problem. Has something to do with switching branches, where a file got renamed.

**Comment by RaghavMangrola** [comment]
I also ran into this issue on a brand new project on a branch I hadn't pushed to to my remote (origin). Just had to push the branch and I was good to go.

**Comment by JhonnyBillM** [comment]
It happened to me today.
Pushing the branch resolved the issue [ Thank you @RaghavMangrola ]
