### ISSUE TITLE
How to effectively ignore the id field returned from the MySQL query result ? 🤔🤔🤔

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1719]
![image](https://user-images.githubusercontent.com/16829428/41202103-1d1abcae-6cf7-11e8-833a-0ff5645e7751.png)

How to **ignore** table's **id** field in **MySQL** query result? 
I don't want to return the id for the user to see. However, my way of writing this is more than the three lines of code. 
It doesn't look like efficient code.

> English is not my native language; please excuse typing errors.

**Comment by grosch** [comment]
You would use the customSql, but it's not working properly right now.

https://github.com/vapor/fluent/issues/495

**Comment by Jinxiansen** [comment]
This feels rather troublesome...

**Comment by 0xTim** [comment]
You need a 'Public' representation of a user and return that instead
