### ISSUE TITLE
Unable to decode optional numbers

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1720]
When sending data from a Leaf POST call that has a bunch of *non-required* input fields, of type number, that fails to decode.

### Steps to reproduce

I have a struct like so on my vapor side.

```swift
    private struct OrderCreatePostData: Content, HasPoints {
        static var defaultMediaType = MediaType.urlEncodedForm

        var ud: Double?
        var dp: Double?
      
        var client: Client.ID
        var station: Station.ID
        var multiplier: Int
        var session: String
    }
```

and then I pass it data like so:

```bash
curl -i 'http://localhost:8080/orders/new' 
    -H 'Content-Type: application/x-www-form-urlencoded' 
    -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' 
    -H 'Accept-Encoding: gzip, deflate, br' 
    --data 'client=9&station=112&multiplier=1&month=May+2018&out=05%2F23%2F2018&session=asdfasdf&dp=2&ud=' 
    --compressed
```

It's received like so:

```swift
func newOrderSubmitViewHandler(_ req: Request) throws -> Future<Response> {
    return try req.content.decode(OrderCreatePostData.self).flatMap(to: Response.self) { data in
        ...
    }
}
```

### Expected behavior

`ud` should be set to `nil`

### Actual behavior

I get a 500 HTTP response:

```json
{"error":true,"reason":"Could not convert to `Double`: str(\"\")"}
```

### Environment

* Vapor Framework version: 3.0.4
* Vapor Toolbox version: 3.1.7
* OS version: mac 10.13.5

**Comment by LoganWright** [comment]
The issue here, is that instead of receiving `nil`, the system is receiving an empty string. The type system is pretty strict and going to enforce that. I think it will have to be structured differently to accommodate the uncertainty about what type will be received.

I had a similar issue w/ an api and made this struct that can perhaps help you if you can't control the quality of your JSON.

```swift
public struct StringOrInt: Content {
    public var string: String?
    public var int: Int?

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        string = try? container.decode(String.self)
        int = try? container.decode(Int.self)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        if let string = string {
            try container.encode(string)
        } else if let int = int {
            try container.encode(int)
        }
    }
}
```

from: https://github.com/LoganWright/penny-github/blob/master/Sources/PennyGitHub/Models/Repo.swift

**Comment by grosch** [comment]
That should work, thanks.
