### ISSUE TITLE
Vapor update stucks at swift-nio-ssl-support

### ISSUE THREAD

**Issue by atacengiz** [vapor/vapor#1721]
Hi,

I am trying to update my packages cause i added a few more package to Package.swift

`// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "GameZone",
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.3"),
		.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc-2.3"),
		.package(url: "https://github.com/Quick/Nimble.git", from: "6.0.0")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentPostgreSQL", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Nimble"])
    ]
)`

### Steps to reproduce

vapor update --verbose

### Expected behavior

It should update all of the frameworks.

### Actual behavior

It stucks at Updating https://github.com/apple/swift-nio-ssl-support.git, everytime i tried and waited more than 30 minute at this stage. I tried to delete build folder and tried again but it again stucked at this framework.

### Environment

* Vapor Framework version: 3.0.3
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.5
* Swift package manager: 4.1.0

**Comment by MartinLasek** [comment]
@atacengiz have you tried to change your dependency `.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc-2.3"),` to `.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "1.0.0-rc"),` ?

It doesn't look "right" with the hyphen `"1.0.0-rc-2.3"` if you want to have it from a specific version I am used to this syntax: `"1.0.0-rc.2.3"` but actually `"1.0.0-rc"` will pull in the latest *rc* version. 😊

**Comment by atacengiz** [comment]
@MartinLasek it worked :) thanks a lot, i thought it would have given me an error or something if the version does not exist...

**Comment by calebkleveter** [comment]
@atacengiz We all wish that happened, but SPM doesn't support that yet 😞.
