### ISSUE TITLE
Unable to proxy requests when running on Linux

### ISSUE THREAD

**Issue by pdamonkey** [vapor/vapor#1723]
I have a vapor app deployed in a Docker container hosted on Cloud Foundry. Any instance of the app has no access to make external network calls and can only do so via a proxy. There is no exception of this, all external traffic must go via a proxy service due to our network security requirements.

### Steps to reproduce

I created a route as per the code below:

```
router.get("test") { req -> Future<String> in
    let sessionConfiguration = URLSessionConfiguration.default
    sessionConfiguration.connectionProxyDictionary = [
        "HTTPEnable": true,
        "HTTPProxy": "192.168.0.5",
        "HTTPPort": 8888,
        "HTTPSEnable": true,
        "HTTPSProxy": "192.168.0.5",
        "HTTPSPort": 8888,
    ]
    
    let session = URLSession(configuration: sessionConfiguration)
    let client = FoundationClient(session, on: req)
    let url = "https://google.com"
    
    var headers: HTTPHeaders = [:]
    headers.add(name: "Cache-Control", value: "no-cache")
    headers.add(name: "Proxy-Authorization", value: "Basic {AUTH_KEY}")
    
    let result = client.get(url, headers: headers)
    return result.map(to: String.self) { response in
        return "\(response.http.body)"
    }
}
```

I had to use hard-coded strings for the keys in the `connectionProxyDictionary` as linux doesn't appear to support the standard constants such as [kCFStreamPropertyHTTPProxyHost](https://forums.developer.apple.com/thread/71411)

The host used as the value for `HTTPProxy` & `HTTPSProxy` is my machine's IP address and using port `8888` to point to my Charles proxy. Doing so allows me to see if the request to `https://google.com` is being proxied through my machine correctly.

### Expected behaviour

After making the request to `https://google.com`, by navigating to the `test` route, I should see it proxied through Charles and see a record of the request.

### Actual behaviour

When building and running the vapor app via Xcode on macOS the request is correctly proxied through Charles. When running the app in a Docker container that is based from a Ubuntu image the request is no longer recorded within Charles. 

Running `curl` with the proxy `-x http://192.168.0.5:8888` option from within the docker container allows for requests to be seen in Charles. This shows that it is not a docker networking issue.

```
curl -x http://192.168.0.5:8888 https://google.com
```

With no code changes proxying works on macOS but not when on Linux.

From looking into [swift-corelibs-foundation](https://github.com/apple/swift-corelibs-foundation) I can see that when a session is [configured](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/URLSession/libcurl/MultiHandle.swift#L59) that the `connectionProxyDictionary` values aren't used although some ground work has been done to allow for [CURLoptions](https://github.com/apple/swift-corelibs-foundation/blob/master/CoreFoundation/URL.subproj/CFURLSessionInterface.h#L169) related to proxying to be set.

I am happy to continue to add support for proxying to `swift-corelibs-foundation` however it would be good for some guidance to ensure that I am looking in the right direction.

### Environment

* Vapor Framework version: 3.0.3
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.4

**Comment by matthewgallaghersky** [comment]
Thanks to help from Tanner I have found a workaround for the above issue for now.  

### Workaround

Here's a great link to some documentation form the **nodes-vapor** team: [how to use a proxy](https://github.com/nodes-vapor/readme/blob/master/Documentation/how-to-use-a-proxy.md#with-tls-using-https)

Here's the code which is working as expected:

```swift
    let sessionConfiguration = URLSessionConfiguration.default
    var headers: HTTPHeaders = [:]
    
    #if os(macOS)
        headers.add(name: "Proxy-Authorization", value: "Basic 838fa8agjasdl=")
        
        sessionConfiguration.connectionProxyDictionary = [
            "HTTPEnable": true,
            "HTTPPort": 8888,
            "HTTPProxy": "192.168.0.5",
            "HTTPSEnable": true, 
            "HTTPSPort": 8888,
            "HTTPSProxy": "192.168.0.5"
        ]
    #else
        setenv("HTTP_PROXY", "http://192.168.0.5:8888", 1)
        setenv("HTTPS_PROXY", "http://192.168.0.5:8888", 1)
    #endif
    
    let session = URLSession(configuration: sessionConfiguration) 
    let client = FoundationClient(session, on: req)
    let result = client.get(url, headers: headers)
```

I found I had to add the `Proxy-Authorization` value on macOS, but when using the workaround for Linux this didn't work so I had to put the username/password into the URL as shown below.  

When using this on my actual proxy which had authentication I had to update the `setenv` call to the following style with username and password included:
`setenv("HTTP_PROXY", "http://username:password@192.168.0.5:8888", 1)`

There may be better ways of putting these settings into your environment, especially if you need to use authentication.  On my actual implementation I'm using values already set in my environment to handle this so no sensitive data is included in my code.  

I will be raising this issue on the Swift Forums to see if we can actually fix this within Foundation on Linux, but at least for now there is a workaround for it.

**Comment by LoganWright** [comment]
This looks like it should solve the issue you're experiencing, if for some reason you find that you're still having trouble, go ahead and reopen the issue!

And we're always available in Discord to help out at vapor.team
