### ISSUE TITLE
Compilation error for Swift 4.1

### ISSUE THREAD

**Issue by GildedHonour** [vapor/vapor#1727]
I was doing this:

        git clone https://github.com/vapor/toolbox vapor-toolbox
        cd vapor-toolbox
        swift build -c release

And:

        [................]

        Compile Swift Module 'Console' (36 sources)
        Compile Swift Module 'Crypto' (13 sources)
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Cipher/Cipher.swift:71:34: error: use of undeclared type 'EVP_CIPHER_CTX'
                    UnsafeMutablePointer<EVP_CIPHER_CTX>,
                                         ^~~~~~~~~~~~~~
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Cipher/Cipher.swift:77:34: error: use of undeclared type 'EVP_CIPHER_CTX'
                    UnsafeMutablePointer<EVP_CIPHER_CTX>,
                                         ^~~~~~~~~~~~~~
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Cipher/Cipher.swift:84:34: error: use of undeclared type 'EVP_CIPHER_CTX'
                    UnsafeMutablePointer<EVP_CIPHER_CTX>,
                                         ^~~~~~~~~~~~~~
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Cipher/Cipher+Method.swift:144:35: error: use of undeclared type 'EVP_CIPHER'
            public var evp: UnsafePointer<EVP_CIPHER> {
                                          ^~~~~~~~~~
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Cipher/Cipher.swift:89:19: error: use of unresolved identifier 'EVP_CIPHER_CTX'
                var ctx = EVP_CIPHER_CTX()
                          ^~~~~~~~~~~~~~
        CTLS.EVP_CIPHER_CTX_iv:1:13: note: did you mean 'EVP_CIPHER_CTX_iv'?
        public func EVP_CIPHER_CTX_iv(_ ctx: OpaquePointer!) -> UnsafePointer<UInt8>!
                    ^
        CTLS.EVP_CIPHER_nid:1:13: note: did you mean 'EVP_CIPHER_nid'?
        public func EVP_CIPHER_nid(_ cipher: OpaquePointer!) -> Int32
                    ^
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Cipher/Cipher.swift:135:13: error: use of unresolved identifier 'EVP_CIPHER_CTX_cleanup'
                    EVP_CIPHER_CTX_cleanup(&ctx)
                    ^~~~~~~~~~~~~~~~~~~~~~
        CTLS.EVP_CIPHER_CTX_num:1:13: note: did you mean 'EVP_CIPHER_CTX_num'?
        public func EVP_CIPHER_CTX_num(_ ctx: OpaquePointer!) -> Int32
                    ^
        CTLS.EVP_CIPHER_CTX_set_num:1:13: note: did you mean 'EVP_CIPHER_CTX_set_num'?
        public func EVP_CIPHER_CTX_set_num(_ ctx: OpaquePointer!, _ num: Int32)
                    ^
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/HMAC/HMAC.swift:25:23: error: use of unresolved identifier 'HMAC_CTX'
                var context = HMAC_CTX()
                              ^~~~~~~~
        CTLS.MD4_CTX:1:18: note: did you mean 'MD4_CTX'?
        public typealias MD4_CTX = MD4state_st
                         ^
        CTLS.MD5_CTX:1:18: note: did you mean 'MD5_CTX'?
        public typealias MD5_CTX = MD5state_st
                         ^
        CTLS.SHA_CTX:1:18: note: did you mean 'SHA_CTX'?
        public typealias SHA_CTX = SHAstate_st
                         ^
        CTLS.HMAC_CTX_new:1:13: note: did you mean 'HMAC_CTX_new'?
        public func HMAC_CTX_new() -> OpaquePointer!
                    ^
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/HMAC/HMAC.swift:26:9: error: use of unresolved identifier 'HMAC_CTX_init'
                HMAC_CTX_init(&context)
                ^~~~~~~~~~~~~
        CTLS.HMAC_CTX_new:1:13: note: did you mean 'HMAC_CTX_new'?
        public func HMAC_CTX_new() -> OpaquePointer!
                    ^
        CTLS.HMAC_CTX_copy:1:13: note: did you mean 'HMAC_CTX_copy'?
        public func HMAC_CTX_copy(_ dctx: OpaquePointer!, _ sctx: OpaquePointer!) -> Int32
                    ^
        CTLS.HMAC_CTX_free:1:13: note: did you mean 'HMAC_CTX_free'?
        public func HMAC_CTX_free(_ ctx: OpaquePointer!)
                    ^
        CTLS.HMAC_CTX_reset:1:13: note: did you mean 'HMAC_CTX_reset'?
        public func HMAC_CTX_reset(_ ctx: OpaquePointer!) -> Int32
                    ^
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/HMAC/HMAC+Method.swift:23:28: error: use of undeclared type 'EVP_MD'
            var evp: UnsafePointer<EVP_MD> {
                                   ^~~~~~
        /home/alex/tmp/vapor_swift/vapor-toolbox/.build/checkouts/crypto.git--5257985161603715880/Sources/Crypto/Random/PseudoRandom.swift:9:15: warning: 'RAND_pseudo_bytes' is deprecated
                guard RAND_pseudo_bytes(&random, Int32(count)) == 1 else {
                      ^
        error: terminated(1): /usr/bin/swift-build-tool -f /home/alex/tmp/vapor_swift/vapor-toolbox/.build/release.yaml main output:
            

And:

        $ swift -version
        Swift version 4.1 (swift-4.1-RELEASE)
        Target: x86_64-unknown-linux-gnu

**Comment by vzsg** [comment]
You need to have libssl-dev 1.0.2 installed, Vapor projects (and in general, most Swift projects) are not compatible with the breaking changes of 1.1.0.

**Comment by GildedHonour** [comment]
yes, it's a part of Arch openssl
I have both now, the 1.0x and 1.1
The later is used by default. Does vapor has a compilation flag for specifiying the path to openssl?

**Comment by 0xTim** [comment]
I believe it uses pkgconfig to specify this but I'm unsure how to specify it. You can manually provide the header locations to `swift build` as well

**Comment by GildedHonour** [comment]
@0xTim 

>You can manually provide the header locations to swift build as well

How?

**Comment by vzsg** [comment]
Probably along the lines of:

```bash
# swift build -Xswiftc -I/usr/lib/openssl-1.0/include -Xlinker -L/usr/lib/openssl-1.0/lib
```

**Comment by GildedHonour** [comment]
I don't have "include"

```
$ ls -al /usr/lib/openssl-1.0
total 272
drwxr-xr-x   4 root root   4096 jul  1 02:00 .
drwxr-xr-x 251 root root 262144 jul  1 02:00 ..
drwxr-xr-x   2 root root   4096 jul  1 02:00 engines
lrwxrwxrwx   1 root root     21 mar 31 23:45 libcrypto.so -> ../libcrypto.so.1.0.0
lrwxrwxrwx   1 root root     18 mar 31 23:45 libssl.so -> ../libssl.so.1.0.0
drwxr-xr-x   2 root root   4096 jul  1 02:00 pkgconfig
```

**Comment by vzsg** [comment]
Yeah, now I see from the PKGBUILD file where things are installed 🤷‍♂️ .

Try this instead (no guarantees it will work though):

```bash
$ swift build -Xswiftc -I/usr/include/openssl-1.0 -Xlinker -L/usr/lib/openssl-1.0
```

If that doesn't work, maybe you should just use Docker or Ubuntu.

**Comment by lokimx88** [comment]
maybe this will work 
`$ swift build   -Xlinker -lssl  -Xlinker -lcrypto `
but I have new problems
`undefined reference to 'deflateBound'`
`error: undefined reference to 'deflateEnd'`
