### ISSUE TITLE
Vapor Won't Build Or Update

### ISSUE THREAD

**Issue by Kcvavkr** [vapor/vapor#1728]
Vapor toolbox won't build or update project (never stops, even left it overnight). Further, Xcode also refuses to build that project with a compiler error in the products. 

### Steps to reproduce

build or update project

### Actual behavior

update/build goes on forever

### Environment

* Vapor Framework version: 3.0.4
* Vapor Toolbox version: 3.1.7
* OS version: MacOS 10.13.5

**Comment by vzsg** [comment]
There are two possible causes for this issue:
1) ongoing network issues on your side (unlikely);
2) invalid or conflicting dependency versions in Package.swift (most likely).

Please share your Package.swift, or at least the `dependencies` array.

**Comment by Kcvavkr** [comment]
hey, thanks for the quick response. 
I thought that might be the issue, and messed around with it a bit to no avail. I have attached both versions, the older one without messing around and the new one. github won't let me attach .swift files so i'm just pasting the text

--------------earlier file--------------------------------
// swift-tools-version:4.1

import PackageDescription

let package = Package(
    name: "Final",
    products: [
        .library(name: "App", targets: ["App"]),
        .executable(name: "Run", targets: ["Run"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        .package(url: "https://github.com/vapor/fluent-provider.git", from: "3.0.0-rc.2"),
        .package(url: "https://github.com/vapor/leaf-provider.git", from: "3.0.0-rc.2"),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: ["Vapor", "FluentProvider", "LeafProvider"],
            exclude: ["Config", "Public", "Resources"]
        ),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
    ]
)

-------------------second file(after messing around) ---------------------------
// swift-tools-version:4.1

import PackageDescription

let package = Package(
    name: "Final",
    products: [
        .library(name: "App", targets: ["App"]),
        .executable(name: "Run", targets: ["Run"])
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.4"),
        .package(url: "https://github.com/vapor/fluent-provider.git", from: "1.3.0"),
        .package(url: "https://github.com/vapor/leaf-provider.git", from: "1.1.0"),
		//this code was updated on the 16th of june 2018.
    ],
    targets: [
        .target(
            name: "App",
            dependencies: ["Vapor", "FluentProvider", "LeafProvider"],
            exclude: ["Config", "Public", "Resources"]
        ),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "Testing"])
    ]
)

**Comment by Kcvavkr** [comment]
hey, thanks. so, I changed the versions of my leaf-provider and my fluent-provider to "3.0.0-rc" in the Package.swift file, but it still won't update. am I doing something wrong here?

**Comment by grundoon** [comment]
Okay, so if you want to work with the Vapor 2 branch, you would use the 2nd version you posted above, but just replace the vapor.git version with `.upToNextMajor(from: "2.4.0")`.

The easiest way right this moment to generate a new project, with the correct .package dependencies, would be to use Vapor Toolbox

for Vapor 3: `vapor new Final`
for Vapor 2: `vapor new Final --web`

You can also examine the differences between the 2 by inspecting the vapor/api-template (version 3) and vapor/web-template (version 2, because it has not yet been updated) repositories.

**Comment by Kcvavkr** [comment]
hey, so I just changed the Vapor version to 2.4.0, and it works fine. Thanks for the help. Builds and Updates fine. though, Xcode still shows errors. I usually build from the terminal anyway, but would that be related?

**Comment by Kcvavkr** [comment]
update: I just cleaned the Xcode project and deleted derived data from the project and that fixed the Xcode errors too. thanks a lot guys!
