### ISSUE TITLE
Please provide a few CRUD examples using raw queries (not Fluent) in the Docs

### ISSUE THREAD

**Issue by kliron** [vapor/vapor#1729]
Hi,

I'm trying to reproduce a simple parameterized query [from the docs ](https://docs.vapor.codes/3.0/postgresql/core/).

This simple query fails in two ways:

`let users = req.withPooledConnection(to: .psql) { conn in
    return try conn.query("SELECT *  users WHERE name = $1;", ["Vapor"])
}`

1. The compiler needs the type of conn specified in the closure `(conn: PostgreSQL.Connection)`
2. The `query` fails to compile with `Missing argument label 'resultFormat:' in call`.  I cannot find any overloads of the `query` function that take parameters, I guess there is some totally different call to prepare a statement and pass parameters. 

Given the existing documentation I have no idea how to pass parameters to a raw query which makes it impossible to use Vapor for anything useful at this point. Which makes me sad.

**Comment by kliron** [comment]
Okay, so this query works:

```
conn.query(.raw(query: "SELECT * users WHERE name = $1;", 
                             binds:  ["Vapor"convertToPostgreSQLData()]))
```

Which I found digging in the Test folder of [vapor/postgresql](https://github.com/vapor/postgresql/blob/master/Tests/PostgreSQLTests/PostgreSQLConnectionTests.swift). So I am guessing this is the right way to do this.

**Comment by rafiki270** [comment]
https://docs.vapor.codes/3.0/postgresql/getting-started/
https://docs.vapor.codes/3.0/mysql/getting-started/
https://docs.vapor.codes/3.0/sqlite/getting-started/
