### ISSUE TITLE
Build failed: Because of Core 3.3.0/Async/Future+Flatten.swift 

### ISSUE THREAD

**Issue by dushandz** [vapor/vapor#1731]
i followed by guide on Vapor's website, after i run `vapor xcode` to create Xcode Project, open xcodeproject selected run scheme.
The Xcode tell me Build Failed in Core 3.3.0/Async/Future+Flatten.swift file.

```Swift
in line 50
        //Xcode tell me  Miss argument label:'file' 
        let promise = worker.eventLoop.newPromise([Element.Expectation].self) 
       
in line 53
        // Ambiguous reference to member 'init'
        var results: [Element.Expectation?] = .init(repeating: nil, count: count)
```

### Environment

* Vapor Framework version:3.0.4
* Vapor Toolbox version:3.1.7
* OS version:macOS high sierra 10.13.4 

Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
Xcode Version: Version 9.2 (9C40b)

**Comment by vzsg** [comment]
Vapor 3 requires Swift 4.1, so your Xcode 9.2 version is too old.
Try upgrading to 9.4.1 (technically at least 9.3), such build errors should go away.

Please reopen this issue if that doesn't fix it.
