### ISSUE TITLE
PlaintextEncoder has a thread race condition 

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#1733]
I'm still working on a repro case for this, but I deduced with @pedantix and Cory that something super funky is happening. They think it may be related to PlaintextEncoder being registered/used as a singleton. It's causing my RPS on a normal Leaf route to sit at around 50rps. 

I will add the repro here when I have it

**Comment by mcdappdev** [comment]
Repro here: https://github.com/mcdappdev/leaf-thread-repro/
Commenting out this section fixes the bug: https://github.com/mcdappdev/leaf-thread-repro/blob/master/Sources/App/configure.swift#L24

You can reproduce by:

1. running in release mode 
2. Enabling TSAM
3. Running `wrk -t 1 -c 32 -d 30s http://localhost:8080`
4. Wait for the TSAM crash in `PlaintextEncoder.swift`

**Comment by mcdappdev** [comment]
This was fixed be registering a custom ContentConfig lazily.

**Comment by vi4m** [comment]
I think came aross the same issue in PlaintextEncoder.swift, any idea how you've fixed that? @mcdappdev
