### ISSUE TITLE
FileMiddleware does not process symlinks correctly

### ISSUE THREAD

**Issue by joeblau** [vapor/vapor#1735]
When trying to load a text file from the Public directory any file that is symbolically linked doesn't render by default.  `FileMiddleware` will only render the first 12 characters of the file.

### Steps to reproduce

1.  In your vapor project create a dummy file in the `Public/` directory called `test.md`
2. Add this code to the file
```
## Installation instructions

hello world test

test test
```
3. Create a symbolic link to the `test.md` file
```
ln -s test.md testsym.md
```
4. Visit visit each file on your vapor server.
http://localhost:8080/test.md (Renders correctly)
http://localhost:8080/testsym.md (Only renders first 12 characters)

### Expected behavior

Symlinks should render exactly like the actual file that is linked. (This feature worked in Vapor 1.5)

### Actual behavior

Symlinked text documents are truncated to only show the first 12 characters

### Environment

* Vapor Framework version: 3.0.0
* Vapor Toolbox version: 3.1.7
* OS version: MacOS 10.14 Beta (18A314h)

**Comment by LoganWright** [comment]
@JamieEdge would you mind submitting that as a pull request so we can properly review it and work through it 👍 

Thanks for participating, we always love to see code from the community 🙌

**Comment by goranche** [comment]
🙄 I really need to start searching issues before starting to write my own 😅
just "lost" an hour on this issue myself (hard links obviously work, since they are the right size)

**Comment by tanner0101** [comment]
Tracking here #2281
