### ISSUE TITLE
Extend Vapor `EventLoop`s with `ThreadSpecificVariable` dictionary

### ISSUE THREAD

**Issue by grundoon** [vapor/vapor#1739]
Filing for discussion.

Motivation is primarily to allow a standard and straightforward method of creating `ThreadSpecificVariable`s for use on `app.eventLoop` (rather than have to modify each app separately).

For example, scheduling a repeating task via the main eventLoop often uses a pattern such as

    public func boot(_ app: Application) throws {
        runRepeatedTask(app)
    }

    func runRepeatedTask(_ app: Application) {
        _ = app.eventLoop.scheduleTask(in: .minutes(5)) { () -> Void in
            _ = app.withNewConnection(to: .psql) { db -> Future<Void> in
                // perform query(on: db) here
            }
            runRepeatedTask(app)
        }
    }

Which, while simple, encourages discarding the `Scheduled<T>` result because there's no obvious place to store it without modifying the stock Vapor Application itself (or pushing that struct into persistent storage, ick). Without storage, cancelling the task requires additional logic to determine whether the recursion should be executed, and regardless will only take effect *after* the current scheduled task has completed, at some future `(in:)` point.

Adding a `ThreadSpecificVariable` of type `Dictionary<String, Any> = [:]` (ob bikeshedding: say, named `userDict` here) would allow for scenarios such as

    func runRepeatedTask(_ app: Application) {
        app.eventLoop.userDict["purgeOldTokens"]: Scheduled = app.eventLoop.scheduleTask(in: .minutes(60)) { () -> Void in
            _ = app.withNewConnection(to: psql) { db -> Future<Void> in
                // perform query(on: db) here
            }
            runRepeatedTask(app)
        }
    }

    // elsewhere
    if let purge = app.eventLoop.userDict["purgeOldTokens"] {
        purge.cancel()
        app.eventLoop.userDict["purgeOldTokens"] = nil
    }

Other considerations:
* This would effectively provide a mechanism for global variables for cases where using a database is either overkill or inefficient (I honestly don't know if this is a good thing, or opening a can of worms rife for abuse).
* Extending this to all `EventLoop`s (the pool, not just just `app.eventLoop`) would facilitate moving such things as the `RFC1123` date header cache out of the responder chain, to a more efficient home.

**Comment by tanner0101** [comment]
What about just a normal `userInfo` style dictionary? The `app` is only intended to be used on _its_ event loop (`app.eventLoop`). So there shouldn't be a need to make the dictionary thread-safe. 

Besides that small thing, I like this idea a lot 👍

**Comment by MrLotU** [comment]
Think we should close this in favor of #1822

**Comment by grundoon** [comment]
Part of the original thinking here was that the RFC1123 date for the header was being unnecessarily potentially recalculated on every Response, and could instead be cached upstream on the event loop itself. I don't know that #1822 addresses this type of use case.

**Comment by tanner0101** [comment]
On master branch, the `Date` header is now calculated once per event loop using a scheduled task. Each response now just reads whatever the current value is: https://github.com/vapor/http/blob/master/Sources/HTTPKit/Utilities/RFC1123.swift#L70

**Comment by grundoon** [comment]
Veering off to the side for a moment, should that `scheduleRepeatedTask` not have a finer-grained `initialDelay` value in order to closely align it with an actual second flip-over boundary?

**Comment by tanner0101** [comment]
That would be a nice feature to add 👍

**Comment by grundoon** [comment]
Sorry, don't have 5.0 in this box's toolchain so can't really play today, but are you good with something like

```swift
    let fracSeconds = 1.0 - Date().timeIntervalSince1970.truncatingRemainder(dividingBy: 1)
    let msToNextSecond = Int(fracSeconds * 1000)
    eventLoop.scheduleRepeatedTask(initialDelay: .milliseconds(msToNextSecond), delay: .seconds(1)) { task in
        new.updateTimestamp()
    }
```
or should we be looking more along the lines of using `clock_gettime`?

**Comment by tanner0101** [comment]
@grundoon yeah that looks good to me. Are you gonna submit a PR?

**Comment by grundoon** [comment]
Well, if _this_ would ever finish I could maybe get to actually testing... 🤣 
```
grundoon:http grundoon$ swift --version
Apple Swift version 5.0 (swiftlang-1001.0.60.3 clang-1001.0.37.8)
Target: x86_64-apple-darwin18.2.0
ABI version: 0.7
grundoon:http grundoon$ swift package update
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/tanner0101/swift-nio-ssl.git
█
```

**Comment by tanner0101** [comment]
Track here: https://github.com/vapor/async-kit/issues/8
