### ISSUE TITLE
"swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib" in Jenkins, it was fail, error log was ---- Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by mingabc** [vapor/vapor#1740]
### Steps to reproduce
"swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib" in Jenkins, it was fail, error log was ----
Undefined symbols for architecture x86_64:
"_ASN1_STRING_data", referenced from:
_CNIOOpenSSL_ASN1_STRING_get0_data in SSLCertificate.swift.o
"_ASN1_STRING_length", referenced from:
__T010NIOOpenSSL22SubjectAltNameSequenceC4nextAA18OpenSSLCertificateC011AlternativeE0OSgyF in SSLCertificate.swift.o
"_ASN1_STRING_to_UTF8", referenced from:
__T010NIOOpenSSL18OpenSSLCertificateC10commonNameSays5UInt8VGSgyF in SSLCertificate.swift.o
"_BIO_ctrl_pending", referenced from:
__T010NIOOpenSSL13SSLConnectionC17getDataForNetwork3NIO10ByteBufferVSgAE0iJ9AllocatorV9allocator_tF in SSLConnection.swift.o
"_BIO_free", referenced from:
__T06Crypto7CRSAKeyC4makeAcA10RSAKeyTypeO4type_10Foundation4DataV4fromSb4x509tKFZ6$deferL_yyF in RSAKey.swift.o

but i run the same command in xcode and terminal was success

### Environment

* Vapor Framework version: Vapor 3.0
* Vapor Toolbox version: 3.1.7
* OS version: macOS High Sierra 10.13.4

**Comment by 0xTim** [comment]
@mingabc what version of OpenSSL do you have installed on your Jenkins nodes?

**Comment by mingabc** [comment]
openssl version 1.0.2o_2

**Comment by 0xTim** [comment]
If you run the command on the build node manually do you get the same output?

**Comment by LoganWright** [comment]
Hmmm, are you using the toolbox? Is there something that fails if you just call `vapor build`? You shouldn't need the additional calls to swiftc etc. here. 

If you're still seeing failing issues w/ `vapor build`, let us know and reopen the issue 😄 

As always, there's lots of help available in discord: vapor.team
