### ISSUE TITLE
Type PathComponentsRepresentable does not conform to ExpressibleByStringLiteral

### ISSUE THREAD

**Issue by jonblatho** [vapor/vapor#1741]
Adding a route to the router breaks for me any time I add any code other than a `return` line in the code block, with the error:

> Type 'PathComponentsRepresentable' does not conform to protocol ‘ExpressibleByStringLiteral'

To test this and make sure I was (hopefully) doing nothing wrong, I copied this example straight out of inline documentation for Vapor and attempted to compile only to receive the same error:

```swift
router.get("users", Int.parameter) { req in
    let id = try req.parameters.next(Int.self)
    return "User #\(id)"
}
```

If I change the route to 
```swift
router.get("users", Int.parameter) { req in
    return try "User #\(req.parameters.next(Int.self))"
}
```
it compiles again.

### Steps to reproduce

1. Create a new Vapor API.
2. Copy the first code block above into the auto-generated App/routes.swift file.
3. Attempt to compile.

### Expected behavior

The code should compile successfully regardless of whether there is additional code before the `return` line.

### Actual behavior

The project fails to compile with the following error:

> Type 'PathComponentsRepresentable' does not conform to protocol ‘ExpressibleByStringLiteral'

### Environment

* Vapor Framework version: 3.0.4
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13.5

**Comment by 0xTim** [comment]
@jonblatho this is an issue with the Swift compiler inferring the returning type for complex closures. Unfortunately there's not a lot Vapor can do about it!

The workaround is to specify the return type:

```swift
router.get("users", Int.parameter) { req -> String in
    let id = try req.parameters.next(Int.self)
    return "User #\(id)"
}
```

**Comment by jonblatho** [comment]
That’ll work for now but I’d love to see if there’s not _some_ way Vapor could make it a little more elegant (or at least indicate this solution in the docs) at some point in the future. Thanks Tim!

**Comment by 0xTim** [comment]
Unfortunately due to the genetics there’s not much Vapor can do to help the compiler. The best way around it is to extract out the closure to a separate function like so https://github.com/raywenderlich/vapor-til/blob/master/Sources/App/Controllers/AcronymsController.swift#L57
