### ISSUE TITLE
Fatal error: Error raised at top level: bind(descriptor:ptr:bytes:) failed: Cannot assign requested address (errno: 99) : file /home/buildnode/jenkins/workspace/oss-swift-4.1-package-linux-ubuntu-16_04/swift/stdlib/public/core/ErrorType.swift, line 191

### ISSUE THREAD

**Issue by winterzou** [vapor/vapor#1742]
when I run my code on ubuntn ,an error was thrown
configure.swift
```
 /// Register custom MySQL Config
    let mysqlConfig = MySQLDatabaseConfig(hostname: "localhost", port: 3306, username: "root", password: "q123456", database: "appmanager_sql")
    services.register(mysqlConfig)
    
    var z = NIOServerConfig.default()
    z.port = 8080
    services.register(z)
```
### Environment

* Vapor Framework version: 3.0.5
* Vapor Toolbox version:
Ubuntu 16.4

**Comment by 0xTim** [comment]
@winterzou are you running anything else on that port?

**Comment by yoimhere** [comment]
I have the same problem...do you fix it?

**Comment by Artemm208** [comment]
I have the same problem((

**Comment by winterzou** [comment]
> I have the same problem((

Follow the error message to find the wrong code. Some c apis can run on xcode, but errors can be reported in plain swift
