### ISSUE TITLE
CRUD controller

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1743]
As an enhancement request...I think we should have the below controller defined in the packages, but I'm not sure "where" it would go so I didn't submit a pull request.  

The API controllers are lots of boilerplate, and this gets rid of it.  You'd end up using it like so for your entire controller:

```swift
final class OrderController : CrudController<Order, OrderCreatePostData, OrderUpdateData> {
    override func createModel(from data: OrderCreatePostData) throws -> Order {
        return Order(stationID: data.station, name: data.session)
    }

    override func update(model: Order, using data: OrderUpdateData) throws {
        model.name = data.name
        model.stationMultiplier = data.multiplier
    }
}
```

If you wanted more than just the standard 5 routes, then you can just grab the attached route handler and add more:

```swift
    override func boot(router: Router) throws {
        try super.boot(router: router)

        routerGroup.post(Order.parameter, "work", use: storeWork)
    }
```

And if you want authentication, you just set `routerGroup` before calling super:

```swift
override func boot(router: Router) throws {
    let routes = router.grouped("api", "client")
    let tokenAuthMiddleware = Producer.tokenAuthMiddleware()
    let guardAuthMiddleware = Producer.guardAuthMiddleware()

    routerGroup = routes.grouped(tokenAuthMiddleware, guardAuthMiddleware)
    super.boot(router: router)
}
```

All that via this one little file:

```swift
import Vapor
import Fluent

open class CrudController<T, C, U>: RouteCollection where T: Content & Parameter & Model, C: Content, U: Content {
    public var mediaType = MediaType.json
    public var routerGroup: Router!
    
    open func boot(router: Router) throws {
        if routerGroup == nil {
            routerGroup = router.grouped("api", String(describing: T.self).lowercased())
        }
        
        routerGroup.get(use: indexHandler)
        routerGroup.get(T.parameter, use: getHandler)
        routerGroup.delete(T.parameter, use: deleteHandler)
        routerGroup.post(C.self, use: createHandler)
        routerGroup.patch(T.parameter, use: updateHandler)
    }
    
    open func indexHandler(_ req: Request) throws -> Future<[T]> {
        return T.query(on: req).all()
    }
    
    open func getHandler(_ req: Request) throws -> Future<T> {
        return try req.parameters.next(T.self) as! Future<T>
    }
    
    open func createHandler(_ req: Request, data: C) throws -> Future<Response> {
        let modelObject = try createModel(from: data)
        
        return modelObject.create(on: req).map { [weak self] obj in
            guard let `self` = self else {
                throw Abort(.internalServerError)
            }
            
            let id = try obj.requireID()
            
            let location = "\(req.http.url.absoluteString)/\(id)"
            let headers = HTTPHeaders([("Location", location)])
            let response = req.makeResponse(http: HTTPResponse(status: .created, headers: headers))
            try response.content.encode(obj, as: self.mediaType)
            
            return response
        }
    }
    
    open func updateHandler(_ req: Request) throws -> Future<T> {
        let param = try req.parameters.next(T.self) as! Future<T>
        let data = try U.decode(from: req)
        
        return flatMap(to: T.self, param, data) { [weak self] old, new in
            guard let `self` = self else { throw Abort(.internalServerError) }
            try self.update(model: old, using: new)
            return old.save(on: req)
        }
    }
    
    open func deleteHandler(_ req: Request) throws -> Future<HTTPStatus> {
        let param = try req.parameters.next(T.self) as! Future<T>
        return param.flatMap { model in
            return model.delete(on: req).transform(to: .noContent)
        }
    }
    
    open func createModel(from data: C) throws -> T {
        throw Abort(.internalServerError)
    }
    
    open func update(model: T, using data: U) throws {
        throw Abort(.internalServerError)
    }
}
```

**Comment by jonblatho** [comment]
I’m not sold on this, mostly because each project’s needs wind up varying so wildly that it’d be tough to form some default case such that most people wouldn’t wind up subclassing and overriding. And if most people are subclassing and overriding, then how much better off are we _really_ than where we are today, with Vapor including no default functionality of this sort?

Not to mention that there are cases (like working with databases, in my opinion) where boilerplate can be a _good_ thing, so that people can easily see and understand every step that’s being taken without having to dig around an extensive Swift package’s source code.

Just my two cents.

**Comment by LoganWright** [comment]
We originally had some support for this, but with Swift's type system, building a solution that works for everybody has proven difficult and we've opted to encourage a more convention system of adding routes manually.

There are two main options w/ protocols implementing 404 functions, or nil closures, neither of which we're very satisfied with.

In the future, it looks like there might be some more swift syntax support and we could explore metadata options, for now, I think we're going to keep this out of the core lib.

If you have strong ideas that solve some good problems, I'd suggest a 3rd party package and submit it in our Discord for users to try. If it becomes popular, we can explore integrating it into core.

Thanks so much for participating, feel free to ping me on discord for any further follow up questions or anything!
