### ISSUE TITLE
Enhancement: Please allow parameter skipping.

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1744]
Please provide a way to "skip" a parameter.  For example, my method is defined like so:

```swift
routerGroup.delete(Order.parameter, "work", WorkComplete.parameter, use: deleteWorkHandler)
```

However, the `WorkComplete` ID is  unique across the database, so I really don't actually *need* the `Order` to be decoded, but being RESTful it has to be in the path.  So I'd like to skip the round-trip to the database for the `Order` parameter.

**Comment by LoganWright** [comment]
@grosch this is _slightly_ trickier than it seems since it follows more of a stack model and is the most common behavior. 

With that said, here is an easy workaround for you and your specialized case:

```swift
guard req.parameters.values.count > 1 else { throw "appropriate error for your api"
let workCompleteId = req.parameters.values[1]
let workComplete = try WorkComplete.resolveParameter(workCompleteId.value, on: req)
```

Sorry about the late reply, let me know if that doesn't help you!
