### ISSUE TITLE
MySQLModel longtext type

### ISSUE THREAD

**Issue by JasonXJKJ** [vapor/vapor#1745]
```
import FluentMySQL

final class CoreProduct: MySQLModel {
    var id: Int?
    var name: String?
    var backgroundImage: String?
    var content: String?
    
    init(id: Int?, name: String, backgroundImage: String, content: String) {
        self.id = id
        self.name = name
        self.backgroundImage = backgroundImage
        self.content = content
    }
}

extension CoreProduct: Migration { }
```

`content` field need be `longtext` not `varchar(255)` how can i do this?

**Comment by grundoon** [comment]
@JasonXJKJ To customize fields, use a migration to create the database:

        static func prepare(on connection: MySQLConnection) -> Future<Void> {
            return MySQLDatabase.create(self, on: connection) { builder in
                builder.field(for: \.id)
                builder.field(for: \.name)
                builder.field(for: \.backgroundImage)
                builder.field(for: \.content, type: .longtext)
            }
        }

**Comment by JasonXJKJ** [comment]
@grundoon thanks!
