### ISSUE TITLE
Debuggable error id

### ISSUE THREAD

**Issue by mixio** [vapor/vapor#1747]
__Request for comment__

Adding a `errorID` property to the `Debuggable` protocol.

__Abstract__

When debugging, it is sometimes difficult to establish the relationship between
a reported exception and the source code that threw it.

A unique identifier establishing this relationship could be a useful addition.

__Proposed `errorID` format__

[0-9A-Fa-f]{8,}

A hex string with minimum length of 8 characters.
For example: `"6572726f724944"`

__Expected benefits__

When an error is reported in the console or displayed in a dialog, this
identifier could be copy/pasted to grep the source code and quickly find the
location where the exception was thrown.

__Caveats__

Every instance of `Debuggable` would need its unique random hex string.

A bit of caution has to be used after cutting and pasting code to avoid
duplicates.

__What would be required__

1. Adding an optional `errorID` property to the `Debuggable` protocol.

```swift
public protocol Debuggable: CustomDebugStringConvertible,
    CustomStringConvertible, LocalizedError {

    // ...

    /// A unique hex string with minimum length of 8 hex.
    /// Characters ([0-9A-Fa-f]{8,}).
    /// This `errorID` should be unique and set at initialization for
    /// each `Debuggable` instance.
    var errorID: String? { get }   // NEW PROPERTY.

    // ...
}
```

2. In the types that adopt `Debbugable`, adding the optional `errorID` to the
initializer(s) with a default value of `nil`.

```swift
public struct VaporError: Debuggable {

    // ...

    /// Creates a new `VaporError`.
    public init(
        identifier: String,
        reason: String,
        suggestedFixes: [String] = [],
        possibleCauses: [String] = [],
        file: String = #file,
        function: String = #function,
        line: UInt = #line,
        column: UInt = #column
        errorID: String? = nil  // NEW PROPERTY.
    ) {
        self.identifier = identifier
        self.reason = reason
        self.sourceLocation = SourceLocation(
            file: file,
            function: function,
            line: line,
            column: column,
            range: nil)
        self.stackTrace = VaporError.makeStackTrace()
        self.suggestedFixes = suggestedFixes
        self.possibleCauses = possibleCauses
        self.errorID: errorID // NEW PROPERTY.
    }

    // ...

}
```

3. Adding a unique identifiers to `Debbugable` instances.

```swift
throw VaporError(identifier: "foo", reason:"bar", /* ... */ , errorID:"5b3e5a533b215")
```

4. Adding the `errorID` to the logged or displayed error messages.

```swift
extension Logger {
    public func report(error e: Error, verbose: Bool = true) {
        switch e {
        case let debuggable as Debuggable:
            var errorString: String
            if let errorID = debuggable.errorID {
                errorString = "[errorID: \(errorID)] \(debuggable.fullIdentifier): \(debuggable.reason)"
            } else {
                errorString = "\(debuggable.fullIdentifier): \(debuggable.reason)"
            }
        // ...
    }
}
```

5. With a bit of caution the existing code could be updated with a recursive
script using a regular expression and a function generating random hex strings.

```sh
    $ # Example shell random hex string generators.
    $ xxd -l 4 -p /dev/urandom
    $ php -r "echo uniqid();"
    $ # ... Search google for your favorite language
```

6. If none exists, an Xcode Editor extension could be developed to help
generate and insert the random `errorID`s.

**Comment by LoganWright** [comment]
Adding fields to protocols can require some default stuff. It's not too tricky, but would require some discussion. 

We'll evaluate this for 3.1, thanks for the contribution 🙌
