### ISSUE TITLE
log source

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1749]
Non-`Debuggable` logging is showing the wrong source location:

```sh
[ DEBUG ] Conform `HTTPParserError` to `Debuggable` for better debug info. (Logger+LogError.swift:34) 
```

Correct file and line info should be passed through using default args.

**Comment by tanner0101** [comment]
Helped a bit by #1813, #1796 but still not entirely solved. For non-`Debuggable` errors, there's no way to get the source location of the error. In these cases, I think we should just omit the file location instead of showing a confusing one.

**Comment by Joannis** [comment]
@tanner0101 is this still an issue?

**Comment by tanner0101** [comment]
Yes. Vapor only logs the source information if it exists now. That way there's not useless source location info being printed.
