### ISSUE TITLE
How do I make all subclasses Model have the attributes of createdAt, updatedAt, and custom entity?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1750]
How do I make all subclasses Model have the attributes of createdAt, updatedAt, and custom entity?

I now have a BaseSQLModel defined as follows: 

```swift
import Foundation
import Vapor
import FluentPostgreSQL

public typealias BaseSQLModel = PostgreSQLModel & Migration & Content
```

But I don't know how to make it implement the above three properties, so that all models that inherit from BaseSQLModel have these three properties, instead of having to write once every time you create a model. 🤔

> English is not my native language; please excuse typing errors.

**Comment by fwgreen** [comment]
@Jinxiansen This seems to be a [Fluent ORM](https://github.com/vapor/fluent) issue, but maybe [this might help](https://github.com/vapor/fluent/blob/984daa174a31c91e08f4b2904d6acb3636beca15/Sources/Fluent/Model/Model.swift#L48)?  Maybe I'm wrong, but I don't think Codable allows you to have JPA style (what I'm most familiar with) inheritance models.

**Comment by Jinxiansen** [comment]
@fwgreen 

Yes, Swift doesn't allow this. 😔
In the end, I can only write this way, but I am not satisfied.

https://github.com/Jinxiansen/SwiftServerSide-Vapor/blob/master/VaporServer/Sources/App/Models/BaseSQLModel.swift
