### ISSUE TITLE
The Client protocol encourages unnecessarily retaining the container property

### ISSUE THREAD

**Issue by proggeramlug** [vapor/vapor#1752]
One of the only two requirements of the `Client protocol` is the `var container: Container { get }` property. This has become something of a de facto standard in the design of many Services in Vapor 3, that the `Container` passed to `ServiceType.makeService(for:)` is stored as a reference in a property on the created service. Unfortunately, because services are cached heavily by the `Containers`, this tends to lead to trivial retain cycles which do problematic things like keep the first Request to create an instance of a given Service alive _forever_. This in turn ultimately roots the entire object graph, including `Application`. This doesn't matter in Vapor's typical usage, but is at best a giant pain in the rear when writing unit tests, and is wasteful of memory besides. Client typically uses its `container` as a base on which to create a `Request` to send, but it would arguably be better design to require callers of `Client` to pass a container in at "send" time (though admittedly less accessible to beginners), which would eliminate the retain cycle.

**Comment by tanner0101** [comment]
You bring up a good point here. I do think that is a design flaw in `Client`. Although, I don't think there is much that can be done about that in the current version.

I think this is related to a more general issue stated here: https://github.com/vapor/vapor/issues/1711. As that issue notes:

> With thread safe controllers, Request will no longer need to be a Container (since the container will be accessible at the route registration / controller phase. This will mean that HTTPRequest and Request can be combined, simplifying the middleware and router layers.

This would mean that `Client` would no longer need this container property. It's even possible that more powerful controllers could help do away with service caching altogether. 

Thoughts?

**Comment by proggeramlug** [comment]
The main issue if it's removed from Request and Client is how to get at a suitable event loop for returning futures and promises.

**Comment by tanner0101** [comment]
You would still use a container to create the client, just at boot time (when configuring the controller) instead of at route time (when responding to a request). The event loop would be captured at that point, so no need to pass it during each request.

**Comment by tanner0101** [comment]
This has been fixed in Vapor 4
