### ISSUE TITLE
Why nobody cant connect to Vapor site and servers from Russia?

### ISSUE THREAD

**Issue by riley-usagi** [vapor/vapor#1753]
Why nobody cant connect to Vapor site and servers from Russia?

**Comment by joscdk** [comment]
@riley-usagi What site are you trying to access, and what error do you get?

**Comment by joscdk** [comment]
It seem that in April Russie blocked ~800,000 IP addresses used by AWS, which might have hit our servers, as they are hosted on AWS
https://www.theregister.co.uk/2018/04/17/russia_blocks_google_aws_ip_addresses_to_get_telegram/

**Comment by joscdk** [comment]
And if that is the case, i think a VPN would be the best solution to get around it :)

**Comment by riley-usagi** [comment]
@joscdk , it is really sad. =(

And VPN cant help users to access to Vapor Cloud systems.
