### ISSUE TITLE
runs slowly

### ISSUE THREAD

**Issue by lokimx88** [vapor/vapor#1756]
* Vapor Framework version: 2.3.0
* Vapor Toolbox version:
* OS version: debain9

I have compiled  "vapor/ web-template"  sucessfully. 
`swift build -c release`
And the welcome page  shows ; But the ab result is wired.
Is there anything wrong? there must be something I missed.

```
C:\Users\Administrator\Desktop\ab>ab  -n 100 -c 10 http://192.168.1.181:8080/
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 192.168.1.181 (be patient).....done


Server Software:
Server Hostname:        192.168.1.181
Server Port:            8080

Document Path:          /
Document Length:        199 bytes

Concurrency Level:      10
Time taken for tests:   334.131 seconds
Complete requests:      100
Failed requests:        1
   (Connect: 1, Receive: 0, Length: 0, Exceptions: 0)
Write errors:           0
Total transferred:      31600 bytes
HTML transferred:       19900 bytes
Requests per second:    0.30 [#/sec] (mean)
Time per request:       33413.111 [ms] (mean)
Time per request:       3341.311 [ms] (mean, across all concurrent requests)
Transfer rate:          0.09 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.5      1       1
Processing: 30495 30942 1013.8  30720   36635
Waiting:        0  211 934.1      1    5995
Total:      30496 30943 1013.8  30720   36635

Percentage of the requests served within a certain time (ms)
  50%  30720
  66%  30721
  75%  30721
  80%  30721
  90%  30721
  95%  32542
  98%  36634
  99%  36635
 100%  36635 (longest request)
```

**Comment by vzsg** [comment]
> Vapor Framework version: github master

Please include the real framework version from Package.resolved.

**Comment by lokimx88** [comment]
yes ,that's 2.3.0

**Comment by vzsg** [comment]
Please also try the following:
- run `vapor update` or `swift package update` to update the dependencies to the current versions (for Vapor 2, that would be 2.4.4).
- make sure that you start the release executable with the `--env production` argument, which will enable some internal caching for Leaf.

**Comment by lokimx88** [comment]
`swift build -c release --env=production`
I get this error:
` error:unkown option --env;use --help to list available options`

**Comment by vzsg** [comment]
Let me spell that out:

```
$ swift build -c release
$ .build/release/Run --env=production
```

**Comment by lokimx88** [comment]
just a little better

```
Concurrency Level:      10
Time taken for tests:   316.016 seconds
Complete requests:      100
Failed requests:        0
Write errors:           0
Total transferred:      31600 bytes
HTML transferred:       19900 bytes
Requests per second:    0.32 [#/sec] (mean)
Time per request:       31601.607 [ms] (mean)
Time per request:       3160.161 [ms] (mean, across all concurrent requests)
Transfer rate:          0.10 [Kbytes/sec] received
```

**Comment by vzsg** [comment]
How are you running the Debian server, is it a VM or another machine on the same network?

**Comment by grundoon** [comment]
@vzsg I'll just point out I get similar results on macOS (10.13.6) native. `wrk` on the same exact running instance happily reports

    Requests/sec:  19575.75
    Transfer/sec:      5.90MB

**Comment by grundoon** [comment]
I do note that the default timeout is 30s and the results here were

    Concurrency Level:      10
    Time taken for tests:   300.312 seconds
    Complete requests:      100
    Failed requests:        0

which seems both odd (100%) and awfully coincidental (10 * 30s).

**Comment by grundoon** [comment]
What's probably more useful to note is that with `-v 4` the `-c` # of responses are logging instantaneous. Then the 30s delay before marking completion.

**Comment by LoganWright** [comment]
Unable to reproduce this locally. If you're still seeing issues on the latest Vapor 3.x version, please reopen the issue and if possible link out to the exact test project running.

Thanks for participating, and as always, there's lots of people in Discord to help you hash through problems 😄 

vapor.team
