### ISSUE TITLE
In Swift 4 (linux), how do I use a third-party library for Python 3 ?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1758]
I want to use some `third-party libraries` in `Python 3`, 
but I don't know how `vapor` supports `Python`.

> English is not my native language; please excuse typing errors.

**Comment by vzsg** [comment]
It doesn't. There is absolutely nothing in common between the two. What are you trying to do?

**Comment by Jinxiansen** [comment]
@vzsg

**Comment by vzsg** [comment]
I'm afraid there's no simple way to use them. Either you could call python scripts via the `Console` class (and do something via standard input/output), or in theory using the C interface of Python could work, but both are seriously more trouble than their worth.

---

I think you should just use Python to build that project of yours.

**Comment by Jinxiansen** [comment]
@vzsg  You are right, but I am a vapor application.
Perfect has a `Perfect-Python` support for Python 2 to interact with Swift, but I want to find the Python 3 version, as if Swift 5 would support it next year.
