### ISSUE TITLE
Cannot add JSON dependency

### ISSUE THREAD

**Issue by rjt3662** [vapor/vapor#1759]
Hi there,
I'm new to Vapor. I'm following some tutorials to develop API using vapor but they are a bit outdated as they are of vapor 1. I've followed same steps to create project for api template as shown in tutorial. I don't know why the JSON dependency isn't added automatically. I'm not that much familiar with Vapor. Below is the SS of my project structure. Please Help.
![screen shot 2018-07-19 at 10 27 42 am](https://user-images.githubusercontent.com/21313219/42922513-77fee46e-8b3e-11e8-8fa3-e06a4eca1e42.png)

**Comment by linqingmo** [comment]
Read this [docs](https://docs.vapor.codes/3.0/).
Vapor 3 dose not use JSON framework. It uses `Codable` to handle JSON.

**Comment by rjt3662** [comment]
Thanks @linqingmo
