### ISSUE TITLE
vapor build fails

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1760]
The build command isn't working.  I have no idea how to build via the swift package manager.

### Steps to reproduce

% vapor build
No .build folder, fetch may take a while...
Fetching Dependencies [                •        ]
Error: backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\nerror: root manifest not found\n", output: "")

### Environment

* Vapor Framework version: 3.0.6
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.6

**Comment by grundoon** [comment]
This is the error you would expect to encounter if you are not in the project directory when issuing the command.

    $ vapor new projectName
    $ cd projectName // <-- if you forget this, you will see that error
    $ vapor build

**Comment by grosch** [comment]
Wow, where's that headslap icon?

**Comment by grundoon** [comment]
We've *all* been there 🙂
