### ISSUE TITLE
Enhancement: Support merge-patch RFC 7396

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1761]
How hard would it be to add a mergePatch method to the router?  That would basically be just like a patch operation, but would ensure that the content-type was application/merge-patch+json

### Expected behavior

Basically if you use mergePatch this code would automatically run:

```swift
        guard let ct = req.http.contentType,
            ct.type.lowercased() == "application",
            ct.subType.lowercased() == "merge-patch+json" else {
                throw Abort(.badRequest)
        }
```

That way we don't have to do it ourselves in each patch method, and callers know that we expect a certain behavior of patching.

**Comment by mcdappdev** [comment]
You should be able to do that as middleware and then chain it to any of your patch routes
