### ISSUE TITLE
Vapor project won't build on Xcode 10 beta 4

### ISSUE THREAD

**Issue by insidegui** [vapor/vapor#1765]
### Environment

* Vapor Framework version: 3.0.6
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13.5

### Problem

When trying to build [the project](http://github.com/insidegui/Sharecuts) on Xcode 10 beta 4 (after running `vapor xcode` to generate it), the build fails in `URLEncodedFormParser.swift` line 101 with the error `Ambiguous use of 'init'`.

Running `vapor build` from the command line is successful.

I tried cleaning, rebuilding and regenerating the Xcode project multiple times.

**Comment by calebkleveter** [comment]
I'm not getting that error. I would delete derived data, your `.build` directory in the project root, and the Xcode project. Then update your packages (just in case something new has come around) and try again.

**Comment by insidegui** [comment]
I've already tried that

**Comment by calebkleveter** [comment]
Looks like there is a PR open for this: https://github.com/vapor/url-encoded-form/pull/13/files

**Comment by insidegui** [comment]
Great, I'll wait for that to me merged then. Thank you

**Comment by calebkleveter** [comment]
Quick update, on this. The PR has been merged, so Vapor should work now.

**Comment by freak4pc** [comment]
Is this part of any release ? Seems like not.

**Comment by calebkleveter** [comment]
@freak4pc Looks like it is in the latest release: https://github.com/vapor/url-encoded-form/commits/1.0.4

**Comment by freak4pc** [comment]
Whoops, my bad :) Thanks !
