### ISSUE TITLE
Conform NotFound to AbortError

### ISSUE THREAD

**Issue by JovanMilenkovic** [vapor/vapor#1770]
Not finding a model in the database when passed as a route parameter results in 500 Internal server error.

### Steps to reproduce

1. register a route (example) router.get("users", User.parameter)
2. add try req.parameters.next(User.self) to the closure

### Expected behavior
Client receives a 200 Ok response for an existing id
Client receives a 404 Not found response for non existing id

### Actual behavior
Client receives a 200 Ok response for an existing id
Client receives a 500 Internal server error response for non existing id

### (Custom) Problem analysis
Fluent queries the db and returns a NotFound error initialized with a FluentError.
ErrorMiddleware doesn't recognize the NotFound error and treats it as a server error.
Proposed solution: Add extension NotFound: AbortError to vapor

**Comment by 0xTim** [comment]
Fixed in #1771
