### ISSUE TITLE
Right way coding

### ISSUE THREAD

**Issue by guarland** [vapor/vapor#1773]
Hello vapor users!  I'm new to async programming, please look at my code, do I go right? there is any memory leak or wrong way?

    func GetCode(_ req: Request) throws -> Future<HTTPResponse>  {
        
        let number = try req.parameters.next(String.self)
        
        if !validateNum(number) {
            return  req.future(HTTPResponse(status: .badRequest , body: "error"))
        }
        
        return req.withPooledConnection(to: .psql){ (conn: PostgreSQLDatabase.Connection) -> Future<PendingAccount?>  in
              return PendingAccount.query(on: conn).filter(\.number == number).first()
         }.flatMap { (pAcc) -> Future<HTTPResponse> in
            if var tempPendingAcc = pAcc {
                return req.withPooledConnection(to: .psql){ (conna: PostgreSQLDatabase.Connection) -> Future<HTTPResponse>  in
                    tempPendingAcc.verification_code = utils.generateVerificationCode()
                    tempPendingAcc.created = 0
                    tempPendingAcc.used = 10023
                    self.sendSmS(tempPendingAcc.number)
                    return  tempPendingAcc.update( on: conna).flatMap({ (pac) -> Future<HTTPResponse> in
                        return req.future(HTTPResponse(status: .ok , body: "updated:ok"))
                    })
                }
            } else {
                return req.withPooledConnection(to: .psql){ (connb: PostgreSQLDatabase.Connection) -> Future<HTTPResponse>  in
                    var pendingAccount = PendingAccount()
                    pendingAccount.number = number
                    pendingAccount.verification_code = utils.generateVerificationCode()
                    pendingAccount.created = 100
                    pendingAccount.used = 1
                    self.sendSmS(pendingAccount.number)
                    return  pendingAccount.create( on: connb).flatMap({ (pac) -> Future<HTTPResponse> in
                        return req.future(HTTPResponse(status: .ok , body: "inserted:ok"))
                    })
                   
                }
            }
        }
    }

* Vapor Framework version: 3 
* OS version: Mac os x

**Comment by rafiki270** [comment]
@guarland this doesn't seem to be an issue with Vapor, could you please ask a question on the Vapor discord chat? http://vapor.team/ to get signed up
