### ISSUE TITLE
The Future method cannot be executed in a for loop. 

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1775]
<img width="912" alt="book" src="https://user-images.githubusercontent.com/16829428/43191697-47a85daa-902e-11e8-8c6c-a75a27dc3e5c.png">

Why can't this Future method be executed in a for loop?
The `book` could not be saved to the database. 🧐

> English is not my native language; please excuse typing errors.

**Comment by vzsg** [comment]
Are you actually getting an error on the marked line?

**Comment by Jinxiansen** [comment]
@vzsg  There are no mistakes, just don't perform.I later replaced by the timer to complete the requirements.😛
