### ISSUE TITLE
On Linux, how to convert UTF8 to GBK ?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1776]
<img width="561" alt="gbk" src="https://user-images.githubusercontent.com/16829428/43275105-83967440-9133-11e8-8cf2-88c0ec4a51ce.png">

When I crawled the HTML, the landing page was a `gbk` encoding, and I needed to convert it to `utf8`.

```swift
extension HTTPBody {

    var gbkString: String { 
        //获取GBK编码，使用GB18030是因为它向下兼容GBK
        let cfEncoding = CFStringEncodings.GB_18030_2000
        let encoding = CFStringConvertEncodingToNSStringEncoding(CFStringEncoding(cfEncoding.rawValue))
        //从GBK编码的Data里初始化NSString，返回的NSString是UTF-16编码
        if let str = NSString(data: data ?? Data(), encoding: encoding) {
            return str as String
        } else {
            return "n/a"
        }
    }
}
```

But the method I use, it can run on mac, there is no such method in the `Linux foundation`.

Running on `linux` , will prompt the following error:
![er](https://user-images.githubusercontent.com/16829428/43275194-c4dfefb2-9133-11e8-8d60-5d6da36d1e44.png)

I checked the information, but I didn't find a solution. I would like to ask for help! please!

> English is not my native language; please excuse typing errors.

**Comment by grundoon** [comment]
It looks like Perfect has a Swift package that should be able to perform this conversion: https://github.com/PerfectSideRepos/Perfect-ICONV

**Comment by Jinxiansen** [comment]
@grundoon  @vzsg  This is the Perfect project, then the vapor have?

**Comment by Jinxiansen** [comment]
<img width="904" alt="lm" src="https://user-images.githubusercontent.com/16829428/43299898-f8c77eac-918e-11e8-9314-cc1d32c51bb1.png">

<img width="654" alt="gb" src="https://user-images.githubusercontent.com/16829428/43299928-164914b8-918f-11e8-988b-026053a1c2ce.png">


@grundoon   This is garbled, not Chinese characters.
This is garbled, not Chinese characters. I have tried these `GB` related enumerations, and they are useless. 😔

**Comment by vzsg** [comment]
Vapor doesn't have a package like this, but Perfect's iconv wrapper should work.
Can you share the source of your attempt at downloading the HTML and converting it?

**Comment by Jinxiansen** [comment]
@vzsg   Yes, big brother, I really hope to get your help, this is the URL: https://www.piaotian.com/html/9/9102/ 

Right click to view the source code, can see the code for the `charset = gbk` first shown above ~

**Comment by Jinxiansen** [comment]
I try to use Perfect 's iconv, but hasn't been able to solve my problem, I do not know if there is something wrong with the usage, or does not support this code ...

**Comment by vzsg** [comment]
That's just half of what I meant. I also need _your_ Swift source code where you download and try to parse this page.

**Comment by vzsg** [comment]
Actually, I just noticed an issue on your screenshot. You initiialized the byte array with `clientResponse.http.body.description.utf8`, which garbled up everything before even touching iconv.

**Comment by vzsg** [comment]
Check this out:

```swift
router.get("jinx") { req -> Future<String> in
    let client = try req.make(Client.self)
    let iconv = try Iconv(from: Iconv.CodePage.GBK, to: Iconv.CodePage.UTF8)
    let url = "https://www.piaotian.com/html/9/9102/"
    return client.get(url)
        .flatMap { $0.http.body.consumeData(on: req) } // 1) read complete body as raw Data
        .map { (data: Data) -> String in
            // 2) convert Data to [UInt8] for Iconv
            var bytes = [UInt8](repeating: 0, count: data.count)
            let buffer = UnsafeMutableBufferPointer(start: &bytes, count: bytes.count)
            _ = data.copyBytes(to: buffer)

            // 3) convert GBK -> UTF8
            return iconv.utf8(buf: bytes) ?? ""
    }
}
```

I can't read Chinese, but the characters in the output seem to be the same as the ones I see in Chrome.

**Comment by Jinxiansen** [comment]
@vzsg   B: oh!Big brother, you are so smart!Thank you very much!I really don't know how to express my gratitude! !😃😁😁

**Comment by Jinxiansen** [comment]
@vzsg  But when I deployed it on Linux, this was not working.

**Comment by Jinxiansen** [comment]
@vzsg 

<img width="867" alt="gu" src="https://user-images.githubusercontent.com/16829428/43331137-a7d42a90-91f7-11e8-8f05-9e1f83048f42.png">
![err](https://user-images.githubusercontent.com/16829428/43331138-aa415c6c-91f7-11e8-95e8-c04894d8da37.png)
![convert](https://user-images.githubusercontent.com/16829428/43331146-ac5a3d8e-91f7-11e8-9458-eed3771b02ac.png)


I tried it many times, this method, on Linux, still can't parse the results. When I get the original `gbk` page data, I use this method to transcode and work on the Mac, but on Linux, the results are as you can see. 🤔

**Comment by vzsg** [comment]
I'm investigating your issue. All I see now is that the conversion returns an EILSEQ error code when run in Linux.

**Comment by vzsg** [comment]
During the last hour, I've found that iconv is working correctly on both platforms. If I use the `convert` function of Iconv instead of `utf8`, identical 33902 bytes are returned.

But `String(validatingUTF8:)` (the last call that converts the bytes into a String) fails on Linux, while it works on macOS. This smells like an issue in the Linux Foundation. 😞

**Comment by Jinxiansen** [comment]
@vzsg  Thank you very much! This method is finally working on Linux 😭. Without you, I might be at a loss as to how to deal with this problem. You are such a great person!  👍👍👍
