### ISSUE TITLE
Type Unknown when using Generics for a RouteCollection

### ISSUE THREAD

**Issue by nathantannar4** [vapor/vapor#1780]
When attempting to make a generic `RouteCollection`, I noticed that calling `next(_:)` on `ParametersContainer` it does not return an `EventFutureLoop`. Note, it can be cast to an `EventFutureLoop` and doesn't fail. I believe the issue is that `Parameter` uses an `associatedtype` so this could just be something the Swift compiler gets confused about. 

### Steps to reproduce

```swift
public protocol CRUDModel: Model, Parameter, Content {}

open class CRUDController<T:CRUDModel>: RouteCollection {

    open func boot(router: Router) throws { }

    func index(_ req: Request) throws -> Future<T> {
        let future = try req.parameters.next(T.self)
        return future // ERROR: future is of type CRUDModel.ResolvedParamater

        // This can be fixed with
        // guard let future = try req.parameters.next(T.self) as? EventLoopFuture<T> else {
        //    throw Abort(.notImplemented)
        // }
        // return future
    }

     open func create(_ req: Request) throws -> Future<T> {
         return try req.content.decode(T.self).save(on: req) // This works
    }

}
```

From what I can tell, `decode(_:)` doesn't use an `associatedtype` where as `Parameter` does. 

I then tried to override the `ResolvedParamater` `associatedtype` but that still did not work. I did the following

```swift
// 
extension Acronym: CRUDModel, Parameter {
    
    typealias ResolvedParameter = EventLoopFuture<Acronym>
    
    static func resolveParameter(_ parameter: String, on container: Container) throws -> EventLoopFuture<Acronym> {
        // Not sure what to actually put here
    }
}

extension CRUDModel where ResolvedParameter == EventLoopFuture<Acronym> {}
```

### Expected behavior

```swift
let future = try req.parameters.next(T.self)
assert(future is EventLoopFuture<T>) // TRUE
```

### Behavior without generics

```swift
final class MyModel: Model, Parameter, Content { }
...
let future = try req.parameters.next(MyModel.self)
// future is of type EventLoopFuture<MyModel.self>
```

### Actual behavior

The use of generics and `associatedtypes` could just be confusing the Swift compiler

```swift
let future = try req.parameters.next(T.self)
// future is of type CRUDModel.ResolvedParamater
```

### Environment

* Vapor Framework version: v3.0.8
* Vapor Toolbox version: Vapor Toolbox: 3.1.7
* OS version: OSX 10.13.6

**Comment by tanner0101** [comment]
Yes, `req.parameters.next(T.self)` returns `T` which is expected. I think the only problem here is that your route needs to return just `T` instead of `Future<T>`.

```swift
func index(_ req: Request) throws -> T
```

From there, you can ensure that `CRUDModel` is something `ResponseEncodable` (like `Content`) and everything should work great 👍
