### ISSUE TITLE
Invalid values cause crash on MySQL, via Fluent

### ISSUE THREAD

**Issue by t-ae** [vapor/vapor#1782]
`MySQLDataConvertible.convertFromMySQLData` throws errors if the value given is not valid, like `text` for `Int` or `3` for `Bool` or whatsoever.
https://github.com/vapor/mysql/blob/448f1ca28b3ea0f64a627bec22e5b0945d31b9f4/Sources/MySQL/Connection/MySQLData.swift

However, if we try to get illegitimate rows via Fluent `QueryBuilder`, errors are also thrown but handler tries to close connection immediately, and app crashes on [here](https://github.com/vapor/mysql/blob/448f1ca28b3ea0f64a627bec22e5b0945d31b9f4/Sources/MySQL/Connection/MySQLConnection.swift#L120).

Of course we should carefully configure the column's and the model's data type, but also we shouldn't let it crash I think.
And the error we see is only `Cannot close during a query.`. It makes debugging a bit more difficult.

**Comment by t-ae** [comment]
I noticed this happens only when I use `withNewConnection`.

Suppose we have invalid values in DB. The code below shows different behavior.

```swift
struct User: MySQLModel {
    static var entity = "users"
    var id: Int?
    var is_banned: Bool
}

// Suppose there are some rows that have 2 or 3 or something for `is_banned` column.

do {
    // this throws error
    try User.query(on: req).all().wait()
} catch {
    print("use req directly: \(error)")
}

do {
    // this also throws error
    try req.withPooledConnection(to: .mysql) { conn in
        User.query(on: conn).all()
        }
    }.wait()
} catch {
    print("withPooledConnection: \(error)")
}

do {
    // this cause crash
    try req.withNewConnection(to: .mysql) { conn in
        User.query(on: conn).all()
    }.wait()
} catch {
    print("withNewConenction: \(error)")
}
```

**Comment by tanner0101** [comment]
Thanks for reporting @t-ae. I can see why the issue would only be happening with `withNewConnection`. When the query has completed (either by error or success), `withNewConnection` attempts to close the connection. In the case of this decoding error, the query has still not technically completed which puts the connection in an invalid state. 

Would you mind moving this issue to https://github.com/vapor/mysql/issues? That is where the relevant code is located. We need to find a solution there to allow for the connection to be closed early, even if the query has not yet completed yet.
