### ISSUE TITLE
Vapor Heroku only allows pushing master branch to heroku master

### ISSUE THREAD

**Issue by westonmiller** [vapor/vapor#1783]
Using the command
```
$ vapor heroku push
```
will only push the master branch to heroku/master.  There are times when I would like tops a feature branch to heroku for testing. 

or

there is a way, but `$ vapor heroku push --help` has missing documentation.

### Steps to reproduce

1. Change to non-master branch
1. Run `$ vapor heroku push`

### Expected behavior

Pushes the current branch to heroku

or have options similar to git
```
$ vapor heroku push --force feature-branch:master
```

### Actual behavior

Will just push the master branch to heroku

### Environment

* Vapor Framework version: 3.0.0
* Vapor Toolbox version: 3.1.7
* OS version: macOS 10.13.2

**Comment by tanner0101** [comment]
Hey @westonmiller, thanks for reporting. Would you mind moving this issue feature request to https://github.com/vapor/toolbox? That is where the relevant code is located. Thanks!
