### ISSUE TITLE
No global methods

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1784]
Let's stop using global methods in app.swift, boot.swift, configure.swift, and routes.swift as it goes against the Swift style guide.

**Comment by mcdappdev** [comment]
@grosch This probably belongs in either one of the template repos or on the styleguide. Vapor the actual framework doesn't promote those styles, just the templates and style guide do. I think the community will better benefit from this discussion being held in a different location

**Comment by grosch** [comment]
Moving to template repo
