### ISSUE TITLE
throwing HTTPResponseStatus.noContent does not close connection.

### ISSUE THREAD

**Issue by Antonasg** [vapor/vapor#1787]
When throwing an error of type `HTTPResponseStatus.noContent`  the connection does not close
and the request hangs.

```swift
throw Abort.init(HTTPResponseStatus.noContent)
``` 

Throwing an error with `.notFound` closes the connection immediately

### Steps to reproduce

When throwing this error:
```swift
throw Abort.init(HTTPResponseStatus.noContent)
``` 

Might be related: #1770  

### Expected behavior

The connection should close, just as when throwing any other error.

### Actual behavior

The connection is kept open, and the HTTP request hangs.

### Environment

* Vapor Framework version: 3.0.8
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.4

**Comment by tanner0101** [comment]
I couldn't recreate the issue of the connection not closing / hanging. But I did notice that Vapor was incorrectly sending a response body even with the 204 status code. I created a PR here to resolve that: https://github.com/vapor/http/pull/304

I've also added a test to ensure 204 status responses are working correctly just in case.

**Comment by tanner0101** [comment]
HTTP 3.1.1 has been pushed with this fix. LMK if you see this issue anymore, thanks!
