### ISSUE TITLE
How to run multiple vapor 3 projects in Ubuntu ?

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#1789]
How to run `multiple` vapor 3 projects in `Ubuntu`?
Exclude `Nginx`.
🤔

**Comment by Jinxiansen** [comment]
@vzsg 


Thank you for your answer!

I know this way by changing the port.
But I don't know how to configure multiple IPs on the Ubuntu server and bind the domain name. For example, the domain names are `api.jinxiansen.com`, `blog.jinxiansen.com`, `shop.jinxiansen.com` .
 How do I configure it in vapor?

--
In cases where I don't use `Nginx`.

**Comment by MrLotU** [comment]
I know how to achieve this using Nginx, why do you not want to use this?

**Comment by zachaysan** [comment]
What you need to do is emulate what nginx would do for you automatically. That means you create a program that listens on 80 or 443, reads the subdomain, then proxies the data to the process that you want to handle the request listening on a different port. There is no way of binding a subdomain to a different port and there is no way to have multiple processes listening on the same port. 

I don't know why you can't use nginx, but this is a valid way of handling it if you're in some weird environment. Of course another valid way is to use a different server per subdomain.

**Comment by LoganWright** [comment]
@Jinxiansen there's nothing out of the box to do this, with nginx stuff, it's not so much multiple projects on one port as it is one nginx project on one port that distributes outward.

You could setup a small vapor server to listen on your desired port and forward the requests out to your sub projects. 

I think this is your best course of action, and a small vapor server to do that shouldn't be too expensive as far as resources! Let us know how it works out, if you made a small package, there might be others that would also benefit from it 👍
