### ISSUE TITLE
Could vapor run on CentOS?

### ISSUE THREAD

**Issue by developforapple** [vapor/vapor#1790]
How

**Comment by tanner0101** [comment]
Vapor can run on all platforms Swift supports. See https://swift.org/download/. CentOS is not supported there. However, Vapor is normally deployed through Docker anyway. If you use a standard Swift image to deploy, you don't need to worry about OS compatibility.

**Comment by LoganWright** [comment]
Closing this for now, there's some threads out there about getting Swift and by virtue Vapor running on more obscure systems, for now, we're only able to officially support platforms officially supported by swift.
