### ISSUE TITLE
Missing project.pbxproj file and cannot run project

### ISSUE THREAD

**Issue by dillonfagan** [vapor/vapor#1791]
After creating a new vapor project and running `vapor xcode` within the project's root directory, a new Xcode project is generated, but it is missing its project.pbxproj file and therefore cannot be opened:

"Project /Users/[User]/Documents/Projects/[ProjectName]/[ProjectName].xcodeproj cannot be opened because it is missing its project.pbxproj file."

Another (but possible related) problem is that after running `vapor build` and `vapor run`, the project does not run and this message is returned in the terminal: "Error: No builds found for debug configuration."

### Steps to reproduce

I have already tried updating vapor, updating Xcode, reinstalling vapor and Xcode; none of which have solved the problem.

### Expected behavior

A complete, functioning Xcode project should have been generated.

### Actual behavior

The resulting Xcode project is missing its project.pbxproj file in the package contents and possibly more (not sure).

### Environment

* Vapor Framework version: 3.0.8
* Vapor Toolbox version: 3.1.10
* OS version: macOS High Sierra (10.13.6)

I was also having this problem with earlier versions. See this older issue:
#1620

**Comment by vzsg** [comment]
Care to post your Package.swift without any modification?

**Comment by dillonfagan** [comment]
@vzsg Not a problem 

```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "Tend",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        // 🍃 An expressive, performant, and extensible templating language built for Swift.
        .package(url: "https://github.com/vapor/leaf.git", from: "3.0.0"),
    ],
    targets: [
        .target(name: "App", dependencies: ["Leaf", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

**Comment by grundoon** [comment]
That looks perfect. Is it possible you could post your `Tend.xcodeproj/package.pbxproj` file up on GitHub as a gist or some such (or attach it here if need be...`compress`ed it should be about 80K)?

I looked at your previous issue, and into a bunch of other non-Vapor but similar issues out there (seems there are all sorts of potential causes, with limited real understanding as to precisely what unless in a team repo environment). Have you by any chance wiped and reinstalled your entire environment from scratch since then? (I mean, it's really sounding like there's something, *something*, just plain whacky in your environment.)

**Comment by dillonfagan** [comment]
The problem is that there also isn't a package.pbxproj file. Inside the project there is a .xcworkspace file and the xcshareddata directory, nothing else.

I've tried reinstalling vapor and reinstalling xcode, but I haven't gone beyond that since this is my daily computer, so wiping everything would be a huge project in itself.

**Comment by vzsg** [comment]
What's the output of `swift package generate-xcodeproj`?

**Comment by dillonfagan** [comment]
`Illegal instruction: 4`

**Comment by dillonfagan** [comment]
I don't think it's my development environment, because `swift package generate-xcodeproj` is working fine with other frameworks like Kitura... but I would prefer to use Vapor

**Comment by grundoon** [comment]
Though, at least previously, you were able to generate just fine on another Mac. The output of one or more of the following commands *might* help provide some clue:

 `xcode-select -p`
 `rm -rf .build && vapor build --verbose`
 `openssl version`
 `locate libssl | grep usr`
 `locate xcconfig`

**Comment by dillonfagan** [comment]
`xcode-select -p`
/Applications/Xcode.app/Contents/Developer

`rm -rf .build && vapor build --verbose`
No .build folder, fetch may take a while...
Fetching Dependencies ...
Fetching https://github.com/apple/swift-nio-zlib-support.git
Fetching https://github.com/vapor/validation.git
Fetching https://github.com/vapor/core.git
Fetching https://github.com/vapor/console.git
Fetching https://github.com/vapor/http.git
Fetching https://github.com/vapor/crypto.git
Fetching https://github.com/vapor/database-kit.git
Fetching https://github.com/vapor/leaf.git
Fetching https://github.com/vapor/routing.git
Fetching https://github.com/vapor/service.git
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/apple/swift-nio-ssl-support.git
Fetching https://github.com/vapor/template-kit.git
Fetching https://github.com/vapor/websocket.git
Fetching https://github.com/vapor/url-encoded-form.git
Fetching https://github.com/vapor/multipart.git
Fetching https://github.com/vapor/vapor.git
Fetching https://github.com/apple/swift-nio-ssl.git
Cloning https://github.com/apple/swift-nio-zlib-support.git
Resolving https://github.com/apple/swift-nio-zlib-support.git at 1.0.0
Cloning https://github.com/vapor/validation.git
Resolving https://github.com/vapor/validation.git at 2.0.0
Cloning https://github.com/vapor/http.git
Resolving https://github.com/vapor/http.git at 3.0.7
Cloning https://github.com/vapor/console.git
Resolving https://github.com/vapor/console.git at 3.0.2
Cloning https://github.com/vapor/core.git
Resolving https://github.com/vapor/core.git at 3.4.1
Cloning https://github.com/vapor/database-kit.git
Resolving https://github.com/vapor/database-kit.git at 1.3.0
Cloning https://github.com/vapor/crypto.git
Resolving https://github.com/vapor/crypto.git at 3.2.0
Cloning https://github.com/vapor/websocket.git
Resolving https://github.com/vapor/websocket.git at 1.0.1
Cloning https://github.com/apple/swift-nio-ssl-support.git
Resolving https://github.com/apple/swift-nio-ssl-support.git at 1.0.0
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 1.9.0
Cloning https://github.com/vapor/service.git
Resolving https://github.com/vapor/service.git at 1.0.0
Cloning https://github.com/vapor/routing.git
Resolving https://github.com/vapor/routing.git at 3.0.1
Cloning https://github.com/vapor/template-kit.git
Resolving https://github.com/vapor/template-kit.git at 1.1.0
Cloning https://github.com/vapor/leaf.git
Resolving https://github.com/vapor/leaf.git at 3.0.0
Cloning https://github.com/vapor/url-encoded-form.git
Resolving https://github.com/vapor/url-encoded-form.git at 1.0.4
Cloning https://github.com/vapor/multipart.git
Resolving https://github.com/vapor/multipart.git at 3.0.2
Cloning https://github.com/vapor/vapor.git
Resolving https://github.com/vapor/vapor.git at 3.0.8
Cloning https://github.com/apple/swift-nio-ssl.git
Resolving https://github.com/apple/swift-nio-ssl.git at 1.2.0
warning: 'fetch' command is deprecated; use 'resolve' instead
Fetching Dependencies [Done]
Building Project ...
Building Project [Done]

`openssl version`
OpenSSL 1.0.2p  14 Aug 2018

`locate libssl | grep usr`
WARNING: The locate database (/var/db/locate.database) does not exist.
To create the database, run the following command:

  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

Please be aware that the database can take some time to generate; once
the database has been created, this message will no longer appear.

*after following the instructions and running again...*

/usr/lib/libssl.0.9.7.dylib
/usr/lib/libssl.0.9.8.dylib
/usr/lib/libssl.35.dylib
/usr/lib/libssl.43.dylib
/usr/lib/libssl.dylib
/usr/local/Cellar/libressl/2.7.2/lib/libssl.45.dylib
/usr/local/Cellar/libressl/2.7.2/lib/libssl.a
/usr/local/Cellar/libressl/2.7.2/lib/libssl.dylib
/usr/local/Cellar/libressl/2.7.2/lib/pkgconfig/libssl.pc
/usr/local/Cellar/libressl/2.7.4/lib/libssl.45.dylib
/usr/local/Cellar/libressl/2.7.4/lib/libssl.a
/usr/local/Cellar/libressl/2.7.4/lib/libssl.dylib
/usr/local/Cellar/libressl/2.7.4/lib/pkgconfig/libssl.pc
/usr/local/Cellar/openssl/1.0.2k/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2k/lib/libssl.a
/usr/local/Cellar/openssl/1.0.2k/lib/libssl.dylib
/usr/local/Cellar/openssl/1.0.2k/lib/pkgconfig/libssl.pc
/usr/local/Cellar/openssl/1.0.2l/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2l/lib/libssl.a
/usr/local/Cellar/openssl/1.0.2l/lib/libssl.dylib
/usr/local/Cellar/openssl/1.0.2l/lib/pkgconfig/libssl.pc
/usr/local/Cellar/openssl/1.0.2m/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2m/lib/libssl.a
/usr/local/Cellar/openssl/1.0.2m/lib/libssl.dylib
/usr/local/Cellar/openssl/1.0.2m/lib/pkgconfig/libssl.pc
/usr/local/Cellar/openssl/1.0.2o_1/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2o_1/lib/libssl.a
/usr/local/Cellar/openssl/1.0.2o_1/lib/libssl.dylib
/usr/local/Cellar/openssl/1.0.2o_1/lib/pkgconfig/libssl.pc
/usr/local/Cellar/openssl/1.0.2p/lib/libssl.1.0.0.dylib
/usr/local/Cellar/openssl/1.0.2p/lib/libssl.a
/usr/local/Cellar/openssl/1.0.2p/lib/libssl.dylib
/usr/local/Cellar/openssl/1.0.2p/lib/pkgconfig/libssl.pc

`locate xcconfig`
/Applications/Xcode.app/Contents/Developer/Library/Xcode/Templates/File Templates/Other/Configuration Settings File.xctemplate/___FILEBASENAME___.xcconfig
/Applications/Xcode.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/Library/PrivateFrameworks/DVTFoundation.framework/xcconfig.xclangspec
/Applications/Xcode.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/Library/PrivateFrameworks/DVTFoundation.framework/xcconfig.xclangspec
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/DVTFoundation.framework/xcconfig.xclangspec
/Applications/Xcode.app/Contents/PlugIns/Xcode3UI.ideplugin/Contents/Resources/com.apple.dt.Xcode3ProjectSupport.icon.xcconfigfile.icns
/Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/Resources/xcconfig.xclangspec

**Comment by grundoon** [comment]
Okay, so there are no conflicting `xcconfig`s and your build looks fine – do you now have a `.build/debug/Run` executable, or are we still stuck on that part?

I *am* disturbed that `openssl version` reports an actual openssl as opposed to the system default LibreSSL 2.2.7. Not sure if that's an issue.

(also, you may want to introduce yourself to the `brew cleanup [-n]` command to weed out those older versions 🙂)

**Comment by dillonfagan** [comment]
Wow I had no idea Homebrew saved older versions. Thanks a ton for pointing that out!

I do not have a `.build/debug/Run` executable, even after running `vapor build`.

I remember back when I first installed Vapor (1.x) that I was having trouble with the original LibreSSL and ended up installing OpenSSL. I could look into changing it back and seeing if this changes anything.

**Comment by Gusont** [comment]
maybe you Xcode Rename

**Comment by dbystruev** [comment]
Had similar problem, xcode-select helped:

$ sudo xcode-select -switch /Applications/Xcode.app/
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by lehaxe** [comment]
> Была похожая проблема, помог xcode-select:
> 
> $ sudo xcode-select -switch /Applications/Xcode.app/
> $ xcode-select -p
> /Applications/Xcode.app/Contents/Developer

thanx, it works!
