### ISSUE TITLE
Vapor rebuilds everything every time

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#1793]
When I do a `vapor build --release` it appears that it's having to recompile every source file every single time.  On my Ubuntu 16.0.4 system the last build took 10 minutes.

### Steps to reproduce

vapor build --release --verbose --run

### Expected behavior

Should leave the existing compiled pieces around like a Makefile building a .c into a .o

### Actual behavior

Long compile time.

### Environment

* Vapor Framework version: 3.0.8
* Vapor Toolbox version: 3.1.6
* OS version: Ubuntu 16.0.4

**Comment by vzsg** [comment]
`vapor build` doesn't actually do anything special, it just calls the Swift's `swift build` command.

**Comment by tanner0101** [comment]
@grosch which `swift` version are you running? There were some issues w/ early SPM builds (esp on Linux) that would not properly cache builds. AFAIK, these have all been resolved quite for a while now though. Either way, as @vzsg mentioned `vapor build` just calls `swift build`, so this is likely a bug with Swift / SPM and not the toolbox.

**Comment by tanner0101** [comment]
Furthermore, this issue would be more relevant if opened here: https://github.com/vapor/toolbox
