### ISSUE TITLE
Vapor Ubunutu APT: 'swift' --> 'swiftlang'

### ISSUE THREAD

**Issue by marc-medley** [vapor/vapor#1795]
**Proposal**

Update Vapor's Linux APT repo script to use `swiftlang` instead of `swift` as the package name.

**Rational**

(1) An Ubuntu package named `swift` is **_already in use_** for the OpenStack Object Store project named "Swift".  The OpenStack Object Store project named "Swift" has a commit history which started August 2010 and remains in active development.

See: [Stackalytics: Swift](http://stackalytics.com/?release=all&module=swift-group&metric=commits), [GitHub openstack/swift](https://github.com/openstack/swift/graphs/contributors), and [Ubuntu Packages search: swift](https://packages.ubuntu.com/bionic/swift)

(2) `swiftlang` is **_unambiguous_** at this time. `swift` is already has significant use the [Unbuntu packages repo](https://packages.ubuntu.com/search?keywords=swift&searchon=names).

``` bash
sudo apt-cache policy swift+

# gnome-speech-swift
# golang-github-ncw-swift-dev
# libphp-swiftmailer
# php-swiftmailer
# php-symfony-swiftmailer-bridge
# puppet-module-swift
# python-backup2swift
# python-swift
# python-swiftclient-doc
# python-swiftclient
# python-swiftsc
# python2.7-backup2swift
# python2.7-swift
# python2.7-swiftsc
# python3-backup2swift
# python3-swiftclient
# python3-swiftsc
# swift (OpenStack Object Store project)
# swift-account
# swift-bench
# swift-container
# swift-doc
# swift-object-expirer
# swift-object
# swift-plugin-s3
# swift-proxy
```

(3) `swiftlang` can be used as a **_unique base name_** and **_unique name component_**.

For example, use `swiftlang` for a stable GM install e.g. version 4.1, and `swiftlang-dev` for early adopters & developers e.g. version 4.2 development branch, etc.

```
swift         // existing
swift-account // existing
swift-doc     // existing
swift-lang    // unused, but buried in swift-... list
swift-...     // many existing swift-...
swiftlang     // not currently used, separates from swift-... list
swiftlang-dev // not currently used, separates from swift-... list
```

`swiftlang` is currently _not_ currently used within any Ubuntu package name. see [Ubuntu Packages search: swiftlang](https://packages.ubuntu.com/search?keywords=swiftlang&searchon=names&suite=all&section=all).  

**Side Notes**

A. `sudo apt-cache show vapor+` and [Ubuntu Packages search](https://packages.ubuntu.com/search?keywords=vapor&searchon=names) indicate that vapor is not currently in use as a package name for the standard Ubuntu APT channel. 

B. A `vapor-dev` package or similar (in addition to a `vapor`) might be convenient for early adopters and developer.

**Change Locations**

1. /Utilities/apt.sh (this repository)
2. apt script deployment: [https://apt.vapor.sh](https://apt.vapor.sh), and related artifacts
3. docs: [https://docs.vapor.codes/3.0/install/ubuntu/](https://docs.vapor.codes/3.0/install/ubuntu/)

**Updated/Amended**

_`swift-language` was replaced with `swiftlang` based on feedback comments and that `swiftlang` is a better fit with the rational. Both `swift-language` and `swift-lang` share the base prefix `swift-` which has already significant use. Also, `language` more typically refers to spoken languages in the context of Linux packages._

**Comment by joscdk** [comment]
Hi @marc-medley 

This did come up when we first decided to make an APT repository, but to be honest, if we should rename i think `swift-language` is a bit too long, one of the original ideas that was up was `swiftlang`/`swift-lang` (To copy Go)

This is a discussion at a larger plan, @tanner0101 @LoganWright anything you want to pitch in with

**Comment by marc-medley** [comment]
@joscdk Good point. Noting that `swiftlang` would also be a unique prefix name relative to the currently available [Ubuntu Packages](https://packages.ubuntu.com/search?keywords=swiftlang&searchon=names).

**Comment by vzsg** [comment]
The `-language` suffix doesn't seem to be used in this context by any other packages. If anything, this is a `-dev` package as it contains the complete toolchain and development files next to the runtime libraries.

**Comment by joscdk** [comment]
@LoganWright There shouldn't be any problems with adding `-lang` to the APT. Only in terms of backwards compatibility, so people would need to do:

```
apt-get update
apt-get purge swift
apt-get install swift-lang
```
So it should be done when we push a new release, e.g. 4.2 so all that want to update to 4.2 should do as above, and keep all old versions as is for now, not to break CI systems etc.

**Comment by tanner0101** [comment]
I like this proposal. +1 for `swiftlang` and `swiftlang-dev`.

**Comment by marc-medley** [comment]
`swiftlang` has a clear separation from the OpenStack Object Store "swift" APT packages.

On the other hand, `swift-lang` is similar to _existing_ OpenStack Object Store "swift-" package names such as `swift-doc` and `swift-bench`. Ubuntu user's could be left to wonder:

* "Is `swift-lang` yet another component for OpenStack Swift?" (nope.) 
* "Are `swift-doc` and `swift-bench` related to Apple's open sourced Swift language?" (they're not.)

Currently, `swiftlang` is [completing unused in the Ubuntu Packages](https://packages.ubuntu.com/search?keywords=swiftlang&searchon=names).


```
swiftlang
swiftlang-dev
swiftlang-doc (not proposing any docs, just shows another potential use example)
```

**Comment by marc-medley** [comment]
Independent of a choice for supporting `apt` vs `snap` vs  both `apt` & `snap`,  the names 'swiftlang' and 'vapor' is currently clear in both namespaces.

At this time:
* `swiftlang` and `vapor` are [unused in https://snapcraft.io/store](https://snapcraft.io/search?category=&q=swiftlang)
* `swiftlang` and `vapor` are [unused in the Ubuntu Packages](https://packages.ubuntu.com/search?keywords=swiftlang&searchon=names).

For `snap`, a long term 'project visibility' benefit might be see if a listed presence under _"Take 15 minutes to publish your first snap. What **language** or **framework** does your app use?"_ on the https://snapcraft.io home page is possible.

**Comment by joscdk** [comment]
@marc-medley i am closing this issue, as i have tried to make a new issue with some changes, including this :) https://github.com/vapor/vapor/issues/1857
