### ISSUE TITLE
Add a WebFlux type functionality to do reactive behaviour over HTTP like SpringBoot

### ISSUE THREAD

**Issue by 00benallen** [vapor/vapor#1798]
Hey vapor developers, I'm working on a Reactive Streams implementation in Swift over at https://github.com/00benallen/reactive-streams-swift. When this is merged into the reactive streams organization, I think it could be pulled in as an SPM dependency and used to create the `Flux` and `Mono` types implemented by SpringBoot and allow reactive streaming over HTTP. 

See: https://spring.io/guides/gs/reactive-rest-service/

I'd like to help with this, but I'd love some feedback on this first!

**Comment by LoganWright** [comment]
Can you give us a bit more information about what this would do and how it might be useful! We've got pretty full plates at the moment, but the community might be interested in a project like this. 

As always, lots of people available in Discord to help hash out the details with you @ vapor.team

**Comment by 00benallen** [comment]
I think the best way to explain it would be to read up on the Spring Boot implementation of this.

But basically, it means you can return ReactiveX style objects over HTTP, allowing a vapour web service to return multiple asynchronous results back to a calling application in a non-blocking way from a single request.

**Comment by LoganWright** [comment]
The only HTTP methods I'm aware of that can return multiple responses are a special HTTP system called Server send events which is more or less deprecated for web sockets.

I'm sure a community wrapper could be integrated w/ sockets if there's a special desired syntax, for now, we'll recommend WebSockets for multiple server send events unless there's a compelling feature we can't achieve with them.

Let us know if you need help setting them up, thanks for the suggestions 🙌
