### ISSUE TITLE
Possible to integrate a JavaScript engine into Vapor for server-side React/Vue rendering?

### ISSUE THREAD

**Issue by markmals** [vapor/vapor#1800]
This may be too far outside of the scope of this project, and feel free to close this if it is, but I was wondering if it might be possible to add a JavaScript engine (and/or JS bindings) to Vapor. Specifically, this would allow developers to render view frameworks, like React and Vue, on the server. This would allow developers to write their main app logic in Swift and their view logic in the latest-and-greatest JavaScript framework, while being able to take advantage of the speed (and other) benefits of server-side view rendering.

I imagine this could be implemented similarly to [NodeKit](https://github.com/nodekit-io/nodekit), with a Node-like abstraction layer on top of different platforms' native engines (JavaScriptCore on macOS and [Linux](https://webkitgtk.org/), [ChakraCore](https://github.com/nodejs/node-chakracore) if you plan to support Windows, etc.).

The other option I considered for server-side rendering would be a native Swift framework to parse and render such view frameworks, but this seems immensely more difficult, especially considering the ever-changing nature of such frameworks.

**Comment by joscdk** [comment]
To be honest, i don't think there are plans to make any official packages like this. But community packages are of cause always welcome.
A lot of usecases can be handled by Leaf, and it's sort of the direction we have focused on.

For implementing VueJS for example, it's always possible to make a separate Vue app, and have it call API endpoints in your Vapor project, this is a solution we are using, and i would personally also suggest that.

**Comment by markmals** [comment]
> But community packages are of cause always welcome.

I guess I'm a bit naive on the capabilities on SPM, but would it be possible to bundle the JavaScript and C/C++ code likely needed to make this work along with the Swift code in an SPM package? If so, a community package sounds like the way to go.

> it's always possible to make a separate Vue app, and have it call API endpoints in your Vapor project, this is a solution we are using, and i would personally also suggest that.

Yes, but this still uses client-side JavaScript to render the Vue app, correct? That's something I'd like to avoid [for multiple reasons](https://ssr.vuejs.org/#why-ssr). If I could render the Vue views on the server, alongside/with my Vapor project instead of having to go back to using Express, that would be fantastic.

**Comment by markmals** [comment]
[Something like this](https://github.com/reactjs/React.NET) is what I was thinking of. Worth noting that there's also a [JavaScriptCore wrapper for Swift Package Manager](https://github.com/ptmt/cjsc) available that works on Linux as well, (with the compiler flag `-Xcc -I/usr/include/webkitgtk-3.0`).
