### ISSUE TITLE
Can't post the JSON data with multiple key values

### ISSUE THREAD

**Issue by sankarsubramanian** [vapor/vapor#1802]
Trying to send the below JSON data in POST request. But not able to create the Content structure for the below one since Content is not accepting Any / AnyObject data type
<code>
{
"notification":
{
"subscriptions":
[
     {
       "Id":"111",
        "notification":[
          {
           "type":"type",
           "Status":"done"
           } 
         ]
       },
       {
         "Id":"222",
        "notification":[
          {
           "type":"type",
           "Status":"error"
           } 
         ]
       }
}
}
</code>

* Vapor Framework version: 3.0.8
* Vapor Toolbox version: 3.1.7
* OS version: 10.13.6

**Comment by grundoon** [comment]
Maybe just a typo, but you're missing a closing `]` between the 2nd and 3rd from last `}` (for the "subscriptions" array).

**Comment by vzsg** [comment]
What does Any have to do with writing a Codable model for this JSON?

```
struct SomeRequest: Content {
    let notification: NotificationStatus
}

struct NotificationStatus: Content {
    let subscriptions: [Subscription]
}

struct Subscription: Content {
    let id: String
    let notifications: [Notification]

    private enum CodingKeys: String, CodingKey {
        case id = "Id"
        case notifications = "notification"
    }
}

struct Notification: Content {
    let type: String
    let status: String

    private enum CodingKeys: String, CodingKey {
        case type
        case status = "Status"
    }
}
```

This should work just fine without any Any trickery.

---

BTW, these mixed lowercase-uppercase keys are pretty ugly. Maybe you could stick to one style instead?

**Comment by LoganWright** [comment]
We can reopen this if the above solutions don't work. Also feel free to hop in our Discord to get help working through this. 👍

**Comment by sankarsubramanian** [comment]
Thank you @vzsg The solution works
