### ISSUE TITLE
Impossible to set Abort properties

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#1804]
It's impossible to set some of the `Abort` struct attributes.

- possibleCauses
- suggestedFixes
- documentationLinks
- stackOverflowQuestions
- gitHubIssues

They are inherited from `Debuggable`, but they are not defined in `Abort.init` nor as `var`.

**Comment by LoganWright** [comment]
Abort doesn't actually have most of those fields on the model we use internally. We'll discuss internally adding those fields, but for now, it'd probably be a quick fix to create an error object you'd like to use and fill out those fields.

Let us know if you come up with something you think might be useful to others!

Thanks for participating 👍

**Comment by tanner0101** [comment]
There is `suggestedFixes` actually, but I don't think it would be a bad idea to add the rest. Would you want to PR that @valeriomazzeo?

**Comment by valeriomazzeo** [comment]
@tanner0101 I am caught into something else at the moment, please be free to add that as it's an easy change.

My point was that `Abort` conforms to `Debuggable`, therefore it does have those properties.
What it doesn't have it's a way set those, as they are automatically synthesised as `read-only`.

Also note that `StackTrace` being optional, collides with the definition in `Debuggable` so it would good perhaps to consolidate that too.

**Comment by JovanMilenkovic** [comment]
I would like to see a custom error format being an option. I could offer a solution if including AnyEncodable in vapor is acceptable.

**Comment by JovanMilenkovic** [comment]
Well a custom error format isn't currently provided. Debuggable conformance would offer additional info, but the fields are static and have the names that they have. If a team was deciding on error response standard they could decide on a format
{
    "key1": "text",
    "key2": {
                     "internalKey1": "text",
                     "internalKey2": "more text
                 },
    "key3": ......
    ...............
    ...............
}
but a developer would not be able to model this and use ErrorMiddleware. I'm thinking this would be nice if this was an available feature.
As far as implementation goes, I haven't found a better solution other than introducing AnyEncodable type. I would like to see a way of implementing this without AnyEncodable, and if that's not possible a decision needs to be made if it's worth introducing it for this feature or not. I personally am not sure if it tips the scale or not.

**Comment by valeriomazzeo** [comment]
@JovanMilenkovic is not provided out of the box, but it's not difficult to implement either. 
For example, I am catching errors in my own `JSONAPI.ErrorMiddleware` and I am converting them to my `JSONAPI.Error` type. The main purpose of this is to provide a different kind of serialisation (which in this case conforms to the `JSONAPI` standard).

If I understood correctly, you are asking for a generic interface in `Vapor.ErrorMiddleware` in order to support a generic `Swift.Error` type?

**Comment by JovanMilenkovic** [comment]
I think adding these fields does not bring real value, and being able to define you own error model that would be caught by default ErrorMiddleware bring much more. Generic as in <MyError> is not possible as far as i know, that’s why I was mentioning AnyEncodable

**Comment by JovanMilenkovic** [comment]
I have made a pull request that should better explain the idea I had, and allow better thoughts sharing with comments. https://github.com/vapor/vapor/pull/1821/commits/6530ce1428ed4ce8b91826b7bd600659ca68e0f2
@tanner0101 @LoganWright @valeriomazzeo

**Comment by kaioser** [comment]
suggestedFixes property still not used in Abort init method, is that on purpose? from vapor 4

**Comment by 0xTim** [comment]
@kaioser `suggestedFixes` is not a property in Vapor 4 anymore
