### ISSUE TITLE
Ambiguous reference to member 'post(_:at:use:)'

### ISSUE THREAD

**Issue by kylebmai** [vapor/vapor#1805]
Brand new install from "brew install vapor/tap/vapor"

Open the app in xcode, test compile as is -> everything is fine.

So I tried to create a POST route:

`    router.post("test") { req in
        print("test")
        return "test"
    }
`

If I remove `print("test")` it compile fine. If it add `print("test")` back, it gives me error 

`Ambiguous reference to member 'post(_:at:use:)'`

Please help!!!

* Vapor Framework version: 3.0.8
* Vapor Toolbox version: 3.1.10
* OS version: MacOS High Sierra 10.13.6
* Xcode version: 9.4.1

**Comment by joscdk** [comment]
Sometimes the Swift compiler need a bit of help, if you define the return value, it should work.. Like this

```swift
router.post("test") { req -> String in
    print("test")
    return "test"  
}
```
