### ISSUE TITLE
Websocket keepalive

### ISSUE THREAD

**Issue by guarland** [vapor/vapor#1806]
I've recently set-up a Vapor WebSocket server which works fine, however I'm having a few troubles understanding how I should handle a sudden loss of connection which the client intentionally initiated,  i.e: client loses power, ethernet cables pulled out etc...

code like this 

`        ws.onClose.always {
            print("websocket disconnected -->"  cChannel)
            con.close()
        }`

**Comment by LoganWright** [comment]
Hey @guarland,

Is there something that's not working as expected in the code you listed here?

**Comment by LoganWright** [comment]
The code listed above should be appropriate handlers, if you're seeing that these handlers have begun failing in some way, please reopen the issue with a bug and repro steps and we'll go from there!

As always, there's lots of help available in Discord 😄

**Comment by guarland** [comment]
@LoganWright  this code works fine, but vapor websocket doesn't have keep alive, when the Internet is terminated, close handler never called, i had to implement myself websocket keepalive
