### ISSUE TITLE
issue in vapor2 " The request timed out."

### ISSUE THREAD

**Issue by siempay** [vapor/vapor#1808]
getting this error as a response from my app:
```Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x1c0e47500 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=http://cerises.precision.ma//caissiers/Stock/Magasin/1/Device/45, NSErrorFailingURLKey=http://cerises.precision.ma//caissiers/Stock/Magasin/1/Device/45, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.}```

I have an ios app that call to an api (made in vapor 2) , but sometimes I get "The request timed out." as a response and when I check the logs of my api I see this :
`Identifier: Sockets.SocketsError.writeFailed)
 Server error: dispatch(Sockets Error: Failed to write from socket`

### Steps to reproduce
I really dont know how reproduce it cause I dont know what part of my code caused it! 
but it happens most of the time in a specific route, where I have `database.transtion(...`
it is very long and it just dose insert/update models to database.

### Expected behavior
return a response with a json object

### Actual behavior
  The request timed out

### Environment

 vapor --version
Vapor Toolbox: 3.1.4
Vapor Framework: 2.4.4
developed on macos 10.13.6 
deployed on ubuntu 16.04
Apple Swift version 4.1.2

**Comment by LoganWright** [comment]
@siempay some troubleshooting:

- are other connections to the database functioning?
- if you make an identical transaction not triggered from iOS, does it clear?
- are other routes connecting and returning from iOS?

**Comment by MrLotU** [comment]
As of November 2018 Vapor 2 is no longer supported. Closing this issue. [Version support](https://docs.vapor.codes/3.0/version/support/)
