### ISSUE TITLE
Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by retendo** [vapor/vapor#1811]
Now that Swift 4.2 is out, including Ubuntu 18.04 support, I just wanted to know if this is on your agenda.

**Comment by LoganWright** [comment]
hahaha, @retendo you _know_ it is ;)

We'll have full support for everything ASAP and likely works already. With new systems there's always a possibility of bugs, let us know if you spot something.

**Comment by makoni** [comment]
There's issue with template on Ubuntu 18.04: https://github.com/vapor/template-kit/issues/39
