### ISSUE TITLE
Vapor3 heroku error with @testable module

### ISSUE THREAD

**Issue by sankarsubramanian** [vapor/vapor#1815]
Getting the below error while push the code in heroku as "module was not compiled for @testable module"

**remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Requests/HTTPRequest+Response.swift:8:29: error: module 'NIO' was not compiled for testing
remote: @_exported @testable import NIO
remote:                             ^
remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Response tools/Response+Checks.swift:7:18: error: module 'Vapor' was not compiled for testing
remote: @testable import Vapor
remote:                  ^
remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Response tools/Response+Checks.swift:8:18: error: module 'NIO' was not compiled for testing
remote: @testable import NIO
remote:                  ^
remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Response tools/Response+Debug.swift:7:18: error: module 'Vapor' was not compiled for testing
remote: @testable import Vapor
remote:                  ^
remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Response tools/Response+Getters.swift:7:18: error: module 'Vapor' was not compiled for testing
remote: @testable import Vapor
remote:                  ^
remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Response tools/Response+Getters.swift:8:18: error: module 'NIO' was not compiled for testing
remote: @testable import NIO
remote:                  ^
remote: /tmp/build_91c77ab363ae841e9fdf43635a9892d3/Sources/VaporTestTools/Extensions/Services/Services+Testing.swift:7:18: error: module 'Service' was not compiled for testing
remote: @testable import Service
remote:                  ^
remote: error: terminated(1): /app/tmp/cache/heroku-16/swiftenv/versions/4.1.2/usr/bin/swift-build-tool -f /app/tmp/cache/.build/release.yaml main output:**
### Actual behavior

- Able to host the app in heroku without the @testable module

### Environment

* Vapor Framework version: 3.0.8
* Vapor Toolbox version: 3.1.0
* OS version: heroku stack is "heroku-16"
* Swift-version: 4.1.2

**Comment by vzsg** [comment]
Which buildpack are you trying to use?

**Comment by sankarsubramanian** [comment]
@vzsg I am using the vapor-community buildpack
https://github.com/vapor-community/heroku-buildpack

**Comment by vzsg** [comment]
I find it really unusual that VaporTestTools is compiled. The buildpack does not run tests, and projects typically don't import that module. Can you upload your Package.swift file?

**Comment by sankarsubramanian** [comment]
Since the testing is required in development, can we configure package.json for development and deployment.
My package.json is 
`import PackageDescription

let package = Package(
    name: "swift-server",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.8"),
    ],
    targets: [
        .target(name: "App", dependencies: ["Vapor"]),
        .target(name: "VaporTestTools", dependencies: ["Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App", "VaporTestTools"])
    ]
)`

**Comment by vzsg** [comment]
Wait, I just realized that VaporTestTools is not part of the project. 🤦‍♂️ 

So the question is, what is that, and why does it try to use `@testable` imports of unrelated packages?

**Comment by sankarsubramanian** [comment]
yes. I am trying to do some unit test for my API's implemented in controllers. so trying to use this package.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
