### ISSUE TITLE
can't git push heroku master 

### ISSUE THREAD

**Issue by DrunkardSworder** [vapor/vapor#1818]
### Steps to reproduce

emote: Building Swift
remote: This may take a very long time...
remote: Building Swift failed
remote: Check out the logfile for more information: /app/tmp/cache/swiftenv/tmp/swiftenv-build-4.1/swiftenv-build.20180921000030.264.log
remote: You can inspect or delete the working tree at: /app/tmp/cache/swiftenv/tmp/swiftenv-build-4.1
remote:  !     Push rejected, failed to compile Swift app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to tranquil-eyrie-93605.
remote:

### Expected behavior

first,I init by 'vapor heroku init', but error 
then, I create Procfile and .swift-version, config buildpack 'https://github.com/kylef/heroku-buildpack-swift.git'
and 'git push hero master'
,but like this

### Environment

* Vapor Framework version:3.0.8
* Vapor Toolbox version:3.1.10
* OS version:

**Comment by walkabout1** [comment]
I have the same problem. How did you solve this?

**Comment by vzsg** [comment]
If you switch to our buildpack, you'll get more detailed logs.

```
heroku buildpacks:set https://github.com/vapor-community/heroku-buildpack.git
```
