### ISSUE TITLE
add `userInfo` to Request and Response

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1822]
This would be an alternative to using `privateContainer` for storing data on a request or response. It's likely that request and response will no longer contain references to containers in a future version of Vapor (see #1711 for more info). Adding the `userInfo` dictionary now as a minor addition could help make the transition of removing container from request easier.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
