### ISSUE TITLE
Vapor 2.4.5 doesn't compile with Swift 4.2 (Ubuntu)

### ISSUE THREAD

**Issue by makoni** [vapor/vapor#1823]
### Steps to reproduce

Try to compile Vapor 2.4.5 with Swift 4.2 on Ubuntu (I Used 18.04). Also tried with Circle CI with Swift 4.2 (not sure which OS version was there).
### Expected behavior
Compiling

### Actual behavior
`1.	While emitting IR SIL function "@$S4Leaf15ParameterParser33_A7F42E4543F0554FB21DD60439F88E99LLC6BufferC14skipWhitespaceyyKF".
 for 'skipWhitespace()' at /root/project/.build/checkouts/leaf.git-1516294132501686698/Sources/Leaf/Buffer/Buffer+Leaf.swift:305:9
<unknown>:0: error: unable to execute command: Aborted
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
error: terminated(1): /usr/bin/swift-build-tool -f /root/project/.build/release.yaml main output:`

### Environment

* Vapor Framework version: 2.4.5
* Vapor Toolbox version: 
* OS version: Ubuntu 18.04

The issue is related to skipWhitespace function.

**Comment by selipso** [comment]
For me the download script itself is not working on 18.04

**Comment by MrLotU** [comment]
As of November 2018 Vapor 2 is no longer supported. Closing this issue. [Version support](https://docs.vapor.codes/3.0/version/support/)
