### ISSUE TITLE
Cannot list organizations or cloud deploy

### ISSUE THREAD

**Issue by JWShroyer** [vapor/vapor#1826]
I'm running into an issue where running the following vapor toolbox command is resulting in an error:

`vapor cloud list`

When it asks me to select from Organizations, Project, Applications, or Domains, I select Organizations and am met with the following error:

> Fetching Organizations [Failed]
Error: Node Error: No converters found for type ModelOrIdentifier<Wallet>
>
>Identifier: Node.NodeError.noFuzzyConverter
>
>Here are some possible causes: 
> - You have not properly set the Node.fuzzy array
>
>These suggestions could address the issue: 
> - Conform ModelOrIdentifier<Wallet> to Node

The above error is also observed when running the `vapor cloud deploy` command when trying to set up my first project.

### Steps to reproduce

The only thing that I do to observe the issue is to run `vapor cloud list` and select the organizations from the list.

### Expected behavior

I expect to be shown the list of organizations or none if there are none like the other options do.

### Actual behavior

I receive the error message instead of it completing and I cannot do a `vapor cloud deploy`.

### Environment

I have one organization and no projects, applications, or domains.

Vapor Toolbox: 3.1.10
Vapor Framework: 3.0.8
macOS Mojave Version 10.14 (18A391)

**Comment by JWShroyer** [comment]
I was able to fix the problem by deleting the organization on the web portal and remaking it.

**Comment by backslash-f** [comment]
This is still an issue for me (couldn't fix by deleting the organization and recreating it):

```
$ vapor cloud list
Fetching Organizations [Failed]
Error: Node Error: No converters found for type ModelOrIdentifier<Wallet>

Identifier: Node.NodeError.noFuzzyConverter

Here are some possible causes: 
- You have not properly set the Node.fuzzy array

These suggestions could address the issue: 
- Conform ModelOrIdentifier<Wallet> to Node
```

¯\_(ツ)_/¯ 

```
$ vapor --version
Vapor Toolbox: 3.1.10
```

**Comment by joscdk** [comment]
@backslash-f hmm yeah that error comes from time to time unfortunately.

I would try deleting the wallet on the organization and creating a new one, that should remove that error.

**Comment by MrLotU** [comment]
With Vapor 4 in Beta and no discussion for over a few months, I'm closing this issue. Feel free to re-open if there are still questions/issues unanswered.
