### ISSUE TITLE
Hello World project crashes immediately

### ISSUE THREAD

**Issue by domagojstankovic** [vapor/vapor#1828]
Hello World project crashes immediately after running Run scheme.

### Steps to reproduce

Follow all the steps from docs: https://docs.vapor.codes/3.0/install/macos/

### Expected behavior

Should run without crashing and http://localhost:8080/hello should open without errors.

### Actual behavior

I get a fatal error on launch:
```
[ INFO ] Migrating 'sqlite' database (/Users/dstankovic/Code/Swift/vapor/Hello/.build/checkouts/fluent.git--3386251611263004497/Sources/Fluent/Migration/MigrationConfig.swift:69)
[ INFO ] Preparing migration 'Todo' (/Users/dstankovic/Code/Swift/vapor/Hello/.build/checkouts/fluent.git--3386251611263004497/Sources/Fluent/Migration/Migrations.swift:111)
[ INFO ] Migrations complete (/Users/dstankovic/Code/Swift/vapor/Hello/.build/checkouts/fluent.git--3386251611263004497/Sources/Fluent/Migration/MigrationConfig.swift:73)
Running default command: /Users/dstankovic/Library/Developer/Xcode/DerivedData/Hello-ejxvhmdnzoacrkghdaljdtogjfxm/Build/Products/Debug/Run serve
Server starting on http://localhost:8080
Fatal error: Error raised at top level: NIO.SocketAddressError.unknown(host: "localhost", port: 8080): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.37.1/src/swift/stdlib/public/core/ErrorType.swift, line 191
2018-10-07 23:50:39.661100+0200 Run[27765:751178] Fatal error: Error raised at top level: NIO.SocketAddressError.unknown(host: "localhost", port: 8080): file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.37.1/src/swift/stdlib/public/core/ErrorType.swift, line 191
```

![screen shot 2018-10-07 at 11 56 12 pm](https://user-images.githubusercontent.com/5526170/46587441-a5c23300-ca8c-11e8-9472-8f4df908168f.png)

### Environment

* Vapor Framework version: 3.1.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS High Sierra 10.13.6 (17G65)

**Comment by vzsg** [comment]
Can you check your /etc/hosts file? The error kind of suggests that the default entries were removed.

This is what it should look like, at minimum:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

**Comment by domagojstankovic** [comment]
It was empty! I added the snippet above and it's working. Thanks :)

**Comment by suhazinwi** [comment]
I have this exact same problem and my /etc/hosts file looks like the sample shown. Any help would be appreciated?

**Comment by vzsg** [comment]
Are you sure it's the exact same error?

Particularly, this message?

> NIO.SocketAddressError.unknown(host: "localhost", port: 8080)
