### ISSUE TITLE
Segmentation fault when running Vapor 2.4.5 on linux in release configuration

### ISSUE THREAD

**Issue by dlbuckley** [vapor/vapor#1829]
We have been adopting Swift 4.2 throughout our codebase and thought we were done until we tried to run it in release configuration. As soon as we ran it we hit a `Segmentation fault` which happens 19 out of 20 times.

In our effort to locate the issue we created a brand new Vapor 2.4.5 template project and ran it in release configuration only to find the issue again without any of our code present. Due to the size of our project, updating to Vapor 3.X hasn't been an avenue we have been able to pursue just yet so we need to find a solution to whats happening on 2.4.5.

### Steps to reproduce

1) Create a new vapor 2.4.5 project with the API template
2) Open the project directory in docker using `docker run --rm -it --volume "$(pwd):/app" --workdir /app swift:4.2 /bin/bash`
3) Run `swift build -c release`
4) Run the newly created executable `./.build/x86_64-unknown-linux/release/Run` (or whatever your project is called)
5) Instantly get a `Segmentation fault`, or you might be lucky and the server will run, but just quit and try again and you will most likely hit the problem.

@vzsg looked into this and came up with a crash log that points towards a casting problem in the `customResolve` method in Config: https://gist.github.com/vzsg/46150bb4a3b95d59a3042dcfd4e7c6ee
@gwynne has just created a fantastic trace over on the runtime bug ticket I created on the swift bug tracker with exactly how to reproduce this issue: https://bugs.swift.org/browse/SR-8980

### Environment

* Vapor Framework version: 2.4.5
* Vapor toolbox: 3.1.10
* OS version: Ubuntu 16.04 (official docker container for Swift 4.2: https://hub.docker.com/r/_/swift/)

**Comment by valeriomazzeo** [comment]
Worth noticing that all the code that is being executed before crashing, is related to the `Config` module.

cc/ @tanner0101 @LoganWright

**Comment by tanner0101** [comment]
Looks to be coming from [here](https://github.com/vapor/vapor/blob/2.4.5/Sources/Vapor/Log/Config%2BLog.swift#L11) or [here](https://github.com/vapor/vapor/blob/2.4.5/Sources/Vapor/Commands/Config%2BConsole.swift#L13-L20).

I'm not really sure what we can do here short of refactoring a lot of that code to try and avoid hitting this Swift bug. :(

**Comment by MrLotU** [comment]
As of November 2018 Vapor 2 is no longer supported. Closing this issue. [Version support](https://docs.vapor.codes/3.0/version/support/)

**Comment by AmirHossein1372** [comment]
For me, the following code was generating "segmentation fault" error sometimes:
`print(error.localizedDescription) `
