### ISSUE TITLE
Vapor 3: FoundationClient caching issue

### ISSUE THREAD

**Issue by zdnk** [vapor/vapor#1831]
There is no possible way to control cache behavior of individual requests.
For more information refer to this issue: https://github.com/LiveUI/S3/issues/19

### Environment

Run framework project tests.

* Vapor Toolbox: 3.1.10
* Vapor Framework: 3.1.0
* OS version: macOS High Sierra

**Comment by tanner0101** [comment]
As mentioned in https://github.com/vapor/http/pull/292#issuecomment-434804373, I think the best way to do this is creating a one-off `FoundationClient` where the special cache policy is needed. There's a code example in the linked reply. 👍
