### ISSUE TITLE
merge Request and HTTPRequest

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1838]
Vapor currently has two, separate HTTP APIs. The lower level one, prefixed with `HTTP` comes from the [vapor/http](https://github.com/vapor/http) package. The higher level one, in Vapor itself, builds upon this and adds some conveniences. This issue proposes merging the HTTP-specific features from Vapor's higher level API into vapor/http to create one, unified API for working with HTTP.

*This idea is very much a work in progress, and any feedback you can give would be greatly appreciated!*

While these separate layers are integral to Vapor's design, their functionality overlaps in many places creating confusion. For example, it's not entirely clear whether a developer should use `Client` or `HTTPClient` for a given task. Should an API return `HTTPResponse` or `Response`? Should one use `HTTPServer` or `Server`? Each API has its own features and caveats that require special knowledge. 

This issue proposes fixing the problem by removing overlapping functionality where possible. Below is a list of specific action items:

- [ ] Remove `Client`, use `HTTPClient` instead. 

This is a fairly straight-forward change. Basically, remove Vapor's `Client` protocol and use either `HTTPClient` or `URLSession` instead. Vapor's `URLSession` conveniences should be changed to accept an `HTTPRequest` instead of a `Request`.

- [ ] add `req.content` and `req.query` encoding / decoding methods to `HTTPRequest`

Currently these convenience methods are on `Request` and can be configured via `ContentConfig`. These methods should be moved to `HTTPRequest`, and be configured by passing in custom coders. 

```swift
var req = HTTPRequest(method: .POST, path: "/planets")
try req.content.encode(earth)
// or
try req.content.encode(earth, using: customJSONEncoder)
let res = try HTTPClient.connect(to: "http://api.codes").wait().send(req).wait()
```

- [ ] add `get`, `post`, `send`, etc conveniences to `HTTPClient`.

These static convenience methods on `Client` work by creating a one-off connection, and sending a request. They can be added to `HTTPClient` to make this common use case easier.

- [ ] Rename `Request` to `HTTPRequestCtx` and add arbitrary data storage (`userInfo`)

A reference-type request wrapper is fundamental to Vapor's design. Things like middleware, parameters, sessions, etc make use of this reference wrapper to store information on incoming requests that can later be used in the route handler or when serializing an HTTP response.

- [ ] remove `container` from `Request` and use controllers instead 

With the addition of `userInfo` to `HTTPRequestCtx`, the container is no longer needed to store information for route closures or other middleware. With the ability to also store shared resources such as databases on controllers (see #1711), there will no longer be a need for access to a container from route closures. 

- [ ] delete `Response` type. 

Interaction with HTTP clients should be done using only `HTTPRequest` and `HTTPResponse` types. `HTTPRequestCtx` is a special case for incoming HTTP requests that will pass through Vapor's middleware and eventually end up in a route closure. There is no need for a reference-type HTTP response.

**Comment by calebkleveter** [comment]
I'm fairly certain there would be a way to build in the resolved parameter type to the component so we only need to do this:

```swift
router.get("users", .userID, "posts") { req -> String in
    let userID = try req.parameters.get(.userID)
    return userID.uuidString
}
```

I haven't played with it enough though.

**Comment by Joannis** [comment]
Closing this since Vapor 4 fixed this.
