### ISSUE TITLE
Handling not found error like others

### ISSUE THREAD

**Issue by code28** [vapor/vapor#1839]
I was writing my own error middleware, when I found, that a not existing route, i.e. a NotFound error, needs special treatment. When some error is thrown, the Future inside the middleware is a "FailedFuture". When the route wasn't found, it's a "SuccessFuture". Is this intended behaviour? If yes, why? For me, this feels strange to have different handlings for different errors.

The default ErrorMiddleware doesn't handle the NotFound error like the others btw. So usually, it prints a JSON, here it's only "Not found".

### Steps to reproduce

I'm talking about line (50 and) 51 in `ApplicationResponder.swift`: https://github.com/vapor/vapor/blob/5580743511c6645b46dc311662cfc272a781bbfb/Sources/Vapor/Response/ApplicationResponder.swift#L51

### Expected behavior

I'd expect:
```swift
return req.eventLoop.newFailedFuture(error: NotFound())
```

### Actual behavior

This is how it looks like now:
```swift
let res = req.response(http: .init(status: .notFound, body: "Not found"))
return req.eventLoop.newSucceededFuture(result: res)
```

### Environment

* Vapor Framework version: 3.1.0
* Vapor Toolbox version: 3.1.0
* OS version: macOS 14.1

**Comment by purkylin** [comment]
Should be failure
