### ISSUE TITLE
Package.swift warning

### ISSUE THREAD

**Issue by OHeroJ** [vapor/vapor#1846]
```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "Vapor",
    products: [
        .library(name: "Vapor", targets: ["Vapor"]),
    ],
    dependencie
   /// ....
```

`swift-tools-version:4.0` why not update to `swift-tools-version:4.2`？

my project has change  to 

```swift
// swift-tools-version:4.2
```
want all project to swift4.2

**But**

`vapor xcode -y` has get waning 

```
Swift Conversion
Conversion to Swift4.2 is avaliable 
``` 
tell third dependences.

**Comment by vzsg** [comment]
Officially Vapor 3.0/3.1 supports Swift 4.1 too. Upgrading the manifest to 4.2 would break that.
