### ISSUE TITLE
Vapor 3 SecTaskLoadEntitlements failed error on POST the HTTP form request

### ISSUE THREAD

**Issue by iandrosov** [vapor/vapor#1847]
This is a request for some documentation or code examples on Vapor 3.
I needed to HTTP POST a request with body parameters, simple thing. Search docs and examples but did not find a simple working code. 
Swift has examples using standard HTTP and Alamofire but that does not seem to work in Vapor. I was tryinng to use Vapor.Request but that only return SecTaskLoadEntitlements failed error=22 cs_flags=20

I try to add Alamofire to Vapor project and call Alamofire.request, but that gave no response. The method simply drops through no error response.

I have done that with older Vapor Droplet but Droplet no longer supported in Vapor 3
I have this process working in Java Spring and wanted to find a way to make that with Server Swift, any ideas or docs will be appreciated.

### Steps to reproduce
Here is code snippet I attempted to use on my  route function that did not work

func mycallback(_ req: Vapor.Request) throws -> String {
     let flags = try req.query.decode(SFAuthCode.self)
     let authCode = flags.code // Validated COde has correct value
 
     let urlString = "https://login.salesforce.com/services/oauth2/token"
     let tokenRequest = SFTokenRequest(grant_type: "authorization_code",
        client_id: "<MY CLIENT ID>",
        client_secret: "CLEINT SECRET",
        redirect_uri: "https://localhost:8080/sessiontoken",
        code: authCode!)

       let res = try req.client().post(urlString) { loginReq in
            // encode the loginRequest before sending
            try loginReq.content.encode(tokenRequest)
        }
     print(res)
     return "Hello, OAuth token"
}

### Expected behavior
I expected that:
let res = try req.client().post(urlString) ....
that res - will have a response with some JSON data but instead, it was just error

### Actual behavior
Vapor.Request but that only return SecTaskLoadEntitlements failed error=22 cs_flags=20

### Environment

* Vapor Framework version: 3.1.0
* Vapor Toolbox version: 3.1.7
* OS version: MacOS Mojave 10.14.1

**Comment by rbuencamino** [comment]
@tanner0101 is there any update on this? Seems to be a common problem when dealing with services like Google Firebase.

**Comment by 0xTim** [comment]
That POST example should work. You can do something like:

```swift
let futureResponse = try req.client().post(urlString) { request in
  // encode the loginRequest before sending
  try request.content.encode(someContent)
    }
```
You may also need to set headers etc to get things to work, like authorisation etc

**Comment by dougreid72** [comment]
I am getting a very similar message on web application talking to a vapor based REST API.   

```
      print("Get Org data by API")
        let organizationID = try! UUID(envOrganizationID())!
        let client = try! req.make(Client.self)
        let url = "http://localhost:8080/api/organizations/\(organizationID)"
        print("Org API URL: \(url)")
        let res = client.get(url).flatMap { orgResponse in
            //print(orgResponse.content)
            return try orgResponse.content.decode(Organization.self)
        }
        return res
```

Error messages:

2019-04-25 10:19:21.140809-0500 Run[3144:571110] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=3144
2019-04-25 10:19:21.140870-0500 Run[3144:571110] SecTaskCopyDebugDescription: Run[3144]/0#-1 LF=0

I do similar code for 2 other calls and they do not get the error messages.

**Comment by tanner0101** [comment]
Hmm... this must be coming from `URLSession`. I can't think of anything else here that would be using `Security.framework`. Might be worth reporting to bugs.swift.org.

**Comment by dougreid72** [comment]
I create a ticket at bugs.swift.org.
