### ISSUE TITLE
Chapter 5: Building vapor (release) [Failed], swift-build: error: rootManifestFileNotFound

### ISSUE THREAD

**Issue by MihranD** [vapor/vapor#1848]
I'm trying to build the same project as in Server-Side Swift book Chapter 5 described, but in the last step, when I want to deploy to vapor cloud, I'm receiving an error:

Building vapor (release) [Failed]
swift-build: error: rootManifestFileNotFound

### Steps to reproduce

I did all steps as described in the book Chapter 5 starting from "Deploying to Vapor Cloud".
I created a public repository in Github and tried with SSH and HTTPS urls:
git@github.com:MihranD/vapor-til.git
https://github.com/MihranD/vapor-til.git

This is the result when I'm trying to deploy:

Mihrans-MacBook-Pro-3:TILApp mdovlatyan$ vapor cloud deploy
app: TIL
git: https://github.com/MihranD/vapor-til.git
env: production
db: none
replicas: 1
replica size: free
branch: master
build: clean
Creating deployment [Done]
Connecting to build logs ...
Waiting in Queue [Done]
Starting deployment: 'slug-mihrando' [Done]
Getting project from Git 'https://github.com/MihranD/vapor-til.git' [Done]
Checkout branch 'master' [Done]
Verifying base folder [Done]
Selected swift version: 3.1.0 [Done]
Selected swift version: 3.1.0 [Done]
Building vapor (release) [Failed]
swift-build: error: rootManifestFileNotFound

Error: deploy failed.

### Expected behavior

Deployment should be succeeded.

### Actual behavior

Building vapor (release) [Failed]
swift-build: error: rootManifestFileNotFound

I'm running from folder, which contains Package.swift file.

### Environment

* Vapor Framework version: 3.1.10
* Vapor Toolbox version: 3.1.0
* OS version: macOS High Sierra 10.13.6

**Comment by grundoon** [comment]
Means a `Package.swift` file was not found in the current directory. Be sure to `cd` into your project directory before trying to build the project.

**Comment by grundoon** [comment]
Oops, sorry! Your repository `https://github.com/MihranD/vapor-til` is empty (just a file `test`) – have you pushed your project from your local machine onto GitHub?

**Comment by MihranD** [comment]
Yes! It works now. Thank you very much!
