### ISSUE TITLE
Slowness creating new project

### ISSUE THREAD

**Issue by rafsouzap** [vapor/vapor#1849]
* Vapor Toolbox version: 3.1.10
* OS: macOS
* OS version: 10.14.1

### Expected Behavior
Expected to scaffold a new Vapor application using the Vapor Toolkit as well as generating.

### Current Behavior
When executing the command to create a new Vapor project, the process stays forever in the step "Updating Package Name". In my last attempt it stayed in that stage by 1 hour and it did not advance.

### How to Reproduce
```
user@MBPro:~/Documents $ vapor new my-project
Cloning Template [Done]
Updating Package Name [   •                     ]

```

**Comment by gcox** [comment]
@rafsouzap So what was the solution? Waiting longer? Something else?

**Comment by gcox** [comment]
In case anyone else runs into this, the solution for me was just to reboot my Mac.
