### ISSUE TITLE
RFC: Changes to Vapor APT

### ISSUE THREAD

**Issue by joscdk** [vapor/vapor#1857]
We are currently working on some major updates to the Vapor APT to make it easier to maintain in the future, and hopefully be able to provide Swift updates faster, and even push out pre releases.

Here are some proposed changes to the APT. Feedback are more than welcome

1. Change swift package name
To prevent duplicates, and give more descriptive package name, as proposed here #1795 we are going to change the name to:
```
apt-get install swiftlang
apt-get install swiftlang-dev
```

2. Change URL
The new APT will have some breaking changes, i propose to change the repository URL. So instead of `repo.vapor.codes` the new url will be `apt.vapor.codes`

We will keep the old system running for some time, giving people the chance to update without breaking current implementations.

3. Standard for Toolbox versions
The Toolbox need to be compiled for each Swift version. So to be able to have the same Toolbox version for multiple Swift versions, the idea is to version them e.g.:

```
3.1.10~4.2.1
3.1.10~4.2.0
```
Where `~x.x.x` will be the specific Swift versions it's compiled for.

4. Package updates through JSON files
To make updates easier, the idea is to allow for JSON files in the apt repository. Each Ubuntu distribution will have a JSON file, which will contain info on which swift/toolbox versions are available, and dependencies.
This will make it easy to e.g. Do automated updates.

We will provide a small CLI tool to easily add new releases.

CC. @tanner0101 @LoganWright

**Comment by joscdk** [comment]
JSON examples can be found here: https://github.com/vapor/apt/tree/1a9410641f623401048d6409715b32bbbf1beaf3

There will also be a small ruby script in the package that can be run to easily add new packages by answering a few questions

**Comment by marc-medley** [comment]
@joscdk The proposed Swift & Vapor `apt-get` changes look good relative to my use case. Is there any estimated timeline for when the proposed [vapor/apt](https://github.com/vapor/apt/branches) changes might be available?

**Comment by joscdk** [comment]
@marc-medley we are currently working on a new Vapor project, once we have the Alpha feature complete, i will try to get the final changes to the new APT out :)

**Comment by marc-medley** [comment]
@joscdk thanks for the update. 

Perhaps, the alpha milestone would also be a good time for APT `vapor-dev` (Vapor 4?) and `swiftlang-dev` (Swift 5?) in addition to full release APT `vapor` & `swiftlang` … to facilitate onboarding of testers, early adopters, and anyone looking to try the new features. :-)

**Comment by joscdk** [comment]
@marc-medley yeah we are going to have to look into what we do in terms of release, because of some big changes, we might need to only make it available for new releases, so e.g.:
- Swift 4.2.2+
- Toolbox 18+
And keep the old APT running for some time for older versions, but we will mention something out when we have a release plan ready :)
