### ISSUE TITLE
no such module / could not build objective-c module

### ISSUE THREAD

**Issue by osianSmith** [vapor/vapor#1858]
Hello, I'm new to Vapor so I might be missing something obvious here.
I've been following the documentation on docs.vapor.code (get started and hello world) and have installed vapor correctly on my Mac but when I open it up in Xcode I have 11 errors (and a request for a swift conversion). These are all in build time. 

These errors are in the CNIOTTPParser, as semantic issues, can't return function type, parameter list without types and parse issues with could not build model "Darwin"

In  NIOOpenSSL  I have a non zero exit code, in Run I have a "No such module App"

In Random  and Core I have again a nonzero exit 

NIOHTTP could not build Object-C module 

NIOWebSocket I have no such model NoHTTP1. 

I've had no issues with Xcode as a iOS developer (In swift). I'm not sure what I've done wrong and a google doesn't help. 
Any recommendations are appreciated 
Thanks 
Osian

**Comment by VineFiner** [comment]
What is the version system? try use

```
brew install vapor/tap/vapor
```

**Comment by vzsg** [comment]
The vapor toolbox unfortunately will not have any effect on this kind of issues. What is your Xcode version though?

**Comment by osianSmith** [comment]
> What is the version system? try use
> 
> ```
> brew install vapor/tap/vapor
> ```

Hey, this did not do any diffrence 

 

> The vapor toolbox unfortunately will not have any effect on this kind of issues. What is your Xcode version though?

I am running Xcode version 10.1

Thanks guys

**Comment by osianSmith** [comment]
Hey, I've reinstalled vapour, xcoe and deleted all folders and still having the same issues.

**Comment by vzsg** [comment]
That sucks... Here are some more ideas that can go wrong?

- Do you have MacPorts installed on your system (maybe long forgotten)? If so, try removing it completely, including any environment variables and overrides left in your bash profile.
- Have you installed `libressl` with brew? If not, install it.
- Is Homebrew installed at the default location? This shouldn't be an issue for now, but still, some packages work better if Homebrew is in /usr/local.

**Comment by osianSmith** [comment]
Cheers that works, however I am still getting 41 build errors - Is there anything else that I need to install?

**Comment by kiancheong** [comment]
Facing the same situation at the moment. Tried this https://github.com/vapor/vapor/issues/1830#issuecomment-437150478 and it worked.

**Comment by funcsatish** [comment]
try using these commands in the terminal where Package.swift file is
```bash
swift build && swift package generate-xcodeproj
```

**Comment by jerryga** [comment]
I am facing the same issue. 

<unknown>:0: error: too many errors emitted, stopping now
<unknown>:0: error: could not build Objective-C module 'Darwin'
/Users/Asa/TestASA: error: manifest parse error(s):
<module-includes>:5:9: note: in file included from <module-includes>:5:

**Comment by jerryga** [comment]
> I am facing the same issue.
> 
> /Users/Asa/TestASA: error: manifest parse error(s):
> :5:9: note: in file included from :5:
> 
> :0: error: too many errors emitted, stopping now
> :0: error: could not build Objective-C module 'Darwin'

I have solved this problem by deleting the dir:/usr/local/include. By the way , thank you very much for the help of oxTim、tholo、gwynne and other team project memebers, thank you.
