### ISSUE TITLE
Impossible to inject Request.parameters

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#1863]
As it stands, it is currently impossible to inject any `Parameter` into a `Request` because `_parameters` is `internal` and `ParametersContainer` is read-only.

This is particularly painful when unit testing, because it means that for testing a controller we have to instantiate router and routes to be able to parse and populate eventual parameters.

**Comment by calebkleveter** [comment]
This has been discussed on Discord, and it was decided that the route parameters API would be rewritten for Vapor 4. You'll probably have to wait until then for any changes in this to occur.

**Comment by Joannis** [comment]
@tanner0101 seems solved. `parameters.set` has been supported for a year now.

**Comment by MrLotU** [comment]
I'll close this for now. If you still have unresolved issues. Please open up a new ticket.
