### ISSUE TITLE
Impossible to access original request url

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#1864]
It seems that `Request.http.url` returns only the relative path of the original request url.
For example:
`GET http://localhost/hello` -> `hello`
Expected value:
`GET http://localhost/hello` -> `http://localhost/hello`

I have tracked this down to `HTTPRequestDecoder` in `SwiftNIO` that seems to parse the original request url by removing `scheme` and `host` (not sure based on what rules as I am not able to identify the source code that does that).

It also seems that `EngineRouter` is perfectly happy with it, in fact in the eventuality where a full url has to be processed by the router it would just fail without matching any `Route` (unless registered with the full url, which doesn't make any sense).

Not being able to access the full original request url from inside controllers is a massive change from Vapor 2 and I don't see any reason why that should not be accessible. Hopefully I am missing something.

Note: using the `Host` in the headers is not an option as it would still miss the scheme `http|https`.

**Comment by tanner0101** [comment]
Sorry I missed this one. This would need to be changed in SwiftNIO I think. You should be able to determine this by looking at `app.http.server.configuration` though. If you're behind a proxy, you can get the forwarded URL using `req.headers.forwarded`.

**Comment by adamzarn** [comment]
Based on the suggestion of @tanner0101, I created a `Request` extension to get its base url:
```swift
extension Request {
    var baseUrl: String {
        let configuration = application.http.server.configuration
        let scheme = configuration.tlsConfiguration == nil ? "http" : "https"
        let host = configuration.hostname
        let port = configuration.port
        return "\(scheme)://\(host):\(port)"
    }
}
```
