### ISSUE TITLE
`Set<String>` does not conform to `ReflectionDecodable`

### ISSUE THREAD

**Issue by xavierLowmiller** [vapor/vapor#1867]
I tried to use a `Set<String>` on one of my models in a Vapor 3 app, and noticed that this does not work since `Set` does not conform to `ReflectionDecodable`

I can work around the issue by conforming `Set` do `ReflectionDecodable` with an implementation that is virtually identical to the one used in `Array`:

```swift
extension Set: ReflectionDecodable {
    public static func reflectDecoded() throws -> (Set<Element>, Set<Element>) {
        let reflected = try forceCast(Element.self).anyReflectDecoded()
        return ([reflected.0 as! Element], [reflected.1 as! Element])
    }

    public static func reflectDecodedIsLeft(_ item: Set<Element>) throws -> Bool {
        return try forceCast(Element.self).anyReflectDecodedIsLeft(item.first!)
    }
}
```

*Disclaimer:*

I'm not an expert on `ReflectionDecodable`.
Is the conformance for Set omitted intentionally?
Would you be interested in a PR that adds the conformance?

### Steps to reproduce

1. Add a property of type `Set<String>` (or any other Set, really) to a Model
2. Build & Run

### Expected behavior

The server starts without issue

### Actual behavior

A fatal error is raised

### Environment

Vapor Toolbox: 3.1.10
Vapor Framework: 3.0.8
OS version: macOS 10.14.2 (18C54)

**Comment by tanner0101** [comment]
> Is the conformance for Set omitted intentionally?

No, just an oversight. 

> Would you be interested in a PR that adds the conformance?

Yes! A PR to https://github.com/vapor/core would be greatly appreciated. :)

**Comment by xavierLowmiller** [comment]
Cool! I'll get to it shortly!

**Comment by xavierLowmiller** [comment]
Since the PR was merged, this can be closed.
