### ISSUE TITLE
Too much warnings in hello world project

### ISSUE THREAD

**Issue by iamybj** [vapor/vapor#1874]
I just learn swift and vapor, in the hello world project, I find a lot of warnings.
Does vapor need a update to fix them?

<img width="768" alt="screen shot 2019-01-18 at 12 13 04" src="https://user-images.githubusercontent.com/1802494/51365284-76ef3a80-1b1a-11e9-84b5-dca26ad88021.png">

**Comment by mixio** [comment]
@iamybj, you can suppress the warnings by going to the Build Settings for the NIO* targets,  search for "suppress warnings" and set the
```
    > Swift Compiler - Warnings Policies 
            > Suppress Warnings YES.
```
