### ISSUE TITLE
Can't update vapor project

### ISSUE THREAD

**Issue by amine2233** [vapor/vapor#1877]
### Steps to reproduce

create a new project with vapor new --auth <name>

then when I added some dependencies in Package.swift

```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "name",
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),
        
        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-postgresql.git", from: "3.0.0"),
        
        // 👤 Authentication and Authorization layer for Fluent.
        .package(url: "https://github.com/vapor/auth.git", from: "2.0.0"),
    ],
    targets: [
        .target(name: "App", dependencies: ["Authentication", "FluentPostgreSQL", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

when I use ```vapor update``` or ```swift package update``` the update not working I waiting this package

```bash
Updating https://github.com/apple/swift-nio-ssl.git
```

and I tried to clean all dependency with ```vapor clean``` and try to update with the same command 

i have this

```bash
Fetching https://github.com/apple/swift-nio-ssl-support.git
```

### Environment

* Swift version: Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
* Vapor Framework version: 3.0.0
* Vapor Toolbox version: 3.1.10
* OS version: MacOs 10.14.2

**Comment by 0xTim** [comment]
Have you tried deleting `Package.resolved` and trying again? SPM can sometimes get a bit confused

**Comment by amine2233** [comment]
thanks for your response,

I removed the file ```Package.resolved``` and i tried again, the result it's the same, only blocked in 

```bash
Updating https://github.com/apple/swift-nio-ssl.git
```

**Comment by 0xTim** [comment]
The package resolver is parallelised so it's quite probable that it isn't that and just getting stuck in a dependency resolution cycle. And I've just spotted the issue! `.package(url: "https://github.com/vapor/fluent-postgresql.git", from: "3.0.0"),` should be 1.0.0 - 3.0.0 doesn't exist! That should fix the issue

**Comment by amine2233** [comment]
Yes, it's my fluent-postgresql is on version 3.0.0 and in release tab of repo git haven't a version 3.0.0, Thanks, it's resolve my problem

**Comment by amine2233** [comment]
why we haven't a doc for vapor module ? because if i see a doc in README.md of repo I would not have had a problem @0xTim
