### ISSUE TITLE
add .env (dotenv) support

### ISSUE THREAD

**Issue by joscdk** [vapor/vapor#1885]
It should be possible to load Environment variables into an Vapor app from a .env file. Examples of this can be seen in various other frameworks (Laravel, NodeJS etc.)

Some examples of what should be allowed:

```
FOO="Foo Bar"
FOO2='Foo Bar'
FOO3=Bar
```

**Comment by MrLotU** [comment]
Yes please! Another thing to keep in mind, there is a solution out there ATM, https://github.com/SwiftOnTheServer/SwiftDotEnv but I don't think it plays well with Xcode

**Comment by vzsg** [comment]
The solutions listed in vapor/documentation#390 work too, even in Xcode 🙂.

**Comment by MrLotU** [comment]
Looks cool! @vzsg if you want, could you open a PR? 😊
