### ISSUE TITLE
graceful shutdown

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#1889]
Vapor 4 has added support for capturing `SIGINT` to shut down the server. This is a great start, but we can do more to support graceful shutdown.

- [x] Use NIO's [`QuiescingHelper`](https://github.com/apple/swift-nio-extras/blob/master/Sources/NIOExtras/QuiescingHelper.swift) to give in-flight HTTP requests a chance to complete before closing the server.
- [x] Also capture `SIGTERM` signal to gracefully close server.
- [x] When `app.cleanup()` calls `elg.syncShutdownGracefully()`, NIO should close any remaining open channels (such as DB connections) if it needs to.  However, it would be nice if by time the event loop shutdown, those connections were already closed. This could be achieved by allowing for service providers to register custom cleanup behavior.
- [ ] Providers like Fluent should add support for `Provider.willShutdown`
- [ ] Server quiescing should have a deadline.

**Comment by weissi** [comment]
and here's a full demo HTTP server that does the whole thing for `SIGINT`: https://github.com/apple/swift-nio-extras/blob/master/Sources/HTTPServerWithQuiescingDemo/main.swift

**Comment by tanner0101** [comment]
QuiescingHelper added in https://github.com/vapor/http/pull/330. I just copied it in for now, but once NIOExtras is updated to NIO 2, I will look into adding that as a dep. I've updated the original tasks to include adding a quiescing timeout.

**Comment by tanner0101** [comment]
When Vapor's running server stops, it now calls `Container.willShutdown()` on any containers it created. This gives container providers a chance to free up resources before they are deinitialized. Any containers created by other means should make sure to call `container.willShutdown()` before letting the container deinit. 

https://github.com/vapor/vapor/pull/1903

**Comment by tanner0101** [comment]
This has been available in Vapor 4 betas for a while now, closing.
