### ISSUE TITLE
vapor build error : fetch  command is deprecated  and  use resolve instead

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [vapor/vapor#1893]
<img width="572" alt="2019-02-14 9 17 27" src="https://user-images.githubusercontent.com/16648917/52789104-f3375800-309d-11e9-9bf8-0db0d918fcd9.png">

* Vapor Framework version:3.1.10
* Vapor Toolbox version:3.1.10
* OS version:10.14.3
How to solve this problem?
I have tried many times .

**Comment by vzsg** [comment]
In the middle of the screenshot, it seems that the network connection was interrupted while fetching the dependencies with `git`. Try deleting the `.build` folder, and use `swift package build` instead of `vapor build`.

**Comment by zhuiyizhiqiu** [comment]
<img width="567" alt="2019-02-14 11 39 05" src="https://user-images.githubusercontent.com/16648917/52797888-ca20c280-30b1-11e9-9032-35108d2850fd.png">
swift build  have some problem too.

**Comment by tanner0101** [comment]
This seems like an issue with your internet connection.
