### ISSUE TITLE
503 error when deploy app to Vapor Cloud 

### ISSUE THREAD

**Issue by simonmitchell** [vapor/vapor#1911]
I'm having trouble distributing a simple API I've created to docker cloud, the code all compiles and runs well on localhost but when distributing via `vapor cloud deploy` everything seems to have gone well until I try and hit the API when I get a `503 Service Temporarily Available` I've tailed the logs and all I can see is:

```
7 Illegal instruction     (core dumped) /vapor/{app_name_here}/code/.build/release/Run serve --port 8080 --hostname 0.0.0.0
```

I have next to zero experience with Docker, or really at all with backend APIs, this is just for an innovation project at work! I've had a google and this error may not be specific to Vapor, but it is happening on a vanilla project created using the vapor cli! N.B. I have since edited the repo slightly to use docker info provided from other example projects but it also didn't work using the vanilla project setup using `vapor new` command. 

### Steps to reproduce

- Clone repo from https://github.com/3sidedcube/devicemonitor
- Setup vapor cloud project and app
- Attempt to deploy (production environment) via `vapor cloud deploy` (No need for a database)
- Witness 503 and provided logs

### Expected behavior

The created instance should work fine!

### Actual behavior

The created instance returns a 503 when hitting available endpoints

### Environment

Vapor Toolbox: 3.1.10
Vapor Framework: 3.1.0
OS version: 
* Vapor Framework version:
* Vapor Toolbox version:
* OS version: macOS 10.14 (18A391)

**Comment by joscdk** [comment]
@simonmitchell these kind of errors are usually linked to features not implemented on Linux.

You *might* be able to get a bit more insight if you try to spin it up locally in a Docker container, and run it in Debug mode.

**Comment by simonmitchell** [comment]
Ok great, thanks! I’ll give that a go first thing tomorrow when I’m back in work. Would it be something within my project that could be causing it? Or more likely to be something that Docker is doing? Sorry, I am very new to Docker!

**Comment by joscdk** [comment]
Usually we see this if a function is called in Foundation that isn't implemented on Linux :)

If you don't want to play around with Docker locally, you can also try out our new Vapor Cloud 2 Alpha, since this allows you to customize the Docker container, so you can set it to Debug mode
docs.v2.vapor.cloud/quick-start/

If you want to try it out on Cloud 2, feel free to poke me e.g. On Discord in #cloud-2 channel, and i can help you setup the container for Cloud 2.

For testing locally, you can use the #docker channel.

Link to Discord: http://vapor.team

**Comment by simonmitchell** [comment]
@joscdk again thanks! I’ll give it a go and get back to you on Discord if I need further assistance, our server team do a lot with Docker though so may corner one of them!

Very strange concept for me not having Foundation functions not available!! I’ve written shared macOS and iOS codebases before but at least they both have the same Foundation availability (for the most part)!

**Comment by simonmitchell** [comment]
@joscdk I've successfully got an instance up and running using docker locally and doesn't seem to be any compiler errors due to missing Foundation api 😞 Any other thoughts?

**Comment by joscdk** [comment]
@simonmitchell what happens when you hit the endpoint in your local docker container, and check the logs?

These kinds of errors only happens during runtime, meaning it's calling the API that crashes it.

**Comment by simonmitchell** [comment]
Ahh apologies, gotcha! Sorry, I'll have another check now. Just gotta get the docker container back up and running!

**Comment by simonmitchell** [comment]
In the end it turned out this was caused because the environment variables were being setup on vapor cloud in a way which was breaking the formatting of a private key used for the ferno library (firebase real-time DB) as suggested by @joscdk Ive since base64 encoded the key to avoid any issues with how spaces and new lines are encoded when setting up environment variables!
