### ISSUE TITLE
Future<Response> improvement

### ISSUE THREAD

**Issue by JaapWijnen** [vapor/vapor#1915]
Suggestion from @0xTim and me implementing the following extension on `Future<Response>`:

```swift
extension Future where T: Response {
    func decodeResponse<U: Decodable>(_ type: U.Type) -> Future<U> {
        return self.map(to: type) { response in
            return try response.content.syncDecode(type)
        }
    }
}
```

This allows for writing cleaner code when sending requests from a `Client` object. And you only want to decode the response to that request. Since you no longer have to flatMap the response and then call flatMap on the `response.content.decode()` it saves writing a closure for another future.

**Comment by JaapWijnen** [comment]
I'm not sure about the naming of the function however. But couldn't think of the right fit yet.

**Comment by 0xTim** [comment]
I'd just call it `decode` as a helper on the normal `decode`. Since it's hidden as a helper, you could use `decode` instead of `syncDecode` as well to allow streaming bodies to be handled

**Comment by MrLotU** [comment]
I’m with @0xTim on just naming it `decode`. Would you be up to PR this?

**Comment by JaapWijnen** [comment]
Yeah agreed `decode` sounds best. Yeah I was trying at first, but couldn't find the correct file. Turns out I was looking around the master branch which is in transition to version 4 right now (I only found out later). Ill throw out a PR somewhere today.

**Comment by JaapWijnen** [comment]
I'm not sure what the correct location for the extension would be. Not the Response.swift file right. Any more correct location for a specific extension on Future? @MrLotU
