### ISSUE TITLE
Who can see my localhost mock of Vapor server ? 

### ISSUE THREAD

**Issue by peopleCallMeStarLord** [vapor/vapor#1918]
I want to apologize for my English and say thank you for this product.
I'm an iOS developer but always wanted to know more about the server side and it's great that I can use Swift for that.

My question is quite strange.
I started studying Vapor at my workplace informally, in my spare time. My computer is connected to my work network and installing localhost server after some time in my office the network administrator came and asked my ip address. And I'm wondering, is this happenstance or should I not be working with Vapor in my work network and just looking at cats in my free time ? Because everyone on the network can see my localhost Vapor ?

**Comment by linqingmo** [comment]
Yes, they can. I write a server, and I can access it with my iPhone.

**Comment by halfnibble** [comment]
It really depends on the firewall settings of your computer and the network settings in general. I can think of no valid reason for a network administrator to ask for your IP address. They should be able to get that information on their own. If your computer is managed by your company, then they can configure it to observe everything you do on it.

**I think we can close this issue.**
