### ISSUE TITLE
Logger+LogError.swift: case is already handled by previous patterns

### ISSUE THREAD

**Issue by marc-medley** [vapor/vapor#1924]
``` bash
…/.build/checkouts/vapor.git--5345404933707134499/
    Sources/Vapor/Logging/Logger+LogError.swift:38:18: 
    warning: case is already handled by previous patterns; consider removing it
            case let convertible as CustomStringConvertible: reason = convertible.description
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce

``` bash
vapor new example --web
cd example
vapor update -n
vapor build --verbose
# Cloning https://github.com/vapor/vapor.git
# Resolving https://github.com/vapor/vapor.git at 3.3.0

# Compile Swift Module 'Vapor' (75 sources)
# …example/.build/checkouts/vapor.git--5345404933707134499/
#    Sources/Vapor/Logging/Logger+LogError.swift:38:18: 
#    warning: case is already handled by previous patterns; consider removing it
#        case let convertible as CustomStringConvertible: reason = convertible.description
#            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Expected behavior

A warning free compile would be nice.

### Actual behavior

_"warning: case is already handled by previous patterns"_ was the only warning in the build.

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: Xcode 10.1, Swift 4.2.1, macOS 10.13.6

**Comment by MrLotU** [comment]
Thanks for the issue @marc-medley! I just did some code digging and the entire section of code generating that warning seems redundant. I'll check with @tanner0101 if there is a reason this is like this, but otherwise we'll get this sorted ASAP 😃 

CC @tanner0101: Origin is this default clause here: https://github.com/vapor/vapor/blob/3/Sources/Vapor/Logging/Logger%2BLogError.swift#L36 but can we not just use `error.localizedDescription` since all `Error` types have that now?

**Comment by tanner0101** [comment]
Could this be related to https://github.com/vapor/core/issues/193

**Comment by MrLotU** [comment]
Ooh, very well might. Debuggable might conform to both of them?

**Comment by tanner0101** [comment]
Yeah, that's what I'm thinking. @marc-medley if you run `swift package update` to get core 3.7.0, do you still see this warning?

**Comment by MrLotU** [comment]
Just checked that. Error did indeed disappear. I'll close this issue.

For anyone coming here with the same error: Running `swift package update` or `vapor update` will fix this.

**Comment by marc-medley** [comment]
@tanner0101 @MrLotU Just to close the loop, `vapor update` did pull in core 3.7.0 and the warning was _gone_ in subsequent builds. Thanks.
