### ISSUE TITLE
 Vapor  initiates http request, how to get the content of the response

### ISSUE THREAD

**Issue by wenxini234** [vapor/vapor#1926]
* Vapor Framework version:3
* Vapor Toolbox version:

**Comment by wenxini234** [comment]
and sets the request header information, such as application/x-www-form-urlencoded or application/json
eg:try req.client().get("http://ip-api.com/json/")

**Comment by linqingmo** [comment]
```swift
struct T: Decodable {
    let `as`: String
    let city: String
    let country: String
    let countryCode: String
    let isp: String
    let lat: Double
    let lon: Double
    let org: String
    let query: String
    let region: String
    let regionName: String
    let status: String
    let timezone: String
    let zip: String
}
let res = try req.client().get("http://ip-api.com/json/").flatMap { response in try response.content.decode(T.self) }
```

**Comment by MrLotU** [comment]
Also see this part of the docs: https://docs.vapor.codes/3.0/vapor/content/#client

**Comment by wenxini234** [comment]
> Also see this part of the docs: https://docs.vapor.codes/3.0/vapor/content/#client
think you very much 
print(res) // NIO.EventLoopFuture<App.(unknown context at 0x107862088).T>
but how to get the value of each field

**Comment by vzsg** [comment]
HTTP requests are asynchronous, meaning that you cannot immediately get the values out of it, only once the call finished in the background – which requires a new way of thinking compared to synchronous/blocking frameworks and languages (including Vapor 2).

Vapor 3 uses EventLoopFutures to represent values "that will arrive in the future", which you can return from route handlers, transform (`map`) or chain (`flatMap`) or combine (`and`) with other futures.

If this is unclear, I suggest looking into the books, some tutorials or perhaps the [documentation](https://docs.vapor.codes/3.0/async/overview/) (which might be too dry at first.)
