### ISSUE TITLE
Generate OPTIONS Routes

### ISSUE THREAD

**Issue by calebkleveter** [vapor/vapor#1927]
There should be a way for an app's router to generate the `OPTIONS` routes for each resource. We could make it configurable, where you would pass in a `Bool` to the router's initializer:

```swift
services.register(Router.self) { container -> EngineRouter in
    let router = EngineRouter(optionRoutes: true)
    try routes(router, container)
    return router
}
```

These routes used to be generated in earlier versions of Vapor, but it fell out during v2 -> v3.

**Comment by tanner0101** [comment]
Agreed, this would be nice for Vapor 4. In Vapor 2, the OPTIONS stuff was handled with the resource routing: https://github.com/vapor/vapor/blob/2.4.5/Sources/Vapor/Routing/Resource.swift#L121-L130. Since Vapor 3 dropped the `ResourceController` concept, we lost the OPTIONS routing. Maybe we can figure out a more generic way to implement OPTIONS support, or this issue should be tied to the feature request for a `RESTController` protocol

**Comment by mcdappdev** [comment]
I believe these get added with the CorsMiddleware currently, yes?

**Comment by tanner0101** [comment]
@mcdappdev hmm yeah, that's a good point. CORSMiddleware would need some help to work well with this. According to HTTP spec, `OPTIONS` can also let you know which routes an API supports, alongside letting you know which methods are supported. I'm not sure how prevalent that is these days given things like OpenAPI, but it's something Vapor 2 supported.

**Comment by mcdappdev** [comment]
Makes sense. Obviously the OPTIONS route is important for CORS and libraries like Axios on the frontend which expect it to be there. So as long as the functionality doesn't disappear, regardless of its final form, I'll be happy :)

**Comment by calebkleveter** [comment]
Exactly. Axios was actually how I discovered this was missing 😄.

**Comment by tanner0101** [comment]
@calebkleveter ah yeah, you just need CORS middleware then :)

**Comment by Joannis** [comment]
Does Vapor 4's middleware suffice nowadays?

**Comment by calebkleveter** [comment]
Yep, just register the `CORSMiddleware` that Vapor now provides and you are good to go.
