### ISSUE TITLE
Error like "Value required for key 'device_id'." should not be returned in production environment

### ISSUE THREAD

**Issue by xiao99xiao** [vapor/vapor#1930]
In Production environment, when posting an empty request to a url, vapor always return a error message indicating what key is needed and what type it should be in this case. Messages like those is something you don't want to be seen in production environment because it might be used to breach your server.

https://github.com/vapor/vapor/blob/def308b5df18e0cc5873a4cb51e0e4b86805cb7c/Sources/Vapor/Middleware/ErrorMiddleware.swift#L63

### Steps to reproduce

1. build a controller post method accepting a struct with a Int inside
2. post an empty request to the url
3. check the response body

### Expected behavior

The response body should be empty or something more generic.

### Actual behavior

Returns exactly what the api requires.

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14 and Ubuntu 18.04

**Comment by tanner0101** [comment]
Hmm, I see your point about this being a potential security issue. But a lot of people rely on this behavior to deliver useful validation info to the client. 

I would support making this behavior opt-in, but that would need to wait for Vapor 4 as I think it should be considered a breaking change. The API for opting in would also need to be decided on and implemented. I've been considering merge https://github.com/vapor/validation with the core repo, so maybe this would be a good time to do it.

As a workaround, you can remove `ErrorMiddleware` from your `MiddlewareConfig`, and the connection will simply close on error. You can implement a custom `ErrorMiddleware` to configure anything beyond that.

**Comment by Joannis** [comment]
Closing this as Vapor 4 fixes this issue.
