### ISSUE TITLE
Cannot create siblings relation between same models

### ISSUE THREAD

**Issue by LinusGeffarth** [vapor/vapor#1932]
I want to create a siblings relationship between two `User` models, for a sort-of "friend" feature, similar to Facebook.  
I created the `UserFriendsPivot`:

    final class UserFriendsPivot: MySQLPivot, ModifiablePivot {
        var id: Int?
        var userID: User.ID
        var friendID: User.ID
        
        typealias Left = User
        typealias Right = User
        
        static var leftIDKey: WritableKeyPath<UserFriendsPivot, Int> {
            return \.userID
        }
        
        static var rightIDKey: WritableKeyPath<UserFriendsPivot, Int> {
            return \.friendID
        }
        
        init(_ user: User, _ friend: User) throws {
            self.userID   = try user  .requireID()
            self.friendID = try friend.requireID()
        }
    }

    extension UserFriendsPivot: Migration {
        public static var entity: String {
            return "user_friends"
        }
    }

I added the `friends` property to `User`:

    var friends: Siblings<User, User, UserFriendsPivot> {
        return siblings()
    }

Now, I'm seeing the following error on the line with `return siblings()`:

>Ambiguous use of 'siblings(related:through:)'

I tried to replace it with:

    return siblings(related: User.self, through: UserFriendsPivot.self)

...without any luck.

I know that the two code snippets *should* work, because I straight-up copied them from another siblings relationship I built between `Event` and `User` that is working just fine.  
The only difference I'm seeing is that I'm trying to build a relationship between the same models.

Is this a Vapor bug, or just me doing something wrong here?

### Environment

* Vapor Framework version: 3.0.0
* Vapor Toolbox version: 3.1.10
* OS version: 10.14.3

**Comment by jbl8084** [comment]
Is MySQLPivot somehow a ModifiablePivot already?

**Comment by LinusGeffarth** [comment]
Don't think so. For attaching, I had to have it conform to ˋModifiablePivotˋ. @jbl8084

**Comment by grundoon** [comment]
The issue here is that in a same-Model (`User`-`User`) siblings relation, `Fluent` cannot infer which  sibling you are referring to – the sides need to be specified.

```swift
extension User {
    // the friends of the user
    var friends: Siblings<User, User, UserFriendsPivot> {
        return siblings(UserFriendsPivot.leftIDKey, UserFriendsPivot.rightIDKey)
    }

    // the users who have friended the user 
    var friendOf: Siblings<User, User, UserFriendsPivot > {
        return siblings(UserFriendsPivot.rightIDKey, UserFriendsPivot.leftIDKey)
    }
}
```

The other same-Model consequence is that you will not be able to use the `attach` convenience method to add to the pivot table, and need to manually create instead:

```swift
let pivot = try UserFriendsPivot(user, friend)
pivot.save(on: req)
```

(There are other approaches to work around this, I just find these straightforward ways above the easiest to use. Specifying the sides and reversing the key positions to obtain the inverse relation are the important concepts.)

**Comment by LinusGeffarth** [comment]
@grundoon, thank you for your answer. Can I use `isAttached` and `detach`, or do I have to work around those too?
If so, what's the equivalents?

**Comment by grundoon** [comment]
@LinusGeffarth Off the top of my head, I believe any method that accesses _through_ the keyed `Siblings<Base, Related, Through>` relations you've defined above (such as `isAttached`, `detach` and `detachAll`) should work right out of the box.

```swift
user.friends.isAttached(friend, on: req)
     ^^^^^^^
```

**Comment by LinusGeffarth** [comment]
Yeah, I've found that both methods do work. Thanks for your help! @grundoon
