### ISSUE TITLE
eventLoop.scheduleTask Limit

### ISSUE THREAD

**Issue by guarland** [vapor/vapor#1934]
Are there any restrictions on use eventLoop.scheduleTask ? 

after 20 times the execution of this code the system hangs

```swift 
 let requestScheduled = req.eventLoop.scheduleTask(in: .seconds(2)) {
                    someMyFunction()
       }
```

after i added this code that deinit scheduleTask, everything works fine

```swift 
   requestScheduled?.cancel()
   requestScheduled = nil
```

but I am afraid that there will be delays when there are numerous requests,  are there any restrictions on use eventLoop.scheduleTask ?

**Comment by tanner0101** [comment]
@guarland sorry I'm not sure. This would be a better question for https://github.com/apple/swift-nio, where all of that code lives.
