### ISSUE TITLE
Are there plans for a SwiftNIO 2 branch of Vapor/Fluent 3?

### ISSUE THREAD

**Issue by MrMage** [vapor/vapor#1936]
I understand that Vapor 4 and Fluent 4 will require (and support, obviously) SwiftNIO 2. However, I need to use SwiftNIO-HTTP2, which recently underwent significant changes that depend on SwiftNIO 2. Given that Vapor 4 and Fluent 4 are not ready yet, are there any plans to offer a branch of the "Vapor 3" projects that supports SwiftNIO 2 instead of 1, for forward compatibility with SwiftNIO 2 while retaining the Vapor/Fluent 3 interface?

**Comment by joscdk** [comment]
@MrMage without having looked more into it, supporting NIO 2 in Vapor 3 would be seen as a breaking change, which won't go into Vapor 3. Besides that, it is afaik. A lot of changes to support NIO 2, so don't think it would be possible.

However let's see what @tanner0101 say.

But all in all, don't think you should hold your breath unfortunately :)

**Comment by tanner0101** [comment]
@MrMage no, I don't think so. That would take a significant amount of time, and it would be of limited use since we could only offer a branch. We couldn't tag any of that as a minor bump to 3 because switching to NIO 2 itself is obviously a breaking change.
