### ISSUE TITLE
[Question] Swift 5 support?

### ISSUE THREAD

**Issue by backslash-f** [vapor/vapor#1937]
Sorry I couldn't find this info somewhere.

How to update Vapor  to support Swift 5.0? (Released yesterday with Xcode 10.2).

Thanks!

**Comment by joscdk** [comment]
There shouldn't be any issues running your Vapor app with Swift 5.. I updated my Xcode last night, and my Vapor 3 project works without problems

**Comment by backslash-f** [comment]
I'm seeing some warnings, should I just run `vapor update -y`?

**Comment by backslash-f** [comment]
Also, can I change this? `// swift-tools-version:4.0` (to `// swift-tools-version:5.0`) (In `Package.swift`).

**Comment by joscdk** [comment]
There are some warnings, the new Vapor 4 will be built directly to and forced on Swift 5 .. You can change that, but you can also leave it, shouldn't make a difference

**Comment by backslash-f** [comment]
All right, got it. Is there a timeline for Vapor 4 release? (You can also close this issue after that as my root question was answered already).

Thank you!

**Comment by joscdk** [comment]
@backslash-f there aren't a fixed timeline, one of the holdbacks have been waiting for Swift 5 and NIO 2 .. Now we should be able to start talking about when we are able to release the first Alpha version of Vapor 4.
But in the end it's up to @tanner0101 when he thinks the API is ready for alpha :)
