### ISSUE TITLE
I can't update vapor 

### ISSUE THREAD

**Issue by jamalalayq** [vapor/vapor#1948]
i can't update to latest version of vapor.
use `brew upgrade vapor` to update version.
current version is (Vapor Toolbox: 3.1.10).
XCode version: 10.2
Swift version: Apple Swift version 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0

**Comment by calebkleveter** [comment]
Vapor Toolbox and Vapor itself are two different things. Vapor toolbox is a command-line tool that wraps a lot of the `swift package` commands, along with allowing you to deploy your app to Vapor Cloud 1. Vapor is the framework, and I suspect that is what you want to update.

In your `Package.swift` file, you should be able to change the version of the Vapor dependency. Then run `swift package update` and `vapor xcode` (if you are using Xcode for development).

**Comment by jamalalayq** [comment]
thank you @calebkleveter i has understand now 😅.
