### ISSUE TITLE
Swagger to Vapor 3 Server API Interface

### ISSUE THREAD

**Issue by thecheatah** [vapor/vapor#1949]
Hi Vapor Team. If you would like to ease API development and like to use Swagger, I have created a swagger-codegen language plugin called SwiftVapor3 located here: https://github.com/thecheatah/SwiftVapor-swagger-codegen

This project will intake a swagger spec and produce a swift package that your vapor project can create a dependency on. The built project will have a routes.swift with a function configure a router to conform to the swagger's API specifications, APIs directory with swift protocols that need to be implemented in your project and a Models directory with models from the swagger.

The project includes a test project with tests that run. You can take a look at it as an example for the type of code that it generates.

Let me know what you think. I apologize if I am breaking a rule for self-promotion. I hope the vapor community finds the project useful.

**Comment by tanner0101** [comment]
Thanks for sharing! Feel free to make a post in our Swift forums section if you'd like: https://forums.swift.org/c/related-projects/vapor
