### ISSUE TITLE
How to add default data to the database

### ISSUE THREAD

**Issue by codwam** [vapor/vapor#1950]
### Environment

* Vapor Framework version:
* Vapor Toolbox version:
* OS version:

**Comment by 0xTim** [comment]
You can do this with a new migration to seed the database, e.g. https://github.com/raywenderlich/vapor-til/blob/master/Sources/App/Models/User.swift#L108

**Comment by codwam** [comment]
@0xTim It didn't work for me...

**Comment by codwam** [comment]
`
static func prepare(on connection: SQLiteConnection) -> Future<Void> {
        let directory = DirectoryConfig.detect()
        let configDir = "Sources/App/Configuration"
        
        do {
            let url = URL(fileURLWithPath: directory.workDir) .appendingPathComponent(configDir, isDirectory: true)
                .appendingPathComponent("Order.json", isDirectory: false)
            let data = try Data(contentsOf: url)
            
            let decoder = JSONDecoder()
            let orders = try decoder.decode([Order].self, from: data)
            return orders.first!.save(on: connection).transform(to: ())
        } catch {
            print(error)
            return Database.update(Order.self, on: connection) { builder in
                
            }
        }
    }
`

Is there any problem with my code?

**Comment by 0xTim** [comment]
@codwam do you get any errors in the console etc? Did you add the migration to your migrations config like so? https://github.com/raywenderlich/vapor-til/blob/master/Sources/App/configure.swift#L98

**Comment by codwam** [comment]
@0xTim
No error.
I have already added it.

But there is no other default data.
Should I create table use sql firstly?

**Comment by codwam** [comment]
I have solved it, thank you very much.
@0xTim
