### ISSUE TITLE
Error: backgroundExecute(code: 1, error: "The file *.xcodeproj does not exist.

### ISSUE THREAD

**Issue by billxcode** [vapor/vapor#1951]
Hello Here I got an error starting new project with vapor, I've ben follow the instruction from documentation here https://docs.vapor.codes/3.0/getting-started/hello-world/
when I going to step `vapor xcode` there is an error apear, like bellow :

```
Error: backgroundExecute(code: 1, error: "The file /Users/jauharibill/Vapor/Hello/*.xcodeproj does not exist.\n", output: "")
```

also here when launch command `vapor version`

```
rror: Error Domain=NSCocoaErrorDomain Code=260 "The folder “checkouts” doesn’t exist." UserInfo={NSFilePath=./.build/checkouts/, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x7fe259d0d760 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
```

please kindly help me, thankyou.

### Steps to reproduce

1. install vapor 
2. create new project
3. launch xcode project with command `vapor xcode` at project directory

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: Mojave

**Comment by calebkleveter** [comment]
I'm not sure why you are getting the first error, but the second one is because you haven't built your project yet (use `swift build`) to do this. The error used to be handled gracefully but it broke somewhere along the way and apparently hasn't been fixed yet.

**Comment by billxcode** [comment]
> I'm not sure why you are getting the first error, but the second one is because you haven't built your project yet (use `swift build`) to do this. The error used to be handled gracefully but it broke somewhere along the way and apparently hasn't been fixed yet.

oh thanks, thats error disappear when I navigate out of project folder, but the first error still not fixed.

**Comment by calebkleveter** [comment]
Homebrew borked your Swift install. Use `xcode-select` to fix that:

```
sudo xcode-select -p /Applications/Xcode.app
```

**Comment by billxcode** [comment]
> Homebrew borked your Swift install. Use `xcode-select` to fix that:
> 
> ```
> sudo xcode-select -p /Applications/Xcode.app
> ```

I think you mean is `sudo xcode-select -s /Applications/Xcode.app`
but thanks for hint, its fix my problem. thank you so much everyone I'll close this issue.

**Comment by ericgroom** [comment]
Can this be put in an FAQ somewhere or make an improved error message? I also ran into this and it took awhile to find this issue.

**Comment by SaezChristopher** [comment]
Same here

**Comment by syedqamara** [comment]
It might be because there is not `Command Line Tool` is select in your Xcode.
Go to `Xcode` > `Preferences` > `Locations` > select a tool from dropdown next to `Command Line Tools`
