### ISSUE TITLE
vapor3 accept the client's json data

### ISSUE THREAD

**Issue by wenxini234** [vapor/vapor#1952]
* Vapor Framework version:vapor 3

Get the JSON data passed from the client, but the fields inside are not fixed, for example
``
{
	"action": "getUser",
	"useId": 1
}
or 
{
	"action": "getOrder",
	"OrderId": 1
}
``
how to define the structure and parse the data from the client.

**Comment by calebkleveter** [comment]
There are a couple of ways to do this. The first that comes to mind is one large struct that contains all the possible keys and they are optional:

```swift
struct ClientJSON: Codable {
    let action: Action // Use an `Action` enum that represents valid actions
    let userId: Int?
    let orderId: Int?
}
```

You could also use a data structure that can handle un-structured JSON. This can get a bit complicated, so you could just use this package: https://github.com/skelpo/JSON (credits to me 😄)

```swift
let someJSON = try JSON(data: response.http.body.data ?? Data())
```

As a side note, that example you give should be handled through different routes in a RESTfull API. You would have a `GET` for both the `user` and `order` collection:

```
GET /users/:userid
GET /order/:orderid
```

Then you just get the ID from the URL and fetch the appropriate model from the database.

If you want to know more about how a REST API works, you can checkout out this resource: https://www.restapitutorial.com/

**Comment by wenxini234** [comment]
@calebkleveter  
thank you very much
