### ISSUE TITLE
How to install vapor 2 instead of vapor 3?

### ISSUE THREAD

**Issue by liyaaa** [vapor/vapor#1961]
My xcode version is 9 and swift version is 4.0, so I can only choose vapor 2. But when I run brew install vapor, it automatically installs vapor 3 for me. How can I get vapor 2?

**Comment by MrLotU** [comment]
`brew install vapor` installs the vapor toolbox, you can still use Vapor 2 by setting your package version in your `Package.swift`. Keep in mind however, Vapor 2 is no longer supported or maintained.
