### ISSUE TITLE
SSL certificate of the Ubuntu repository is expired

### ISSUE THREAD

**Issue by ivan-aksamentov** [vapor/vapor#1966]
It looks like the SSL certificate of the Ubuntu repository is expired. Starting today, April 26, 2019, the update is failing.

### Steps to reproduce

With Vapor repositories set up, run as superuser:

```bash
apt-get update
```

### Expected behavior

Update succeeds, no error messages emitted.
SSL certificate requested from "https://repo.vapor.codes/apt" should be up to date.

### Actual behavior

During update:
```
Ign:14 https://repo.vapor.codes/apt bionic InRelease                                                                   
Err:15 https://repo.vapor.codes/apt bionic Release                                                                     
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 34.249.98.110 443]
```

Summary in the end of update:
```
Reading package lists... Done                      
E: The repository 'https://repo.vapor.codes/apt bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Requesting the certificate info with
```bash
curl --insecure -v "https://repo.vapor.codes/apt" 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
```
returns the following information:
```
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=repo.vapor.codes
*  start date: Jan 26 12:00:27 2019 GMT
*  expire date: Apr 26 12:00:27 2019 GMT
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify result: certificate has expired (10), continuing anyway.
* Connection #0 to host repo.vapor.codes left intact
```

Looks like Letsencrypt's certbot is not properly setup for automatic updates or the update failed for another reason.

### Environment

* Vapor Framework version: does not matter
* Vapor Toolbox version: does not matter
* OS version: Ubuntu 18.04.2 LTS amd64
* apt version: 1.6.10

**Comment by tanner0101** [comment]
@ivan-aksamentov thanks for reporting. cc @joscdk.

**Comment by joscdk** [comment]
Hi @ivan-aksamentov thanks for reporting, unfortunately the issue seemed a lot more complicated than an expired cert.
However it's been fixed now.

**Comment by Behinder** [comment]
I have still this problem

**Comment by Behinder** [comment]
E: The repository 'https://repo.vapor.codes/apt bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by 0xTim** [comment]
@Behinder this repository is deprecated now. To install Swift (and if needed the toolbox) you should follow the instructions at https://docs.vapor.codes/4.0/install/ubuntu/

**Comment by Behinder** [comment]
So there is no repository exists anymore and I need manually install
packages?

**Comment by 0xTim** [comment]
You only need to install Swift following that standard process. You probably don't need the toolbox, you can build and run it with Swift
