### ISSUE TITLE
Vapor does not allow big files to upload

### ISSUE THREAD

**Issue by jochenkiene** [vapor/vapor#1972]
### Steps to reproduce
Create an upload form with multipart/form-data and a vapor route as action. Upload a big file (2 MB is sufficient).

### Expected behavior
The route should be executed.

### Actual behavior
The connection breaks and the route isn’t executed.

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.4

**Comment by th-mustache-dk** [comment]
in configure.swift

```
 var nioConfig = NIOServerConfig.default()
 nioConfig.maxBodySize = 1024 * 1024 * 50 // <------
 nioConfig.hostname = Environment.get("hostname") ?? "localhost"
 nioConfig.port = Environment.get("PORT") ?? 8080
 services.register(nioConfig)
```
