### ISSUE TITLE
Vapor Toolbox: 3.1.10 Swift 5.0.1 Error: GeneralError(message: "Unable to locate vapor dependency")

### ISSUE THREAD

**Issue by JinfeiChen** [vapor/vapor#1973]
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.5.

Vapor Toolbox: 3.1.10

brew tap vapor/tap
brew install vapor/tap/vapor
vapor new Hello
cd Hello
vapor xcode

**Comment by RomainQuidet** [comment]
I just run it on my Mac, same config, it works for me.
I ran ```vapor build``` then ```vapor run```
Opening the project in xcode works also.

**Comment by JinfeiChen** [comment]
Thank you very much for your help! I have given up Vapor and used Perfect.

**Comment by SmartJSONEditor** [comment]
Hello, I am unable to build a xcode project, using vapor 3.1.10, xcode 10.2.1, macOS 10.14.4
The vapor xcode command just run and ask to open project, then fails with :
Opening Xcode project...
Error: backgroundExecute(code: 1, error: "The file /Users/jan.kubny/Desktop/Vapor/VaporTest/HelloVapor/*.xcodeproj does not exist.\n", output: "")

Any thoughts?

**Comment by idev4u** [comment]
I had the same issue, but the issue was related to Swift PM. 
When I had run the swift package help command. I got this error
```
bash$ swift package --help
dyld: Library not loaded: @rpath/llbuild.framework/Versions/A/llbuild
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/swift-package
  Reason: image not found
Abort trap: 6
```
after I fixed it with 
```
bash$ sudo xcode-select -r
```
the vapor toolbox works as expected.
