### ISSUE TITLE
Escaped "/" in JSON response

### ISSUE THREAD

**Issue by samuel-girard** [vapor/vapor#1974]
### Steps to reproduce

From the [Hello World project](https://docs.vapor.codes/3.0/getting-started/hello-world/#hello-world), create a TODO containing a "/" character in the title:  
```
curl -X POST -d '{"title":"bla/bla"}' --header "Content-Type: application/json" http://localhost:8080/todos
```

### Expected behavior

The todo should be created and the value returned should be like `{"id":1,"title":"bla/bla"}`

### Actual behavior

The todo is correctly created, but the value is returned as `{"id":1,"title":"bla\/bla"}` (see as the "/" is escaped in the title value)  

It looks like only "/" character is escaped, from my tests all other characters are correctly returned.

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.4

How can I make Vapor not escape "/" character in the response JSON?

**Comment by joscdk** [comment]
@samuel-girard it's a JSON thing, your client need to handle escapes which most do :)

**Comment by samuel-girard** [comment]
Arg, of course it is escaped... 😳 
My manual copy/paste from the REST client did not escape it ^^

I just understood why this character is escaped in JSON (which didn't seem to be logic to me at first) - if anyone else wonders => https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped

Thanks @joscdk for your quick answer!
