### ISSUE TITLE
ubutun vapor build --release  error

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [vapor/vapor#1978]
### Environment

* Vapor Framework version: 3
* Vapor Toolbox version: 
* OS version: ubutun 16.04
My project store in /root/HelloVapor
I use the supervisor to control that.
but there are the error of "No .build folder, fetch may take a while...
Fetching Dependencies [ •                       ]
Error: backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\nerror: root manifest not found\n", output: "") " when I use vapor build --release.
<img width="570" alt="00650E56C8DD87EE5333F9738405A1F8" src="https://user-images.githubusercontent.com/16648917/57855402-244e3280-781d-11e9-960f-dd2776d6afcb.png">
<img width="570" alt="FB2AFE8CA4A8FB75C7DCA0495DDFB383" src="https://user-images.githubusercontent.com/16648917/57855392-1f897e80-781d-11e9-9b2a-49e59079eddd.png">

**Comment by vzsg** [comment]
You need to be in the project folder `/root/HelloVapor` when you call `vapor build`. The last screenshot clearly shows that you're standing in `/etc/supervisor/conf.d` at the moment.

**Comment by zhuiyizhiqiu** [comment]
Thank you very much. I have resolve the problem.
But I meet another problem.
<img width="575" alt="屏幕快照 2019-05-16 下午10 20 37" src="https://user-images.githubusercontent.com/16648917/57861331-f969db80-7828-11e9-855f-27f03e0527a2.png">

**Comment by vzsg** [comment]
It seems to me that something overwrote your `/etc/supervisor/supervisord.conf` file with some random text instead of a valid configuration.
