### ISSUE TITLE
vapor xcode failed 

### ISSUE THREAD

**Issue by HuuLiang** [vapor/vapor#1982]
vapor xcode failed 

```
error: failed to clone; Cloning into bare repository '/Users/Liang/Desktop/Hello/.build/repositories/vapor-2c13b66e'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Package.swift 

```
 // swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "Hello",
    products: [
        .library(name: "Hello", targets: ["App"]),
    ],
    dependencies: [
        // :droplet: A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        // :large_blue_circle: Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

terminal swift--version

```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0
```

:slight_frown:

**Comment by vzsg** [comment]
That seems like a network error on your side, or perhaps a VPN/proxy messing with the communication with GitHub. Remove the `.build` folder and try again.

If that doesn't help, investigate the network issues and perhaps try from elsewhere.

**Comment by HuuLiang** [comment]
I turn off the Lantern VPN and try again but also failed.
vapor xcode -y
Generating Xcode Project [Failed]
error: failed to clone; Cloning into bare repository '/Users/Liang/Desktop/Hello/.build/repositories/vapor-8c72449b'...
fatal: unable to open /Users/Liang/Desktop/Hello/.build/repositories/vapor-8c72449b/objects/pack/tmp_pack_gb1SLa: No such file or directory
fatal: index-pack failed

Error: Could not generate Xcode project: error: failed to clone; Cloning into bare repository '/Users/Liang/Desktop/Hello/.build/repositories/vapor-8c72449b'...
fatal: unable to open /Users/Liang/Desktop/Hello/.build/repositories/vapor-8c72449b/objects/pack/tmp_pack_gb1SLa: No such file or directory
fatal: index-pack failed

I try  google the reason about the "fatal:index-pack failed" and chmod 777 -R  "my_project_folder" and it doesn't work .

**Comment by xiong1081** [comment]
➜  api-template-master vapor xcode
Generating Xcode Project [Failed]
error: failed to clone; Cloning into bare repository '/Users/duke/Documents/Server/api-template-master/.build/repositories/vapor-2c13b66e'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

Error: Could not generate Xcode project: error: failed to clone; Cloning into bare repository '/Users/duke/Documents/Server/api-template-master/.build/repositories/vapor-2c13b66e'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by xiong1081** [comment]
Can I download "vapor-2c13b66e" manually?

**Comment by tanner0101** [comment]
Closing here since this looks like an issue with SPM. I don't know of any way to download an SPM project's dependencies manually.
