### ISSUE TITLE
Request with no session key gets last session object

### ISSUE THREAD

**Issue by cleverer** [vapor/vapor#1984]
I'm using https://github.com/vapor-community/CSRF and there seems to be a problem regarding the session cache.

When I manually delete the session cookie, I can't login anymore, because it does not create a new CSRF-Secret.
More importantly the [corresponding code](https://github.com/vapor-community/CSRF/blob/4e2f27a2c850627da8a745574d0e71e3519ceaf9/Sources/CSRF.swift#L64-L77) gets a session object (specifically the old session), even though the browser didn't send a session cookie.

### Steps to reproduce

1. Open a URL which creates a session.
2. Delete session cookie in Browser. Alternatively close the browser and open it again.
3. Reload that page.

### Expected behavior

A new session is returned.

### Actual behavior

An old (probably the last) session gets returned.

### Environment

Project: https://git.damutten.ch/Nicolas/HomeControl
Not running in Docker!

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.13.6 (17G5019)

**Comment by tanner0101** [comment]
From what I can tell, this appears to be a bug in vapor-community/CSRF and not vapor/vapor's sessions. I've moved the issue to the correct repository: https://github.com/vapor-community/CSRF/issues/12

If I'm mistaken, and this is an issue w/ vapor/vapor's sessions, we can re-open here. Thanks!
