### ISSUE TITLE
4.0 build failed

### ISSUE THREAD

**Issue by xiaobeiswift** [vapor/vapor#1986]
Could not build Objective-C module 'CCryptoOpenSSL'
'openssl/conf.h' file not found
What is the reason?Version 3.3 does not have this problem.
What do I need to do to build？
thanks

* Vapor Framework version: 4.0.0
* Vapor Toolbox version: 
* OS version: 10.14

**Comment by joscdk** [comment]
@xiaobeiswift i haven't seen that error before, however be warned that Vapor 4 is just being tagged as Alpha now, and not all packages have been released in Alpha yet.

@tanner0101 do you know what is causing this?

**Comment by satishbabariya** [comment]
@xiaobeiswift try installing OpenSSL,
```bash
brew install openssl@1.1
```

**Comment by tanner0101** [comment]
Yup @satishbabariya is correct, you'll need `openssl@1.1` specifically for Vapor's crypto package. I'm looking into removing this requirement in the future, but for now the snippet above should do the trick.

**Comment by andreasley** [comment]
From what I can tell, the package [`OpenCrypto`](https://github.com/vapor/open-crypto) isn't used anymore at this time. Removing the corresponding dependency from Vapor's `Packages.swift` and `Sources/Vapor/Exports.swift` is sufficient to make Vapor build – without having Homebrew or OpenSSL installed.

With this fixed, Vapor can be imported into Xcode 11 by adding a single Package Dependency, which is really nice!

**Comment by tanner0101** [comment]
Yup Vapor 4 no longer requires OpenSSL. Internal copies of BoringSSL are used for things like Crypto and TLS now.
