### ISSUE TITLE
How to exclude property of instance which is extension of 'Content' protocol?

### ISSUE THREAD

**Issue by NicolasKim** [vapor/vapor#1989]
### How to exclude property of instance which is extension of 'Content' protocol?

```swift
struct User: MySQLModel ,Content{
  
    static let entity = "t_user"
    var id: Int?
    var username: String
    var email: String?
    var password: String
}
```
How to exclude password to encoding to JSON ?

**Comment by 0xTim** [comment]
@NicolasKim you have three options, but only one viable one (option 3):

1. Custom init for `Encodable`
2. Overwrite the `CodingKeys` for the `Codable` synthesisation to ignore `password`
3. Note that option 1 and 2 will affect it saving in the database so the real way to do it is to create a public representation of a user and convert it to that before returning it as JSON

**Comment by tanner0101** [comment]
This section of the docs might be helpful: https://docs.vapor.codes/3.0/vapor/content/#dynamic-properties
