### ISSUE TITLE
could not install vapor on macos mojave

### ISSUE THREAD

**Issue by HappyDaydayUp** [vapor/vapor#1993]
### Environment

* Vapor Framework version: 3
* Vapor Toolbox version: newest
* OS version:macOS mojave 10.14.4
 when do command of 
 brew install vapor/tap/vapor 

the terminal show the error is 
 Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
#######                                                                    9.8%
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "vapor"
Download failed: https://github.com/vapor/toolbox/releases/download/3.1.10/macOS-sierra.tar.gz
Can help me solve this trouble ?

I am in China。this  have influence

**Comment by joscdk** [comment]
It sounds like a problem with the firewall in China, and AWS S3, without having looked additional into it.
