### ISSUE TITLE
Use Github's new feature for vapor templates.

### ISSUE THREAD

**Issue by satishbabariya** [vapor/vapor#1994]
Generate new repositories with repository templates

Github introduced repository templates to make boilerplate code management and distribution a first-class citizen on GitHub.

When Enabled on repo, Which will create **Use this template** button on GitHub repo, like this:
![Screen Shot 2019-06-08 at 12 41 35 PM](https://user-images.githubusercontent.com/16605023/59143673-e6db6000-89ea-11e9-9ae2-ac5823039244.png)

more info can be found here, [https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/](https://github.blog/2019-06-06-generate-new-repositories-with-repository-templates/)

**Comment by vzsg** [comment]
Thanks for bringing this to attention!

It's a no-brainer, so I went and set the flag in the api-template, web-template and auth-template repos.
