### ISSUE TITLE
Help with CoreLocation

### ISSUE THREAD

**Issue by leomeneguzzi** [vapor/vapor#1996]
Hi, I want to use `CoreLocation` with `geocodeAddressString` but the function don't do nothing.

### Steps to reproduce

I'm using like this: 

```
import CoreLocation

...

func geocodeAddressString(string: String, completionHandler: @escaping (String?) -> ()) {
        CLGeocoder().geocodeAddressString(string) { placemarks, error in
            if error != nil {
                print(error!)
            }
            
            if let placemark = placemarks?.first {
                let lat = placemark.location?.coordinate.latitude
                let lon = placemark.location?.coordinate.longitude
                let concat = "Lat: \(String(describing: lat)), Lon: \(String(describing: lon))"
                completionHandler(concat)
            } else {
                completionHandler("Error!!")
            }
        }
    }
```

### Expected behavior

I want when I call this function I can put the `completionHandler` and get the String.

### Actual behavior

Nothing inside the `completitionHandler` or inside the `CLGeocoder().geocodeAddressString` are executed apparently. I tried to put some `terminal.print` inside theirs and don't print nothing.

### Environment

* Vapor Framework version: I think is 3.0.0
* Vapor Toolbox version: 3.1.10
* OS version: 10.14.5

**Comment by 0xTim** [comment]
`CoreLocation` is not available on Linux so is probably out of scope for Vapor - especially if you were thinking on deploying to Linux?

**Comment by leomeneguzzi** [comment]
In this case, because of CoreLocation, If this works well I'm considering deploy to MacOs
