### ISSUE TITLE
requires a minimum Swift tools version of 5.0.0 (currently 4.2.0)

### ISSUE THREAD

**Issue by Gusont** [vapor/vapor#1998]
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
requires a minimum Swift tools version of 5.0.0 (currently 4.2.0)

Run the Demo

**Comment by Gusont** [comment]
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
requires a minimum Swift tools version of 5.0.0 (currently 4.2.0)

**Comment by calebkleveter** [comment]
You'll need to install the Swift 5 or 5.1 toolchain to build your project. You can do this by either installing the Xcode 11 beta if you are on a paid Apple developer account or you can download and install the toolchain from the [Swift website](https://swift.org/download/#snapshots).

**Comment by 0xTim** [comment]
You could also change the [api-template](https://github.com/vapor/api-template) (since that's what I'm assuming you're talking about) and change the Package.swift to be 4.2 compatible. Vapor 3 will work fine with 4.2, I think there's nothing in the template that is 5.0 specific
