### ISSUE TITLE
can not vapor build on the macos

### ISSUE THREAD

**Issue by zhuiyizhiqiu** [vapor/vapor#2005]
* Vapor Framework version: vapor 3
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.5
<img width="573" alt="屏幕快照 2019-06-17 上午11 01 04" src="https://user-images.githubusercontent.com/16648917/59575715-3a3a6600-90ef-11e9-9ec3-ad03f961c5e1.png">

**Comment by zhuiyizhiqiu** [comment]
vapor new project is successes, but I can not vapor build the project.

**Comment by vzsg** [comment]
What's the output of `swift build` and `xcode-select -p`?

**Comment by zhuiyizhiqiu** [comment]
The fellow is output information
<img width="562" alt="屏幕快照 2019-06-17 下午10 59 55" src="https://user-images.githubusercontent.com/16648917/59614627-b8c8ef00-9153-11e9-8340-5e33f3131563.png">

**Comment by vzsg** [comment]
Okay, makes sense.

You need to run `sudo xcode-select -s /Applications/Xcode.app` or use Xcode -> Preferences -> Locations to select Xcode as the active command line tools location.

> Homebrew lately installs and activates the mostly useless "Command Line Tools for Xcode" package as the active tools when you first install it...

**Comment by zhuiyizhiqiu** [comment]
I have run sudo xcode-select -s /Applications/Xcode.app. But the have an error when I run swift build. 
<img width="563" alt="屏幕快照 2019-06-17 下午11 27 49" src="https://user-images.githubusercontent.com/16648917/59616694-87522280-9157-11e9-825c-780b07670b25.png">

**Comment by vzsg** [comment]
You are standing in your home folder instead of your project folder.
