### ISSUE TITLE
Extracting file content for Environment variable

### ISSUE THREAD

**Issue by alexsteinerde** [vapor/vapor#2006]
# Summary
Proposal for a function for the Environment struct to extract the file content for a name that is given in the environment variables.

# Details
It's more and more common to run Vapor or other services in a Docker container. Typically the run configurations are passed into the container by environment variables. But passwords and secrets should not be stored in a plain text configuration file that is possible in a Git repo. For this Docker has the Docker-secrets feature. Passwords are encrypted and mounted as a file into the container on runtime. The paths to the files are then given in the environment variables.
This repo has an Environment structure to get the values of environment variables. This method is really convenience. But to the content of a file, for example, a password that is stored in a secret and mounted as a file takes some additional work.
If you have multiple secrets for your app you would need to repeat this extra work a lot, extract it into helper functions or as an alternative you could use an insecure way and maybe even hardcode the passwords.

To increase the security of apps and to prevent every developer from reinventing the wheel in every new project, my suggestion is to implement a central solution to get the content of a file that's name is stored in an environment variable.

I already implemented a solution that fits my needs in my own project. But it could be used in this repo or even become more powerful:
```swift 
extension Environment {
    static func secretFromFile(for name: String) throws -> String {
        if let filePath = self.get(name) {
            let url = URL(fileURLWithPath: filePath)
            guard FileManager.default.fileExists(atPath: url.absoluteString) else { throw Error.fileNotFound }
            return try String(contentsOf: url).trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
        } else {
            throw Error.environmentVariableNotFound
        }
    }

    enum Error: Swift.Error {
        case environmentVariableNotFound
        case fileNotFound
    }
}

// Usage
let dbPassword = (try? env.secretFromFile(for: "DB_PASSWORD_FILE")) ?? env.get("DB_PASSWORD")
```

Additionally, some other projects in different fields use a fallback to a plaintext password in the variables as it is shown in my usage example. 
A higher level of implementation could look like this: `env.secret("DB_PASSWORD")`. Internally it would, first of all, try to append "_FILE" to the name and read the file of the content. If this variable or file is not given it falls back to the plain text solution.

Would this feature fit into this repository and the idea behind it or do you have any ideas how it could even be improved?

**Comment by tanner0101** [comment]
I've moved this issue to vapor/vapor since that is where the services code relies currently for the alphas: https://github.com/vapor/vapor/tree/master/Sources/Vapor/Services

I think this feature makes sense to include. 

If I understand correctly, the file contains just the value of the secret key and nothing else? It's not formatted like `.env` files or anything?

If that's the case, then we should be able to do this relatively easily. The only issue is that we might want to consider making this asynchronous using NIO's FileIO type, like DotEnv does currently: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Utilities/DotEnv.swift

This would allow for users to read environment variables on the event loop--in case they wanted to do this from inside a route closure for some reason. We probably don't _need_ to support this, but it's worth bringing up. 

If we think it's fine for this to be a blocking operation (only happens during configuration / boot), then your proposed code seems like a good idea. 

Would you be willing to submit a PR for this?

**Comment by alexsteinerde** [comment]
> If I understand correctly, the file contains just the value of the secret key and nothing else? It's not formatted like .env files or anything?

That's right. It's a simple plain text file that contains the secret value. This section in the Docker documentation describes it very quick: https://docs.docker.com/engine/swarm/secrets/#example-rotate-a-secret

An asynchrony solution would be nice I think as well. I've come across multiple use cases where that would be useful. On startup an `.wait()` can be added so it's more synchronous.
Unfortunately, I've not so much experience with asynchronies file loading. So I've so following two solutions but with the second I would need some more input from you to complete it.
First: 
```swift
static func secret(key: String, on eventLoop: EventLoop) throws -> EventLoopFuture<String> {
    let promise = eventLoop.newPromise(String.self)
    DispatchQueue.global().async {
        if let filePath = self.get(key) {
            let url = URL(fileURLWithPath: filePath)
            guard FileManager.default.fileExists(atPath: filePath) else { return promise.fail(error: Error.fileNotFound) }
            do {
                let value = try String(contentsOf: url).trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
                promise.succeed(result: value)
            } catch {
                promise.fail(error: error)
            }
        } else {
            promise.fail(error: Error.environmentVariableNotFound)
        }
    }
    return promise.futureResult
}
```
Second:
```swift
static func secret(key: String, fileio: NonBlockingFileIO, on eventLoop: EventLoop) throws -> EventLoopFuture<String> {
    if let filePath = self.get(key) {
        return fileio.openFile(path: filePath, eventLoop: eventLoop).flatMap({ (arg) -> EventLoopFuture<ByteBuffer> in
            return fileio.read(fileRegion: arg.1, allocator: .init(), eventLoop: eventLoop)
                .map({ (buffer) -> ByteBuffer in
                    try arg.0.close()
                    return buffer
                })
        }).map({ (buffer) -> (String) in
            // missing
            return ""
        })
    } else {
        throw Error.environmentVariableNotFound
    }
}
```

Finally, I think a very easy to use API is the most important aspect so users use this instead of unsecured plain text passwords. I haven't tried the new ApplicationDelegate implementation in Vapor 4. Please correct me if I'm wrong but in Vapor 3 there is no possibility to access an event loop without creating a new one right? Additionally accessing a fileIO reader is not as easy as `req.eventLoop`, right?

I think a PR would make more sense when some more implementation details are clear. But then I would really like to submit one.
