### ISSUE TITLE
Database connection leakage

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/vapor#2013]
### Steps to reproduce

Hello,

I use postgresql. When I run project on heroku I have  [PostgreSQLError.server.fatal.InitializeSessionUserId: too many connections for role.

I have 20 connections limit on heroku. And this limit is reached very fast.

For accessing connections I use `withPooledConnection`. And from documentation these connections don't require to be released. So I don't release them. I also use implicitly connection through Fluent. I don't use `requestCachedConnection`/`requestPooledConnection` or other methods that require releasing. Can you please help where can be the leakage of connections

* Vapor Framework version:
Vapor 3.3.0
PostgreSQL 1.4.1
FluentPostgreSQL 1.0.0
DatabaseKit 1.3.3
* Vapor Toolbox version:
3.1.10
* OS version:
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"

**Comment by vzsg** [comment]
It's not necessarily a leak. The default configuration of Vapor is really connection hungry - it spawn one worker for each logical CPU core (of which Heroku reports 8), and limits connections to 10 _per worker_. You'll need to cut down on one or both of those parameters.

**Comment by Igor-Palaguta** [comment]
@vzsg Thanks for response.

On heroku we have 8 cores. 20 maximum connections. Does it mean I should set 20/8 == 2 to `DatabaseConnectionPoolConfig`?

**Comment by vzsg** [comment]
Yes. Or you can limit the number of workers to 4 with a NIOServerConfig instance, and limit the connections to 4 with the DatabaseConnectionPoolConfig.

**Comment by Igor-Palaguta** [comment]
Thank you for clarification. So with this setup number of connections should not be more than 17? Will monitor it
