### ISSUE TITLE
Cleanup usage of assumingMemoryBound

### ISSUE THREAD

**Issue by atrick** [vapor/vapor#2017]
Doing a random github search I found unnecessary uses of the unsafe assumingMemoryBound API

https://github.com/vapor/vapor/blob/af2b50e7e37de2edaf3285924678c415a35d2ac3/Sources/Vapor/Multipart/MultipartParser.swift

```
return parser.data.assumingMemoryBound(to: MultipartParser.Context.self).pointee
```

should be

```
return parser.data.load(as: MultipartParser.Context.self)
```

And
```
guard let unsafeBufferStart = unsafeBuffer.baseAddress?.assumingMemoryBound(to: Int8.self) else {
    fatalError("no base address")
}
let unsafeBufferEnd = unsafeBufferStart.advanced(by: unsafeBuffer.count)
if pointer >= unsafeBufferStart && pointer <= unsafeBufferEnd {
```

could be

```
guard let unsafeBufferStart = unsafeBuffer.baseAddress? else {
    fatalError("no base address")
}
let unsafeBufferEnd = unsafeBufferStart.advanced(by: unsafeBuffer.count)
if UnsafeRawPointer(pointer) >= unsafeBufferStart && UnsafeRawPointer(pointer) <= unsafeBufferEnd {
```

And
```
private extension String {
init(cPointer: UnsafePointer<Int8>?, count: Int) {
        let pointer = UnsafeRawPointer(cPointer)?.assumingMemoryBound(to: UInt8.self)
        self.init(decoding: UnsafeBufferPointer(start: pointer, count: count), as: UTF8.self)
    }
```

should be

```
    self.init(decoding: UnsafeRawBufferPointer(start: cPointer, count: count), as: UTF8.self)
```

**Comment by tanner0101** [comment]
There seems to be a lot less of this in Vapor 4, but still some usage points. What are the downsides of using `assumingMemoryBound`?

**Comment by atrick** [comment]
`assumingMemoryBound(to:)` is unsafe in ways that most programmers don't think about. It can introduce undefined behavior whenever two pointers access the same memory via different pointer types, even if those pointers are in completely unrelated pieces of code. So, even if you are careful with pointers with respect to object lifetimes and bounds, the code could be undefined. This could be a problem as the code evolves and pointers are passed across code boundaries where each side makes different assumptions. You generally won't notice the problem at first, but the code could miscompile with newer versions of the compiler.

We need to communicate this much better. I started randomly auditing code last year in expectation of adding better compiler diagnostics. Unfortunately we still don't have those compiler diagnostics, and just haven't gotten back around to working on pointer APIs and docs.
