### ISSUE TITLE
Fetch never ends when invalid tag in dependency

### ISSUE THREAD

**Issue by cparnot** [vapor/vapor#2029]
When issuing a `vapor fetch` command, and the tag referenced in the package file for a dependency does not exist, the command keeps running forever without any error message or explanation.

### Steps to reproduce

	vapor new bug-fetch-stuck
	cd bug-fetch-stuck

Replace the required version of vapor with e.g. "42.42.42"

        .package(url: "https://github.com/vapor/vapor.git", from: "42.42.42"),

	vapor fetch

Goes in infinite wait.

### Expected behavior

It would be nice to have some kind of error message or a timeout. I don't know the internals, but it should know that there is an issue.

### Actual behavior

Goes forever.

### Environment

* Vapor Framework version: (somehow vapor was not able to get it)
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.5

I realize the issue might be in SPM to start with.

**Comment by joscdk** [comment]
Yeah it's an SPM issue, i think it would be better to create an issue on bugs.swift.org

**Comment by cparnot** [comment]
OK, will do. You can close the issue, I suppose...

**Comment by joscdk** [comment]
@cparnot btw. Just tried on my local machine to run:
```
swift build
```
I am using the Swift 5.1 pre-release on Linux, and i get this error:
```
error: the package dependency graph could not be resolved; unable to find any available tag for the following requirements:
    https://github.com/vapor/vapor.git @ 32.0.0..<33.0.0
```
So looks like there have been some progress regarding this :)
