### ISSUE TITLE
Wrong route being used

### ISSUE THREAD

**Issue by rausnitz** [vapor/vapor#2030]
I have two routes with three parameters each. The first parameter is the same static `String` in both. The second parameter is a dynamic `Int` parameter in one and a dynamic `String` parameter in the other. Each has a different static `String` as its third parameter.

Vapor appears to register two distinct routes, but requests that should go to the second one get routed to the first one.

To reproduce:
- Build this repo, which is the API template modified to demonstrate this bug: https://github.com/rausnitz/vapor-parameters-bug
- Do `vapor run routes`, which should output
```
| GET | /test/:int/integer_test   |
+-----+---------------------------+
| GET | /test/:string/string_test |
```
- Do `vapor run`
- Send a GET request to `test/:string/string_test`, e.g. visit `http://localhost:8080/test/a/string_test`.

Expected behavior:
- A successful response.

Actual behavior:
- An error is thrown with the message `Invalid parameter type: string != int`.

Vapor Toolbox: 3.1.7
Vapor Framework: 3.3.0
OS: macOS or Linux

**Comment by tanner0101** [comment]
This is expected behavior in Vapor 3. Only one dynamic parameter may be registered at a given place in the route path. Vapor 4's routing API has been fixed to make this limitation more clear.
