### ISSUE TITLE
Compiler error trying to create a filter in a fluentMySQL query

### ISSUE THREAD

**Issue by bottlehall** [vapor/vapor#2033]
I am trying to implement a JOIN equivalent to the MySQL:

`SELECT * FROM A JOIN B ON A.id = B.id AND A.order = B.order`

The most obvious way of re-creating this in Fluent would seem to be:

let minimal = A.query(on:request).join(\B.id, to:\A.id).filter(\A.order == \B.order)

However, I get:

> Cannot convert value of type 'Bool' to expected argument type 'FilterOperator<_, _>'

I expected it to compile as I have used filters many, many times before. In reviewing my earlier uses in Vapor 3, it transpires they have all been of the form:

`...filter(\A.deleted == false) `

or:

`...filter(\A.value == variable)`

...but not using a second operand that is also a column in the query. I don't know if this is relevant.

* Vapor Framework version: unsure, but `vapor update` done and no change
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.6 (running latest beta of Xcode: Version 11.0 beta 5 (11M382q))

There are quite a few questions on SO with the same error message and all suggest explicitly typing the operands, but I can't seem to find a way of doing this.

**Comment by bottlehall** [comment]
Close. No response. I'll try SO.

**Comment by HugoSay** [comment]
Anyone ending up here : just import Fluent in your file and it should work just fine !
