### ISSUE TITLE
depend SwiftSMTP  vapor xcode failed

### ISSUE THREAD

**Issue by jancywen** [vapor/vapor#2035]
### Steps to reproduce

Package.swift

```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "NewProject",
    products: [
        .library(name: "NewProject", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        /// mail Server
        .package(url: "https://github.com/IBM-Swift/Swift-SMTP", .upToNextMinor(from: "5.1.0"))

    ],
    targets: [
        .target(name: "App", dependencies: ["SwiftSMTP",  "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

```
$ vapor xcode
Generating Xcode Project [Failed]
Completed resolution in 92.42s
error: multiple products named 'Logging' in: Console, swift-log
error: multiple targets named 'Logging' in: Console, swift-log

Error: Could not generate Xcode project: Completed resolution in 92.42s
error: multiple products named 'Logging' in: Console, swift-log
error: multiple targets named 'Logging' in: Console, swift-log
```

### Environment

* Vapor Framework version:
* Vapor Toolbox version: 3.1.10
* OS version:10.14.5 (18F132)

**Comment by vzsg** [comment]
IBM packages are not out-of-the-box compatible with Vapor 3, because of the naming clash that you found in the error output from SPM...

What you can do to get around the issue is adding a new dependency to your Package.swift:

```swift
.package(url: "https://github.com/IBM-Swift/LoggerAPI.git", .upToNextMinor(from: "1.8.0"))
```

With this, the LoggerAPI package (transitive dependency of Swift-SMTP) will be pinned to the last version that doesn't pull in apple/swift-log, and should work.

**Comment by jancywen** [comment]
Today I used a new device to verify it, and I encountered a new problem when I used the command to produce the xcode project, *.xcodeproj did not appear
```
admindeMacBook-Pro:TestDemo bear$ vapor xcode
Generating Xcode Project [Done]
Select the `Run` scheme to run.
Open Xcode project?
y/n> y
Opening Xcode project...
Error: backgroundExecute(code: 1, error: "The file /Users/bear/Roo/Vapor/TestDemo/*.xcodeproj does not exist.\n", output: "")

```
I tried several times, but failed.

**Environment**

- Vapor Framework version:

- Vapor Toolbox version: 3.1.10

- OS version:10.14.5 (18F2058)

**Comment by vzsg** [comment]
Try running `swift package generate-xcodeproj` instead, it will give you a better error message.

My gut feeling says that your active toolchain is messed up (most commonly Homebrew's install script does that by making the Command Line Tools for Xcode package active, which is not enough for SPM).

If that is the case, you must run `xcode-select` to activate your Xcode installation instead.
For example:

```
sudo xcode-select -s /Applications/Xcode.app
```

**Comment by jancywen** [comment]
My problem is because my Xcode(version: 10.3)  Command Line Tools no xcode selected. Select the only one then ran as expected.
