### ISSUE TITLE
Upgrade SwiftNIO Http/2 due to security notice

### ISSUE THREAD

**Issue by alexsteinerde** [vapor/vapor#2036]
An official security notice was published at the swift forum that provides details about some security issues with SwiftNIO HTTP/2: https://forums.swift.org/t/swiftnio-http-2-security-notice/27855

As I can see vapor is still using version 1.0.0. 
Are there any blocking tasks before upgrading to the package version 1.5.0 to fix the security issues?

### Environment

- Vapor master branch

**Comment by stolenbrain** [comment]
I don't think it's necessary, since ```.package(url: from version:)``` will pull the latest minor version from the specified repo. The update to the NIO Http2 is already pulled from 1.6.1 as of today.

**Comment by tanner0101** [comment]
Also, the `Package.resolved` file that ships with our template is already at `1.14`: https://github.com/vapor/api-template/blob/master/Package.resolved#L113-L120 This means that even if someone doesn't run `swift package update`, they will be getting a fairly new version. 

I do think we could bump up the from to `1.5.0` though. That shouldn't break anything and will ensure that people are getting critical fixes 👍.

**Comment by tanner0101** [comment]
Vapor 4 requires `1.11.0` atm: 

```swift
.package(url: "https://github.com/apple/swift-nio-http2.git", from: "1.11.0")
```
