### ISSUE TITLE
Read Route/Request metadata in Middleware.

### ISSUE THREAD

**Issue by MrLotU** [vapor/vapor#2046]
[`Route<Output>`](https://github.com/vapor/routing-kit/blob/3/Sources/Routing/Register/Route.swift#L8) conforms to `Extendable` allowing you to pass in extra metadata when registering your route like so:
```swift
router.get("hello") { req in
    return "Hello, world!"
}.extend.set("someProperty", to: "someValue")
```
However, from the digging that I've done today (though I might've overlooked something) there is no place to read this data, for example in `Middleware` because `TrieRouter` and in an extension `EngineRouter` don't return `Route<Output>` but `Output` from their `route(request:)` functions, which gets rid of all metadata.

I see two possible solutions to the issue I'm facing with this (and I'm willing to PR either one). One would be to make `Router`s API return the `Route<Output>` instead of just `Output`. I think this is quite a big undertaking and will also end up being a breaking change.

The other option I see is to make `Request` conform to `Extendable`. This would allow the following setup:
```swift
router.get("hello") { req in
    req.extend.set("someProperty", to: "someValue")
    return "Hello, world!"
}

// MyMiddleware
public func respond(to request: Request, chainingTo next: Responder) throws -> Future<Response> {
    let myProperty = request.extend.get("someProperty", "unknown")
    // Do something with myProperty
    return try next.respond(to: request)
}
```
I personally think this is the most elegant solution and it will also not have any breaking changes. I'm opening this issue to get some feedback & opinions on both implementations, and to see if there are concrete reasons that `Request` is not `Extendable` already 😄

**Comment by tanner0101** [comment]
This should be possible now that `Request` has an optional `route` property.
