### ISSUE TITLE
Container.shutdown() was not called before Container deinitialized

### ISSUE THREAD

**Issue by AnyCPU** [vapor/vapor#2049]
A new vapor 4 app crashes immediately under the wrk

Full message:
Assertion failed: Container.shutdown() was not called before Container deinitialized: file ../vapor/Sources/Vapor/Services/Container.swift, line 103

### Steps to reproduce

 vapor new --branch=4 vp4
cd vp4
vapor update
vapor build
vapor run
wrk -c 100 -t 100 -d 30s http://localhost:8080

### Expected behavior

No crash

### Actual behavior

It usually crashes, but it might not crash very very rarely.

### Environment

* Swift version: Apple Swift version 5.1 (swiftlang-1100.0.270.6 clang-1100.0.32.1)
Target: x86_64-apple-darwin18.7.0

* Vapor Framework version: 4.0.0-alpha.3.1.1

* Vapor Toolbox version: Vapor Toolbox: 3.1.10

* OS version: macOS 10.14.6, Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by MrLotU** [comment]
Seems not to happen in Xcode (v11b6) but I can repro from terminal.

**Comment by tanner0101** [comment]
I'm unable to repro this as well. Try running `swift package update` and let us know if you continue to see this error.
