### ISSUE TITLE
HTTPServerResponder is not thread safe.

### ISSUE THREAD

**Issue by MrLotU** [vapor/vapor#2050]
When running Vapor 4's API template with the Thread Sanitizer under heavy load (wrk) there is an access race in `HTTPServerResponder`.
```
Swift access race in closure #1 (Vapor.Container) throws -> Vapor.Responder in Vapor.(HTTPServerResponder in _1A326A4C8972E7AA192E4DD7599C3E6D).respond(to: Vapor.Request) -> NIO.EventLoopFuture<Vapor.Response> at 0x7b0c0005ff10
```
### Steps to reproduce

`vapor new --branch=4 vp4`
`cd vp4`
`vapor update`
`open Package.swift` (Xcode 11 SPM support)
Enable thread sanitizer (`CMD + OPT + R` -> Diagnostics -> Thread Sanitizer)
Run project
Run `wrk -c 100 -t 100 -d 30s http://localhost:8080`

### Expected behavior

Nothing much, app should work fine.

### Actual behavior

Thread Sanitizer reports access races in `HTTPServerResponder`

### Environment

* Vapor Framework version: 4.0.0-alpha.3.1.1
* Vapor Toolbox version: 3.1.10
* Xcode version: Xcode 11 Beta 6
* OS version: MacOS 10.14.6

**Comment by musamuss** [comment]
вс, 8 сент. 2019 г., 14:23 Jari (LotU) <notifications@github.com>:

**Comment by tanner0101** [comment]
This has been fixed. Running `wrk` no longer reports race conditions.
