### ISSUE TITLE
configure(:) called twice on app start (Vapor 4)

### ISSUE THREAD

**Issue by deze333** [vapor/vapor#2055]
Each time an app starts in Vapor 4, its `config` function gets called twice:

```swift
func configure(_ s: inout Services) throws {
    print("• Config is called")
   // ...
}
```

Is that an intended behaviour or a bug?

### Steps to reproduce

Put a print statement and run the app. 

### Environment

* Vapor Framework version: 4.0.0-alpha.3.1.1
* Vapor Toolbox version: 3.1.10
* OS version: 10.14.6

**Comment by tanner0101** [comment]
This was expected behavior in early versions of Vapor 4. However, recent versions should no longer do this. `configure` will be called once per process.
