### ISSUE TITLE
React-Vapor 'hybrid' app

### ISSUE THREAD

**Issue by dekhaus** [vapor/vapor#2058]
Hi All

I writing to solicit the opinions of the group as to whether or not its possible to configure Vapor to serve a React app (or any JS Framework based front-end app) as its static assets.

I've used this approach on several project with Django and its works really well.  I realize there are advantages to creating two separate apps - one for the front-end and one for the back-end.  

There are also advantages to creating a combined / 'hybrid' app - consolidated code bases, simpler deploys, easier authentication, etc...

This hybrid approach relies on creating a 'catch-all' index.html route/page - in Django it looks like this ....

```
re_path('.*', TemplateView.as_view(template_name='index.html')),
 ```

Next - npm is run to create and transfer all the 'build' assets (css, js, html) to a build directory that index.html page is setup to reference.   As far Vapor would be concerned its just server html, css and js.

So - has anyone tried this ?

Can anyone think of any technical reasons why this wouldn't work using Vapor ?

Thanks
Dave

**Comment by 0xTim** [comment]
This has definitely been done before - you can just put the static assets in the `Public` directory and use a catch all route to return the main page

**Comment by Joannis** [comment]
I've done it, too, the way Tim mentioned. Closing this, but if anyone's having issues be sure to check out discord.
