### ISSUE TITLE
Vapor Models should be cross-platform

### ISSUE THREAD

**Issue by mcritz** [vapor/vapor#2060]
### Steps to reproduce

Bootstrap new Vapor4 project with `vapor new MyProject -branch=4`

### Expected behavior

Bootstrap code should support write-less-code philosophy. Bootstrap template should separate generic code from Vapor-specific code.

Suggestion:
Create a template that automatically assumes that the developer would like to create a cross-platform app that reuses server side code on the client.

### Environment

* Vapor Framework version:
4 alpha

* Vapor Toolbox version:
3.1.10

* OS version:
macOS 10.14.6

**Comment by tanner0101** [comment]
Could you elaborate on this? The Vapor template should work cross platform and is tested on all of Vapor's supported OSes.

**Comment by mcritz** [comment]
@tanner0101 when i say cross-platform I mean between server and client

**Comment by 0xTim** [comment]
Unfortunately the changes to Fluent makes this difficult to do. However, for 'real' projects it isn't really a problem, and the improvements to Fluent more than make up for it.

The general pattern (and something that should be highlighted in the docs) is to have your `User` model that is saved to the database and then your `CreateUserData` and `User.Public` models (or similar) that you accept and return. This makes it much more flexible to remove fields and add fields you don't necessarily save in the database. For instance in the `CreateUserData` model you might have `password` and `confirm Password` to validate the password, but your `User.Public` won't have any `password` field at all.

**Comment by mcritz** [comment]
@0xTim My dude. Our project is very “real”. And this is very much an inconvenience, if not an outright problem.

I think I can see why the team made the architectural decisions. But, it’s less elegant as a developer.

What we’ve got is a Framework that I share between different clients and the Vapor 3 backend. It works well enough for our purposes. The code is reusable. Sometimes we move functionality between server and client and _was_ a benefit of choosing Vapor. Less code. More reuse. More flexibility. The worst case scenario for models was adding an `id: UUID?` where the client may not have needed one.

I think I can move this around by creating `ServerModel` class that hoists `ServerModel.FrameworkModel` but this is less elegant than Vapor 3.

**Comment by tanner0101** [comment]
As Tim said using separate DTOs is the recommended approach here. From our experience and lengthy discussions with the community about this change, this is what most people were already doing in Vapor 3. Regardless, It's a good idea to avoid coupling your database models to your DTOs otherwise things can become difficult to maintain in the long run. If you don't like this pattern, an alternative approach would be to use SQLKit or the underlying database drivers directly.
