### ISSUE TITLE
Unable to parse JSON with invalid Content-type

### ISSUE THREAD

**Issue by john-crossley** [vapor/vapor#2065]
Unable to parse JSON with an invalid Content-type.

When trying to hit another API to process its "JSON" they return the `Content-type` as `text/javascript` (which is wrong, it should actually be `application/json`) to deal with this problem I tried to create a custom `ContentConfiguration` to process this response with vapor's `JSONDecoder()` like so:

```swift
var contentConfig = ContentConfiguration.default()
    contentConfig.use(decoder: JSONDecoder(), for: .init(type: "text", subType: "javascript", parameters: ["charset": "utf-8"]))
ContentConfiguration.global = contentConfig
```

This does actually work, vapor picks this up and tries to parse the request with the `JSONDecoder` The problem arises inside the `JSONCoders+Content.swift` there's a check that throws `Abort(.unsupportedMediaType)` 

```swift
headers.contentType == .json || headers.contentType == .jsonAPI else {
    throw Abort(.unsupportedMediaType)
}
```

this means that we cant parse the response as JSON using the built in JSONDecoder.

This issue can easily be fixed but it all depends on the design decision. Would it make more sense to re-create a custom JSONDecoder that can handle this or does it make sense for the vapor JSONDecoder to attempt to parse the data. 

Seems that the JSONDecoder shouldn't be concerned about HTTP Headers. ✌️

### Environment

* Vapor Framework version: Vapor 4.0.0-alpha.2
* Vapor Toolbox version: 3.1.10
* OS version: macOS Catalina

**Comment by jamesruston** [comment]
As a quick fix for anyone else running into this you can create your own custom decoder like this 

```swift
class CustomDecoder: ContentDecoder {
    let jsonDecoder = JSONDecoder()
    
    func decode<D>(_ decodable: D.Type, from body: ByteBuffer, headers: HTTPHeaders) throws -> D
        where D: Decodable {
            let data = body.getData(at: body.readerIndex, length: body.readableBytes) ?? Data()
            return try jsonDecoder.decode(D.self, from: data)
            
    }
}
```

and register it

```swift
var contentConfig = ContentConfiguration.default()
contentConfig.use(decoder: CustomDecoder(), for: .init(type: "text", subType: "javascript", parameters: ["charset": "utf-8"]))
ContentConfiguration.global = contentConfig
```

I agree though that the decoder itself shouldn't have any knowledge of HTTP headers.

**Comment by vzsg** [comment]
There's an even quicker workaround: you can overwrite the header in the Response, allowing ContentDecoder to do its job. (I agree that Vapor shouldn't be this zealous, but c'est la vie.)

```swift
client.get(...)
    .flatMap { resp in
        resp.http.contentType = .json
        return resp.content.decode(SomeType.self)
    }
```

**Comment by tanner0101** [comment]
I've removed the content-type check in JSONDecoder's content conformance. This should allow you to register `JSONDecoder` to the `text/javascript` media type without issue 👍
