### ISSUE TITLE
consider enabling TSan on all repos

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2066]
Swift 5.1 now supports TSan (thread sanitizer) on Linux (and it always has supported macOS). Given that Vapor 4 will be 5.1 only I think you should definitely consider always running

     swift test --sanitize=thread

instead of just `swift test`. That way a large number of threading issues will be found much earlier.

**Comment by tanner0101** [comment]
This has been added on all repos. Thanks @weissi !
