### ISSUE TITLE
consider specifying platform in Package.swift

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2067]
Since Swift 5.0, SwiftPM supports specifying the supported platforms minimum version like so:

```swift
let package = Package(
    name: "vapor",
    platforms: [
       platforms: [.macOS(.v10_14), .iOS(.v12), .tvOS(.v12), .watchOS(.v5)],
    ],
    products: [...],
    [...]
```

Possibly somewhat unintuitively, not specifying `platforms` means all platforms in the _oldest_ versions. That, on mac/iOS has two problems:

- you sometimes get suboptimal code (because it has to sometimes include shim code to make some stuff work on old OSes)
- you have to use `#if available(...)` around a lot of things that got introduced in Foundation later than 10.9 which is a lot of stuff. Especially around the new, much improved `Process` stuff.

Specifying a more reasonable platform (for Vapor I'd recommend macOS 10.14 or 10.15 probably) solves both of those issues.

Why do I file this issue now? Upping the `platforms` versions is probably a SemVer major change, so it should be done before v4. The other reason is that all Vapor consumers will also need to specify the same `platforms` stanza, so you should add it to your migration guide (from Vapor 3 to 4) as well as to your templates.

CC @lukasa @aciidb0mb3r, agree? Does this make sense?

---

Why does SwiftNIO not specify the versions it actually supports? Simply because we missed it for `2.0.0` and now we have to wait until `3.0.0` when we'll be able to close the issue (https://github.com/apple/swift-nio/issues/1049) we have for that.

**Comment by MrLotU** [comment]
Closed by #2070
