### ISSUE TITLE
Reflection issue when using CodingsKeys

### ISSUE THREAD

**Issue by scsinke** [vapor/vapor#2068]
When using `CodingsKeys` in a Model, Vapor is unable to reflect them when using `.find(id, on: req)` when retrieving a model from the database.
[repository](https://gitlab.com/wifisnoopers/wifisnooper)

### Steps to reproduce

Model
```Swift
import Foundation
import Vapor
import FluentPostgreSQL
import FluentPostGIS

struct Hotspot: PostgreSQLModel {
    static let entity = "hotspot"
    
    var id: Int?
    var ssid: String
    var password: String?
    var passwordType: String?
    var location: GeographicPoint2D
    
    enum CodingKeys: String, CodingKey {
        case ssid, password, passwordType = "password_type", location
    }
}
```

Controller
```Swift
struct HotspotController {  
    func getById(_ req: Request) throws -> Future<Hotspot> {
        let id = try req.parameters.next(Int.self)
        let hotspotService = try req.make(HotspotService.self)
        
        return hotspotService.getId(req, id: id).thenThrowing() { hotspot in
            guard let hotspot = hotspot else {
                throw Abort(HTTPResponseStatus.notFound)
            }
            return hotspot
        }
    }
}
```

Service
```Swift
struct HotspotService {    
    func getId(_ req: Request, id: Int) -> Future<Hotspot?> {
        return Hotspot.find(id, on: req)
    }
}
```

### Expected behavior
Vapor should be able to reflect the `passwordType` using `CodingsKeys` and `return Future<Hotspot?>`

### Actual behavior
When using CodingsKeys the application will crash as follows:
```
Fatal error: Could not reflect property `Swift.WritableKeyPath<App.Hotspot, Swift.Optional<Swift.Int>>`.: file 
/Users/steincarstensinke/Documents/School/mad/wifisnooper/.build/checkouts/fluent/Sources/Fluent/Query/FluentProperty.swift, line 15
2019-10-02 11:18:50.192553+0200 Run[56813:2144125] Fatal error: Could not reflect property `Swift.WritableKeyPath<App.Hotspot, Swift.Optional<Swift.Int>>`.: file 
/Users/steincarstensinke/Documents/School/mad/wifisnooper/.build/checkouts/fluent/Sources/Fluent/Query/FluentProperty.swift, line 15
```

When removing the `CodingsKeys` and change `passwordType` to `password_type` the application is working as aspected. Although this is a workaround and not an expected behaviour.

When using: 
```Swift
    Hotspot.query(on: req).all()
```
`CodingKeys` do work. 

### Environment

* Vapor Framework version: 3.3.0
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.6

**Comment by 0xTim** [comment]
@scsinke you aren't specifying the ID in the coding keys, was that intentional? My guess is that by doing that, the Fluent can't find an ID property hence the crash (It's looking for an optional Int)

**Comment by hfhbd** [comment]
I guess @scsinke won't publish the internal id, so its not included in `CodingKeys`. But id doesn't have an default value, so the compiler should fail, because the compiler cannot synthesize your Model to Decodable.

Default failing Codable Implementation
error: cannot automatically synthesize 'Decodable' because 'id' does not have a matching CodingKey and does not have a default value

    struct T: Codable {
        let id: Int?
        let s: String

        enum CodingKeys: String, CodingKey {
            case s
        } 
    }

    let s = """
        { "s":"asdf" }
    """.data(using: .utf8)!

    let t = try? JSONDecoder().decode(T.self, from: s)
    print(t)

**Comment by MrLotU** [comment]
I think @0xTim is correct here. The reason the compiler does not raise anything is because your model does not conform to `Codable`. It just happens to have a `CodingKeys` enum inside of it. Could you try adding `id` to your `CodingKeys` and report back if it's still broken @scsinke ?

**Comment by scsinke** [comment]
I will try it out tomorrow and share my findings.

**Comment by scsinke** [comment]
@0xTim was right. It was indeed necessary to specify the id key. I thought only strings where needed in the CodingKeys. I will close this issue.
