### ISSUE TITLE
Variables defined in .env file are not available during configuration

### ISSUE THREAD

**Issue by kaishin** [vapor/vapor#2090]
The environment variables are not available through `Environment.get()` during the app configuration phase; where they'd be most used.

### Steps to reproduce

1. Create a new app using the api-template.
2. Reference a variable using `Environment.get()` somewhere in the body of `configure(_ app: Application)`.
3. Run the app from the CLI using `vapor build && vapor run`

### Expected behavior 

- The value of the variable is available.

### Actual behavior

- The `Environment.get()` returns `nil`.

PS: The same variable can be accessed later on, for instance as a response to a request. 

### Environment

* Vapor Framework version: 4.0.0-beta.1
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.15 and Ubuntu 18.04

### Additional Info

* A sample project is attached.
[sample.zip](https://github.com/vapor/vapor/files/3795805/sample.zip)

**Comment by tanner0101** [comment]
This should be possible now with the latest version of Vapor 4. `.env` files are loaded during `Application.init` which now happens _before_ the `configure` method is called.
