### ISSUE TITLE
"todo" object in new project not persisting with default config?

### ISSUE THREAD

**Issue by jazzychad** [vapor/vapor#2092]
When I make a new project with `vapor new <AppName>` I try to create a todo item with
`curl -X POST -d "id=1&title=sing" http://myserver.com/todos` and I get back a 200 response with the json'ified object: `{"id":1,"title":"sing"}`

Now when I visit `http://myserver.com/todos` I still only see `[]` as the output.

### Steps to reproduce

```
$ vapor new AppName
$ vapor build
$ vapor run
```
visit `localhost:8080/todos` and see initial output of `[]`
`curl -X POST -d "id=1&title=sing" http://localhost:8080/todos` and get back a json object
visit `localhost:8080/todos` again and still see `[]`

### Expected behavior

I would expect to see my new todo object in the array at `localhost:8080/todos`

### Actual behavior

I still only see an empty array of `[]`

### Environment

I have tried this same set of steps on my local Macbook and an Ubuntu 18.04 server

configuration.swift is the default config from running `vapor new AppName`

```
import FluentSQLite
import Vapor

/// Called before your application initializes.
public func configure(_ config: inout Config, _ env: inout Environment, _ services: inout Services) throws {
    // Register providers first
    try services.register(FluentSQLiteProvider())

    // Register routes to the router
    let router = EngineRouter.default()
    try routes(router)
    services.register(router, as: Router.self)

    // Register middleware
    var middlewares = MiddlewareConfig() // Create _empty_ middleware config
    // middlewares.use(FileMiddleware.self) // Serves files from `Public/` directory
    middlewares.use(ErrorMiddleware.self) // Catches errors and converts to HTTP response
    services.register(middlewares)

    // Configure a SQLite database
    let sqlite = try SQLiteDatabase(storage: .memory)

    // Register the configured SQLite database to the database config.
    var databases = DatabasesConfig()
    databases.add(database: sqlite, as: .sqlite)
    services.register(databases)

    // Configure migrations
    var migrations = MigrationConfig()
    migrations.add(model: Todo.self, database: .sqlite)
    services.register(migrations)
}
```

* Vapor Framework version: `Error: GeneralError(message: "Unable to locate vapor dependency")`
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.14.6 and Ubuntu 18.04

**Comment by jazzychad** [comment]
Hmm, ok.. if I omit the `id` parameter in the POST body then it works as expected, and the id is auto-generated. This is slightly surprising, but maybe intended behavior?

**Comment by grundoon** [comment]
I don't think many would argue that is not at minimum *confusing* behavior (whether the status and JSON should be returned under this condition, when the db layer itself has not actually reported an error to relay, is perhaps a separate issue), but it is indeed essentially intended and documented:

> Saves the model, calling either create(...) or update(...) depending on whether the model already has an ID.
> 
> If you need to create a model with a pre-existing ID, call create instead. 

https://api.vapor.codes/fluent/3.2.0/Fluent/Protocols/Model.html#/s:6Fluent5ModelPAAE4save2on3NIO15EventLoopFutureCyxG11DatabaseKit0I11Connectable_p_tF
