### ISSUE TITLE
Expired cookie is not cleared

### ISSUE THREAD

**Issue by pankajsoni19** [vapor/vapor#2095]
https://github.com/vapor/vapor/blob/318af638c3d19f2cb9233d33b2c9d9a5e15730a9/Sources/Vapor/Sessions/SessionsMiddleware.swift#L82

When creating cookie we specify domain. However the expired cookie is created statically without the config domain. Browser does not logout the user.

Create cookie with correct domain attribute.

```
let cookie = self.config.cookieFactory("")
cookie.expires = Date(timeIntervalSince1970: 0)

res.http.cookies[self.config.cookieName] = cookie
```

**Comment by pankajsoni19** [comment]
## Hotfix:

This happens when cookie is set with domain. The Session middleware generating cookie, is a static import. It does not include the domain for setting clear cookie header.

I solved this by creating my own custom middleware and generating correct cookie. Basically it sees if response has a cookie set with my configured cookie name, and then adds domain to it, and then re-adds it back to response.

```
public final class CookieMiddleware: Middleware {
    
    public func respond(to req: Request, chainingTo next: Responder) throws -> Future<Response> {
        return try next.respond(to: req).flatMap { res in
            let config = try req.make(SessionsConfig.self)
            
            if var cookie = res.http.cookies[config.cookieName], cookie.string == "" {
                cookie.domain = GLOBAL_CONFIG.domain
                res.http.cookies[config.cookieName] = cookie
            }
            
            return req.eventLoop.newSucceededFuture(result: res)
        }
    }
}
```

**Comment by tanner0101** [comment]
It should be possible to customize `SessionMiddleware`'s cookie using `SessionsConfiguration.cookieFactory`. If you're setting cookies manually, then something like the  `CookieMiddleware` you're using here seems like a good solution 👍
