### ISSUE TITLE
Vapor 4 BETA new project does not compile

### ISSUE THREAD

**Issue by jesuslg123** [vapor/vapor#2105]
Hi!

When creating a new project using the beta (on Mac OS Catalina), project template does not compile. I am not fully sure if I did something wrong, but here are my founds in case some one can reply for a fix or are actually issues.

Issues found:

- Package.swift:  The package product 'Vapor' requires minimum platform version 10.14 for the macOS platform, but this target supports 10.10

Solution applied on `Package.swift`: 
```
platforms: [
     .macOS(.v10_15),
],
```

- routes.swift:3: `Use of undeclared type 'Container'` (This may now be `ContentContainer`?) 
- configure.swift:6: `Value of type 'Services' has no member 'extend'`
- configure.swift:11: `Value of type 'Services' has no member 'register'`
- App.swift:4: Application(environment: environment) {...} ```Cannot invoke initializer for type 'Application' with an argument list of type '(environment: Environment, @escaping (inout Services) -> ())'```

### Steps to reproduce

- Mac OS Catalina 10.15.1
- Install vapor beta using brew: `brew install vapor/tap/vapor-beta`
- Create a new project: `vapor-beta new hello -n`
- Open the project: `open Package.swift`
- Compile the project
- The above issues will appear.

### Expected behaviour

The expected behaviour is be able to run the Vapor default template app. 

### Actual behaviour

The current behaviour is not able to run the Vapor default template app due to compilation errors mentioned above. 

### Environment

* Vapor Framework version: Vapor 4 Beta 1
* Vapor Toolbox version: `vapor-beta --version` does not return version information. Unknown command "--version"
* OS version: Mac OS Catalina 10.15.1

Thanks!

**Comment by mcritz** [comment]
Can consistently reproduce this bug.

**Comment by mcritz** [comment]
@jesuslg123 In case you (or someone else reading this) is blocked, you can work around the documentation by bootstrapping a Vapor 4 beta project with the following command that uses the “old” (current / vapor-3) toolbox.

`vapor new PROJECTNAME --branch=4`

**Comment by jesuslg123** [comment]
I have not manage to try it as I'm now facing issues with the openssl version.
I have manually installed following the infor on the issue https://github.com/vapor/vapor/issues/2104, but still getting the openssl issue...

**Comment by tanner0101** [comment]
Latest Vapor 4 no longer requires OpenSSL 👍
