### ISSUE TITLE
Vapor is requiring Migrations

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#2106]
When starting a Vapor 4 API project it immediately fails saying "No services registered for Migrations: file ..../Vapor/Services/Services.swift"

I can't use Migrations because my SQL server version is too old.  Also, this isn't a Code-First database.  The database is already there, and I don't want the Vapor project screwing with it.

### Environment

* Vapor Framework version: 4.0.0-beta
* Vapor Toolbox version: 3.1.10
* OS version: 10.15.2 beta

**Comment by grosch** [comment]
I ended up putting this in my `configure.swift` file to make it work, but I shouldn't have to do this:

```swift
app.register(Migrations.self) { _ in Migrations() }
```

**Comment by RamblinWreck77** [comment]
FYI, in beta 2 the way to do this is now:

```
extension Application {

    var migrations: Migrations {
        let migrations = Migrations()
        migrations.add(YourModel(), to: .psql)
        return migrations
    }
}
```

**Comment by tanner0101** [comment]
This has been fixed in beta.2

Here's an example: https://github.com/vapor/api-template/blob/4/Sources/App/configure.swift#L14
