### ISSUE TITLE
WebSocket timeout

### ISSUE THREAD

**Issue by umbri** [vapor/vapor#2107]
* Vapor Framework version: Vapor 4.0.0 Beta 1

```onClose``` is never called if connection is lost (not sent .connectionClose opcode), ex: client loses power, ethernet cables pulled out etc... 

Related to #1806

**Comment by bridger** [comment]
This might be fixable by implementing the ChannelInactive  callback, as done in https://github.com/IBM-Swift/Kitura-WebSocket-NIO/pull/53. I plan to investigate this.
