### ISSUE TITLE
Dockerfile doesn't work

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#2112]
The web.Dockerfile that comes with the beta 4 template doesn't seem to work.

It gets near the end and then does this:

> Step 12/15 : COPY --from=builder /build/bin/Run .
 ---> 66831dd5aa20
Step 13/15 : COPY --from=builder /build/lib/* /usr/lib/
COPY failed: stat /var/lib/docker/overlay2/002460ec93410af2892b164d93f2b679d1f730889e80de1e3d9900c8fc48824b/merged/build/lib/libicudataswift.so.61.1: no such file or directory

I also had to explicitly add these packages to get it past the compile stage:

> openssl libssl-dev zlib1g zlib1g-dev

* Vapor Framework version: 4.0.0-beta.1
* Vapor Toolbox version: 3.1.10 (even though brew said 3.1.11)
* OS version: Catalina

**Comment by tanner0101** [comment]
I've updated the dockerfile here: https://github.com/vapor/api-template/blob/4/web.Dockerfile

Let me know if that works for you. Thanks :)
