### ISSUE TITLE
The query of the request

### ISSUE THREAD

**Issue by sergiusX** [vapor/vapor#2115]
### Steps to reproduce

groupedRouter.get("updateInfo", use: updateInfo)

 func updateInfo(_ req: Request) throws -> Future<Result> {
        return try req.client().get("http://...........................

I call the code from Postman - 
http://83.166.240.100:8080/router/updateInfo

### Expected behavior
On the MacOS (localhost) this is not a problem - I get the response

but on Linux 18.04 I get the error "Something went wrong" and if you call this method a couple more times vapor just closes on the command line.

[ ERROR ] URLError(_nsError: error:0DFFF0A1:lib(13):func(4095):reason(161)) (ErrorMiddleware.swift:26)

Swift 5.0
Vapor Toolbox: 3.1.10

**Comment by tanner0101** [comment]
This seems like an issue with URLSession but there's not really enough info here to help debug it.
