### ISSUE TITLE
RouteCollection does not register in latest beta 

### ISSUE THREAD

**Issue by mcdappdev** [vapor/vapor#2130]
When creating a controller that conforms to RouteCollection the routes are never actually registered.

### Steps to reproduce
1. Create a new `RouteCollection` controller and implement the `boot()` method 
2. Register that controller in `routes.swift`
3. Attempt to hit the route

### Expected behavior
The route should be registered

### Actual behavior
The route is not registered 

### Environment

* Vapor Framework version: 4.0.0-beta.3
* Vapor Toolbox version: 3.1.7
* OS version: 10.14.6

**Comment by tanner0101** [comment]
I'm unable to repro this in latest Vapor 4. I've added a test case to prevent regression 👍
