### ISSUE TITLE
vapor new --auth login problem in docker ubuntu container

### ISSUE THREAD

**Issue by thomasgueldenerg** [vapor/vapor#2134]
Hallo everybody,
I hope someone can help me.
I use the vapor new --auth example under a ubuntu docker container and after the login, I get out of the vapor app. I tried it under ubuntu:18.04 and 16.04, same problem.
To build a user is no problem, but after the login, I'm out of the app. When I run the example out of the container it is still working. There is no problem.
Can someone help me?

**Comment by thomasgueldenerg** [comment]
When I use  .build/debug/Run in the ubuntu container a message is coming: ILLEGAL INSTRUCTION. And vapor server is crashing.

**Comment by 0xTim** [comment]
Can you post the full output with the crash etc

**Comment by thomasgueldenerg** [comment]
Hallo 0xTim,
thanks for your answer. This is all what I get:

Server starting on http://0.0.0.0:8080
[sqlite] [2019-12-20 14:38:40 +0000] INSERT INTO "User" ("passwordHash", "email", "name") VALUES (?, ?, ?) ["$2b$12$dXLaAhncQj1iFyLDIwfEVu2iISO3Rcgtv7oKggsTt4Tc3hI.UOXBm", "thomas.gueldenberg@gmx.de", "hans"]
[sqlite] [2019-12-20 14:38:49 +0000] SELECT * FROM "User" WHERE "User"."email" = (?) LIMIT 1 OFFSET 0 ["thomas.gueldenberg@gmx.de"]
[sqlite] [2019-12-20 14:38:50 +0000] INSERT INTO "UserToken" ("userID", "string", "expiresAt") VALUES (?, ?, ?) [1, "WSGcvHG1M8ACW3lkPL631g==", 1576870730.302701]
Illegal instruction
root@b1e2acb7b982:/swiftcode/vapordbauth# 

I will reset the docker and make everything new. I think, I have a problem with SwiftShims, is that possible? I think I have to install Ubuntu:18.04 and vapor  step by step to find the problem

**Comment by thomasgueldenerg** [comment]
Hallo 0xTim,
thanks for the answer. Here is all what I get:
, 0xd16ec58063764cc6a32f67c1f902ebf2, 1]
[sqlite] [2019-12-20 14:38:28 +0000] SELECT * FROM "fluent" WHERE "fluent"."name" = (?) LIMIT 1 OFFSET 0 ["Todo"]
[ INFO ] Preparing migration 'Todo' (/swiftcode/vapordbauth/.build/checkouts/fluent/Sources/Fluent/Migration/Migrations.swift:111)
[sqlite] [2019-12-20 14:38:28 +0000] CREATE TABLE "Todo" ("id" INTEGER NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "userID" INTEGER NOT NULL, CONSTRAINT "fk:Todo.userID+User.id" FOREIGN KEY ("userID") REFERENCES "User" ("id")) []
[sqlite] [2019-12-20 14:38:28 +0000] INSERT INTO "fluent" ("createdAt", "updatedAt", "name", "id", "batch") VALUES (?, ?, ?, ?, ?) [1576852708.588103, 1576852708.588103, "Todo", 0x1badc353f8604313930bbbc8a04203b1, 1]
[ INFO ] Migrations complete (/swiftcode/vapordbauth/.build/checkouts/fluent/Sources/Fluent/Migration/MigrationConfig.swift:73)
Running default command: .build/debug/Run serve
Server starting on http://0.0.0.0:8080
[sqlite] [2019-12-20 14:38:40 +0000] INSERT INTO "User" ("passwordHash", "email", "name") VALUES (?, ?, ?) ["$2b$12$dXLaAhncQj1iFyLDIwfEVu2iISO3Rcgtv7oKggsTt4Tc3hI.UOXBm", "thomas.test@abc", "hans"]
[sqlite] [2019-12-20 14:38:49 +0000] SELECT * FROM "User" WHERE "User"."email" = (?) LIMIT 1 OFFSET 0 ["thomas.test@abc.de"]
[sqlite] [2019-12-20 14:38:50 +0000] INSERT INTO "UserToken" ("userID", "string", "expiresAt") VALUES (?, ?, ?) [1, "WSGcvHG1M8ACW3lkPL631g==", 1576870730.302701]
Illegal instruction
root@b1e2acb7b982:/swiftcode/vapordbauth#

I think I have a problem during the Ubuntu:18.04 and Vapor installation. Maybe the problem is the SwiftShims, because vapor server stops after the login and the token.string is an object of SwiftShims, so maybe there is the problem. What do you think? Is that possible?

**Comment by 0xTim** [comment]
Do you get the same behaviour on macOS? It looks like something it crashing because of a force unwrap somewhere, in Xcode you'll get the line it crashes on

**Comment by thomasgueldenerg** [comment]
No, when i'm not in the ubuntu container everything works fine. And when I'm in Xcod, there is also no problem. I reset the docker now, and I find now some problems with installing vapor. 
one is this:
GPG error: https://repo.vapor.codes/apt bionic Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E72020EB309474F

**Comment by thomasgueldenerg** [comment]
Then I'm trying this:
wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | sudo apt-key add -
echo "deb https://repo.vapor.codes/apt $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/vapor.list
sudo apt-get update

But now I get bash: lsb_release: command not found

**Comment by 0xTim** [comment]
Which Dockerfile are you using? You don't need to use one that install Swift like that, you can either use the official Swift ones and install any dependencies, or use `vapor/swift:5.1` which has everything you need

**Comment by thomasgueldenerg** [comment]
I'm using this one:# Datei Dockerfile
FROM ubuntu:18.04
Run apt-get update && \
  apt install -y gnupg2 && \
  apt-get install -y curl wget &&\
  /bin/bash -c "$(wget -qO- https://apt.vapor.sh)" && \
  apt-get install -y vapor && \
  rm -rf /var/lib/apt/lists/* 
WORKDIR /swiftcode

**Comment by thomasgueldenerg** [comment]
I did everything new and when i did vapor build --verbose, i got this now:

root@856ec04f6b0b:/swiftcode/vaporDB# vapor build --verbose
Building Project ...
Compile Swift Module 'Debugging' (3 sources)
Compile Swift Module 'NIOPriorityQueue' (2 sources)
/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/CSQLite.build/module.modulemap:2:14: warning: umbrella directory '/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include' not found
    umbrella "/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include"
             ^
<unknown>:0: error: PCH was compiled with module cache path '/swiftcode/vapordb/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C', but the path is currently '/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C'
<unknown>:0: error: missing required module 'SwiftShims'
/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/CSQLite.build/module.modulemap:2:14: warning: umbrella directory '/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include' not found
    umbrella "/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include"
             ^
<unknown>:0: error: PCH was compiled with module cache path '/swiftcode/vapordb/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C', but the path is currently '/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C'
<unknown>:0: error: missing required module 'SwiftShims'
/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/CSQLite.build/module.modulemap:2:14: warning: umbrella directory '/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include' not found
    umbrella "/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include"
             ^
<unknown>:0: error: PCH was compiled with module cache path '/swiftcode/vapordb/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C', but the path is currently '/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C'
<unknown>:0: error: missing required module 'SwiftShims'
/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/CSQLite.build/module.modulemap:2:14: warning: umbrella directory '/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include' not found
    umbrella "/swiftcode/vapordb/.build/checkouts/sqlite.git-1703015118678763207/Sources/CSQLite/include"
             ^
<unknown>:0: error: PCH was compiled with module cache path '/swiftcode/vapordb/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C', but the path is currently '/swiftcode/vaporDB/.build/x86_64-unknown-linux/debug/ModuleCache/PN4LB97QG60C'
<unknown>:0: error: missing required module 'SwiftShims'
error: terminated(1): /usr/bin/swift-build-tool -f /swiftcode/vaporDB/.build/debug.yaml main output:
    

Building Project [Failed]
Error: execute(code: 1)
root@856ec04f6b0b:/swiftcode/vaporDB#

**Comment by 0xTim** [comment]
Change all of that apart from the last line to
```
FROM vapor/swift:5.1
```

**Comment by thomasgueldenerg** [comment]
Hallo Tim,
you mean just:
From vapor/swift:5.1
WORKDIR /swiftcode

**Comment by 0xTim** [comment]
Yes that only includes swift. Why do you need the Vapor toolbox? What command are you trying to run that it's failing on?

**Comment by thomasgueldenerg** [comment]
Hi Tim,
I want to create a new vapor project with,
vapor new --auth mariadbauth,
when I'm in the container, or do you mean, to create everything outside? and just running the project inside?

**Comment by 0xTim** [comment]
Ah right I see now. Yeah I would recommend that you create the project outside of the container, then boot the container and mount the current directory as a volume and run `swift build` inside the container. Alternatively you can manually clone the template and set it up as a new git project yourself inside the container, but I'd go with the first option.

**Comment by thomasgueldenerg** [comment]
Tim,
many thanks. It is working now. Thanks a lot.
