### ISSUE TITLE
Unable to install vapor-beta

### ISSUE THREAD

**Issue by brunobl** [vapor/vapor#2136]
I'm unable to install vapor 4 beta 

brew install vapor/tap/vapor-beta

results in

==> Tapping vapor/tap
Cloning into '/usr/local/Homebrew/Library/Taps/vapor/homebrew-tap'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 2), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (11/11), done.
Tapped 7 formulae (43 files, 30.0KB).
==> Installing vapor-beta from vapor/tap
==> Downloading https://github.com/vapor/toolbox/archive/18.0.0-beta.19.tar.gz
==> Downloading from https://codeload.github.com/vapor/toolbox/tar.gz/18.0.0-beta.19
######################################################################## 100.0%
==> swift build --disable-sandbox
Last 15 lines from /Users/bruno/Library/Logs/Homebrew/vapor-beta/01.swift:
/private/tmp/vapor-beta-20191226-7451-1x1jhap/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:9:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "env", short: "e")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191226-7451-1x1jhap/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:11:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "branch", short: "b")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191226-7451-1x1jhap/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:32:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "app", short: "a")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191226-7451-1x1jhap/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:34:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "env", short: "e")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-beta-20191226-7451-1x1jhap/toolbox-18.0.0-beta.19/Sources/CloudCommands/Deploy.swift:36:10: error: cannot convert value of type 'Option<_>' to specified type 'String'
        @Option(name: "branch", short: "b")
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by NickSet** [comment]
This issue should be resolved with https://github.com/vapor/toolbox/commit/c5ae8a03cb0ebb33a9ae32d9bb0380fe21228e65
