### ISSUE TITLE
Command `vapor xcode` hangs

### ISSUE THREAD

**Issue by asteiman** [vapor/vapor#2142]
Running the command `vapor xcode` just hangs.
I have seen a similar issues but none of the solutions worked for me unfortunately.

### Steps to reproduce
Following the official documentation:
1) Run `vapor new Hello`
2) Run `vapor xcode` inside the created directory

### Expected behavior
Xcode project should be created

### Actual behavior
Nothing, terminal just hangs

### Environment

* Swift version: 5.1.3
* Vapor Framework version: It not even created yet
* Vapor Toolbox version: 3.1.10
* OS version: Catalina 10.15.1
* Xcode version: 11.3

This the the package.swift:
```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "perros",
    products: [
        .library(name: "perros", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```

Note: tried to use Vapor version 4.0.0-beta.3 but still same result

**Comment by 0xTim** [comment]
Delete your Package.resolved and `.build` directory and try again - it's probably caching stuff from when you tried Vaopr 4, which I suspect was because of the tools version

**Comment by asteiman** [comment]
After trying verbose mode, noticed that it was getting stuck on cloning a repo, and finally timing out.
Forgot to mention I am in a place with slow internet.
Got a better connection and managed to run it successfully.

Thanks
