### ISSUE TITLE
Request query validation

### ISSUE THREAD

**Issue by davuthdv** [vapor/vapor#2143]
There's no method to validate object decoded from request query.

### Steps to reproduce
This is how it looks in Vapor 3:
```swift
let paginationRequest = try req.query.decode(PaginationRequest.self)
try paginationRequest.validate()
```

An attempt for Vapor 4:
```swift
try PaginationRequest.validate(req)
let paginationRequest = try req.query.decode(PaginationRequest.self)
```
It crashes on the the validate line with error `Unprocessable Entity`.

### Expected behavior
There should be a method to validate request query. Maybe something like this:
```swift
Foo.validate(req.query)
```

* Vapor Framework version: 4.0.0-beta.3.1

**Comment by Khronoss** [comment]
It seems to be fixed using the following solution:
```
try PaginationRequest.validate(query: req)
let paginationRequest = try req.query.decode(PaginationRequest.self)
```

Using Vapor framework: 4.32.0

**Comment by siemensikkema** [comment]
@Khronoss thanks for following up! I'll go ahead and close this issue.
