### ISSUE TITLE
General Vapor issue

### ISSUE THREAD

**Issue by michalbursik** [vapor/vapor#2145]
Hello,

I have a deployed project on a Vapor and first month it was working nicely. I was late couple of days with payment and it stopped working so I decided to pay for an extra year of subscription but it seems like nothing changed since then. I looked at Vapor UI and AWS and everything seems to be available, but my web address is not working (like it does not exists anymore) - [https://resilient-sydney-nhwulryi5buu.vapor-farm-b1.com](url). I can't even ping it.

### Expected behavior

I don't know exatly how Vapor controls those situations so I can't say much, but I think Vapor should renew those DNS records after payment. 

### Actual behavior

I think that's not a normal behavior. I can't imagine that the project would be in production. 

### Environment

Vapor CLI ^1.4
Vapor core ^2.2

**Comment by 0xTim** [comment]
@michalbursik this is the repo for Vapor the Swift web framework, not Laravel's thing.

**Comment by michalbursik** [comment]
Oh, sorry I missed the repo. You can remove this.
