### ISSUE TITLE
vapor build failed with beta version

### ISSUE THREAD

**Issue by YujxZJCN** [vapor/vapor#2149]
### Steps to reproduce
Running `vapor new APNs --branch=4` and `vapor build`.

### Expected behavior
Build Success.

### Actual behavior
`clang-4.0: error: no such file or directory: '/Users/albertyu/Developer/Vapor/TILApp/.build/x86_64-apple-macosx/debug/index/store'
clang-4.0: error: no such file or directory: '/Users/albertyu/Developer/Vapor/TILApp/.build/x86_64-apple-macosx/debug/index/store'
clang-4.0: error: no such file or directory: '/Users/albertyu/Developer/Vapor/TILApp/.build/x86_64-apple-macosx/debug/index/store'
clang-4.0: error: no such file or directory: '/Users/albertyu/Developer/Vapor/TILApp/.build/x86_64-apple-macosx/debug/index/store'
[0/14] Compiling CNIOOpenSSL helpers.c
[0/14] Compiling CNIOHTTPParser c_nio_http_parser.c
[0/14] Compiling CNIOSHA1 c_nio_sha1.c
[0/14] Compiling CNIOZlib empty.c
[0/14] Compiling CNIODarwin shim.c
[0/14] Compiling CNIOLinux ifaddrs-android.c
[0/14] Compiling CNIOOpenSSL shims.c
[0/14] Compiling CNIOLinux shim.c`

### Environment
Vapor Toolbox: 3.1.10
Swift-tools-version: 5.1

* Vapor Framework version: 4.0.0-beta.2
* Vapor Toolbox version: 3.1.10
* OS version: 10.14.5

**Comment by 0xTim** [comment]
What's the output from `swift build` and which directory are you in? (The logs look like you're in TILApp not APNs). Have you tried cleaning first?
