### ISSUE TITLE
Array validation

### ISSUE THREAD

**Issue by simonedelmann** [vapor/vapor#2158]
While adding validations to my models I encountered an issue while validating an array of objects. (Vapor 4.beta, examples below simplified)
```swift
final class Todo: Model, Content, Validatable {
    @Field(key: "tags")
    var tags: [Tag]

    static func validations(_ validations: inout Validations) {
        validations.add("tags") { tag in
            tag.add("name", as: String.self, is: !.empty)
        }
    }
}

struct Tag {
    var name: String
}
```
```http
POST /todos/validated HTTP/1.1
Content-Type: application/json; charset=utf-8
Content-Length: 44

{"title":"MyTodo","tags":[{"name":"MyTag"}]}
```
When sending a proper request like above, this results in an decoding validation error: 
`tags failed to decode: Decoding error: Value of type 'Dictionary<String, Any>' required for key ''.`, while decoding the model works as expected.
```swift
try Todo.validate(req) // Throws Decoding error
try req.content.decode(Todo.self) // Works as expected
```

I've prepared a simple example (https://github.com/simonedelmann/vapor-bug-validating-array-of-objects) where you can check this.

**Comment by simonedelmann** [comment]
Not sure anymore if this is a bug or a missing feature:
```swift
validations.add("tags") { tag in
    tag.add("name", as: String.self, is: !.empty)
}
```
The argument `tag` has not the type `Tag` but `[Tag]`. We would probably need to have some kind of forEach for validations.

**Comment by tanner0101** [comment]
Yeah the nested validations as built are for dictionaries, not arrays. We'll need to invent new syntax for this.

**Comment by kaioser** [comment]
But if the type of `tags` is `[String]`, and still want to do the `!empty` validation, How do I write code in the closure?
