### ISSUE TITLE
Is there any good example/tutorial of how to use SwiftProtobuf with Vapor.

### ISSUE THREAD

**Issue by 3a4oT** [vapor/vapor#2160]
I'm using Vapor beta 4 and trying to understand whether it's a good idea to use SwiftProtobuf with Vapor.  Seems like generated models don't conform to Codable but Vapor is all about Codable(which I think is great). For instance, I'm not sure how I can register a global/route-specific custom Content coder for protobuf (Does it make sense at all?)? [Based on documentation](https://docs.vapor.codes/4.0/content/custom/) I should conform to:

```
public protocol ContentEncoder {
    func encode<E>(_ encodable: E, to body: inout ByteBuffer, headers: inout HTTPHeaders) throws
        where E: Encodable
}

public protocol ContentDecoder {
    func decode<D>(_ decodable: D.Type, from body: ByteBuffer, headers: HTTPHeaders) throws -> D
        where D: Decodable
}
```

But constrains are Encodable/Decodable. Should I generate *pb.swift files and then manually create extensions and conform to Codable. What are the best practices? I can imagine I would also need `Codable` models to use Vapor's ORM etc.

**Comment by 0xTim** [comment]
Have a look at https://gist.github.com/vzsg/7a309d24a1a92cf706a0dd17183673b9

**Comment by 3a4oT** [comment]
Thank you! I wish Vapor to get a protobuf support out the box one day :)

**Comment by 0xTim** [comment]
Hope so! Feel free to close the issue if you think it's resolved
