### ISSUE TITLE
URL decoding for sequences

### ISSUE THREAD

**Issue by kartikthapar** [vapor/vapor#2161]
### Steps to reproduce

I am trying to decode the URL of type: `".../lookup?entities=1,2,3,4"`. I use the following `Content` type:

```
struct EntityInfo: Content {
  var entities: [Int]
}
```

Here's the GET request resolution:

```
app.get("lookup") { req in 
  let entityInfo = try req.query.decode(EntityInfo.self)
  // ....
}
```

### Expected behavior

I am unsure if this is the right way to retrieve entities from the URL. But this does work for primitive types.

### Actual behavior

This fatals.

### Environment

* Vapor Framework version: 4.0.0
* Vapor Toolbox version:
* OS version: 10.15.2

**Comment by grundoon** [comment]
https://github.com/vapor/vapor/issues/2138 contains an approach that does currently work.

**Comment by tanner0101** [comment]
Yup the current pattern is to do:
```
/lookup?entities[]=1&entities[]=2...
```
IIRC someone in Vapor chat shared prior art for supporting decoding arrays from comma separated lists as well. If that's true, I'd be open to supporting that.

**Comment by vzsg** [comment]
I did some mentioning on Discord before, and Spring MVC is the prior art. [Here's](https://medium.com/@AADota/spring-passing-list-and-array-of-values-as-url-parameters-1ed9bbdf0cb2) a simple example of what's possible there.

**Comment by thecheatah** [comment]
Hi, if you are looking for documented examples of various types of encoding/deciding of query parameters, please take a look at the “Query Parameter” section of https://swagger.io/docs/specification/serialization/

It has a table of all possible combinations that swagger supports. Most apis document their interface using swagger/oas. So this is a good target to start from and then extend.

I would say that the “encoding” strategy might be “endpoint specific” so if the approach could support that, that would be great.

**Comment by thecheatah** [comment]
I am currently working on a PR for this. I should be able to share something in a few days.

**Comment by thecheatah** [comment]
Submitted PR for some "base work" to build up to this issue: https://github.com/vapor/vapor/pull/2180

**Comment by thecheatah** [comment]
PR was merged. This should work now.

**Comment by MrLotU** [comment]
Super awesome @thecheatah . I will close this issue now.
