### ISSUE TITLE
`Lock` not used anywhere in `Storage` class - missing thread-safety?

### ISSUE THREAD

**Issue by cameroncooke** [vapor/vapor#2162]
`Sync` property defined in `Storage` class but unused. On appearance, it looks like`Storage` is not thread-safe and should be using this lock.

### Steps to reproduce

https://github.com/vapor/vapor/blob/f2506413159c0dda6a9cf02619c05862208c4b7c/Sources/Vapor/Utilities/Storage.swift#L16

### Expected behavior

Storage should be thread-safe. If the goal is not to be thread-safe or if it's implicitly thread-safe then it should be documented ideally in header comments and any references to locks or synchronisation should probably be removed.

### Actual behavior

Undefined.

### Environment

Xcode Version 11.3.1 (11C504)
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
macOS 10.15.2 (19C57)
Vapor Toolbox: 3.1.10
Vapor 4.0.0 Beta 3.6

**Comment by tanner0101** [comment]
That lock was used previously but ended up being able to create deadlocks if two things access storage at the same time. It has been replaced by `app.locks` and should be removed. You can see an example of lock usage here: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Client/Application%2BClient.swift#L31-L50

**Comment by cameroncooke** [comment]
Thank you!

**Comment by tanner0101** [comment]
Actually I should keep this open to track removing Storage's lock.
