### ISSUE TITLE
Zoom in/out doesn't work WRF files are not rendered correctly on OS X 

### ISSUE THREAD

**Issue by adamk0** [vapor/vapor#2167]
On OSX zoom in/out doesn't work, and WRF netcdf files are not rendered incorrectly with the Z dimension stretched by a factor of 10 or so.

In the new 3.2 version zoom in/out that worked with the hold right click and vertical mouse movement stopped working. Also, WRF netcdf files are not rendered correctly. The Z axis is stretched and the lat/lon is not processed correctly judging by the way how the Erth background is displayed.

### Steps to reproduce

Open Vapor 3.2. Import WRF output file. Add image renderer, select the default image file.

### Expected behavior
Same as in 3.1

### Environment

* Vapor Framework version:
Version: 3.2.0
* Vapor Toolbox version:
* OS version:
OS X 10.12.6
Vapor 3.2 - bad
![Vapor_3 2](https://user-images.githubusercontent.com/3976665/73895221-13769e80-483c-11ea-8b8e-deb698f8e837.png)
Vapor 3.1 - good
![Vapor_3 1](https://user-images.githubusercontent.com/3976665/73895223-14a7cb80-483c-11ea-8407-43bf42e44587.png)

**Comment by grundoon** [comment]
This `vapor` is a web framework, not the one you are looking for – try https://github.com/NCAR/VAPOR

**Comment by adamk0** [comment]
sorry, my bad.
