### ISSUE TITLE
Parsing Query Parameter as Array when malformed causes a crash

### ISSUE THREAD

**Issue by thecheatah** [vapor/vapor#2176]
### Steps to reproduce

Try to parse query parameter using:
```swift
let emailsToSearch = try? request.query.get([String].self, at: "emailsToSearch[]")
```

Pass in query parameter as `?emailsToSearch%5B%5D=xyz` where `%5B%5D` is `[]`.

### Expected behavior

`?emailsToSearch[]=xyz` works as expected, but a malformed user input using `%5B%5D` should not crash the server.

### Actual behavior

Server Crashes

Crash happens in URLEncodedFormDecoder.swift Line: 113's fatalError()
```swift
    /// See `Decoder`
    func unkeyedContainer() throws -> UnkeyedDecodingContainer {
        guard let data = self.data else {
            return UnkeyedContainer(data: [], codingPath: self.codingPath)
        }
        switch data {
        case .array(let arr):
            return UnkeyedContainer(data: arr, codingPath: self.codingPath)
        default: fatalError()
        }
    }
```
### Environment

* Vapor Framework version: Vapor 4.0.0-beta.3.10
* Vapor Toolbox version:
* OS version: MacOS

**Comment by Joannis** [comment]
I've confirmed the bug and I've started a solution.
