### ISSUE TITLE
Please provide the HTTP major and minor version in ClientResponse

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#2186]
Subject says it all.  Latest vapor 4 version.

**Comment by tanner0101** [comment]
I started implementing this, but it looks like async-http-client actually hardcodes HTTP/1.1: https://github.com/swift-server/async-http-client/blob/master/Sources/AsyncHTTPClient/HTTPHandler.swift#L656

Given that is the only implementation `Client` currently supports, we can assume 1.1.
