### ISSUE TITLE
Allow WebSocket maxFrameSize to be configured

### ISSUE THREAD

**Issue by bridger** [vapor/vapor#2194]
Today the NIOWebSocketServerUpgrader is always created with the same maxFrameSize of 1 << 14 (16kb). My app regularly sends larger frames to the server, which is causing the  server to reject them.

I'd like to add a configuration parameter when setting up the route to allow larger frames. The configuration can also be used for future features, such as enabling compression or starting automatic ping/pong heartbeats.

I plan to submit a PR soon to create this feature.

**Comment by lmcd** [comment]
I'm also running into this. WebSocket connection is closing on my if I send anything over 16kb

**Comment by bridger** [comment]
I hope to get this merged in soon! There is a different PR to be merged first, and then I can update this fix maybe tonight.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
