### ISSUE TITLE
not work in xcode 11 and swift 5.2

### ISSUE THREAD

**Issue by Jonathanseng** [vapor/vapor#2202]
I cant make vapor build and it shows the message below:
backgroundExecute(code: 1, error: "warning: \'fetch\' command is deprecated; use \'resolve\' instead\nerror: terminated(72): xcrun --sdk macosx --find xctest output:\n    xcrun: error: unable to find utility \"xctest\", not a developer tool or in PATH\n    \n", output: "")

**Comment by 0xTim** [comment]
The likely cause is homebrew messing up your command line tools. Run `sudo xcode-select -s /Applications/Xcode.app` (or wherever your Xcode is located). Also, instead of `vapor build` run `swift build`
