### ISSUE TITLE
Some cookies have quotes around them

### ISSUE THREAD

**Issue by bridger** [vapor/vapor#2207]
I've seen that some cookies, accessed by `request.headers.cookie["cookie-key"]?.string` have quote characters at the beginning and end. I believe they happen when the cookie itself contains a special character like / or +.

I believe Vapor should automatically trim those quote characters out of the value. They are just a detail of how the cookie is encoded.

[This is where that trimming happens in Kitura](https://github.com/IBM-Swift/Kitura/blob/ac4d947b701635cc5eba2de7fd1b25f3be6dbef4/Sources/Kitura/RouterRequest.swift#L331)

### Steps to reproduce

Try setting a cookie value like `+cookie/value`

Get that cookie from Vapor. It is returned as `"+cookie/value"`

### Expected behavior

It should be returned as `+cookie/value`

### Environment

* Vapor Framework version: 4.0.0-beta.4.2

**Comment by tanner0101** [comment]
Thanks for reporting. Can you let me know if https://github.com/vapor/vapor/pull/2215 looks good?
