### ISSUE TITLE
Missing parameter in route

### ISSUE THREAD

**Issue by pugachevskiy** [vapor/vapor#2208]
### Steps to reproduce

 i have 2 routes
1.)  route.get("api","addresses", use: address.index)
2.) route.get("api", "addresses","search", ":addressUUID", use: address.findById)

I don't pass any value after api/addresses/search/ 
### Expected behavior
I expect some kind of error(not found, missing parameter)

### Actual behavior
Get result from first route ([Address])

### Environment

* Vapor Framework version: 4.0.0-rc.1
* Vapor Toolbox version:
* OS version:10.15.3

**Comment by Joannis** [comment]
Thanks for the report. I've just written a test to verify your issue but I couldn't find an issue in the framework. Do you have a `.catchall` in a router group on the path `/`, `/api` or `/api/addresses`?

**Comment by pugachevskiy** [comment]
no, nothing like this.
here is the code
func routes(_ app: Application) throws {
    AddressRouter(app.routes)
}

struct AddressRouter {
    @discardableResult
    init(_ route: RoutesBuilder) {
        let address = AddressController()
       
        route.get("api","addresses", use: address.index)
        route.get("api", "addresses","search", ":addressUUID", use: address.findById)
   }
}

**Comment by tanner0101** [comment]
I'm not able to recreate this. I used this code:

```swift
let app = Application(.testing)
defer { app.shutdown() }

app.get("api","addresses") { req in
    "a"
}
app.get("api", "addresses","search", ":id") { req in
    "b"
}

try app.testable(method: .running).test(.GET, "/api/addresses/") { res in
    XCTAssertEqual(res.body.string, "a")
}.test(.GET, "/api/addresses/search/test") { res in
    XCTAssertEqual(res.body.string, "b")
}.test(.GET, "/api/addresses/search/") { res in
    XCTAssertEqual(res.status, .notFound)
}.test(.GET, "/api/addresses/search") { res in
    XCTAssertEqual(res.status, .notFound)
}
```

**Comment by pugachevskiy** [comment]
sorry, wrong filter for search give this result. Without fields for search it gives array of all addresses.
