### ISSUE TITLE
Consider depending on Swift Metrics 2.x (whilst still allowing 1.x)

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2213]
[Swift Metrics 2.0](https://github.com/apple/swift-metrics/releases/tag/2.0.0) just got released. It is almost completely compatible with Swift Metrics 1.x unless you exhaustively switch on the `TimeUnit` enum. I would highly recommend depending on `swift-metrics` like the following:

```swift
// swift-metrics 1.x and 2.x are almost API compatible, so most clients should use
.package(url: "https://github.com/apple/swift-metrics.git", "1.0.0" ..< "3.0.0"),
```

alternatively, `from: "2.0.0"` will also work but may in the interim cause compatibility issues with packages that specify `from: "1.0.0"`.

If at all possible, this should be done before tagging the next release here. If using `"1.0.0" ..< "3.0.0"` this isn't even a SemVer major change because 1.x versions are still accepted.

**Comment by 0xTim** [comment]
This is complicated by https://github.com/vapor/vapor/blob/master/Sources/Vapor/Exports.swift#L11

Again, why this is exported I have no idea. @tanner0101 I'm pretty sure we can remove this export before tagging 4.0. Anyone wanting to write out metrics in their own apps is going to be pulling in a metrics library anyway that outputs to something

**Comment by weissi** [comment]
oh yes, I'd highly recommend removing all `@_exported import`s that export stuff from a different package.

**Comment by weissi** [comment]
if that's really necessary, Vapor 4 should do `from: "2.0.0"` I think

**Comment by tanner0101** [comment]
@0xTim agreed, I think that one can be removed without breaking anyone. To reiterate here, Vapor 5 will try to get rid of or at least significantly cut down on all `@_exported` usage so that we can prevent dependency hell going forward.

**Comment by tanner0101** [comment]
On PostgresNIO, which doesn't expose metrics at all, updating to 2.0.0 causes SPM to implode: https://github.com/vapor/postgres-nio/pull/88/checks?check_run_id=490844870

Not sure if I'm doing something wrong or if that's an SPM bug.

**Comment by weissi** [comment]
@tanner0101 ouch, that’s bad, mind filing a bug with the repro instructions? CC @aciidb0mb3r

**Comment by weissi** [comment]
Ankit, it’s one of these: 

```
github.com/apple/swift-log.git
11
Updating https://github.com/vapor/async-kit.git
12
Updating https://github.com/apple/swift-metrics.git
13
Updating https://github.com/apple/swift-nio.git
14
Removing https://github.com/apple/swift-crypto.git
15
Removing https://github.com/apple/swift-metrics.git
16
Removing https://github.com/apple/swift-nio-ssl.git
17
Updating https://github.com/apple/swift-log.git
18
Updating https://github.com/apple/swift-nio.git
19
Fetching https://github.com/apple/swift-metrics.git
20
Fetching https://github.com/apple/swift-nio-ssl.git
21
Fetching https://github.com/apple/swift-crypto.git
22
Updating https://github.com/vapor/sql-kit.git
23
Updating https://github.com/vapor/async-kit.git
24
Updating https://github.com/vapor/postgres-nio.git
25
Everything is already up-to-date
26
error: the Package.resolved file is most likely severely out-of-date and is preventing correct resolution; delete the resolved file and try again
27
##[error]Process completed with exit code 1.
```

@tanner0101 which Swift version is this? 5.2?
