### ISSUE TITLE
Memory will not be released

### ISSUE THREAD

**Issue by VineFiner** [vapor/vapor#2227]
### Environment

* Vapor Framework version: 4.0.0-beta.3.10
* Vapor Toolbox version: Vapor Toolbox: 3.1.10
* OS version: 10.15.3

Code

```
    // This is test
    // http://127.0.0.1:8080/api/document/100
    func testClient(req: Request) throws -> EventLoopFuture<String> {
        guard let count = req.parameters.get("count", as: Int.self) else {
            throw Abort(.notFound, reason: "No count")
        }
        print("count:\(count)")
        for index in 0..<count {
            let bookUrl: URI = URI(string: "https://vapor.codes/")
            _ = req.client.get(bookUrl).map { (response: ClientResponse) -> (String?) in
                var resultHtml: String?
                switch response.status {
                case .ok:
                    let resultData = response.body.flatMap { (buffer) -> Data? in
                        return buffer.getData(at: 0, length: buffer.readableBytes)
                    }
                    if let info = resultData, let infoStr = String(data: info, encoding: .utf8) {
                        resultHtml = infoStr
                        print("success:\(index)")
                    }
                default :
                    break
                }
                return resultHtml
            }
        }
        return req.eventLoop.future("")
    }
```

**Comment by 0xTim** [comment]
Does this happen on the latest RCs?

**Comment by VineFiner** [comment]
> Does this happen on the latest RCs?

Switching to RCs has improved, but the memory is still increasing. 
For example, starting `11M`, it becomes` 20M` after running.
Replace the destination link with `https://www.google.com`.
 I used `ab -n 5000 -c 10 http://127.0.0.1:8080/api/document/1` for testing and reported an error. `dnssd_clientstub deliver_request: socketpair failed 24`

**Comment by 0xTim** [comment]
I know Google has lots of issues because they don't close TLS connections properly. 

So some questions, does it climb throughout the duration of the test or does it spike early and then stay flat (which is to be expected as Vapor allocates all the services for each event loop). Have you run it through the profiler to work out what's using the memory?

**Comment by VineFiner** [comment]
> I know Google has lots of issues because they don't close TLS connections properly.
> 
> So some questions, does it climb throughout the duration of the test or does it spike early and then stay flat (which is to be expected as Vapor allocates all the services for each event loop). Have you run it through the profiler to work out what's using the memory?

it spike early and then stay flat。
I just use xcode。
Okay thank you. I will close it。
