### ISSUE TITLE
Deprecated HTTPServer.Configuration initializer creates ambiguous compilation error for most cases

### ISSUE THREAD

**Issue by jordanebelanger** [vapor/vapor#2230]
An old initializer of HTTPServer.Configuration has been deprecated, but unfortunately that initializer's signature is almost exactly the same as the new initializer. 

Since these initializers have default values for most of their parameters, this means most people will get an "Ambiguous use of 'init'" compilation error in most cases. 

For example, a simple hostname/port use of the initializer will no longer compile.

![image](https://user-images.githubusercontent.com/1856085/76220831-87ff7d00-61ee-11ea-8846-32a83456999d.png)

### Expected behavior

Commonly expected usage of the HTTPServer.Configuration should not lead to compilation issue. We may just want to remove the deprecated initializer altogether if having it deprecated leads to compilation issues anyway.

### Environment

* Vapor Framework version: 4.0.0-rc.3.1
* OS version: Mac OS 10.15 Catalina

**Comment by tanner0101** [comment]
This deprecation has been removed in the final release version of Vapor 4
