### ISSUE TITLE
[Vapor 3] Websocket server connection when testing

### ISSUE THREAD

**Issue by lorenalexm** [vapor/vapor#2243]
I am attempting to preform some basic testing on websockets within Vapor 3, admittedly though I am not terribly familiar with them. 

When running the test suite from Xcode or the command line I am running into the issue of the websocket client code not being able to connect to the server within the same application; it is stating that there is a NIO.ChannelError with a code of 1.It seems to me this is due to a refused connection. 

What throws me for a loop though, is if I already have a build of the server running, outside of the test suite, the connection is made and the test passes without issue. So it would seem that somewhere, something is preventing a client connection to a server of the same process? Does this sound correct, or is this intended behavior?

Outside of the testing, I have been able to connect and pass messages through the server using a simple SwiftUI project that uses Starscream to handle the websocket connection, and also the WebSocket Client application by AwayUp. So the server does otherwise function as intended, it just trips over itself with testing.

### Steps to reproduce

Using the provided code as a basis added to a new Vapor 3 project, attempt to run the testing suite. You will/should find that the tests fail as the server is not able to connect to itself.

### Expected behavior

Tests should allow a websocket client connection to the server from within the testing suite. Upon connection to the server, the server emits a message that contains the "Welcome" text.

### Actual behavior

Testing fails when attempting to connect a client to the websocket server.
Localized error reports the following: _The operation couldn’t be completed. (NIO.ChannelError error 1.)_

As stated in the description though, the test will run and pass if a separate server process is already running. (i.e. within iTerm)

### Relevant code (hopefully)
```
// configure.swift
public func configure(_ config: inout Config, _ env: inout Environment, _ services: inout Services) throws {
    // Register routes to the router
    let router = EngineRouter.default()
    try routes(router)
    services.register(router, as: Router.self)

    // Register middleware
    var middlewares = MiddlewareConfig() // Create _empty_ middleware config
    middlewares.use(ErrorMiddleware.self) // Catches errors and converts to HTTP response
    services.register(middlewares)
    
    let socket = SocketTestController()
    services.register(socket, as: SocketTestController.self)
    
    let websocket = NIOWebSocketServer.default()
    websocket.get("ws", use: socket.onUpgrade)
    services.register(websocket, as: WebSocketServer.self)
}
```

```
// Application+Testable.swift
@testable import App
import XCTest
import Vapor

extension Application {
    static func testable() throws -> Application {
        var config = Config.default()
        var services = Services.default()
        var env = Environment.testing
        try configure(&config, &env, &services)
        return try Application.asyncBoot(config: config, environment: env, services: services).wait()
    }
    
    func sendRequest<Body>(to path: String, method: HTTPMethod, headers: HTTPHeaders = .init(), body: Body?) throws -> Response where Body: Content {
        let httpRequest = HTTPRequest(method: method, url: URL(string: path)!,headers: headers)
        let wrappedRequest = Request(http: httpRequest, using: self)
        if let body = body {
            try wrappedRequest.content.encode(body)
        }
        let responder = try make(Responder.self)
        
        return try responder.respond(to: wrappedRequest).wait()
    }
}

struct EmptyBody: Content {}
```

```
// SocketTests.swift
@testable import App
import XCTest
import Vapor

final class SocketTests: XCTestCase {
    var app: Application!
    
    override func setUp() {
        super.setUp()
        
        app = try! Application.testable()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    func testWebsocketConnection() {
        var raw: String?
        do {
            let _ = try app.client().webSocket("ws://localhost:8080/ws").flatMap { ws -> Future<Void> in
                ws.onText { _, text in
                    raw = text
                    ws.close()
                }
                return ws.onClose
            }.wait()
        } catch {
            print("!!! \(error.localizedDescription)")
            return XCTFail()
        }
        
        guard let response = raw else {
            return XCTFail()
        }
        
        do {
            let response = try JSONDecoder().decode(SocketResponse.self, from: response)
            XCTAssertEqual(response.message.message, "Welcome")
        } catch {
            print("!!! \(error.localizedDescription)")
            return XCTFail()
        }
    }
}
```

### Environment

* Vapor Framework version: "from 3.0.0" in package.swift, _vapor --version_ throws an error of _Error: GeneralError(message: "Unable to locate vapor dependency")_
* Vapor Toolbox version: 3.1.10
* OS version: macOS 10.15.3

**Comment by tanner0101** [comment]
From a glance, the code you have looks like it should work. Are you sure the app is binding to port `8080`? If you set a breakpoint in `testWebsocketConnection` are you able to connect to the testable application via other clients like a CLI client? It's also possible trying `127.0.0.1` instead of `localhost` may work.

**Comment by lorenalexm** [comment]
For verifying that the binding is taking place, within the Scheme Editor I have specified `--port 8080` as an argument; this did not yield any noticeable difference when running the tests. I also added the following to the `configure(config: env: services:)` function to force the desired port.

```
if env == .development || env == .testing {
    let server = NIOServerConfig.default(hostname: "0.0.0.0", port: 8080)
    services.register(server)
}
```

Once again, there did not seem to be any change as the tests still failed. 

With a breakpoint set in `testWebsocketConntion` and another arbitrary test checking a route returning just a string, I was not able to connect by means of CLI using websocat, the test client in another Xcode instance, or the WebSocket Client application by AwayUp.  Though a thought, as breakpoints pause execution, is this not to be expected; or am I either using breakpoints improperly or do not fully understand them?

Through inspecting the app with the breakpoint in place, I do see that the port argument was indeed passed with `8080` as a value in the environment. Though I cannot seem to further find anything in the inspector relating to the port value.

To your final question, I have tried using `localhost`, `127.0.0.1`, and the computers assigned IP within the `192.168.3.*` range. None of which have seemed to make a difference either.

**Comment by tanner0101** [comment]
Try adding a call to `asyncRun` to actually run the application after booting (initializing) it: https://github.com/vapor/vapor/blob/3/Tests/VaporTests/ApplicationTests.swift#L883.

**Comment by lorenalexm** [comment]
As per your suggestion, I have called `asyncRun` within the `testable` function. But in doing so, I am now having an exception being thrown when trying to capture the return of `testable` in the tests `setUp` function. The exception presents itself both within Xcode and the console, though with each presenting differently; as seen below.

```
# lorenalexm at Alexs-iMac.lan in ~/Projects/sockettest on git:master ✖︎ [18:34:09]
→ vapor test
Testing [Failed]

Log:
Test Suite 'All tests' started at 2020-03-19 18:35:09.794
Test Suite 'sockettestPackageTests.xctest' started at 2020-03-19 18:35:09.794
Test Suite 'AppTests' started at 2020-03-19 18:35:09.794
Test Case '-[AppTests.AppTests testNothing]' started.
Test Case '-[AppTests.AppTests testNothing]' passed (0.157 seconds).
Test Suite 'AppTests' passed at 2020-03-19 18:35:09.951.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.157 (0.157) seconds
Test Suite 'SocketTests' started at 2020-03-19 18:35:09.951
Test Case '-[AppTests.SocketTests testWebsocketConnection]' started.
Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ CommandError: Unknown command `/Users/lorenalexm/Projects/sockettest/.build/x86_64-apple-macosx/debug/sockettestPackageTests.xctest`
- id: CommandError.unknownCommand
: file /Users/lorenalexm/Projects/sockettest/Tests/AppTests/SocketTests.swift, line 17


Output:
[1/18] Compiling CNIOZlib empty.c
[2/18] Merging module COperatingSystem
[3/18] Merging module NIOPriorityQueue
[4/18] Compiling CNIOOpenSSL shims.c
[5/18] Compiling CNIOOpenSSL helpers.c
[6/18] Compiling CNIOLinux shim.c
[7/18] Compiling CNIOSHA1 c_nio_sha1.c
[8/18] Compiling CNIOLinux ifaddrs-android.c
[9/18] Compiling CNIODarwin shim.c
[10/18] Compiling CCryptoOpenSSL shim.c
[11/18] Compiling CNIOHTTPParser c_nio_http_parser.c
[12/18] Compiling CBcrypt blf.c
[13/18] Compiling CBcrypt bcrypt.c
[14/18] Compiling CBase32 base32.c
[15/18] Merging module Debugging
[16/18] Compiling c-atomics.c
[17/19] Merging module NIOConcurrencyHelpers
[18/20] Merging module NIO
[19/24] Merging module NIOTLS
[20/24] Merging module NIOFoundationCompat
[21/26] Merging module Bits
[22/27] Merging module NIOHTTP1
[23/27] Merging module Async
[24/28] Merging module Random
[25/28] Merging module NIOOpenSSL
[26/28] Merging module NIOWebSocket
[27/29] Merging module Core
[28/33] Merging module Multipart
[29/34] Merging module Validation
[30/34] Merging module URLEncodedForm
[31/34] Merging module Logging
[32/34] Merging module Service
[33/38] Merging module Routing
[34/38] Merging module HTTP
[35/38] Merging module Crypto
[36/41] Merging module WebSocket
[37/41] Merging module TemplateKit
[38/41] Merging module DatabaseKit
[39/41] Merging module Console
[40/42] Merging module Command
[41/43] Merging module Vapor
[42/44] Merging module App
[43/46] Merging module Run
[44/46] Linking Run
[45/46] Merging module AppTests
[46/46] Linking sockettestPackageTests
Usage: /Applications/Xcode.app/Contents/Developer/usr/bin/xctest <command>

Commands:
   serve (default) Begins serving the app over HTTP.
  routes Displays all registered routes.
    boot Boots the application's providers.

Use `/Applications/Xcode.app/Contents/Developer/usr/bin/xctest <command> [--help,-h]` for more information on a command.
Exited with signal code 4


Help:
Join our Slack where hundreds of contributors
are waiting to help: http://vapor.team

Error: Tests failed.
```

```
Test Suite 'All tests' started at 2020-03-19 18:37:00.524
Test Suite 'AppTests.xctest' started at 2020-03-19 18:37:00.525
Test Suite 'AppTests' started at 2020-03-19 18:37:00.525
Test Case '-[AppTests.AppTests testNothing]' started.
Test Case '-[AppTests.AppTests testNothing]' passed (0.078 seconds).
Test Suite 'AppTests' passed at 2020-03-19 18:37:00.605.
	 Executed 1 test, with 0 failures (0 unexpected) in 0.078 (0.080) seconds
Test Suite 'SocketTests' started at 2020-03-19 18:37:00.605
Test Case '-[AppTests.SocketTests testWebsocketConnection]' started.
Running default command: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/xctest serve
Usage: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Xcode/Agents/xctest [--hostname,-H] [--port,-p] [--bind,-b] 

Begins serving the app over HTTP.

Options:
  hostname Set the hostname the server will run on.
      port Set the port the server will run on.
      bind Convenience for setting hostname and port together.
Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ CommandError: Too many arguments or unsupported options were supplied: ["-NSTreatUkownArgumentsAsOpen", "NO", "-ApplePersistenceIgnoreState", "YES"]
- id: CommandError.excessInput
: file /Users/lorenalexm/Projects/sockettest/Tests/AppTests/SocketTests.swift, line 17
2020-03-19 18:37:00.625647-0700 xctest[59484:129238] Fatal error: 'try!' expression unexpectedly raised an error: ⚠️ CommandError: Too many arguments or unsupported options were supplied: ["-NSTreatUkownArgumentsAsOpen", "NO", "-ApplePersistenceIgnoreState", "YES"]
- id: CommandError.excessInput
: file /Users/lorenalexm/Projects/sockettest/Tests/AppTests/SocketTests.swift, line 17
Program ended with exit code: 9
```

In regards to the Xcode output: When I look through the project, I do not see anything explicitly set for passing the two arguments shown; though admittedly I am a bit ignorant when it comes to more than surface level Xcode.

With the CLI in mind I have verified that the `./.build/x86_64-apple-macosx/debug/sockettestPackageTests.xctest` bundle does exist where expected from the output.

I have performed a `brew upgrade vapor` on both my iMac and MBP to ensure I am up to date with brew providing the following feedback.

```
# lorenalexm at Alexs-iMac.lan in ~/Projects/sockettest on git:master ✖︎ [7:24:03]
→ brew info vapor
vapor/tap/vapor: stable 3.1.13
https://vapor.codes
/usr/local/Cellar/vapor/3.1.13 (6 files, 17.8MB) *
  Built from source on 2020-03-19 at 18:31:44
From: https://github.com/vapor/homebrew-tap/blob/master/vapor.rb
==> Dependencies
Required: ctls ✔, libressl ✔
```

In hopes of it helping catch the issue, I have attached the "project" for review if desired.
[sockettest.zip](https://github.com/vapor/vapor/files/4360094/sockettest.zip)


I really appreciate the time you are giving in helping sort out my issue, thank you!

**Comment by tanner0101** [comment]
Make an environment like this for use in tests.
```swift
private extension Environment {
    static var xcode: Environment {
        return .init(name: "xcode", isRelease: false, arguments: ["xcode"])
    }
}
```
You can see examples in Vapor 3's tests here: https://github.com/vapor/vapor/blob/3/Tests/VaporTests/ApplicationTests.swift#L865
