### ISSUE TITLE
Failure to parse x-www-form-urlencoded percent encoded ARRAY data

### ISSUE THREAD

**Issue by deze333** [vapor/vapor#2244]
When passing a form **arrays of values**, browsers send form data in percent encoded format – including `[]` brackets: `name=example&ids%5B%5D=100001&ids%5B%5D=100002&ids%5B%5D=100003` yet Vapor seems to expect `name=example&ids[]=100001&ids[]=100002&ids[]=100003` as a valid input.

### Steps to reproduce

Simple tests:

```swift
    func testFormDecodePercentEncodedRaw() throws {
        let data = """
        name=example&ids%5B%5D=100001&ids%5B%5D=100002&ids%5B%5D=100003
        """
        let form = try URLEncodedFormDecoder().decode(Form.self, from: data)
        XCTAssert(form.ids.count == 3) // fails
    }
    
    func testFormDecodePercentEncoded() throws {
        let data = """
        name=example&ids%5B%5D=100001&ids%5B%5D=100002&ids%5B%5D=100003
        """
        let s = data.removingPercentEncoding!
        let form = try URLEncodedFormDecoder().decode(Form.self, from: s)
        XCTAssert(form.ids.count == 3) // succeeds
    }
    
    struct Form: Content {
        var name: String
        var ids: [String]
    }
```
### Expected behavior

Percent encoding removed, non-empty array returned.

### Actual behavior

Empty array is returned.

### Environment

* Vapor Framework version: 4.0.0-rc.3.4
* Vapor Toolbox version: 4
* OS version: macOS 10.15

**Comment by tanner0101** [comment]
That is expected. If the browsers is sending `ids%5B%5D` then the key is interpreted as `ids[]` which is _not_ using the array encoding. The brackets must remain unescaped to use array encoding. 

With the latest changes in https://github.com/vapor/vapor/releases/tag/4.0.0-rc.1 you can also pass an array without brackets with the following:

```
ids=1&ids=2&ids=3
```

This can be useful if you're having difficulty getting the brackets to encode correctly.
