### ISSUE TITLE
Single thread mode?

### ISSUE THREAD

**Issue by lmcd** [vapor/vapor#2248]
I'm running a Vapor server inside of an app that will only ever have a handful of low-throughput clients connected at any given time. Having connections served through different threads has the additional mental overhead of having to enforce thread safety everywhere, use locks etc.

Is there an option to have just a single event loop running out of a single thread, so as to have Vapor behave in a more predictable/deterministic way?

**Comment by 0xTim** [comment]
In Vapor 4 you can initialise the `Application` instance with an `eventLoopGroupProvider` which can provide only the event loop groups you want to run on. So you can create your own like so:
```swift
let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
```
And pass that to the provider to achieve what you want

**Comment by lmcd** [comment]
Perfect! I'm assuming long running file uploads etc won't block the event loop by design?

**Comment by tanner0101** [comment]
@lmcd if you use Vapor's fileio helpers or NIO's NonBlockingFileIO type (which Vapor's helpers use internally) then you won't block the event loop 👍
