### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by ducdung98tb** [vapor/vapor#2251]
I have a error when i get an API from another server 
Fatal error: Error raised at top level: Foundation.URLError(_nsError: SSL certificate problem: unable to get local issuer certificate): file /home/buildnode/jenkins/workspace/oss-swift-4.2-package-linux-ubuntu-18_04/swift/stdlib/public/core/ErrorType.swift, line 191
Current stack trace:
0    libswiftCore.so                    0x00007fdf59c0dac0 _swift_stdlib_reportFatalErrorInFile + 215
1    libswiftCore.so                    0x00007fdf599660f1 <unavailable> + 1503473
2    libswiftCore.so                    0x00007fdf59ba2c52 <unavailable> + 3849298
3    libswiftCore.so                    0x00007fdf59ba4f49 <unavailable> + 3858249
4    libswiftCore.so                    0x00007fdf5996583a <unavailable> + 1501242
5    libswiftCore.so                    0x00007fdf59ba2b98 <unavailable> + 3849112
6    libswiftCore.so                    0x00007fdf5996583a <unavailable> + 15012

**Comment by 0xTim** [comment]
This is caused by misconfiguration on the API by that API not setting up their SSL certificates correctly

**Comment by ducdung98tb** [comment]
Thank you @0xTim . How can I set up the SSL certificate correctly when I program API with vapor

**Comment by ducdung98tb** [comment]
When I test that API on postman, I can still get data by turning off postman's SSL.

**Comment by 0xTim** [comment]
Do you own the API or is it owned by someone else?

**Comment by ducdung98tb** [comment]
I connect that API using bearer token and that's my API

**Comment by ducdung98tb** [comment]
I can only connect to the APIs in the same lan network.

**Comment by 0xTim** [comment]
How are you serving the SSL certificate?
