### ISSUE TITLE
Support overriding Application.Client

### ISSUE THREAD

**Issue by owainhunt** [vapor/vapor#2269]
In Vapor 3, it's possible to override the client used by the application, as follows:
`services.register(Client.self) { return MockClient() }`

This is useful for a number of reasons, but is especially handy for testing - the app client can be mocked so requests can be inspected. With the changes to services in Vapor 4, this is no longer possible.

Vapor 4 should support overriding the client in the same way as Vapor 3, possibly by following a similar pattern to that used for settings the view renderer (`app.views.use(.leaf)`).

Possible usage:
`app.client.use(.myFakeClient)`

**Comment by tanner0101** [comment]
This is now supported:

```swift
app.clients.use(.custom)
```

An example can be seen here: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ClientTests.swift#L129-L138
