### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by onurtuna** [vapor/vapor#2274]
After Xcode update the users who use 3.0.0 and below versions encounter with the compiler problem.

Since the Vapor comes compiled with the Swift Package Manager the library should be compiled with the Swift 5.2 version for the version greater than 3.0.0.

**Comment by 0xTim** [comment]
@onurtuna do a full clean and try again

**Comment by onurtuna** [comment]
This seems to work @0xTim Closing the issue.
