### ISSUE TITLE
Complex Accept header parsing fails

### ISSUE THREAD

**Issue by reversepanda** [vapor/vapor#2283]
We try to differentiate between a request from the browser or a REST client, so we are able to provide the appropriate response (HTML vs. JSON).

We look at the "Accept" header to analyse the accepted answer.

```
   func index(req: Request) throws -> EventLoopFuture<Response> {
        let objects = SomeModel.query(on: req.db).all()
        if req.headers.accept.mediaTypes.contains(.html) {
           // Return HTML result
           return req.view.render("index")
        }
        else {
            // E.g. return JSON
            return objects.encodeResponse(for: req)
        }
    }
```

`req.headers.accept.mediaTypes.contains(.html)` seems not to parse the Accept header correctly. Using a basic Accept header like `Accept: text/html` will yield the correct result. But more complex headers like Safari's `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8` fail to parse correctly.

`req.headers.accepts` is an empty array.
### Steps to reproduce

 - Use the above snippet for a route. 
 - Send a basic `Accept` header (`Accept: text/html`). This works fine.
 - Send a more complex `Accept` header, which expects a HTML response (e.g. Safari's `Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`). You will receive a JSON response.

### Expected behavior

 - The request with a more complex `Accept` header (which in my case expects a HTML response) should be mapped to the correct media type.

PS:  I'm currently using this workaround 

`if req.headers["Accept"].first?.contains("html") ?? false {...` 

### Environment

Xcode 11.4

* Vapor Framework version: Vapor 4 RC 3.12
* Vapor Toolbox version: vapor-beta
* OS version: macOS 10.15.4

**Comment by schwmi** [comment]
Ping @0xTim - (in refer to your tweet) I think this issue had no attention for long time. Stumbled on this when migrating from vapor 3 to 4. I tried to use the api for checking html accepts. That doesn‘t work for safari headers which is imo a quite common use-case. If you like I could also look into this and open a PR.
