### ISSUE TITLE
Reference to member 'psql' cannot be resolved without a contextual type

### ISSUE THREAD

**Issue by nickfarrant** [vapor/vapor#2291]
I cannot compile due to this error being present on my migrations.

In configure, where I am setting up migrations for my models I am getting a compilation error reading `Reference to member 'psql' cannot be resolved without a contextual type`.

### Steps to reproduce

I don't know any. Last time I opened the project (last 2 weeks) it built and ran without issues.

![Screenshot 2020-04-04 at 17 44 40](https://user-images.githubusercontent.com/46451124/78456676-eceaad80-769c-11ea-96e7-88653b1ada19.png)
![Screenshot 2020-04-04 at 17 44 47](https://user-images.githubusercontent.com/46451124/78456679-f411bb80-769c-11ea-9434-f5880f046fa6.png)

### Environment

* Vapor Framework version: Cannot get due to compilation error
* Vapor Toolbox version: 3.1.10
* OS version: 10.15.3

**Comment by 0xTim** [comment]
It's a bug in the 5.2 compiler - see [this forum post](https://forums.swift.org/t/vapor-3-swift-5-2-regression/34764) for the fix
