### ISSUE TITLE
Filter query

### ISSUE THREAD

**Issue by jose46moreno** [vapor/vapor#2299]
I can't find information in the documentation on how to perform a filtering action on the database in Vapor 4 beta.

I've tried to do it like in Steam 3, but it gives me error.

I have attached an image, where the value against which I compare it is optional, so that if it doesn't exist, I don't make the comparison and return them all without filters.

<img width="1062" alt="Captura de pantalla 2020-04-09 a las 20 02 15" src="https://user-images.githubusercontent.com/8105593/78926246-0d4fa900-7a9d-11ea-8338-8f7016679513.png">

**Comment by mcdappdev** [comment]
This should be:

```swift
Users.query(on: req.db).filter(\.$name == filterData.name).all()
```

(Notice the $ before the property, that accesses the underlying value of the property wrapper)

**Comment by jose46moreno** [comment]
And to make contains?

That is, to check if a String contains another one, etc...

**Comment by jose46moreno** [comment]
In addition, the answer you have given does not allow for optional use.

It is attached here if you allow it:

Users.query(on: req.db).filter("name", ., filterData.name).all()
