### ISSUE TITLE
Question for connecting MySQL

### ISSUE THREAD

**Issue by mohok** [vapor/vapor#2301]
I'm on migrating Vapor 3 to 4.
I got errors when I tried to access same database(AWS RDS - MySQL 5.6.44).

What is the difference between Vapor3 and Vapor4? How can I access my database? 
### Steps to reproduce
Use same MySQL config.
* Vapor3

`MySQLDatabaseConfig(
    hostname: "hostname",
    username: "username",
    password: "password",
    database: "database")`

* Vapor4

`  app.databases.use(.mysql(
    hostname: "hostname",
    username: "username",
    password: "password",
    database: "database"
    ), as: .mysql)
`

### Expected behavior
Accessing.

### Actual behavior

[ ERROR ] handshakeFailed(NIOSSL.BoringSSLError.sslError([Error: 268435581 error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED]))

### Environment

* Vapor Framework version: 4.0.0-rc3.12
* Vapor Toolbox version:
* OS version: macOS 10.15.4

**Comment by TomShen1234** [comment]
(Just contributing some informations here, I’m not the dev)

I ran into this issue a while ago. I think this happens when the MySQL server does not have a valid SSL certificate. If you don’t mind about that, you can turn off the ssl mode by following the instruction here:

https://serverfault.com/questions/770618/how-to-disable-ssl-plugin-on-mysql-5-7-server

**Comment by mohok** [comment]
> (Just contributing some informations here, I’m not the dev)
> 
> I ran into this issue a while ago. I think this happens when the MySQL server does not have a valid SSL certificate. If you don’t mind about that, you can turn off the ssl mode by following the instruction here:
> 
> https://serverfault.com/questions/770618/how-to-disable-ssl-plugin-on-mysql-5-7-server

Thanks for your replying. :)

I just solved this problem. The main problem was 'hostname' on my server.

Vapor 4 is starting `http://127.0.0.1:8080` by default. So, I set hostname to
 `app.http.server.configuration.hostname = "localhost"`
 
Then, It works well. 😀

**Comment by kennyevo** [comment]
Sorry for bumping a closed issue, but I had the same issue.
Disabled SSL on the mysql server, but now I get the following:
`MySQL error: A secure connection to the server is required for authentication.`

Or if I change the password type to native in mysql, I get the following:
`MySQL error: Unknown protocol error`

Even tried to change the hostname to localhost

**Comment by tanner0101** [comment]
@kennyevo which version of the MySQL package are you using?

**Comment by RobertoMachorro** [comment]
Having same issue with Vapor 4.65.1, mysql-no 1.4.0, mysql-kit 4.5.2.

**Comment by 0xTim** [comment]
@RobertoMachorro Discord is the best place to get help, there are a number of different things that could cause this

**Comment by RobertoMachorro** [comment]
Thanks! In the end this is the code that worked (note having to do the tlsConfig with *.makeClientConfiguration*):

```swift
	var tlsConfig = TLSConfiguration.makeClientConfiguration()
	tlsConfig.certificateVerification = .none

	app.databases.use(.mysql(
        hostname: Environment.get("DATABASE_HOST") ?? "127.0.0.1",
        port: Environment.get("DATABASE_PORT").flatMap(Int.init(_:)) ?? MySQLConfiguration.ianaPortNumber,
        username: Environment.get("DATABASE_USERNAME") ?? "vapor_username",
        password: Environment.get("DATABASE_PASSWORD") ?? "vapor_password",
        database: Environment.get("DATABASE_NAME") ?? "vapor_database",
		tlsConfiguration: tlsConfig
    ), as: .mysql)
```
