### ISSUE TITLE
[Vapor 4] ErrorMiddleware: `CorsMiddleware` headers are not propagated if we throw an `Abort` error

### ISSUE THREAD

**Issue by MaherKSantina** [vapor/vapor#2303]
Amazing job on Vapor 4 BTW! 

I have a small issue

I was wondering if I have a `CorsMiddleware` in place, I'd expect that the cors headers to be sent too even if I throw `Abort` errors in my code.

The use case for this is that, I have an application that tries to login with my Vapor API, on successful login everything goes great and the cors headers are sent properly. However, if the login failed, I'm throwing an `Abort(.unauthorized)` error. But from the app's perspective, I would need to gracefully catch that error and show a message `Email or password is incorrect`. I wouldn't be able to do that if the cors headers don't get sent back with the error response because the browser will block the request. 
A simple way to fix this is to pass the cors headers as arguments with the `Abort` error, but then I would need to pass these headers to every `Abort` error I'm throwing. And to me, it makes sense that this configuration should be global in a way.

There are different solutions around this issue but it comes back to the main use case:
I need my middleware headers to be passed no matter what the response is

### Steps to reproduce

1. Use a default Vapor template
2. Add cors middleware
```swift
app.middleware.use(CORSMiddleware(configuration: .default()))
```
3. Create a get route
4. throw `Abort(.unauthorized)` in route
5. Make call to specific route

### Expected behavior
On my Client, I'm expecting to get the cors headers

### Actual behavior
On my client, I'm not getting the cors headers

### Environment
I'm using `vapor-beta` and couldn't get the version 😢 
OSX version: 10.15.3

### Possible Solution
As a quick and dirty solution, I changed the init for ErrorMiddleware to this:
```swift
public static func `default`(environment: Environment, configuration: CORSMiddleware.Configuration) -> ErrorMiddleware
```
And I added all Cors logic in there and now it's working as expected, but I don't think that's the ideal solution

I'm not sure if that's something you guys would pursue so please let me know your thoughts, I'm also happy to create a pull request to help you out. 
I hope I explained myself properly as this is my first issue here. Keep up the great work! 🕺

**Comment by grundoon** [comment]
This was just added to the docs today (see the very bottom): https://docs.vapor.codes/4.0/middleware/

Also see https://github.com/vapor/vapor/issues/2295 for more discussion.

**Comment by MaherKSantina** [comment]
Thanks @grundoon! 
Haha I just read them before seeing your comment and was coming to close the ticket. I think it worked for me after I updated the library

Have a great day!
