### ISSUE TITLE
failed build vaoor app how to fix it

### ISSUE THREAD

**Issue by linuxbiekaisar** [vapor/vapor#2307]
### Environment

* Vapor Framework version:
* Vapor Toolbox version:
* OS version:
![Screenshot from 2020-04-11 08-29-25](https://user-images.githubusercontent.com/60579529/79033304-ff01aa00-7bce-11ea-8226-d1cf049def40.png)

**Comment by Joannis** [comment]
Can you post a few more details? The things that are in the issue template.

**Comment by jhoughjr** [comment]
Also maybe try swift build -v to get verbose output.
