### ISSUE TITLE
Support for content type "application/hal+json"

### ISSUE THREAD

**Issue by pajapro** [vapor/vapor#2309]
Hi there, I playing out with Vapor 4.0.1 (exciting 🤗), where I want call an external API from my Vapor app. This external API returns response with `Content-Type: application/hal+json`. When trying to [decode the response](https://docs.vapor.codes/4.0/content/#decoding) it fails (expectably) with `Abort 415: Unsupported Media Type`. 

### Steps to reproduce
Call API which returns `application/hal+json` content type.

```
app.client
	.get(request)
	.map { response in
		// Vapor does not support `content-type` of `application/hal+json` ☹️, therefore need to do the heavylifting
		do {
			let model = try response.content.decode(Model.self)
			print(model)
		} catch {
			print(error) // Abort 415: Unsupported Media Type
		}
	}
```

### Expected behavior
I guess, that I will need to implement custom content decoder ([Content](https://docs.vapor.codes/4.0/content/#custom-coders)) is there an easy way to do that? 

Alternatively, how can I overcome this issue by force using JSON decoder instead and ignore the [HAL](https://en.wikipedia.org/wiki/Hypertext_Application_Language) parts in response? 

### Actual behavior
`Abort 415: Unsupported Media Type` is thrown.

### Environment
vapor-beta
* Vapor Framework version:
4.0.1
* Vapor Toolbox version:
vapor-beta
* OS version:
10.15.4

**Comment by m-barthelemy** [comment]
@pajapro if you want to "force using JSON decoder" because your `hal+json` content is, in fact, just JSON, then you can add a `HTTPMediaType` extension to your code:

```swift
public extension HTTPMediaType {
    static let hal = HTTPMediaType(type: "application", subType: "hal+json")
}
```

and define the decoder to use for this new media type in your Vapor4 config:
```swift
ContentConfiguration.global.use(decoder: JSONDecoder(), for: .hal)
```

**Comment by tanner0101** [comment]
@m-barthelemy's solution is the correct solution 👍. More information here: https://docs.vapor.codes/4.0/content/#override-defaults

**Comment by pajapro** [comment]
Thanks for advice @m-barthelemy and @tanner0101 , unfortunately the response is in fact `hal+json` content. Therefore the suggested workaround to force use `JSONDecoder` does not work for `hal+json` content. What are my other options to be able to parse this type of responses within writing custom decoder 🤔?

**Comment by grundoon** [comment]
@pajapro I think the point being made by @m-barthelemy is that `hal+json` _is_  just JSON. The `hal+` part simply specifies that the JSON-encoded content can be expected to be of type `HAL`.

As long as you have a `Content`-conforming model appropriate for the expected content, it should decode just fine using the supplied approach. Can you further describe the conditions of the error you are encountering?

**Comment by pajapro** [comment]
> As long as you have a Content-conforming model appropriate for the expected content, it should decode just fine using the supplied approach.

@grundoon you're right. I was using still RC version of Vapor in which the above mentioned approach didn't work and resulted in `Abort 415: Unsupported Media Type` error. Updating Vapor dependency to `4.4.0` fixed the problem.

Thank you very much for your support 🙏
