### ISSUE TITLE
Unable to create Xcode Project

### ISSUE THREAD

**Issue by NG235** [vapor/vapor#2311]
Hello.

I just installed Vapor on my MacBook running macOS Catalina version 10.15.4.
When I run ```vapor xcode``` from the terminal, generating the Xcode project fails.
Below/attached is a screenshot.

I have attempted running the command as an admin (```sudo vapor xcode```) but that did not work.

Thank you.

![Screen Shot 2020-04-14 at 7 55 03 pm](https://user-images.githubusercontent.com/51286292/79215650-09e86300-7e8b-11ea-9234-11f0acb90214.png)

**Comment by 0xTim** [comment]
If you have Xcode 11, don't use `vapor xcode`, just use `open Package.swift` instead. 

It looks like Homebrew has rewritten your command line tools, so run `sudo xcode-select -s /Applications/Xcode.app` (or wherever your Xcode lives) and try again

**Comment by NG235** [comment]
Thank you for the quick response. That has solved the issue.
