### ISSUE TITLE
Vapor client GET Request not forwarding request and timing out

### ISSUE THREAD

**Issue by Andrew-Venovis** [vapor/vapor#2313]
### Steps to reproduce

Create a GET request using client get request. Sample Code:
```
router.get("Test") {
            request -> Future<Response> in
            return try request.client().get("https://postman-echo.com/get?foo1=bar1&foo2=bar2") {
                get in
                get.http.headers = request.http.headers
            }.flatMap {$0.http.body.consumeData(on: request)}.map(to: Response.self) { /// Code doesn't even reach here and times out.
                response in
                var http = HTTPResponse(status: .ok)
                http.contentType = .json
                http.body = response.convertToHTTPBody()
                return Response(http: http, using: request)
            }
        }
```

### Expected behavior

Response sends back data to client

### Actual behavior

Connection times out.

### Environment

* Vapor Framework version: 3
* Swift version: 5.2
* Vapor Toolbox version: 3.1.10
* OS version: OSX Catalina 10.15.4

**Comment by 0xTim** [comment]
Do you know if it hits `$0.http.body.consumeData(on: request)` and second question why are you doing that?

You could just write it as:
```swift
router.get("Test") { request -> Future<HTTPResonse> in
    return try request.client().get("https://postman-echo.com/get?foo1=bar1&foo2=bar2") { get in
        get.http.headers = request.http.headers
    }.map { response in
        var http = HTTPResponse(status: .ok)
        http.contentType = .json
        http.body = response.body
        return http
    }
}
```

**Comment by Andrew-Venovis** [comment]
It looks like it, the code seems to break at line 680 in EventLoop.swift when running it through the debugger. I tried your version but the result remains the same. 

The goal is to make an API gateway for the microservices and vysg reported on discord that using client to simply route and return Response tends to break, so creating a HTTPResponse was to fix that, until it broke yesterday. 

Implementation wise we made a class extending RouteCollection, and subclasses for various microservices to register the routes.

**Comment by Andrew-Venovis** [comment]
Upon further investigation, extending RouteCollection with a class rather than a struct leads to the hangup on GET Requests

**Comment by Andrew-Venovis** [comment]
The cause of GET requests breaking is caused by assigning headers,

for example:
```
request.client().get(url) {
    get in
    get.http.headers = request.http.headers /// This bit here will cause a timeout
}
```

This can be rectified by assigning individual headers to the request rather than broadly assigning headers.

**Comment by tanner0101** [comment]
That makes sense as the current request headers may not be valid for the outgoing request. You should set specifically the ones you want 👍
