### ISSUE TITLE
ETag support

### ISSUE THREAD

**Issue by grosch** [vapor/vapor#2318]
Vapor doesn't currently support HTTP ETag headers, and it would be nice if it were to do so.  An ETag is a representation of the data that clients can use to sync with the server.  There are two main uses of an ETag. 

1. When a GET request is made the client passes the ETag, previously received from the server, in an If-None-Match header.  The server examines that header, compares it to the ETag which _would_ be returned, and if they are the same, it replies with a 304 (Not Modified) status code.  It does not send any data back.  This prevents unnecessary data transfers.
2. Prevents "lost update" issues.  I GET the object I want to modify, make my changes locally on the client, and then PUT/PATCH that item back to the server.  This time, I send the ETag in an If-Match header.  When the server sees that it determines the current ETag of the object and ensures that they are the same.  If they aren't, then a 412 (Precondition Failed) is returned telling the client that inbetween when they fetched the object and when the PUT/PATCH was sent, someone else modified the entity.

The second item is pretty easy to handle, via this extension.

```swift
public extension EventLoopFuture where Value: EntityTaggableModel {
    /// Verifies that the ETag stored in the database matches the ETag passed via the `If-Match` HTTP header.
    /// - Parameters:
    ///   - req: The `Request` object.
    func verifyETag(on req: Request) -> EventLoopFuture<Value> {
        return self.flatMapThrowing { model -> Value in
            guard let ifMatch = req.headers.first(name: .ifMatch) else {
                throw Abort(.badRequest, reason: "Missing If-Match HTTP Header.")
            }

            guard ifMatch == model.eTag else {
                throw Abort(.preconditionFailed, reason: "Model state is no longer valid.")
            }

            return model
        }
    }
}
```

You would simply add that `verifyETag(on:)` method after the database query but before the map call if you want to do that verification.

The first one is harder. The client has to have a way to identify _what_ the ETag should be.  There are currently three thoughts around this.

1. Deep integration with `Content`
2. Middleware
3. Static methods on `Response`

The first option is highly error prone as it assumes that the content itself represents the ETag which is desired. While that might be true frequently it removes the ability of people to do weak validator etags. it also means there has to be a **known** way to convert that content to ETag.  So now we're forcing something like a JSON encoder to determine the content, ensuring keys are ordered, etc...

The second option is a non-starter because it would assume that *every* response should have an ETag, and that's definitely not going to be OK in many use cases. It also depends on the deep integration with Content working.

The third option is to extend `Response` with a `withETag`  set of methods which will add the eTag to the HTTP header.  It's much more adaptable for different uses cases, but does mean that people are no longer simply returning their `Model`/`Content` but are instead now returning a `Response`. As this would be 100% opt-in I don't feel there's much concern there.

My initial implementation (https://github.com/vapor/fluent/pull/675/files) implements the third option.  If somebody wants their model to support ETag they use the `EntityTaggableModel` protocol and then the static methods on the `Response` object.  In my initial testing it's working quite well.

There's no *standard* on how frameworks do this.  Generally you have to implement all of it yourself.  Because Fluent has a standard `Model` type though that we can extend it becomes pretty easy to support this generically by storing an etag in the model (which is a common solution people use).

Having a generic way to support this for `Content` would be much more difficult.

**Comment by tanner0101** [comment]
Here's a more in-depth explanation of what I mean by "integration with Content" (1). 

```swift
protocol TaggedContent: Content {
    // Can be implemented however you want, for example
    // using a JSON encoder with sorted keys
    //
    // By default, implemented with a "swift specific" 
    // encoding using hashable
    var tag: String? { get }
} 

extension TaggedContent where Self: Hashable {
    var tag: String? {
        self.hashValue.description
    }
}

final class Todo: Model {
    ...
}

extension Todo {
    struct Output: TaggedContent {
        var id: UUID
        var title: String
    }

    var output: Output {
        .init(id: self.id!, title: self.title)
    }
}

extension Todo {
    struct Update: Content {
        var title: String?
    }

    func update(to update: Update) {
        if let title = update.title {
            self.title = title
        }
    }
}

// 1.
// Since Todo.Output conforms to TaggedContent, its tag
// can be compoared to the incoming request's tag before
// returning.
app.get("todos", ":id") { req -> EventLoopFuture<Todo.Output> in
    Todo.find(req.parameters.get("id"))
        .unwrap(or: Abort(.notFound))
        .flatMapThrowing 
    { todo in
        guard todo.output.tag != req.content.tag else {
            throw Abort(.notModified)
        }
        return todo.output
    }
}

// 2. 
// Since Todo.Output conforms to TaggedContent, its tag
// can be compared to the incoming request's tag before
// proceeding with model update. 
app.patch("todos", ":id") { req -> EventLoopFuture<Todo.Output> in
    Todo.find(req.parameters.get("id"))
        .unwrap(or: Abort(.notFound))
        .flatMapThrowing 
    { todo in 
        // Verifies output tag still matches.
        guard todo.output.tag == req.content.tag else {
            throw Abort(.preconditionFailed)
        }
        // Do update. 
        let update = try req.content.decode(Todo.Update.self)
        todo.update(to: update)
        return todo
    }.flatMap { todo in
        todo.update(on: req.db).map {
            todo.output
        }
    }
}
```

I think this could play interesting into native DTO support in Vapor as well. For example, what if `Content` allowed a type to declare `Create`, `Read`, `Update` and `Replace` DTOs? Could we get a more concise API like:

```swift
// 1. 
// Automatically uses Todo's "read" DTO for response. 
// Automatically throws 304 Not Modified if the incoming eTag matches.
app.get("todos", ":id") { req -> EventLoopFuture<Todo> in
    Todo.find(req.parameters.get("id"))
        .unwrap(or: Abort(.notFound))
}

// 2.
// Automatically uses Todo's "update" (patch) DTO since we call `update`. 
// Automatically throws 412 Precondition Failed if the incoming tag doesn't match. 
app.patch("todos", ":id") { req -> EventLoopFuture<Todo> in
    Todo.find(req.parameters.get("id"))
        .unwrap(or: Abort(.notFound))
        .flatMapThrowing 
    { todo in 
        try req.content.update(&todo)
        return todo
    }.flatMap { todo in
        todo.update(on: req.db).map { todo }
    }
}
```

**Comment by grosch** [comment]
I'd be concerned about including the etag in with the body of the content.  It's supposed to be in the header, not the body.

**Comment by grosch** [comment]
Your idea about better DTO integration is great.  Wouldn't that require that we have some protocols like `UpdateDTO` and `CreateDTO` though so that `req.content.update` knew what it was looking at?

I'd want to see something like `req.content.update` return the model so we could just write this
```swift
.flatMapThrowing { try req.content.update(&$0) }
```

**Comment by grosch** [comment]
For the first item, the GET requests throwing a 412, this is what I've been playing with in my current project.  I'm sure somebody can come up with a much better name

```swift
/// Checks the ETag HTTP header, if it exists, to see if the model has changed.
/// - Parameter req: The `Request` object.
/// - Returns: The model object
/// - Throws: An `Abort(.notModified)` if the header's ETag matches the model's ETag
func abortIfETagUnchanged(on req: Request) -> EventLoopFuture<Value> {
    return self.flatMap { model -> EventLoopFuture<Value> in
        guard let ifNoneMatch = req.headers.first(name: .ifNoneMatch) else {
            return self.eventLoop.makeSucceededFuture(model)
        }

        guard ifNoneMatch != model.eTag else {
            return self.eventLoop.makeFailedFuture(Abort(.notModified))
        }

        return self.eventLoop.makeSucceededFuture(model)
    }
}
```

**Comment by grosch** [comment]
I started a separate item at #2319 to specifically discuss the DTO related enhancement that @tanner0101 raised.  Let's please keep this one focused on the ETag parts.

**Comment by grosch** [comment]
Instead of a property we could make a `headers()` method and then people could add whatever headers they wanted. That way they could also add things like caching or custom headers and not pollute the body.

**Comment by grosch** [comment]
This would still break down if the ETag were stored in the database, and was dependent on the content of the body because there'd be no way to pass the etag to the content.  Even using the `headers()` method that would mean we'd have to still store the etag as a property, which then means using `CodingKeys`.  It's really annoying that Swift doesn't let you just add a property wrapper or something to prevent a property from being JSON encoded!

**Comment by grosch** [comment]
Tagging @gwynne and @0xTim to get their inputs as well.

**Comment by 0xTim** [comment]
Implemented
