### ISSUE TITLE
Session cookies decoding error

### ISSUE THREAD

**Issue by Rubenfer** [vapor/vapor#2320]
Vapor 4 doesn't decode cookies when other cookies are sent.

Normally, we use localhost as test host with a lot of environments in different ports. I notice that in the login form if the browser sends other cookies, the Vapor session is not working properly. The external cookies are sent in a UUID format.

### Steps to reproduce

In a login form sent other cookies in a UUID format (not just Vapor generated cookie).

### Expected behavior

The session data persists.

### Actual behavior

The session data doesn't persist. It is empty when external cookies are sent.

### Environment

* Vapor Framework version: 4.2.0

**Comment by tanner0101** [comment]
@Rubenfer that should work. Maybe this is related to https://github.com/vapor/vapor/issues/2316? Can you share the HTTP request headers that are causing the problem?

**Comment by Rubenfer** [comment]
I have been doing some tests to find the error.
Looks like it fails when in headers are sent a cookie with a number in the name. The best way to try it is customize the vapor cookie name, for example:
`app.sessions.configuration.cookieName = "session_1234_my_service"`
So the issue is related to #2316.

**Comment by tanner0101** [comment]
Ah okay, updating to `4.2.1` should fix that then: https://github.com/vapor/vapor/releases/tag/4.2.1
