### ISSUE TITLE
Not possible to install vapor-beta

### ISSUE THREAD

**Issue by mynonaGithub** [vapor/vapor#2323]
Not possible to install vapor beta
MacOS 10.15.4 / Xcode 11.4.1

brew install vapor/tap/vapor-beta

==> Installing vapor-beta from vapor/tap
==> Downloading https://github.com/vapor/toolbox/archive/18.0.0-beta.27.tar.gz
Already downloaded: /Users/kaeru/Library/Caches/Homebrew/downloads/a17328593022736d0658058db21d6d516deb7c561c088ed71d02f0949e905954--toolbox-18.0.0-beta.27.tar.gz
==> swift build --disable-sandbox
Last 15 lines from /Users/kaeru/Library/Logs/Homebrew/vapor-beta/01.swift:
2020-04-18 11:53:35 +0200

swift
build
--disable-sandbox

error: terminated(72): OBJCXX=clang++ HOMEBREW_CURL=curl HOMEBREW_AUTO_UPDATE_CHECKED=1 HOMEBREW_GIT=git HOMEBREW_BREW_FILE=/usr/local/bin/brew SHLVL=0 HOMEBREW_DEFAULT_CACHE=/Users/kaeru/Library/Caches/Homebrew HOMEBREW_OPT=/usr/local/opt HOMEBREW_CACHE=/Users/kaeru/Library/Caches/Homebrew CPATH=/usr/local/include HOMEBREW_OS_VERSION=macOS 10.15.4 HOMEBREW_ANALYTICS_ID=UA-76679469-1 CMAKE_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries HOMEBREW_CORE_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/homebrew-core TERM=xterm-256color HOMEBREW_ANALYTICS_USER_UUID=5BCA10C2-6DFC-4ACE-AEBF-4191D3027679 HOMEBREW_CC_LOG_PATH=/Users/kaeru/Library/Logs/Homebrew/vapor-beta/01.swift HOMEBREW_BOTTLE_DOMAIN=https://homebrew.bintray.com CARGO_HOME=/Users/kaeru/Library/Caches/Homebrew/cargo_cache HOMEBREW_SYSTEM=Macintosh HOMEBREW_TEMP=/private/tmp HOMEBREW_MACOS_VERSION_NUMERIC=101504 HOMEBREW_COMMAND_DEPTH=2 HOMEBREW_ARCHFLAGS= HOMEBREW_CCCFG=sa HOMEBREW_CC=clang HOMEBREW_MACOS_VERSION=10.15.4 SHELL=/bin/bash HOMEBREW_ERROR_PIPE=/private/tmp/homebrew20200418-94797-1sqtz20/socket HOMEBREW_LOGS=/Users/kaeru/Library/Logs/Homebrew HOMEBREW_OPTIMIZATION_LEVEL=Os HOMEBREW_DEFAULT_LOGS=/Users/kaeru/Library/Logs/Homebrew CURL_HOME=/Users/kaeru HOMEBREW_BREW_DEFAULT_GIT_REMOTE=https://github.com/Homebrew/brew PATH=/usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin PWD=/Users/kaeru HOMEBREW_BREW_GIT_REMOTE=https://github.com/Homebrew/brew HOMEBREW_VERSION=2.2.13 HOMEBREW_CXX=clang++ _JAVA_OPTIONS=-Duser.home=/Users/kaeru/Library/Caches/Homebrew/java_cache HOMEBREW_PREFIX=/usr/local HOMEBREW_CELLAR=/usr/local/Cellar HOMEBREW_USER_AGENT_CURL=Homebrew/2.2.13 (Macintosh; Intel Mac OS X 10.15.4) curl/7.64.1 CXX=clang++ CC=clang HOMEBREW_DEPENDENCIES= LOGNAME=kaeru HOMEBREW_SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk HOMEBREW_PREFER_CLT_PROXIES=1 SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.EAr6ZmClBJ/Listeners CMAKE_INCLUDE_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers LC_ALL=en_US.UTF-8 HOMEBREW_LIBRARY=/usr/local/Homebrew/Library HOMEBREW_FORMULA_PREFIX=/usr/local/Cellar/vapor-beta/18.0.0-beta.27 TMP=/private/tmp HOMEBREW_RUBY_PATH=/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby TMPDIR=/private/tmp ACLOCAL_PATH=/usr/local/share/aclocal CMAKE_PREFIX_PATH=/usr/local HOMEBREW_GIT_CONFIG_FILE=/usr/local/Homebrew/.git/config HOMEBREW_PRODUCT=Homebrew HOMEBREW_CORE_GIT_REMOTE=https://github.com/Homebrew/homebrew-core USER=kaeru TEMP=/private/tmp __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x5C MAKEFLAGS=-j12 HOMEBREW_MINIMUM_GIT_VERSION=2.14.3 HOMEBREW_ISYSTEM_PATHS=/usr/local/include:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers GOCACHE=/Users/kaeru/Library/Caches/Homebrew/go_cache HOMEBREW_PROCESSOR=Intel HOME=/private/tmp/vapor-beta-20200418-95462-1333wgn/toolbox-18.0.0-beta.27/.brew_home HOMEBREW_USER_AGENT=Homebrew/2.2.13 (Macintosh; Intel Mac OS X 10.15.4) OBJC=clang HOMEBREW_DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk HOMEBREW_REPOSITORY=/usr/local/Homebrew HOMEBREW_RUBY_WARNINGS=-W0 HOMEBREW_BOTTLE_DEFAULT_DOMAIN=https://homebrew.bintray.com LIBRARY_PATH=/usr/local/lib PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15 HOMEBREW_ENV=super HOMEBREW_DEFAULT_TEMP=/private/tmp HOMEBREW_OPTFLAGS=-march=nehalem HOMEBREW_LIBRARY_PATHS=/usr/local/lib:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries xcrun --sdk macosx --find xctest output:
    xcrun: error: unable to find utility "xctest", not a developer tool or in PATH
    

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/vapor/homebrew-tap/issues

These open issues may also help:
Update vapor-beta.rb to include latest toolbox release https://github.com/vapor/homebrew-tap/pull/30

**Comment by 0xTim** [comment]
Closing in favour of vapor/homebrew-tap#31
