### ISSUE TITLE
Microservices in monorepository setup

### ISSUE THREAD

**Issue by nugmanoff** [vapor/vapor#2324]
Hello, everyone!

I am trying to setup microservices on Vapor 4, I have watched a few videos and articles here and there. But all of them use multirepository setup, where each individual microservice resides in its own repository. What I am trying to achieve is the opposite - to have them all in one repository.

I understand it is no big deal to just have create several separate folders in one repository - and that should be it. But there are few particular perks that I want to benefit from having monorepository (please correct me if I am wrong and some of them are not possible & I am just misunderstanding the way S3 works):

- I want to have some root `Package.swift` that includes some shared dependencies (e.g. SwiftLint, SwiftFormat). And inside that `Package.swift` have different targets (or maybe prodcuts?) representing microservices. 
- At the same time I need to keep my individual microservices independent so that I can deploy them independently (AFAIK because that's what mainly they are all about). Each of them needs to be able to describe its own dependencies (via `Package.swift` obviously)
- So I will have some command to get all of my system up and running & as well as ability to start each microservice individually. 

[Some referenced](https://medium.com/reachnow-tech/swift-package-manager-in-a-monorepo-430665228594)

**Comment by jonny7** [comment]
This is probably best suited for discord https://discord.gg/BnXmVGA 😄
