### ISSUE TITLE
Question: about return types in a route?

### ISSUE THREAD

**Issue by diuming** [vapor/vapor#2328]
macOS 10.15.4
Vapor 4.3.0

I'm a newcomer in Vapor.
I have no idea for return type, please following
session.get("login") { (request) -> `EventLoopFuture<View>` in
could you give me advice?
thanks.

MyRoute.swit
---
```
func myRoute(_ app: Application) throws {
    let session = app.routes.grouped([SessionsMiddleware(session: app.sessions.driver),
                                      UserSessionAuthenticator(),
                                      UserCredentialsAuthenticator()])
    session.get("login") { (request) -> EventLoopFuture<View> in
        if request.auth.get(User.self) != nil {
            return request.redirect(to: "/go_some_place") // <- here
        }
        return request.view.render("./Leaf/Login.leaf")   // <- here
    }
}
```

**Comment by tanner0101** [comment]
@diuming for routes that return more than one type you have a couple of options:

- Return `Response`. 

You can call `makeResponse` on `View` and any other type conforming to `ResponseEncodable` (`Content`).

- Return `AnyResponse`. 

You can wrap any `ResponseEncodable` type in the `AnyResponse` struct. 

- Return an enum. 

You could create an enum for both cases and return that:

```swift
enum ViewOrRedirect: ResponseEncodable {
    case view(View)
    case redirect(to: String)
    func makeResponse(...) { ...}
}
```

**Comment by diuming** [comment]
@tanner0101 thanks! I got it.
