### ISSUE TITLE
Thread-safe storage

### ISSUE THREAD

**Issue by Frizlab** [vapor/vapor#2330]
Accessing or setting the App’s storage should be done in a thread-safe manner, or we can easily get segfault if we change the storage during the processing of a request.

### Steps to reproduce
Change a storage you control in the processing of a request. For instance:
```swift
req.application.locks.lock(for: MyStorage.self).withLockVoid{
   req.application.storage[MyStorage.self] = "toto"
}
```
As you can see the change is done in a lock to ensure only one request at a time changes the storage.

### Expected behavior
The app should not crash.

### Actual behavior
The app crashes randomly, usually in `Storage.swift`, at line 44 (storage getter), because the storage is accessed while being modified in another thread.

### Environment

* Vapor Framework version: 4.3.0
* Vapor Toolbox version: N/A
* OS version: Debian Stretch

**Comment by Frizlab** [comment]
Random thought: Because of performance issue, the storage may have to be modified to be read-only after the configuration of the app is done in order to avoid the penalty cost of locking each access to the storage.

**Comment by Joannis** [comment]
@Frizlab what are you trying to store inside of the application storage? And shouldn't you use a database here?

**Comment by Frizlab** [comment]
@Joannis Yes, I should definitely be using a db, w/o a doubt. But this is a small project used internally only and I didn’t want to go to the trouble of setting a proper db (I only store a [String: Date], modified at each request).

To solve the concurrency issue, I have created a MyProjectStorage class which contains the dictionary I want, and I mutate the class in a lock (which does not mutate Vapor’s storage).

Which brings me to: Vapor’s storage should be r/o once the app setup has been done, otherwise all accesses/modifications to it should be done in a global lock, which would probably incur a big cost on the access. I might be wrong on that one, but that is how I see it 🙃

**Comment by Joannis** [comment]
Personally, I'd use an EventLoop to submit these tasks to. And have function calls to the dictionaries provide a completing promise that the results are dumped into. That way, even if the dictionary is locked for a long time, the (other) EventLoops aren't waiting on that. But on a small scale that's not a worry, this is mainly a heads up for other people reading this.

Most of the objects I normally put inside of the storage container use the above principle, like database drivers. Other usecases are pretty static data, such as a JWT signing key.

**Comment by 0xTim** [comment]
Resolved with `Sendable`
