### ISSUE TITLE
What is the default payload size in Vapor 4, and how can I change it?

### ISSUE THREAD

**Issue by TomShen1234** [vapor/vapor#2332]
I am making a website that allows uploading files through a `multipart/form-data` HTML form. However, even when I select a relatively small image file (700KB), I still gets the `413 Payload Too Large` error. I checked the `app.http.server.configuration` property, there doesn't seems to be a way to increase it. 

Where is this setting available for me to change?

* Vapor Framework version: 4.3.0
* OS version: macOS 10.15.4

**Comment by tanner0101** [comment]
Use `router.on(_:_:body:)`.

```swift
router.on(.POST, "...", body: .collect(maxSize: ...)) { req in 
    ...
} 
```

More info here: https://docs.vapor.codes/4.0/routing/#body-streaming

We're working on making this globally configurable: https://github.com/vapor/vapor/pull/2312
