### ISSUE TITLE
Support $PORT and $HOSTNAME

### ISSUE THREAD

**Issue by tanner0101** [vapor/vapor#2333]
Support `PORT` and `HOSTNAME` environment variables for setting server configuration. These should override the default configured port / hostname when present in the environment. `--port` and `--hostname` passed via the CLI should still take precedent. 

https://github.com/vapor/api-template/pull/93#issuecomment-618751767

**Comment by gwynne** [comment]
@tanner0101 To fully replace the functionality currently found to be unavailable via `CMD` in `Dockerfile`s (for multiple reasons), you will also need an `ENVIRONMENT`, `ENV`, or (my personal favorite) `VAPOR_ENV` corresponding to `--env`.

**Comment by tanner0101** [comment]
From Discord, these seem like the best options in terms of variable naming:
- LOG_LEVEL
- SERVER_HOSTNAME
- SERVER_PORT
- VAPOR_ENV

**Comment by mattpolzin** [comment]
Not sure if it’s really worth much to support Heroku out of box but that would come for free with the ENV var named PORT
