### ISSUE TITLE
Support for Content-Range

### ISSUE THREAD

**Issue by AKazm** [vapor/vapor#2341]
Vapor currently does not support content ranges at all. This is fine in most cases, but **not** for streaming content like video or audio. Safari, for example, [requires proper support](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6) of valid HTTP 206 Responses for streaming.

I've already implemented a first version of it, which _seems_ to be working fine. 

I unfortunately don't have enough time for contributing to Vapor on a regular basis, nor am I experienced with contributing to Open Source projects (I've never done this, to be honest). However, I'd be happy to share my code with you guys so you'll at least got something to start with.

So, how to proceed with this, if at all? Pull Request?

**Comment by 0xTim** [comment]
@AKazm yes if you have a working implementation a pull request is the best way forward to kick things off. You can fork the repo (as described [here](https://help.github.com/en/github/getting-started-with-github/fork-a-repo), commit your changes to that repo and then submit a PR, as described [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). 

(Apologies if the doc links are a bit basic but I thought I'd provide them just in case you weren't sure!)

**Comment by AKazm** [comment]
Thanks! Don't worry, I know Git (quite well), judr never had the chance to contribute to Open Source projects, which tend to have higher standards than projects developed within a company.

**Comment by 0xTim** [comment]
Closed in #2342
