### ISSUE TITLE
A problem with Vapor app deployed to Heroku

### ISSUE THREAD

**Issue by NoFearJoe** [vapor/vapor#2343]
I've deployed my Vapor app to Heroku, but when I try to make a request, it fails with the error:

`at=error code=H10 desc="App crashed" method=GET path="/feed" host=detect-api.herokuapp.com request_id=970e4005-58b0-4b34-8489-715dc9cd5e19 fwd="5.228.26.4" dyno= connect= service= status=503 bytes= protocol=https`

Also, I get the next logs:

```
State changed from crashed to starting
State changed from starting to crashed
```

My Procfile contains the next code:

`web: Run serve --env production --hostname 0.0.0.0 --port $PORT`

I added config variable "PORT = 5432" to the Settings on Heroku.

In the `configure.swift` file I added this code:

```
let nioServerConfig = NIOServerConfig.default(
    hostname: "0.0.0.0",
    port: Int(Environment.get("PORT") ?? "") ?? 8080
)
services.register(nioServerConfig)
```

### Steps to reproduce

The commands I run:
- git push heroku master
- heroku ps:scale web=1

### Expected behavior

Requests respond with the 200th status code.

### Actual behavior

Requests respond with the 503rd status code.

### Environment

* Vapor Framework version: 3
* Vapor Toolbox version: 3.1.10
* OS version: 10.14.6

**Comment by jhoughjr** [comment]
It looks to me like you are starting your server on the same port as postgres.

**Comment by NoFearJoe** [comment]
@jhoughjr Maybe I use wrong port number, but I tried to set different port numbers and results were the same.

**Comment by jhoughjr** [comment]
Can you see the logs related to the crash?
It seems likely its crashing due to port in use.
Id try to find the crash reason to proceed.

**Comment by vzsg** [comment]
While it might not be the cause of the app crashing (with this much info it could be anything; full logs are welcome), do not, ever, try to set PORT as a custom configuration value. It will be handled by their system.

**Comment by NoFearJoe** [comment]
I've solved the problem by replacing SQLite with PostgreSQL.

**Comment by vzsg** [comment]
Good to know.

**Comment by jolebowski** [comment]
hello,

I use postgres and I have the same error

**Comment by vzsg** [comment]
Same error? As in the app crashed at startup? Because that's the only error that was mentioned in this issue, and even then, we never got to see the actual logs of the app – where the real problem would be found.

If you're still having issues with your app launching, I recommend asking on the Discord server.
