### ISSUE TITLE
Calling request.query.encode multiple times overwrites result of previous calls

### ISSUE THREAD

**Issue by toineheuvelmans** [vapor/vapor#2344]
When constructing a `ClientRequest` I want to make two calls to `query.encode(...)`. It turns out that the second call overrides any result from the first call. It seems that `URLEncodedFormEncoder` (the encoder used by `URLQueryContainer`) simply sets `url.query` on every call to `encode`, instead of appending to `url.query` if it exists. 

### Steps to reproduce

For example:

```
request.client.get(url) { req in
       req.query.encode(userParams)
       req.query.encode(searchParams)
}
```

### Expected behavior

In the example above I would expect both the `userParams` and the `searchParams` to be encoded in the URL query.

### Actual behavior

Only the `searchParams` are encoded. If you set breakpoints you can observe that the `userParams` are encoded properly but then overwritten by `searchParams`.

### Environment

* Vapor Framework version: 4.5.0
* Vapor Toolbox version: `vapor-beta`
* OS version: 10.15.3

**Comment by toineheuvelmans** [comment]
I haven't tested this on `Request` and `XCTHTTPRequest` but their implementation of `query` looks very similar if not identical to that of `ClientRequest`. As such it is likely that this issue also relates to those types.

**Comment by tanner0101** [comment]
This is the expected behavior of `encode`. Luckily you have the full power of `Codable` here so there are a lot of ways to achieve what you want. 

For example, something like this could work:

```swift
struct Search: Encodable {
    let foo: String
}
struct User: Encodable {
    let bar: String
}
struct All: Encodable {
    let search: Search
    let user: User

    func encode(to encoder: Encoder) throws {
        try self.search.encode(to: encoder)
        try self.user.encode(to: encoder)
    }
}

request.client.get(url) { req in
    let all = All(search: searchParams, user:  userParams)
    try req.query.encode(all)
}
```

**Comment by toineheuvelmans** [comment]
@tanner0101 yet that is pretty much exactly what I already did, although using the following:
```
struct CombinedContent<A: Codable, B: Codable>: Content {

    let a: A
    let b: B

    init(_ a: A, _ b: B) {
        self.a = a
        self.b = b
    }

    func encode(to encoder: Encoder) throws {
        try a.encode(to: encoder)
        try b.encode(to: encoder)
    }

    init(from decoder: Decoder) throws {
        a = try A(from: decoder)
        b = try B(from: decoder)
    }
}

infix operator &
func & <A, B>(lhs: A, rhs: B) -> some Content where A: Codable, B: Codable {
    return CombinedContent(lhs, rhs)
}
```

This lets me encode like so:
```
try req.query.encode(user & search)
```

Now, where this _does_ work on `req.content` (which uses the native `JSONEncoder`), this _does not_ work on `req.query` (which uses `URLEncodedFormEncoder`). If you step through it, it boils down to the `_Encoder` in `URLEncodedFormEncoder.swift` which sets its `container` whenever it is asked for a `KeyedEncodingContainer`. In both my example and yours, that happens on encoding `a` and again on encoding `b` (or `search` and `user`). So the container set for `a` is overwritten with the container initialized for `b`.

**Comment by toineheuvelmans** [comment]
So that's `Vapor/URLEncodedForm/URLEncodedFormEncoder.swift` line 135 (in Vapor version 4.5.1)

**Comment by toineheuvelmans** [comment]
@0xTim I filed this issue on [your suggestion](https://discordapp.com/channels/431917998102675485/519613337638797315/706829092892180491) and think that it should be discussed a bit further. I hope you can move it to the Backlog again?

**Comment by tanner0101** [comment]
@toineheuvelmans that inconsistency between `URLEncodedFormEncoder` and `JSONEncoder` sounds like a bug. Would you mind opening a separate issue for that? If you can include a concise reproduction that will help get it fixed quickly. Thanks!
