### ISSUE TITLE
Save Image

### ISSUE THREAD

**Issue by jose46moreno** [vapor/vapor#2346]
I'm trying to save an image.

I have configured the scheme indicating a folder inside my computer where to store the images but when executing the following code, it passes without errors but there is nothing in that folder.

And I confirm that I receive data from the image and that the name of the image is saved in the DDBB.

let workPath = DirectoryConfiguration.detect().workingDirectory
let name = "\(realUser.username)-\(UUID().uuidString).jpg"
let path = workPath + self.imageFolder + name
FileManager().createFile(atPath: path, contents: user.image, attributes: nil)

**Comment by 0xTim** [comment]
[Here's some code](https://github.com/raywenderlich/vapor-til/blob/master/Sources/App/Controllers/WebsiteController.swift#L326-L329) I've used to save files to a directory that works - does the user running the app have permission to write to that directory?

**Comment by jose46moreno** [comment]
Yeah, it's the same code.

And as for the permissions, yes, it's the first thing he asks me when I run the project.

In fact, in the DDBB the string with the name of the image is saved, but in the desktop folder where I told you to save it it does not appear.

**Comment by VineFiner** [comment]
> Yeah, it's the same code.
> 
> And as for the permissions, yes, it's the first thing he asks me when I run the project.
> 
> In fact, in the DDBB the string with the name of the image is saved, but in the desktop folder where I told you to save it it does not appear.

This is demo, can work
https://github.com/BinaryBirds/liquid-local-driver

**Comment by 0xTim** [comment]
@jose46moreno if you can upload a production case that would be great as I'm unable to reproduce

**Comment by jose46moreno** [comment]
> @jose46moreno if you can upload a production case that would be great as I'm unable to reproduce

Could you leave me an email and I'll send you the project so you can try it out?

**Comment by 0xTim** [comment]
This is best for Discord. Find me in there and DM me with the project
