### ISSUE TITLE
Is there any tracking tools for vapor, like Sentry etc.

### ISSUE THREAD

**Issue by lixiaoyu** [vapor/vapor#2349]
### Steps to reproduce
I am using vapor for my backend api service, the service crashed with the error message below. I can't read which line or file of my code caused it. 

> Assertion failed: unexpectedly, fcntl(98, F_SETFL, F_SETNOSIGPIPE) returned nil: file /Users/c3po/services/xxx/.build/checkouts/swift-nio/Sources/NIO/System.swift, line 314
Illegal instruction: 4

The releated System.swift code:

          #if !os(Linux)
                if fd != -1 {
                    let ret = try? Posix.fcntl(descriptor: fd, command: F_SETNOSIGPIPE, value: 1)
                    assert(ret == .some(0),
                           "unexpectedly, fcntl(\(fd), F_SETFL, F_SETNOSIGPIPE) returned \(ret.debugDescription)")
                }
            #endif

It cannot always reproduce, almost once a week it crashes. so i don't know how to reproduce this issues.
I try to add try-catch in main.swift to make it emit more detail error message, but not works.
 **main.swift**
`import App

while (true) {
  do {
    try app(.detect()).run()
  } catch {
    print("Error: \(error)")
  }
}`

### Expected behavior
Any good advice, or methods for trouble-shooting, By the way,is there any tracking tools for vapor, like Sentry etc.

### Environment

* Vapor Framework version: 3.0.0
* OS version: macOS Mojave 10.14.4

**Comment by tanner0101** [comment]
I recommend using something like supervisor to automatically restart your app after a crash. The docs go over this: https://docs.vapor.codes/4.0/deploy/supervisor/. But there are probably lots of other great tools out there. 

This would be a good question for the Swift forums:

- https://forums.swift.org/c/server/43
- https://forums.swift.org/c/related-projects/vapor/30
