### ISSUE TITLE
ContentConfiguration encoder has no effect for custom HTTPMediaTypes

### ISSUE THREAD

**Issue by unibrowed** [vapor/vapor#2350]
When I register an encoder or decoder in the configure method using a custom HTTPMediaType never hits the encoder.  However, if I pass in `.json` it works fine.  It seems custom MediaTypes don't work.

### Steps to reproduce

1. Register an encoder
```Swift
ContentConfiguration.global.use(encoder: CustomEncoder(), for: .init(type: "text", subType: "xml"))
```

2. Make a request passing `text/xml` as a `Accept` in the header.

3. Code never hits the `CustomEncoder`

4. However, if I register for .json it works and hits my `CustomEncoder`
```Swift
ContentConfiguration.global.use(encoder: CustomEncoder(), for: .json)
```

### Expected behavior
Code should enter my `CustomEncoder`

### Actual behavior
Code does not enter the `CustomEncoder`

### Environment

* Vapor Framework version: 4.5.1
* Vapor Toolbox version: 18.0.0-beta.27
* OS version: 10.15.4

**Comment by tanner0101** [comment]
The media type passed to `for` should match the `Content-Type` header of the incoming request. The `Accept` header is used to tell the server which response types the client supports.

**Comment by unibrowed** [comment]
I'm seeing the same thing using Content-Type.
