### ISSUE TITLE
Remember original request location from Auth Redirect Middleware

### ISSUE THREAD

**Issue by TomShen1234** [vapor/vapor#2363]
I'm not sure if this is an enhancement request or a question (aka. the feature already exists). 

Currently the redirect middleware is a great options to redirect away from protected routes while unauthenticated. However, it does not remembers the location of the original request after redirecting. So if someone is taken to the login page from a direct link (e.g. from an email), they will not be able to go back to the original link after logging in. 

I think vapor should add a feature that allows retrieving the original link before redirecting using the redirect middleware (or maybe this feature already exists?). 

### Environment

* Vapor Framework version: Vapor 4.5.1
* OS version: macOS 10.15.4

**Comment by MrLotU** [comment]
I don't think this is in Vapor itself currently. But what many websites do is add the original path to the query of the login page, and redirect there after login. This would be pretty simple to implement yourself, I don't fully see how this design would look if you implemented it directly into Vapor since every website works differently.

**Comment by TomShen1234** [comment]
@MrLotU Thanks for the response. However, if I correctly remembered, the redirect middleware will intercept the request and redirect before actually reaching my own handler block. So unless I implement my own flavor of redirect middleware (into the request handler itself or my own middleware) there isn't really a way to dynamically add it into the login page query, right? (the direct links to my server pages were dynamic, like: `"/post/:id"`)

I think all we need to do to improve this is to make another initializer for the redirect middleware that gives the original request URL back to us through a closure and let us return our own dynamic redirect URL (aka adding a GET query to the login form).

**Comment by MrLotU** [comment]
I think adding a closure to redirect middleware to figure out where to redirect would be a good thing. Would you mind taking a shot at a PR? 😄
