### ISSUE TITLE
issuer of new Model

### ISSUE THREAD

**Issue by bovsheva** [vapor/vapor#2367]
Hello, Vapor Tim!
In create QueenHeavens cloud project  on Vapor docker service. 
And I want to implement Custom Model Creating feature.
This letter about my idea.
My idea is about how to implement CommonModel class that can connect to different database table in Runtime.
Getting metadata from FluentDriver about fields and create Container with fields names and values and types. This CommonModel class can have @ID base field, @createdAt base field,
@deletedAt base field and the Container for custom fields.

Scope: Fluent

### Expected behavior

If Client (my QueenHeavens Service User) wants to create new database table for his own data to store and client can provide all fields information from web UI. Such as field name, field  value, field type and new Model scheme name.

In Vapor service side there is now such common Model class that can reconnect to different database models, getting metadata information from database table than creating container in common Model corresponds database fields.

Of course it can be done with Fluent driver directly and with creating new common Model class.
But I want all functionality for common Model like Model class has in Middleware layer and SQL Query builder.

To provide common Model serialization/deserialization  way we need to convert every field name to KeyPath value to conform Content protocol in Runtime mode and create JSON from common Model. It must be seems that we have such class type. And in back way case we must create container of fields (FluentField) from JSON data getting from web UI. 

So, this common Model has Model behaviour but has another construction.
Common Model  has basic @ID, @createdAt fields from Model  and Container for fields that are not KeyPath fields ( may be FluentField or some metadata about database table columns ).

 This issuer needs for additional database tables creation to provide functionality with permanent links and needs to provide the filter functionality with custom database tables.

* Vapor Framework version: Vapor 4.0
* Vapor Toolbox version:
* OS version:

**Comment by tanner0101** [comment]
Closing this since there's not a clear bug / feature request here.

**Comment by 0xTim** [comment]
@bovsheva I _think_ you're talking about inheritance and having a base class? That won't work with Fluent

**Comment by bovsheva** [comment]
Hello, thanks for answer. I'm sorry for my English -> I'm from Russia   :)

There is no such functionality in Model. ModelAlias implements a part of my desire: ModelAlias can connect to different schema with one model class (for ex. model class Team from your tests and two schemas in db)

```
            final class HomeTeam: ModelAlias {
                static let name = "home_teams"
                let model = Team()
            }

            final class AwayTeam: ModelAlias {
                static let name = "away_teams"
                let model = Team()
            }
```
AwayTeam and HomeTeam incapsulates Team class instance and can provide additional @Field properties via code writing and building.
But I explain about new feature of ModelAlias or Model - additional @Container property for Fluent fields ( add as property of Model or ModelAlias).  

This feature already exists but inside of Fluent. Fluent creates [FieldProperty] array but only from static part code (I mean part of code before service building).

When Model will connect to different schemas in runtime and run query we must merge code fields of Model (from Model code @Field ... ) and dynamic added fields from @Container.
And the next stage is Content and encode/decode functions that must  support @Container property and create JSON.

This feature will be helpful for huge distributed cloud applications like cloud platforms to enable clients to create own db tables and columns via Web UI or iOS configuration applications. 

Thanks, for your attention.
