### ISSUE TITLE
XCTVapor does not preserve session data between calls to .test()

### ISSUE THREAD

**Issue by bottlehall** [vapor/vapor#2376]
I am writing `XCTVapor` unit tests for my recently ported application; a bit late in the day. The application is working fine.

I can successfully test a POST to log-in to the application, but subsequent calls to .test() in the same test function behaves as though the user was not logged in.

Investigation showed that the cookie was missing from the request headers. Added this back in, but it still failed to detect that the user had logged in.

```swift
func test005UserLogin() throws
    {
        var sessionCookie:String = ""
        
        func attemptLogin(with password:String, completion:(XCTHTTPResponse) throws -> ()) throws -> Void
        {
            var body = ByteBufferAllocator().buffer(capacity: 0)
            body.writeString(#"{"email":"me@example.com","password":"\#(password)"}"#)
            var headers = HTTPHeaders()
            headers.replaceOrAdd(name: .contentLength, value: body.readableBytes.description)
            headers.contentType = .json
            try app!.test(.POST, "/login", headers:headers, body:body) { response in sessionCookie = response.headers["set-cookie"].first ?? ""; try completion( response ) } <--- RETURNED
        }

        func beforeRequest(request:inout XCTHTTPRequest) -> Void
        {
            request.headers.replaceOrAdd(name: "set-cookie",value: sessionCookie)
        }
        
        try attemptLogin(with:"secret") // <--- CALL 1
        {
            response in
            XCTAssertEqual(response.status, .seeOther)
            XCTAssertEqual(response.headers["location"].first,"events") // <--- BOTH SUCCEED
        }
        
        try app!.test(.GET, "/events", beforeRequest:beforeRequest) // <--- CALL 2
        {
            response in
            XCTAssertEqual(response.status, .ok) // <--- FAILS
        }
```

### Expected behaviour

I expected CALL 2 to succeed because this route is available to the logged-in user.

### Actual behaviour

CALL 1 works as expected. The instance of the `Application` at RETURNED shows that the session has the correct value for `_UserSession` in the `session` data in the `Application` instance `app`.

In CALL 2, the log shows that the call to `user.auth.require(User.self)` throws because the user is not logged in. The assertion fails because the code returns a redirection to the log-in page.

This appears to be because there is no `session` property in the `XCTHTTPRequest` instance request that can be inspected in `beforeRequest` and although `session` exists in the running app's `Request`, there is no data.

### Environment
* Vapor Framework version: 4 latest
* Vapor Toolbox version: 3.1.10 beta 4 latest version
* OS version: macOS 10.15.5

**Comment by tanner0101** [comment]
XCTVapor does not maintain state on purpose. In order to persist the session, pull the cookie from the response and pass it into the next request. You can see an example of that here: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/SessionTests.swift#L31
