### ISSUE TITLE
URLQueryContainer doesn't decode escaped []

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/vapor#2383]
Possibly related to https://github.com/vapor/vapor/issues/1055

### Steps to reproduce

Send a request using `Foundation` to something similar to:
```
GET /users?page[offset]=0&page[limit]=50&filter[ids]=auth0|abc123
```
Foundation will percent escape the url to something like this:
```
GET /users?page%5Boffset%5D=0&page%5Blimit%5D=50&filter%5Bids%5D=auth0%7Cabc123
```

Try to decode the query:
```
try request.query.get([String: String].self, at: "filter")
```

### Expected behavior

```
{ ids: "auth0|abc123" }
```

### Actual behaviour

```
nil
```

### Environment

* Vapor Framework version: 4.8
* OS version: macOS 10.15.5

**Comment by tanner0101** [comment]
I took some time to dig into how some other web frameworks handle this, mainly PHP, Node.js, and Rails. Support for nested query parameters in each of the frameworks varies, but in all cases I could find percent encoded brackets are allowed. That makes Vapor the odd one out and I agree we should change it. 

Below are details about the tests carried out for each framework. 

### PHP

PHP was the only language / framework that included support for nested query strings in its main URI parsing method. 

```php
parse_str("page[offset]=0&page[limit]=50&filter[ids]=auth0|abc123");
parse_str("page%5Boffset%5D=0&page%5Blimit%5D=50&filter%5Bids%5D=auth0%7Cabc123");
```

Both calls to `parse_str` yield:

```
Array
(
    [page] => Array
        (
            [offset] => 0
            [limit] => 50
        )
    [filter] => Array
        (
            [ids] => auth0|abc123
        )
)
```

### Node

Node includes a library `querystring` but it does not support nested parameters.

```js
const querystring = require('querystring');
querystring.parse('page[offset]=0&page[limit]=50&filter[ids]=auth0|abc123');
querystring.parse('page%5Boffset%5D=0&page%5Blimit%5D=50&filter%5Bids%5D=auth0%7Cabc123');
```

Both calls to `parse` output:

```
[Object: null prototype] {
  'page[offset]': '0',
  'page[limit]': '50',
  'filter[ids]': 'auth0|abc123' }
```

However, there is a library [qs](https://github.com/ljharb/qs) that seems to be the defacto method for parsing nested query params. Changing the require from `querystring` to `qs` changes both parse outputs to:

```
{ page: { offset: '0', limit: '50' },
  filter: { ids: 'auth0|abc123' } }
```

### Rails

Finally, Rail's main parse method does not support nested query parameters.

```ruby
require 'rails'

CGI.parse('page[offset]=0&page[limit]=50&filter[ids]=auth0|abc123')
CGI.parse('page%5Boffset%5D=0&page%5Blimit%5D=50&filter%5Bids%5D=auth0%7Cabc123')
```

Both parse calls output:

```
{"page[offset]"=>["0"], "page[limit]"=>["50"], "filter[ids]"=>["auth0|abc123"]}
```

However, the `Rack` module includes a method for parsing nested query strings. 

```ruby
require 'rails'

Rack::Utils.parse_nested_query 'page[offset]=0&page[limit]=50&filter[ids]=auth0|abc123'
Rack::Utils.parse_nested_query 'page%5Boffset%5D=0&page%5Blimit%5D=50&filter%5Bids%5D=auth0%7Cabc123'
```

Using this method, both parse calls output:

```
{"page"=>{"offset"=>"0", "limit"=>"50"}, "filter"=>{"ids"=>"auth0|abc123"}}
```
