### ISSUE TITLE
Vapor hijacks command line argument parsing

### ISSUE THREAD

**Issue by MaxDesiatov** [vapor/vapor#2385]
I have a command-line tool that parses CLI arguments with [Apple's swift-argument-parser package](https://github.com/apple/swift-argument-parser), but it looks like Vapor hijacks argument parsing by default, so I had to pass an environment explicitly to the Application initializer. This stopped working after updating to 4.6, now CLI args parsing is always hijacked by Vapor. I think this PR broke the behavior: #2353.

### Steps to reproduce

Create a command-line tool that uses `swift-argument-parser` package. Use it to parse the arguments, then start the Vapor server by explicitly providing the environment:

```
var env = Environment.development
try LoggingSystem.bootstrap(from: &env)
let app = Application(env)
try app.run()
```

### Expected behavior

`try app.run()` does not attempt to parse command-line arguments when the environment is provided explicitly. This is the behavior of Vapor 4.5.

### Actual behavior

`try app.run()` parses command-line arguments, which previously were parsed by a different framework.

### Environment

* Vapor Framework version: 4.6 or later
* Vapor Toolbox version: 18.0.0-beta.27, seems unrelated though.
* OS version: reproducible on any OS version.

**Comment by MaxDesiatov** [comment]
@gwynne would you be able to have a look please as this behavior broke after your PR? Maybe you could give some pointers on what would be the best way to fix this?

**Comment by gwynne** [comment]
Ah, yeah, I have a good idea what's up here. I'll dig into this tonight if I can.

**Comment by tanner0101** [comment]
Using `var env = Environment.development` will initialize environment with `CommandLine.arguments`. You must use the initializer if you want something else, like a static array:

```swift
var env = Environment(name: "development", arguments: ["vapor"])
```

The reason this was working in < 4.6 was a bug that @gwynne's PR rightly fixed.

**Comment by mattt** [comment]
@MaxDesiatov Thanks for filing this issue. I was running into this myself, but was able to resolve my issue thanks to this thread. 

For future reference, I believe the PR in question is #2353. Here's the code I'm using to serve a Vapor app in my own `serve` command (using @apple/swift-argument-parser):

```swift
mutating func run() throws {
       let env = Environment(name: "development", arguments: ["vapor"]) // <-- workaround
       let app = Application(env)
       defer { app.shutdown() }
       try configure(app)
       try app.run()
}
```

FWIW, I find it surprising that Vapor does anything related to command line parsing here. I don't know enough about Vapor internals to understand why or whether this is necessary, but this may be something to reconsider going forward.

**Comment by mxcl** [comment]
This isn't the ticket for discussing this (I apologize) but I'd prefer Vapor provide a way to parse a configuration out of `CommandLine.arguments` which can then be the default behavior when constructing the Application. eg. something like:

```
let app = Application(config: .extract(from: CommandLine.arguments)))
// ^^ this would be the parameter default at the declaration site
```

I dislike the “magic” Vapor does here—it makes me feel both anxious and out of control. Also it seems to throw a wrench into having my own custom arguments.

**Comment by MaxDesiatov** [comment]
I concur, this default behavior was unexpected and confusing to me and I hope that Vapor can parse from `CommandLine.arguments` explicitly in future versions, as Max suggested above.

**Comment by tanner0101** [comment]
> FWIW, I find it surprising that Vapor does anything related to command line parsing here. 

@mattt We do command line parsing to discover which command to run (i.e., `serve`, `routes`, `migrate`, etc). And also to discover things like environment (`--env prod`) or log level (`--log trace`). 

> I dislike the “magic” Vapor does here—it makes me feel both anxious and out of control. Also it seems to throw a wrench into having my own custom arguments.

@mxcl I agree. I really dislike magic around environment detection. I originally intended for `Environment.detect()` to be the only method that pulls in `CommandLine.arguments` without asking. I'm honestly not sure how `Environment.init` ended up with that default value and I think it should be removed. I will look into this. 

 > I want to make a separate binary that contains the migrations and that I explicitly run to migrate or revert and then delete afterwards.

@mxcl This should be possible by customizing which commands your application is configured with: https://docs.vapor.codes/4.0/commands/. Fluent adds a `MigrateCommand` which you are free to remove. You could remove it from your main executable and only add it in the "migrate" executable (and even make it the default there). As for the `--auto-migrate` and `--auto-revert` flags, those could be disabled via configuration as well. If this seems helpful, lmk and I can look into getting it done.

**Comment by mattt** [comment]
> > FWIW, I find it surprising that Vapor does anything related to command line parsing here.
> 
> @mattt We do command line parsing to discover which command to run (i.e., `serve`, `routes`, `migrate`, etc). And also to discover things like environment (`--env prod`) or log level (`--log trace`).

@tanner0101 Thanks for clarifying. I guess what I found surprising was that that creating an `Application` and calling `run()` in code had anything to do with running a command. I think of APIs and CLIs to be completely orthogonal interfaces to functionality.
