### ISSUE TITLE
NIO Promise Leak During Response Body Stream

### ISSUE THREAD

**Issue by jshier** [vapor/vapor#2389]
### Steps to reproduce
Attempting to repeatedly write to a `Response` body stream results in a promise leak.

This route:
```swift
app.on(.GET, "chunked", ":count") { request -> Response in
    guard let count = request.parameters["count", as: Int.self], count > 0, count <= 100 else {
        return Response(status: .badRequest)
    }
    let response = Response(body: .init(stream: { writer in
        for i in 0..<count {
            writer.write(.buffer(.init(integer: i)))
        }
    }, count: 0))
    return response
}
```

Results in a runtime assertion about "leaking promise":

> Fatal error: leaking promise created at (file: "/SourcePackages/checkouts/vapor/Sources/Vapor/HTTP/Server/HTTPServerHandler.swift", line: 53): file /SourcePackages/checkouts/vapor/Sources/Vapor/HTTP/Server/HTTPServerHandler.swift, line 53
2020-06-10 17:49:10.639020-0400 firewalk[70185:2526213] Fatal error: leaking promise created at (file: "/SourcePackages/checkouts/vapor/Sources/Vapor/HTTP/Server/HTTPServerHandler.swift", line: 53): file /SourcePackages/checkouts/vapor/Sources/Vapor/HTTP/Server/HTTPServerHandler.swift, line 53

Which is this code:

```swift
func serialize(_ response: Response, for request: Request, context: ChannelHandlerContext) {
    switch request.version.major {
    case 2:
        context.write(self.wrapOutboundOut(response), promise: nil)
    default:
        response.headers.add(name: .connection, value: request.isKeepAlive ? "keep-alive" : "close")
        let done = context.write(self.wrapOutboundOut(response)) // Leaked
        if !request.isKeepAlive {
            done.whenComplete { _ in
                context.close(mode: .output, promise: nil)
            }
        }
    }
}
```

### Expected behavior

No leaked promises.

### Actual behavior

Runtime assertion.

### Environment

* Vapor Framework version: 4.8.0
* Vapor Toolbox version: N/A
* OS version: 10.15.5

**Comment by Joannis** [comment]
Hello @jshier, coincidentally @wessi also ran into this issue in #2390 and provides a solution. I think this is a problem that should be primarily clarified in a better error message.

**Comment by jshier** [comment]
Yes, I filed this bug on his suggestion during a [discussion of streaming bodies](https://forums.swift.org/t/streaming-multiple-payloads-through-a-response/35240/29). He later did his own experiments and hit the same issue.

**Comment by tanner0101** [comment]
This should be fixed by https://github.com/vapor/vapor/releases/tag/4.11.0, lmk if that works for you.
