### ISSUE TITLE
unhelpful crash if response stream is never terminated

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2390]
Below program which I though would just accept all body bits and never send a response crashes with an unhelpful message (promise leak in `HTTPServerHandler`).

```swift
import Vapor

var env = try Environment.detect()
try LoggingSystem.bootstrap(from: &env)

let app = Application(env)
defer { app.shutdown() }

app.on(.POST, "echo")  { request -> Response in
    return Response(body: .init(stream: { writer in
        request.body.drain { body in
            return request.eventLoop.makeSucceededFuture(())
        }
    }, count: 0))
}

try app.run()
```

I guess it's totally fair to crash if the user never completes the `writer` but a message telling the  user what they need to do would be good I think.

**Comment by Joannis** [comment]
I assume that this is the same issue as #2389, right?

**Comment by weissi** [comment]
@Joannis I would assume so, unclear if they're exactly the same.

**Comment by tanner0101** [comment]
Fixed here: https://github.com/vapor/vapor/commit/205663ceae4ca3b2bc35b981bd22cece186f9a39
