### ISSUE TITLE
body streaming doesn't stream

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2393]
Because of #2392, I've added the `r.headers.remove(name: "content-length")` to this echo server below:

```swift
import Vapor

var env = try Environment.detect()
try LoggingSystem.bootstrap(from: &env)

let app = Application(env)
defer { app.shutdown() }

app.on(.POST, "echo")  { request -> Response in
    let r = Response(body: .init(stream: { writer in
        request.body.drain { body in
            switch body {
            case .buffer(let buffer):
                return writer.write(.buffer(buffer))
            case .error(let error):
                return writer.write(.error(error))
            case .end:
                return writer.write(.end)
            }
        }
    }, count: 0))
    r.headers.remove(name: "content-length")
    return r
}

try app.run()
```

I would expect this to stream. To check that it does, I wrote this shell script:

```bash
( echo -ne 'POST /echo HTTP/1.1\r\ntransfer-encoding: chunked\r\n\r\n3\r\nFOO\r\n'; sleep 1; echo -ne '3\r\nBAR\r\n0\r\n\r\n'; sleep 1; ) | nc localhost 8080
```

which writes the request head + the first three bytes (`FOO`), then waits a second until it writes the next three bytes (`BAR`). Sure, HTTP chunks aren't semantic but 1 second should really be long enough for them to be sent back individually (and not concatenated).

They're sent back concatenated which means that Vapor must buffer them in memory!?

Expected:

```
HTTP/1.1 200 OK
connection: keep-alive
date: Wed, 10 Jun 2020 22:40:08 GMT
transfer-encoding: chunked

3\r\n
FOO\r\n
3\r\n
BAR\r\n
0
```

Actual:

```
HTTP/1.1 200 OK
connection: keep-alive
date: Wed, 10 Jun 2020 22:40:08 GMT
transfer-encoding: chunked

6
FOOBAR
0
```

I know that this is totally legal for Vapor to do but given that I waited a whole second, I would have really expected for those bytes to come back in two chunks.

For a `.pcap` run

```
sudo tcpdump -i lo0 -w /tmp/test.pcap '' 'port 8080' & sleep 1;  ( echo -ne 'POST /echo HTTP/1.1\r\ntransfer-encoding: chunked\r\n\r\n3\r\nFOO\r\n'; sleep 1; echo -ne '3\r\nBAR\r\n0\r\n\r\n'; sleep 1; ) | nc localhost 8080; sudo pkill -INT tcpdump
```

Another way of showing this would be

```
( echo -ne 'POST /echo HTTP/1.1\r\ntransfer-encoding: chunked\r\n\r\n3\r\nFOO\r\n'; sleep 100; ) | nc localhost 8080
```

where I only write the first chunk, and then wait 100 seconds. Sure, the "client" never completes the request but the `FOO` should've been replied back.

**Comment by tanner0101** [comment]
Vapor collects request bodies by default. To stream requests, use the body parameter as described here: https://docs.vapor.codes/4.0/routing/#body-streaming

```diff
- app.on(.POST, "echo")  { request -> Response in
+ app.on(.POST, "echo", body: .stream) { request -> Response in
```

However, even with body streaming enabled, Vapor doesn't currently allow for a response to be sent _before_ the current request has been entirely consumed. I've started a PR to tackle this issue here: https://github.com/vapor/vapor/pull/2404
