### ISSUE TITLE
Choose to always run a route on the same thread

### ISSUE THREAD

**Issue by lmcd** [vapor/vapor#2407]
Is it possible in Vapor 4 to guarantee that a particular route will always run on the same thread?

**Comment by 0xTim** [comment]
No, it depends on what request event loops (threads) are free to handle the request

**Comment by lmcd** [comment]
I think this could be a useful feature. In my particular situation, I have a WebSocket endpoint, of which around 10 clients will connect. There is no reason in this instance for each of these clients to potentially be coming in on different threads, requiring all sorts of synchronisation. Yet, I'd still like for all other endpoints to be served using whichever thread/event loop is available.

**Comment by tanner0101** [comment]
The only way to do this would be to supply the application's initializer with a single threaded `EventLoopGroupProvider`. It's not possible for SwiftNIO to choose a certain event loop based on routes.

That said, you could just as easily dispatch all requests coming into that endpoint to a single dispatch queue or event loop of your choice. You just need to make sure to hop back to the original request's event loop before returning.
