### ISSUE TITLE
Using response compression double-compresses an already compressed response

### ISSUE THREAD

**Issue by trasch** [vapor/vapor#2415]
My app delivers some content from a database that is already gzipped, so I set the appropriate 
response header. I also have some other content that I want to be gzipped according to the client's
wishes, so I enable the `responseCompression`  option for the server.

Now when I request one of my pre-compressed resources, it will be compressed twice...

(It would also be nice to have support for response decompression, for requests without `Content-Encoding` header...)

### Steps to reproduce

Activate response compression in the app:

`app.http.server.configuration.responseCompression = .enabled`

Set the appropriate response header in the route:

```
let headers: HTTPHeaders = [
    "Content-Encoding": "gzip",
]
return Response(
    status: .ok,
    version: req.version,
    headers: headers,
    body: .init(data: someGzippedData)))
```

Fetch the resource:

`wget -S --header="accept-encoding: gzip" http://localhost:80/theGzippedResource`

You now have to unzip the resource twice.

### Expected behavior

I would expect that the response compression checks if the resource is already compressed,
and returns it as-is if yes.

### Actual behavior

The resource will be compressed twice.

### Environment

* Vapor Framework version: 4.10.0
* OS version: Mac OS 10.15 and Linux, with Swift 5.2

**Comment by tanner0101** [comment]
@trasch response compression is handled entirely by the NIOHTTPCompression library. The Vapor API just controls whether or not the handler should be added. See https://github.com/apple/swift-nio-extras/blob/master/Sources/NIOHTTPCompression/HTTPResponseCompressor.swift

My guess is the `HTTPResponseCompressor` handler should be checking for the `content-encoding` header. And probably the other handlers, too. 

You can open an issue for that module here: https://github.com/apple/swift-nio-extras/issues
