### ISSUE TITLE
Multipart Array decoding

### ISSUE THREAD

**Issue by Magiguigui** [vapor/vapor#2423]
Trying to decode a content containing array from a `multipart/form-data` is not possible : 

```swift
struct Test: Content {
    var name: string
    var array: [String]
}
```
```
[ ERROR ] Array<String> is not convertible to multipart data
```

It is the same for every type conforming to `MultipartPartConvertible` the type is decodable, an array of this type (`String`, `Int`, `Double`, ...) isn't.

**Comment by tanner0101** [comment]
Hi @Magiguigui, can you share the raw HTTP request you are trying to decode?

**Comment by Magiguigui** [comment]
Hi @tanner0101, finally the error came from my part, the `struct` I present above is not what was really decoded (the properties were wrapped with property wrapper and my implementation of decodable couldn't handle array, etc...)
You can close as array are decodable with multipart.
