### ISSUE TITLE
spelling mistake - caseInsenstive

### ISSUE THREAD

**Issue by wangyanxi** [vapor/vapor#2426]
* Vapor Framework version: 4.14.0

`caseInsensitive` is misspelled as `caseInsenstive`

https://github.com/vapor/vapor/blob/9d57bde296912f3c66b78813e46b5535e1758aee/Sources/Vapor/Routing/Routes.swift#L8

**Comment by MrLotU** [comment]
Good catch. Though since this is a public variable we won't be able to remove/rename it until Vapor 5 (would be a breaking change). Seems we're stuck with it 😄

**Comment by MrLotU** [comment]
I will close this issue for now. Feel free to re-open when Vapor 5 starts it's development and this is still an issue in Vapor 5.

**Comment by ileitch** [comment]
Rather than just ignore this, couldn't we add the correct spelling along side, and add a comment to remove the incorrect spelling? Seems unlikely that anyone is going to remember to do this for Vapor 5.

**Comment by wangyanxi** [comment]
@ileitch I think it's a good idea, and I found Swift has this kind of syntax to generate compiler warning.

```Swift
@available(*, deprecated, renamed: "caseInsensitive", message: "spelling mistake")
public var caseInsenstive: Bool

public var caseInsensitive: Bool
```

**Comment by MrLotU** [comment]
Feel free to open a PR with the deprecation 😄

**Comment by wangyanxi** [comment]
ok, I'll try to fix it.

**Comment by mattpolzin** [comment]
Admittedly it will ultimately not be up to me anyway, but generally deprecation in this way is still only done with major version releases. Even though making that change will not cause compile time errors it will cause compile time warnings and for some projects that is as good as an error. 

Usually, `@available` deprecation allows a library to say that “with the move to this major version we are deprecating this thing so that we can entirely remove it in the next major version.” It’s actually a slower process than just making the change all at once in one major version bump.

**Comment by ileitch** [comment]
I actually wasn't suggesting to add the deprecation notice, just a comment that's easily searchable for Vapor 5, e.g `// TODO: Vapor 5 - deprecated incorrect spelling`.

**Comment by MrLotU** [comment]
Either would be fine, however I lean towards @ileitch's suggestion. Feel free to open a PR in either case :)

**Comment by grundoon** [comment]
I'll throw my 2¢ of disagreement in here. I think it should be corrected ASAP, despite technically a "breaking" change.

There's now a mismatch with release docs, formal documentation (https://github.com/vapor/docs/blob/master/4.0/docs/routing.md#case-insensitive-routing), and the associated `.caseInsensitive` property within `TrieRouter.ConfigurationOption` itself.

It's clearly a simple typo, that was then propagated by code-completion and missed in review. Unfortunate, but it's only been a couple of weeks and highly unlikely to be in use by more than a very small handful of people. This is already the second time it's been reported (first is on the original PR over a week ago) and will surely be noticed and filed many more times before 5 is even on the horizon. "Breaking" in this case is not behaviorally breaking, just means that a tiny number of people will get an easily-fixed compiler warning next time they `package update`... where "tiny" == "tiny _for now_".

**Comment by tanner0101** [comment]
@mattpolzin while that's true for Swift itself, it's not a convention that SwiftNIO has followed at least. See https://github.com/vapor/vapor/releases/tag/4.15.1 as an example.

**Comment by mattpolzin** [comment]
I probably used the word "usually" too easily. I don't actually know how many library authors would prefer avoiding the introduction of deprecation warnings in non-major semver versions vs. not 😄. It's my personal preference to avoid, but I also find this particular issue to be a sufficiently minor example of renaming something that I feel pretty pedantic even voicing the opinion to begin with.
