### ISSUE TITLE
Request.Authentication.require discardable

### ISSUE THREAD

**Issue by jnordberg** [vapor/vapor#2428]
Would be good good if `auth.require` was marked with `@discardableResult` so you can write

```swift
try req.auth.require(SomeAuthenticatable.self) 
```

instead of 

```swift
let _ = try req.auth.require(SomeAuthenticatable.self) 
```

when you're only interested in that some authenticated user is present and not the exact user

**Comment by MrLotU** [comment]
If you only require something to be authenticated, but don't require the instance, you can use `GuardMiddleware`.

[Vapor 4 Guard Middleware](https://github.com/vapor/vapor/blob/master/Sources/Vapor/Authentication/GuardMiddleware.swift#L18)
[Vapor 3 Guard Middleware (in Auth package)](https://github.com/vapor/auth/blob/master/Sources/Authentication/Utilities/GuardMiddleware.swift#L14)
