### ISSUE TITLE
Certificate issue during Vapor setup

### ISSUE THREAD

**Issue by mHassan20896** [vapor/vapor#2430]
Err:11 https://repo.vapor.codes/apt bionic Release                             
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 34.249.98.110 443]

**Comment by 0xTim** [comment]
@mHassan20896 that repo is no longer supported - see https://docs.vapor.codes/4.0/install/linux/ for installing on Linux
