### ISSUE TITLE
Stack trace improvements in 4.10 showing massive slowdown

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#2436]
Placeholder until I can get some real measurements and what's being slow, but with ~150 tests it was taking ~27 seconds. If I turned off the stack trace stuff with `StackTrace.isCaptureEnabled = false` it went down to 1s

**Comment by 0xTim** [comment]
After some investigation, it's caused by `GuardMiddleware` instantiated an `AbortError` which ends up in `StackTrace.capture`. On macOS this hits
```swift
    return Thread.callStackSymbols.dropFirst(1).map { line in
            let parts = line.split(
                separator: " ",
                maxSplits: 3,
                omittingEmptySubsequences: true
            )
            let file = String(parts[1])
            let functionParts = parts[3].split(separator: "+")
            let mangledFunction = String(functionParts[0])
                .trimmingCharacters(in: .whitespaces)
            return .init(file: file, mangledFunction: mangledFunction)
        }
```
Which is very slow...

**Comment by tanner0101** [comment]
This shouldn't affect most users since stack trace capturing is only enabled at trace log level if you use `LoggingSystem.boostrap`: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Logging/LoggingSystem%2BEnvironment.swift#L6-L8

I think we could recommend using `LoggingSystem.bootstrap` in tests, too with a pattern like:

```swift
let isLoggingConfigured: Bool = {
    var env = Environment.testing
    LoggingSystem.bootstrap(from: &env)
}()
```

```swift
import XCTest

final class FooTests: XCTestCase {
    override func setUp() {
        XCTAssert(isLoggingConfigured)
        ...
    }
}
```

**Comment by MrLotU** [comment]
Or possibly revert that statement? Disable by default, and enable at trace level?

**Comment by tanner0101** [comment]
@MrLotU yeah that's a good idea, too. I was also considering something like `--capture-stack-traces`

**Comment by MrLotU** [comment]
Both would also be an option :)
