### ISSUE TITLE
Content decode Bool type?

### ISSUE THREAD

**Issue by diuming** [vapor/vapor#2444]
vapor: 4.25.0
xcode: 11.5

issue: when using request.content.decode(... function.

example.leaf
---
```
<form action="/example" method="POST">
    <div>
        <input type="checkbox" name="isActivated">
    </div>
    <div>
        <input type="submit" value="Submit">
   </div>
</form> 
```
example.swift
---
```
app.post("example") { request -> Response in
    struct Context: Content {
        var isActivated: Bool
    }
    let context = try request.content.decode(Context.self)
    return request.redirect(to: "/")
}
```

Result
---
- checkbox unchecked:  no issue
- checkbox checked: **{"error":true,"reason":"Value of type 'Bool' required for key 'isActivated'."}**

**Comment by 0xTim** [comment]
Checkboxes in HTML forms don't have as true/false switches. As per the [W3C specs](https://www.w3.org/TR/html401/interact/forms.html#checkbox) the value of the checkbox is sent if checked, otherwise nothing is set. You'll need to change your content type to match this

**Comment by BeauNouvelle** [comment]
For anyone else stumbling in here:
You can still use a Bool value, just make it optional and hardcode the `value` in the HTML to `true`.

```
<input type="checkbox" name="myCheck" id="myCheck" value=true #if(someBoolValue == true): checked#else:#endif/>
```

When the form is sent, and the box is unchecked, you'll get a `nil` value returned, which is just as good as `false`.
