### ISSUE TITLE
Response compression can't be decoded by popular Javascript framework "got"

### ISSUE THREAD

**Issue by gkaindl** [vapor/vapor#2449]
While debugging an issue about the new debugger in Visual Studio Code not being able to load source maps from my Vapor app, I noticed that the popular Javascript library [got](https://github.com/sindresorhus/got) can't decompress responses from the Vapor app.

The vscode issue is [here](https://github.com/microsoft/vscode-js-debug/issues/650), and relevant issues at got are plentiful, like [this](https://github.com/sindresorhus/got/issues/1124), [this](https://github.com/sindresorhus/got/issues/677), or [this](https://github.com/sindresorhus/got/issues/388).

It seems to be that browsers are more lenient about compressed responses, but it's also possible that it's actually an issue with "got", even though that library seems to be quite widely used. However, since the builtin Javascript debugger in vscode will switch to using "got" in the next update to load source maps, it might be worth looking into this, since otherwise, debugging the frontend for a Vapor app could be broken in vscode.

### Steps to reproduce

- Make a trivial vapor app, serving a static file or so.
- Enable response compression in `configure()`: `app.http.server.configuration.responseCompression = .enabled`

Try to load the static page from the Vapor app, using the "got" libary. As an example, the following can be used to test it (adapt the `url` variable, of course):

```js
const got = require('got');

const url = 'http://127.0.0.1:8080/'

(async () => {
  for (const encoding of ["identity", "gzip", "deflate", "br"]) {	
    try {
      await got.get(url, {
        headers: {
          "Accept-Encoding": encoding,
          "Connection": "keep-alive"
        }
      });
      
      console.log(encoding, 'success');
    } catch (error) {
      console.log(encoding, 'error', error);
    }
  }
})();

```

### Expected behavior

"got" should succeed with all 4 `Accept-Encoding` headers.

### Actual behavior

"got" fails with the "gzip" and "deflate" encodings.

Full output from my machine:

```
xxx@yyyyyyy$ node index.js
identity success
gzip error RequestError: unexpected end of file
    at PassThrough.<anonymous> (/private/tmp/got-test/node_modules/got/dist/source/core/index.js:730:31)
    at Object.onceWrapper (events.js:422:26)
    at PassThrough.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
  name: 'ReadError',
  code: 'Z_BUF_ERROR',
  timings: {
    start: 1595520912761,
    socket: 1595520912762,
    lookup: 1595520912762,
    connect: 1595520912762,
    secureConnect: undefined,
    upload: 1595520912762,
    response: 1595520912765,
    end: 1595520912767,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 0,
      tls: undefined,
      request: 0,
      firstByte: 3,
      download: 2,
      total: 6
    }
  }
}
deflate error RequestError: unexpected end of file
    at PassThrough.<anonymous> (/private/tmp/got-test/node_modules/got/dist/source/core/index.js:730:31)
    at Object.onceWrapper (events.js:422:26)
    at PassThrough.emit (events.js:327:22)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17) {
  name: 'ReadError',
  code: 'Z_BUF_ERROR',
  timings: {
    start: 1595520912773,
    socket: 1595520912774,
    lookup: 1595520912774,
    connect: 1595520912774,
    secureConnect: undefined,
    upload: 1595520912774,
    response: 1595520912777,
    end: 1595520912777,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 0,
      tcp: 0,
      tls: undefined,
      request: 0,
      firstByte: 3,
      download: 0,
      total: 4
    }
  }
}
br success
```

### Environment

* Vapor Framework version: 4.10.0
* Vapor Toolbox version: N/A
* OS version: macOS 10.15.4

**Comment by tanner0101** [comment]
Hi @gkaindl, thanks for reporting. Vapor's HTTP compression is handled completely by SwiftNIO (specifically this file: https://github.com/apple/swift-nio-extras/blob/master/Sources/NIOHTTPCompression/HTTPResponseCompressor.swift). 

You can see here how Vapor's configuration setting results in that handler being added: https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/Server/HTTPServer.swift#L396-L405

It's _possible_ the issue is in Vapor but, based on how you described it, it seems like an affordance that NIOHTTPCompression will need to make for `got`.

**Comment by gkaindl** [comment]
Thanks @tanner0101 ! I'll open an issue at [swift-nio-extras](https://github.com/apple/swift-nio-extras) then with some additional information! I can also reproduce the issue with `curl` and `gunzip` too, so I'm quite convinced it's really swift-nio being at fault here.

**Comment by tanner0101** [comment]
@gkaindl can you elaborate on what you mean by:

> Make a trivial vapor app, serving a static file or so.

Could you share a Vapor code sample that repros this error? If it's happening in `curl` and `gunzip` too that makes me less sure it's a NIO error.

**Comment by gkaindl** [comment]
Of course! Please see the attached demo project – Make sure that the `Public` directory is properly served by the FileMiddleware, e.g. if you launch the project directly from Xcode, you might have to tell Xcode to copy `Public` into the build directory.

[demo.zip](https://github.com/vapor/vapor/files/4968711/demo.zip)

Anyway, with this running, I can reproduce the problem like this:

```
xxx@yyy$ curl -H 'Accept-encoding: gzip' --output /tmp/swift-nio-compressed-response.gz 'http://127.0.0.1:8080/index.html'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   205    0   205    0     0  51250      0 --:--:-- --:--:-- --:--:-- 51250

xxx@yyy$ file /tmp/swift-nio-compressed-response.gz
/tmp/swift-nio-compressed-response.gz: gzip compressed data, original size modulo 2^32 4294901760 gzip compressed data, reserved method, ASCII, has CRC, extra field, has comment, encrypted, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 4294901760

xxx@yyy$ gunzip -tv /tmp/swift-nio-compressed-response.gz
gunzip: /tmp/swift-nio-compressed-response.gz: unexpected end of file
gunzip: /tmp/swift-nio-compressed-response.gz: uncompress failed
/tmp/swift-nio-compressed-response.gz:	  NOT OK
```

If I do the same with google.com, I get

```
xxx@yyy$ curl -H 'Accept-encoding: gzip' --output /tmp/other-compressed-response.gz 'http://www.google.com'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5186  100  5186    0     0  50349      0 --:--:-- --:--:-- --:--:-- 50349

xxx@yyy$ file /tmp/other-compressed-response.gz 
/tmp/other-compressed-response.gz: gzip compressed data, max compression, original size modulo 2^32 11804

xxx@yyy$ gunzip -tv /tmp/other-compressed-response.gz 
/tmp/other-compressed-response.gz:	  OK
```

And I'm testing it all on macOS 10.15.4, Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)

**Comment by tanner0101** [comment]
After digging into this, I think it's in NIOHTTPCompression. I'm able to recreate the bug using the commands you sent, but I can't see anything Vapor would be doing differently to cause that. 

I'm also wondering if this could be a bug with cURL? If I use the `--compression` flag, it works. HTTPie also works.

```fish
# httpie deflate
http localhost:8080/index.html --verbose 
# httpie gzip
http localhost:8080/index.html 'accept-encoding: gzip' --verbose  
# curl deflate
curl --compressed http://localhost:8080/index.html --verbose  
# curl gzip
curl -H 'accept-encoding: gzip'  --compressed http://localhost:8080/index.html --verbose   
```

All of the above correctly output the index.html page.

**Comment by gkaindl** [comment]
Yes, it's strange, I had a look at NIOHTTPCompression too, and while I don't see anything at first glance that might hint at what's causing this, I'd also say the problem is more likely to be there than in Vapor.

I don't think it's a cURL bug, though, since apart from my own Vapor demo app, I haven't managed to find a server that exhibits the same issue for me (I've tried it with a few other apps with different stacks) – gzip always succeeds to decompress the uncompressed response sent for the "gzip" accept-encoding.

I've had a look at the `got` library too: It uses the [decompress-response](https://github.com/sindresorhus/decompress-response) package to decompress gzip and deflate responses, which uses the zlib stream API exposed by nodejs, so that's pretty much equivalent to the cURL/gzip command line tool combination.

I think it's best if I open an issue with NIO for now and reference this one, and we see what they say. I'll also try to dig deeper into it with.

**Comment by tanner0101** [comment]
Sounds good, thanks!

**Comment by gkaindl** [comment]
Okay, it has been [resolved](https://github.com/apple/swift-nio-extras/pull/100) in SwiftNIO (there was specific sequence of channel events happening that would cause a part of the compressed chunked response to be skipped/omitted).

I'll close the issue, since there's nothing to do for Vapor anymore. Thank you for your help in looking into this!
