### ISSUE TITLE
Precompiled dependencies on macOS for Swift 5.3

### ISSUE THREAD

**Issue by 3a4oT** [vapor/vapor#2450]
Starting from Swift 5.3 SPM support binary dependencies on macOS. Just wondering is it possible to release vapor with precompiled dependencies on macOS. It should be a massive improvement in build time and free computation resources.  Does it make sense?

**Comment by ileitch** [comment]
This is #1 on my wish-list. Container deploys to Heroku are painfully slow due to dependency compilation. While having binary dependencies for Vapor libs would be awesome, I think the majority of compilation time is spent in Apple's various NIO libs.

**Comment by 0xTim** [comment]
It also does not play nice at all with transitive dependencies.  However the future improvements to the build system with caching etc in llbuild2 should help a lot

**Comment by tanner0101** [comment]
It's my understanding that the binary dependency support landing in 5.3 is not meant for open source projects or improving build speed. As Tim said, improvements to caching that are being worked on will help there. I imagine caching would work similar to Homebrews bottle system if/when we get it. 

That said, most of the time spent compiling a Vapor project is spent compiling apple/* repos. Mainly `swift-crypto` and `swift-nio-ssl` which have internal copies of BoringSSL. 

```fish
# vapor/vapor.git
$ time swift build
swift build  247.83s user 49.83s system 671% cpu 44.309 total

# empty project with swift-nio, swift-crypto, swift-nio-ssl, swift-nio-extras swift-nio-http2
$ time swift build
swift build  181.13s user 38.03s system 516% cpu 42.425 total
```

If any packages are to move to being precompiled it should be those ones, not Vapor.

**Comment by 3a4oT** [comment]
thanks for the detail response!
