### ISSUE TITLE
Question: A simple way to get Content's values?

### ISSUE THREAD

**Issue by diuming** [vapor/vapor#2453]
macOS: 10.15.5
vapor: 4.27.1

Is it possible to use a simple way to get Content's values(like key-value)? 
(We don't need to create a lot of structs for accessing content's values)
refer to post route, please!

login.leaf
---
```
<form action="/login" method="post">
    Name: <input type="text" name="name" />
    Password: <input type="text" name="password" />
    <input type="submit" value="Submit"/>
</form>
```

post route
---
```
app.post("login") { request -> HTTPResponseStatus in
    //struct User: Content {
    //    var name: String
    //    var password: String
    //}
    let name = try request.content["name"]           // <-- here: a simple way
    let password = try request.content["password"]   // <-- and here
    print("\(name):\(password)")
    return HTTPStatus.ok
}
```

**Comment by Joannis** [comment]
@diuming it's not possible to find a single value from within a request's body.

Vapor uses the `Content-Type` header's value to search a valid `Decoder`, which is then used to decode the Content from the request. This change would put additional requirements on the Decoder, specifically the ability to decode a single value generically. However, this must then also support non-string values for other Encoders/Decoders that Vapor has no control over. The result, if implemented, would be closer to the following:

```swift
let name = try request.content.decodeValue(String.self, forKey: "name")
```

**Comment by tanner0101** [comment]
A subscript API is indeed available:

```swift
let foo: String? = req.content["foo"]
let bar = req.content[Int.self, at: "bar"]
```

Using a struct will be more performant though 👍
