### ISSUE TITLE
request.query.decode should not throw with Optional decodable type

### ISSUE THREAD

**Issue by patrick-zippenfenig** [vapor/vapor#2460]
Hi,

after migrating an application vom vapor 3 to 4 I realised that the behaviour of `request.query.get` changed. I am trying to get an optional URL query param and decode it to a specified type.

Unfortunately decoding to optional types and missing query paramter thows an exception.

### Steps to reproduce

```swift
// request.query does not set parameter `lang`

let lang: String? = try request.query.get(at: "lang")
// throws Value of type 'String' required for key 'lang' -> Should be nil

struct QueryParam: Codable {
    let lang: String?
}
let param = try request.query.decode(QueryParam.self)
print(param)
// QueryParam(lang: nil) -> Correct
```

### Expected behavior

`request.query.get` with optional types should return `nil` instead of throwing an error, if the query parameter is not specified in the url. This would be the same behaviour as decoding to a struct.

If the query parameter is specified, but malformed (e.g. decoding to an enum or integer), it should throw.

### Actual behavior

`request.query.get` with optional type, throws for missing parameter

### Environment

vapor 4.27.1, linux & macOS

**Comment by 0xTim** [comment]
As a workaround you could do
```swift
let lang = try? request.query.get(at: "lang")
```

**Comment by patrick-zippenfenig** [comment]
Thanks! Yes, this works and I am doing it already, but it suppresses errors in case a value can not be parsed to integer or enum
