### ISSUE TITLE
File write documentation example relies on VaporTest Utility helper

### ISSUE THREAD

**Issue by VFUC** [vapor/vapor#2466]
Hello! I tried to write to a file by following the tutorial [here](https://docs.vapor.codes/4.0/files/#write) and using the following snippet.

```swift
req.fileio.writeFile(ByteBuffer(string: "Hello, world"), at: "/path/to/file")
```

However, this code doesn't compile, since it relies on a `ByteBuffer` extension declared in `Tests/VaporTests/Utilities/ByteBuffer+Helpers.swift`.

I would suggest either of the two following:

- Move the extension from the test target to the main target, so that it can also be used from there
- Adjust the documentation example to not use the extension

I'm happy to provide a PR with a fix myself, If you let me know which of the two you'd prefer.

Cheers!

### Steps to reproduce

Use the code example from the documentation, e.g. inside the `configure`-func of `configure.swift`: 
```swift
let request = Request(application: app, on: app.eventLoopGroup.next())
let data = "Hello"
let path = "/tmp/fileio_write.txt"
	
try request.fileio.writeFile(ByteBuffer(string: data), at: path).wait()
```

### Expected behavior

The code compiles

### Actual behavior

Compiler error: `Cannot convert value of type 'String' to expected argument type 'ByteBufferView'. Extraneous argument label 'string:' in call`

### Environment

* Vapor Framework version: 4.27.2
* Vapor Toolbox version: n.a.
* OS version: macOS 10.15.5

**Comment by tanner0101** [comment]
Hi @VFUC, thanks for reporting. Those convenience methods were actually added to SwiftNIO itself here: https://github.com/apple/swift-nio/releases/tag/2.18.0. Doing `swift package update` should fix the problem. 

If not, let me know. Either way, Vapor should bump its SwiftNIO requirement if we're using those APIs in the docs.

**Comment by VFUC** [comment]
Oh, you're right - that's even better! Thanks for the quick response 👍

**Comment by VFUC** [comment]
I made a quick PR to bump the version, feel free to close it though if you're having different plans as to when and how to bump this 🙂
