### ISSUE TITLE
"ScheduledJob" can not be used

### ISSUE THREAD

**Issue by AlbusSong** [vapor/vapor#2477]
**Vapor 4, MacOS 10.15.6**

I try to make a struct of ScheduledJob. But After I create the struct, the program can not be compiled.

<img width="565" alt="Screen Shot 2020-08-21 at 8 16 32 PM" src="https://user-images.githubusercontent.com/47345588/90917273-35f09380-e3eb-11ea-8674-39b9ad5595dd.png">

The compiling error:
<img width="382" alt="Screen Shot 2020-08-21 at 8 15 04 PM" src="https://user-images.githubusercontent.com/47345588/90917158-017cd780-e3eb-11ea-817d-4d1d8b31185c.png">

Any help will be much appreciated

**Comment by 0xTim** [comment]
@AlbusSong I've just tried this and it's working for me. Could you:
* do a full clean
* delete your derived data
* delete your .swiftpm directory

Then try again?

**Comment by AlbusSong** [comment]
Sure, I will try in your way

**Comment by AlbusSong** [comment]
After I did all the above, and upgraded some essential packages, worse things happened:

<img width="653" alt="Screen Shot 2020-08-28 at 11 13 33 AM" src="https://user-images.githubusercontent.com/47345588/91538778-04168a00-e921-11ea-9016-95929dee4bd9.png">

<img width="709" alt="Screen Shot 2020-08-28 at 11 24 39 AM" src="https://user-images.githubusercontent.com/47345588/91538812-11cc0f80-e921-11ea-8016-c3b024510e1d.png">

**Comment by MrLotU** [comment]
@AlbusSong Could you share your full Package.swift (or the full project)? It's very difficult to see what exactly is going on right now.

**Comment by AlbusSong** [comment]
Sure. This is my repository:
https://github.com/AlbusSong/EastCupid-Vapor4

You shall find **JobOpenVIPOrder** in _Sources > Others > Jobs_

**Comment by AlbusSong** [comment]
Try this:
https://github.com/AlbusSong/JobTry.git

**JobOpenVIPOrder** is in _**Sources > App > Job**_  folder

**Comment by 0xTim** [comment]
@AlbusSong you haven't added queues as a dependency in your Package.swift? See the [docs](https://docs.vapor.codes/4.0/queues/#package) for details on how to do that
