### ISSUE TITLE
WebSockets behind nginx reverse proxy not working with (simple) setup: stream ended at an unexpected time

### ISSUE THREAD

**Issue by code28** [vapor/vapor#2482]
When using Vapor 4 with websockets behind a nginx reverse proxy, it is advised to set the connection header explicitly (see first code block [here](https://www.nginx.com/blog/websocket-nginx/)).
Unfortunately, the "Connection: Upgrade" header will be set with _every_ request. This means, that the [HTTPServerUpgradeHandler](https://github.com/vapor/vapor/blob/master/Sources/Vapor/HTTP/Server/HTTPServerUpgradeHandler.swift#L35) always thinks, that there will be an upgrade. For larger requests, this leads to an error.

Sure, it's bad behaviour (or you could say wrong behaviour/configuration) to always set this header, even for not-websocket-requests. But the docs of nginx (and many tutorials and StackOverflow answers) can easily be misinterpreted that way.

My suggestion is one (or both) of the following:
* The HTTPServerUpgradeHandler could also check, if the "Upgrade" header is set and only if both are set, an upgrade is initialized.
* The docs could mention in the deploy section for nginx, which settings should be done to get websockets to work. (The example at [this nginx post](https://www.nginx.com/blog/websocket-nginx/) at the bottom has the correct values, using `map`.)

I'd gladly open a PR (or two), but first wanted to discuss this topic here.

### Steps to reproduce

Use Vapor 4 behind a nginx reverse proxy (as described in the vapor 4 docs), setting the "Connection: Upgrade" header explicitly (as described at nginx).

### Expected behavior

Running requests, even a large request (> 1024 bytes) should work, as well as connection to a websocket.

### Actual behavior

Running large requests (> 1024 bytes) fails. Nginx closes the connection and vapor logs the error `stream ended at an unexpected time`.

### Environment

* Vapor Framework version: 4.29.0
* OS version: doesn't matter here, both on macOS and Ubuntu
* nginx version: 1.19.2

**Comment by Igor-Palaguta** [comment]
Have same issue `stream ended at an unexpected time` with POST request where body has similar size like 1kb

**Comment by code28** [comment]
@Igor-Palaguta did you try the fix, I mentioned (indirectly)?
Configure your nginx like this:
```
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
 
    server {
        [...]
        location / {
            [...]
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
        }
    }
}
```

**Comment by Igor-Palaguta** [comment]
Thanks a lot @code28 , did not notice your fix. Will try this

**Comment by 0xTim** [comment]
This looks like a fault in how Nginx is configured to pass the value to Vapor. @code28 I think a section in the Nginx docs is the best way forward

**Comment by code28** [comment]
@0xTim Yeah, you're right. But nevertheless, I think it could be helpful, to do something about it - at least add a hint in the docs about how to configure nginx correctly. Especially since it behaves differently to Vapor 3, I think it could be quite a good help.

**Comment by 0xTim** [comment]
@code28 if you want to do a PR that would be 👌 

Otherwise I'll get round to it when I can. Will close this issue for now
