### ISSUE TITLE
Fails to decode request body in middleware

### ISSUE THREAD

**Issue by t-ae** [vapor/vapor#2494]
I got error in this line.

https://github.com/vapor/vapor/blob/66f412bcb276c09ad3a5df263f159cee9fecc310/Sources/Vapor/Request/Request.swift#L75-L78

It seems `request.bodyStorage` is not yet `.collected`.

### Steps to reproduce

Run this project:
https://github.com/t-ae/api-template/tree/request-decode-fail

and

```
curl -X POST -F "file=@/path/to/large/file" localhost:8080
```

The cause of this problem seems:
- Send request with large body (Uploading file, for example)
- Decode request body in early timing (In `Middleware`)

We can avoid this problem by calling `request.body.collect(max: nil)` before decoding for now.
https://github.com/t-ae/api-template/blob/request-decode-fail/Sources/App/DecodingMiddleware.swift#L8-L10

**Comment by 0xTim** [comment]
Closing tis in favour of #2742
