### ISSUE TITLE
Cannot create custom Validator

### ISSUE THREAD

**Issue by sprzenus** [vapor/vapor#2505]
Hi! 

I just realized that the built-in model validating tool is not extendable. I cannot create a custom validator because the `ValidatorResult`'s initializer has internal protection level.

### Steps to reproduce

- Create an app with Vapor imported.
- Extend `Validator` for creating a custom validator.
- Create a static method returning the validator.
- Try to initialize ValidatorResult to return the result of the validation.

### Expected behavior

I should be able to create the `ValidationResult` or at least initialize one of the `ValidationResults`.

### Actual behavior

Currently, all of these initializers are internal and it's impossible to initialize any of them. This makes it impossible to create custom validators.

### Environment

* Vapor Framework version: 4.31.0
* Vapor Toolbox version: 18.2.2
* OS version: macOS 10.15.7

**Comment by 0xTim** [comment]
I think you're looking in the wrong place. Here's an example of a custom validation for checking a ZIP code:

```swift
extension Validator where T == String {
    /// Validates whether a `String` is a valid email address.
    public static var zipCode: Validator<T> {
        .init {
            guard
                let range = $0.range(of: zipCodeRegex, options: [.regularExpression]),
                range.lowerBound == $0.startIndex && range.upperBound == $0.endIndex
            else {
                return ValidatorResults.ZipCode(isValidZipCode: false)
            }
            return ValidatorResults.ZipCode(isValidZipCode: true)
        }
    }
}

private let zipCodeRegex: String = "^\\d{5}(?:[-\\s]\\d{4})?$"

extension ValidatorResults.ZipCode: ValidatorResult {
    public var isFailure: Bool {
        !self.isValidZipCode
    }
    
    public var successDescription: String? {
        "is a valid zip code"
    }
    
    public var failureDescription: String? {
        "is not a valid zip code"
    }
}

extension ValidatorResults {
    /// `ValidatorResult` of a validator that validates whether a `String` is a valid zip code.
    public struct ZipCode {
        /// The input is a valid zip code
        public let isValidZipCode: Bool
    }
}
```
This allows you to create your own validator to do what you want
