### ISSUE TITLE
Fluent `filter()` produces error

### ISSUE THREAD

**Issue by thecoolwinter** [vapor/vapor#2506]
### Fluent `filter()` produces error `Type of expression is ambiguous without more context`

I'm building a hello world project in vapor, and am trying to query for users in my database. My function looks like this, and is trying to filter for an existing user in the database to log them in.
```swift
try User.Login.validate(content: req)
let create = try req.content.decode(User.Login.self)

return User.query(on: req.db).filter(\.$email == create.email).first().unwrap(or: Abort(.unauthorized)).flatMapThrowing { (user) throws -> String in
        guard try Bcrypt.verify(create.password, created: user.password) else { throw Abort(.unauthorized) }
        let payload = try user.generateJWT()
        let token = try req.jwt.sign(payload, kid: .private)
        return token
}
```

The problem is the line with `User.query(on: req.db).filter(\.email == create.email)`. It produces the error mentioned above.

I've got Fluent, FluentSQL and my db driver all imported into the file. I have tried remaking the whole project and reinstalling vapor on my computer. The error only comes up when trying to use the `filter()` query builder function.

### Expected behavior

The line compiles, and I can use filters in my db to find data.

### Actual behavior

The line doesn't compile in either Xcode or the vapor cli.

### Environment

* Vapor Framework version: 4.32.0
* Vapor Toolbox version: 18.2.2
* OS version: macOS 10.15.6
* Swift version: 5.3 
* Xcode version: 12.0.1

**Comment by Joannis** [comment]
Swift's type system can be confused a lot. From my experience either you've got an error within the `flatMapThrowing` clause or the query. However:

> The problem is the line with User.query(on: req.db).filter(\.email == create.email). It produces the error mentioned above.

This seems to indicate you used `\.email` instead of `\.$email`, in which case the error is the missing `$`. Fluent needs a keypath pointing to the property wrapper's projected value instead, because that's the type that contains the necessary metadata.

**Comment by fouadhatem** [comment]
@thecoolwinter is this still an issue with you?

**Comment by 0xTim** [comment]
Closing as the fix is as @Joannis suggests, using the property wrapper's project value key path and not the key path directly.

The underlying issue of a useless compiler error message is a Swift bug, so raising that on bugs.swift.org would be a good step

**Comment by klaas** [comment]
The same happens if you forget to include FluentKit:

    import FluentKit
