### ISSUE TITLE
Use logger request-id from Heroku's X-Request-ID header

### ISSUE THREAD

**Issue by grennis** [vapor/vapor#2508]
### Steps to reproduce

Vapor is using a generated UUID for each request-id for the logger (see `Request` initializer). It would be nice for Vapor and Heroku to use the same ID, for tracing requests. Heroku passes the request ID in the X-Request-ID header. What is the best way for Vapor to use this request ID instead?

I tried to create middleware to do this, but the Vapor default Responder logs the request before any middleware is executed. Therefore, I had to write my own responder which just set the logger request ID from the header, and then forwards to the default responder. Ideally this wouldn't be necessary.

### Expected behavior

A way to get the request ID from a header, or a way to customize the logger request ID via callback.

### Actual behavior

Creating a forwarding responder seems the only way to do this currently.

### Environment

* Vapor Framework version: 4.31.0

**Comment by gwynne** [comment]
Implemented in #3072
