### ISSUE TITLE
WWW-Authenticate header missing in 401 response

### ISSUE THREAD

**Issue by seriyvolk83** [vapor/vapor#2524]
When any server responds with 401 it must include "WWW-Authenticate". Currently, it's not.

By providing `BasicAuthenticator` instance to the router it must add "WWW-Authenticate: Basic"

**Comment by mman** [comment]
For now this can be handled like this: https://github.com/vapor/vapor/issues/2337#issuecomment-740675655

**Comment by 0xTim** [comment]
Closing in favour of #2337
