### ISSUE TITLE
stream ended at an unexpected time for POST requests

### ISSUE THREAD

**Issue by Igor-Palaguta** [vapor/vapor#2527]
### Steps to reproduce

Server can not handle posts with big body (approx 1kb)

Send to `test_post` request with big body

```swift
        routes.post("test_post") { request -> EventLoopFuture<Response> in
            return "Ok".encodeResponse(status: .ok, for: request)
        }
```

### Expected behavior
Server should collect body and call handler

### Actual behavior

[ ERROR ] **stream ended at an unexpected time** [request-id: F6FA5684-9CA8-48C2-9C65-68B20612AEEC] (Vapor/Middleware/ErrorMiddleware.swift:42)
[ DEBUG ] Unhandled HTTP server error: dataReceivedInErrorState(stream ended at an unexpected time, ByteBuffer { readerIndex: 0, writerIndex: 6, readableBytes: 6, capacity: 16384, slice: _ByteBufferSlice { 0..<16384 }, storage: 0x00007ff038101be0 (16384 bytes) }) (Vapor/HTTP/Server/HTTPServer.swift:421)
[ DEBUG ] Unhandled HTTP server error: ioOnClosedChannel (Vapor/HTTP/Server/HTTPServer.swift:421)
[ DEBUG ] Unhandled HTTP server error: stream ended at an unexpected time (Vapor/HTTP/Server/HTTPServer.swift:421)

### Environment

* Vapor Framework version:
4.35.0
* OS version:
Ubuntu 16.04.6
* nginx
1.10.3

**Comment by Igor-Palaguta** [comment]
During testing locally on Mac it works fine, probably issue when working together with nginx
Also same POST request worked on Vapor 3

**Comment by Igor-Palaguta** [comment]
List of request headers:

```
POST /test_post HTTP/1.1
Accept: application/json, text/plain, */*
Content-Type: application/json;charset=utf-8
Origin: <URL>
Cookie: <COOKIES>
Content-Length: 507
Accept-Language: en-us
Host: <URL>
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
Referer: <URL>
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
```

**Comment by Igor-Palaguta** [comment]
In nginx conf had this:
```
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
```
I am not using WebSockets, so removed it, and now it works

**Comment by samepant** [comment]
@Igor-Palaguta I'm running into the same issue on POST with a large file, do you mind sharing the nginx conf that ended up working for you?

**Comment by tarag** [comment]
> In nginx conf had this:
> 
> ```
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
> ```
> 
> I am not using WebSockets, so removed it, and now it works

I had has the same issue and this solution worked.

**Comment by zcohan** [comment]
Thanks for posting this solution, spent hours trying to debug this issue and ended up here.
