### ISSUE TITLE
Swift cannot resolve local dependency when itself has a local dependency (only with Vapor as a dependency)

### ISSUE THREAD

**Issue by cflorion** [vapor/vapor#2529]
Hi :)

I have started working on a Vapor project and I am amazed by the clarity of the API, thanks 😊
I am using Swift 5.3 and Vapor 4.35.0.

I am struggling with a small problem that is completely blocking me. I shared a lot of code from another project via local Swift packages. When I open package.swift and add local dependencies, Swift cannot resolve some of them.

### Steps to reproduce

So I made a sample project with fake local packages:

- Pack1 (that has Pack 2 has a dependency)
- Pack2

I then tried 3 different scenari (I simplified the package.swift for this post) : 

Sample 1: I added Pack2 as a dependency: THIS WORKS

```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
        .macOS(.v10_15)
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
        .package(path: "Packages/Pack2"),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                "Pack2",
            ]
        ),
        .target(name: "Run", dependencies: [
            .target(name: "App")
        ])
    ]
)

```

Sample 2: I added Pack1 as a dependency: THIS DOES NOT WORK

```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
        .macOS(.v10_15)
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
        .package(path: "Packages/Pack1"),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                "Pack1",
            ]
        ),
        .target(name: "Run", dependencies: [
            .target(name: "App")
        ])
    ]
)

```

Sample 3: I added Pack1 as a dependency and remove Vapor remote dependency: THIS WORKS !!! 😧

```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
        .macOS(.v10_15)
    ],
    dependencies: [
        .package(path: "Packages/Pack1"),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                "Pack1",
            ]
        ),
        .target(name: "Run", dependencies: [
            .target(name: "App")
        ])
    ]
)

```

So it seems that Vapor intefere with local Swift packages that has a local dependecy itself. I cannot find a reason why this could be logical.
Does anyone has a clue ? 🤔

**Comment by siemensikkema** [comment]
@cflorion I don't see how the Vapor could affect package resolution this way. Have you tried substituting Vapor for another remote package?

**Comment by cflorion** [comment]
@siemensikkema Thanks for your response! Good idea I will try that

**Comment by cflorion** [comment]
@siemensikkema You are right, this is not related to Vapor, strange I'll keep digging ☹️ Thank you !

**Comment by cflorion** [comment]
@siemensikkema 
For information, I found a way to make it working for me:
In the dependencies, you need to put the remote ones always at the end of the list. And, important, in the target list you need to put them at the end as well.
lise so:

```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "hello",
    platforms: [
        .macOS(.v10_15)
    ],
    dependencies: [
        .package(path: "Packages/Pack1"),
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                "Pack1",
                .product(name: "Vapor", package: "vapor"),
            ]
        ),
        .target(name: "Run", dependencies: [
            .target(name: "App")
        ])
    ]
)
```

Weird huh 😁
