### ISSUE TITLE
Bypassing JWTAuthenticator and accessing secure endpoint

### ISSUE THREAD

**Issue by tikhop** [vapor/vapor#2530]
Trying to implement a secure endpoint using JWTAuthenticator and it works well. However, sending a request without `Authorization` header at all leads to a successful response whereas sending an invalid or expired token works as expected.

### Steps to reproduce

```
struct UserAuthenticator: JWTAuthenticator
{
    typealias Payload = App.Payload
    
    func authenticate(jwt: Payload, for request: Request) -> EventLoopFuture<Void>
	{
        request.auth.login(jwt)
        return request.eventLoop.makeSucceededFuture(())
    }
}
```

```
let wsRoute = app.grouped("ws")
wsRoute.group(UserAuthenticator()) { auth in
	auth.webSocket("channel") { req, ws in
		// I can reach this point if I send a request without `Authorization` header, but if I pass an expired or invalid jwt token then request fails and never reach this point. 
	}
}
```

### Expected behavior

Request must fail at validation point.

### Actual behavior

Request successfully goes thru JWTAuthenticator and returns 200.

### Environment

* Vapor Framework version: 4.32

**Comment by tikhop** [comment]
Tried to debug what's going on under the hood and sounds like I just need my own implementation of `RequestAuthenticator.authenticate(Request)`. Otherwise the following function will be called:

```
extension BasicAuthenticator {
    public func authenticate(request: Request) -> EventLoopFuture<Void> {
        guard let basicAuthorization = request.headers.basicAuthorization else {
            return request.eventLoop.makeSucceededFuture(())
        }
        return self.authenticate(basic: basicAuthorization, for: request)
    }
}
```

Unfortunately, default implementation doesn't handle the case when a client makes a request without provide `Authorization` header.

**Comment by 0xTim** [comment]
Are you proving the guard middleware as [shown in the docs](https://docs.vapor.codes/4.0/authentication/#jwt) for protecting routes with JWT?

**Comment by mkll** [comment]
@tikhop ?

**Comment by 0xTim** [comment]
Closing as I'm assuming this is due to a missing `GuardMiddleware` - feel free to reopen if it's not the case!
