### ISSUE TITLE
Vapor clang dependencies for clang-10 missing 

### ISSUE THREAD

**Issue by quantum-fusion** [vapor/vapor#2546]
### Describe the bug

I am trying to build the project in this article (https://heartbeat.fritz.ai/deploying-core-ml-models-using-vapor-c562a70b1371)
https://github.com/rickwierenga/heartbeat-tutorials/tree/master/CoreML-API

vapor build is missing clang-10 dependencies 

### To Reproduce

vapor build
Building project...
Fetching https://github.com/vapor/console.git
Fetching https://github.com/vapor/sql.git
Fetching https://github.com/vapor/sqlite.git
Fetching https://github.com/vapor/fluent.git
Fetching https://github.com/apple/swift-nio-ssl-support.git
Fetching https://github.com/apple/swift-nio-zlib-support.git
Fetching https://github.com/vapor/vapor.git
Fetching https://github.com/apple/swift-nio-ssl.git
Fetching https://github.com/vapor/multipart.git
Fetching https://github.com/vapor/http.git
Fetching https://github.com/vapor/service.git
Fetching https://github.com/vapor/template-kit.git
Fetching https://github.com/vapor/url-encoded-form.git
Fetching https://github.com/vapor/websocket.git
Fetching https://github.com/vapor/database-kit.git
Fetching https://github.com/vapor/fluent-sqlite.git
Fetching https://github.com/vapor/validation.git
Fetching https://github.com/vapor/core.git
Fetching https://github.com/vapor/crypto.git
Fetching https://github.com/vapor/routing.git
Fetching https://github.com/apple/swift-nio.git
Cloning https://github.com/vapor/database-kit.git
Resolving https://github.com/vapor/database-kit.git at 1.3.3
Cloning https://github.com/vapor/sql.git
Resolving https://github.com/vapor/sql.git at 2.3.2
Cloning https://github.com/vapor/http.git
Resolving https://github.com/vapor/http.git at 3.4.0
Cloning https://github.com/vapor/vapor.git
Resolving https://github.com/vapor/vapor.git at 3.3.3
Cloning https://github.com/vapor/fluent.git
Resolving https://github.com/vapor/fluent.git at 3.2.1
Cloning https://github.com/vapor/crypto.git
Resolving https://github.com/vapor/crypto.git at 3.4.1
Cloning https://github.com/apple/swift-nio.git
Resolving https://github.com/apple/swift-nio.git at 1.14.2
Cloning https://github.com/apple/swift-nio-ssl-support.git
Resolving https://github.com/apple/swift-nio-ssl-support.git at 1.0.0
Cloning https://github.com/vapor/core.git
Resolving https://github.com/vapor/core.git at 3.10.0
Cloning https://github.com/vapor/service.git
Resolving https://github.com/vapor/service.git at 1.0.2
Cloning https://github.com/vapor/sqlite.git
Resolving https://github.com/vapor/sqlite.git at 3.3.0
Cloning https://github.com/vapor/validation.git
Resolving https://github.com/vapor/validation.git at 2.1.1
Cloning https://github.com/vapor/routing.git
Resolving https://github.com/vapor/routing.git at 3.1.0
Cloning https://github.com/vapor/fluent-sqlite.git
Resolving https://github.com/vapor/fluent-sqlite.git at 3.0.0
Cloning https://github.com/vapor/console.git
Resolving https://github.com/vapor/console.git at 3.1.1
Cloning https://github.com/vapor/multipart.git
Resolving https://github.com/vapor/multipart.git at 3.1.3
Cloning https://github.com/vapor/websocket.git
Resolving https://github.com/vapor/websocket.git at 1.1.2
Cloning https://github.com/apple/swift-nio-ssl.git
Resolving https://github.com/apple/swift-nio-ssl.git at 1.4.0
Cloning https://github.com/vapor/template-kit.git
Resolving https://github.com/vapor/template-kit.git at 1.5.0
Cloning https://github.com/apple/swift-nio-zlib-support.git
Resolving https://github.com/apple/swift-nio-zlib-support.git at 1.0.0
Cloning https://github.com/vapor/url-encoded-form.git
Resolving https://github.com/vapor/url-encoded-form.git at 1.1.0
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
unknown argument: '-index-store-path'

unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
unknown argument: '-index-store-path'
unknown argument: '-index-store-path'
unknown argument: '-index-store-path'
unknown argument: '-index-store-path'

### Environment

* Vapor Framework version: unknown 
* Vapor Toolbox version: unknown 
* OS version: MacOS Big Sur 11.2 Beta

**Comment by quantum-fusion** [comment]
swift --version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.3.0

**Comment by 0xTim** [comment]
What's the output from `swift build --verbose`? This is likely a compiler error rather than anything to do with Vapor

**Comment by quantum-fusion** [comment]
@0xTim See the output from swift build --verbose

[output.log](https://github.com/vapor/vapor/files/5771861/output.log)

**Comment by quantum-fusion** [comment]
@0xTim see the last 20 lines of errors with the vapor module  in question. Urlparser

/Users/hottelet/miniconda3/bin/x86_64-apple-darwin13.4.0-clang -fobjc-arc -target x86_64-apple-macosx10.15 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -g -O0 -DSWIFT_PACKAGE=1 -DDEBUG=1 -fblocks -index-store-path /Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store -fmodules -fmodule-name=CURLParser -I /Users/hottelet/hello/.build/checkouts/vapor/Sources/CURLParser/include -fmodules-cache-path=/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/ModuleCache -MD -MT dependencies -MF /Users/hottelet/hello/.build/x86_64-apple-macosx/debug/CURLParser.build/urlparser.c.d -c /Users/hottelet/hello/.build/checkouts/vapor/Sources/CURLParser/urlparser.c -o /Users/hottelet/hello/.build/x86_64-apple-macosx/debug/CURLParser.build/urlparser.c.o
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/hello/.build/x86_64-apple-macosx/debug/index/store'

**Comment by 0xTim** [comment]
Most of the errors seems to be coming from the macOS SDK (the fact you're on a beta macOS is suspicious). Have you tried deleting your `.build` directory and trying again? Like I said there's not much Vapor can do about this since it's an error coming from clang and not a Vapor error

**Comment by quantum-fusion** [comment]
@0xTim You were right I deleted the .build directory, but had to delete the garbage files in ~/Library/Developer/Xcode/DerivedData , followed by "swift package update". This issue was related to https://github.com/vapor/vapor/issues/1562

I learned that vapor build was producing the errors for clang-10 , which means that vapor build is no longer supported.

**Comment by quantum-fusion** [comment]
@0xTim This issue was related to https://developer.apple.com/forums/thread/128535

**Comment by 0xTim** [comment]
`vapor build` just calls down to `swift build`

This can be closed now right?

**Comment by quantum-fusion** [comment]
@0xTim If we think the problem is with Xcode and swift, i currently see this output.  If you think this isn't related to vapor then I can move this over to the Xcode forum , and will have to find help from Apple.  Yes, you should probably close this.  

swift build
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: unknown argument: '-index-store-path'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
clang-10: error: no such file or directory: '/Users/hottelet/Desktop/heartbeat-tutorials-master/CoreML-API/CoreML-API/.build/x86_64-apple-macosx/debug/index/store'
[0/20] Compiling CNIOHTTPParser c_nio_http_parser.c

**Comment by 0xTim** [comment]
Yes this has nothing to do with Vapor. This is working now right? It's a problem with stale build artefacts

**Comment by quantum-fusion** [comment]
@0xTim I deleted the GitHub clone repo for vapor, and then ran swift build --verbose > output.log  You can see from the resulting output, that this has nothing to do with stale dependencies.  

Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Target: x86_64-apple-darwin20.4.0

[output.log](https://github.com/vapor/vapor/files/5960422/output.log)

**Comment by 0xTim** [comment]
@quantum-fusion I'm pretty sure this is a Swift error and not a Vapor error. If you try and build a plain Swift package what does that do?
It looks like you have a mismatch between clang and Swift (like a different toolchain installed but it's trying to use an old clang version)

**Comment by quantum-fusion** [comment]
@0xTim I investigated the swift version installed, and clang version installed.  I found a collision and the clang version was 10, and this was the wrong version for MacOS Big sur.  I needed to be clang-1205.0.19.6 , for Big Sur MacOS version 11.3 Beta.

I had to delete the following: 
sudo rm -rf /home/miniconda3/* -> which had clang version 10
sudo rm -rf /Library/Developer/CommandLineTools

I had to follow the instructions here, in order to upgrade the version of Xcode and command line tools: 
https://stackoverflow.com/questions/63972113/big-sur-clang-invalid-version-error-due-to-macosx-deployment-target

To fix, the new command line tools can be gotten from Apple here (https://developer.apple.com/download/more/?=xcode).
At the time of this writing, the tool versions needed are: 
Xcode 12.5 beta , dated Feb 1, 2021
Additional tools 12.5 beta, dated Feb 1, 2021
CommandLine tools for Xcode 12.5 beta

-------
clang —version
Apple clang version 12.0.5 (clang-1205.0.19.34)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

swift --version
Apple Swift version 5.4 (swiftlang-1205.0.16.12 clang-1205.0.19.6)
Target: x86_64-apple-darwin20.4.0
---

Once those tools are installed, you have to link the commandLine tools with Xcode, like shown here:
https://stackoverflow.com/questions/61501298/xcrun-error-unable-to-find-utility-xctest-not-a-developer-tool-or-in-path
---

cd vapor
rm -rf .build 
swift build --verbose
--

Good Results: 

1.) Compiles clean now, with the correct dependencies.

2.) I did inspect some of the apple dependencies for SSL, and saw there is a new version for:
    .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.10.2"),
 
I think you can now close this, with the newest version of Xcode and command line tools, for Big Sur 11.3 Beta OS.

---
more Package.swift
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "vapor",
    platforms: [
       .macOS(.v10_15)
    ],
    products: [
        .library(name: "Vapor", targets: ["Vapor"]),
        .library(name: "XCTVapor", targets: ["XCTVapor"]),
        .library(name: "_Vapor3", targets: ["_Vapor3"]),
    ],
    dependencies: [
        // HTTP client library built on SwiftNIO
        .package(url: "https://github.com/swift-server/async-http-client.git", from: "1.2.0"),
    
        // Sugary extensions for the SwiftNIO library
        .package(url: "https://github.com/vapor/async-kit.git", from: "1.0.0"),

        // 💻 APIs for creating interactive CLI tools.
        .package(url: "https://github.com/vapor/console-kit.git", from: "4.0.0"),

        // 🔑 Hashing (BCrypt, SHA2, HMAC), encryption (AES), public-key (RSA), and random data generation.
        .package(url: "https://github.com/apple/swift-crypto.git", from: "1.0.0"),

        // 🚍 High-performance trie-node router.
        .package(url: "https://github.com/vapor/routing-kit.git", from: "4.0.0"),

        // 💥 Backtraces for Swift on Linux
        .package(url: "https://github.com/swift-server/swift-backtrace.git", from: "1.1.1"),
        
        // Event-driven network application framework for high performance protocol servers & clients, non-blocking.
        .package(url: "https://github.com/apple/swift-nio.git", from: "2.18.0"),
        
        // Bindings to OpenSSL-compatible libraries for TLS support in SwiftNIO
        .package(url: "https://github.com/apple/swift-nio-ssl.git", from: "2.10.2"),
        
        // HTTP/2 support for SwiftNIO
        .package(url: "https://github.com/apple/swift-nio-http2.git", from: "1.13.0"),
        
        // Useful code around SwiftNIO.
        .package(url: "https://github.com/apple/swift-nio-extras.git", from: "1.0.0"),
        
        // Swift logging API
        .package(url: "https://github.com/apple/swift-log.git", from: "1.0.0"),

        // Swift metrics API
        .package(url: "https://github.com/apple/swift-metrics.git", from: "2.0.0"),

        // WebSocket client library built on SwiftNIO
        .package(url: "https://github.com/vapor/websocket-kit.git", from: "2.0.0"),
        
        // MultipartKit, Multipart encoding and decoding
        .package(url: "https://github.com/vapor/multipart-kit.git", from: "4.0.0"),
    ],
    targets: [
        // C helpers
        .target(name: "CBase32"),
        .target(name: "CBcrypt"),
        .target(name: "COperatingSystem"),
        .target(name: "CURLParser"),

        // Vapor
        .target(name: "Vapor", dependencies: [
            .product(name: "AsyncHTTPClient", package: "async-http-client"),
            .product(name: "AsyncKit", package: "async-kit"),
            .product(name: "Backtrace", package: "swift-backtrace"),
            .target(name: "CBase32"),
            .target(name: "CBcrypt"),
            .target(name: "COperatingSystem"),
            .target(name: "CURLParser"),
            .product(name: "ConsoleKit", package: "console-kit"),
            .product(name: "Logging", package: "swift-log"),
            .product(name: "Metrics", package: "swift-metrics"),
            .product(name: "NIO", package: "swift-nio"),
            .product(name: "NIOExtras", package: "swift-nio-extras"),
            .product(name: "NIOFoundationCompat", package: "swift-nio"),
            .product(name: "NIOHTTPCompression", package: "swift-nio-extras"),
            .product(name: "NIOHTTP1", package: "swift-nio"),
            .product(name: "NIOHTTP2", package: "swift-nio-http2"),
            .product(name: "NIOSSL", package: "swift-nio-ssl"),
            .product(name: "NIOWebSocket", package: "swift-nio"),
            .product(name: "Crypto", package: "swift-crypto"),
            .product(name: "RoutingKit", package: "routing-kit"),
            .product(name: "WebSocketKit", package: "websocket-kit"),
            .product(name: "MultipartKit", package: "multipart-kit"),
        ]),
        // Vapor 3 API shim
        .target(name: "_Vapor3", dependencies: [
            .target(name: "Vapor"),
            .product(name: "_NIO1APIShims", package: "swift-nio")
        ]),

        // Development
        .target(name: "Development", dependencies: [
            .target(name: "Vapor"),
            .target(name: "_Vapor3"),
        ], swiftSettings: [
            // Enable better optimizations when building in Release configuration. Despite the use of
            // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
            // builds. See <https://github.com/swift-server/guides#building-for-production> for details.
            .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
        ]),

        // Testing
        .target(name: "XCTVapor", dependencies: [
            .target(name: "Vapor"),
        ]),
        .testTarget(name: "VaporTests", dependencies: [
            .product(name: "NIOTestUtils", package: "swift-nio"),
            .target(name: "XCTVapor"),
        ]),
    ]
)
