### ISSUE TITLE
Provide Configuration to enable GZIP easily

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#2547]
As a framework, Vapor should provide a seamless way to enable/use GZIP compression when returning responses. NIO has the necessary channel handlers to provide compression so we should hook these up as part of the responder behind a configuration flag.

**Comment by jshier** [comment]
I would appreciate Brotli and Deflate support, or at least some mechanism to hook into such compression myself. This is mainly for my testing server, but Brotli is becoming more popular.

**Comment by 0xTim** [comment]
I think providing a configuration option so end-users can provide their own compression channel handlers should be doable

**Comment by 0xTim** [comment]
This is done as described by https://docs.vapor.codes/4.0/server/#response-compression

**Comment by jshier** [comment]
@0xTim Thanks for pointing that out. However, my requirements go beyond simply enabling some sort of compression to being able to control exactly which compression is applied on a per response basis. Is that configureable?
