### ISSUE TITLE
Crash in Vapor or NIO

### ISSUE THREAD

**Issue by coaoac** [vapor/vapor#2549]
### Describe the bug

Hello! I am lately having my Vapor app crash rather frequently but not always.
I cannot pinpoint when exactly this happens but it seems to be when I make too many requests at the same time. 
Attached the backtrace 
[Backtrace.txt](https://github.com/vapor/vapor/files/5782639/Backtrace.txt)

### To Reproduce

I am not able to consistently reproduce the crash. it seems to occur when I am making many requests at the same time but I can't be sure.

### Environment
I am attaching my Package.resolved

[Package.resolved.txt](https://github.com/vapor/vapor/files/5782644/Package.resolved.txt)

**Comment by fouadhatem** [comment]
@coaoac please specify environment details: OS version, Vapor version, Xcode version and whether this was a DEBUG or RELEASE build.

**Comment by coaoac** [comment]
Sure!
OS: Heroku 20 dyno (Linux)
Vapor version: 4.37.0
Release build.

**Comment by 0xTim** [comment]
Can you also attach the relevant code, such as route handlers and app setup

**Comment by coaoac** [comment]
The crash did not happen consistently so it was hard to identify which portion of my code triggered it. It just seemed to happen when I am doing many requests at the same time. But that could be jus my because it increased the probability of it happening. 
now I am not able to make the app crash anymore after the last Vapor update.  
I can close this for now and come back it it happens again.
