### ISSUE TITLE
How to run Vapor on macOS App ?

### ISSUE THREAD

**Issue by CloseServer** [vapor/vapor#2555]
I want to run vapor on MacOS app, but it always fails. Is there any other good solution?

![image](https://user-images.githubusercontent.com/12987627/104835338-e30b0180-58e0-11eb-91b7-cf65df2698d9.png)

**Comment by 0xTim** [comment]
This looks like an Xcode/network or proxy issue. Can you clone the repo from the command line?

**Comment by CloseServer** [comment]
Thanks !
