### ISSUE TITLE
stream ended at an unexpected time when Safari is uploading

### ISSUE THREAD

**Issue by omrd** [vapor/vapor#2567]
Vapor produces `stream ended at an unexpected time ` whenever a client using Safari is uploading a large file (or multiple files) through an `XMLHttpRequest`. 
* The issue appears to be specific to Safari on Big Sur.  I have attached a project to demonstrate. 
* Testing with Catalina or previous macOS versions seems to be ok.
* Testing with Chrome and Edge works fine on any OS.
* Setting `app.routes.defaultMaxBodySize` makes no difference

### To Reproduce
- Build project.
- Make sure to set the working directory to the root of the project. 
- Run server
- Use Safari to test on localhost:8080
- Chrome and Edge work fine. 

### Steps to reproduce the behavior:
1. Try to upload one or two files larger than 100MB. My clients have files as large as 2GB. 
2. Zip files sometimes show as uploaded but unzipping them produces errors.

### Expected behavior
- Expect results to complete normally similar to Chrome and Edge

### Environment
* Vapor Framework version: 4.40
* OS version: macOS Big Sur 11.3

### Additional context
- Using M1 Mac, but it seems like issue persists regardless of platform. 

[vaportest.zip](https://github.com/vapor/vapor/files/6007870/vaportest.zip)

**Comment by 0xTim** [comment]
This has been fixed by using FileIO as shown [here](https://github.com/vapor/vapor/blob/main/Sources/Development/routes.swift#L181)
