### ISSUE TITLE
running Vapor tests in parallel fails

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2568]
If you run

```
docker run -it --rm  -w "$PWD" -v "$PWD:$PWD" swift:5.3 swift test --enable-test-discovery --parallel --num-workers 1
```

in a vapor checkout, your tests won't succeed. You'll see many failures such as

```
Test Suite 'Selected tests' started at 2021-02-19 09:52:59.423
Test Suite 'ApplicationTests' started at 2021-02-19 09:52:59.424
Test Case 'ApplicationTests.testBoilerplate' started at 2021-02-19 09:52:59.424
<EXPR>:0: error: ApplicationTests.testBoilerplate : threw error "Error: Unknown command `VaporTests.ApplicationTests/testBoilerplate`"
Test Case 'ApplicationTests.testBoilerplate' failed (0.006 seconds)
Test Suite 'ApplicationTests' failed at 2021-02-19 09:52:59.431
	 Executed 1 test, with 1 failure (1 unexpected) in 0.006 (0.006) seconds
Test Suite 'Selected tests' failed at 2021-02-19 09:52:59.431
	 Executed 1 test, with 1 failure (1 unexpected) in 0.006 (0.006) seconds
```

**Comment by weissi** [comment]
@0xTim thank you! but this will also affect all user code, right? Is it necessary that Vapor parses the command line in these scenarios in  unit test? Ie in `.testing`?

**Comment by 0xTim** [comment]
Ah right, see what you mean now. Yes there's definitely something going on when you create an `Application` and execute it from the command line. I'm not sure if this is a bug in ConsoleKit, Vapor or 'you're holding it wrong'. I suspect the fix would be to optionally disable command line input for tests, or in the test environments

**Comment by weissi** [comment]
> Ah right, see what you mean now. Yes there's definitely something going on when you create an `Application` and execute it from the command line. I'm not sure if this is a bug in ConsoleKit, Vapor or 'you're holding it wrong'. I suspect the fix would be to optionally disable command line input for tests, or in the test environments

Sounds like the right call to me!
