### ISSUE TITLE
`vapor new hello -n` fails due to missing master branch

### ISSUE THREAD

**Issue by hollyschilling** [vapor/vapor#2581]
### Describe the bug
Attempting to validate a new installation of Vapor, I attempted to create and build the Hello World project from the tutorial. 
```
vapor new hello -n
```
The output is:

> Cloning template...
> Error: Cloning into '/Users/hollyschilling/Projects/Vapor/hello/.vapor-template'...
> fatal: Remote branch master not found in upstream origin

### To Reproduce
1. Verify Swift version using `swift --version`. 
2. Install Vapor using Homebrew. `brew install vapor`
3. Attempt to create a new project using `vapor new hello -n`.

### Expected behavior

New project template will be cloned.

### Environment

System: M1 MacBook Pro running macOS 11.2.3
Swift: Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
Vapor Toolkit: 18.3.1

**Comment by schmitcn** [comment]
The main branch seems to be `main` now. Don't know if Github forced it automatically or the maintainers did it and forgot to update the command.

**Comment by grundoon** [comment]
Yes, most if not all (should be all) Vapor repositories have been updated to use `main` rather than `master`. The toolbox `New.swift` script was updated earlier today in version 18.3.2

@hollyschilling Updating your toolbox via `brew` from 18.3.1 to version 18.3.2 should fix this. Apologies for the timing inconvenience!

**Comment by 0xTim** [comment]
Just a heads up, we're waiting for the PR to be merged in homebrew at the moment. The workaround is passing `--branch=main` to the toolbox

**Comment by 0xTim** [comment]
Update it's now been merged so running `brew update` should fix this

**Comment by katzenbaer** [comment]
I'm having an issue where it still tries to access master when I'm on vapor 18.4.1. Is there some cache I need to clear?

```swift
terrence.katzenbaer$ brew upgrade vapor
Warning: Treating vapor as a formula. For the cask, use homebrew/cask/vapor
Warning: vapor 18.4.1 already installed
terrence.katzenbaer$ vapor new HelloVapor
Cloning template...
Error: Cloning into '/Users/tkatzenbaer/Developer/vapor/.vapor-template'...
fatal: Remote branch master not found in upstream origin
terrence.katzenbaer$ 
```
