### ISSUE TITLE
Review Vapor's log level usage

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#2586]
Most alerting systems relying on analysing the logs produced by the application. Many 5XX errors are signs that something is wrong and anything logged at `error` or `critical` can be cause for paging people (and waking them up!). We should go through the framework and ensure that we aren't logging anything at `error` or `critical` unless absolutely necessary (for instance, failing to bind to a port or start).

We might want to provide some configuration so that when in `development` mode we log errors at `error` to easily catch bugs at development time, but certainly when running in `production` most server errors should be `warning` or below

**Comment by vzsg** [comment]
> We might want to provide some configuration so that when in development mode we log errors at error to easily catch bugs at development time, but certainly when running in production most server errors should be warning or below

TBH, this sounds more like that all those "errors" should be warnings, and in development, the log level should be warning (or something more verbose).

**Comment by Joannis** [comment]
I agree with not varying the log levels.
