### ISSUE TITLE
Stop creating ByteBufferAllocators

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#2588]
We should stop creating our own ByteBufferAllocators and use the one from the `Channel`

**Comment by Joannis** [comment]
I don't disagree, but ByteBufferAllocator is currently a singular implementation that's pretty straightforward. So I don't see how it harms _right now_.

**Comment by 0xTim** [comment]
It's the performance hit. It's more performant (and recommended) to reuse the one from the channel. This is especially relevant for Vapor since `req.content` (and I think Fluent) all create a `ByteBufferAllocator` from fresh

**Comment by Joannis** [comment]
I'm curious what the performance hit actually is. Since it only refers to 4 or 5 global functions defined in C.

**Comment by 0xTim** [comment]
cc @weissi

**Comment by Joannis** [comment]
Also a note: I think following down a class chain may even be more expensive than creating a new allocator.

**Comment by weissi** [comment]
I'd recommend using the `ByteBufferAllocator` from the `Channel`. We haven't really made use of the potential, for example pooling some ByteBuffers per Channel or statistics (bytes allocated per channel or so) but we could in the future. Therefore I'd recommend using the allocator from the `Channel` itself whenever possible.
