### ISSUE TITLE
cache

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#259]
# Cache

* Author(s): [Tanner](https://github.com/tannernelson)
* Status: **[Awaiting review](#rationale)**

## Introduction

A unified API for using various caching systems to ephemerally store data. 

## Motivation

Some operations to fetch data can be slow and do not need to be performed with every request. Caching allows these values to be fetched more quickly at the cost of being real time.

## Proposed solution

Implement an `app.cache` property that uses Fluent or another cache driver to persist the cache.

Requirements:
- Fluent, persist the cache (instead of Redis or Memcached)
- Console, create the tables for the cache

## Code snippets

```swift
let string: String = app.cache.get("key")
let string = app.cache.get("key") // Cacheable
app.cache.store("value", at: "key", for: 5)
app.cache.forget("key")
```
## Impact

This only adds functionality.

## Alternatives considered

No alternatives were considered, feel free to recommend them.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by frankieleef** [comment]
@tannernelson Is there already any progress on this? Otherwise I would like to start working on this.

**Comment by tannernelson** [comment]
Nope, this one is still in the pipeline. That would be awesome if you could work on it :)

HMU in Slack at some point and we can finalize the public API before you get started. What is here is a little outdated.
