### ISSUE TITLE
EventLoopFuture嵌套的问题

### ISSUE THREAD

**Issue by zhuayi** [vapor/vapor#2591]
**Is your feature request related to a problem? Please describe.**

我有一个功能, 需要获取APIA,APIB,APIC 三个接口的数据, 按顺序获取 APIA 得到结果去获取 APIB,得到结果再去获取 APIC. 这样功能可以实现, 但是代码不够简洁

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

```
let res = EventLoopFuture<EventLoopFuture<response>>

res.flatMap{res in

             res.flatMap{ res in

                 res.map { res in

                    return res.configurations

                }

            }
}
```

**Comment by 0xTim** [comment]
Unfortunately there's not a lot we can do at this point since API B requires the result of API A, so the only option you have is to nest your futures.

This will be eventually solved by async/await, but for now there's nothing we can do 😞
