### ISSUE TITLE
fluent database configuration didn‘t work

### ISSUE THREAD

**Issue by cit117** [vapor/vapor#2594]
### Describe the bug
<img width="767" alt="image" src="https://user-images.githubusercontent.com/54506518/112726699-c7178200-8f59-11eb-999d-b465e6e8e496.png">

I set up the database configuration in the .env file. And set up the working directory. 
<img width="382" alt="image" src="https://user-images.githubusercontent.com/54506518/112726939-dfd46780-8f5a-11eb-999c-edab78ccda6e.png">

![4CD11BD611CBEBF9C0DA83B9A2854C57](https://user-images.githubusercontent.com/54506518/112726787-342b1780-8f5a-11eb-864b-512867dede6e.jpg)

but the error is reported when running.Did I make a mistake somewhere?

* Vapor Framework version: 4.41.3
* Fluent version: 4.2.0
* FluentPostgresDriver version: 2.1.2
* OS version: 11

**Comment by cit117** [comment]
if I don't set up the  working directory,it will work normally.

**Comment by 0xTim** [comment]
Do you have a .env file? And how did you set up the database?

**Comment by cit117** [comment]
oh,sorry.This is my mistake. vapor cli created a .env.development file.I didn't look at it
