### ISSUE TITLE
Protocol '**' can only be used as a generic constraint because it has Self or associated type requirements

### ISSUE THREAD

**Issue by zhuayi** [vapor/vapor#2604]
I need to put ABC and BCD into the dictionary, but it doesn't seem to work

```
protocol abcdefg: Content {}


struct abc : abcdefg {}

struct bcd : abcdefg {}


let dict: [String: abcdefg.Type] = [
    "abc" : abc.self,
    "bcd" : bcd.self
]

dict.map{(key: String, value: abcdefg.Type) in
          
    ..........dosomething..........
    
}
```
When such a choice is made, the following error will be reported:

**Protocol 'abcdefg' can only be used as a generic constraint because it has Self or associated type requirements**

**Comment by siemensikkema** [comment]
@zhuayi you are running into a Swift limitation and not a Vapor specific one as this would happen without extending `Content` as well. It is not clear to me exactly what you need but maybe you can try asking in the #swift channel in the Vapor discord 🙂
