### ISSUE TITLE
Nested content dose not call beforeEncode or afterDecode

### ISSUE THREAD

**Issue by jvanbrunt** [vapor/vapor#2605]
### Describe the bug

When nesting content, nested structs/classes do not call beforeEncode and afterDecode now allowing sub rules for coding and decoding.

### To Reproduce

1. Create struct that conforms to Content protocol with a child struct also conforming to content protocol.
2. Decode struct with default decoder. 
3. Notice afterDecode is not called on child objects.

```swift
struct Parent: Content {
    let child: Child
}

struct Child: Content {
...
}
```
### Expected behavior

As struct is decoded all children of struct that conforms to Content protocol should use the same decoder.

### Environment

* Vapor Framework version: 4.44.1
* Vapor Toolbox version: 18.3.3
* OS version: MacOS 11.2.3

**Comment by 0xTim** [comment]
I don't think it's possible for Vapor to know what the types of the different properties are and therefore know that it has a `Child` to call into. You should be able to work around this though by calling `child.beforeEncode()` inside your `Parent`'s `beforeEncode()`
