### ISSUE TITLE
Missing PlaintextDecoder means users need to fall back to req.body to parse plain text http apis

### ISSUE THREAD

**Issue by DaveTCode** [vapor/vapor#2607]
**Is your feature request related to a problem? Please describe.**
As per https://discordapp.com/channels/431917998102675485/435928766812913664/833695763296813107 http apis which return content with Content-Type plain/text hit an Abort.httpDecoder error: Unsupported Media Type when decoding.

e.g.

```
return req.client.get(address).flatMapThrowing { res in
    try res.content.decode(UInt8.self)
}.map { n in
    /// do stuff
}
```

**Describe the solution you'd like**
I believe it would be in keeping with the rest of the API surface of vapor if this "just worked" (possibly with a requirement to specify the encoder)

I _think_ that means that I'd want a `PlaintextDecoder` (there's already a `PlaintextEncoder`) selected based on Content-Type plain/text

**Describe alternatives you've considered**
In my application I'm instead using `res.body!.getString(at: 0, length: res.body!.readableBytes)!` which feels strictly inferior (albeit hardly a lot of extra typing)

**Additional context**
None

**Comment by 0xTim** [comment]
I think a `PlaintextDecoder` that consumes the body of the response as a `String` in `res.content.decode` makes sense and should be a good first issue PR for someone unless one of the core team pick it up
