### ISSUE TITLE
Can not generate Xcode project

### ISSUE THREAD

**Issue by sinduke** [vapor/vapor#2622]
Please look at this

There is a warning here:
dependency 'fluent' is not used by any target

But There is an issue
vapor/Sources/App/configure.swift:2:8: No such module 'Fluent'

![image](https://user-images.githubusercontent.com/22930750/117639905-03740a00-b1b7-11eb-9eb2-796ff214815e.png)

**Comment by 0xTim** [comment]
Can you show the contents of your Package.swift please?

**Comment by 0xTim** [comment]
Closing as solved in Discord - Fluent needs to be added as a dependency to the target as well
