### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by anchao-lu** [vapor/vapor#2623]
load .env wrong: Could not load .env file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/Utilities/DotEnv.swift:120)

**Comment by 0xTim** [comment]
Going to need more information than this to help debug it. What version are you using? Do you have a .env file? What file is it looking for? Have you set a custom working directory? etc

**Comment by iWECon** [comment]
<details>
main            | [ DEBUG ] Could not load .env.production file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/Utilities/DotEnv.swift:120)

main            | [ DEBUG ] Could not load .env file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/Utilities/DotEnv.swift:120)

main            | App/Database.swift:32: Fatal error: Should set database info to env: DB_HOST_NAME, DB_PORT, DB_USERNAME, DB_PASSWORD, DB_DATABSE

main            | Received signal 4. Backtrace:

main            | 0x561f58b53df2, Backtrace.(printBacktrace in _B82A8C0ED7C904841114FDF244F9E58E)(signal: Swift.Int32) -> () at /build/.build/checkouts/swift-backtrace/Sources/Backtrace/Backtrace.swift:66

main            | 0x7efcb97c73bf

main            | 0x7efcb9a930ab

main            | 0x561f589a2c52, function signature specialization <Arg[1] = Dead> of static App.Database.liveuConfigure(app: Vapor.Application) -> PostgresKit.PostgresConfiguration at /build/Sources/App/Database/Database.swift:0

main            | 0x561f589a2dfb, static App.Database.liveuConfigure(app: Vapor.Application) -> PostgresKit.PostgresConfiguration at /build/<compiler-generated>:0

main            | 0x561f589a2dfb, App.configure(Vapor.Application) throws -> () at /build/Sources/App/configure.swift:17

main            | 0x561f591fedf6, Run_main at /build/Sources/Run/main.swift:8

main            | 0x7efcb8b330b2

main            | 0x561f589939ad

main            | 0xffffffffffffffff
</details>


<img width="440" alt="CleanShot 2022-02-12 at 15 44 10@2x" src="https://user-images.githubusercontent.com/16604027/153702256-312c0630-19db-4cff-b041-e389d46a2dc4.png">


@0xTim
