### ISSUE TITLE
Choose a key coding strategy for query parameters

### ISSUE THREAD

**Issue by RemiBardon** [vapor/vapor#2627]
### Is your feature request related to a problem? Please describe.

I have an endpoint, which takes a `"display_name"` query param. To decode the query parameters, I have to use [`URLQueryContainer`'s `public func decode<C>(_ content: C.Type) throws -> C where C: Content`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/Content/URLQueryContainer.swift#L33-L50), which takes a type. I created the following `struct` to decode the query params:

```swift
public struct QueryFilters: Content {
	public var displayName: String
}
```

My problem is: the query param isn't decoded because it's sent in snake_case and in camelCase in code.

I know I can set the [`URLQueryDecoder`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/Content/URLQueryCoders.swift#L1-L4) using [`ContentConfiguration.global.use(urlDecoder:)`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/Content/ContentConfiguration.swift#L93-L95) in `configure.swift`, but I don't want to rewrite a whole decoder just for key mapping.

### Describe the solution you'd like

The [default `URLQueryDecoder`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/Content/ContentConfiguration.swift#L38) ([`URLEncodedFormDecoder`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift)) allows one to choose a [`Configuration`](https://github.com/vapor/vapor/blob/main/Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift#L14-L47). This configuration `struct` supports `dateDecodingStrategy`, but not `keyDecodingStrategy`.

I propose we add a `KeyDecodingStrategy` `enum` similar to Foundation's `JSONDecoder.KeyDecodingStrategy`. At the same time, we can add its encoding counterpart.

We would be able to do:

```swift
let urlDecoder = URLEncodedFormDecoder(configuration: .init(keyDecodingStrategy = .convertFromSnakeCase))
ContentConfiguration.global.use(decoder: urlDecoder, for: .urlEncodedForm)
ContentConfiguration.global.use(urlDecoder: urlDecoder)
```

### Describe alternatives you've considered

I've tried:

- <details>
    <summary>Adding a <code>[String: String]</code> initializer to my <code>QueryFilters</code> <code>struct</code>.</summary>
    
    ```swift
    public init(fromDict dict: [String: String]) {
    	self.displayName = dict["display_name"]
    }
    ```
  </details>
  
  and use:
  
  ```swift
  let queryParams = try req.query.decode([String: String].self)
  let filters = User.QueryFilters(fromDict: queryParams)
  ```
  
  It works… but it means I am stuck with `String` values. In addition, I don't like hard coding coding keys. I'd prefer a non-intrusive coding strategy.
- <details>
    <summary>Wrapping a <a href="https://github.com/vapor/vapor/blob/91bbc66320f91c62e1888985e154d48526b944e9/Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift">URLEncodedFormDecoder</a> inside another Decoder to use its working functions.</summary>
  
    ```swift
    import Vapor
    
    public struct URLEncodedMappedFormDecoder: ContentDecoder, URLQueryDecoder {
    	
    	let jsonEncoder: JSONEncoder
    	let jsonDecoder: JSONDecoder
    	
    	public init(jsonEncoder: JSONEncoder, jsonDecoder: JSONDecoder) {
    		self.jsonEncoder = jsonEncoder
    		self.jsonDecoder = jsonDecoder
    	}
    	
    	/// `ContentDecoder` conformance.
    	public func decode<D>(_ decodable: D.Type, from body: ByteBuffer, headers: HTTPHeaders) throws -> D
    		where D: Decodable
    	{
    		let dict = try URLEncodedFormDecoder().decode([String: String].self, from: body, headers: headers)
    		return try self.jsonDecoder.decode(decodable, from: self.jsonEncoder.encode(dict))
    	}
    	
    	/// `URLQueryDecoder` conformance.
    	public func decode<D>(_ decodable: D.Type, from url: URI) throws -> D where D: Decodable {
    		let dict = try URLEncodedFormDecoder().decode([String: String].self, from: url.query ?? "")
    		return try self.jsonDecoder.decode(decodable, from: self.jsonEncoder.encode(dict))
    	}
    	
    }
    ```
    
    And use
    
    ```swift
    let urlDecoder = URLEncodedMappedFormDecoder(jsonEncoder: encoder, jsonDecoder: decoder)
    ContentConfiguration.global.use(decoder: urlDecoder, for: .urlEncodedForm)
    ContentConfiguration.global.use(urlDecoder: urlDecoder)
    ```
    
    in `configure.swift`.
  
  </details>
  
  It works too, and isn't intrusive… but it's far from perfect (still requires `String` values, needs a JSON encoder doing the opposite of the JSON decoder…).

I'd prefer not to:

- Create a local `struct` in the route, with snake_case members and a mapping function to convert it to my `QueryFilters` `struct`.
- Rewrite an entire Decoder (duplication of code, mistakes…) + Parser just for this, as [the Parser used by Vapor](https://github.com/vapor/vapor/blob/91bbc66320f91c62e1888985e154d48526b944e9/Sources/Vapor/URLEncodedForm/URLEncodedFormDecoder.swift#L64) ([`URLEncodedFormParser`](https://github.com/vapor/vapor/blob/91bbc66320f91c62e1888985e154d48526b944e9/Sources/Vapor/URLEncodedForm/URLEncodedFormParser.swift)) is `internal`.

### Additional context

I can create a PR if you want, after you accept/reject my proposition.

**Comment by 0xTim** [comment]
@RemiBardon so traditionally `keyDecodingStrategy` has been discouraged because it's _really_ slow - at least it was in the past I've no idea how it currently stacks up.

I'm not opposed to this per se, though it would require a fair bit of work because we'd also need to do the same for `Content` as well and that adds a lot of API surface that I think can be achieved other ways. There are a couple of options I didn't see you mention:

1. why not just use `CodingKeys` since that's basically the go to way to work around this in Swift. All you'd need it
```swift
enum CodingKeys: String, CodingKey {
  case displayName = "display_name"
}
```
In `QueryFilters` and it should just work.

2. You can specify a `URLQueryDecoder` for a one-off use by doing `req.query.decode(QueryFilters.self, using: myCustomQueryDecoder)`. That should allow you to achieve what you need for that one use case (though again requires a whole `URLQueryDecoder` to be written.

**Comment by RemiBardon** [comment]
Thank you for your response Tim.

> `keyDecodingStrategy` has been discouraged because it's really slow - at least it was in the past I've no idea how it currently stacks up.

Yeah, you're right. I don't know either but it probably is still slow.

> that adds a lot of API surface that I think can be achieved other ways

You mean your two following propositions or something else?

> why not just use `CodingKeys`

Erm… I can't remember why I chose not to… there possibly are no reason 🤭 I think it was to keep some flexibility over the casing of the API, but it makes no sense and it's not something that's likely to change anyway 🤔

> You can specify a `URLQueryDecoder` for a one-off use

Yeah, I know, but I'd still need to write my own `URLQueryDecoder`, and that was my last point.

I think using `CodingKeys` solves the problem, so I let you close the issue if you want. Thank you again and sorry for not thinking about this really basic solution 🙄

**Comment by 0xTim** [comment]
No worries, glad it solves your problem and happy to be a rubber duck! 😅
