### ISSUE TITLE
Improve the “Connection refused” error message

### ISSUE THREAD

**Issue by jaanus** [vapor/vapor#2629]
### Describe the bug

When a Dockerized Vapor app gets a “connection refused” error from PostgreSQL, the log provided in Docker Dashboard is not helpful and does not have all the details.

### To Reproduce

Build a simple Vapor app (based on the template app) with this `Dockerfile` and `docker-compose.yml`.

[dockerfiles.zip](https://github.com/vapor/vapor/files/6539280/dockerfiles.zip)

Observe that there is an error in `docker-compose.yml`. `DATABASE_PORT` is specified as 6432, which is the externally visible port. Yet the Dockerized app should use the internal port 5432. With this setup, the app tries to connect to an inaccessible port when running in Docker context.

When you compose this setup, the database containers run fine. The app exits shortly after starting with error code 132.

Docker Dashboard shows this log.

<img width="1362" alt="Screenshot 2021-05-25 at 15 14 45" src="https://user-images.githubusercontent.com/184253/119499495-72cd2a80-bd6f-11eb-911f-04374438688f.png">

When inspecting the log with Terminal, there is a bit more info and a mention of `Connection refused (errno: 111)`.

<img width="1410" alt="Screenshot 2021-05-25 at 15 13 25" src="https://user-images.githubusercontent.com/184253/119499714-a60fb980-bd6f-11eb-8de5-d30fa8964e2f.png">

### Expected behavior

1) Docker Dashboard should have an indication of the connection error.

2) The connection error itself could be more helpful and specific.

### Environment

* Vapor Framework version: 4.45.3
* Vapor Toolbox version: 18.3.3
* OS version: macOS Big Sur 11.3.1 (20E241)

**Comment by shilpeegupta14** [comment]
Wont this error will go away by changing the DATABASE_PORT from 6432 to 5432 ?

**Comment by 0xTim** [comment]
This isn't restricted to Docker, basically any connection issue should provide the port and hostname as well

**Comment by thx1766** [comment]
Is this still an issue?

I am doing my best to replicate (vapor toolbox 18.6.3, swift 5.6.1).

I have created a default vapor app with fluent/postgres. I have modified the docker-compose.yml file to use `DATABASE_PORT: 6432` and db containers ports to `"6432:5432"`.

When I run `docker compose up`, the app starts up fine and does not crash. However, when I try the POST endpoint to create a Todo, I do see an error bubbling up in the docker desktop logs. It does seem to indicate the port number and address/ hostname.

`[ NOTICE ] Server starting on http://0.0.0.0:8080 (Vapor/HTTP/Server/HTTPServer.swift:270)

[ INFO ] GET /todos [request-id: AB6796DC-CB12-47DB-A349-4CD44301925C] (Vapor/Middleware/RouteLoggingMiddleware.swift:13)

[ DEBUG ] query read todos [database-id: psql, request-id: AB6796DC-CB12-47DB-A349-4CD44301925C] (FluentKit/Query/Builder/QueryBuilder.swift:291)

[ DEBUG ] SELECT "todos"."id" AS "todos_id", "todos"."title" AS "todos_title" FROM "todos" [] [database-id: psql, request-id: AB6796DC-CB12-47DB-A349-4CD44301925C] (FluentPostgresDriver/FluentPostgresDatabase.swift:29)

[ DEBUG ] No available connections on this event loop, creating a new one [database-id: psql, request-id: AB6796DC-CB12-47DB-A349-4CD44301925C] (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:202)

[ WARNING ] PSQLError(base: PostgresNIO.PSQLError.Base.connectionError(underlying: NIOPosix.NIOConnectionError(host: "db", port: 6432, dnsAError: nil, dnsAAAAError: nil, connectionErrors: [NIOPosix.SingleConnectionFailure(target: [IPv4]db/172.21.0.2:6432, error: connection reset (error set): Connection refused (errno: 111))]))) [request-id: AB6796DC-CB12-47DB-A349-4CD44301925C] (Vapor/Middleware/ErrorMiddleware.swift:42)`

When I check the logs from the terminal, I see similarly informative information regarding port numbers and the internal docker network address/ hostname.

**Comment by jaanus** [comment]
I re-tested: this is no longer an issue. There are two key differences from my original report:

* The template app starts fine without a database connection. The routes not requiring database work fine.
* If I do not have a database running, or it is inaccessible, and I try to access a route that tries to talk to database, I see clear error message in Docker Dashboard console (same `PSQLError` as in the last comment).

🎉
