### ISSUE TITLE
scheduled tasks

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#263]
# Tasks
- Author(s): [Tanner](https://github.com/tannernelson)
- Status: **[Awaiting review](#rationale)**
## Introduction

This feature would add an array of tasks that can be scheduled to run at certain time intervals.
## Motivation

Web applications frequently have tasks such as cleaning a database, transferring data, or sending emails that need to be run at certain intervals. 
## Proposed solution

A new type called `Task` will be added that can be instantiated and added to an array of scheduled tasks on the application. 

Required:
- Console
- Fluent
## Code snippets

``` swift
protocol Task {
    var interval: Int { get}
    func run()
}
```

``` swift
class EmptyUsers: Task {
    var interval: Int = 5
    func run() {
        DB.statement("TRUNCATE users")
    }
}
```

```
app.tasks += EmptyUsers()
```
## Impact

This adds functionality.
## Alternatives considered

No alternatives have been considered. Feel free to add some.
## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by Evertt** [comment]
I propose either calling the protocol `ScheduledTask` or `RepeatingTask` **or** doing it the Laravel way. The Laravel is to have `Job` objects which only have knowledge of *what* they do, but don't care about *when*. And then elsewhere in the app you can choose to add a `Job` to the `Queue` and / or to schedule a `Job`.

I actually think that would be my favorite way. That way it's really easy to keep the code modular and DRY.  I don't have a preference between calling it a `Task` or a `Job`.

## Code snippet

```swift
protocol Task {
    func run()
}

class EmptyUsers: Task {
    func run() {
        DB.statement("TRUNCATE users")
    }
}

app.schedule(EmptyUsers()).daily(at: "13:00")
```

Now it's also easy to make a general `Action` class based on this `Task` protocol:

```swift
class Action: Task {
    let task: Void -> Void

    init(task: Void -> Void) {
        self.task = task
    }

    func run() {
        task()
    }
}

let emptyUsersAction = Action {
    DB.statement("TRUNCATE users")
}

app.schedule(emptyUsersAction).daily(at: "13:00")
```

**Comment by tannernelson** [comment]
I like the idea of making a `Job` both queueable and scheduleable. 👍

**Comment by tannernelson** [comment]
@czechboy0 Could we use something like your https://github.com/czechboy0/Pong/blob/master/Sources/PeriodicRunner.swift for this?

**Comment by czechboy0** [comment]
@tanner Yup.

**Comment by Mordil** [comment]
What's the status on this? Is this ready to be picked up and worked on?

**Comment by matthijs2704** [comment]
@Mordil maybe this already what you're looking for? https://github.com/BrettRToomey/Jobs

**Comment by Casperhr** [comment]
Indeed Bretts package seems to have most things right now.
Only downside is when you redeploy all is lost

So for schedules tasks far out in the future. Use cronjobs. For async jobs 
https://github.com/BrettRToomey/Jobs

Thats how we run it in Nodes at least

**Comment by LoganWright** [comment]
For now, we'll defer to Jobs. @BrettRToomey if you'd like to integrate that into vapor org, let us know

**Comment by valeriomazzeo** [comment]
you guys may want to have a look at https://github.com/reswifq/reswifq

**Comment by daltonclaybrook** [comment]
@valeriomazzeo GPL license, though... 😕

**Comment by niazoff** [comment]
In @Evertt's proposal above, there's a snippet, `app.schedule(emptyUsersAction).daily(at: "13:00")`. Is something like this possible in the current version?

**Comment by mcdappdev** [comment]
@niazoff there’s currently work being done on a queue system at https://github.com/vapor-community/jobs. There’s only last bug I’m sorting out and then I think the first version will be ready for testing :) it doesn’t do scheduling yet but it’s at least a step in the right direction.
