### ISSUE TITLE
queue 

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#264]
# Queue

* Author(s): [Tanner](https://github.com/tannernelson)
* Status: **[Awaiting review](#rationale)**

## Introduction

Queues allow you to defer the processing of a time consuming task, such as sending an e-mail, until a later time which drastically speeds up web requests to your application.

## Motivation

Web applications that can defer long processing can be faster and more efficient. 

## Proposed solution

Introduce a `Queue` class and `app.queue` function.

Requires
- Console
- Fluent

## Code snippets

```swift
let sendEmail = Queue("send email") {
    // send email here
}

app.queue(sendEmail)
```

## Impact

This adds functionality.

## Alternatives considered

No alternatives were considered, please feel free to submit your ideas.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by ketzusaka** [comment]
I feel like running tasks shouldn't require the app server to start up. I recommend a different kind of `Application`.

**Comment by tannernelson** [comment]
Hmm. What do you mean by that? The tasks here aren't required for the server to start. When you call `app.queue` it enqueues the `Queue` task in persistent memory then runs the task at a later time.

**Comment by ketzusaka** [comment]
Err, yeah. Sorry. I wanted more details about how an queue runner works specifically.

**Comment by tannernelson** [comment]
I just wanted to get the rough outline here. This feature will require the Console _and_ Fluent to be working so it's a ways off.

**Comment by ketzusaka** [comment]
ah gotcha, thanks. Some things that might be interesting to read re this in the future: Resque and Sidekiq. Also, I don't know if Fluent should be required for deferred tasks. I feel like those should be optional additions, and the queue system should have Drivers like some of the other systems. For example, I found it convenient to be able to setup a Postgres session store without requiring Fluent

**Comment by tannernelson** [comment]
The queue system is going to need to be able to do something like:

```swift
let enqueued = Query<Queue>().all()
for e in enqueued {
   if e.shouldRun() {
      e.run()
      e.markComplete()
   }
}
```

Creating this type of an interface between a database engine such as redis, memcached, sql, or mongo is exactly what Fluent is supposed to do. I think to separate the protocol for this alone would end up being really complicated.

**Comment by ketzusaka** [comment]
I feel like my concerns stem from being an early adopter, where Fluent hasn't been very prevalent. I'll keep in mind it becoming a more core part of Vapor in the future. Will Fluent soon be a dependency of Vapor?

**Comment by tannernelson** [comment]
Yes I think it will become a dependency. Many of the higher level features need a persistent data store.

**Comment by Evertt** [comment]
> ```
let sendEmail = Queue("send email") {
    // send email here
}

> app.queue(sendEmail)
```

Why does the Queue need a string label here? And furthermore, I think the `Queue` object isn't actually a `Queue` object. It's an `Action`, which you are putting on a queue.

```swift
let sendEmail = Action {
    // send email here
}

app.queue(sendEmail)
```

Or you could call it `Job` like Laravel does it:

```swift
let sendEmail = Job {
    // send email here
}

app.queue(sendEmail)
```

When you call it `Action` or `Job` then it also makes more sense if you would type it in this way:

```swift
app.queue(Job {
    // send email here
})
```

**Comment by tannernelson** [comment]
An API for easily creating background threads should solve this since Vapor has a runtime unlike PHP.

**Comment by valeriomazzeo** [comment]
you guys may want to have a look at https://github.com/reswifq/reswifq
