### ISSUE TITLE
Possibility to set static TimeZone or ignore TimeZone

### ISSUE THREAD

**Issue by denis-ev** [vapor/vapor#2640]
**Is your feature request related to a problem? Please describe.**
I'm try to set up a website with Events, for which the TimeZone of the Date does not matter.
Right now, viewing from different timezones always shows different times.
I've set the Website to always set UTC with the right date and then save it.

**Describe the solution you'd like**
Setting the date via #date(date, "YYYY-mm-dd HH:mm", static) or #date(date, "YYYY-mm-dd HH:mm", TimeZone: 0) or similar

**Describe alternatives you've considered**
I've tried to edit the Date on the Server before showing it on the website, but could not get it to work.
I have an Event Model which gets passed as the model or even a model array.

**Additional context**
Any ideas to work around that problem?

Thank you

**Comment by mkll** [comment]
@denis-ev Just don't tell Leaf to format the date string, format it yourself with DateFormatter, then pass it to Leaf.

**Comment by denis-ev** [comment]
> @denis-ev Just don't tell Leaf to format the date string, format it yourself with DateFormatter, then pass it to Leaf.

Hey @mkll,
Then I have to modify a model which would be a bit more of a hassle.

@0xTim gave the tip about creating a custom DateFormatter.

So I'm trying to set a custom leaf tag. 
I'm checking out the [Example](https://docs.vapor.codes/4.0/leaf/custom-tags/#tag-renderer), but I'm not sure how to pass the date to it.

**Comment by denis-ev** [comment]
thanks to @0xTim 
got it working by looking at the default DateFormatter [link](https://github.com/vapor/leaf-kit/blob/main/Sources/LeafKit/LeafSyntax/LeafTag.swift#L55)
