### ISSUE TITLE
Vapor does not initiate the main queue

### ISSUE THREAD

**Issue by Lukasa** [vapor/vapor#2648]
### Describe the bug

In Dispatch, the main queue is not started automatically. Instead, it’s the responsibility of the application being launched to ensure that the main queue is started. When working with Dispatch-aware UI frameworks this tends to be done automatically, but for CLI tools and servers like Vapor the binary itself needs to start the main queue using `dispatchMain`.

Vapor does not currently do this. As a result, any block enqueued to the main queue (via `Dispatch.main.async`) will never execute. This can subtly (or less-subtly!) break a wide range of cross-platform libraries that assume that the main queue will always be being served.

### To Reproduce

1. Create a new Vapor app using `vapor new`
2. In a route handler, add a call to the main queue, e.g.

        DispatchQueue.main.async { print(“Hello”) }

3. Observe that this call does not execute.

### Expected behavior

Calls to the main queue should execute.

### Environment

* Vapor Framework version: 4.47.1
* OS version: macOS 11.4

### Additional context

`dispatchMain` will essentially terminate the thread that calls it, and must be called from the main thread. This means the current model of execution for Vapor is difficult to reconcile with what is done today. In particular, right now Vapor assumes that the function `run` is capable of returning. That’s a bit awkward, as that is the logical place to park the main thread.

It seems likely that Vapor may need two separate run functions, one of which can start a server from any thread and assumes the user will be responsible for initiating the main queue, and one that enqueues a background block and then parks the main queue.

**Comment by BeauNouvelle** [comment]
I'm running into this same problem trying to integrate a Vapor sever into my iOS application.
Running the server freezes the app. Nothing can be run on the main thread.


My current solution has been to just wrap the initialization in a background thread. But it would be nice to have a cleaner way of doing this via server configuration or similar.

**Comment by jhoughjr** [comment]
This issue also seems to affect KVO of NSWorkspace on macOS.

**Comment by vzsg** [comment]
@Lukasa could you please elaborate a bit on how a Vapor application should _shut down_ if the main thread is parked into the RunLoop? Even today, it's possible to kick off a Vapor server on a background thread while the main thread starts the RunLoop, but it opens a whole new can of worms, since no graceful signals work anymore.

I have a strange feeling that this would also affect [swift-server-lifecycle](https://github.com/swift-server/swift-service-lifecycle) too, that follows the same idea as Vapor does.
