### ISSUE TITLE
PlainTextDecoder crashes application

### ISSUE THREAD

**Issue by MFranceschi6** [vapor/vapor#2649]
### Describe the bug

Plain Text Decoder crashes applications based on external input:
Any application which uses vapor can crash basically using any normal http request.

### To Reproduce
Start any vapor project with this route:

```
struct DTO {
   let example: String
}
app.post("") { request in
  request.content.decode(DTO.self)
  return "OK"
}
```

Send a request using header `Content-Type: text/plain`
and body:
```
{
  "example": "example"
}
```

Application Crashes

### Expected behavior

The application doesn't crash

### Environment

* Vapor Framework version: 4.47.2

### Additional context

https://github.com/vapor/vapor/blob/f94f0bff47c1c07df6e404e889f5c71c4270a9ea/Sources/Vapor/Content/PlaintextDecoder.swift#L29-L35

**Comment by 0xTim** [comment]
Thanks for reporting! This is resolved in [4.48.1](https://github.com/vapor/vapor/releases/tag/4.48.1)
