### ISSUE TITLE
Bug in validation for email

### ISSUE THREAD

**Issue by gulivero1773** [vapor/vapor#2651]
If I use space between characters in email I have This error - "reason": "value is not a valid email address". I use standard validation for check email
<img width="868" alt="Снимок экрана 2021-07-13 в 12 03 52" src="https://user-images.githubusercontent.com/61082418/125424071-317dea7d-91ee-443a-8656-e68670e28461.png">
![Снимок экрана 2021-07-13 в 12 04 09](https://user-images.githubusercontent.com/61082418/125424125-92959f66-f31d-40bd-81a1-2ca84c7671b0.png)
"
Maybe needs in func for validation remove space between characters?

**Comment by 0xTim** [comment]
@gulivero1773 what's the bug? Emails with a space in aren't valid emails

**Comment by 0xTim** [comment]
Your client should be sanitising the data before sending it to you as well
