### ISSUE TITLE
How to generate log files by day?

### ISSUE THREAD

**Issue by zhuayi** [vapor/vapor#2653]
It is suggested to add the method of generating log files by day.  thanks

**Comment by 0xTim** [comment]
What do you mean by generating. log files by day? If you mean Vapor should save the logs to a file and split them up by day then that is the concern of the Logger. Vapor uses [swift-log](https://github.com/apple/swift-log) so you can choose any backend you want that implements Swift Log including one that saves it to a file etc. You can even write your own.

Vapor only provides a Console Logger for outputting logs to the console and we have no plans to offer anything else as the community has a wide range of Swift Log backends.
