### ISSUE TITLE
Consistent segmentation fault in SwiftNIO, NIO-ELT-0-#10 (7): EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by jaredh159** [vapor/vapor#2663]
Vapor is fairly consistently seg-faulting when handling requests, with an error like:

```
NIO-ELT-0-#10 (7): EXC_BAD_ACCESS (code=1, address=0x0)
```

I'm developing a web app that talks to my Vapor API. When working on a screen that makes about 7 concurrent requests to the API, I noticed that if I reload over and over again, I can almost always get it to segfault.

I don't have a minimal reproduction repo for you.  I guess I'm looking for some general help on how to diagnose and troubleshoot the segfault.  I was not expecting to get any segfaults.  I don't think I'm doing anything super unusual, I'm not doing any low-level stuff, just sticking pretty much to the happy path, although I'm building a GraphQL server with Graphiti and graphql-kit, not a standard REST based app with many routes.

The segfault is coming from the bowels of SwiftNIO. LLDB is calling out line `231` from this file:

 https://github.com/apple/swift-nio/blob/main/Sources/NIOCore/EventLoopFuture.swift#L228-L237

I can't find any of my own code in the stack trace at all.  I do see a bunch of Postgres related calls in the stack track though.

I apologize, I'm fairly new to swift, and I'm not even sure how to dump out or copy the stack trace in a way that would be helpful.  So I'll post an image of the stack trace in the comments.

Any thoughts?  Am I doing something wrong with Postgres? Is there some other code I could add that would help someone to help me?  Do I need to think more carefully about the connection pool or something like that? Is there some way to get more information about why this is happening?  Truly appreciate any help!  :pray: 

### Environment

* Database: Postgres
* framework: 4.48.0
* toolbox: 18.3.3
* OS version: 11.4

**Comment by jaredh159** [comment]
Here's the screenshot:

![Screen Shot 2021-07-30 at 5 05 05 PM](https://user-images.githubusercontent.com/7050938/127711463-9ba02b4a-d017-4f2f-98a5-3dd196cf02c4.png)

**Comment by 0xTim** [comment]
@jaredh159 What does the route handler that causes the crash look like?

**Comment by jaredh159** [comment]
Because it's a graphql app, there's really only _one_ route handler, added in `configure.swift` with a line like this:

```swift
app.register(graphQLSchema: AppSchema, withResolver: Resolver())
```

The functionality is provided by `graphql-kit`, under the hood adds a `/graphql` route which handles all queries and mutations.  Not sure if that's any help. Thanks for replying!

**Comment by 0xTim** [comment]
What does your resolver look like then? I'm pretty sure this is an issue with GraphQLKit or the setup of it

**Comment by alexsteinerde** [comment]
I'm trying apache `ab` for making concurrent requests. Unfortunately I cannot get into any segfault at the moment. 

What level of complexity do your queries/mutations have? Are you working with a lot of sub-fields in your query? 
Do you make queries or mutations (reading or writing)?

Would it be possible to share some of your queries/mutations in an anonymous way?

**Comment by jaredh159** [comment]
@alexsteinerde Thanks for replying!  I'm sending you an email to the email address listed on your Github profile with code to reproduce. Really appreciate you looking into this.  FWIW, I tried to reproduce the crash again just now, and got a slightly different output (although this time I was running the vapor app from terminal, and not from xcode). The error I got this most recent time was:

```
Run(41007,0x70000f564000) malloc: Double free of object 0x7ff31f10cf80
Run(41007,0x70000f564000) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by jaredh159** [comment]
@alexsteinerde kindly reproduced the issue, and it had nothing to do with graphql-kit -- instead it was my stupid decision to add a static property to `Middleware` because I didn't grok how to do authentication correctly with vapor+graphql. 🤦 

Thanks to both of you, and sorry for wasting your time!
