### ISSUE TITLE
A leaf tag for raw content without encoding

### ISSUE THREAD

**Issue by TomShen1234** [vapor/vapor#2666]
**Is your feature request related to a problem? Please describe.**
In previous versions of vapor there is a `#raw` tag in Leaf that can deliver contents such as HTML into a leaf template. There doesn't seems to be one in Vapor 4 (as far as the documentation and my experimentation goes). This makes it quite difficult to encode a piece of HTML (use cases might be one downloaded using the req's client) into a leaf template. 

**Describe the solution you'd like**
A leaf tag such as `#raw` that can embed contents without any encoding. 

**Describe alternatives you've considered**
It can also be a flag in the `render` function that disables encoding, but that might give less customizability for other parameters in the context that might actually want encoding.

If this feature already exists, it might be useful to add to the documentations too.

**Comment by 0xTim** [comment]
@TomShen1234 it was recently released as `unsafeHTML` (see the release notes [here](https://github.com/vapor/leaf-kit/releases/tag/1.3.0)).

But you're right, it should get added to the docs. Want to open an issue on vapor/docs for it?

**Comment by TomShen1234** [comment]
It’s done. https://github.com/vapor/docs/issues/616
