### ISSUE TITLE
Error fatalError deploy in ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by nguyenminhtienhust** [vapor/vapor#2681]
ubuntu 20.04 LTS
Swift version 5.4.2
vapor --version
framework: 4.48.4
toolbox: main (7575fe2)
====================
when I run the command:  "Swift run" 
==> output error: 
Compiling Vapor Demangler. swift
error: fatalError
=========================
When run with "vapor run"
===> output error: 
VaporToolbox/exec.swift:55: Fatal error: result 1
Illegal instruction (core dumped)

(Note: same source code, did build successfully in my Macos )

**Comment by vzsg** [comment]
> ubuntu 20.04 LTS

This unfortunately doesn't mean much.

Three questions:
1. Where are you running this Linux? Is it a virtual machine, a cloud service, Docker, real hardware, etc? Intel or ARM?
2. How much RAM is available to this machine? Unhelpful fatal errors most often occur when the compiler runs out of memory. The more you can allocate, the better.
3. Related to question 2, do you have swap enabled? If not, you should definitely [add some](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04).

**Comment by nguyenminhtienhust** [comment]
> > ubuntu 20.04 LTS
> 
> This unfortunately doesn't mean much.
> 
> Three questions:
> 
> 1. Where are you running this Linux? Is it a virtual machine, a cloud service, Docker, real hardware, etc? Intel or ARM?
> 2. How much RAM is available to this machine? Unhelpful fatal errors most often occur when the compiler runs out of memory. The more you can allocate, the better.
> 3. Related to question 2, do you have swap enabled? If not, you should definitely [add some](https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-20-04).
Answer: 
1. I use digital ocean, with droplets, not docker, 
2. I checked: 
                        total        used        free      shared  buff/cache   available
Mem:          981Mi       353Mi       316Mi        15Mi       311Mi       461Mi
3. i will try it
