### ISSUE TITLE
Logger not respected in app.autoMigrate()

### ISSUE THREAD

**Issue by cshadek** [vapor/vapor#2688]
### Describe the bug

Regardless of log level, the app.autoMigrate() function still prints NOTICE logs.  

### To Reproduce

```
app.logger.log(level: .notice, "TEST 1", metadata: nil, source: nil)
app.logger.logLevel = .error
app.logger.log(level: .notice, "TEST 2", metadata: nil, source: nil) // This will not print because the logger is respected
try app.autoMigrate().wait() // This will print NOTICE logs.
```

### Expected behavior

The app.autoMigrate() function should not print NOTICE logs because the logLevel is set to `.error`.

### Environment

* Vapor Framework version: 4.47.0
* Vapor Toolbox version:  
* OS version: Mac OS 11.6

**Comment by 0xTim** [comment]
@cshadek which database are you using and what notice logs are you seeing? On both SQLite and Postgres I can't see any notice logs printed for the migrations

**Comment by cshadek** [comment]
I'm using Postgres.  If it helps, most of the logs have to do with shortening index or foreign key names, like the following:

2021-09-23T12:54:24-0400 notice codes.vapor.postgres : relation "_fluent_migrations" already exists, skipping (transformCreateStmt)
2021-09-23T12:54:24-0400 notice codes.vapor.postgres : identifier "...." will be truncated to "...." (truncate_identifier)

**Comment by cshadek** [comment]
Also if it changes anything, I'm using ```autoMigrate()``` inside the setup method for XCTests.

**Comment by 0xTim** [comment]
Do you get the same behaviour if you update all your packages?

**Comment by 0xTim** [comment]
Additionally do you set the log level _before_ you add the migrations to the app migration list?

**Comment by cshadek** [comment]
I'm now using the latest version of every package and I get the same behavior.  

See below:
```
let app = Application(.testing)
try configure(app)
app.logger.logLevel = .error
app.addMigrations()
try app.autoRevert().wait()
try app.autoMigrate().wait()
```

2021-09-24T11:20:59-0400 notice codes.vapor.postgres : relation "_fluent_migrations" already exists, skipping (transformCreateStmt)
2021-09-24T11:21:00-0400 notice codes.vapor.postgres : identifier "..." will be truncated to "..." (truncate_identifier)

**Comment by gwynne** [comment]
Closing this out due to age and significant modification to the relevant code in the time since. Please reopen if you're still having this problem!
