### ISSUE TITLE
Move OTP from Vapor

### ISSUE THREAD

**Issue by makleso6** [vapor/vapor#2690]
**Is your feature request related to a problem? Please describe.**
I am try to run Vapor server on iOS

**Describe the solution you'd like**
My application support iOS 11, but vapor target iOS 13 because using swift-crypto

**Describe alternatives you've considered**
Move OTP in other target. My application does not use OTP

**Additional context**
none

**Comment by makleso6** [comment]
https://github.com/EdadealMobileDevelopment/vapor/commit/34f94dcaa220d5d98f88dd68440927e50b901f44

**Comment by 0xTim** [comment]
This is a breaking change in Vapor and something we can't accept unfortunately. Anyone currently using OTP with Vapor would need to add a new target dependency and change their imports. So any change like this would require a major version release of Vapor, which is not something the core team is prepared to do at the moment.

**Comment by makleso6** [comment]
@0xTim one of the solutions is move core logic in another repo (vapor-core) 🙂

**Comment by 0xTim** [comment]
That would add another repo to the list we maintain. At this time the core team are not prepared to lower the supported iOS version. iOS support is very much experimental and changing Vapor to accommodate iOS 11 is not something we're prepared to do.
