### ISSUE TITLE
Project won't compile with Xcode 13

### ISSUE THREAD

**Issue by Lukaz32** [vapor/vapor#2693]
### Describe the bug
The package fails to compile in the Xcode 13 

![Screenshot 2021-09-28 at 17 16 06](https://user-images.githubusercontent.com/544727/135115803-3781fa97-6196-4912-93d9-7b80b3c655f8.png)

### Environment

* Vapor Framework version: 4.48.8
* OS version: macOS BigSur 11.3 (20E232)
* Xcode Version 13.0 (13A233)

**Comment by 0xTim** [comment]
You need to update your packages, this was fixed in [SwiftNIO 2.32.3](https://github.com/apple/swift-nio/releases/tag/2.32.3)
