### ISSUE TITLE
request initializable

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#270]
# Request Initializable

* Author(s): [Tanner](https://github.com/tannernelson)
* Status: **[Awaiting review](#rationale)**

## Introduction

This feature would allow requests to be directly initialized into more a more meaningful and useful type.

## Motivation

Reducing boilerplate code between multiple routes increases efficiency and cuts down on bugs.

## Proposed solution

Provide a `RequestInitializable` protocol that can be type hinted on routes. 

## Code snippets

```swift
protocol RequestInitializable {
    init(request: Request) throws
}
```

```swift
class LoginRequest: RequestInitializable {
	var email: Valid<Email>
	var password: Valid<Password>

	init(request: Request) throws {
		email = try request.data["email"].validated()
		password = try request.data["password"].validated()
	}
}
```

```swift
app.get<LoginRequest>("/") { request in
    print(request.password)
}
```

OR

```swift
app.get("/") { (request: LoginRequest) in
    print(request.password)
}
```

## Impact

This adds functionality.

## Alternatives considered

No alternatives considered, please share your ideas.

## Decision (For Moderator Use)

On **[Date]**, the community decided to **(TBD)** this proposal. When the community makes a decision regarding this proposal, their rationale for the decision will be written here.

**Comment by Joannis** [comment]
This will be amazing once #281 get's merged.
