### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#271]
Add authentication middleware like OAuth, Basic auth, etc.

**Comment by Joannis** [comment]
Basic auth could be done using https://github.com/Zewo/BasicAuthMiddleware . I'm not familiar with it myself.

OAuth already exists for Swift 2.2 at https://github.com/p2/OAuth2 . I haven't used it.. but we could make it C7/S4 compliant and modify it for Swift 3.0 .

**Comment by LoganWright** [comment]
that oauth2 lib looks good, anyone tried compiling to see what its linux status is?

**Comment by Joannis** [comment]
Just cleaning up a misconception: OAuth is **not** authentication. It's authorization.

**Comment by Evertt** [comment]
I wonder, should we make functionalities like `Authentication` and `Authorization` separate packages maybe? I don't mind to make them "default dependencies", I just like to have them in separate packages, because I find it cleaner.

Any thoughts?

**Comment by tannernelson** [comment]
I think auth is necessary for virtually all web applications and usually a big headache for most web developers which makes me think it would be easiest for everyone to include a great solution by default.

**Comment by Joannis** [comment]
@tannernelson *authentication* is necessary. *authorization* is for platforms.
I think authentication is necessary as you say. But authorization is a lower priority imo

**Comment by Evertt** [comment]
@tannernelson and making it a separate package and including that as a default dependency is, in your opinion, not as good as just putting it in vapor? :-)

To me that's the same thing, only the separate package option promotes better code separation and motivates me to write it more loosely coupled from vapor itself.

**Comment by tannernelson** [comment]
This is being covered in #529
