### ISSUE TITLE
Validations against database

### ISSUE THREAD

**Issue by velascopja** [vapor/vapor#2712]
Hi,

I've been searching the docs and the issues but I haven't been able to find any information about it (sorry if there's already some available). Is it possible to validate the data sent in a request against values in the database? For example, would it be possible through Vapor Validation check the user name for a new user doesn't already exits in the database?

Please, if there's some information about this question already available anywhere, it would be much appreciated the link to it.

Thanks in advance.

**Comment by 0xTim** [comment]
Currently the Validations library doesn't allow any future work so you can't talk to the database. You'd need to write that yourself. 

Additionally there are complications when doing checks in the DB like you're talking about. If you get two concurrent requests with the same email they might bypass validation but fail a DB constraint so it's better to catch that at that level

**Comment by velascopja** [comment]
Yes, you're absolutely right.

Thank you very much!
