### ISSUE TITLE
faker

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#272]
Add support for Fakery https://github.com/vadymmarkov/Fakery

**Comment by timominous** [comment]
@tannernelson would this be added as a Provider?

**Comment by tannernelson** [comment]
I don't know yet. It's a lower priority feature for now so I didn't consider the full feature proposal yet. 
Do you have any ideas for how it should work?

**Comment by timominous** [comment]
Not yet. Was just starting to think about how to implement this. Seeing that it adds 3rd-party functionality to Vapor, I think it should be made as a provider. Thoughts?

**Comment by theobouwman** [comment]
But why not add is as a provider?

**Comment by LoganWright** [comment]
This is being temporarily deprioritized so we can focus on more critical issues.
