### ISSUE TITLE
Improve debugging for errors thrown when missing required Parameters

### ISSUE THREAD

**Issue by rausnitz** [vapor/vapor#2720]
We had a typo in our code that led to this error: https://github.com/vapor/vapor/blob/main/Sources/Vapor/Routing/Parameters%2BRequire.swift#L23. It was hard to debug in part because of the vague `Abort(.internalServerError)`. I suggest adding a `reason` value to the `Abort`, unless that would be considered a breaking change. I can submit a PR if you're interested.

**Comment by 0xTim** [comment]
@rausnitz I think a log should definitely be added and probably a reason as well. Happy for a PR or you can leave it for someone else to pick up

**Comment by rausnitz** [comment]
@0xTim If I were to introduce a `Logger` into this function, should I follow the pattern used here and just give it a different label? https://github.com/vapor/vapor/blob/2567c05b465e10aeb37d6a55762f2c1fe6fcb253/Sources/Vapor/Utilities/DotEnv.swift#L46

**Comment by 0xTim** [comment]
You can just use the requests logger, with `req.logger.debug` etc
