### ISSUE TITLE
Support `async/await` in macOS 10.15+

### ISSUE THREAD

**Issue by luispadron** [vapor/vapor#2723]
**Is your feature request related to a problem? Please describe.**
Not being able to use async/await on macOS 10.15 or macOS 11

**Describe the solution you'd like**
Remove the `@available(macOS12)` flags with the [new minimum deployment targets](https://www.swiftbysundell.com/special/swift-concurrency-backward-compatibility/).

**Describe alternatives you've considered**
Not using async/await 😢 

**Additional context**
Probably just need to wait for Xcode 13.2 to be out of beta to roll this out everywhere, would be nice to have a pre-release of sorts. Happy to contribute this as well

**Comment by mattesmohr** [comment]
Hey @luispadron, does this answer your question/issue?: [Swift Forum](https://forums.swift.org/t/async-await-has-arrived-in-vapor/53077/7)

**Comment by luispadron** [comment]
@mattesmohr Ah yes that make sense thanks a ton!
