### ISSUE TITLE
Support for peerAddress on Request

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#2736]
When checking a request's `remoteAddress`, it's usually the address from which NIO received the request. While that's technically correct, Vapor servers are often hosted behind a reverse-proxy such as nginx. Therefore the original peer's address is often lost. To resolve this, it's not uncommon to set the original peer's address in a header such as `X-Forwarded-For`.

**Describe the solution you'd like**
I'd like Vapor to add a property on Request, such as `peerAddress`, which reads the headers to find the peer's address first.

**Comment by VineFiner** [comment]
https://github.com/vapor/http/pull/32

**Comment by Joannis** [comment]
@VineFiner , Vapor/HTTP is only used in Vapor 3. My issue targets regression in Vapor 4.

**Comment by paunik** [comment]
Hello @Joannis, I tried to do this for the Vapor 4.
When You have time, could You please check if this is ok?

**Comment by Joannis** [comment]
@paunik I'll continue the discussion in your PR
