### ISSUE TITLE
Bottleneck in HTTPServerRequestDecoder?

### ISSUE THREAD

**Issue by lmcd** [vapor/vapor#2739]
Noticing that backpressure isn't working (https://github.com/vapor/vapor/issues/2738) made me also realise that NIO is taking in massive numbers of chunks super quick and efficiently, but they're arriving into Vapor at a much slower clip, even if you're not even doing anything with them.

Profiling a large upload, it looks like `HTTPServerRequestDecoder` is actually quite slow relative to how quick the rest of NIO is.
Probably around 30%+ of all time is spent dealing in `HTTPServerRequestDecoder`/`CircularBuffer`, half of that being ARC traffic.

With ARC, the whole NIO system is insanely efficient - over a 2s period, I'm seeing 10ms of retain traffic, and 9ms release.
Vapor on the other hand is seeing 109ms retain, and 92ms release.

I get a strong sense that there are some big optimisation opportunities here. I'm still trying to understand how this all works, but I might have a crack at hacking on this.

Someone correct me if I'm wrong and/or misinterpreting profiling data on this one.

**Comment by Joannis** [comment]
Hey @lmcd , thanks for the investigation! Before I start diving in, can you poke me on Vapor's Discord channel where I have the same username?

**Comment by lmcd** [comment]
It seems that this is most likely only a prevalent issue for long running upload/stream requests. If Vapor can't handle chunks fast enough, then they get queued up in a `CircularBuffer`. But then the costs of managing this buffer start to compound things further.

The performance hit seems to be coming from constantly reallocating/release/retaining the `ContiguousArray` and its underlying data storage, even if the `CircularBuffer` is set with a very high `initialCapacity`.

If backpressure was a thing, I'm not sure we'd need to buffer incoming chunks, but I'm still trying to wrap my head around NIO's ability to support this.

**Comment by lmcd** [comment]
Another observation, the bigger the circular buffer gets, the slower it is to append to. If I force an initial capacity of `1_000_000` (rather than the default where it starts at 16 and doubles when it maxes out), upload performance is significantly degraded.

Over 50% of all load is now spent managing this buffer, mostly in `_platform_memmove`. I think the issue here is that passing this struct around all over the place during state changes is causing extraneous copies which is blowing up like crazy as the buffer grows.

A good place to start might just be to create a property hanging directly off of `HTTPServerRequestDecoder` for the `CircularBuffer`, rather than passing it around as en enum case associated value.

**Comment by 0xTim** [comment]
Closed via #2759
