### ISSUE TITLE
Complex requests are not properly decoded

### ISSUE THREAD

**Issue by ka-ramba** [vapor/vapor#2746]
### Describe the bug
I have the following incoming get request coming form python urllib.parse.urlencode:
`codes=%5B%27SomeCodes%27%5D&offset=0&limit=100&orderBy=time&sortDirection=desc&filter=%7B%27metadata%27%3A+%7B%27w%27%3A+%27y%27%7D%2C+%27name%27%3A+%27somename%27%7D`

This should be decoded into
`codes=['SomeCodes']&offset=0&limit=100&orderBy=time&sortDirection=desc&filter={'metadata': {'w': 'y'}, 'name': 'somename'}`
And it does when checked in external tools for example here: https://www.url-encode-decode.com

But in Vapor it does not when the parameters are passed in query string but does when it is in the body.

`
public struct Filter : Content {
    public var id: UUID?
    public var name: String?
    public var after: Date?
    public var before: Date?
    public var metadata: [String:String]?
    public var version: Int32?
    public init()
    {
    }
    init(metadata: [String:String])
    {
        self.init()
        self.metadata = metadata
    }
}

struct GetRequest :  Content {
    var codes: [String]
    var filter: Filter = Filter()
    var offset:Int?
    var limit: Int?
    var orderBy: OrderBy? = .name
    var sortDirection: SortDirection? = .asc
}

`
In my controller I do:
`
let request = try req.query.decode(GetRequest.self)
`

It fails to decode Filter part of the request.
When I send this request in the request body and do 
req.content.decode instead of req.query.decode
Everything is working as expected.

**Comment by stelzo** [comment]
You have mixed parameter types which require different decoding strategies. How should Vapor know you encoded the filter parameter as JSON? One could try decoders and fail when everyone failed. I don't know if other servers do this though and I don't think this would be a good idea or good practice.

You could encode the filter as string, then decode it separately to your [String: String], this way the query stays consistent - or use the body instead.

**Comment by 0xTim** [comment]
Yeah this isn't a Vapor issue. As explained above you're converting incoming data from FormURLEncoded data and then expecting the JSON string to be converted from JSON data to a Swift struct. Vapor has no way of knowing this is JSON, so you should decode it to a String and then manually convert the JSON string to a Swift type (or write a nice extension to do it for you)
