### ISSUE TITLE
Cannot compile with Fluent MySQL driver

### ISSUE THREAD

**Issue by joshsharp** [vapor/vapor#2750]
Hello Vapor team! I'm just getting started with Vapor on Linux, as someone who isn't super familiar with Swift. So to begin, I successfully built the 'hello world' example. Now, after adding the MySQL driver dependencies and configuring them in `configure.swift`, I recieve this compilation error:

```
/home/me/web/vaporhello/.build/checkouts/fluent-mysql-driver/Sources/FluentMySQLDriver/MySQLRow
+Database.swift:40:14: error: value of type 'MySQLRow' has no member 'sql'
            .sql(decoder: self.decoder)
             ^~~
[1/5] Compiling FluentMySQLDriver MySQLRow+Database.swift
error: fatalError
```

### To Reproduce

1. Use this `Package.swift`:
```swift
// swift-tools-version:5.5
import PackageDescription

let package = Package(
    name: "vaporhello",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor/fluent-mysql-driver.git", from: "4.0.0-beta"),
        
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "FluentMySQLDriver", package: "fluent-mysql-driver")
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides/blob/main/docs/building.md#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .executableTarget(name: "Run", dependencies: [.target(name: "App")]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)
```
2. Use this `configure.swift`:
```swift
import Vapor
import Fluent
import FluentMySQLDriver


// configures your application
public func configure(_ app: Application) throws {
    var tls = TLSConfiguration.makeClientConfiguration()
    tls.certificateVerification = .none

    // uncomment to serve files from /Public folder
    //app.middleware.use(FileMiddleware(publicDirectory: app.directory.publicDirectory))
    app.databases.use(.mysql(hostname: "localhost", username: "[user]", password: "[pass]", database: "vapor", tlsConfiguration: tls), as: .mysql)

    // register routes
    try routes(app)
}
```

3. Compile & run on command line with `swift run`.

### Expected behavior

I expected this to compile successfully.

### Environment

* Vapor Framework version: 4.54.0
* Vapor Toolbox version: 18.3.3
* OS version: Ubuntu 16.04

**Comment by mkll** [comment]
@joshsharp Hi there,

The `sql()` method mentioned above is defined in `MySQLKit`:
https://github.com/vapor/mysql-kit/search?q=MySQLRow

It's strange that `MySQLKit` is not resolved and downloaded automatically by SPM as dependency of `FluentMySQLDriver`, but maybe you need to add `Fluent` to your Package.swift:

`.package(url: "https://github.com/vapor/fluent", from: "4.0.0"),` to `dependencies` section
and
`.product(name: "Fluent", package: "fluent"),` to `App` target.

**Comment by 0xTim** [comment]
`swift package update` and rebuilding should fix t

**Comment by joshsharp** [comment]
Thanks both! @0xTim's suggestion didn't work, but @mkll yours did, thanks very much.

So is this an SPM bug where it should have known better? I guess I'll keep in mind that it isn't great with transitive dependencies.

**Comment by mkll** [comment]
@joshsharp Well, you can't use `FluentMySQLDriver` without `Fluent` itself, so it's quite obvious that you need to specify Fluent too.

**Comment by joshsharp** [comment]
I'm not sure it's useful to point out that it's obvious. It wasn't to me :) the docs also say that Fluent is provided by default when you create a new project with Toolbox, which didn't happen for me.

Appreciate your quick help!

**Comment by mkll** [comment]
Oh, sorry for that. You're right. Glad it helped.

**Comment by 0xTim** [comment]
cc @gwynne this probably shouldn't be breaking
