### ISSUE TITLE
Any chance this will come to Windows?

### ISSUE THREAD

**Issue by philipturner** [vapor/vapor#2752]
I’m just curious whether there are any plans to bring Vapor to Windows. It would be a step closer to Swift being a universal cross-platform language, much like Swift for TensorFlow. Is Vapor already extremely fine-tuned for Unix?

**Comment by 0xTim** [comment]
@philipturner yes it should come to Windows with very few changes. Our main blocker is SwiftNIO - once that supports Windows (it's been on and off for a while) then Vapor should be able to support Windows

**Comment by 0xTim** [comment]
Closing in favour of #2646
