### ISSUE TITLE
Using APNS but failed in configuation

### ISSUE THREAD

**Issue by knight2010** [vapor/vapor#2753]
Hi, 

I am trying to use the APNS in vapor project,  and I am following the documentation.

I got the .p8 file from apple development website.

Will I am trying to run the project , it crashed on config the APNS. 

However, I got error for that.
JWTKit error: signing algorithm error: bioConversionFailure

Any one meet that issue?

**Comment by mkll** [comment]
@knight2010 Show the appropriate part of `configure.swift` and how you store the APNS keys. Maybe you're using the wrong keys.

**Comment by mkll** [comment]
@knight2010 Could you show the appropriate part of configure.swift and how you store the APNS keys? Maybe you're using the wrong keys or its format.

**Comment by 0xTim** [comment]
I'm guessing this is the same as Discord. The issue is that you're configuring the APNS library with:

```swift
.private(pem: "/path/to/key.p8"),
```

It should be:

```swift
.private(filePath: "/path/to/key.p8"),
```

Notice the difference in parameter name
