### ISSUE TITLE
There are some minor questions about the way .OPTIONS is used.

### ISSUE THREAD

**Issue by CainLuo** [vapor/vapor#2758]
I am a first-time server-side developer and I am new to the Vapor project. When I was browsing through the documentation provided by Vapor, I found that there is an .OPTIONS request method, but it doesn't seem to work according to the documentation. I didn't find the answer I was looking for in Issues, but here is my code and the result of Postman's request：

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/8857291/149162786-68a9c8d4-0c9c-4c5f-81b3-27d5c27ff152.png">

<img width="933" alt="image" src="https://user-images.githubusercontent.com/8857291/149162870-e9d42148-df45-435d-9a3c-67e9b4fedd45.png">

**Comment by 0xTim** [comment]
@CainLuo I think you need to change the HTTP method from `POST` to `OPTIONS` in Postman

**Comment by CainLuo** [comment]
> @CainLuo I think you need to change the HTTP method from `POST` to `OPTIONS` in Postman

Oh, I checked Postman and found that there is OPTIONS as a request method, thanks a lot~
