### ISSUE TITLE
APNS not working in Docker only environment, Xcode run works

### ISSUE THREAD

**Issue by markbattistella** [vapor/vapor#2763]
### Describe the bug

Running `docker-compose build` and then `docker-compose up -d` for an APNS only Vapor project doesn't see tables in Postgres. Running from Xcode and running only database in Docker works.

### To Reproduce

1. Download the [test project files](https://github.com/markbattistella/VaporAPNS) 
1. Run the WebService Vapor package - `Vapor-WebService`
1. In the WebService: 
  1. Edit the WebService to be your `key:`, `keyIdentifier:`, `teamIdentifier:` (lines 33-35 of configure.swift)
  1. Edit the WebService `topic` (line 39 of configure.swift) to the Bundle ID of the PushNotifications project (change it to a custom one you own)
  1. Edit the `APNSKeys` enum with your `p8` file
1. In terminal run `docker-compose up -d db` for the WebService
1. Run the Vapor Xcode project and accept the terminal use
1. Open the demo iOS app - `iOS-PushNotifications`
1. Edit the AppDelegate.swift file to change the IP address to your local machine
1. Run the demo app on a device and accept the permissions for notifications
1. Use a HTTP POST application (Postman / PAW) to send a notification to: `POST http://xxx.xxx.xxx.xxx:8080/token/notify`

Alert message on the iOS screen ✅ 

1. Stop the Xcode Vapor project
1. Stop the Docker database
1. From terminal run the command for the Vapor directory: `docker-compose build`
1. Once built, load the containers: `docker-compose up -d`
1. You should have the app and database running from Docker
1. Quit the iOS app (swipe up)
1. Relaunch the iOS app to register the APNS and database
1. Use a HTTP POST application (Postman / PAW) to send a notification to: `POST http://xxx.xxx.xxx.xxx:8080/token/notify`

Alert message does not appear on screen ❎ 

This also occurs when deploying to Heroku.

### Expected behavior

Expected that building the Vapor project into a container and running it from Docker would result in the same as running it from Xcode directly.

### Environment

* Vapor Framework version: 4.54.0
* Vapor Toolbox version: 18.3.3
* OS version: 12.1

### Additional context

When running it sometimes pops up with this in the Docker logs:

```
app_1 | [ WARNING ] server: relation "tokens" does not exist (parserOpenTable) 
[request-id: 17704098-65F0-496A-9B9F-2566CAF15E30] 
(Vapor/Middleware/ErrorMiddleware.swift:42)
```

But manually starting them database, waiting, then app still no notifications.

**Comment by 0xTim** [comment]
@markbattistella I'm guessing you haven't run the migrations to create the table

**Comment by markbattistella** [comment]
Hi @0xTim, sorry I had run them - just forgot to add it to the issue!

I had run them both on the Docker environment locally, and on Heroku.

I'm using DBeaver to watch the Postgres table, and when I launch my app the `tokens` table gets populated with an id, token, and debug.

That error message is only sometimes (but more likely to db not launching before app call).

No mater what I do, I cannot get a push notification from Docker only despite the logs saying everything is okay:

```
Attaching to vapor-app-ws_app_1, vapor-app-ws_db_1

db_1       | 
db_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1       | 
db_1       | 2022-01-17 23:41:59.225 UTC [1] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db_1       | 2022-01-17 23:41:59.225 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2022-01-17 23:41:59.225 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2022-01-17 23:41:59.229 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2022-01-17 23:41:59.235 UTC [22] LOG:  database system was shut down at 2022-01-17 23:41:30 UTC
db_1       | 2022-01-17 23:41:59.244 UTC [1] LOG:  database system is ready to accept connections

app_1      | [ DEBUG ] Could not load .env.production file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/Utilities/DotEnv.swift:120)
app_1      | [ DEBUG ] Could not load .env file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/Utilities/DotEnv.swift:120)
app_1      | [ NOTICE ] Server starting on http://0.0.0.0:8080 (Vapor/HTTP/Server/HTTPServer.swift:270)
app_1      | [ INFO ] POST /token [request-id: A346AE5D-D14B-43C8-A507-58A820C14049] (Vapor/Middleware/RouteLoggingMiddleware.swift:13)
app_1      | [ DEBUG ] query create tokens input=[[id: E3716996-AA03-4551-85F4-C8BAF1664A6C, token: "54bbbf68fc8ceb62ad8e62510375813f22d22caa6de9666d1a2bcf534e245800", debug: true]] [database-id: psql, request-id: A346AE5D-D14B-43C8-A507-58A820C14049] (FluentKit/Query/Builder/QueryBuilder.swift:291)
app_1      | [ DEBUG ] INSERT INTO "tokens" ("id", "token", "debug") VALUES ($1, $2, $3) RETURNING "id" [E3716996-AA03-4551-85F4-C8BAF1664A6C, "54bbbf68fc8ceb62ad8e62510375813f22d22caa6de9666d1a2bcf534e245800", true] [database-id: psql, request-id: A346AE5D-D14B-43C8-A507-58A820C14049] (FluentPostgresDriver/FluentPostgresDatabase.swift:29)
app_1      | [ DEBUG ] No available connections on this event loop, creating a new one [database-id: psql, request-id: A346AE5D-D14B-43C8-A507-58A820C14049] (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:202)
app_1      | [ INFO ] POST /token/notify [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (Vapor/Middleware/RouteLoggingMiddleware.swift:13)
app_1      | [ DEBUG ] query read tokens [database-id: psql, request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (FluentKit/Query/Builder/QueryBuilder.swift:291)
app_1      | [ DEBUG ] SELECT "tokens"."id" AS "tokens_id", "tokens"."token" AS "tokens_token", "tokens"."debug" AS "tokens_debug" FROM "tokens" [] [database-id: psql, request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (FluentPostgresDriver/FluentPostgresDatabase.swift:29)
app_1      | [ DEBUG ] No available connections on this event loop, creating a new one [database-id: psql, request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:202)
app_1      | [ DEBUG ] No available connections on this event loop, creating a new one [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (AsyncKit/ConnectionPool/EventLoopConnectionPool.swift:202)
app_1      | [ DEBUG ] Send - starting up [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (APNSwift/APNSwiftConnection.swift:176)
app_1      | [ INFO ] Send - sending [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (APNSwift/APNSwiftConnection.swift:214)
app_1      | [ DEBUG ] Request - building [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (APNSwift/APNSwiftRequestEncoder.swift:70)
app_1      | [ DEBUG ] Response - received [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (APNSwift/APNSwiftStreamHandler.swift:36)
app_1      | [ WARNING ] Response - bad request badDeviceToken [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (APNSwift/APNSwiftStreamHandler.swift:46)
app_1      | [ DEBUG ] query delete tokens filters=[tokens[id] = E3716996-AA03-4551-85F4-C8BAF1664A6C] [database-id: psql, request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (FluentKit/Query/Builder/QueryBuilder.swift:291)
app_1      | [ DEBUG ] DELETE FROM "tokens" WHERE "tokens"."id" = $1 [E3716996-AA03-4551-85F4-C8BAF1664A6C] [database-id: psql, request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (FluentPostgresDriver/FluentPostgresDatabase.swift:29)
```

**Comment by markbattistella** [comment]
It also seems that though running the same codebase, when running from Xcode the token doesn't get deleted from the Postgres database. 

When running it from Docker or Heroku the token for the device is deleted once the app is terminated (this is how I was testing).

Is there something potentially the way Xcode runs and complies the web app vs the way Docker/Heroku services do?

**Comment by mkll** [comment]
@markbattistella It looks like you're sending the notification to the wrong APNS server (sandbox instead of production or vice versa) and Apple server returns `badDeviceToken` error:

```
[ WARNING ] Response - bad request badDeviceToken [request-id: 44064A4A-7CA2-41F3-8437-B253B1A804EA] (APNSwift/APNSwiftStreamHandler.swift:46)
```

Double check your Vapor environment settings (debug or production) in both (Xcode and Docker) configurations. It makes sense to explicitly specify the environment in Vapor (you need debug environment due to iOS app runs from Xcode).

**Comment by mkll** [comment]
@markbattistella I looked at your Dockerfile - it explicitly says `.production` mode in the very last line. This is the cause of your troubles. Just change it to `.sandbox`.

**Comment by mkll** [comment]
@markbattistella Also, there are following lines in your `configure()`:

```
if app.environment == .development {
    try app.autoMigrate().wait()
}
```
This is the cause of that error message related to database.

P.S. Btw, I didn't get why don't you run migrations in production mode. Who will create and populate database in such case?

**Comment by markbattistella** [comment]
> @markbattistella I looked at your Dockerfile - it explicitly says `production` mode in the very last line. This is the cause of your troubles. Just change it to `development`. Then, APNSwift will use "sandbox" APNS servers.

I'll switch it over shortly and test - hopefully this is the answer! I can't believe I read over that line so many times.

Re:

> if app.environment == .development {
    try app.autoMigrate().wait()
}

That's because on Heroku it fails to deploy correctly if left in without the check. You have to manually migrate.

**Comment by mkll** [comment]
> hopefully this is the answer

Definetly. :)

**Comment by markbattistella** [comment]
thanks @mkll I cant believe that was my issue all along!

for those who need help in the future there were different places to switch the environment:

## Running app in Xcode and database in Docker
- everything should work correctly without modification

## Running the app and database in Docker
- `docker-compose.yml` edit the line from:
  - `command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]` to
  - `command: ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]`
- `Dockerfile` edit the last line:
  - `CMD ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]` to
  - `CMD ["serve", "--env", "development", "--hostname", "0.0.0.0", "--port", "8080"]`

## Running it Heroku
- `Procfile`change this:
  - `web: Run serve --env production --hostname 0.0.0.0 --port $PORT` to
  - `web: Run serve --env development --hostname 0.0.0.0 --port $PORT`
