### ISSUE TITLE
Vapor 4.54.1 broke decompressing of certain gzipped requests

### ISSUE THREAD

**Issue by LukasCZ** [vapor/vapor#2766]
It seems that Vapor 4.54.1 broke decompressing of requests which are gzipped (not all of them, but some).
In my testing, with Vapor 4.54.0 decompressing works correctly for all gzip requests that I send to it. But in 4.54.1, I am running into this issue with certain gzip files:

```
[ ERROR ] /sync - Error while parsing the request: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Foundation.JSONError.unexpectedEndOfFile))), error.localizedDescription = The operation could not be completed. The data isn’t in the correct format..
```

Here's how I am setting up support for decompressing requests in my configure.swift:
`app.http.server.configuration.requestDecompression = .enabled(limit: .size(20_000_000))`

(It has worked correctly for me for the last year+, up until yesterday when I updated my Vapor app on the server which pulled Vapor 4.54.1)

I'm attaching the gzip file for which it is failing:
[problem-file.gz](https://github.com/vapor/vapor/files/7916553/problem-file.gz).

**Comment by LukasCZ** [comment]
Yes, here:
["Content-Type": "application/json", "Content-Encoding": "gzip", "Authorization": "Bearer XXXXXXXXXXXX=="])

I am setting the contents of the file (the gzipped data) as httpBody of the URLRequest that I am making from my iOS app using NSURLSession.

**Comment by Joannis** [comment]
I've reproduced it with that file
