### ISSUE TITLE
Can Vapor 4 redirect with params?

### ISSUE THREAD

**Issue by iWECon** [vapor/vapor#2772]
Can Vapor 4 redirect with params?

Like `XCTApplicationTester.test(.POST, "/new/path", body: ByteBuffer?)`?

May not call `redirect` name, I don't know what the name is.

**Comment by 0xTim** [comment]
No. A redirect simple returns a response to the client with a 3XX status code and a `Location` header - there's no room in the spec for returning a redirect with some body. If you want to pass information you have to use URL query parameters like `/new/path?data=something`

Does that answer your question?

**Comment by iWECon** [comment]
> No. A redirect simple returns a response to the client with a 3XX status code and a `Location` header - there's no room in the spec for returning a redirect with some body. If you want to pass information you have to use URL query parameters like `/new/path?data=something`
> 
> Does that answer your question?

Yeah, does the vapor has anyone function easy to send `/new/path?data=something?` (the /new/path define in another RouteCollection), or only can use `req.client.get/post`?

**Comment by iWECon** [comment]
Example:
```swift
struct Api1: RouteCollection {
    func boot(_ routes:…) {
        // post
        routes.post(“user”) { req in
       // some codes…
    }
}

struct Api2: RouteCollection {
    func boot(_ routes:…) {
        routes.get(“favorite”) { req in
            // how to call POST /user (define in api1)
    }
}
```

**Comment by iWECon** [comment]
@0xTim 
Uhhhh, have consideration to provide a similar `.test` method?

```swift
// in test
try app.test(.POST, "user", afterResponse: { res in
    XCTAssertEqual(res.status, .ok)
})

// in production
try req.call(.POST, "user", headers: req.headers, body: req.body ?? result)
```

**Comment by 0xTim** [comment]
If you really want you can use the client to do that, but I strongly advise against doing that. You're introducing a network stack at that point which will just slow things down and could go wrong. Just extract both route handlers to a common function and call them using Swift?

**Comment by iWECon** [comment]
@0xTim ok, thanks for your response
