### ISSUE TITLE
Docker problems with arm64 (M1)

### ISSUE THREAD

**Issue by apps4everyone** [vapor/vapor#2777]
When building Vapor on a M1 the docker container from https://hub.docker.com/_/swift?tab=tags are failing.
When changing to https://hub.docker.com/r/swiftarm/swift the container is building locally but not on Google Cloud run.

Could it be that multi arch is needed? https://www.docker.com/blog/multi-arch-images/

1. Start new Vapor with template
2. build docker container (swift error)
3. Run in google cloud run

**Comment by 0xTim** [comment]
This is a Swift problem rater than a Vapor issue. You can use the [nightlies](https://hub.docker.com/r/swiftlang/swift) for now to build with a multi arch container. These will be released into the official Swift image with 5.6

**Comment by apps4everyone** [comment]
thx for the info. solved now with, maybe a hint in the docs would help (for now):

Docker file top:
`FROM --platform=linux/x86-64 swift`

and build with:
`docker buildx build --platform linux/amd64 --push -t eu.gcr.io/xxx/yyy .`

**Comment by ShawnBaek** [comment]
@apps4everyone Thanks! It works

**Comment by 0xTim** [comment]
Multiplatform Docker images are now available so you can remove the platform flag is building and running locally. Note you'll still need the platform command if you're _deploying_ to an x86 server (but really in that case you should be building on CI and not locally)

**Comment by JuliusHuizing** [comment]
Are there any examples of a Dockerfile + docker-compose.yml for a Vapor project that:

1. Lead to successful local builds on arm-based machines (e.g. M1 Mac)
2. Allow the resulting image to be deployed to an amd-based machine (e.g AWS Lightsail container)?

I have the same problem as described above, but cannot solve it using the suggested solutions; all local builds fail as soon as I try to specify linux/amd64 as the target platform.

**Comment by 0xTim** [comment]
Anytime you try and emulate x86 on ARM you're going to have issues. Until the cross-compilation toolchains are available then this will continue to crop up. You're best option is if you're going to deploy to x86 then build on x86 (usually through CI). AWS has ARM platforms available for most services as well
