### ISSUE TITLE
How to install older version of Vapor?

### ISSUE THREAD

**Issue by alexvbush** [vapor/vapor#2785]
hi, how do I install older version of Vapor such as version 3? `brew install vapor` get me the latest one and running `brew install vapor@3` doesn't seem to work.

**Comment by 0xTim** [comment]
Are you talking about the toolbox or the framework?

**Comment by DevOpsThinh** [comment]
> hi, how do I install older version of Vapor such as version 3? `brew install vapor` get me the latest one and running `brew install vapor@3` doesn't seem to work.

🤝 Hi sir, support your issue:

- https://stackoverflow.com/questions/62593987/how-to-downgrade-vapor-4-to-vapor-3
- https://docs.vapor.codes/upgrading/

Have a good day 😃

**Comment by DevOpsThinh** [comment]
> @DevOpsThinh why do you want to install the old toolbox?

🤭 Hi sir, not me! However, my macOS's version is Big Sur + Xcode 13.2 (Swift package 5.5.0), but the latest Vapor framework is supporting swift package 5.6.0.

**Comment by 0xTim** [comment]
I'm going to close this issue. The toolbox is used for creating new projects so there shouldn't be a need to install the old version. If you do need it, it can be installed from source.

You can pass the old API Template as a parameter if you want but Vapor 3 is EoL now so not supported. Feel free to ask any other questions though!
