### ISSUE TITLE
Vapor could support cluster?

### ISSUE THREAD

**Issue by ldbfrank** [vapor/vapor#2793]
**Is your feature request related to a problem? Please describe.**
Could Vapor support multiple instances?

**Describe the solution you'd like**
Are there any docs about it?

**Describe alternatives you've considered**
Cluster is required.

**Additional context**

**Comment by fig666** [comment]
the implication of the subject is no resolved

**Comment by 0xTim** [comment]
What do you mean by a cluster specifically? You can run multiple instances of the same app as long as any state (like the database) is managed by a sever that all instances can talk to

**Comment by ldbfrank** [comment]
One server instance for one processor, like node cluster.

**Comment by mkll** [comment]
@ldbfrank You don't need it because Vapor will do it for you.: ["When your application boots, it will usually create one event loop for each core in the CPU it is running on"](https://docs.vapor.codes/4.0/async/#event-loop)

**Comment by ldbfrank** [comment]
@mkll Great!
