### ISSUE TITLE
Improvement docker build speed

### ISSUE THREAD

**Issue by iWECon** [vapor/vapor#2806]
I put the docker build process of vapor on the VPS for execution, then I found that this will cost me a lot of time, even if I only modify someone of the files in the project. Of course, I have also searched the forum for related content, and the answer did not find useful content. So I decided to try myself.

> My VPS configure: 4vCPU 8G RAM, Ubuntu 20.04

Vapor runs, using the compiled product, but can't cache build in docker.

So I tried to place the build process to run on the VPS, and then handed the compiled product (Run) to Docker to run.

In the end, I succeeded, I shorten the time from 500s(about, usually about 470s without layer cache) to 40s (about and without layer cache).

I don't know if there will be other problems, so I want to discuss with you. 

I can share all things I have done, when I determine or you need it.

**Comment by AndreYonadam** [comment]
`swift:5.6-focal` supports arm and I heard that should dramatically decrease build time. Please give that a try.

**Comment by iWECon** [comment]
> `swift:5.6-focal` supports arm and I heard that should dramatically decrease build time. Please give that a try.

I tried, but still always build whole module, and shorten time from 470s to 400s about, remain...

**Comment by 0xTim** [comment]
What platform are you building on? We cache as much as we can in the Dockerfile but there's a limit to what you can do with SwiftPM. Note that you'll need to built the same architecture as you're deploying to and this is usually handled by CI.

**Comment by iWECon** [comment]
> What platform are you building on? We cache as much as we can in the Dockerfile but there's a limit to what you can do with SwiftPM. Note that you'll need to built the same architecture as you're deploying to and this is usually handled by CI.

😂 I mean I found a way to speed up the compilation (using the cache from the last compilation):

I can use (swift build - c release) to compile on the host machine(VPS), and copy the result(Run) into the docker container after the compilation is completed.

In fact, when compiling on the host, the cache completed by the last compilation will be used, which can greatly improve the compilation speed.

My English is not good, check the code should be more clear...

I don't know if there will be other problems in this way. What do you recommend?

`fast_build.sh`
```bash
#!/bin/bash

echo "🚀 fast building"

# stop when happen error
set -e

echo "run > swift build -c release"
swift build -c release

# move run to .
echo "run > copy {Run} to ./Run"
cp .build/x86_64-unknown-linux-gnu/release/Run ./Run

echo "run > docker build fastDockerfile"
docker build -f fastDockerfile . -t main:latest

echo "run > rm local ./Run"
rm -rf ./Run

echo "> 🎉 all of done"
```

`fastDockerfile`
```
# ================================
# Build image
# ================================
FROM swift:5.6.1-focal as build

# Install OS updates and, if needed, sqlite3
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y \
    && rm -rf /var/lib/apt/lists/*

# Set up a build area
WORKDIR /build

# Copy entire repo into container
COPY . .
RUN rm ./Run

# Switch to the staging area
WORKDIR /staging

# Copy main executable to staging area
COPY ./Run ./

# Copy any resources from the public directory and views directory if the directories exist
# Ensure that by default, neither the directory nor any of its contents are writable.
RUN [ -d /build/Public ] && { mv /build/Public ./Public && chmod -R a-w ./Public; } || true
RUN [ -d /build/Resources ] && { mv /build/Resources ./Resources && chmod -R a-w ./Resources; } || true

# ================================
# Run image
# ================================
FROM swift:5.6.1-focal-slim

# Make sure all system packages are up to date.
RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
    apt-get -q update && apt-get -q dist-upgrade -y && rm -r /var/lib/apt/lists/*

# Create a vapor user and group with /app as its home directory
RUN useradd --user-group --create-home --system --skel /dev/null --home-dir /app vapor

# Switch to the new home directory
WORKDIR /app

# Copy built executable and any staged resources from builder
COPY --from=build --chown=vapor:vapor /staging /app
#COPY --from=build --chown=vapor:vapor /staging/.env /app
#COPY --from=build --chown=vapor:vapor /staging/.env.production /app

# Ensure all further commands run as the vapor user
USER vapor:vapor

# Let Docker bind to port 8080
EXPOSE 8080

# Start the Vapor service when the image is run, default to listening on 8080 in production environment
ENTRYPOINT ["./Run"]
CMD ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
```

**Comment by VineFiner** [comment]
you can use github Action
This is demo `https://github.com/VineFiner/vapor-hello-action`

**Comment by 0xTim** [comment]
I'm going to close this of now. They above trick is great as long as you have a build machine that is the same as your deployment image. It won't help e.g. people building Linux images on macOS.

There's a bigger piece of work around caching and build speeds that the SSWG and Swift teams are aware of and working on
