### ISSUE TITLE
How to add routes to a running Application?

### ISSUE THREAD

**Issue by abdulowork** [vapor/vapor#2807]
**The problem:**
I am trying to understand how routing works in Vapor. Right now I have a bit of a trouble understanding how I should approach adding new routes to a running `Application` instance. Ex:

```swift
let app = Application()

app.get("a") { _ -> String in
    "a"
}

try app.start()

app.get("b") { _ -> String in
    "b"
}
```

when I send a request to route `/a` I get the expected response; however, when I send a request to route `/b` I get a 404 error.

Say I was building a file sharing service where a user can upload a file, get a link and share it with someone. The naive implementation that I am thinking about looks like this:

```swift
app.post("upload") { uploadRequest -> String in
    let fileUniqueIdentifier = UUID().uuidString
    
    // read the data and save the file

    uploadRequest.application.get("download", .constant(fileUniqueIdentifier)) { downloadRequest in
        downloadRequest.fileio.streamFile(at: pathToUploadedFile)
    }

    return fileUniqueIdentifier
}
```

Am I supposed to use dynamic path components instead?

**Describe the solution you'd like:**
Is the inability to register routes with a running application intentional? In case it is, I feel like it would be beneficial to emit a warning when registering routes with an already running application.

**Comment by biboran** [comment]
A related API behavior that I find a little bit surprising is that a call to `app.http.server.shared` finalizes the routing setup. So in the following example `/a` is routed as expected but `/b` will not be routed:

```swift
let app = Application()

app.get("a") { _ -> String in
    "a"
}

_ = app.http.server.shared

app.get("b") { _ -> String in
    "b"
}

try app.run()
```

**Comment by mkll** [comment]
@biboran The short answer to your question in the issue title is no.

But your problem can be solved, just in a different way. Vapor has built-in tools for such cases. Take a look at [this section](https://docs.vapor.codes/4.0/routing/#route-parameters
) of the documentation.

**In a nutshell**:

Instead of:
```
uploadRequest.application.get("download", .constant(fileUniqueIdentifier))
```
you use something like that:

```
uploadRequest.application.get("download", ":fileUniqueIdentifier")
```
(pay attention to the colon in the second parameter)

P.S. In general, it was very useful to read the Vapor documentation from beginning to end. It is small in volume, but it explains all the practical issues, with examples. I strongly advise you to do this.

**Comment by abdulowork** [comment]
@mkll Thank you for pointing out the section in the documentation. I read through the documentation and now I have a better understanding of how the routing is supposed to be setup in Vapor.

The codebase that I wanted to migrate to Vapor had routing registrations all over the place. To simplify things I ended up implementing a custom Responder class based on [DefaultResponder](https://github.com/vapor/vapor/blob/cdcae457ac60b7b7e29e68f3ea7e482541da3f03/Sources/Vapor/Responder/DefaultResponder.swift#L4) with support for registering new routes on the fly.
