### ISSUE TITLE
Building hello sample application with Docker does not work

### ISSUE THREAD

**Issue by tobiastom** [vapor/vapor#2819]
### Describe the bug

When I try to build the `hello` sample application with Docker I get the following error:

```
…
[927/928] Compiling AsyncHTTPClient HTTPClient+execute.swift
error: link command failed with exit code 254 (use -v to see invocation)
clang-13: error: unable to execute command: Killed
clang-13: error: linker command failed due to signal (use -v to see invocation)
[934/935] Linking Run
The command '/bin/sh -c swift build -c release --static-swift-stdlib' returned a non-zero code: 1
```

### To Reproduce

1. `vapor new hello -n`
2. `cd vapor`
3. `docker build ./`

### Expected behavior

The Docker image should be build without an error. 

### Environment

* Vapor Framework version: 4.57.0
* Vapor Toolbox version: 18.3.6
* OS version: macOS 12.3.1

### Additional context

```
❯ docker --version
Docker version 20.10.14, build a224086349
❯ minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```

If there is anything I can to do debug this issue further, please let me know.

**Comment by 0xTim** [comment]
I suspect you've run out of memory. Try giving the Docker runtime more memory

**Comment by tobiastom** [comment]
@0xTim This indeed helped. Thank you! Sorry for the noise.
