### ISSUE TITLE
brew install vapor compile error

### ISSUE THREAD

**Issue by xiangfly11** [vapor/vapor#2828]
> 

### Describe the bug

I use brew install vapor/tap/vapor to install vapor, but i get compile error.
### To Reproduce

1, Xcode Version 13.3
2, Mac OS Version 12.3
3,Homebrew 3.4.11-34-gc20b3ab
Homebrew/homebrew-core (git revision 1b4baeeddb; last commit 2021-02-08)
Homebrew/homebrew-cask (git revision 3a77e334e4; last commit 2022-05-16)

Error:
brew install vapor/tap/vapor           
==> Downloading https://github.com/vapor/toolbox/archive/18.0.0.tar.gz
Already downloaded: /Users/jiaxiangli/Library/Caches/Homebrew/downloads/a4d3c11ed4b9d0aa51eaf5b9b88cfcd1b357a41b6d06ee739e7050a90963ca51--18.0.0.tar.gz
==> Installing vapor from vapor/tap
==> swift build --disable-sandbox -c release -Xswiftc -cross-module-optimization
Last 15 lines from /Users/user/Library/Logs/Homebrew/vapor/01.swift:
                                     ^~~~~
                                     AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/console-kit/Sources/ConsoleKit/Console.swift:37:26: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol Console: class {
                         ^~~~~
                         AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:32: warning: initialization of 'UnsafeMutablePointer<yaml_version_directive_t>' (aka 'UnsafeMutablePointer<yaml_version_directive_s>') results in a dangling pointer
            versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:53: note: implicit argument conversion from 'yaml_version_directive_t' (aka 'yaml_version_directive_s') to 'UnsafeMutablePointer<yaml_version_directive_t>' (aka 'UnsafeMutablePointer<yaml_version_directive_s>') produces a pointer valid only for the duration of the call to 'init(_:)'
            versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
                                                    ^~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:53: note: use 'withUnsafeMutablePointer' in order to explicitly convert argument to pointer valid for a defined scope
            versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
                                                    ^

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/vapor/homebrew-tap/issues

Build logs:
> 2022-05-17 03:03:29 +0000

swift
build
--disable-sandbox
-c
release
-Xswiftc
-cross-module-optimization

warning: Failed creating default security location, Error Domain=NSCocoaErrorDomain Code=513 "“security” couldn’t be removed because you don’t have permission to access it." UserInfo={NSUserStringVariant=(
    Remove
), NSFilePath=/Users/jiaxiangli/.swiftpm/security, NSUnderlyingError=0x6000010b2310 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}
warning: Failed creating default configuration location, other(1)
warning: Failed creating default cache location, other(1)
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/apple/swift-nio.git
Fetching https://github.com/tanner0101/mustache.git
[1/75] Fetching objects
Fetched https://github.com/apple/swift-nio.git (660.02s)
Fetched https://github.com/jpsim/Yams.git (660.02s)
Fetched https://github.com/tanner0101/mustache.git (660.02s)
Fetching https://github.com/vapor/console-kit.git
Fetching https://github.com/apple/swift-log.git
Fetched https://github.com/apple/swift-log.git (120.74s)
Fetched https://github.com/vapor/console-kit.git (120.85s)
Fetching https://github.com/vapor/console-kit.git
Fetched https://github.com/vapor/console-kit.git (6.36s)
Computing version for https://github.com/vapor/console-kit.git
Computed https://github.com/vapor/console-kit.git at 4.1.1 (3.38s)
Fetching https://github.com/apple/swift-log.git
Fetched https://github.com/apple/swift-log.git (16.19s)
Computing version for https://github.com/tanner0101/mustache.git
Computed https://github.com/tanner0101/mustache.git at 0.1.0 (1.27s)
Updating https://github.com/apple/swift-log.git
Computing version for https://github.com/jpsim/Yams.git
Updated https://github.com/apple/swift-log.git (1.65s)
Computed https://github.com/jpsim/Yams.git at 2.0.0 (2.69s)
Computing version for https://github.com/apple/swift-nio.git
Computed https://github.com/apple/swift-nio.git at 2.18.0 (1.08s)
Computing version for https://github.com/apple/swift-log.git
Computed https://github.com/apple/swift-log.git at 1.2.0 (0.90s)
Creating working copy for https://github.com/apple/swift-log.git
Working copy of https://github.com/apple/swift-log.git resolved at 1.2.0
Creating working copy for https://github.com/vapor/console-kit.git
Working copy of https://github.com/vapor/console-kit.git resolved at 4.1.1
Creating working copy for https://github.com/tanner0101/mustache.git
Working copy of https://github.com/tanner0101/mustache.git resolved at 0.1.0
Creating working copy for https://github.com/jpsim/Yams.git
Working copy of https://github.com/jpsim/Yams.git resolved at 2.0.0
Creating working copy for https://github.com/apple/swift-nio.git
Working copy of https://github.com/apple/swift-nio.git resolved at 2.18.0
Building for production...
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[1/14] Compiling writer.c
[2/14] Compiling reader.c
[3/15] Compiling parser.c
[4/15] Compiling api.c
[5/15] Compiling CNIOSHA1 c_nio_sha1.c
[6/15] Compiling CNIOLinux shim.c
[7/15] Compiling CNIOLinux ifaddrs-android.c
[8/15] Compiling CNIODarwin shim.c
[9/15] Compiling emitter.c
[10/15] Compiling scanner.c
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[11/16] Compiling c-nioatomics.c
[12/16] Compiling CMustache mustach.c
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[13/17] Compiling c-atomics.c
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[14/18] Compiling Logging Locks.swift
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[15/19] Compiling NIOConcurrencyHelpers NIOAtomic.swift
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization[16/20] Compiling Mustache MustacheContext.swift
[17/20] Compiling NIO AddressedEnvelope.swift
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/Channel.swift:22:30: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol ChannelCore: class {
                             ^~~~~
                             AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/Channel.swift:105:26: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol Channel: class, ChannelOutboundInvoker {
                         ^~~~~
                         AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/ChannelHandler.swift:20:33: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol ChannelHandler: class {
                                ^~~~~
                                AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/CircularBuffer.swift:114:1: error: type 'CircularBuffer<Element>' does not conform to protocol 'MutableCollection'
extension CircularBuffer: Collection, MutableCollection {
^
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/CircularBuffer.swift:114:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
extension CircularBuffer: Collection, MutableCollection {
^
Swift.MutableCollection:8:12: note: 'subscript(_:)' declared here
    public subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get set }
           ^
Swift.MutableCollection:6:14: note: requirement 'subscript(_:)' declared here
    override subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get set }
             ^
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/EventLoop.swift:719:33: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol EventLoopGroup: class {
                                ^~~~~
                                AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/MarkedCircularBuffer.swift:132:1: error: type 'MarkedCircularBuffer<Element>' does not conform to protocol 'MutableCollection'
extension MarkedCircularBuffer: Collection, MutableCollection {
^
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/swift-nio/Sources/NIO/MarkedCircularBuffer.swift:132:1: error: unavailable subscript 'subscript(_:)' was used to satisfy a requirement of protocol 'MutableCollection'
extension MarkedCircularBuffer: Collection, MutableCollection {
^
Swift.MutableCollection:8:12: note: 'subscript(_:)' declared here
    public subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get set }
           ^
Swift.MutableCollection:6:14: note: requirement 'subscript(_:)' declared here
    override subscript(bounds: Range<Self.Index>) -> Self.SubSequence { get set }
             ^
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/console-kit/Sources/ConsoleKit/Command/CommandSignature.swift:49:38: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
internal protocol AnySignatureValue: class {
                                     ^~~~~
                                     AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/console-kit/Sources/ConsoleKit/Console.swift:37:26: warning: using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead
public protocol Console: class {
                         ^~~~~
                         AnyObject
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:32: warning: initialization of 'UnsafeMutablePointer<yaml_version_directive_t>' (aka 'UnsafeMutablePointer<yaml_version_directive_s>') results in a dangling pointer
            versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:53: note: implicit argument conversion from 'yaml_version_directive_t' (aka 'yaml_version_directive_s') to 'UnsafeMutablePointer<yaml_version_directive_t>' (aka 'UnsafeMutablePointer<yaml_version_directive_s>') produces a pointer valid only for the duration of the call to 'init(_:)'
            versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
                                                    ^~~~~~~~~~~~~~~~~~~~~~
/private/tmp/vapor-20220517-98923-akz50t/toolbox-18.0.0/.build/checkouts/Yams/Sources/Yams/Emitter.swift:338:53: note: use 'withUnsafeMutablePointer' in order to explicitly convert argument to pointer valid for a defined scope
            versionDirective = UnsafeMutablePointer(&versionDirectiveValue)
                                                    ^

HOMEBREW_VERSION: 3.4.11-34-gc20b3ab
ORIGIN: https://mirrors.ustc.edu.cn/brew.git
HEAD: c20b3ab91381aca5fdfda54374fc0390cc09dd51
Last commit: 3 days ago
Core tap ORIGIN: https://mirrors.ustc.edu.cn/homebrew-core.git
Core tap HEAD: 1b4baeeddb26848d3b3f8ede52eb62a97d54375a
Core tap last commit: 1 year, 3 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8/bin/ruby
CPU: quad-core 64-bit skylake
Clang: 13.1.6 build 1316
Git: 2.32.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.79.1 => /usr/bin/curl
macOS: 12.3-x86_64
CLT: N/A
Xcode: 13.3

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/apache2:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/12
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by vzsg** [comment]
Use `brew install vapor` instead of `brew install vapor/tap/vapor`.
The latter is deprecated and outdated.

Unfortunately, not all written guides are up to date on this either...
Thanks for raising the issue though, we'll figure out a solution.

**Comment by vzsg** [comment]
Actually, I shouldn't close this yet, sorry.

**Comment by xiangfly11** [comment]
> 



> Use `brew install vapor` instead of `brew install vapor/tap/vapor`. The latter is deprecated and outdated.
> 
> Unfortunately, not all written guides are up to date on this either... Thanks for raising the issue though, we'll figure out a solution to reduce friction.

thanks

**Comment by 0xTim** [comment]
This should be solved by https://github.com/vapor/homebrew-tap/commit/7cc8b802739630ca4125cf68fdcb7476a8affa5b which should block installing from the Vapor tap and point people to Homebrew core
