### ISSUE TITLE
Issue Value of type Parameters has no member of logger

### ISSUE THREAD

**Issue by amine2233** [vapor/vapor#2841]
### Describe the bug

Can't build Vapor 4.60.3 on my project

### To Reproduce

1. Add package with configuration '.package(url: "https://github.com/vapor/vapor.git", from:"4.60.3")'
2. Send request with options "build the app"
3. See error4. 

<img width="460" alt="Capture d’écran 2022-06-01 à 21 52 43" src="https://user-images.githubusercontent.com/404449/171490410-d7a6fd64-8c84-493d-8692-7000c258c9ed.png">

### Expected behavior

build the app

### Environment

* Vapor Framework version: 4.60.3
* Vapor Toolbox version:
* OS version: macOS 12.3.1

**Comment by bitwit** [comment]
I had this issue as well today and it appeared to make. difference whether I was building for debug or release. Looks like this was introduced in 4.60.1

**Comment by mkll** [comment]
> I had this issue as well today and it appeared to make a difference whether I was building for debug or release. Looks like this was introduced in 4.60.1

Definetly in https://github.com/vapor/vapor/pull/2833/commits/02e00d446ce2415f7201df26198585ad01bbbc14

**Comment by 0xTim** [comment]
Make sure you've updated your dependencies, I missed upping the RoutingKit dependency when this was added
