### ISSUE TITLE
AWS: /usr/bin/ld.gold: fatal error: out of file descriptors and couldn't close any

### ISSUE THREAD

**Issue by aibo-cora** [vapor/vapor#2844]
### Describe the bug

My project runs fine in a container on local machine, but Fargate task on ECS fails to start it.

I've deployed containers without Fluent and Postgress driver dependencies without issues before, I believe that's what is causing the error.

### To Reproduce

<pre>
// swift-tools-version:5.6
import PackageDescription

let package = Package(
    name: "database",
    platforms: [
       .macOS(.v12),
       .iOS(.v15)
    ],
    dependencies: [
        .package(url: "https://github.com/vapor/fluent.git", from: "4.0.0"),
        .package(url: "https://github.com/vapor/fluent-postgres-driver.git", from: "2.0.0"),
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Fluent", package: "fluent"),
                .product(name: "FluentPostgresDriver", package: "fluent-postgres-driver"),
                .product(name: "Vapor", package: "vapor"),
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides/blob/main/docs/building.md#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .executableTarget(name: "Run", dependencies: [.target(name: "App")]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)
</pre>
2. Dockerfile
<pre>
# Ubuntu Bionic 18.04
# Swift 5.6.1 Release
FROM swift
LABEL maintainer="Yura Filatov <yura.fila@gmail.com>"
LABEL description="Joint API key production vapor http server."

EXPOSE 8080

COPY . .
RUN apt update && apt install -y \
	make \
	sudo

# Download `Vapor`
WORKDIR /vapor
RUN mkdir vapor && cd vapor
RUN git clone https://github.com/vapor/toolbox.git && cd toolbox && git checkout 18.3.6

# Increase number of file descriptors (compiler does not have enough to work with)
RUN ulimit -Ha
# Build `Vapor`
RUN cd toolbox && make install 
#RUN cd toolbox && swift build

# Create new project
RUN vapor new joint -n
WORKDIR /vapor/joint

# Copy source files
COPY context/Sources /vapor/joint/Sources
COPY context/.env /vapor/joint/
COPY context/Package.swift /vapor/joint

# Run server on container start
CMD ["swift", "run", "Run", "serve", "--hostname", "0.0.0.0"]
</pre>

Running <code>ulimit -n 65356</code> did not help.
### Log
<pre>

2022-06-03T09:51:41.426-04:00 | [2138/2143] Emitting module App
-- | --
  | 2022-06-03T09:51:41.734-04:00 | [2139/2145] Compiling App CreateUserTables.swift
  | 2022-06-03T09:51:41.787-04:00 | [2140/2145] Compiling App User.swift
  | 2022-06-03T09:51:42.469-04:00 | [2141/2145] Compiling App configure.swift
  | 2022-06-03T09:51:42.469-04:00 | [2142/2145] Compiling App routes.swift
  | 2022-06-03T09:51:42.656-04:00 | [2145/2147] Wrapping AST for App for debugging
  | 2022-06-03T09:51:42.888-04:00 | [2146/2149] Emitting module Run
  | 2022-06-03T09:51:42.901-04:00 | [2147/2149] Compiling Run main.swift
  | 2022-06-03T09:51:43.158-04:00 | [2150/2151] Wrapping AST for Run for debugging
  | 2022-06-03T09:51:44.624-04:00 | error: link command failed with exit code 1 (use -v to see invocation)
  | 2022-06-03T09:51:44.624-04:00 | /usr/bin/ld.gold: fatal error: out of file descriptors and couldn't close any
  | 2022-06-03T09:51:44.624-04:00 | clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
  | 2022-06-03T09:51:44.729-04:00 | [2150/2151] Linking Run

</pre>

Please let me know if there are known workarounds for this.

**Comment by mkll** [comment]
@aibo-cora Please, tell me why you think this is a Vapor bug? The number of file descriptors is an operating system setting and has nothing to do with the applications you run.

There are about a million recipes on the Internet on how to change this setting.

**Comment by mkll** [comment]
Ok, for Debian:

`/etc/systemd/user.conf`
`/etc/systemd/system.conf`
In the both add the following line in addition to the changes you made in the third file:
`DefaultLimitNOFILE=65536`

`/etc/security/limits.conf` like this:
`user hard nofile 65536`

**Comment by jdmcd** [comment]
We ran into this as well due to the size of our project and a nasty linker bug that exists in Swift right now. Even increasing the `nofile` limit didn't fix it for us. We had to do in `Package.swift`: 

```swift
.executableTarget(
            name: "Run",
            dependencies: [
                .target(name: "App"),
            ],
            linkerSettings: [.unsafeFlags(["-Xlinker", "--no-keep-files-mapped", "-Xlinker", "--no-map-whole-files", "-Xlinker", "--no-mmap-output-file", "-Xlinker", "--no-keep-memory"], .when(platforms: [.linux]))] // Workaround for https://github.com/apple/swift/issues/58380
        ),
```

**Comment by mkll** [comment]
@jdmcd You seem to be talking about excessive memory consumption, not file descriptors, right?

**Comment by jdmcd** [comment]
@gwynne might be able to shine more light as she wrote the solution but that's how we fixed the same error in this issue

**Comment by aibo-cora** [comment]
> We ran into this as well due to the size of our project and a nasty linker bug that exists in Swift right now. Even increasing the `nofile` limit didn't fix it for us. We had to do in `Package.swift`:
> 
> ```swift
> .executableTarget(
>     name: "Run",
>     dependencies: [
>         .target(name: "App"),
>     ],
>     linkerSettings: [.unsafeFlags(["-Xlinker", "--no-keep-files-mapped", "-Xlinker", "--no-map-whole-files", "-Xlinker", "--no-mmap-output-file", "-Xlinker", "--no-keep-memory"], .when(platforms: [.linux]))] // Workaround for https://github.com/apple/swift/issues/58380
> ),
> ```
> 
> Thankfully a partial fix for the linker bug is landing in Swift 5.7

@jdmcd Unfortunately, this did not work for me. There is a discussion on the Swift side with little progress. Here is the issue https://github.com/apple/swift/issues/54348

@mkll I do not think it's a Vapor issue, but since I am trying to deploy a Vapor server, I thought someone might have an insight into the problem I am running into.

**Comment by mkll** [comment]
@aibo-cora Got it. But previously you told that
> Running ulimit -n 65356 did not help

Does this mean you had a lower value at the time of writing and later increased it to 1M+?

And I'm curious, did you try `swift build` instead of `make install`?

**Comment by aibo-cora** [comment]
@mkll, @jdmcd Thanks for having this conversation with me. I managed to find a solution. I was looking for differences between running a local container and AWS. It turns out that there is a way to specify soft and hard <code>NOFILE</code> limits when configuring the container in a task definition.

https://towardsaws.com/how-to-configuring-linux-ulimit-with-docker-and-aws-ecs-599c71f00473
