### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by devcz** [vapor/vapor#2850]
I want to return an array of Content, but the content is different type which conform Content protocol. but I got an error below. I know the Content Protocol can not as a type, however how to achieve return different type.

![CleanShot 2022-06-14 at 18 38 29](https://user-images.githubusercontent.com/71340227/173558874-150fef9b-1913-4b79-aacd-d41a506ebcd8.png)

This is what I want to return.
![CleanShot 2022-06-14 at 18 44 22](https://user-images.githubusercontent.com/71340227/173559710-42dca9f8-3936-48a7-9a42-bebfb618cb40.png)

**Comment by 0xTim** [comment]
This is difficult with Swift as it stands today. What you'll probably need to do is type-erase the array (something like `AnyContent` to make it work

**Comment by devcz** [comment]
OK, thank you very much, I'll try later.

**Comment by 0xTim** [comment]
Will close this - if you get stuck the best place to ask is our [Discord server](http://vapor.team)
