### ISSUE TITLE
Running Vapor with Xcode 13

### ISSUE THREAD

**Issue by LiamAlexanderJones** [vapor/vapor#2851]
I'm just starting out with Vapor and git. It's possible I'm missing some obvious here, but I've poked around the documentation and online and can't find a solution.

I'm using Swift 5.5, Xcode 13.1 and macOS 11.6.7. I'd like to upgrade to macOS 12, but my current machine, being rather old, doesn't support it.

When I install Vapor with homebrew and create a new project following the documentation, I can't run it because it requires Swift 5.6. I've tried changing Package.swift to swift tools version 5.5 and platform .v11, but that just gives me a fleet of errors when I try to build. This happens even using the starter's Hello World project.

In the best possible world, I'd like to be able to use vapor with async/await on my current platform, but as far as I can tell you're dependent on SwiftNIO for that.

My other option is to work without async/await, and update it when I get a new machine. So -- how can I get a Vapor project to do that? If I can make a change to the current download, what do I change? If I need to download an earlier version, how do I do that?

**Comment by 0xTim** [comment]
Vapor does not support async/await on macOS 11. If you're starting out you can clone an older version of the template as described in https://blog.vapor.codes/posts/updating-template-to-async-await/ and then use futures.

To be able to use async/await you have a few options, the best being use Docker and VSCode with the Swift extension
