### ISSUE TITLE
Can't Run on macOS app.

### ISSUE THREAD

**Issue by GlobalGayhub** [vapor/vapor#2860]
Hi, I wan to run Vapor on my macOS app, but I encountered this error.
<img width="1400" alt="fail" src="https://user-images.githubusercontent.com/12987627/180181191-def1152a-e6b8-40de-91f9-bbff34120b1f.png">

I don't know what to do, if you have time, please help me check.
This is my demo:
[VaporServerExample.zip](https://github.com/vapor/vapor/files/9158143/VaporServerExample.zip)

Thanks!

**Comment by 0xTim** [comment]
Can you show the actual error - the one that's in `error` that's cut off in the variable panel?

**Comment by vzsg** [comment]
Alternatively, remove `.localizedDescription` to print out the _real_ description of the error, and share that outcome.

**Comment by GlobalGayhub** [comment]
Thanks so much! It worl well when I **unselect** this **Document Versions** option.
