### ISSUE TITLE
TLS PSK support

### ISSUE THREAD

**Issue by GP89** [vapor/vapor#2862]
It looks like swift-nio is quite close to merging support for TLS PSK (https://github.com/apple/swift-nio-ssl/pull/369). I was curious what level of effort / changes would be needed to bring PSK support to vapor once support has been added there? Is it something that is likely to see support in vapor?

**Comment by 0xTim** [comment]
Vapor takes a `TLSConfiguration` and passes it directly to NIOSSL (https://docs.vapor.codes/advanced/server/#tls) so it looks like we should support it out of the box as soon as it's released

**Comment by Joannis** [comment]
@0xTim can we close this?

**Comment by Joannis** [comment]
Actually - I think it's safe. I'm closing this. Reopen if it's a mistake
