### ISSUE TITLE
Using decode to handle large file uploads can be very slow.

### ISSUE THREAD

**Issue by GlobalGayhub** [vapor/vapor#2864]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/12987627/182285989-44fed7fc-4fc8-47af-b36b-0663df01af1c.png">

Hi, 
I just uploaded a 6 MB file, but it took 12 seconds in the `req.content.decode(Input.self)` method, which is really slow.
Is there any way to solve this problem? Or is there an alternative?

**Comment by 0xTim** [comment]
@GlobalGayhub make sure you're running a release build and not a debug build - the decoder is orders of magnitude quicker

**Comment by GlobalGayhub** [comment]
Oh~ That's amazing!  I test it, you are right! Thanks so much!
