### ISSUE TITLE
docker-compose up app  can't connect MongoDB.

### ISSUE THREAD

**Issue by dushandz** [vapor/vapor#2869]
### Describe the bug
When i run vapor project, i can connnect to MongoDB.
But after i `docker-compose build` and run `docker-compose up app`, i got error like this:
<img width="2189" alt="截屏2022-08-11 23 00 35" src="https://user-images.githubusercontent.com/14211720/184164846-9382b2e2-21db-43d0-a398-58cc18ffeb02.png">

this is my docker-compose.yaml:
`version: '3.7'

volumes:
  db_data:
x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}
  DATABASE_URL: ${DATABASE_URL}
  
services:
  app:
    image: switch-game-hime:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  migrate:
    image: switch-game-hime:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--yes"]
    deploy:
      replicas: 0
  revert:
    image: switch-game-hime:latest
    build:
      context: .
    environment:
      <<: *shared_environment
    depends_on:
      - db
    command: ["migrate", "--revert", "--yes"]
    deploy:
      replicas: 0
  db:
    image: mongo:4.4
    volumes:
      - db_data:/data/db
    restart: unless-stopped
    ports:
      - '27017:27017'
`
plz, help. First i used postgreSQL. Met same kind error. Can not connect to postgreSQLDB. Then i changed to mongoDB.
But when i just run in Xcode or VScode, it worked, same mongoDB image in same container of Docker.

### Environment

* Vapor Framework version: 4.0.0
* Vapor Toolbox version:18.5.1
* OS version: Mac 12.5 Intel

**Comment by 0xTim** [comment]
Your `DATABASE_URL` should be `mongodb://db:27017/vapor_database`. If you generate a new project from the template you'll see the correct data

**Comment by dushandz** [comment]
> Your `DATABASE_URL` should be `mongodb://db:27017/vapor_database`. If you generate a new project from the template you'll see the correct data

OK. That' work fo me. By the way, what should i do, if i want mongoDB run witch Auth. For Example, i  want to my App connect mongoDB with role admin, db admin, when i use ` mongodb://admin:123456@db:27017/admin` for `DATABASE_URL ` it connect failed.

**Comment by 0xTim** [comment]
Looks like you need to do it with environment variables https://stackoverflow.com/a/42973849/1823705

**Comment by dushandz** [comment]
> Looks like you need to do it with environment variables https://stackoverflow.com/a/42973849/1823705

Thx again old sport~
