### ISSUE TITLE
Only receiving first chunk of data using FileMiddleware server

### ISSUE THREAD

**Issue by GP89** [vapor/vapor#2871]
### Describe the bug

Only receiving first chunk of data receiving from `FileMiddleware` static server.

This could well be due to the way I'm using Network.framework as a test client, but I'm really not sure where the problem lies.

### To Reproduce

I created a test project that demonstates the behaviour: [TestStaticServer](https://github.com/GP89/TestStaticServer)

1. Run TestStaticServer target
2. Run Downloader target
3. Client only receives (for me) first chunk of data (174bytes) then no more

### Expected behavior

Receive should keep receiving data until the whole file is sent (~3kb)

### Environment

* Vapor Framework version: main branch
* Vapor Toolbox version: ?
* OS version: 12.3.1

**Comment by GP89** [comment]
Hey so I make a stupid mistake in that example! I was using `strlen` to get the message size, which is only the size until the first null byte 🤦 . So can confirm all the data is being received. 
However the client is still sitting on receive though expecting more data as `is_complete` doesn't come back as true. I'm not sure where / what the problem could be there

**Comment by vzsg** [comment]
According to the Network.framework docs, if you're doing raw, unbounded TCP, `is_complete` will only be true if the other side closes the connection. In HTTP 1.1, connections are persistent by default, meaning that the server will not close the connection at the end of the response.

You could change the request line to say `HTTP/1.0`, or add a `Connection: close` header to the request, and it should be closed automatically by the server. (Or you could just use a real HTTP client instead?)

**Comment by GP89** [comment]
Ah thank you!! Sorry I'll close this off.

I needed something that used tls psk and plain tcp was the only way I could find in objective-c.

**Comment by GP89** [comment]
Hey I've just tried with `HTTP/1.0` and with `Connection: close` but I'm still seeing the same behaviour. Gets all the data and sites on state 3 (ready) waiting to receive again

**Comment by 0xTim** [comment]
Do you get the same behaviour when serving the file from something like Nginx?
