### ISSUE TITLE
I'm missing test now. Please Help me ASAP!!

### ISSUE THREAD

**Issue by RIRUa** [vapor/vapor#2880]
### Code
this is target.
```
func create(req: Request) async throws -> Response {
        var body: Arg
        do {
            body = try req.content.decode(Arg.self)
        } catch {
            print(error.localizedDescription)
            throw errorBinding(err: error)
        }
       ~~~~~~~~~~
       ~~~~~~~~~~
}
```

this is test-code.
```
struct Arg: content{ ~~~~ }
struct Result: content{ ~~~ }

var arg = Arg( ~~~ )
var want = Result( ~~~ )

                try await app.test(
                    .POST,
                    "admin",
                    beforeRequest: { req async throws in
                        try req.content.encode(arg)
                    },
                    afterResponse: { resp async throws in
                        let body = try resp.content.decode(Result.self)
                        XCTAssertEqual(body, want)
                    }
                )
```

### this Error message
データが見つからないため、読み込めませんでした。（JP）
Could not read because no data was found.（EN）

## PS
If not enough infomation. I'll write.

**Comment by Kyle-Ye** [comment]
Could you please provide more information? 

For example, the zip package or core code of a minimal **reproducible** environment.

**Comment by RIRUa** [comment]
> Could you please provide more information? 
> 
> 
> 
> For example, the zip package or core code of a minimal **reproducible** environment.

OK!I'll send it after 4 hours.

**Comment by Sherlouk** [comment]
Did you figure out a solution for your problem here @RIRUa, or are you still planning on sending across a minimal project enabling us to help fix your errors?

**Comment by RIRUa** [comment]
I have already fixed it. I close it.
