### ISSUE TITLE
My programs always get stuck on this line when they compile

### ISSUE THREAD

**Issue by zhtut** [vapor/vapor#2885]
### Describe the bug

My application works fine on MAC OS, but it gets stuck on Ubuntu, Then my AWS server crashes and I have to go to the console to restart it to make it work. I've tried it many times But the result is the same.
Please help me analyze the reason.

My project address is: https://github.com/zhtut/Server/tree/main/ProductManager

### Environment

* Vapor Framework version: 4.65.1
* Vapor Toolbox version: 18.5.1
* OS version: aws ubuntu 20.04，t2.macro, 1vcpu, 1G Memory

### Additional context

build log:
swift build -c release
Fetching https://github.com/apple/swift-atomics.git from cache
Fetched https://github.com/apple/swift-atomics.git (0.47s)
Fetching https://github.com/vapor/leaf.git from cache
Fetched https://github.com/vapor/leaf.git (0.33s)
Fetching https://github.com/swift-server/swift-backtrace.git from cache
Fetched https://github.com/swift-server/swift-backtrace.git (0.32s)
Fetching https://github.com/apple/swift-nio-http2.git from cache
Fetched https://github.com/apple/swift-nio-http2.git (0.41s)
Fetching https://github.com/apple/swift-algorithms.git from cache
Fetched https://github.com/apple/swift-algorithms.git (0.36s)
Fetching https://github.com/vapor/postgres-nio.git from cache
Fetched https://github.com/vapor/postgres-nio.git (0.36s)
Fetching https://github.com/apple/swift-numerics from cache
Fetched https://github.com/apple/swift-numerics (0.34s)
Fetching https://github.com/vapor/fluent.git from cache
Fetched https://github.com/vapor/fluent.git (0.40s)
Fetching https://github.com/vapor/fluent-kit.git from cache
Fetched https://github.com/vapor/fluent-kit.git (0.38s)
Fetching https://github.com/apple/swift-metrics.git from cache
Fetched https://github.com/apple/swift-metrics.git (0.33s)
Fetching https://github.com/vapor/routing-kit.git from cache
Fetched https://github.com/vapor/routing-kit.git (0.42s)
Fetching https://github.com/apple/swift-nio.git from cache
Fetched https://github.com/apple/swift-nio.git (0.97s)
Fetching https://github.com/apple/swift-crypto.git from cache
Fetched https://github.com/apple/swift-crypto.git (0.38s)
Fetching https://github.com/apple/swift-log.git from cache
Fetched https://github.com/apple/swift-log.git (0.35s)
Fetching https://github.com/vapor/websocket-kit.git from cache
Fetched https://github.com/vapor/websocket-kit.git (0.34s)
Fetching https://github.com/apple/swift-nio-ssl.git from cache
Fetched https://github.com/apple/swift-nio-ssl.git (0.42s)
Fetching https://github.com/vapor/async-kit.git from cache
Fetched https://github.com/vapor/async-kit.git (0.35s)
Fetching https://github.com/swift-server/async-http-client.git from cache
Fetched https://github.com/swift-server/async-http-client.git (0.40s)
Fetching https://github.com/apple/swift-collections.git from cache
Fetched https://github.com/apple/swift-collections.git (0.45s)
Fetching https://github.com/apple/swift-nio-transport-services.git from cache
Fetched https://github.com/apple/swift-nio-transport-services.git (0.34s)
Fetching https://github.com/vapor/sql-kit.git from cache
Fetched https://github.com/vapor/sql-kit.git (0.34s)
Fetching https://github.com/apple/swift-nio-extras.git from cache
Fetched https://github.com/apple/swift-nio-extras.git (0.34s)
Fetching https://github.com/vapor/multipart-kit.git from cache
Fetched https://github.com/vapor/multipart-kit.git (0.55s)
Fetching https://github.com/zhtut/SSCommon.git from cache
Fetched https://github.com/zhtut/SSCommon.git (0.32s)
Fetching https://github.com/zhtut/CommonApi.git from cache
Fetched https://github.com/zhtut/CommonApi.git (0.35s)
Fetching https://github.com/vapor/postgres-kit.git from cache
Fetched https://github.com/vapor/postgres-kit.git (0.35s)
Fetching https://github.com/vapor/console-kit.git from cache
Fetched https://github.com/vapor/console-kit.git (0.34s)
Fetching https://github.com/vapor/leaf-kit.git from cache
Fetched https://github.com/vapor/leaf-kit.git (0.35s)
Fetching https://github.com/vapor/fluent-postgres-driver.git from cache
Fetched https://github.com/vapor/fluent-postgres-driver.git (0.34s)
Fetching https://github.com/vapor/vapor.git from cache
Fetched https://github.com/vapor/vapor.git (0.62s)
Computing version for https://github.com/zhtut/CommonApi.git
Computed https://github.com/zhtut/CommonApi.git at 1.0.1 (1.32s)
Computing version for https://github.com/zhtut/SSCommon.git
Computed https://github.com/zhtut/SSCommon.git at 1.1.0 (0.22s)
Computing version for https://github.com/vapor/leaf.git
Computed https://github.com/vapor/leaf.git at 4.2.1 (0.23s)
Computing version for https://github.com/vapor/fluent-postgres-driver.git
Computed https://github.com/vapor/fluent-postgres-driver.git at 2.4.0 (0.23s)
Computing version for https://github.com/vapor/fluent.git
Computed https://github.com/vapor/fluent.git at 4.5.0 (0.23s)
Computing version for https://github.com/vapor/vapor.git
Computed https://github.com/vapor/vapor.git at 4.65.1 (0.28s)
Computing version for https://github.com/vapor/leaf-kit.git
Computed https://github.com/vapor/leaf-kit.git at 1.8.0 (0.22s)
Computing version for https://github.com/vapor/postgres-kit.git
Computed https://github.com/vapor/postgres-kit.git at 2.8.2 (0.22s)
Computing version for https://github.com/vapor/fluent-kit.git
Computed https://github.com/vapor/fluent-kit.git at 1.35.1 (0.24s)
Computing version for https://github.com/vapor/async-kit.git
Computed https://github.com/vapor/async-kit.git at 1.13.0 (0.22s)
Computing version for https://github.com/vapor/multipart-kit.git
Computed https://github.com/vapor/multipart-kit.git at 4.5.2 (0.21s)
Computing version for https://github.com/vapor/websocket-kit.git
Computed https://github.com/vapor/websocket-kit.git at 2.6.1 (0.23s)
Computing version for https://github.com/apple/swift-algorithms.git
Computed https://github.com/apple/swift-algorithms.git at 1.0.0 (0.23s)
Computing version for https://github.com/apple/swift-metrics.git
Computed https://github.com/apple/swift-metrics.git at 2.3.2 (0.28s)
Computing version for https://github.com/apple/swift-log.git
Computed https://github.com/apple/swift-log.git at 1.4.4 (0.22s)
Computing version for https://github.com/apple/swift-nio-extras.git
Computed https://github.com/apple/swift-nio-extras.git at 1.12.1 (0.25s)
Computing version for https://github.com/apple/swift-nio-http2.git
Computed https://github.com/apple/swift-nio-http2.git at 1.22.1 (0.24s)
Computing version for https://github.com/apple/swift-nio-ssl.git
Computed https://github.com/apple/swift-nio-ssl.git at 2.21.0 (0.28s)
Computing version for https://github.com/apple/swift-nio.git
Computed https://github.com/apple/swift-nio.git at 2.41.1 (0.35s)
Computing version for https://github.com/swift-server/swift-backtrace.git
Computed https://github.com/swift-server/swift-backtrace.git at 1.3.3 (0.21s)
Computing version for https://github.com/vapor/routing-kit.git
Computed https://github.com/vapor/routing-kit.git at 4.6.0 (0.23s)
Computing version for https://github.com/apple/swift-crypto.git
Computed https://github.com/apple/swift-crypto.git at 2.1.0 (0.26s)
Computing version for https://github.com/vapor/console-kit.git
Computed https://github.com/vapor/console-kit.git at 4.5.0 (0.24s)
Computing version for https://github.com/swift-server/async-http-client.git
Computed https://github.com/swift-server/async-http-client.git at 1.11.5 (0.25s)
Computing version for https://github.com/apple/swift-atomics.git
Computed https://github.com/apple/swift-atomics.git at 1.0.2 (0.22s)
Computing version for https://github.com/vapor/sql-kit.git
Computed https://github.com/vapor/sql-kit.git at 3.21.0 (0.22s)
Computing version for https://github.com/vapor/postgres-nio.git
Computed https://github.com/vapor/postgres-nio.git at 1.11.0 (0.25s)
Computing version for https://github.com/apple/swift-collections.git
Computed https://github.com/apple/swift-collections.git at 1.0.2 (0.25s)
Computing version for https://github.com/apple/swift-nio-transport-services.git
Computed https://github.com/apple/swift-nio-transport-services.git at 1.13.1 (0.22s)
Computing version for https://github.com/apple/swift-numerics
Computed https://github.com/apple/swift-numerics at 1.0.2 (0.23s)
Creating working copy for https://github.com/apple/swift-metrics.git
Working copy of https://github.com/apple/swift-metrics.git resolved at 2.3.2
Creating working copy for https://github.com/apple/swift-numerics
Working copy of https://github.com/apple/swift-numerics resolved at 1.0.2
Creating working copy for https://github.com/vapor/leaf.git
Working copy of https://github.com/vapor/leaf.git resolved at 4.2.1
Creating working copy for https://github.com/apple/swift-atomics.git
Working copy of https://github.com/apple/swift-atomics.git resolved at 1.0.2
Creating working copy for https://github.com/apple/swift-nio-transport-services.git
Working copy of https://github.com/apple/swift-nio-transport-services.git resolved at 1.13.1
Creating working copy for https://github.com/vapor/vapor.git
Working copy of https://github.com/vapor/vapor.git resolved at 4.65.1
Creating working copy for https://github.com/apple/swift-nio.git
Working copy of https://github.com/apple/swift-nio.git resolved at 2.41.1
Creating working copy for https://github.com/zhtut/CommonApi.git
Working copy of https://github.com/zhtut/CommonApi.git resolved at 1.0.1
Creating working copy for https://github.com/vapor/console-kit.git
Working copy of https://github.com/vapor/console-kit.git resolved at 4.5.0
Creating working copy for https://github.com/apple/swift-nio-extras.git
Working copy of https://github.com/apple/swift-nio-extras.git resolved at 1.12.1
Creating working copy for https://github.com/zhtut/SSCommon.git
Working copy of https://github.com/zhtut/SSCommon.git resolved at 1.1.0
Creating working copy for https://github.com/swift-server/swift-backtrace.git
Working copy of https://github.com/swift-server/swift-backtrace.git resolved at 1.3.3
Creating working copy for https://github.com/vapor/websocket-kit.git
Working copy of https://github.com/vapor/websocket-kit.git resolved at 2.6.1
Creating working copy for https://github.com/apple/swift-crypto.git
Working copy of https://github.com/apple/swift-crypto.git resolved at 2.1.0
Creating working copy for https://github.com/swift-server/async-http-client.git
Working copy of https://github.com/swift-server/async-http-client.git resolved at 1.11.5
Creating working copy for https://github.com/apple/swift-log.git
Working copy of https://github.com/apple/swift-log.git resolved at 1.4.4
Creating working copy for https://github.com/apple/swift-nio-ssl.git
Working copy of https://github.com/apple/swift-nio-ssl.git resolved at 2.21.0
Creating working copy for https://github.com/vapor/leaf-kit.git
Working copy of https://github.com/vapor/leaf-kit.git resolved at 1.8.0
Creating working copy for https://github.com/vapor/multipart-kit.git
Working copy of https://github.com/vapor/multipart-kit.git resolved at 4.5.2
Creating working copy for https://github.com/apple/swift-collections.git
Working copy of https://github.com/apple/swift-collections.git resolved at 1.0.2
Creating working copy for https://github.com/vapor/postgres-kit.git
Working copy of https://github.com/vapor/postgres-kit.git resolved at 2.8.2
Creating working copy for https://github.com/vapor/postgres-nio.git
Working copy of https://github.com/vapor/postgres-nio.git resolved at 1.11.0
Creating working copy for https://github.com/apple/swift-nio-http2.git
Working copy of https://github.com/apple/swift-nio-http2.git resolved at 1.22.1
Creating working copy for https://github.com/vapor/async-kit.git
Working copy of https://github.com/vapor/async-kit.git resolved at 1.13.0
Creating working copy for https://github.com/vapor/fluent-postgres-driver.git
Working copy of https://github.com/vapor/fluent-postgres-driver.git resolved at 2.4.0
Creating working copy for https://github.com/vapor/sql-kit.git
Working copy of https://github.com/vapor/sql-kit.git resolved at 3.21.0
Creating working copy for https://github.com/apple/swift-algorithms.git
Working copy of https://github.com/apple/swift-algorithms.git resolved at 1.0.0
Creating working copy for https://github.com/vapor/fluent-kit.git
Working copy of https://github.com/vapor/fluent-kit.git resolved at 1.35.1
Creating working copy for https://github.com/vapor/fluent.git
Working copy of https://github.com/vapor/fluent.git resolved at 4.5.0
Creating working copy for https://github.com/vapor/routing-kit.git
Working copy of https://github.com/vapor/routing-kit.git resolved at 4.6.0
Building for production...
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-nio/Sources/PostgresNIO/Connection/PostgresConnection.swift:382:30: warning: 'NIOAtomic' is deprecated: please use ManagedAtomic from https://github.com/apple/swift-atomics instead
    static let idGenerator = NIOAtomic.makeAtomic(value: 0)
                             ^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-nio/Sources/PostgresNIO/Data/PostgresData.swift:2:17: remark: '@preconcurrency' attribute on module 'NIOCore' is unused
@preconcurrency import NIOCore
~~~~~~~~~~~~~~~~^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-nio/Sources/PostgresNIO/Data/PostgresRow.swift:2:17: remark: '@preconcurrency' attribute on module 'NIOCore' is unused
@preconcurrency import NIOCore
~~~~~~~~~~~~~~~~^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-nio/Sources/PostgresNIO/New/Messages/DataRow.swift:2:17: remark: '@preconcurrency' attribute on module 'NIOCore' is unused
@preconcurrency import NIOCore
~~~~~~~~~~~~~~~~^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-nio/Sources/PostgresNIO/New/PostgresCell.swift:2:17: remark: '@preconcurrency' attribute on module 'NIOCore' is unused
@preconcurrency import NIOCore
~~~~~~~~~~~~~~~~^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-kit/Sources/PostgresKit/PostgresConnectionSource.swift:58:39: warning: 'connect(to:tlsConfiguration:serverHostname:logger:on:)' is deprecated: Use the new connect method that allows you to connect and authenticate in a single step
            return PostgresConnection.connect(
                                      ^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-kit/Sources/PostgresKit/PostgresConnectionSource.swift:58:39: note: use 'connect(on:configuration:id:logger:)' instead
            return PostgresConnection.connect(
                                      ^~~~~~~
                                      connect
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-kit/Sources/PostgresKit/PostgresConnectionSource.swift:65:29: warning: 'authenticate(username:database:password:logger:)' is deprecated: Use the new connect method that allows you to connect and authenticate in a single step
                return conn.authenticate(
                            ^
/home/ubuntu/Server/ProductManager/.build/checkouts/postgres-kit/Sources/PostgresKit/PostgresConnectionSource.swift:65:29: note: use 'connect(on:configuration:id:logger:)' instead
                return conn.authenticate(
                            ^~~~~~~~~~~~
                            connect
[959/961] Compiling AsyncHTTPClient HTTPClient+execute.swift

**Comment by vzsg** [comment]
> 1G Memory

That's nowhere near enough for the Swift toolchain.
You need to use larger VMs with more RAM, and enable swap while you're there.

**Comment by zhtut** [comment]
Thanks for the answer, and it worked
