### ISSUE TITLE
Fix handling of uppercase domain names when validating email addresses

### ISSUE THREAD

**Issue by gwynne** [vapor/vapor#2889]
`Validator.email` misbehaves when asked to validate an email address whose domain name contains uppercase characters. The address will be reported as invalid, which is not correct by spec (lowercase is the recommended canonical form, but isn't an actual requirement). See https://github.com/vapor/vapor/blob/main/Sources/Vapor/Validation/Validators/Email.swift#L56

The correct fix is for the regular expression to either allow uppercase, or, preferably, be replaced with something that's not guaranteed to have other issues 🙂.

**Comment by BennyDeBock** [comment]
I'll take a look at this soon if you don't mind @gwynne

**Comment by BennyDeBock** [comment]
I've solved this, but i'll contribute the fix in a demo i'm planning to give. Just a bit more time for this one 😅

**Comment by 0xTim** [comment]
@BennyDeBock was this ever submitted?
