### ISSUE TITLE
Does template docker deployment configuration include .env.* files? 

### ISSUE THREAD

**Issue by olegbragin** [vapor/vapor#2890]
I tried to use docker to deploy the newly generated app. Did not change anything in the files, only added .env.production.
The docker image itself built ok, the app runs, but then throws an error:
[ DEBUG ] Could not load .env.production file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/DotEnv.swift:120)
[ DEBUG ] Could not load .env file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/DotEnv.swift:120)

From the error I get the .env files is missing, but I can't figure out how to add those. 
Has anyone faced something like these?

**Comment by 0xTim** [comment]
@olegbragin it does not. It's not good practice to use `.env` files with Docker images as you bake secrets into the container which makes them insecure. You should pass them in as environment variables when you run the container instead.

If you really want to use a `.env` file you'll need to copy it from the build image to the run image, similar to how the `Resources` directory is copied
