### ISSUE TITLE
Buliding for debug...

### ISSUE THREAD

**Issue by wieczorek1990** [vapor/vapor#2902]
I am seeing this text:

_Buliding for debug..._

when running with:

_vapor server --env production_

Previous step was:

_swift build_

Can I somehow disable the debug build?

**Comment by 0xTim** [comment]
By default `swift build` builds a debug executable. If you want to build a release build you can do `swift build -c release`

**Comment by vzsg** [comment]
When you're running the app, you also have to specify that you want to run the release executable. Best forget the `vapor` command, you can use this instead with the added benefit of rebuilding the executable if there were any changes before starting it:

```
swift run -c release Run serve --env production
```

**Comment by 0xTim** [comment]
Yeah would be good to see how you're actually running the app, there's no `vapor server` command so I took that as you were running the executable directly

**Comment by wieczorek1990** [comment]
So this is my Dockerfile:

```
FROM fedora:36

# Install requirements

RUN dnf install -y\
 @development-tools\
 git\
 libstdc++-static\
 swift-lang\
 which

# Install Vapor Toolbox

ENV VAPOR_TOOLBOX_VERSION=18.6.0

WORKDIR /srv/

RUN git clone https://github.com/vapor/toolbox.git &&\
 cd toolbox &&\
 git checkout $VAPOR_TOOLBOX_VERSION &&\
 make install &&\
 cd .. &&\
 rm -rf toolbox

# Project related

RUN mkdir -p /srv/sledzik/

WORKDIR /srv/sledzik/

COPY ./Package.swift ./

RUN swift package resolve

COPY ./ ./

RUN swift build -c release --static-swift-stdlib

CMD vapor run serve --env production --hostname 0.0.0.0 --port 8080

```

**Comment by 0xTim** [comment]
You don't need the toolbox, you can replace the command with

```docker
CMD swift run -c release Run serve --env production --hostname 0.0.0.0 --port 8080
```

You can even slim down the images a use static linking to allow you to remove the Swift runtime from the final image - see https://github.com/vapor/template-bare/blob/main/Dockerfile#L26

**Comment by wieczorek1990** [comment]
Yes, I used that in Dockerfile.
Thanks for the tips.

W dniu pon., 24.10.2022 o 16:14 Tim Condon ***@***.***>
napisał(a):

**Comment by wieczorek1990** [comment]
I changed the Dockerfile to:

```
FROM fedora:36

ARG PROJECT_NAME

RUN dnf install -y\
 git\
 libstdc++-static\
 swift-lang\
 zlib-devel

RUN mkdir -p /srv/${PROJECT_NAME}/
WORKDIR /srv/${PROJECT_NAME}/

COPY ./Package.swift ./
RUN swift package resolve

COPY ./ ./
RUN swift build -c release --static-swift-stdlib

CMD swift run -c release Run serve --env production --hostname 0.0.0.0 --port 8080
```

Now I see:

```
Building for production...
```

I thought that if I build first the run should not compile but it does.
What to do?

**Comment by wieczorek1990** [comment]
So I uderstand that if I use same set of flags it will not rebuild. Thanks.

W dniu wt., 25.10.2022 o 14:42 Tim Condon ***@***.***>
napisał(a):

**Comment by vzsg** [comment]
Ideally, you could use the [Dockerfile provided by Vapor](https://github.com/vapor/template-bare/blob/main/Dockerfile) that makes smaller images and solves a lot of issues in the meantime.

Or, take a look at [this comment](https://github.com/apple/swift-package-manager/issues/4651#issuecomment-1116966497) about how to set up the build cache in the Dockerfile.

**Comment by wieczorek1990** [comment]
I want to use Fedora. Thanks. Will copy the executable and delete the build
directory.

W dniu wt., 25.10.2022 o 14:57 Zsolt Váradi ***@***.***>
napisał(a):

**Comment by vzsg** [comment]
> Will copy the executable and delete the build directory.

That wasn't exactly the point, especially with the cache mount, but go ahead.
