### ISSUE TITLE
Collecting the request body sometimes hangs

### ISSUE THREAD

**Issue by tancred** [vapor/vapor#2906]
### Describe the bug

A route that `.collect`s a request body hangs under certain conditions.

### To Reproduce

Download the attached Vapor project [hanging-collector.zip](https://github.com/vapor/vapor/files/9968465/hanging-collector.zip) and unpack it. Then follow the instructions in`readme.md` that's found in the root of the project. I've copied most of the instructions here.

#### Prepare
 
1. Start the app:

```
$ swift run Run serve --port 7687
```

2. Upload the sample image:

```
$ curl -i -T ./sample.jpg -X PUT http://127.0.0.1:7687/hanger
```

This should work out ok: there's a copy of `sample.jpg` in `/tmp/pix/hanger`.

#### Reproduce the hang

1. Start the app

```
$ swift run Run serve --port 7687
```

2. GET the image

```
curl -i http://127.0.0.1:7687/hanger
```

3. PUT the image

```
$ curl -i -T ./sample.jpg -X PUT http://127.0.0.1:7687/hanger
```

Often this will be enough. The vapor app has logged the PUT request but `curl` will now hang, and running `lsof -i -nP` will show the open connection:

```
$ lsof -i -nP
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
...
Run       22462 malte   12u  IPv4 0xd3a42b18da250499      0t0  TCP 127.0.0.1:7687 (LISTEN)
Run       22462 malte   13u  IPv4 0xd3a42b18da24e4d1      0t0  TCP 127.0.0.1:7687->127.0.0.1:55955 (ESTABLISHED)
curl      22503 malte    6u  IPv4 0xd3a42b18d947ef69      0t0  TCP 127.0.0.1:55955->127.0.0.1:7687 (ESTABLISHED)
```

Stopping the app now takes some time. After about 10 seconds the app quits with the following message:

```
[ ERROR ] Could not stop HTTP server: Abort.500: Server stop took too long.
ERROR: Cannot schedule tasks on an EventLoop that has already shut down. This will be upgraded to a forced crash in future SwiftNIO versions.
```

The hang is intermittent. I often have to retry from step 1 for the hang to occur. It's important that the app is restarted!

### Expected behavior

The PUT request should never hang.

### Environment

* Vapor Framework version: 4.67.1
* Vapor Toolbox version: 18.6.0
* OS version: macOS 12.6.1 (21G217)

```
$ swift --version
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx12.0
```

I'm on an M2 MacBook Air running Xcode Version 14.1 (14B47b).

**Comment by tancred** [comment]
Ok, and here's the file. Neither `tar.bz2` nor `.tgz` worked out apparently, but here's a `.zip` at least!

[hanging-collector.zip](https://github.com/vapor/vapor/files/9963078/hanging-collector.zip)

**Comment by tancred** [comment]
* I updated the sample project.
* The bug desription now includes most of the text from the readme file in the sample project
* The sample project is linked from the bug description above (I deleted my comment that held the original sample download).

**Comment by tancred** [comment]
I think so!

I noticed the release but haven't had time to check my example yet. I'll have time tomorrow afternoon (Swedish time).

**Comment by 0xTim** [comment]
Yes this was fixed in [4.67.3](https://github.com/vapor/vapor/releases/tag/4.67.3) - I'll close this but feel free to reopen if it's still an issue!

**Comment by tancred** [comment]
Finally got around to test a bit and I still see the hang unfortunately.

I don't know the internals of NIO and Vapor well enough to know where to start searching in the code. I can only guess, and I can describe the symptoms. Here's a way to trigger the hang more reliably:

First restart the server. Then run

```bash
( curl -i http://127.0.0.1:7687/hanger > /dev/null & ) && curl -i -T ./sample.jpg -X PUT http://127.0.0.1:7687/hanger
```

Here the GET runs in the background and the PUT is started in parallel. For me this triggers the bug more often than when I run the two commands sequentially.

My first thought was that this had something todo with how the handlers process the file data. For example, the GET handler uses `request.fileio.streamFile` while the PUT collects the complete input as a `Data` and then writes it atomically to disk. Maybe `streamFile` and `Data.write` interacts in strange ways?

I noticed that `streamFile` stats the file for some metadata before it opens it and starts reading. To avoid a race between the GET and PUT handlers, where the latter would replace the file before the former started reading it but after stat'ing for metadata, I adopted a version of `streamFile` that opens the file directly and then gathers metadata using an `fstat` on the open file descriptor.

This excursion didn't pay off though; still hangs.

Then I realized it might not have to do with the file at all, but with how `streamFile` works. Here's a command that triggers the bug as reliably as the one above:

```bash
( curl -i http://127.0.0.1:7687/hanger > /dev/null & ) && curl -i -T ./sample.jpg -X PUT http://127.0.0.1:7687/hanger2
```

Here we GET the file `hanger` and PUT the file `hanger2`. So, it's not about the specific file apparently. Could still be a problem with `streamFile` though. So, I replaced

```swift
    return request.fileio.streamFile (at: fileUrl.path, mediaType: .binary)
```

with

```swift
    let data = try Data(contentsOf: fileUrl)
    return Response(status: .ok, body: .init(data: data))
```

but to no avail. I still see the hang.

I've also put a bunch of `Darwin.puts(...); Darwin.fflush(Darwin.stdout)` here and there (Fortran FTW!) and when the hang occurs I only ever see output from the GET handler, never the PUT handler. If this fortran debugging inidactes anything it's that the problem occurs directly after a cold boot when both a GET and a PUT request (i.e., an empty and a non-empty req) are received.

**Comment by tancred** [comment]
When I run the server in Xcode and pause for debugging on hang, I see no difference in any of the threads compared to an idle server with no hang. It's as if the request/connection has just disappeared (like a case where a promise is never completed).

**Comment by tancred** [comment]
I bumped the deps to vapor 4.67.4 when running these tests.

**Comment by Joannis** [comment]
Hey @tancred , I've ran the tests over 100 times on my system but cannot for the life of me reproduce it. Do you have more details about your development system/environment?

**Comment by tancred** [comment]
> Hey @tancred , I've ran the tests over 100 times on my system but cannot for the life of me reproduce it.

Hmm, and you restart the app between each try?

> Do you have more details about your development system/environment?

Well, I'm not sure what else there is to say. I've run this on an M2 Air (the specs in the original report above) and on an M1 13" MacBook Pro from 2020. They both run Monterey, Xcode 14.1 and (an up-to-date) homebrew.

🤔🤔🤔

**Comment by Joannis** [comment]
No, I ran the app twice and kept sending requests against the same instance over & over. We have the same specs, so that's not it. Should I restart Vapor for every attempt?

**Comment by tancred** [comment]
Yes, it's only after a fresh start that the hang occurs!

And it's important that the first request is a GET, then the PUT with the payload.

**Comment by Joannis** [comment]
How often does this happen for you?

**Comment by Joannis** [comment]
Ah,  I just got it. I can reproduce it.

**Comment by Joannis** [comment]
I found that your method never exited - seems like a Foundation issue.

```swift
    func upload (request: Request) async throws -> Response {
        guard let fname = request.parameters.get ("fname") else {
            print("Missing fname")
            throw Abort (.badRequest, reason: "Missing fname")
        }

        try FileManager.default.createDirectory (at: storageUrl, withIntermediateDirectories: true)

        guard let buffer = request.body.data, let data = buffer.getData(at: 0, length: buffer.readableBytes) else {
            print("No body")
            throw Abort (.badRequest, reason: "No body in request")
        }

        let fileUrl: URL = storageUrl.appendingPathComponent (fname)

        try data.write(to: fileUrl, options: .atomic)

        print("Written file")
        
        return Response(status: .created)
    }
```

In this method, none of the logs triggered. That leads me to believe it hung in createDirectory or the write data call.

**Comment by Joannis** [comment]
Some more info; the route was never called in the first place. This happens when accepting/reading the request.

**Comment by Joannis** [comment]
This happens during collecting data, the stream never gets a single chunk read.

**Comment by Joannis** [comment]
Found it, I'll try to make a patch.

**Comment by Joannis** [comment]
Let me know if this PR fixes it for you  @tancred

**Comment by tancred** [comment]
Yes, it sure does!

I've run the test sequence _many_ times against the `feature/jo-lost-chunks` branch and can't reproduce the hang. Switching back to 4.67.4 and the bug triggers immediately.

Fenomenal! 🎉
