### ISSUE TITLE
Decode input throws Abort.422 and falls through

### ISSUE THREAD

**Issue by OurBigAdventure** [vapor/vapor#2915]
### Issue

When accepting POST input and trying `try request.content.decode(Input.self)` where Input expects `String` values, Vapor is throwing Abort.422 if a value is empty.  It also falls through as if an error was not thrown.

Changing the expected value to `String?` has the same behavior.

### To Reproduce

1. Create a post route
2. Create a model such as:
   `struct Input: Content {
          var title: String
        }`
3. Decode the post body with: `try request.content.decode(Input.self)`
4. Print the decoded input value in the `do`, log the error in the `catch`
5. See both appear

I am sending the data using a JQuery $.post() method.

`$.post(<route>, { title: document.getElementById("title").value } );`

### Expected behavior

The error should either throw or continue but should not do both.

### Environment

* Vapor Framework version: 4.65.0
* Vapor Toolbox version: 18.6.0
* OS version: macOS 13.0.1

**Comment by 0xTim** [comment]
Can you show your route handler? Because that doesn't make any sense!

**Comment by OurBigAdventure** [comment]
fileprivate func savePost(request: Request) async -> Response {
    do {
      let (user, profile) = try await GeneralUser.retrieve(with: request)
      if let user = user, profile != nil {
        struct Input: Content {
          var title: String
          var content: String
          var publish: String
        }
        let input = try request.content.decode(Input.self)
        let newPost = Post(userId: user.id!, title: input.title, content: input.content, publish: input.publish)
        try await newPost.save(on: request.db)
      } else {
        print("Post processing Error: No session, user or profile ??")
      }
    } catch let error {
      print("Post processing Error: \(error.localizedDescription)")
    }
    return request.redirect(to: "/posts")
  }

**Comment by OurBigAdventure** [comment]
Agreed, it makes no sense.  The throw happens on the decode line and the `error.localizedDescription` is printed, but the Post is also created and saved to the database.

**Comment by vzsg** [comment]
What's the output if you replace `\(error.localizedDescription)` with `\(error)`? The localizedDescription is absolutely useless in most cases, in any framework, including Foundation and all the Apple stuff.

**Comment by OurBigAdventure** [comment]
I think I may have found the problem, the form tag has an `action` and the submit button has the `onclick` so the POST call is being made twice.

The interesting thing is that sending the form action results in the Abort.442 error.  Probably from what @0xTim pointed out in another issue (that it is expected behavior for an empty field).

Sending the POST from the JQuery call works, even if the content is empty.  I'm assuming that this is because JQuery is probably sending JSON so the value is by default an empty string.

I will disagree @vzsg on the localizedDescription, but in the cases where they are useless it's because a developer didn't take the time to provide a helpful description.  We've all been there ;)

Thanks for taking a look guys, I'm going to mark this one as closed.

**Comment by vzsg** [comment]
Pragmatically speaking, you are more likely to find the actual actionable issue by inspecting the description than the localizedDescription. And that's useful when investigating mysterious issues. Alas, I'm glad the issue is now resolved.
