### ISSUE TITLE
🐞Error: no such module 'PackageDescription' using VScode Hello world project

### ISSUE THREAD

**Issue by Muhammed9991** [vapor/vapor#2925]
### Describe the bug
I was following the  "Hello world" project on your [Getting started](https://docs.vapor.codes/getting-started/hello-world/) page. Using VsCode, and the extension for swift. I keep getting error saying `error: no such module 'PackageDescription'`. 

### To Reproduce

1.  `vapor new hello -n`
2.   `cd hello`
3. Open project on VScode (I'm currently using MacOS 13.0.1)
4. You will see `error: no such module 'PackageDescription'`

### Environment

* Vapor Framework version: Can't find vapor framework when I use `swift build`. Because of missing package.
* Vapor Toolbox version: 18.6.0
* MacOS version: 13.0.1

### Additional context

Results from `swift build -v`

```
error: 'swift-posts-api': Invalid manifest
Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx11.0
/Library/Developer/CommandLineTools/usr/bin/swift-frontend -frontend -c -primary-file /Users/muhammedmahmood/Documents/swift-posts-api/Package.swift -target arm64-apple-macosx11.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I /Library/Developer/CommandLineTools/usr/lib/swift/pm/ManifestAPI -swift-version 5 -package-description-version 5.7.0 -disable-implicit-concurrency-module-import -disable-implicit-string-processing-module-import -target-sdk-version 13.0 -module-name main -o /var/folders/x_/zhwb1ylj4f19hgdrt7ckn9lr0000gn/T/Package-77d667.o
/Users/muhammedmahmood/Documents/swift-posts-api/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

**Comment by Muhammed9991** [comment]
**Update:**

Weirdly when opening this project on XCode it resolves packages and builds as normal. However, on VScode it still shows the same error `error: no such module 'PackageDescription'`. Could this potentially be an issue with swift extension for VsCode?

**Comment by vzsg** [comment]
While there might be other issues around VSCode and the extensions (which Swift extension are you using, again?), the immediate error that you got on the command line is caused by the Command Line Tools package being active, instead of a full SDK from Xcode.

The following command should fix that (or you can change it in Xcode / Preferences / Locations):

```
sudo xcode-select -s /Applications/Xcode.app
```

**Comment by Muhammed9991** [comment]
Yeah that fixed it. Thanks for that. This can be closed now

**Comment by vzsg** [comment]
Yes, it is obligatory to have Xcode installed, as the platform SDK and some of the required tooling are only included with Xcode. And all the tools installed with Xcode (including random stuff like git) are gated to only work if the agreement is accepted. There's no way around it.[^1]

The CommandLineTools package, which is often installed and activated by Homebrew during its installation, contains only a subset of the SDK and therefore is not enough.

The "fix" just ensures that the full version is active, which could also be set in Xcode's Preferences / Locations.

[^1]: I mean, if you want to run the app on macOS. During recent years, VSCode dev containers appeared and allow you to work with Swift on Linux "directly" in the comfort of VSCode, inside a Docker container that's managed for you in the background.

**Comment by cin4ed** [comment]
Thank you for clarifying. I now understand the concept better. Nonetheless, it's surprising to me that running Swift without Xcode isn't feasible, especially when it's possible on Linux. Given this, I had assumed it would be achievable.

**Comment by 0xTim** [comment]
It's a 'known issue' and difficult because Swift on Linux != Swift on macOS because of Foundation and XCTest. On macOS they still use the Objective-C implementations. With the new Foundation and Swift Testing those last barriers should be solvable
