### ISSUE TITLE
Crash during upload 

### ISSUE THREAD

**Issue by varungakhar** [vapor/vapor#2930]
### Describe the bug

 When i try to upload a file .  Server Crash . Please see attached screenshot

This issue may be related to https://github.com/vapor/multipart-kit/issues/86

### To Reproduce

1. Upload a file larger than 1 mb

### Environment

* Vapor Framework version: 4.67.0
* Vapor Toolbox version: 
* OS version: Mac Mini M1 (Ventura 13.0)
![Screenshot 2022-12-03 at 6 29 51 PM](https://user-images.githubusercontent.com/12067480/210242297-b1da737e-5a20-4ad0-81ba-36446a2b91d0.png)
![Screenshot 2022-12-03 at 6 30 02 PM](https://user-images.githubusercontent.com/12067480/210242374-876b7b6f-0f44-41ad-8081-8c76397cbc17.png)

**Comment by 0xTim** [comment]
What does the request you're sending to the server look like and what does your route handler code look like?

**Comment by varungakhar** [comment]
Rite now I am using latest version of vapor (4.67.5) . Now I am getting race condition error too. Please check screenshot
Here's server code 
struct StreamController: RouteCollection
{
 func boot(routes: RoutesBuilder) throws {
        let group = routes.grouped("api")
        group.on(.POST, "testingasyncstream", body: .stream, use: testingasyncstream)
    }
    
    func testingasyncstream(req:Request) async throws -> String
    {
        var buffer = ByteBuffer()
        for try await bytebuffer in req.body
        {
            var nextbuffer = bytebuffer
            buffer.writeBuffer(&nextbuffer)
        }
        return ""
    }
}

Here's iOS Code

**Comment by varungakhar** [comment]
Rite now I am using latest version of vapor (4.67.5) . Now I am getting race condition error too. Please check screenshot

### Environment

    Vapor Framework version: 4.67.5
    OS version: Mac Mini M1 (Ventura 13.0)

Here's server code
 ```
     struct StreamController: RouteCollection 
     {
         func boot(routes: RoutesBuilder) throws 
         {
        let group = routes.grouped("api")
        group.on(.POST, "testingasyncstream", body: .stream, use: testingasyncstream)
         }

       func testingasyncstream(req:Request) async throws -> String
       {
         var buffer = ByteBuffer()
         for try await bytebuffer in req.body
         {
           var nextbuffer = bytebuffer
           req.logger.info("readableBytes...\(nextbuffer.readableBytes)")
           buffer.writeBuffer(&nextbuffer)
          }
         return ""
        }
    }
```
Here's iOS Code
```
 func uploadstreamfiles<T>(url:String,upload_type:String,random:Int,filemodel:T , clouser : @escaping (Data?,Error?) -> (Void) = {_,_ in}) where T : FilePro
                {
  let url = URL(string: url)!
  var request = URLRequest(url: url)
  request.httpMethod = "POST"
  request.setValue("multipart/form-data; boundary=boundary", forHTTPHeaderField: "Content-Type")
  request.setValue("chunked", forHTTPHeaderField: "Transfer-Encoding")
  var param = [String:Any]()
    let mirror = Mirror(reflecting: filemodel)
         for child in mirror.children
         {
             if (child.value is Data) == false
                 {
                     param[child.label!] = child.value
                  }
          } 
                var body = Data()
 if param.count > 0
 {
  for (key,value) in param
   {
      let unwrapvalue = unwrap(any: value)
       if let unwrapvalue = unwrapvalue
       {
        body.append("--boundary\r\n".data(using: .utf8)!)
        body.append("Content-Disposition: form-data; name=\"\(key)\"\r\n\r\n".data(using: .utf8)!)
        body.append("\(unwrapvalue)\r\n".data(using: .utf8)!)
        }
     }
 }
     if filemodel.image_file != nil
     {
body.append("--boundary\r\n".data(using: .utf8)!)
body.append("Content-Disposition: form-data; name=\"image_file\"; filename=\"image.jpeg\"\r\n".data(using: .utf8)!)
body.append("Content-Type: image/jpeg\r\n\r\n".data(using: .utf8)!)
body.append(filemodel.image_file!)
body.append("\r\n".data(using: .utf8)!)
       }
      if filemodel.video_file != nil
      {
body.append("--boundary\r\n".data(using: .utf8)!)
body.append("Content-Disposition: form-data; name=\"video_file\"; filename=\"video.mp4\"\r\n".data(using: .utf8)!)
body.append("Content-Type: video/mp4\r\n\r\n".data(using: .utf8)!)
body.append(filemodel.video_file!)
body.append("\r\n".data(using: .utf8)!)
       }
               
                body.append("--boundary--\r\n".data(using: .utf8)!)
                request.httpBody = body

                let uploadtask = mediasession.uploadTask(withStreamedRequest: request)
                uploadtask.taskDescription = String(random)
                uploadtask.resume()
}
```
![Screenshot 2023-01-05 at 1 27 33 PM](https://user-images.githubusercontent.com/12067480/210732142-d63f980b-e623-4d3e-977a-789551be7c18.png)
![Screenshot 2023-01-05 at 1 31 31 PM](https://user-images.githubusercontent.com/12067480/210732189-eca56334-35e3-4605-980b-276a0d4b4266.png)

**Comment by Joannis** [comment]
@varungakhar can you try submitting this in a PR as a unit test, if that's possible?
