### ISSUE TITLE
Make `WebSocket` conform to `Sendable`

### ISSUE THREAD

**Issue by fumoboy007** [vapor/vapor#2936]
**Is your feature request related to a problem? Please describe.**
Some `WebSocket` methods can only be used safely from the event loop thread. For example, `close(code:promise:)` can only be called from the event loop thread because it reads/writes instance variables that are also read/written by the `handle(incoming:)` method, which is only called on the event loop thread.

In other words, `WebSocket` is not thread-safe (a.k.a. `Sendable`). Callers need to make sure to dispatch onto the event loop thread before using the `WebSocket` instance. This is especially inconvenient for developers who are using the Swift Concurrency version of the API: now they need to know about SwiftNIO’s event loop system.

**Describe the solution you'd like**
Ideally, `WebSocket` were thread-safe and marked as `Sendable`. Not only would clients not have to worry about dispatching onto the event loop thread but they could also easily pass `WebSocket` instances across concurrency domains.

How to achieve thread-safety is an interesting question. I haven’t thought much about it but the first thing that comes to my mind is using the following pattern in each `WebSocket` method:
```swift
func myMethod(…, promise: EventLoopPromise<Void>?) {
  if eventLoop.inEventLoop {
    myMethodUnsafe(…, promise: promise)
  } else {
    eventLoop.execute { [weak self] in
      guard let self else {
        promise?.fail(MyError.webSocketClosed)
        return
      }
      myMethodUnsafe(…, promise: promise)
    }
  }
}

private func myMethodUnsafe(…, promise: EventLoopPromise<Void>?) { … }
```

**Describe alternatives you've considered**
We could also use a lock? (Like I said, I haven’t thought much about the implementation!)

**Comment by 0xTim** [comment]
This was done in [WebsocketKit 2.12.0](https://github.com/vapor/websocket-kit/releases/tag/2.12.0)
