### ISSUE TITLE
Application.run() should be `noasync`

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#2937]
https://github.com/vapor/vapor/blob/b293ee5e14c1d7732d1a6d37a1bc4bf19a0837e1/Sources/Vapor/Application.swift#L102

`Application.run()` blocks the calling thread. That's fine but not on the Swift Concurrency thread pools. It should therefore be marked `@available(*, noasync)`.

Additionally, it might be worthwhile to provide an `public func run() async` which `await`s the shutdown.

**Comment by Joannis** [comment]
I believe I have the second idea already in a PR, I might've forgotten to submit it though. I forgot about `noasync`, let me do that!

**Comment by Joannis** [comment]
I want to add that it's become a notorious issue in `func main() async throws`
