### ISSUE TITLE
Static file response issues when compression is enabled

### ISSUE THREAD

**Issue by NeedleInAJayStack** [vapor/vapor#2944]
### Describe the bug

FileMiddleware response issues are observed when response compression is enabled. Specifically when loading a page that should have caches of static assets (and therefore get `304` responses), some asset requests receive a `(failed) net::ERR_INVALID_HTTP_RESPONSE` error. In rarer cases, these requests hang indefinitely.

This error has been observed on Chrome browsers when the client is a different machine than the server.

### To Reproduce

See https://github.com/NeedleInAJayStack/vapor-fileissues

### Expected behavior

The cached static asset requests succeed with a `304` response.

### Environment

* Vapor Framework version: 4.69.1
* Vapor Toolbox version: 18.6.0
* OS version: MacOS 13.0, MacOS 12.4

### Additional context

The issue appears to happen on the 7th static file request, suggesting that there may be something strange going on with TCP connection reuse.

**Comment by Joannis** [comment]
@NeedleInAJayStack was this solved by your PR?

**Comment by NeedleInAJayStack** [comment]
Yes, it was resolved by https://github.com/vapor/vapor/pull/2943! I will mark as closed. Thanks @Joannis!
