### ISSUE TITLE
No scheme/target created with Xcode 14.1 or 14.2

### ISSUE THREAD

**Issue by dansinclair25** [vapor/vapor#2946]
### Describe the bug

I'm following the instructions in the [Getting Started](https://docs.vapor.codes/getting-started/hello-world/) section but when I open `Package.swift`, there's no scheme for me to run at all. I've tried with Xcode 14.1 and 14.2. Am I missing something or has something broken?

<img width="434" alt="image" src="https://user-images.githubusercontent.com/2573447/215184319-1a464ce4-c97c-4ae0-9c01-13c960b45798.png">

EDIT: I've also tried Xcode 14.0.1 and 13.4.1 but they present the same issue.

### To Reproduce

1. Install Xcode 14.1 or 14.2
2. Create a new project using `vapor new hello -n`
3. Open `Package.swift`

### Expected behavior

As per the instructions, a scheme should be created so that you can run the app.

### Environment

* Vapor Framework version: 4.69.1
* Vapor Toolbox version: 18.6.0
* OS version: macOS Venture 13.1

### Additional context
N/A

**Comment by 0xTim** [comment]
What does your Package.swift look like and what errors do you see in either the issue navigator pane or the build logs in the report navigator?

**Comment by dansinclair25** [comment]
After further investigation it appears it was an issue on my Mac. For some reason Xcode wasn't able to fetch any SPM packages giving me a "no credentials provided" error. It turns out that Git on my Mac had got confused somehow with my Git credentials. Updating all git credentials using [Git Credential Manager](https://github.com/GitCredentialManager/git-credential-manager/blob/main/README.md), and then opening the `Package.swift` file in Xcode meant that Xcode could fetch the SPM packages and then create the target.
