### ISSUE TITLE
ETag should be a hash

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#2948]
### Describe the bug

Currently, ETag for file serving is generated from the modified date and file size. A hash is a stronger alternative, and can be precomputed if available. See #2943.

**Comment by jhoughjr** [comment]
"ETag should be a hash of the contents (not just \(lastModificationTime)-\(fileLength))" re precomputing, precomputing when?

**Comment by jhoughjr** [comment]
if the hash is to be based on the file contents, what algorithm should be used?

**Comment by jhoughjr** [comment]
currently im testing an md5 hash on the contents.

**Comment by jhoughjr** [comment]
I dont think this is teastable.

**Comment by Joannis** [comment]
I think that's mostly up for debate / deferred to the end user implementation. Many people prefer not using MD5, but rather SHA1, or a modern standard like SHA2 (whichever variant). And since hashes vary depending on the user and their infrastructure, I'd say cached hashes should not be mandated to use a specific algorithm.

I think it would be nice to support non-cached hashing out of the box, however that might be a two-step process. I'd love us to have an algorithm option in the case of non-cached hashes such as `etag: .md5` or `etag: .sha1`

**Comment by jhoughjr** [comment]
can do that tonight I think.

**Comment by linus-hologram** [comment]
As discussed on discord, I'll try to compute a hash whenever data is written to the file system and store it in a file attribute. As for the hashing technique, SHA-1, SHA-256 or similar will be used.

**Comment by linus-hologram** [comment]
We're using a different approach now. Creating the hash solely when a file is written to the file system using Vapor turned out to be unviable since that would not create any file hashes for manually added files.

Instead, the hash is now generated whenever a file is streamed back to the client, provided the hash is not already cached.

**Comment by linus-hologram** [comment]
@0xTim will the PR #3015 be merged some time soon?

**Comment by linus-hologram** [comment]
@0xTim any update on this?
