### ISSUE TITLE
Is it possible to get memory usage in ubuntu system？

### ISSUE THREAD

**Issue by shenfu1991** [vapor/vapor#2956]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
get memory usage in ubuntu system

**Describe alternatives you've considered**

**Additional context**

-----
hi,
I can use the following function to get the memory usage in macOS, but an error will occur in ubuntu, so is there any other way to get it? Get cpu info by the way . thank you.

<pre>
func report_memory() {
    var info = task_basic_info()
    var count = mach_msg_type_number_t(sizeofValue(info))/4

    let kerr: kern_return_t = withUnsafeMutablePointer(&info) {

        task_info(mach_task_self_,
            task_flavor_t(TASK_BASIC_INFO),
            task_info_t($0),
            &count)

    }

    if kerr == KERN_SUCCESS {
        println("Memory in use (in bytes): \(info.resident_size)")
    }
    else {
        println("Error with task_info(): " +
            (String.fromCString(mach_error_string(kerr)) ?? "unknown error"))
    }
}
</pre>

**Comment by mkll** [comment]
@shenfu1991 Excuse me, but what does this problem have to do with Vapor?

**Comment by shenfu1991** [comment]
@mkll Sorry, this should have nothing to do with vapor, but vapor does not seem to have a built-in function to query relevant information, just to discuss, I hope there is no misunderstanding.

**Comment by Joannis** [comment]
@shenfu1991 you'll have to look for Glibc's APIs, and import that on Linux. This is the first thing I found:

https://stackoverflow.com/questions/669438/how-to-get-memory-usage-at-runtime-using-c

**Comment by shenfu1991** [comment]
@Joannis Thank you for your help, but how to compile and run swift and c will be another problem, I tried to compile it together, but the compiler directly reported an error, and it cannot be compiled together.

**Comment by 0xTim** [comment]
I'm going to close this since it's not related to Vapor. Feel free to continue discussion here or the Swift Forums
