### ISSUE TITLE
Hello world URL wrong

### ISSUE THREAD

**Issue by rph8** [vapor/vapor#2980]
If you do the hello world at https://docs.vapor.codes/getting-started/hello-world/ and
go to http://127.0.0.1:8080 in your browser, you will get this error message:
`{"error":true,"reason":"No template found for index"}`
The /hello is missing in the URL.

The other URL mentioned, http://localhost:8080/hello and of course http://127.0.0.1:8080/hello will work instead.
I wanted to create a pull request on the docs right away btw, but could not find the docs repository / subfolder.

**Comment by 0xTim** [comment]
This is being discussed on https://github.com/vapor/docs/pull/781 but I don't think it's an issue
