### ISSUE TITLE
Non HTTP/S ports open for public inbound connection

### ISSUE THREAD

**Issue by vaclavdobsicek** [vapor/vapor#3001]
### Describe the bug

Lambda has open ports 3306, 22 and 5432 for INBOUND connection.

### To Reproduce

Deploy Laravel Vapor to AWS

1. Visit Lambda - Configuration - VPC

### Expected behavior

There should be only port 80 and 443 open and idealy with SG of API Gateway, not for 0.0.0.0/0

### Environment

* Vapor Framework version: not sure
* Vapor Toolbox version: not sure
* OS version: N/A

### Additional context
![image](https://user-images.githubusercontent.com/12571002/233346300-7908f8c1-6e69-4206-8cc3-d6fdefe3b855.png)

**Comment by vzsg** [comment]
I'm afraid if this is about **Laravel** Vapor, then this is the wrong repository to open an issue against.
