### ISSUE TITLE
Ability to not create 64 threads when booting vapor.

### ISSUE THREAD

**Issue by John-Connolly** [vapor/vapor#3003]
### Describe the bug

On iOS platforms the default threadpool size of 64 is a bit aggressive. Sometimes iOS will not want to create that many threads leading to a crash  in ``` ThreadOpsPosix.run (ThreadPosix.swift:109)```.  Even when swapping the ```NIOThreadPool``` to one with only one thread doesn't prevent the default one from creating 64 threads.

### To Reproduce
Boot a vapor app.

n/a this is the default behaviour.

### Expected behavior
```  app.threadPool = NIOThreadPool(numberOfThreads: 1)``` should replace the default threadpool before it's started. 

### Environment

* Vapor Framework version: [4.76.0](https://github.com/vapor/vapor/releases/tag/4.76.0)
* Vapor Toolbox version: N/A
* OS version: N/A

### Additional context
 I'm happy to provide a patch for this.

**Comment by 0xTim** [comment]
Yes this seems sensible and has come up in the past - happy to accept a patch for this change in behaviour

**Comment by dfed** [comment]
Adding a +1 to this. When deploying Vapor on iOS we're creating _way_ too many threads. Would love to be able to cap this in the initializer.

**Comment by gwynne** [comment]
Addressed by #3092 and the preexisting ability to replace the default thread pool.
