### ISSUE TITLE
template error

### ISSUE THREAD

**Issue by sinduke** [vapor/vapor#3004]
### Describe the bug

I created a new project using vapor new and ran it directly without modifying anything to create todos
The error that comes up is:
"reason": "Value required for key at path 'id'. No value associated with key \"id\"."

**Comment by sinduke** [comment]
I use
struct CreateTodoData: Content {
let title: String
}
When using CreateTodoData.self instead of Todo.self in req.content.decode(), it can be created normally. It is obvious that something went wrong when using the model directly. I used the project created by vapor new and did not modify other You can test the contents of

**Comment by vzsg** [comment]
How did you test the request?

**Comment by sinduke** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/22930750/233816965-fa05aec3-7b83-4b1b-a02d-e38b242efabc.png">
This is use struct CreateTodoData: Content 
Still can't use Todo.self

**Comment by vzsg** [comment]
I can't seem to reproduce your issue. In a freshly cloned template with postgres, after adding autoMigrate to create the table easily, the following request worked just fine in Postman:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1783465/233859274-2d6f5e7e-7e29-411b-a8a7-a21f5a61df5a.png">

As unfortunately I can't read Chinese, especially not on screenshots, I can't tell what's misconfigured, but be sure that you're sending the `Content-Type: application/json` header with the request. In my case, it's added automatically as I selected a raw body and JSON (in blue).
