### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by jchannon** [vapor/vapor#301]
Hi

I was wondering if you had any plans for Vapor to have a builtin testing framework/API to test routes in a Vapor app?  For Nancy, we had great feedback by providing this functionality.  Here's an example:

```
[Fact]
    public void GetData_WhenRequested_ShouldReturnJSON()
    {
        var browser = new Browser();
        var response = browser.Get("/GetData", (with) =>
        {
            with.Header("Accept", "application/json");
            with.HttpRequest();
        });

        Assert.Equal("application/json", response.Content.Headers.ContentType.MediaType);
    }
```

So `Browser` is just a class, by calling it Browser people kind of get a contextual idea of what it is doing. It has the HTTP verbs on it, and the second argument is a closure that allows you to add Headers, Body etc etc. What this does underneath is return an instance of itself eg. a call to headers adds the header then returns the class instance so that when HttpsRequest is called it already has the headers.  When it is all invoked it uses these values to create a simulated request but without a server into Nancy and Nancy acts as if a server had made the request and it goes through its logic to return the response etc and then back in the test you can check the response values.

Just thought this would be a beneficial thing for Vapor to have

**Comment by Evertt** [comment]
I like your suggestion! Especially calling it browser so that people understand it quickly. Again here I would like to draw some inspiration from [how laravel does it](https://laravel.com/docs/master/testing#application-testing).

```swift
class BlablaTest {
    let browser = Browser()

    public testSomething() {
        browser
            .visit("/")
            .see("some phrase")
            .dontSee("some other phrase")
            .click("Some Link")
            .seePageIs("/some-page")
    }

    public testRegistering() {
        browser
            .visit("/register")
            .type("Evert", inFieldCalled: "name")
            .check("terms")
            .press("Register")
            .seePageIs("/dashboard")
    }
}
```

**Comment by jchannon** [comment]
That seems more UI focused, ie /check field and type data which I think
potractor or similar JS tool is better at doing IMO.

I would like an HTTP API test focus.

What Nancy does is use a library that you can query the HTML response
though.

[Fact]public void Should_display_error_message_when_error_passed()
{
    // Given
    var bootstrapper = new DefaultNancyBootstrapper();
    var browser = new Browser(bootstrapper);

    // When
    var response = browser.Get("/login", (with) => {
        with.HttpRequest();
        with.Query("error", "true");
    });

    // Then
    response.Body["#errorBox"]
            .ShouldExistOnce()
            .And.ShouldBeOfClass("floatingError")
            .And.ShouldContain(
                "invalid",
                StringComparison.InvariantCultureIgnoreCase);
}

**Comment by tannernelson** [comment]
That's a great idea. We'll include this in the roadmap.

**Comment by jchannon** [comment]
Brill :)

**Comment by tannernelson** [comment]
Feel free to submit a more formalized proposal if you want. Otherwise Logan and I will get to his during one of the future milestones.

**Comment by jchannon** [comment]
What would you like to see in a more formal proposal?

**Comment by tannernelson** [comment]
If you create a new issue, the "feature" template will be pre-filled in there. I think you have a majority of the elements here already. Just a matter of formatting them.

**Comment by tannernelson** [comment]
This would be as simple as providing a couple of convenience extensions to `HTTPResponder`. 

The branch of the vapor-example with separated modules works like this.

**Comment by LoganWright** [comment]
We've got some documentation here #667. Let's move testing thread here.
