### ISSUE TITLE
PostgresNIO.PSQLError (backing: PostgresNIO.PSQLError. (unknown context at $10160e44c). Backing)

### ISSUE THREAD

**Issue by Muning69** [vapor/vapor#3028]
### bug

The original project was running well, and everything logged in was normal. No code changes have been made, only the latest version of Vapor has been updated. As a result, the app's account cannot be logged in.

If you intentionally use the wrong account password to log in, you will normally report that your identity has not been verified.
But if the correct account password is used for login, it will report:
`PostgresNIO.PSQLError (backing: PostgresNIO.PSQLError. (unknown context at $10160e44c). Backing)`

It's really strange to have this problem. Once again, confirm that the original project code has not been changed. Everything was originally normal.

I am using the `Postgres` database.

I tried using both the old and new versions of the database registration API, but the problem remained the same.

I am trying to write a routing method to read the database content, and using a Postman request, I can successfully obtain the data content. But logging in using Postman or app and using the correct account and password will result in an error:
`PostgresNIO.PSQLError (backing: PostgresNIO.PSQLError. (unknown context at $10160e44c). Backing)`
If the wrong account password is used, it will be reported that the identity has not been verified.

I am using Basic Auth provided by Vapor.
The premise is that everything was running normally.

**Comment by Muning69** [comment]
###  The cause of the problem
If you initially configured the database connection certificate in Vapor, but your certificate may be expired or invalid. You may want to give up configuring the certificate, so you changed TLS to `.disable`, and you will encounter the following error message:` PostgresNIO.PSQLError (backing: PostgresNIO.PSQLError. (unknown context at $10160e44c). Backing)` . No matter how you clear the Xcode cache, you cannot solve this error.

### Solution to the problem
Unless you re `enable` the `TLS certificate` and it is valid. Then the error message will disappear.

### postscript
The possible cause of this issue may be due to issues with the code for `TLS certificates` in `PostgresNIO`. I hope the relevant person in charge of `Vapor` can improve it as soon as possible.

My English is not good, I rely entirely on translation, and some expressions may not be appropriate. You can only understand on your own.

Finally, roast that your forum is too slow to participate in the reply. I hope there can be more improvements.

**Comment by Muning69** [comment]
This bug is very strange. It will work for a while, but it won't work again.

**Comment by cshadek** [comment]
I'm also seeing this issue

**Comment by Muning69** [comment]
### The cause of the problem
`If there are multiple fields in the model`, it is easier to understand when reporting an error in versions `before Vapor 4.77.0, while in version 4.77.0`, it will report `PostgresNIO.PSQLError (backing: PostgresNIO.PSQLError. (unknown context at $10160e44c) The mistake of 'Backing'` makes people confused.
