### ISSUE TITLE
Adopt Swift Tracing

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#3033]
[Swift Tracing](https://github.com/apple/swift-distributed-tracing) is now 1.0 so we should adopt it, probably in middleware to make is easy to add.

We need to be careful as it relies on TLVs so if we cross ELF boundaries we could lose the context, but I think we're ok if we use an async middleware. Will need to test the whole stack

**Comment by slashmo** [comment]
@0xTim Glad to see this being tracked now 👍 Feel free to ping me once you're starting the implementation, then I could update my HTTP client/server example to use Vapor as well as Hummingbird: https://github.com/slashmo/swift-otel/tree/example/http

**Comment by NeedleInAJayStack** [comment]
@0xTim / @gwynne Now that #3253 is merged, I think we can call this closed! Thanks!

**Comment by NeedleInAJayStack** [comment]
Also, @0xTim / @gwynne do you think we should add tracing usage instructions to https://github.com/vapor/docs ? I'd be happy to submit a draft if you think so!

**Comment by 0xTim** [comment]
@NeedleInAJayStack Yep some docs would be great!

**Comment by NeedleInAJayStack** [comment]
@0xTim Cool, I've added a pull request: https://github.com/vapor/docs/pull/1039
