### ISSUE TITLE
Hang risk when running on iOS as a file server

### ISSUE THREAD

**Issue by tomisacat** [vapor/vapor#3034]
### Describe the bug

I'm trying to embed Vapor into an iOS app as file server following the tutorial from [Running a Web Server on iOS with Vapor | Kodeco](https://www.kodeco.com/31498014-running-a-web-server-on-ios-with-vapor), but encountered hang risk when running app:

<img width="289" alt="SCR-20230703-qebr" src="https://github.com/vapor/vapor/assets/1179735/14e3f23f-a8b4-4568-a4aa-45f4b74bc1b8">

The full warning report is:

```
Thread Performance Checker: Thread running at QOS_CLASS_USER_INTERACTIVE waiting on a lower QoS thread running at QOS_CLASS_DEFAULT. Investigate ways to avoid priority inversions
```

### To Reproduce

1. Add package with Xcode built-in package manager
2. Initialize `Application` and start

```Swift
  init(port: Int) {
    self.port = port
    app = Application(.production)
    configure(app)
  }

  private func configure(_ app: Application) {
    app.http.server.configuration.hostname = "0.0.0.0"
    app.http.server.configuration.port = port

    app.views.use(.leaf)
    app.leaf.cache.isEnabled = app.environment.isRelease
    app.leaf.configuration.rootDirectory = Bundle.main.bundlePath

    app.routes.defaultMaxBodySize = "50MB"
  }

  func start() {
    Task(priority: .high) {
      do {
        try app.start()
      } catch {
        fatalError(error.localizedDescription)
      }
    }
  }
```
3. Call `start` when app launch, and the error will prompted out.

### Expected behavior

No hang risk, just like running Vapor as a server side app.

### Environment

* Vapor Framework version: 4.77.0
* Vapor Toolbox version: 18.7.1
* OS version: 13.3.1

### Additional context
No

**Comment by 0xTim** [comment]
This is a dupe of https://github.com/apple/swift-nio/issues/2223 and an issue inside NIO - not something we can control unfortunately

**Comment by tomisacat** [comment]
@0xTim Thanks for your reply. I think I should adopt the temporary solution as a workaround for the time being.
