### ISSUE TITLE
Error whyle deploy to fly.io on postgress migration

### ISSUE THREAD

**Issue by IvanovGeorge** [vapor/vapor#3042]
Hello!

I'm trying to deploy a vapor project with a postgres db to fly following this instruction https://docs.vapor.codes/deploy/fly/
App has configured and attached db on fly launch command.
When i just deploy an app, all goes fine, but when i add this flag to start migration:

```
[deploy]
 release_command = "migrate -y"
```

it fails with error on this:

```
Migrate Command: Prepare
  Migrate Command: Prepare
  [ WARNING ] PSQLError(code: connectionError, underlying: NIOSSL.NIOSSLError.handshakeFailed(NIOSSL.BoringSSLError.sslError([Error:  EOF during handshake])))
  Swift/ErrorType.swift:200: Fatal error: Error raised at top level: PSQLError(code: connectionError, underlying: NIOSSL.NIOSSLError.handshakeFailed(NIOSSL.BoringSSLError.sslError([Error:  EOF during handshake])))
```
Also, migration works fine if i run it locally on my machine with a **swift run App migrate** command.

May be you have some ideas, what could go wrong?

**Comment by 0xTim** [comment]
In fact this looks exactly like this issue, I'm going to close this in favour of https://github.com/vapor/postgres-kit/issues/247 - feel free to reopen if it's not the case
