### ISSUE TITLE
Fix 27 occurrences of hardcoded port in vapor tests

### ISSUE THREAD

**Issue by jhoughjr** [vapor/vapor#3052]
I noticed an edge case interaction that others could experience.
I was using carton and swiftwasm in terminal while using Xcode to run unit tests.
Randomly it seemed 8 tests failed Short story shorter the tests were clashing with a development server.
Gwynne has identified 27 places in the tests that still hard code 8080 and will thus clash with any development server running on the standard port.

This is bad as it causes false test failures which consume time and make tests feel less reliable and easier to ignore.
I will make a PR within the hour with a fix for this.
I just wanted an issue to reference in the PR.

**Comment by gwynne** [comment]
For reference: 
<img width="275" alt="Screenshot 2023-08-08 at 09 01 43" src="https://github.com/vapor/vapor/assets/1130717/4610828a-df56-44cd-bde8-047c6ac453ff"><img width="304" alt="Screenshot 2023-08-08 at 09 02 35" src="https://github.com/vapor/vapor/assets/1130717/76224650-6b9d-42ff-aa38-db29141842a6">

**Comment by jhoughjr** [comment]
Not as simple as just replacing 8080 as the tests dont all use the value in the same way. I need to understand more of how the interaction leaks happen.
