### ISSUE TITLE
Capistrano like update system

### ISSUE THREAD

**Issue by anthonycastelli** [vapor/vapor#306]
When updating a rails up, there is a gem, capistrano that allows you to run tasks in order to update the rails app. This makes things super simple for pushing a new version. 
## Example

`cap production deploy`
What is happening here is capistrano is deploying the production version of the app to server. It'll ssh in, run a few commands to pull the latest source from git, update gems, and restart the process. One of the nice things capistrano does is handles versioning so if you update and the whole app breaks, you can revert to a previously deployed release. The releases are handled on the server so it doesn't use tags or branches from git, though handling versioning off of tags might be a good solution or option as well.  

Something like this would be a huge help for running on a Digital Ocean, Linode or any other Linux server or VPS. 

I'm still figuring out how this whole system works and functions so I wanted to drop this here as a feature request for anyone who is willing to work on it and has much more knowledge of vapor than me.

**Comment by tannernelson** [comment]
This is definitely functionality I'd like to see in `vapor-cli`. Laravel's Envoy does something similar.

**Comment by LoganWright** [comment]
Is there a series of shell commands that we could wrap in the interim just to add a quick convenience for happy path?

**Comment by anthonycastelli** [comment]
Off the top of my head something like would be ideal.

Set up a config file with the test, production and/or dev server IP/Domain, ssh info (username and password, otherwise default to an SSH key) and git info

After you have the server setup and everything installed, you can run something like `vapor production deploy) and it will know which server to connect to and run a set of commands to pull the source from a git repo, (either checkout a version tag or create a version based on git hashes). Once its done setting up everything it up will compile and run the process. 

A good example of setting up capistrano is http://guides.beanstalkapp.com/deployments/deploy-with-capistrano.html. I'm sure there are other solutions but I've only use capistrano as I've used rails for backend work so I am using it as a base to explain everything. 

At the end of the day, something to set the server info, pull changes from git, compile the new source and restart the service is definitely adequate for a v1.0 release. Staging servers and such can be added later.

**Comment by alomvar** [comment]
This reminds me on PHP [Deployer](http://deployer.org) and [TYPO3 Surf](https://github.com/TYPO3/Surf) (both inspired by Capistrano). I know their structure since I worked with both. Usually they are just a wrapper for shell commands utilizing [Symfony's Process Component](http://symfony.com/doc/current/components/process.html), @LoganWright.

Wouldn't it make sense to encapsulate this in an own module but tightly couple it into the CLI? Itself probably does not use anything from Vapor and so can be a generic standalone solution.

**Comment by anthonycastelli** [comment]
You are correct @alomvar, its just a bunch of commands it'll run on the server to set everything up. I agree with you about having it its own module. A few friends who are rails dev have forked capistrano and added their own enhancements so keeping it separate would good in a few ways. You wouldn't have to have it if you don't need or use it and it will allow others to easily add additions and add what they might need for their environment. I could probably whip something up as a rough working example.

**Comment by LoganWright** [comment]
I'm open to keeping it in a separate repository, we could call it from within vapor cli if its available. I don't know enough about everyone's workflows to come up with a standard implementation, maybe a few people could articulate the sets of commands they usually call in an ordered and repeatable way that we could incorporate.

**Comment by anthonycastelli** [comment]
Judging off of what most of these modules do I think all that is needed to go from local development to a remote server is:

A config file to handle
- Setting server type (dev, test, production, etc)
- Setting info for each server (SSH, git, username/password/ssh keys)

Commands to run on the server
- Fetch the latest changes from git
- Some sort of versioning system to allow easy rollback if something is broken (Fetching the latest tag or commit has?)
- Compile the vapor app
- Restart the service

If you want it coupled into `vapor-cli` That would make things easy since you would just run `vapor deploy` or whatever the command may be. 

Is there anything I am missing? I'll probably play around with some ideas tonight.

**Comment by jakeheis** [comment]
I'll throw in a small plug for [Flock](https://github.com/jakeheis/Flock) in conjunction with [VaporFlock](https://github.com/jakeheis/VaporFlock). Flock is a very new project, but it should already accomplish most of the tasks discussed above. If there are features it lacks which the Vapor community wants/needs, I hope that Flock will at least provide a place from which we can build what is needed.

**Comment by LoganWright** [comment]
@jakeheis this looks really promising. It's the first I'm seeing it, but I'm excited to check it out. Please submit this to our providers page in our documentation repository to help others with discovery.

Thanks for supporting this project and being part of its vibrant ecosystem.

**Comment by LoganWright** [comment]
@alomvar @anthonycastelli would you guys mind looking at Jake's submission and see if it satisfies some of your intent for the features provided.

**Comment by alomvar** [comment]
@LoganWright I did not use it practically yet but read through their documentation. (Vapor)Flock appears to be a suitable equivalent to deployment tools like Capistrano which solves this issue.
