### ISSUE TITLE
File Middleware strips query parameters with redirect

### ISSUE THREAD

**Issue by Captain-Kirkie** [vapor/vapor#3076]
### Describe the bug
When using the the DirectoryAction .redirect on FileMiddleWare we lose any query parameters sent with the request on redirect. 

Example:
GET /Utilities?test=test -> 301 Moved Permanently /Utilities/ (Query parameters are stripped.)

### To Reproduce

To reproduce:
1) Use Vapor FileMiddleware with directory action .redirect. 
2) Serve files through file middleware. 
3) Make getRequest without trailing "/" and add query parameters GET /Utilities?test=test.

1. Add package with configuration '...'
2. Send request with options '...'
3. See error

### Expected behavior
GET /Utilities?test=test -> 301 Moved Permanently /Utilities/?test=test (Query parameters persist)

### Environment

* Vapor Framework version: framework: 4.78.2
* Vapor Toolbox version: toolbox: 18.7.1
* OS version: MacOS Ventura Version 13.6

**Comment by Captain-Kirkie** [comment]
Pull request [Here](https://github.com/vapor/vapor/pull/3077)

**Comment by 0xTim** [comment]
Fixed in #3077
