### ISSUE TITLE
Document Hot Reload w/ Gulp-Vapor

### ISSUE THREAD

**Issue by LoganWright** [vapor/vapor#311]
Maciej made an awesome feature for hot reloading code changes that uses npm's gulp. It can be found here: https://www.npmjs.com/package/gulp-vapor

We need some brief documentation articulating how to use it.

**Comment by LoganWright** [comment]
Also https://github.com/wess/overlook

**Comment by bejayoharen** [comment]
does vapor-gulp work with vapor 2? I wasn't able to get it to work, but it could be my own lack of  npm/node/javascript foo.
