### ISSUE TITLE
Double encoded post requests after recent update (4.89.3 → 4.91.1)

### ISSUE THREAD

**Issue by finestructure** [vapor/vapor#3133]
Our social media posts made via

```swift
        struct Query: Encodable {
            var status: String
        }

        let res = try await client.post(URI(string: apiURL), headers: headers) { req in
            try req.query.encode(Query(status: message))
        }
```

started showing up as 

![Screenshot 2024-01-08 at 13 11 18@2x](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/assets/5180/6f4530af-5be5-4f17-9e32-12fc1c685281)

after updating from Vapor 4.89.3 → 4.91.1 today.

@gwynne seems to know what the issue might be, adding the issue for tracking purposes.

**Comment by gwynne** [comment]
Duping to #3138, the central tracking for the underlying issue.
