### ISSUE TITLE
double slash in URL no longer matches route handlers

### ISSUE THREAD

**Issue by weissi** [vapor/vapor#3137]
Consider this route

```
app.get("foo", "bar", "buz") { request -> String in
    return try request.query.get(at: "v")
}
```

Before https://github.com/vapor/vapor/commit/6db3d917b5ce5024a84eb265ef65691383305d70 everything worked as expected:

```
$ curl http://127.1:8080/foo/bar/buz?v=M%26M
M&M
```

But after that (including 4.91.1), this will fail with

```
$ curl http://127.1:8080//foo/bar/buz?v=M%26M
{"error":true,"reason":"Not Found"}
```

because it seemingly no longer matches the route on `//`

**Comment by weissi** [comment]
CC @gwynne

**Comment by gwynne** [comment]
Yep, already 3/4 done with the fix for this and several related issues I caused with that change 😅

**Comment by gwynne** [comment]
Duping to #3138, the central tracking for the underlying issue.
