### ISSUE TITLE
StringInitializable Fluent Models

### ISSUE THREAD

**Issue by Evertt** [vapor/vapor#315]
# StringInitializable Fluent Models

* Author(s): [Evertt](https://github.com/Evertt)
* Status: **[Approved](#rationale)**

## Introduction & Motivation

[In the vapor documentation](https://vapor.readme.io/docs/routing#string-initializable) it's explained that you can get type-safe model-binding in routes if you make the model implement `StringInitializable`.

That's nice and all, but why make the developer write code to make each and every one of their models conform to `StringInitializable` when we could so easily make a default implementation?

## Proposed solution & Code snippits

Okay so since Swift doesn't allow you to make a protocol conform to a new protocol via an extension, we need to make a new protocol that inherits from Fluent's `Model` **and** inherits from `StringInitializable`. Luckily for us we can name the new protocol exactly the same as the old protocol.

```swift
import Fluent

public protocol Model: Fluent.Model, StringInitializable {}

extension Model {
    public init?(from string: String) throws {
        guard let model = try Self.find(string) else {
            return nil
        }
        
        self = model
    }
}
```

Yes this compiles, I've tested it.

## Impact

For people who already did this manually, they can now delete that code. If they don't delete their code then I believe this will not affect them.

## Alternatives considered

None, this feature is just awesome and there is no better way of doing it I believe.

**Comment by tannernelson** [comment]
This is a great idea.

**Comment by tannernelson** [comment]
We have this now.
