### ISSUE TITLE
Default to `HTTPClient.shared` when possible

### ISSUE THREAD

**Issue by MahdiBM** [vapor/vapor#3171]
See https://github.com/swift-server/async-http-client/releases/tag/1.21.0
We can default to that when users haven't provided a default configuration.
The default configuration should also be changed to `.singletonConfiguration` if that doesn't seem too much of a behavior change, because that configuration:

> tries to mimic the platform's default or prevalent browser as closely as possible.

**Comment by 0xTim** [comment]
This is primarily aimed at application developers. Since we can control the lifecycle of the client, the guidance is to continue to use our client we instantiate
