### ISSUE TITLE
Crash after installing posix ELG as concurrency executor

### ISSUE THREAD

**Issue by MahdiBM** [vapor/vapor#3179]
### Describe the issue

Crash after installing posix ELG as concurrency executor.

[Quoting Johannes](https://github.com/apple/swift-nio/pull/2710):
> Letting NIO take over the Concurrency thread pool is important for performance. We saw roughly 30% improvements on Linux for non-I/O code and much more for I/O code.

### Vapor version

4.94.1

### Operating system and version

macOS 14.4

### Swift version

Swift 5.10 RELEASE

### Steps to reproduce

Add this code (also `import NIO`) to the Entrypoint in the bare Vapor template:
```swift
if NIOSingletons.unsafeTryInstallSingletonPosixEventLoopGroupAsConcurrencyGlobalExecutor() {
    print("*** installed posix 'EventLoopGroup' as concurrency global executor")
} else {
    print("*** FAILED to install posix 'EventLoopGroup' as concurrency global executor")
}
```

<kbd>
<img width="724" alt="Screenshot 2024-04-29 at 2 02 54 PM" src="https://github.com/vapor/vapor/assets/54685446/73805540-a333-4db5-9ccd-50bad33951c2">
</kbd>

### Outcome

Crash at `Application.execute()`:
<kbd>
<img width="2047" alt="Screenshot 2024-04-29 at 2 03 27 PM" src="https://github.com/vapor/vapor/assets/54685446/6d16c2d4-e918-4f7b-8801-8e6d972815d5">
</kbd>

**Comment by 0xTim** [comment]
See #3168 which should solve the issue
