### ISSUE TITLE
Stored property '_id' of 'Sendable'-conforming class 'Todo' is mutable

### ISSUE THREAD

**Issue by crawford-jake** [vapor/vapor#3180]
### Describe the issue

A warning is appearing on all classes that conform to Model

### Vapor version

4.94.1

### Operating system and version

macOS 14.4.1

### Swift version

Swift 5.10.0-dev

### Steps to reproduce

1. Create a new vapor project: `vapor new my-app`
2. Enter the following prompts:
- Would you like to use Fluent (ORM)? (--fluent/--no-fluent): **y**
- Which database would you like to use? (--fluent.db): **1**
- Would you like to use Leaf (templating)? (--leaf/--no-leaf): **n**
3. Open the vapor project in Xcode using Xcode 15.3
4. Navigate to Sources > App > Models > Todo
5. Warning: Stored property '_id' of 'Sendable'-conforming class 'Todo' is mutable
<img width="641" alt="Screenshot 2024-04-29 at 5 41 18 PM" src="https://github.com/vapor/vapor/assets/82613137/161bd458-db1f-4b37-9b1d-d1619848c596">

### Outcome

This warning appears on any class that conforms to **Model**.

### Additional notes

Running on M2 mac

**Comment by gwynne** [comment]
This is unfortunately an expected side effect of making Fluent otherwise `Sendable`-correct. I've been in touch with the Swift Core team about it; they were able to offer no better solution than to annotate each individual `Model`-conforming type with `@unchecked Sendable` 🙁. We'll be publishing a blog post with more details sometime this week.

**Comment by gwynne** [comment]
That being said, I did forget to update the template project accordingly 😰 Thanks for the nudge!

**Comment by Craz1k0ek** [comment]
Should this be mentioned in the documentation as well, I got confused when this error occurred during new model creation
