### ISSUE TITLE
[routes] does not split path parameter by '/'

### ISSUE THREAD

**Issue by fummicc1** [vapor/vapor#3185]
### Describe the issue

Route does not split path by `"/"`

### Vapor version

4.95.0

### Operating system and version

macOS Sonoma 14.4.1

### Swift version

Swift Package Manager - Swift 5.10.0-dev

### Steps to reproduce

1. Create new nested route by slack '/' delimiter like `'foo/bar'`
2. send a request to it
3. get a response: `{"reason":"Not Found","error":true}`

sample code to reproduce: https://github.com/fummicc1-sample/vapor-nested-grouped/blob/fc92ad345afd511097daabaf33bc84c83d49c9c0/Sources/App/routes.swift#L12-L17

```swift
	app.grouped("foo").grouped("bar").get("", use: { _ in
		"foo-bar"
	})
	app.grouped("foo/baz").get("", use: { _ in
		"foo/baz"
	})
```

on the above code, `"foo/bar"` works but `"foo/baz"` does not work. Is it expected behavior?

### Outcome

hope to support `"foo/baz"` route on the [above repository code](https://github.com/fummicc1-sample/vapor-nested-grouped/blob/fc92ad345afd511097daabaf33bc84c83d49c9c0/Sources/App/routes.swift#L12-L17).

**Comment by 0xTim** [comment]
This is by design, what's happening is when you pass the path `foo/baz` it's getting escaped. To provide separate paths you must do `app.grouped("foo", "baz")...`
