### ISSUE TITLE
Is there a way to add additional behavior to the web server boot?

### ISSUE THREAD

**Issue by bunchjesse** [vapor/vapor#3200]
I just want to add some additional functionality to the web server boot. Is there a way to bolt on this additional work without having to copy `ServeCommand` just to add additional behavior to the `run` method?

**Comment by mkll** [comment]
@bunchjesse Did you mean something like that?
https://docs.vapor.codes/advanced/services/#lifecycle

**Comment by bunchjesse** [comment]
I did see that yes!

Is there a way to ensure that that only runs when the web server is started? I don’t want this extra behavior to run for other commands.

**Comment by mkll** [comment]
@bunchjesse You can be sure.

**Comment by bunchjesse** [comment]
Any pointers on how? In my testing, I see the lifecycle middleware get called for all commands, not just the default `serve` command.

**Comment by mkll** [comment]
@bunchjesse Hmm, my bad. This needs to be explored.

**Comment by mkll** [comment]
@bunchjesse It seems, you may use the following approach:
Check the `app.environment.commandInput.arguments` for command string presence. It will contain "serve", "routes", "<other command name>" or nothing in case of default command.

**Comment by mkll** [comment]
@bunchjesse It seems you can use the following approach:

Check `app.environment.commandInput.arguments` for the command line. It will contain `"serve"`, `"routes"`, or nothing in case of the default command.

**Comment by mkll** [comment]
@bunchjesse Something like that:
```
func didBoot(_ app: Application) throws {
	let defaultCommandName = "serve"
	let currentRunCommandName = app.environment.commandInput.arguments.first ?? defaultCommandName
	
	if currentRunCommandName == defaultCommandName {
		// do something
	}
}
```

**Comment by bunchjesse** [comment]
Beautiful, thank you so much for taking the time to help.

**Comment by mkll** [comment]
@bunchjesse Thanks for pointing this out, I didn't know that the LifeCycle middleware always run.
