### ISSUE TITLE
Major crash when decoding a ClosedRange<> type from query parameters

### ISSUE THREAD

**Issue by jcbriones** [vapor/vapor#3217]
### Describe the issue

ClosedRange<some Numeric> 

### Vapor version

4.102.1

### Operating system and version

MacOS 14.5

### Swift version

5.10

### Steps to reproduce

1. Create a struct that conforms to a decodable and have a property that is ClosedRange<Double> for example

```swift
struct SomeFilterName: Decodable {
    let percentRange: ClosedRange<Double>?
}
```

2. Then create an api request. Here is another example

```swift
routes.get("") { request in
    let filter = try request.query.decode(SomeFilterName.self) // Crash happens here
    return HTTPStatus.ok
}
```

3. Make a request call with a single `percentRange[]=0.1` as part of the query parameter. Then you should expect the crash to happen

### Outcome

`mutating func decode<T: Decodable>(_: T.Type) throws -> T` on `URLEncodedFormDecoder:381` causing some index out of bounds/range because the ClosedRange decodable is expected to have 2 elements but only 1 was provided in the query parameter. 

### Additional notes

It's a convenient way to have support for Ranges, especially used in filtering some data. It would be also make sense to have it something like {{Numeric}}...{{Numeric}} lowerBound...upperBound format instead of array.

**Comment by ptoffy** [comment]
Fixed in #3226
