### ISSUE TITLE
Can’t build on Mac Catalyst since 4.94.0

### ISSUE THREAD

**Issue by makaGeorge** [vapor/vapor#3219]
I recently realized I can no longer build my project with Mac Catalyst as the platform. I’ve then located the first version of Vapor that had this problem: 4.94.0

I get a “No such module ‘System Package’” error when building swift-nio (file is Convenience.swift in NIOFileSystem)

on older versions everything builds fine. 

I’ve tested this on a new empty Xcode project by just adding the Vapor package and compiling, so it’s easily reproducible.

**Comment by 0xTim** [comment]
Can you build NIOFileSystem on MacCatalyst if you check out SwiftNIO and try and build that directly?

**Comment by makaGeorge** [comment]
No. I tried on an empty project and I get the same error.

**Comment by 0xTim** [comment]
Ok so to be clear you're getting an error building NIOFileSystem directly without any Vapor stuff? If so, could you open an issue on SwiftNIO?

**Comment by makaGeorge** [comment]
Ok.

**Comment by makaGeorge** [comment]
swift-system 1.4.0 was released and it includes support for MacCatalyst, so Vapor is now working fine too
