### ISSUE TITLE
No way to specify extra headers for fileio.streamFile?

### ISSUE THREAD

**Issue by llsc12** [vapor/vapor#3221]
**Is your feature request related to a problem? Please describe.**
I can't seem to find a way to specify custom headers for when I'm streaming a file to a client

**Describe the solution you'd like**
A way to specify headers in the streamFile method.

**Comment by 0xTim** [comment]
`streamFile` returns a `Response` you can add headers to:

```swift
let res = req.fileio.streamFile(at: "/path/to/file")
res.headers....
```

**Comment by llsc12** [comment]
my apologies, i'm new to vapor and did try googling quite a lot
