### ISSUE TITLE
Support for HTTP/3 and QUIC?

### ISSUE THREAD

**Issue by ranmocy** [vapor/vapor#3235]
**Is your feature request related to a problem? Please describe.**
HTTP/3 and QUIC would dramatically reduce the time to first byte of requests.
It reduces hand-shake round trips from 4 to 1~2.

**Describe the solution you'd like**
Support HTTP/3 and QUIC protocol, which is implemented by Apple SDKs.

**Describe alternatives you've considered**
https://github.com/swift-quic/swift-quic seems not being active any more.

**Additional context**
HTTP/3 and QUIC are recommended since WWDC2021: https://developer.apple.com/videos/play/wwdc2021/10094/

**Comment by gwynne** [comment]
The implementation in Apple SDKs is not available on Linux, and NIO does not currently support HTTP/3/QUIC. The request for this feature in NIO is being tracked by https://github.com/apple/swift-nio/issues/1730 .

**Comment by marc-medley** [comment]
fyi: [SwiftNIO QUIC 'swift-nio-quic'](https://github.com/apple/swift-nio-quic) pre-release v0.1.0 on 2026.07.02

- [Swift 6.3 and up](https://swift.org/install)
- macOS 26.0 and up or Linux (Ubuntu 22.04+)
- Xcode 26.0 and up (Apple platforms only)

**Comment by 0xTim** [comment]
Vapor 5 should support H3
