### ISSUE TITLE
Not an issue, looking for a real wold example of https://docs.vapor.codes/basics/async/?h=promises#wait

### ISSUE THREAD

**Issue by WilliamFernsV3** [vapor/vapor#3260]
### Describe the issue

Not an issue, looking for a real wold example of https://docs.vapor.codes/basics/async/?h=promises#wait. 

### Vapor version

4.106.3

### Operating system and version

macOS 15.1.1 24B91 arm64

### Swift version

Swift Package Manager - Swift 6.0.2-dev

### Steps to reproduce

None.

### Outcome

I understand that you cannot use `wait` in an event loop thread. Can you please give me a real world example of how I can use `wait`? If it cannot be in an event loop thread, how do I create a `EventLoopFuture` and use it in `configure.swift` for example, without having access to an `eventLoop` instance? Should I pass in `EventLoop` as an argument to create a `EventLoopFuture` outside of an event loop thread, or should I pass in the `EventLoopFuture` as an argument, and then just call it with `wait()`? 

It will mean a lot if you can create a practical, in-depth but simple real world example of how using `wait()` to execute a future synchronously outside an event loop. 

Thanks.

### Additional notes

It will be helpful to add a real word example of using `wait()` as part of the following documentation: https://docs.vapor.codes/basics/async/?h=promises#wait

**Comment by gwynne** [comment]
That particular documentation is unfortunate, in that it is out of date; use of `.wait()` is no longer recommended at all. Use `await` and add `.get()` if the API in question is still based on `EventLoopFuture` and has no Concurrency-based version.

**Comment by gwynne** [comment]
(In fact, that entire section of the docs really should be completely revamped, to be perfectly honest...)

**Comment by WilliamFernsV3** [comment]
Thanks @gwynne ! That makes completely sense. Will use Swift Concurrency `async` and `await` syntax instead of Futures. 

Do you know any maintainers that might be interested in updating the documentation?
