### ISSUE TITLE
Docs issue: Basic install on Mac OS seems to need Swift 6

### ISSUE THREAD

**Issue by cprince-foreflight** [vapor/vapor#3262]
### Describe the issue

Basic install on Mac OS seems to need Swift 6

### Vapor version

Current

### Operating system and version

Mac OS 14.5 (23F79)

### Swift version

Xcode 15.4, Swift 5.10

### Steps to reproduce

1. I did the basic install indicated here: https://docs.vapor.codes/install/macos/
2. Then did the process here: https://docs.vapor.codes/getting-started/hello-world/

### Outcome

I see these issues in Xcode
![Vapor docs issue 1](https://github.com/user-attachments/assets/c0baa13e-3f3b-4cfc-912e-5ad79467c985)

![Vapor docs issue 2](https://github.com/user-attachments/assets/5cb5db1c-60b8-470b-878b-c70701f815bf)

**Comment by 0xTim** [comment]
Yes the current template requires Swift 6 because of the use of Swift Testing.

If you can't update, you could remove the Swift testing stuff and change the package manifest to 5.10 and that should work

**Comment by vzsg** [comment]
I don't think there's anything wrong with requiring Swift 6 – after all, the new version of JWTKit also requires it – but perhaps it would be cleaner if the docs also said that "you need Xcode 16".
