### ISSUE TITLE
How to only query soft deleted models in Fluent?

### ISSUE THREAD

**Issue by WilliamFernsV3** [vapor/vapor#3266]
### Describe the issue

How to only query soft deleted models in Fluent?

### Vapor version

4.106.3

### Operating system and version

macOS 15.1.1 24B91 arm64

### Swift version

Swift Package Manager - Swift 6.0.2-dev

**Comment by gwynne** [comment]
1. Add the `.withDeleted()` modifier to the query to prevent Fluent from excluding soft-deleted models.
2. Add the inverse condition to the query manually.

E.g.:

```swift
let allSoftDeleted = try await MyModel.query(on: req.db)
    .withDeleted()
    .filter(\.$deletedAt != nil)
    .filter(\.$deletedAt < Date())
    .all()
```

**Comment by WilliamFernsV3** [comment]
THanks :)
