### ISSUE TITLE
Debug log: could not load environment files on docker container run

### ISSUE THREAD

**Issue by WilliamFernsV3** [vapor/vapor#3268]
### Describe the issue

The app still works as expected, I am still able to get the environment variables because they are specified in the `docker-compose.yml` file. . 

### Vapor version

4.106.3

### Operating system and version

macOS 15.1.1 24B91 arm64

### Swift version

Swift Package Manager - Swift 6.0.2-dev

### Steps to reproduce

```
app-1  | [ DEBUG ] Could not load .env.production file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/DotEnv.swift:296)
app-1  | [ DEBUG ] Could not load .env file: open(file:oFlag:mode:): No such file or directory (errno: 2) (Vapor/DotEnv.swift:296)
```

Possible solutions:

- Suppress/remove the debug logs
- Add this to the Dockerfile (not sure if this is the best solution, just a workaround I found):
```
# Switch to the new home directory
WORKDIR /app

# Copy built executable and any staged resources from builder
COPY --from=build --chown=vapor:vapor /staging /app
COPY .env .env.* ./ # this got added
```

**Comment by 0xTim** [comment]
These are fine, they-re just informational logs
