### ISSUE TITLE
fatalError in Application.Core.storage.getter triggered when uploading files

### ISSUE THREAD

**Issue by IgorMuzyka** [vapor/vapor#3270]
### Describe the issue

fatalError in Application.Core.storage.getter triggered when uploading files

### Vapor version

4.106.5

### Operating system and version

iOS 18

### Swift version

Swift Package Manager - Swift 6.0.3

### Steps to reproduce

Unknown.

### Outcome

At unknown moment while uploading file a crash happens from here:
```swift
@Sendable private func patch(request: Request) async throws -> Response {
    ...
    let buffer = try await request.body.collect(upTo: Int(length.rawValue))
    // at this point we access fileio which crashes
    try await request.fileio.writeFile(buffer, at: url.path(percentEncoded: false))
    ...
}
```
And the fatal error which causes it is in `Sources/Vapor/Core/Core.swift` at line `120` which is :
```swift
var storage: Storage {
    guard let storage = self.application.storage[Key.self] else {
        // here
        fatalError("Core not configured. Configure with app.core.initialize()")
    }
    return storage
}
```

### Additional notes

If it's of any use. [stack-trace.txt](https://github.com/user-attachments/files/18166790/stack-trace.txt)

**Comment by 0xTim** [comment]
This is iOS right? Some questions

* How are you setting up the application? (I'm assuming you're running an HTTP server inside the iOS app).
* Is this reproducible?
* How do you tear down the application?

The error you're seeing normally means the application has been told to shutdown and you're then trying to handle a request

**Comment by IgorMuzyka** [comment]
@0xTim 
iOS >= 17 
- yes http, the only middleware on the whole app is `CORSMiddleware`
- for users, i'm not able to determine how to reproduce this myself
- this is happening while files are being uploaded and server is running

This is an api which implements [TUS](https://tus.io), with create extension, meaning at the least the previous request to create an upload and maybe few patch requests succeeded.
If server is being stopped that means user had to dismiss view hmm.
Anyway here's how it's being shutdown:
```swift
/// somewhere in model:
Task(priority: priority) { [weak self] in
    guard let self else { return }
    await self.asyncStopServer()
}
/// and the method it calls:
func asyncStopServer() async  {
    guard isRunning else { return }
    do {
        try await server?.stop()
        isRunning = false
    } catch {
        isRunning = false
        self.error = error
    }
    server = .none
}
```

And here's how it's setup:
```swift
func start() async throws {
    try await prepare() // just checks to fail early if misconfigured
    let application = try await Application.make(environment, .singleton)
    try await configure(application)
    try await bootstrap(application)
    self.app = application
    try await application.startup()
}

func stop() async throws {
    guard let app else { return }
    try await app.asyncShutdown()
    self.app = .none
}
private func configure(_ app: Vapor.Application) async throws {
    app.routes.caseInsensitive = false
    app.http.server.configuration.serverName = configuration.server.name
    app.http.server.configuration.hostname = configuration.server.address
    app.http.server.configuration.port = Int(configuration.server.port)
    app.http.server.configuration.tcpNoDelay = true
    app.http.server.configuration.reuseAddress = true
    if let logLevel = configuration.server.logLevel {
        app.http.server.configuration.logger.logLevel = logLevel
    } else {
        #if DEBUG
        app.http.server.configuration.logger.logLevel = .debug
        #else
        app.http.server.configuration.logger.logLevel = .critical
        #endif
    }
    let maxBodySize = Int(
        configuration.upload.chunkSize?.rawValue ?? configuration.upload.maxFileSize.rawValue
    ) + 2000
    app.routes.defaultMaxBodySize = .init(value: maxBodySize)
}

private func bootstrap(_ app: Vapor.Application) async throws {
    app.sessions.configuration.cookieName = configuration.server.name
        .replacingOccurrences(of: " ", with: "-")
    app.sessions.use(.memory)
    app.middleware.use(app.sessions.middleware)
    app.middleware.use(CORSMiddleware(configuration: .default()))
    let webUI = try WebUIController(
        fileSystemQueue: configuration.fileSystemQueue,
        webUIConfiguration: configuration.webUI,
        uploadConfiguration: configuration.upload,
        capabilities: configuration.capabilities,
        baseURL: baseURL,
        sharedDirectoryURL: configuration.directories.shared,
        mountedDirectories: configuration.directories.mounted
    )
    let resources = WebUIResourcesController(localizationDelegate: configuration.webUI.localizationDelegate)
    try app.register(collection: resources)
    try app.register(collection: webUI)
    if configuration.capabilities.upload {
        let upload = UploadController(
            fileSystemQueue: configuration.fileSystemQueue,
            configuration: configuration.upload,
            directories: configuration.directories,
            baseURL: baseURL,
            hooks: configuration.hooks
        )
        try app.register(collection: upload)
    }
    let api = APIController(
        fileSystemQueue: configuration.fileSystemQueue,
        localizationDelegate: configuration.webUI.localizationDelegate,
        reportingDelegate: configuration.reportingDelegate,
        capabilitites: configuration.capabilities,
        directories: configuration.directories,
        hooks: configuration.hooks,
        importComparatorStrategy: configuration.upload.importComparatorStrategy,
        showHiddenFiles: configuration.webUI.showHiddenFiles
    )
    try app.register(collection: api)
}
```

**Comment by IgorMuzyka** [comment]
```swift
private var environment: Environment {
    #if DEBUG
    .init(name: "development", arguments: [ProcessInfo.processInfo.arguments.first!])
    #else
    .init(name: "production", arguments: [ProcessInfo.processInfo.arguments.first!])
    #endif
}
```

**Comment by IgorMuzyka** [comment]
@0xTim if you are suggesting that crash is happening due to user triggering the server shutdown, what would be the correct way to check if we are in that state from within request handling method?

**Comment by 0xTim** [comment]
Well the point is you shouldn't be handling requests if the app is shut down (because the request handler could get torn down at that point). What you should probably be doing is checking that the server is up before sending the request (and then you need to consider what to do if the user backgrounds the app during the upload etc). You might not want to shut the server down when the app is backgrounded but instead do is when the app is about to be killed (it's been a long time since I've done any iOS so I'm not sure on what the best lifecycle hooks are).

As a side note, you definitely want to be running some error middleware as well

**Comment by IgorMuzyka** [comment]
@0xTim checking if the server(iOS) is up from the client(browser) sounds kinda weird cause how do i check if it's alive other than send a request from client? (maybe i'm not understanding what you mean)
The backgrounding shouldn't be the problem, cause app audio session has background mode.
 I guess i'll need some kind of lifecycle handle + middleware then to just reject anything as soon as vapor app is being shut down?

**Comment by 0xTim** [comment]
Wait so you have external browsers making requests to the iOS app running a server? How are you getting past the OS firewall?

If the backgrounding isn't the problem, have you tried not shutting down the app when the app gets backgrounded? Middleware won't help - when the Vapor app is shutdown, it will not respond to requests. The listener will be killed. The issue is you have an inflight request that isn't getting cleanup up properly and we're probably not propagating cancellation too. Or the OS is just killing the app without letting us shutdown the application cleanly.

**Comment by IgorMuzyka** [comment]
@0xTim it's always in local network with the browser, not sure what problem with any firewall i should have, browser file api is limited due to http though, but sufficient for the task. 
My assumption after your comments was that request manages to go through even when app is being(i assume async means it still takes some steps/time to do) shutdown.
But if that's not the case, probably due to async task suspension the request is busy collecting the `offset+octet-stream` body of an upload patch request and by the time it's done it continues to write to disk at which point the `fileio` accessor crashes due to app probably already been spun down and storage not being setup. 
I'm failing to reproduce this myself so this is all is speculative. 
Have no idea about inner workings of cancellation propagation in Vapor. 
Any suggestions on what i should have a look at or read to know more about it?

**Comment by 0xTim** [comment]
First step is reproduce it. Without that it's very hard to know the scenario that causes it
