### ISSUE TITLE
Leaf serious Render Bug

### ISSUE THREAD

**Issue by h4acda** [vapor/vapor#3272]
### Describe the issue

无法渲染\

### Vapor version

4.99.3

### Operating system and version

mac os 15.2

### Swift version

swift 6

### Steps to reproduce

![image](https://github.com/user-attachments/assets/ed492bcc-03b9-4fdb-ace2-1477cf25b156)
![image](https://github.com/user-attachments/assets/9efa1491-7303-423e-be2e-b6696ba560b2)
图1 渲染 图2
图1中 无法 渲染 变量"title"

在 leaf 您回复说  使用"\\\\"
请看 图3
"\\\\" 是可以渲染出 "\\"   同样  后面 是变量   变量 依旧 无法 渲染  请看 图3
![image](https://github.com/user-attachments/assets/afeef970-4f0f-41f0-9917-116ac768d456)

route 代码如下
![image](https://github.com/user-attachments/assets/c7284651-234f-4045-ad13-e679cb74a0d0)

想要的 正确 结果 如下
![image](https://github.com/user-attachments/assets/6e21dd07-f45a-4412-b6be-e73833a648b3)
麻烦 修复 渲染 Bug

**Comment by 0xTim** [comment]
Duplicate of https://github.com/vapor/leaf/issues/234

**Comment by h4acda** [comment]
麻烦您 按照如图所示 操作一次    Bug   没有解决

**Comment by glepnir** [comment]
off topic .. there is GIthub. You should use English if you want others to understand your question better.

**Comment by h4acda** [comment]
翻译成英文也翻译不准确   并且谁规定的必须用英语?   都是做贡献的   凭什么惯的你

**Comment by glepnir** [comment]
You're like a jerk.

**Comment by h4acda** [comment]
你就是个傻逼   没见过你这么没素质的人    你还是人了?

**Comment by h4acda** [comment]
你牛逼个得啊    Fuck

**Comment by h4acda** [comment]
You Are Like a Bitch @glepnir

**Comment by 0xTim** [comment]
Attacks and abusive messages will not be tolerated
