### ISSUE TITLE
Development Container With Hot Reloading

### ISSUE THREAD

**Issue by WilliamFernsV3** [vapor/vapor#3273]
### Please summarize your feature request

It would be nice to develop locally, while running the app in a container, reloading the app when making changes.

### Describe the functionality you're seeking in more detail

Took me a lot of time to setup a development container for Vapor. It would be nice if it supported it out of the box, saving time.

Here are some of the benefits of using a development container instead of developing locally:

- It drastically reduces the pain of deploying your app in a production environment, especially if you use a different operating system locally
- Great for collaborating without encountering problems, because all developers uses the exact same environment for development
    - It is easier and faster for new developers to start collaborating, because there is almost no setup work, other than having docker and a code editor like VS Code installed

Here is a simplified version of how this can be done:
- https://github.com/Agnostic-Software/demo-dev-container
- A video I just made (using nodemon for hot reloading): https://youtu.be/6aiZZNMIn_Q

### Have you considered any alternatives?

Yes. I created my own implementation using nodemon for hot reloading and bind mounts from docker. 

- https://github.com/Agnostic-Software/demo-dev-container
- A video I just made (using nodemon for hot reloading): https://youtu.be/6aiZZNMIn_Q

For hot reloading, I tried using [Ice](https://github.com/jakeheis/Ice), but it does not have Linux support, because it depends on a library called PathKit which does not expose some objects for Linux. Nodemon seems to be the best solution.

**Comment by 0xTim** [comment]
The Swift VSCode extension has an experimental flag for hot reloading. Since this is more a build system thing and the template contains what you need for a dev container I'm going to close this

**Comment by WilliamFernsV3** [comment]
👍
