### ISSUE TITLE
I'm wondering if the current validation system is overly complicated

### ISSUE THREAD

**Issue by Evertt** [vapor/vapor#376]
Why have a `Valid<Email>` type, when you could just have an `Email` type with a failable initializer?

I'm guessing it's not because of the magic `"example@domain.com".validated()` method, because you could just as easily do that with the `Email` type if you'd let that conform to some protocol called `Validator`.

I'm guessing it's also not because of how easily you can compose validators in the current system:

```swift
class Name: ValidationSuite {
    static func validate(input value: String) throws {
        let evaluation = OnlyAlphanumeric.self
            && Count.min(5)
            && Count.max(20)

        try evaluation.validate(input: value)
    }
}
```

Because you could just as easily do this:

```swift
struct Name: Validator {
    let value: String

    required init?(_ value: String) {
        guard value.isOnlyAlphanumeric()
            && value.hasMin(count:  5)
            && value.hasMax(count: 20) else {
            return nil
        }

        self.value = value
    }
}
```

And of course methods like `isOnlyAlphanumeric()` would need to be defined somewhere else, but so would the other validation suites like `OnlyAlphanumeric`. The only difference is that in my model those methods are simply extensions of for example `String`.

Can anyone explain to me the significant benefits of the current system? Because if the benefits are not significant then I propose to ditch that system. I believe having a simpler system with the fewest demands on how to shape your types is always better, because it gives more freedom to the developer.

**Comment by Evertt** [comment]
The system I have in mind would be much simpler. We could have a very simple protocol to allow for the `.validated()` method:

```swift
protocol Validator {
    associatedtype ValueType
    init?(_: ValueType) throws
```

So that we can write stuff like:

```swift
protocol Validatable {
    func validated<T: Validator where T.ValueType == self>() throws -> T
}

extension Validatable {
    func validated<T: Validator where T.ValueType == self>() throws -> T {
        guard let validated = try T(self) else {
            // throw some general error
        }

        return validated
    }
}

extension String: Validatable
```

But that's not very different from what we have. I just wanted to show that we wouldn't lose any features per se. Things just get simpler, like our model would look something like:

```swift
class Person: Model {
    var id: Value?
    var name: Name
    var email: Email
    var age: Age
}

extension Person {
    struct Age: Validator {
        let value: Int

        init?(_ number: Int) {
            guard 18...120 ~= number else {
                return nil // not a valid adult human age
            }

            value = number
        }
    }
}
```

This also happens to give `Age` a nice namespace `Person.Age`, which can come in handy since the age of other things might not have the same limits (a tree for example).

**Comment by LoganWright** [comment]
@Evertt Thanks for another great proposal! We put a lot of time and thought into the current validation system, so I think this warrants a bit of extra discussion time so we can way all the pros and cons effectively.

I'll try and dig in a bit deeper in the next couple days personally, I'm looking forward to seeing some of the feedback on this 👍
