### ISSUE TITLE
Users, roles, authentication, authorization and sessions

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#380]
# Users and roles

Vapor is growing to be a big framework. And big frameworks like these will have a big community that design middlewares and other modules to add functionality.

If Vapor doesn't act before the community does we'll risk Vapor-based plugins to be incompatible.

One plugin might support LDAP authentication, and another might support role management, and yet another one supports OAuth. But if we don't provide a flexible framework for users and roles we could risk segregation.

I think it's important (if not crucial) that we provide this kind of a framework that others can build upon.

## Users

Users always have a few bits of information.

|     Information   |   Description                                  |
--------------------|-------------------------------------------------
| Public identifier | Username/Email                                 |
| Password hash     | Hashes password                                |
| Salt              | Unique binary data per user                    |
| Algorithm         | The hashing algorithm for hashing the password |

The algorithm is mainly there as a backup. Someone might be using PBKDF2<SHA1> initially and switch to PBKDF2 using SHA512 for enhanced security. If you force your users to change their password it would be a big inconvenience.

By doing this you allow older passwords to remain functioning.

Besides these core essential pieces of information I think that we shouldn't encourage developers to hash their user's passwords with a simple hashing algorithm because of rainbow tables.

Therefore I think that `iterations` are also important. KDFs iterate multiple times by repeating a hashing algorithm. It's good practice to make these iterations variable. For PBKDF2 the minimum recommended rotations is 10'000. But by changing the amount of rotations for your users to a random number above 10'000 (but not too high) you can increase the difficulty of cracking the passwords even more.

`rand(500) + 10_000`

## Roles

Roles are also really important. A permission system needs to be thought out although I don't directly have a plan for this yet.

I do think it's important that Roles are to be discussed alongside other discussion subjects here.

---------

# Sessions

## Current crypto weakness

Currently in Vapor we do support sessions. But they're easy to break if you look in the sourcecode.
The session token is generated using 3 constant `String` variables.

`v@p0r`, `s3sS10n` and `k3y`. These constants are not unique, they're completely equal across all vapor websites.

Besides this it makes use of 3 random number strings in the range of `0...9999` (or `10'000`).

The strength of the token is not increased by adding the three constants. And the strength of these 3 random numbers isn't the best. Currently there are 1 trillion possible combinations. Sounds like a lot until you realise that storing these 1 trillion SHA256 hashes as a rainbow table takes up 500GB tops. At this point you've got a medium sized laptop HDD filled with all possible vapor tokens.

## Cryptographic improvements

I propose using a properly random number using the `Darwin` or `Glibc` API. They both allow you to generate random (U)Int32 numbers. A single `UInt32` has over 4 billion combinations.

This random number would be our identifier for the user's session and can be combined with a salt to generate a random token.

## Extra verification steps

The user's session can now still be hijacked by anoher user by simply copying the cookie. This is not entirely preventable, although there are a few methods.

One method would be by recording the IP address of the user and the browser footprint. By reading the headers you can read the user agent string if provided. Along with these there are other footprints that can be recorded.

If you combine these footprints and assign them a weight we could use this weight to determine the validity of the cookie. For IP Addresses the weight would be quite high. But for the browser version the weight should be really low.

The IP addresses could even go as far as to have a weight depending on the change of geolocation. If you were to have moved your IP address across the street or within the same city it could affect the server's decision less than moving to another country (when traveling).

Based on the weight we could invalidate the token to ensure that the account is not hijacked without interrupting user experience.

This verification should be done by the SessionDriver. But there needs to be room for this to be implemented.

## Persistence

Since Fluent has matured I feel like it's important to support persistent session management using either SQLite or MongoDB in the respective officially supported Fluent library. Cross-reboot the information like tokens should be remembered to benefit both user as well as development experience.

## Authorization

I propose the token to be returned to the user to be AES encrypted. The encryption key would be stored in the vapor configuration file and should be different for every Vapor application. The reason is to allow Vapor installations to recognize the tokens from previous sessions. The IV should be set to something unique to the user.

I propose the contents of the encrypted token to contain the user session identification as described above. The user's public identifier (email/username) and their authorized role(s).

For a user logging into the admin-panel the `admin` role would be in the authorization token.

This solution allows us to keep the same IV and key and we can modify parts of the token on the fly. So when someone logs out of the admin panel they'll stay logged in under another (lesser?) role without revoking their session identifier and other important data like their IP address.

## Expiration

Using the above described method of AES we can now also include validation timestamps (like epoch time). This would identify the validity of the token within the token itself as well as other optional metadata.

This method is (of couse) not a replacement for sessions itself but rather an extensible method of token validation.

## Discussion

The only problem I haven't figured out yet is the usage of older tokens. Currently this method would allow users to copy their token and use it within the same physical and virtual enivronment to (for example) re-autheticate as the `admin` role, even though they logged out of the admin panel. This is because the expiration date hasn't been reached yet, and the old token is still recognized when decrypted. This is a problem to be sovled in a discussion.

**Comment by tannernelson** [comment]
This is a great proposal. Let's talk about including this in 0.12 once we push 0.11.

**Comment by Obbut** [comment]
I think that including users, groups and roles in Vapor isn't necessarily a good idea. Different applications may want to have these implemented in their own ways – they may have local users/groups, they may be external (OAuth or LDAP) or they may not be there at all (application servers with only auth keys).

However, including a more abstract access control system seems like a good thing for me. This may contain user-definable permissions that can be applied (required) to certain routes or groups of routes. The application should be able to define the allowed permissions for each request (for example, as middleware) or expose a function or closure that checks if a request has access to a given permission.

I do think that a universal implementation of users & groups is a good idea, which I would like to see as an extension to Vapor – maybe in a separate project, or included in Vapor as a optional (default disabled) component.

**Comment by Joannis** [comment]
This is something I completely agree with. I stay with my opinion that Qutheory (not necessarily Vapor) should provide a basis on which other developers can build. This is I think true for Users, permissions, as well as already implemented functionalities like requests (middlewares)

**Comment by LoganWright** [comment]
Looking at this thread, I propose that we postpone some of the higher level "roles" stuff for now so we can focus on basic authorization of users in a secure way, this means that I'd like some way of modeling. Once we have that, I think it'll be easier to work through what type of role management system people might want. Sometimes these are very bound to databases, so that's something for us to consider

**Comment by bspringston** [comment]
As a swift framework, why not store users on CloudKit and use JWT tokens for sessions?

**Comment by Obbut** [comment]
Aside from the discussion if CloudKit is suitable for such a use, that would not be possible on Linux.

**Comment by bspringston** [comment]
The CloudKit framework itself may not be available yet.  There is a CloudKit JS framework and it is possible to interact with CloudKit web services from Linux.  A key benefit is that users do not have to log into apps as long as they are signed into iCloud on their phone.  Support also exists for users that do not have iCloud accounts and the entire UI is provided for account authorization and setup on the web through CloudKit JS.

**Comment by cihantas** [comment]
I agree with @Joannis and I'm happy this topic is attacked so early. But I have to disagree with @bspringston. Authentication and authorization system like the one Laravel offers provide a basis on which other developers can build. Signing in using iCloud is way to specific. In the beginning we should stick for plain username / password authentication like @Joannis described it.

**Comment by LoganWright** [comment]
Due to complexities associated w/ users getting setup on 06-06 snapshot and Xcode 8, we're shipping 0.13 w/o this feature. It is still a priority.

**Comment by tannernelson** [comment]
This is going to happen with #529
