### ISSUE TITLE
hot code reload

### ISSUE THREAD

**Issue by gakaki** [vapor/vapor#389]
# Feature, Enhancement, or Optimization
swiftexpress has the hot code reload 
is vapor can same hot code reload thank you

**Comment by LoganWright** [comment]
This supports Vapor projects: https://www.npmjs.com/package/gulp-vapor

**Comment by guillaumealgis** [comment]
To add another non-javascript solution to the "reload server on changes", I've been using the following shell scripts (relying on https://github.com/emcrisostomo/fswatch) and it has been working nicely (and is easy enough to customize) : 

**server.sh**
```sh
#!/bin/sh

host="${1:-localhost}"
port="${2:-8080}"

project_name=${PWD##*/}
pid_path="/tmp/vapor-server-$project_name.pid"
server_pid=$(($(cat 2>/dev/null "$pid_path" || echo 0)))

if [ $server_pid -ne 0 ]; then
    kill $server_pid 2>/dev/null && echo "🔄 Changes detected, reloading server"
fi

swift run App serve --env dev --hostname "$host" --port "$port" &
echo $! > "$pid_path"
```

**runserver.sh**
```sh
#!/bin/sh

src_dir="Sources"

type fswatch >/dev/null 2>&1 || { echo 'Error: fswatch not found. Install with brew install fswatch.'; exit 1; }

sh server.sh "$@"
fswatch -r -o "$src_dir" | xargs -n1 -I{} sh server.sh "$@"
```

Make `runserver.sh` executable : `chmod u+x runserver.sh`.

Then run 

```
./runserver.sh 
```

to start the development server. Or 

```
./runserver.sh localhost 8000
```

to change the host and port used (default is `localhost` and `8080`).
