### ISSUE TITLE
Error: Could not determine Swift version (check your .swift-version file)

### ISSUE THREAD

**Issue by iksnae** [vapor/vapor#398]
when executing the `vapor docker build` command, i get the following error:
`Error: Could not determine Swift version (check your .swift-version file)
Note: Make sure you are using Swift 3.0 Snapshot 06-06`
I'm confident I'm using 3.0 as entering `swift --version` returns:
`Apple Swift version 3.0-dev (LLVM cb08d1dbbd, Clang 383859a9c4, Swift 9e8266aaeb)
Target: x86_64-apple-macosx10.9`

**Comment by tannernelson** [comment]
Do you have a `.swift-version` file in the root of your project? This is required for swiftenv to work.
