### ISSUE TITLE
Default view templates for aborted requests

### ISSUE THREAD

**Issue by timominous** [vapor/vapor#418]
# Default view templates for aborted requests

* Author(s): [timominous](https://github.com/timominous)

## Introduction & Motivation

A suite of view templates that would display appropriate information on what caused the request to be aborted when on a development environtment. This will make the development process using vapor much more pleasant.

Here is a sample screenshot from Django:

![Screenshot](http://i.stack.imgur.com/c6EQV.pngl)

## Proposed solution

This would be implemented using a variation of the AbortMiddleware in Application. The switching of abort middleware types would be dependent on the current Environment config.

## Code snippets

No code snippets yet.

## Impact

This shouldn't have to affect current implementations using Vapor and would just add functionality.

## Alternatives considered

None as of the moment.

**Comment by LoganWright** [comment]
@timominous awesome contribution, I believe we had talked about this before some where, so this is definitely something we want!

I think your instincts are right on about Middleware, the only thing we'd really need is a design that's simple enough to use w/o requiring a template engine. 

I'd _prefer_ to not use a template engine just for portability, but I'm open to alternatives.

**Comment by timominous** [comment]
I agree with not having to include a template engine. Was thinking about something in the lines of generated html code as of the moment. Ideas?

**Comment by LoganWright** [comment]
Generated seems fine, we could also start smaller w/ just a basic 404 w/o too much debug info and fill that in later. The info is going to be useful, but also probably the most complex part of the operation. Maybe in interim we could log the request on non-production environment.

**Comment by timominous** [comment]
A stack trace would be great but would be really complicated. Having something like the top part of the screenshot above could be the first phase and more functionality can be added on top of it.

**Comment by timominous** [comment]
What's the community's consensus on this?

**Comment by tannernelson** [comment]
I've been wanting to add something like this for a while. I think it should be a part of the abort middleware.

**Comment by LoganWright** [comment]
I think we're all in agreement, I just assumed this was already approved.

**Comment by timominous** [comment]
@tannernelson Part of the current abort middleware? I was thinking about a new abort middleware that gets swapped out depending on the environemnt config.

@LoganWright  I see. Will assign myself and work on this when I can.

**Comment by tannernelson** [comment]
@timominous If you pass the middleware a pointer to the droplet then it can check environment and create views itself.

**Comment by BrettRToomey** [comment]
Now that Leaf is defaulting with Vapor, cannot we use it for this? I think it would be perfect for this case.

**Comment by LoganWright** [comment]
@tannernelson this is done now, right?

**Comment by tannernelson** [comment]
Yup. We could still make something more useful for debug scenarios, but that can be a separate issue.
