### ISSUE TITLE
Provider configuration should wait until after Application has initialized

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#420]
Playing around with the `Provider` protocol, I'm not sure how useful I'm finding it right now. I expected the boot function to allow me to configure middleware and routes (not just configuring drivers through properties).

However, since providers are booted on application creation, it will crash. I suggest booting them on `app.start()` or something else that will allow me to configure the app object. 

```Swift
public class TestProvider: Provider {
    public func boot(with application: Application) {
        // Neither adding global middleware or a route works
        app.globalMiddleware.append(TestMiddleware())
        app.get("/test") { request in
            return "OH HEY!"
        }
    }
}

public class TestMiddleware: Middleware {
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        return try next.respond(to: request)
    }
}
```

Otherwise, I could accomplish what I wanted to above by asking the developer to do the following:

```Swift
import Vapor

let app = Application()

app.globalMiddleware.append(TestMiddleware())

public class TestMiddleware: Middleware {
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        if request.uri.path == "/test" && request.method == .get {
            return "OH HEY!"
        }
        return try next.respond(to: request)
    }
}
```

**Comment by tannernelson** [comment]
We could add another method like `beforeStart()`. What crash were you getting, though?

**Comment by edjiang** [comment]
The crash is because the Application object is not fully initialized. 

https://github.com/qutheory/vapor/blob/master/Sources/Vapor/Application/Application.swift#L130

Eg, since provider is the first thing to be run, Application.hash is not set when I try to use the application object. Which means that I can't use the Application object, so it crashes.

**Comment by tannernelson** [comment]
The providers aren't booted until here, though: https://github.com/qutheory/vapor/blob/master/Sources/Vapor/Application/Application.swift#L232

**Comment by edjiang** [comment]
Oh right. It's been a bit since I last tried this; I'll use the latest & see if I can find the crash.
