### ISSUE TITLE
Help needed in deployment

### ISSUE THREAD

**Issue by s3lvin** [vapor/vapor#425]
First of all, thank you for this awesome web server. Really appreciate the great work!

Please consider adding documentation for deployment in ubuntu environment with some of the standard servers. I am trying to my app in Google Cloud Platform unsuccessfully.

I have Apache 2 installed on an instance which runs with Ubuntu 14.x. Now I have no clue how to make Vapor work with it. I am stuck need help!

**Comment by LoganWright** [comment]
Hi @s3lvin thanks for the comments!

For documentation on that specific platform, I think you may be the first to go for Google Cloud Platform! We have some people who could likely help in Slack, but in the meantime, you documenting this could help quite a bit.

- Logan

**Comment by tannernelson** [comment]
Closing this for now.
