### ISSUE TITLE
How to route to the controller action?

### ISSUE THREAD

**Issue by imhomin** [vapor/vapor#430]
How to route to the controller action?

**Comment by LoganWright** [comment]
@imhomin I'm not sure I follow, would you mind adding some more context to the question?

**Comment by imhomin** [comment]
How to route to the controller action?

**Comment by imhomin** [comment]
@LoganWright   How to route to the controller action?

**Comment by LoganWright** [comment]
@imhomin You should be able to do:

```
app.get("some/path", yourController.someAction)
```

**Comment by tannernelson** [comment]
We need to add this to the documentation.

**Comment by tannernelson** [comment]
vapor/documentation#17
