### ISSUE TITLE
Dokku Support

### ISSUE THREAD

**Issue by LoganWright** [vapor/vapor#439]
We should make sure to have explicit support for this:

https://github.com/dokku/dokku

**Comment by alexfedosov** [comment]
All is fine at least with dokku 0.5.0.
I've tested different cases and vapor works only if
- you're using this buildpack: `https://github.com/vapor/heroku-buildpack`
- buildpack URL is in the `.buildpacks` file, overwise it doesn't work
- if app `port` is `5000` dokku will bind it in a right way out of the box. If you want to use custom port - you have to update dokku at least to 6.0 and use proxy

**Comment by LoganWright** [comment]
@alexfedosov thanks, sounds like this can be closed!
