### ISSUE TITLE
IoC container & Automatic resolution

### ISSUE THREAD

**Issue by frankieleef** [vapor/vapor#442]
# IoC & Automatic resolution

* Author(s): [Frank](https://github.com/frankieleef)

## Introduction

One of Laravel greatest features is their IoC container. It is a powerful tool for managing class dependencies. Instead of defining the dependencies hard-coded, they are injected on runtime, which allows for a greater flexibility.

## Motivation

One of my motivations is the fact that I can maintain my dependencies properly. Whenever I get more dependencies, I don't want code like this: 

`let vehicle = Vehicle(type: Car(engine: Engine(), wheels: Wheels()))`

Another motivation is that I like to code behind an interface (or protocol). Instead of injecting implementations into my classes, I inject an interface. Whenever I want to swap implementations, I only need to do this at one place in my code.

## Proposed solution

The Application class is the main class of Vapor. This class could be extended by a container. In my mind registering and resolving something to/from a container would look like this.

```swift
let app = Application()

app.bind('vehicle', Vehicle(type: Car())

let vehicle = app.resolve('vehicle') as? Vehicle
// Wil return the Vehicle class with Car as the type
```

The automatic resolution part, although I'm not sure in which way this would be possible in Swift

```swift
// bind the CarProtocol to an implementation of Car
app.bind(CarProtocol, Car)

class Vehicle {
  let _carProtocol: CarProtocol

   init(carProtocol: CarProtocol) {
        // Whenever a carProtocol is recieved, a Car instance will be passed in
        self._carProtocol = carProtocol
     }
}
```

I have absolutely no clue if this matches Vapor's philosophy and in which way it's possible, but I would like to open the discussion and see how other people think about it. Personally I'm a big fan of this implementation inside Laravel, but of course there is also magic going on, which might be a downside.

**Comment by LoganWright** [comment]
As discussed in chat a bit, I think we support a lot of the intentions of this feature. One addition we should make is to add `storage` the way we have on request/response for greater application extensibility via providers.

**Comment by frankieleef** [comment]
Yesterday I had a talk with @LoganWright about this and one of the issues we faced with this implementation was the fact that we were matching on strings. This could possibly result in runtime errors, which needs to be minimized as much as possible. However, we do want the flexibility of being able to switch implementations without modifying all of our other classes. A way we could implement this is by using extensions. This would look like the following.

```swift
extension Application {
   var userRepository: UserRepositoryProtocol{
       get{
          // do all the stuff you need to initialize and return a new instance of a UserRepository
        }
   }
}
```

This way you would be able to use it like this: `app.userRepository.all()`. However, I can image writing an extension for Application directly could be a bit tricky, so it might be a good idea to create a seperate `Storage` or `Container` class that you can write an extension for, so you'll get `app.storage.userRepository`.

I'm also still looking on how we can extends the current providers functionality, so it can be added to providers. @LoganWright , @tannernelson , do you might know a good solution for this?

**Comment by tannernelson** [comment]
What is `UserRepositoryProtocol` trying to achieve?

**Comment by frankieleef** [comment]
The UserRepositoryProtocol is used to force a class to adhere to a contract. When I'm accepting a concrete implementation instead of a protocol, it could be the case that I'm returning an implementation that does not match what's being used in f.e. the controller. Let me explain it by code. Underneath you see that I accept a UserRepositoryProtocol and the controller does not care what kind of implementation it is. All it knows is that there's a contract that it can call methods on, in this case the method `all`.

```swift
extension Application {
    var userRepository: UserRepositoryProtocol{
        get{
            return UserRepository()
            // do all the stuff you need to initialize and return a new instance of a UserRepository
        }
    }
}


public class UsersController : Controller{
    
    let droplet: Droplet
    let userRepository: UserRepositoryProtocol
    public required init(droplet: Droplet){
        self.droplet = droplet
        self.userRepository = droplet.storage.userRepository
    }

    public func index(){
        let users = self.userRepository.all()
   }
}
```

Now let's change the UserRepositoryProtocol to a concrete implementation. As you can see it's UserRepository. In this case the UserRepository still has the method `all`, so that's what I'm calling in my controller.

```swift
extension Application {
    var userRepository: UserRepository{
        get{
            return UserRepository()
            // do all the stuff you need to initialize and return a new instance of a UserRepository
        }
    }
}

public class UsersController : Controller{
    
    let droplet: Droplet
    let userRepository: UserRepository
    public required init(droplet: Droplet){
        self.droplet = droplet
        self.userRepository = droplet.storage.userRepository
    }

    public func index(){
        let users = self.userRepository.all()
   }
}
```

But imagine that I change the UserRepository to UsersMongoRepository. It would look like this:

```swift
extension Application {
    var userRepository: UserMongoRepository{
        get{
            return UserMongoRepository()
            // do all the stuff you need to initialize and return a new instance of a UserRepository
        }
    }
}

public class UsersController : Controller{
    
    let droplet: Droplet
    let userRepository: UserMongoRepository
    public required init(droplet: Droplet){
        self.droplet = droplet
        self.userRepository = droplet.storage.userRepository
    }

    public func index(){
        let users = self.userRepository.all()
   }
}
```

But the problem here is that the controller can not rely on the fact that it has a `all` method. I could decide to rename it to `getAll`. However, this will result in compile errors and to make this work I need to change the `all` in my controller to `getAll`. That's something I don't want. Whenever I change my implementation, I don't want to touch the rest of my classes to make it work.

I hope this explanation works for you :) If you have any questions, let me know!

**Comment by tannernelson** [comment]
If you need to use the `all()` function, then that function will have to be declared in the `UserRepositoryProtocol`. All of this seems like it would work. The only thing we need is a storage property on the droplet.

```
protocol UserRepository {
   static func all() -> [User]
}
```

```
extension Droplet {
    var userRepository: UserRepository? { 
        get { return storage["userRepository] as? UserRepository }
        set { storage["userRepository] = newValue }
    }
}
```


```
final class MyUserRepository: UserRepository {
       static func all() -> [User] { return [] }
}

let drop = Droplet()
drop.userRepository = MyUserRepository()
```

**Comment by frankieleef** [comment]
Exactly! :) I will start working on this.

The only thing I'm still wondering is if we should create the storage object on the droplet itself, or create a separate class that holds the storage. This so that people can write an extension for that class, instead of directly for Droplet. So are there any potential problems when writing an extension for Droplet directly?

**Comment by LoganWright** [comment]
@frankieleef @tannernelson I think whatever we do, we should seek parity w/ `HTTPMessage` which uses `storage: [String: Any]`. I think that's a good introduction for now, but I'm also open to proposals for a type and what sort of benefits it could add. Right now the dictionary is a little loose, so if a new type could give us more stability, could be nice.

Summary

- Let's do storage now
- Continue discussion on custom object

**Comment by tannernelson** [comment]
This should be achievable with droplet storage now.
