### ISSUE TITLE
Vapor couldn't make database table  preparations unlike in mysql

### ISSUE THREAD

**Issue by c1404570** [vapor/vapor#447]
I have found a work around to make model and database function properly , hope this helps :

************in the sqlite database make a fluent table and corresponding model table ;****************
SQLITE3 Database/database.sqlite
CREATE TABLE fluent(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL); 
CREATE TABLE surveys(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT  not NULL, country TEXT  not NULL, time INT  not NULL);
***************** this is model*********************
import Vapor
import Foundation

final class Survey: Model {
var id: Value?
var name: String
var country: String
var time: Int

init(name: String, country: String, time: Int) {
    self.name = name
    self.country = country
            self.time = time
}

init(serialized: [String: Value]) {
    name = serialized["name"].string ?? ""
            country = serialized["country"].string ?? ""
            time = serialized["time"].int ?? 0
}

}

extension Survey: JSONRepresentable {
func makeJSON() -> Vapor.JSON {
return JSON([
"id": "(id!)",
"name": "(name)",
"country": "(country)",
"time": "(time)"
])
}
}
********************************************************************
this is the script in main.swift file:

import Vapor
import VaporMustache
import Foundation
import Fluent
//import VaporMySQL
import VaporSQLite

let sqlite = try VaporSQLite.Provider(path: "/home/b/sqlite_travel/Database/database.sqlite")
let drop = Droplet(providers: [sqlite], preparations:[Survey.self] )

/**
Calls survey form template

*/
drop.get("survey") { request in 
	return try drop.view("survey.html")
}

/**
posts data received from survey form 
*/
drop.post("surveys") { request in

let name = request.data["name"].string ?? "no name"
let country = request.data["country"].string ?? "no country"
let time = NSDate().timeIntervalSince1970.int ?? 0

var survey = Survey(name: name, country: country, time: time)
try survey.save()
return survey

}

**Comment by c1404570** [comment]
I have found a work around , hope this helps :
***************** this is model*********************
import Vapor
import Foundation



final class Survey: Model {
    var id: Value?
        var name: String
        var country: String
        var time: Int


    init(name: String, country: String, time: Int) {
        self.name = name
        self.country = country
                self.time = time
    }

    init(serialized: [String: Value]) {
        name = serialized["name"].string ?? ""
                country = serialized["country"].string ?? ""
                time = serialized["time"].int ?? 0
    }
}

extension Survey: JSONRepresentable {
    **func makeJSON() -> Vapor.JSON {**
        return JSON([
            "id": "\(id)",
                        "name": "\(name)",
                        "country":  "\(country)",
                        "time":  "\(time)"
        ])
    }
}
************************************************
in the sqlite database make a fluent table ;
CREATE TABLE fluent(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL); 

******************************************************************
this is the script in main.swift file:

drop.post("surveys") { request in 

	let name = request.data["name"].string ?? "no name"
	let country = request.data["country"].string ?? "no country"
	let time = NSDate().timeIntervalSince1970.int ?? 0

	var survey = Survey(name: name, country: country, time: time)
	try survey.save()
	return survey

}

**Comment by c1404570** [comment]
But it doesn't automatically create sqlite database :+1:
fatal error: Error raised at top level: SQLite.SQLite.Error.connection("unable to open da                                  tabase file"): file /home/buildnode/jenkins/workspace/oss-swift-package-linux-ubuntu-15_1                                  0/swift/stdlib/public/core/ErrorType.swift, line 152
Current stack trace:
0    libswiftCore.so                    0x00007f95a45961d0 swift_reportError + 117
1    libswiftCore.so                    0x00007f95a45a7440 _swift_stdlib_reportFatalError                                  InFile + 103
2    libswiftCore.so                    0x00007f95a454f073 <unavailable> + 0
3    libswiftCore.so                    0x00007f95a454d7af <unavailable> + 0
4    libswiftCore.so                    0x00007f95a4552c8e <unavailable> + 0
5    libswiftCore.so                    0x00007f95a43c5c3f <unavailable> + 0
6    libswiftCore.so                    0x00007f95a4503b79 <unavailable> + 0
7    libswiftCore.so                    0x00007f95a450332f <unavailable> + 0
8    libswiftCore.so                    0x00007f95a45033bf <unavailable> + 0
9    libswiftCore.so                    0x00007f95a43c5c3f <unavailable> + 0
10   libswiftCore.so                    0x00007f95a43c5870 _assertionFailed(StaticString,                                   String, StaticString, UInt, flags : UInt32) -> () + 187
11   libswiftCore.so                    0x00007f95a43e84c2 <unavailable> + 0
12   App                                0x000000000041a974 <unavailable> + 0
13   libc.so.6                          0x00007f95a274b9d0 __libc_start_main + 240
14   App                                0x00000000004199b9 <unavailable> + 0
Illegal instruction
Error: Run failed.

**Comment by adriencanterot** [comment]
I just implemented the schema function in the fluent-sqlite driver so preparations with sqlite should work now

**Comment by tannernelson** [comment]
This looks like an issue with SQLite configuration. Closing for now.
