### ISSUE TITLE
Getting socket errors with middleware trying to access headers

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/vapor#454]
I was working on a sample project, [here is the code](https://github.com/kdawgwilk/ToDoAPI) and when trying to send this request from Paw and also Postman:
```
GET / HTTP/1.1
Authorization: Basic XXXXXXXXXXXXXXXXX
Host: localhost:8080
Connection: close
User-Agent: Paw/2.3.4 (Macintosh; OS X/10.11.5) GCDHTTPRequest
```

I get the following response
```
Server Error: Socket failed with code 0 ("Success") [unparsableBytes] "Unknown error"
```

**Comment by tannernelson** [comment]
@kdawgwilk are you still seeing this issue? Closing this for now since it's very old.
