### ISSUE TITLE
Support overriding request method

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/vapor#472]
# Feature: Support overriding request method

* Author: [Kdawgwilk](https://github.com/kdawgwilk)

## Introduction

Add support for overriding the request method by passing a `_METHOD` (or similar) parameter in a POST request that Vapor will then treat the request method as the type that was passed.

## Motivation

I previously had to do use a similar workaround when using the SlimPHP framework to be able to send a PATCH/PUT/DELETE request when using a form because html form tags only allow use of the methods GET/POST ([documented here](http://www.w3schools.com/tags/att_form_method.asp))

[Slims Docs explaining this](http://www.slimframework.com/docs/objects/request.html#the-request-method)

## Proposed solution

Vapor would check incoming POST requests to see if they include a `_METHOD` (or similar) parameter and if the value is a valid request method type then vapor would call the valid passed method route handler.

## Code snippets

Ideally this wouldn't require changes to server side code but Vapor would just route the request to the right route handler after checking for the override in the POST params

## Impact

Shouldn't affect current Vapor servers.  However I am not sure of the security implications of adding this feature so if anyone that who's specialty is security could chime in I would appreciate it

## Alternatives considered

SlimPHP also supports sending a header `X-Http-Method-Override: PUT` that will also override the request method.  I can't think of any specific use cases where this would be needed but it seems this could also be implemented without much effort

**Comment by LoganWright** [comment]
@kdawgwilk @tannernelson is there any sort of security concerns associated w/ this that we should check the type of request before routing?

It seems like forwarding manually in Vapor would solve the issue w/o a lot of overhead internally for what seems like a narrow use case.

**Comment by tannernelson** [comment]
Laravel does this, so I don't think there should be any security concerns. We could either handle in the Engine or in the Droplet. Might make the most sense in the droplet since it's non-standard HTTP behavior.

**Comment by LoganWright** [comment]
This can be accomplished through middleware, I'd like to see it introduced that way.

**Comment by LoganWright** [comment]
@kdawgwilk @tannernelson 

Just looked in, and we need to change the Droplet's responder to look more like this:

```
        let routerResponder = Request.Handler { [weak self] request in
            if let handler = self?.router.route(request, with: request) {
                return try handler.respond(to: request)
            } else {
                // Default not found handler
                let normal: [Method] = [.get, .post, .put, .patch, .delete]

                if normal.contains(request.method) {
                    throw Abort.notFound
                } else if case .options = request.method {
                    return Response(status: .ok, headers: [
                        "Allow": "OPTIONS"
                        ])
                } else {
                    return Response(status: .notImplemented)
                }
            }

        }

        // Loop through middlewares in order
        responder = middleware.reversed().chain(to: routerResponder)
```

Then it's easy to add through middleware. Right now, we're actually routing the request _before_ putting it through middleware which I think is incorrect either way.

I'll patch this in later, just leaving here as a reminder.

**Comment by tannernelson** [comment]
Closing this for now, since projects can easily add this functionality as middleware themselves.

**Comment by kdawgwilk** [comment]
@tannernelson will it be added in a future version with built in support like SlimPHP and Laravel do?

**Comment by tannernelson** [comment]
Since you can easily add it yourself with middleware, there's not a huge incentive for Vapor to include it by default.

**Comment by koenpunt** [comment]
> since projects can easily add this functionality as middleware themselves.

This is an old issue, but I'm having trouble implementing this functionality as middleware, because the default responder parses the routes and handles the url before going through middleware.
What would be the recommended approach with Vapor 4.0?

**Comment by 0xTim** [comment]
I'm not sure if there's a good way to solve this in Vapor 4 because of the way the responder is built. The easiest way would be to register a route handler for all HTTP methods and in the route handler check the method and call whichever function you need
