### ISSUE TITLE
Found invalid inferred toolchain error when installing toolbox in ubuntu.

### ISSUE THREAD

**Issue by FrainL** [vapor/vapor#474]
![screen shot 2016-07-22 at 2 36 54 am](https://cloud.githubusercontent.com/assets/15017942/17034427/3d865554-4fb5-11e6-9e19-8f122d8ed589.png)
By the way, thanks for the great work, really amazing :  )

**Comment by FrainL** [comment]
![screen shot 2016-07-22 at 2 40 14 am](https://cloud.githubusercontent.com/assets/15017942/17034537/a9d102a4-4fb5-11e6-9fce-90997e3dc0be.png)

**Comment by tannernelson** [comment]
Thanks!

I've never seen that error before.... I would try restarting the server you're installing on. 
If that doesn't work, try compiling the toolbox from source. It's the `qutheory/vapor-toolbox` repo.

**Comment by FrainL** [comment]
found this
![screen shot 2016-07-22 at 1 08 54 pm](https://cloud.githubusercontent.com/assets/15017942/17047167/80af4dce-500d-11e6-8e7d-96184a25ccde.png)

**Comment by tannernelson** [comment]
You need to compile using the Swift Package Manager. So, `swift build` in the root directory (where the `Package.swift` file is)

**Comment by FrainL** [comment]
😄💦💦 Thanks for help!
I'm not so good at using linux ,not to mention using swift in linux.
Did you receive my email?
