### ISSUE TITLE
Smart upgrade with notification and impact

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#479]
Whether Wordpress roll out new updates, some plugins will be impact that seem like simple thing can be smarter. So I thought an idea how we can make a safe web framework and plugins upgrade that Vapor could implement a scanner/validation that checks for:
- Versioning compatibility if plugins or modules can support newer web framework version
- Update APIs if there are breaking change
- Security Update if there are impact that will cause plugins or modules to fail.
etc.

This could be similar to Toolbox.

**Comment by tannernelson** [comment]
We will definitely be doing this with versions of Vapor >= 1.0
