### ISSUE TITLE
CSRF Support

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#485]
Cross-site request forgery is a problem that all sites face. I think Vapor should implement a CSRF strategy for devs to use.

Here's a good guide to get started: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by LoganWright** [comment]
I saw some in the docs about CORS, ended up building a little middleware here. Might be able to adapt for more comprehensive CSRF support: https://github.com/vapor/todo-example/blob/master/Sources/App/Middleware/CorsMiddleware.swift

Excuse me if it's misguided, still researching.

**Comment by Lidbetter** [comment]
@LoganWright I can see that middleware being useful for almost everyone, but it doesn't help with csrf attacks (except perhaps when initiated from userland js [citation needed])


In the same vein as CSRF, sending an `X-Frame-Options` header is needed to mitigate [click jacking](https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet), [info](https://www.owasp.org/index.php/Clickjacking) 

A sensible default is `X-Frame-Options: SAMEORIGIN` provides a reasonable level of protection and will prevent a bunch of support issues for those who end up trying to use some part of their own site in a frame - having said that I don't think it's that common so maybe `DENY` might be better.

**Comment by BrettRToomey** [comment]
Closed due to inactivity. Feel free to reopen.

**Comment by aurawindsurfing** [comment]
Hi, just as someone who lobes swift and check vapour every so ofter to see if it is production ready I need to say That this puts me off a little. As far as I understand CRSF is known issue for any web app, Vapour is a web franework and as such should make a life easy for web developer. I'm not that technical to know if I need CRSF or not, but knowing that if I use Vapour Ill be safe woukd be greatly appreciated. 

Thanks!

**Comment by 0xTim** [comment]
@aurawindsurfing CSRF is definitely an issue but the majority of attacks can be mitigated with proper use of CSP and Cookie hardening. I've added in most of the groundwork to either the Cookie objects in Vapor or with the [Vapor Security Headers](https://github.com/brokenhandsio/VaporSecurityHeaders) library. I'm working on a way to either integrate CSRF protections in to VSH or as a separate library for old browsers that don't support CSP or Cookie prefixes/same site, but haven't had much time recently.
