### ISSUE TITLE
Server error appears after application sits idle

### ISSUE THREAD

**Issue by fwgreen** [vapor/vapor#492]
# Bug
If my application is idle for a few minutes, this message appears at the command line:
```
Server error: dispatch(Engine.HTTPParserError.streamEmpty)
```
However, the application continues to run without issue.

Vapor 0.14
Swift 3.0-PREVIEW-2
Ubuntu 15.10 (VirtualBox)

**Comment by joernroeder** [comment]
Same behaviour here! I'm also able to reproduce the error by running `curl http://example.qutheory.io/json` pointing to my local docker running the example app.

**Comment by mikecsh** [comment]
I'm also seeing this locally on Mac and in a Docker Ubuntu 14.04 container.

**Comment by tannernelson** [comment]
This could be related to VaporMySQL

**Comment by Joannis** [comment]
Not just MySQL

**Comment by joernroeder** [comment]
my route handler just returns plain son, no sql involved…

```
drop.get("/") { request in
    return try JSON([
        "number": 123,
        "string": "test",
        "array": try JSON([
            0, 1, 2, 3
        ])
    ])
}
```

**Comment by tannernelson** [comment]
Mentioned in #523
