### ISSUE TITLE
Add a default path of / for cookies

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#495]
So I figured out what was causing the session error -- it was 3 hours of debugging and tearing out my hair today.

When I set a cookie on a page that's not on the root directory (for instance /login/facebook), browsers implicitly set the cookie for that path. Same with using sessions. 

Even 

```Swift
let cookie = Cookie(name: "TurnstileSession", value: sessionID, expires: "Wed, 13 Jan 2021 22:23:01 GMT", maxAge: nil, domain: "localhost", path: "/", secure: false, HTTPOnly: false)
response.cookies = Cookies(arrayLiteral: cookie)
```

was not working for me, although that's a bug fixed in #473.

IDK if setting the default path as `/` is the right thing to do, but maybe we should look into it. Especially for the convenience subscript of `cookie["TEST"]`.

Right now I'm using a workaround of:

```Swift
response.headers["Set-Cookie"] = "SessionID=\(sessionID); Path=/;"
```

**Comment by LoganWright** [comment]
Seems like a good one to get in. I believe we could do this in a 15.1 w/o breaking source.

**Comment by edjiang** [comment]
Awesome! No need to rush these; I have workarounds for now and I'm probably not going to migrate to 0.15 until late next week. I have a few things to do early next week =-]

**Comment by tannernelson** [comment]
Got this in master.
