### ISSUE TITLE
Improve API for cookies

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#497]
Currently, the cookies API has a setter that looks like this:

```Swift
Cookie(name: <#T##String#>, value: <#T##String#>, expires: <#T##String?#>, maxAge: <#T##Int?#>, domain: <#T##String?#>, path: <#T##String?#>, secure: <#T##Bool#>, HTTPOnly: <#T##Bool#>)
```

Several things that could be improved about this API:

1. expires: use a Swift Date object or something similar (not sure about its status in Foundation)
2. maxAge: see above. 

Also, to delete a cookie, standard practice is to set the expires time to something in the past. Using this API, you'd have to:

```Swift
let deleteCookie = Cookie(name: "name", value: "", expires: "Thu, 01 Jan 1970 00:00:00 GMT", maxAge: nil, domain: nil, path: "/", secure: false, HTTPOnly: false)
response.cookies = Cookies(arrayLiteral: deleteCookie)
```

Would be nicer to have an API like:

```Swift
response.cookies["test"] = Cookie.delete 
```

**Comment by tannernelson** [comment]
We have this now! woot
