### ISSUE TITLE
Security features and changes in Vapor

### ISSUE THREAD

**Issue by czechboy0** [vapor/vapor#500]
(This ticket was created as a reaction to #485)

I'm glad to see some security-focused tickets! While I agree that there is a lot Vapor can provide for devs to prevent attacks, I think there needs to be a more general discussion about where that goes and what the policy for such improvements is.

An example could be: a new qutheory/vapor-security repo that provides easily pluggable tools to increase security. For example, a Origin/Referer Header check (the simplest but pretty effective protection against CSRF) can be implemented as a Middleware. Other defenses could take different forms.

So before we start dropping defense mechanisms in in an ad-hoc manner, I think a discussion and a policy for how those get discussed/implemented should happen first. Not to scare anyone, but merging the first implementation (that could be purposefully built with hard-to-see holes) can create the appearance of protection, but could actually be more harmful. 

I'm suggesting:
- developing a separate policy for security-related issues/patches
- ensuring we don't create a veil of security features which are not well implemented

While I'd be happy to be involved in this (I've studied some crypto and infosec this year), I think it'd be best to politely get inspired by established web frameworks written in old and "boring" languages - and adapt them to Vapor and Swift.

Happy to hear your thoughts below 🎉

**Comment by Joannis** [comment]
Agreed. We need careful planning for more advanced security features. Although I believe we need to be "secure by default". Which means that security features are enabled and integrated in Vapor by default.

But we needn't create security features that are half-implemented. That harms more than it does good.

I'd love to have a proper discussion about this ticket.

**Comment by LoganWright** [comment]
Hey @Joannis and @czechboy0 Just chiming in to get this ticket back up. 

Right now, we've just merged the Authorization work, wondering if there's some next steps people think we should work towards.

**Comment by LoganWright** [comment]
Not much traffic here, I think w/ LibreSSL, Crypto, and Turnstile we've provided quite a bit generally. If there's some specific additions we can make, let's open some focused high priority issues.
