### ISSUE TITLE
Layouting Engine

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#503]
It would be awesome for Vapor to support the concept of "layouts" in its templating engine.

Looking at https://github.com/ericf/express-handlebars#layouts:

>A layout is simply a Handlebars template with a `{{{body}}}` placeholder. Usually it will be an HTML page wrapper into which views will be rendered.

This could look like the following in Vapor:

```Swift
try drop.render("note.mustache", layout: "global.mustache")
```

The could also be a default layout, making it as easy as:

```Swift
try drop.render("note.mustache")
```

In addition, there might be some global context information for the layouts. Eg, logged in information, error banners, etc. Adding them each time you use `drop.render` is a bit exhausting. 

We could look into adding context into the request object itself, so middleware can add data to the layout context.

This would then look like:

```Swift
// BEFORE
drop.grouped(AuthenticationMiddleware()) { group in
    group.get("/") { request in
        try drop.render("note.mustache", context: ["loggedIn": request.user!.authenticated])
    }
}

// AFTER
drop.grouped(AuthenticationMiddleware()) { group in
    group.get("/") { request in
        try request.render("note.mustache")
    }
}
```

**Comment by tannernelson** [comment]
Here's what I'm thinking:

```swift
drop.view.context = [
	"title": "Hello, World!"
]
drop.view.layout = "layout.mustache"
```

```swift
app.get("users", User.self) { req, user in
	return drop.view.render("user.mustache", context: [
		"name": user.name
	])
}
```

`layout.mustache`
```mustache
<html>
	<head>
		<title>{{ title }}</title>
	</head>
	<body>
		{{> yield}}
	</body>
</html>
```

`user.mustache`
```mustache
Hello {{ name }}
```

`Rendered`
```html
<html>
	<head>
		<title>Hello, World!</title>
	</head>
	<body>
		Hello Bob
	</body>
</html>
```

**Comment by Joannis** [comment]
I think any layouting engine needs proper bindings to the I18n engine. I've been discussing this with @Obbut earlier today. And I think `{{..}}` paired with filter options are great. Especially in combination with literals and statements inside it could be *really* powerful.

I think that if the layout engine becomes similar to vuejs.org 's engine we'll be golden.

```html
...
<h1>{{"Welcome to my website" | translate}}</h2>
<p>
{{{article}}}
</p>
...
```

or

```html
...
<h1>{{"Welcome to my website" | translate}}</h2>
<p>
{{article | markdown}}
</p>
...
```

And I can name many more examples

**Comment by edjiang** [comment]
Hey @tannernelson, is your example's context with a global context? Since the title is different on each page, so the drop.view.context could have a lot of contention from requests on different threads...

**Comment by tannernelson** [comment]
@edjiang That's a good point. That would make a good static global context, but for middleware maybe something like this would work better.

```swift
extension View: HTTP.ResponseRepresentable {
    func makeResponse() -> Response {
        let response = Response()
        response.view = self
        return response
    }
}
```

```swift
extension Response {
    public var view: View? { // hold view in storage }
}
```

```swift
func respond(to: Request, next: Responder) -> Response {
    let response = try next.respond(to: request)
    if let view = view {
        view.context["title"] = "My specific page title"
    }
    return response
}
```

**Comment by tannernelson** [comment]
Moved to: https://github.com/vapor/leaf/issues/5
