### ISSUE TITLE
RequestParameterInitializable

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#504]
# Feature: RequestParameterInitializable
- Author(s): [Joannis Orlandos](https://github.com/joannis)
## Introduction

QueryParameters are widely used for applying filters to the requested data within the URL. The filtering functionality of the parameters on a request is not only useful for creating filters in a REST API. But also on pages where data can be filtered server side. Be it a table or blog. The paginate functionality is usually based on Parameters. Although there's no transparent way of incorporating these QueryParameters. But QueryParameters are a powerful tool for interacting with user requests since they can copy the URL and maintain the filters.
## Motivation

Within my attempts to create a clean API on top of Vapor I found that query parameters are not to be ignored. I tried to create something transparent that wouldn't need my attention for converting QueryParameters to the filter object I wanted. Most people have different goals for using QueryParameters for a filter. Some use it for paginations, others for database interactions. User filtering, API calls.. etc.
## Proposed solution

I propose creating a protocol that allows a struct or class complying to this protocol to be initializable with the QueryParameters. Similar to the `RequestInitializable` solution for Requests.
## Code snippets

Note: Oriented towards MongoDB

``` swift
protocol APIModel {
    associatedtype Identifier
    associatedtype Filter: QueryParameterInitializable

    static func resolve(identifier: Identifier) throws -> Self?
    static func discover(constraints: Filter) throws -> [Self]?
}

struct UserFilter: QueryParameterInitializable, MongoKitten.QueryProtocol {
    let username: String? = nil
    let age: Int? = nil

    init(queryParameters: [String: String]) {
        self.username = queryParameters["username"]?.string
        self.age = queryParameters["age"]?.string
    }

    var data: Document {
        var doc: Document = [:]
        if let username = username {
            doc["username"] = ~username
        }
        ....
    }
}

extension User: APIModel {
    typealias Identifier = ObjectId
    typealias Filter = UserFilter

    static let collection: Collection = db["users"]

    static func discover(constraints: Filter) throws -> [User]? {
        return try collection.find(matching: contraints.data)
    }
}
```
## Impact

There'll be zero impact on the Vapor codebase and zero impact on the existing applications build with Vapor.
## Alternatives considered

The alternative is to implement this yourself in every Vapor application that uses this.

**Comment by tannernelson** [comment]
This is interesting. I think a good first step would be having `RequestInitializable` as a more well-defined and useful class. 

It looks like what you are doing here would be similar to something like.

```swift
try User.query().filter(request).all()

**Comment by Joannis** [comment]
It completely is equal to that
