### ISSUE TITLE
Add support for Gzip (Server and Client)

### ISSUE THREAD

**Issue by czechboy0** [vapor/vapor#505]
Unless developers put Vapor behind Nginx or similar, they can't take advantage of the ubiquity of support of the gzip transfer encoding. It's a huge bandwidth and time saver, so I think Vapor should add support for it, either automatically (as a required dependency) or optionally (as an add-on to Vapor in the form of a Middleware).

I actually build this middleware (S4.Middleware) already: https://github.com/Zewo/gzip
It'd be great to make a Vapor adapter for it.

Extra points: currently, as far as I can see, Vapor Client doesn't support middlewares - I think it should, so that it can receive gzipped responses when doing cross-server queries.

**Comment by tannernelson** [comment]
We should definitely support Gzip and client middleware. @loga

**Comment by LoganWright** [comment]
I'd like to bring @Joannis into this convo as well, I remember he had some thoughts on gzip. Definitely seems standard enough to have some type of support for.

**Comment by Joannis** [comment]
I've been trying to port GZip to swift. I've made quite some progress and quite some mess. Needs testing soon and cleaning up. But GZip is really important because it's the basis for `.zip` alongside many other formats including `XLSX`

**Comment by czechboy0** [comment]
So I gave it a try: https://github.com/czechboy0/gzip-vapor.

Would be great if `Client` also supported middlewares (I added both a Server and a Client gzip middleware in that repo)

**Comment by czechboy0** [comment]
Also, I'll need help there with zipping the chunked body, not really sure how to work with it. Help (PRs) appreciated: https://github.com/czechboy0/gzip-vapor/blob/master/Sources/gzip-vapor/GzipMiddleware.swift#L60

**Comment by czechboy0** [comment]
But, if you're interested, I'm already running Vapor with gzip here (check the headers): http://pong.honza.tech/status

**Comment by czechboy0** [comment]
Update: I actually got the chunked body to work, I implemented a GzipStream that complies to Transport.Stream. Give version 0.2.0 a try, all should be working.

**Comment by BrettRToomey** [comment]
Closing. Feel free to reopen if this is still up for discussion.
