### ISSUE TITLE
JSON initialization with array

### ISSUE THREAD

**Issue by UberJason** [vapor/vapor#506]
Am I going crazy or missing something simple? See following screenshot:

![screen shot 2016-08-02 at 4 24 35 pm](https://cloud.githubusercontent.com/assets/5779307/17343886/e8a80b6e-58cd-11e6-9088-d8d790b132c1.png)

Basically JSON initializer with array literal works, but a variable fails. (Also fails if I explicitly state the type, i.e. `let list: [String] = ["foo", "bar"]`.)

Using Vapor 0.15 and Swift Development Snapshot 2016-07-25 (a).

**Comment by tannernelson** [comment]
Try this:

```swift
let json = try JSON(node: list)
```

**Comment by UberJason** [comment]
Thank you, that workaround works - but my mind is still boggled. Is this a bug in your stuff or a bug in Swift? It seems like the array variable and the array literal would be completely identical...

**Comment by tannernelson** [comment]
The init methods can be a little difficult to work with. Homogenous vs non homogenous arrays need different inits. the `node: ` init covers all of these and we're going to push that as the default for JSON in the updated docs.

**Comment by UberJason** [comment]
I see - thank you for the explanation, and for being super responsive in general! :)
