### ISSUE TITLE
can't install vapor, while I use xCode 8 beta 4

### ISSUE THREAD

**Issue by faklyasgyuri** [vapor/vapor#507]
I try to install Vapor with this command > curl -sL check.qutheory.io | bash
but I always get two warnings, first, that you don't have swiftenv installed, but it is not true. I have installed and use it. Second, that my command line tools version is incorrect, > 
Correct: Xcode 8.0 (8S174q)
Current: Xcode 8.0
Build version 8S188o
I have installed xCode 8.0 beta 4 and it's annoying, that I can't download xCode 8.0 beta 3, so if this is the problem I can't do anything.
And I get an error message too, that I have invalid swift version, I must have installed swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a, but I don't know why get this message, because I download and install and set this snapshot. I can check it with swiftenv global and the result is DEVELOPMENT-SNAPSHOT-2016-07-25-a, so the correct snapshot was installed. I really don't know what did I in a wrong way, so please someone, who can, help me. Thanks.

**Comment by LoganWright** [comment]
Hi @faklyasgyuri 

We made a video that can hopefully help get you setup!

https://www.youtube.com/watch?v=YxvQo-EH2AA

Join us in Slack at http://vapor.team and we'll get you hooked up if the video doesn't help.

**Comment by faklyasgyuri** [comment]
I did everything based on this video. My problems was, that I installed development snapshot, but this command failed  check.qutheory.io | bash that swift version is not good and I don't know why. I thought that because I have xCode 8 beta 4.0

**Comment by faklyasgyuri** [comment]
$ swiftenv global
DEVELOPMENT-SNAPSHOT-2016-07-25-a

**Comment by tannernelson** [comment]
We may need to update the check script to support Xcode 8 beta 4.

**Comment by faklyasgyuri** [comment]
Anyway I tried to hack a little your script. I write and run an own script without checking swift version and I could install vapor, than I would like to install mysql with it> vapor xcode --mysql and I got the following> 
Fetching Dependencies [Failed]
Error: error:: no Package.swift found
Any idea for this?

**Comment by tannernelson** [comment]
`vapor xcode` runs inside of the directory for a Swift 3 package to generate an Xcode project for it.

**Comment by faklyasgyuri** [comment]
Than I really don't understand something. I would like to install your MySQL lib into my Xcode Project to be able to remote a MySQL database from iPhone. I thought after running this four line of codes> 
brew install mysql
brew link mysql
mysql.server start
swift build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib
MySQL lib will be installed on my xCode and after that I will be able to import MySQL and use its functions. Anyway last command didn't work, while I had xCode 7.3 and used Swift 2.2, so I upgrade both of them and installed vapor with that ugly way, what I have written below, and after tried to run vapor xcode --mySQL because thought that this is an easier way to achive my goals. Right now I don't understand (i am really tired right now :D ) , what I did and what shall I do to work mySQL in xCode. I will be really thanksful, if you can help me.

**Comment by tannernelson** [comment]
You have to include the `VaporMySQL` provider as a package to your project. The `--mysql` flag just links MySQL headers and libs.

Check this out: https://github.com/vapor/vapor-university/blob/master/api/Package.swift

**Comment by faklyasgyuri** [comment]
I successfully check out the packages, with swift build. Then I create a new xCode Single View Application and add to the app the Packages folder. But after that when I tried to build, I get this error message > 
Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
What did I do in a wrong way????

**Comment by faklyasgyuri** [comment]
Hi @rustymagnet3000 Thanks for your comment. And are you using mySQL in an xCode iPhone application project? Don't you have same errors as I had above? I could successfully run swift build and cloned the packages from git, than I add the packages into my xCode (iPhone app) project but get annoying errors (swiftc failed with exit code 1 or Failed to remove “Info.plist” couldn't be removed)

**Comment by tannernelson** [comment]
Closing this for now.

**Comment by Faizulkarim** [comment]
Install failed, trying sudo  when i try to install vapor tool with command curl -sL toolbox.qutheory.io | bash. what should i do now??

**Comment by vzsg** [comment]
Please open a new issue with more details (e.g. output from the command, version numbers), or join [Vapor on Slack](http://vapor.team/) to ask the same.
