### ISSUE TITLE
Final Middleware

### ISSUE THREAD

**Issue by Joannis** [vapor/vapor#511]
# Feature: FinalMiddleware

* Author(s): [Joannis](https://github.com/joannis)

## Introduction

This feature would allow developers to inject middlewares into the response chain inbetween the middlewares and the response.

## Motivation

When developing a.n API I've been using an authentication middleware that works on a role-based model. Users that have a role with sufficient permissions for an operation on an object can access this part of the API.

In practice we noticed that some new functions that were being developed didn't implement this usage of the middleware correctly. They either didn't apply the middleware to the chain because the `.get`, `.put`, `.post` and `.delete` functions don't accept middlewares or completely forgot.

So we wanted to add a global middleware that prevents requests from being executed unless they're authenticated. We can't put it in front of the chain. Because then we'll check for successful authentication before the authentication middleware checked for the permissions.

## Proposed solution

The solution would be to add a global middleware to the end of the middleware chain. Right before it executes the responder's closure.

## Code snippets

```swift
import MongoKitten
import HTTP
import Vapor

protocol RolesRepresentable {
    var roles: [Role] { get }
}

protocol Role {
    var authorizationLevel: AuthorizationLevel { get }
}

struct MongoRole: Role {
    static var collection: MongoKitten.Collection!
    static func find(forUser userID: ObjectId) throws -> [MongoRole] {
        return Array(try MongoRole.collection.find(matching: "user" == ~userID).flatMap {
            MongoRole(document: $0)
        })
    }
    
    init?(document: Document) {
        self.data = document
    }
    
    let data: Document
    
    var authorizationLevel: AuthorizationLevel {
        return .anonymous
        // TODO: Change to a real role
    }
}

struct MongoUser: Account, RolesRepresentable {
    var accountID: String
    var roles: [Role] {
        do {
            return try MongoRole.find(forUser: try ObjectId(accountID)).flatMap {
                $0
            }
        } catch {
            return []
        }
    }
}

extension APIKitten.User: RolesRepresentable {
    internal var roles: [Role] {
        guard let authDetails = self.authDetails else {
            return []
        }
        
        guard let mongoUser = authDetails.account as? MongoUser else {
            return []
        }
        
        return mongoUser.roles
    }

    var authorizationLevel: [AuthorizationLevel] {
        return [.anonymous]
//        return roles.map {
//            $0.authorizationLevel
//        }
    }
}

extension Request {
    var subject: APIKitten.User? {
        get {
            return storage["TurnstileSubject"] as? APIKitten.User
        }
        set {
            storage["TurnstileSubject"] = newValue
        }
    }
}

enum AuthorizationLevel {
    case anonymous
}

class AuthenticationMiddleware: Middleware {
    let turnstile: Turnstile
    let levels: [AuthorizationLevel]
    
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        let user = APIKitten.User(turnstile: turnstile)
        request.subject = user
        
        print(levels)
        print(user.authorizationLevel)
        
        for level in user.authorizationLevel where levels.contains(level) {
            request.storage["authenticated"] = true
            return try next.respond(to: request)
        }
        
        return try Response(status: .badRequest, json: try JSON(["error": "Insufficient permissions"]))
    }
    
    init(_ authorizationLevels: [AuthorizationLevel], turnstile: Turnstile) {
        self.turnstile = turnstile
        self.levels = authorizationLevels
    }
}

class AuthenticationVerifier: Middleware {
    func respond(to request: Request, chainingTo next: Responder) throws -> Response {
        guard request.storage["authenticated"] as? Bool ?? false else {
            // Request is not authenticated by a `Middleware`
            return try Response(status: .internalServerError, json: try JSON(["error": "Internal server error"]))
        }
        
        return try next.respond(to: request)
    }
}

let a = Droplet()
let turnstile = Turnstile(sessionManager: MemorySessionManager(), realm: MemoryRealm())

a.finalMiddleware.append(AuthenticationVerifier())

a.group() { app in
    app.get("test") { req in
        
        return "this will never execute"
    }
}

a.get("test") { req in  
    return "this will never execute"
}

a.group(AuthenticationMiddleware([.anonymous], turnstile: turnstile)) { app in
    app.get("test2") { req in
        return "works"
    }
}

a.serve()
```
## Impact

The impact would be zero, since it's additive to the ecosystem.

## Alternatives considered

The alternative is to implement these "failsafe" checks inside the closure. Which is counterproductive.

**Comment by tannernelson** [comment]
Can you expand upon this part:

> In practice we noticed that some new functions that were being developed didn't implement this usage of the middleware correctly. They either didn't apply the middleware to the chain because the .get, .put, .post and .delete functions don't accept middlewares or completely forgot.

**Comment by Joannis** [comment]
Internally we're being rushed to develop features currently. And rushing features has a downside for quality. So one of us forgot to apply the authentication checker somewhere which exposed user data briefly in the API. This is of course really bad, so this `finalMiddleware` solution would allow us to build a middleware acting as a failsafe. Whenever the authenticator does it's job it'll set a boolean to true, indicating that the request passed successfully through the authentication middleware. Otherwise the `finalMiddleware` that's shown in this example as the `AuthenticationVerifier` will prevent the request from reaching the handler preventing us from accidentally exposing user data, or  allowing people from abusing this leak in the API to modify data they don't have access to

**Comment by tannernelson** [comment]
I don't see yet the different between finalMiddleware and middleware.

If you add something to `drop.globalMiddleware` it will run with every request as well.

**Comment by Joannis** [comment]
The difference is that `drop.globalMiddleware` is executed before the middleware chain. And `drop.finalMiddleware` would be executed after the middleware chain. Both will be executed on every request. But `finalMiddleware` would be in a different position in the chain allowing for different actions to be taken.

**Comment by Joannis** [comment]
@tannernelson Is it clear or unclear what I mean?

**Comment by tannernelson** [comment]
It is still a bit unclear. Do you mean you want something to run _after_ the middleware added by the `drop.group()`?

The middleware runs in this order:

```
          Client
       v            ^
Droplet middleware
      v             ^
Route middleware
      v             ^
       Closure
      v             ^
         Server
```

So basically the middleware runs from least specific to most specific. 

This means the first middleware on the Droplet will always be the **first request** modifier and the **last response** modifier.

If you want to be the **last request** and **first response** modifier, you need to do so in the closure.

If you imagine the middleware like on onion (shrek lol) having a global middleware be more toward the core of the onion is non-intutive. 

There must be another way to format the middleware to achieve what you are trying to do here.

**Comment by Joannis** [comment]
Hmm.. With the onion reference I can see it being counter-intuitive. But I'm certain there can be something that does the same. I'll check for a new method of approach

**Comment by tannernelson** [comment]
Closing this for now.
