### ISSUE TITLE
Strip JSON comments before parsing

### ISSUE THREAD

**Issue by NathanFlurry** [vapor/vapor#515]
# Feature, Enhancement, or Optimization

# Name of Feature

* Author(s): [Nathan Flurry](https://github.com/NathanFlurry)

## Introduction

It would be nice to be able to put comments in JSON, just like you do in JavaScript or Swift with `//`.

## Motivation

Things like config files commonly need comments to describe certain things, and currently the default JSON parser does not like having comments.

## Proposed solution

I propose stripping all comments in JSON files matching the Swift/JavaScript/etc. pattern of either `// Lorem ipsum` or `/* Lorem ipsum */`.

## Code snippets

An example JSON document in which the comments should be stripped out before parsing:

```json
{ // My comment
  "some": "json",
  "array": [
    /* "hello", */
    "world" /* My other comment */
  ]
}
```

## Impact

This feature will no break or impact existing code, only help make JSON files easier to understand by allowing comments.

## Alternatives considered

We could just stick with the current system in which you have to do something like this:
```json
{
  "__comment": "My ugly comment.",
  "hello": "world"
}
```

**Comment by tannernelson** [comment]
I like this idea a lot. It wouldn't be too hard to implement a step before parsing that removes comments.

But maybe this would be a bad idea because then our JSON is not technically JSON anymore.

**Comment by NathanFlurry** [comment]
I think that as long as we're not making changes to the JSON parser that break existing JSON files, we should be fine. I've seen a few NodeJS libraries that seem to support JSON comments (none that I can remember off the top of my head).
However, as you said, we would be technically breaking RFC compliance, so for those who are picky, we should add a key in the config file for disabling the comment stripping.

**Comment by edjiang** [comment]
https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr

>Suppose you are using JSON to keep configuration files, which you would like to annotate. Go ahead and insert all the comments you like. Then pipe it through JSMin before handing it to your JSON parser.﻿

A minifier would probably be useful in the context of Vapor anyways =]

**Comment by tannernelson** [comment]
@vdka does your JSON parser allow for stripping comments?

**Comment by vdka** [comment]
@tannernelson it can I guess but for simple one time loading config files it might be better to just do a single pass over stripping comments prior. It'd be best not to add complexity into the parser when it's not needed.

**Comment by tannernelson** [comment]
We just need the parser to not break if comments are present. I haven't checked if it does this by default yet.

**Comment by vdka** [comment]
It'll throw with `Error.Reason.syntaxError` or something of the sort at the moment, because I went for full RFC compliance, but I mean, I have extended it with the option to strip `null`s so I don't see why I couldn't do comments as an Option.

**Comment by tannernelson** [comment]
That would be awesome 👏. `skipComments` option or something. 

It would be really nice for the default Vapor configuration files to look like:

```
/*
    This is the application's configuration file.
*/
{
    "key": "1234" // the default crypto key
}
```

**Comment by vdka** [comment]
Just to make sure you do just load config's once and hold them in memory of something like that right?

**Comment by tannernelson** [comment]
Yup, the config files are loaded into memory when the app boots.

**Comment by vdka** [comment]
Initial support done vdka/json#13, I ended up just adding to the parser directly. Should work, but I haven't written any tests for it.
