### ISSUE TITLE
use of undeclared type 'Never'

### ISSUE THREAD

**Issue by faklyasgyuri** [vapor/vapor#520]
After running swift package generate-xcodeproj command I tried to build my xCode project, but build failed because I get the following error> use of undeclared type 'Never'  in SynchronusTCPServer class and its startWithHandler function returns with Never object. Where should be declared this class, maybe it's one of the novelty of swift or it is removed from newest version??? I don't know how to solve this problem. Thanks for help.

**Comment by LoganWright** [comment]
@faklyasgyuri `-> Never` replaced `@noreturn` in snapshots after 07-25, I believe your project is compiling on an older one. Make sure to set the correct toolchain, and everything should compile 👍

**Comment by rustymagnet3000** [comment]
@LoganWright  @faklyasgyuri  I had the same issue.  Sure enough it was my own fault.  The Toolchain had reverted to the default xCode 8.0 version instead of the  snapshots 07-25.

**Comment by LoganWright** [comment]
@rustymagnet3000 @faklyasgyuri closing this for now, sounds like you got it working! We can reopen if people are still having issues.

**Comment by faklyasgyuri** [comment]
Yes. Thank you for your helping. :)
