### ISSUE TITLE
Integrate with XCode 8 beta 5

### ISSUE THREAD

**Issue by ankitthakur** [vapor/vapor#526]
Please integrate https://github.com/apple/swift/releases/tag/swift-3.0-PREVIEW-5

**Comment by alomvar** [comment]
Meanwhile [Xcode 8 Beta 6](https://developer.apple.com/download/) (with [Swift 3.0 Preview 6](https://swift.org/download/#previews)) was released.

**Comment by tannernelson** [comment]
We are supporting beta 6 with 0.17 which should be out soon.
