### ISSUE TITLE
Make code coverage only run tests once?

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#528]
I'm stealing the CI scripts you have for now, but I noticed when I run:

```yml
- eval "$(curl -sL swift.qutheory.io/ci)"
- eval "$(curl -sL swift.qutheory.io/codecov)"
```

CI is running the tests once, and codecov is running them again. Could we integrate those two steps on mac? Since some of my tests are for BCrypt (which by definition try to consume lots of cpu time), running tests twice mean that Turnstile's tests take ~15 mins to run on mac.

**Comment by tannernelson** [comment]
The first test uses the Swift package manager `swift test` and the second ones uses Xcode with some strange `xcbuild` test or something. Codecov needs the Xcode way (which is a lot slower) to produce the reports it uses.

I haven't looked into any way of merging these but I assume it will get better once Xcode 8 is released or Codecov gets support for the package manager.

**Comment by edjiang** [comment]
Right -- I guess if the `xcbuild` test fails, it should fail the whole test anyways? So no need to run `swift test` beforehand.

**Comment by tannernelson** [comment]
Closing this for now.
