### ISSUE TITLE
Default parameter values

### ISSUE THREAD

**Issue by NielsKoole** [vapor/vapor#531]
# Enhancement

Default parameter values

* Author(s): [Niels Koole](https://github.com/nielskoole)

## Introduction

It would be great when you can provide default values for parameters in a route. I've seen it in other web frameworks and I think it would be great addition to the Vapor framework as well.

## Motivation

When building a multilangual website, the user is often able to change the language. To me it seems consistent that when the user enter your website the first time, a default language will be set. But that it also will be visible in the URL, this would be a great addition on SEO level of your website. [Specify language in URL](https://support.google.com/webmasters/answer/182192?hl=en#1).

In practice:
- User enters your website: http://www.example.com/
- Vapor framework doesn't recon a language, so forward to: http://www.example.com/en

## Proposed solution

Could be done with a tuple to provide a default value:
```swift
drop.get("/", (String.self, "en")) { request, lang in
    return try drop.view("welcome.mustache", context: [
        "title": drop.localization[lang, "welcome", "title"],
        "body": drop.localization[lang, "welcome", "body"]
    ])
}
```

## Impact

I would say that the impact is rather small, except for the routing part. But that's not something I can estimate. In defining the route you should be able to recognise a tuple or a single value, and act upon that.

## Alternatives considered

Not on this moment.

**Comment by tannernelson** [comment]
This is an interesting idea. You could achieve the same result by moving the closure to a controller:

```swift
class WelcomeController {
    func welcome(request: Request, language: String = "en") {
        ...
    }
}
```

```swift
let wc = WelcomeController()
drop.get(wc.welcome)
drop.get(String.self, wc.welcome)
```

**Comment by LoganWright** [comment]
I'm not crazy about the tuple syntax on this one, I think the easiest way to implement this is to just do:

```swift
drop.get { _ in return Response(redirect: "/en") }
```

Would that accomplish what's suggested here?

**Comment by LoganWright** [comment]
Closing this since there are currently workarounds and adding the tuple option would almost triple our generated code and kill compile times.

If we have some alternatives and we want to reopen this, let's do that 👍
