### ISSUE TITLE
Allow disabling View.cache in development

### ISSUE THREAD

**Issue by czechboy0** [vapor/vapor#534]
When debugging/tweaking a renderable resource (e.g. a Mustache template), it is a pain to have to restart the server every time you change the file on disk. It's be great to only have to 1. change the file on disk, 2. reload in browser. 

Currently file caching in [here](https://github.com/vapor/vapor/blob/master/Sources/Vapor/View/View.swift#L28) prevents that behavior, so I suggest an option to disable caching is added, for exactly this usecase.

**Comment by LoganWright** [comment]
This is now the view render's responsibility. Just create a stem w/ `nil` cache and nothing will get stored 👍

**Comment by czechboy0** [comment]
@LoganWright Thanks!
