### ISSUE TITLE
Caching and Conditional Requests

### ISSUE THREAD

**Issue by ogres** [vapor/vapor#539]
Currently, Vapor has no caching support/mechanism for HTTP Requests.

Even for static files ( images, logos, css, js ... ) Vapor is not retuning proper headers for browser to cache the data,

Current Response:

```
Connection:keep-alive
Content-Length:211183
Content-Type:application/javascript
Date:Tue, 23 Aug 2016 13:40:44 GMT
Server:Vapor 0.16.0
```

Missing headers:

```
Cache-Control: max-age=21600
Last-Modified: Wed, 01 Sep 2016 16:34:52 GMT
ETag: "3115cba6"
```

After implementing the missing headers/caching, browser will be able to send :

```
If-Modified-Since: Wed, 01 Sep 2016 16:34:52 GMT
If-None-Match: "3115cba6"
```

For static files Vapor should be able to process the request and provide proper result ( 304 when not modified ) itself.

Also, would be nice, to have helper functionality for custom request handlers, to do the same.

**Comment by czechboy0** [comment]
+1, I think this will be a great addition. I think we might be able to get this in sooner if we focus *only* on supporting conditional requests for static resources. I'm not sure there's anything Vapor can do for caching dynamic resources, it's the app's responsibility to figure out when to send 304 and when to resend the data.

I'd go as far to say that such middleware should be enabled by default, so that new apps automatically minimize the CPU load and bandwidth for static resources.

**Comment by tannernelson** [comment]
I think @czechboy0 is right in saying we should support static (file) resources first. Caching dynamic resources is much more nuanced and would probably be achieved by caching slow database responses.

This should be fairly easy to implement for files in the `FileMiddleware`.  May even be possible to implement this as a separate ETag middleware which could be nice in case such support needs to be removed for some reason.

**Comment by ogres** [comment]
This issue is not for Dynamic Responses, as I wrote Vapor should be able to handle static files caching, 

but also **would be nice** to have helper functionality for custom responses, in this I mean to provide easy access from request handler to ETag and if-modified-since flags without parsing headers each time manually.

So yeah, caching static files should be fine for now, even if we won't provide any additional functionality for request handlers right now.

**Comment by tannernelson** [comment]
Okay, that makes sense. I imagine the ETag or FileMiddleware will add extensions onto Request for accessing those headers more easily. And those would then be available for `import Vapor`.

**Comment by LoganWright** [comment]
ETag middleware is in.
