### ISSUE TITLE
Source code interactive, mouse over hotspots

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#543]
The code with tooltip on Vapor home page is a good example for new developers who may be completely new to Swift and understood in seconds. Except for documentations which could be applied the same method?

Can be implement the same tooltip method on the source code examples in Documentation page?
https://vapor.github.io/documentation/

Due to a few of us may not know what is "RenderDriver" and where is the source located

```
public protocol Driver {
    var idKey: String { get }
    func query<T: Entity>(_ query: Query<T>) throws -> Node
    func schema(_ schema: Schema) throws
    func raw(_ raw: String, _ values: [Node]) throws -> Node
}
```
I rather see a tooltip explain on "Entity", "Schema", throws, etc are easier than navigate to many different place for answers.

**Comment by LoganWright** [comment]
@wildfiremedia this seems like a cool addition. I believe some of the graphic on the home page was customized, so we'll look into the difficulty associated with putting this in documentation as well. My initial reaction is to say, don't get your hopes to high, but we'll see what we can do!

**Comment by tannernelson** [comment]
Closing this for now. Feel free to re-open on vapor/website.
