### ISSUE TITLE
Add tests ensuring there are no file/socket leaks

### ISSUE THREAD

**Issue by czechboy0** [vapor/vapor#550]
I've been having to restart one of my Vapor servers every few days, as it errors for new connections with "too many files open on the system", so my guess is there's a file descriptor leak. I'm doing some file access there, so I'm not positive it's a Vapor socket leak, or something I'm doing in a responder.

Nevertheless, I'd like to propose we add a functional test, which 
1. starts a Vapor server
2. snapshots the number of open files
3. makes a few calls to the endpoints
4. snapshots the number of open files

Ideally, the numbers in 2 and 4 should equal (if we ignore keepAlive here for a second). I found a way to do this [here](http://stackoverflow.com/a/25123694/909246).

Overall, I think some tests to ensure resources are being cleaned up in the right way would be great here. Especially since such issues only manifest themselves after days/weeks of running on a server, when it becomes much more difficult to debug and reproduce.

**Comment by tannernelson** [comment]
This might have to do with our recent fix to engine. vapor/engine#44

**Comment by czechboy0** [comment]
Yes, that's possible. I just want to have an assurance for the long run
that we'd catch it if we introduced something in the future.

**Comment by LoganWright** [comment]
@czechboy0 @tannernelson any ideas for how to do this one?

**Comment by tannernelson** [comment]
I'm almost positive this is fixed now, but not sure how to test it.

**Comment by czechboy0** [comment]
It's probably not robust, but I've noticed the os always gives increasing numbers to the allocated sockets. You could allocate 5 sockets (respond to 5 requests), then finish them all and allocate a new socket and ensure the descriptor is the "starting number" one (something low like 5). Would need testing to ensure it always happens but that might work. 

Also AFAIK there is a way to query some things like all open sockets from the process, don't remember how though. That could also help.

**Comment by czechboy0** [comment]
Even if it's fine now, I think it's an important regression test to ensure it doesn't get broken in the future.

**Comment by tannernelson** [comment]
Figured out a way to test this.

1. Get PID of process
2. Run `sudo lsof -p $PID | egrep 'TCP|UDP'` to show all running processes
3. Run `... | wc -l` to count

Application idle:

```
Gertrude:vapor tanner$ sudo lsof -p 33329 | egrep 'TCP|UDP' | wc -l
       1
```

Running `wrk -d 10 -t 4 -c 128 http://localhost:8080/plaintext`

```
Gertrude:vapor tanner$ sudo lsof -p 33329 | egrep 'TCP|UDP' | wc -l
     129
```

After run has completed

```
Gertrude:vapor tanner$ sudo lsof -p 33329 | egrep 'TCP|UDP' | wc -l
       1
```

@czechboy0 Let me know if you think this test has any holes in it. I think we can run this test time to time and make sure we aren't leaking sockets. Closing this for now.

**Comment by czechboy0** [comment]
Would be awesome if we could automate it on GitHub but great, thanks!
