### ISSUE TITLE
Resource path in Development module needs to be fixed.

### ISSUE THREAD

**Issue by damuellen** [vapor/vapor#551]
🚀 Thanks for contributing!

Below are templates for various types of issues (Bugs, Security, and Features) separated by horizontal rules. 
Please delete whichever sections of the template you do not need.

# Bugs

The resource path in the Development module is wrong.

`/DevelopmentResources/` needs to be `/Development/Resources/`

localhost:8000/
give this response:
> Server Error: fileLoad("./Sources/DevelopmentResources/Views/welcome.leaf")

**Comment by LoganWright** [comment]
Fixed in #552
