### ISSUE TITLE
servers.json for improved tls config

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#557]
The `servers.json` file needs to support the improved TLS configuration options.

**Comment by LoganWright** [comment]
Putting a proposal in here, we could have security be the name of a file.

ie:

```
"securityLayer": "my-cert.pem"
```

And then in the same directory, include `my-cert.pem` as the raw certificate since config can load raw files now as bytes.

**Comment by tannernelson** [comment]
I think it needs to be more complex than that. Since you can provide multiple certs possibly as well as various configuration options like ciphers, etc.

I was thinking something like:

```json
{
	"host": "vapor.codes",
	"port": 443,
	"securityLayer": "tls",
	"tls": {
		"ca": "blah.pem",
		"cert": "blah.cert",
		"cipher": "compat",
		"verifyCert": true,
		"verifyHost": true
	}
}
```

**Comment by LoganWright** [comment]
@tannernelson that works for me, the core of what I was suggesting was using names to point to certs in the config folder which seems to be done here 👍 

I like the `tls` key as it is in your suggestion.
