### ISSUE TITLE
Asynchronous response reporting ambiguous use of close - 0.17

### ISSUE THREAD

**Issue by Denvious** [vapor/vapor#560]
## Bug
Attempting to close an async request with a string response in the parameter causes the xcode compiler to flag the line as ``` Ambiguous use of close(with:) ```

## Code snippets
```
drop.get("foobar") { req in    
    return try Response.async { portal in
        portal.close(with: "This is a string")   <-- Ambiguous use of 'close(with:)'
    }
}
```

## Working Alternative
Explicitly typecasting the string or error to the appropriate type removes the compiler error.
```
let resp = String("This is a string") as! ResponseRepresentable
portal.close(with: resp)

- or / safer version - 

drop.get("foobar") { req in
    return try Response.async { portal in
        if let resp = String("Aaa") as? ResponseRepresentable {
            portal.close(with: resp)
        }
    }
}
```

## Question
Is there a possibility that typecasting from String to ResponseRepresentable can fail? 

## Environment
OSX El Capitan 10.11.6
XCode 8.0 beta 6 (8S201h) 
Swift Development Snapshot 2016-08-18(a)

**Comment by tannernelson** [comment]
@LoganWright Any ideas about what could be ambiguous here? The closure needs a `ResponseRepresentable` so the compiler should be able to figure that out.

**Comment by Denvious** [comment]
Sneaking suspicion that its because in 3.0 beta 6(?) they've removed the automated cast from Types to "AnyObject", and how you need to "bridge cast" it.

**Comment by LoganWright** [comment]
Will be fixed in next version, underlying leaf issue.
