### ISSUE TITLE
error: invalid inferred toolchain

### ISSUE THREAD

**Issue by kingcos** [vapor/vapor#562]
I am installing the toolbox on my Ubuntu server. 
But it always has this error. I can't find what's wrong with it.

How can I fix it? Thank you.

<img width="703" alt="screen shot 2016-09-01 at 5 17 41 pm" src="https://cloud.githubusercontent.com/assets/10249989/18162251/11eca88e-7068-11e6-9928-ca9dbb804b76.png">

**Comment by LoganWright** [comment]
@kingcos I haven't seen this one yet, have you made any progress or do you still need assistance?

**Comment by tannernelson** [comment]
I think this might have to do with the toolbox not being updated yet (also #564)

**Comment by LoganWright** [comment]
Let's start grouping these together, moving this one to #570
