### ISSUE TITLE
Swift version issue

### ISSUE THREAD

**Issue by Shunzi007** [vapor/vapor#564]
After delete DEVELOPMENT-SNAPSHOT-2016-07-25-a
> vapor new ss
> dyld: Library not loaded: @rpath/libswiftCore.dylib
>   Referenced from: /usr/local/bin/vapor
>   Reason: image not found
> Trace/BPT trap: 5

and run 
`curl -sL toolbox.qutheory.io | bash`

> ✅  Compatible
> Downloading...
> Compiling...
> swiftenv: version `DEVELOPMENT-SNAPSHOT-2016-07-25-a' (set by /Users/wangshun/.vapor-toolbox-0.8.0/vapor-toolbox/.swift-version) is not installed
> Installing...
> bash: line 24: .build/release/Executable: No such file or directory
> Use vapor --help and vapor <command> --help to learn more.

I think the toolbox may be compliled by DEVELOPMENT-SNAPSHOT-2016-07-25-a, however 0.17 is using DEVELOPMENT-SNAPSHOT-2016-08-18-a

**Comment by nickskull** [comment]
The toolbox hasn't yet been updated to support Vapor 0.17. I'm working on it in [this branch](https://github.com/vapor/toolbox/tree/vapor-0.17-support).

**Comment by Shunzi007** [comment]
ok, I see,  great work. How can  I use  this branch?

**Comment by nickskull** [comment]
Clone the repository, switch to the branch and run `swift build -c release`, after it finishes you can run `./.build/release/Executable self install` to install it. After that you can use it as usual, just by calling `vapor` in terminal. 

There are still some issues though and I'd love some feedback on things that work/don't work.

**Comment by tannernelson** [comment]
We've been busy with the try! Swift conference this week. The toolbox should be updated soon. :)

**Comment by Shunzi007** [comment]
@nickskull I'm sorry to reply you so late. Under your guidance, I successfully installed toolbox v0.9.0, and it runs without any issue, Thanks.
Be waiting for your further work.

**Comment by Shunzi007** [comment]
@tannernelson 
Hi, Nelson. I am an iOS developer from China. When I was looking for a background language, I met Vapor. I have be watching and playing with Vapor for months. Could you describe the future of Vapor for me? It will be a popular framework, which could handle a large number of concurrent just like Java or C frameworks, or just a tool to help build background of demo apps? 
Most likely the users will be swifters, maybe 90% of which is mobile developer now. We all think it is cool to code with the same language on server and mobile side. But we need you to help us to build the confidence of Vapor about it's performance.Maybe you can write an perform report, I think? 
Thanks!

**Comment by Shunzi007** [comment]
@nickskull 
the command `vapor xocde` don't work, I don't know whether it is a bug of v0.9.0
