### ISSUE TITLE
$ENVIRONMENT syntax in a config object doesn't work

### ISSUE THREAD

**Issue by edjiang** [vapor/vapor#566]
```Swift
let config = Config([
    "servers": [
        "http": [
            "port": "$PORT"
        ]
    ]
])

let app = Droplet(config: config)
```

Steps to reproduce:
I set PORT to 5000 in Xcode's environment variables settings
Run the app

Expected result:
`Server 'http' starting at 0.0.0.0:5000`

Actual result:
`Server 'http' starting at 0.0.0.0:8080`

Not sure if this happens on the command line

**Comment by LoganWright** [comment]
Waiting on tests for #567
