### ISSUE TITLE
Tool box issue in Ubuntu 16.04

### ISSUE THREAD

**Issue by Shunzi007** [vapor/vapor#568]
In environment Ubuntu 16.04, after type `curl -sL toolbox.vapor.sh | bash`, it could get toolbox installed.
However, `vapor --help` tells 

> vapor: command not found

**Comment by tannernelson** [comment]
It should have installed to `/usr/local/bin/vapor`. Can you check if it's there? You might need to open a new terminal window or move it to `/usr/bin/vapor`.

**Comment by m-revetria** [comment]
I just had the same issue with Ubuntu 16.04. Vapor binary wasn't copied either to `/usr/local/bin` or `/usr/bin`.

I could fix it this way:
1. Download the installation scrip http://toolbox.vapor.sh
2. Delete this line `rm -rf $DIR;` in the script so it don't delete vapor toolbox after installation
3. Run the modified script
4. Copy the vapor binary to `/usr/bin`:
```shell
cd .vapor-toolbox-0.10.0
cp .build/release/Executable /usr/bin/vapor
```

That worked for me but would be great if the installation script do all the stuff in Ubuntu 16.04

**Comment by Shunzi007** [comment]
@tannernelson There are no file named `vapor ` in the `/usr/local/bin/vapor`

**Comment by Shunzi007** [comment]
@m-revetria I tried as you told, but it didn't work when use  `vapor run` after `vapor build`
I use the following commands:
```
git clone https://github.com/vapor/toolbox.git
cd toolbox/
swift build -c release
./.build/release/Executable self install
```
It seems well to run 😄

**Comment by tannernelson** [comment]
This should work now with 0.10.1. Can you try it?

**Comment by Shunzi007** [comment]
@tannernelson 
Yeah, I have fished testing, both in macOS & Ubuntu, it works well.
