### ISSUE TITLE
Vapor Toolbox Issues

### ISSUE THREAD

**Issue by LazyBoy72** [vapor/vapor#570]
Just for a premise, I installed and worked on Vapor Toolbox with Linux Ubuntu 14.04.5 without any problem.
Now I'm trying to setup the environment on Mac OS to take advantage from Xcode.
I installed the required Swift development snapshot and run:

curl -sL toolbox.vapor.sh | bash

It seems to run successfully, but vapor executable is not installed.
I downloaded the toolbox.vapor.sh script and removed the lines to delete the folder.
I made "cp .build/release/Executable /usr/local/bin/vapor" myself in the right folder and vapor toolbox started to work, but with some strange behavior. It always gives success even when the procedure didn't complete.
Normal commands (like "new" and "build") work properly, but as said before if there is an error it is not signaled.
Furthermore "vapor xcode" does nothing (do not generate the Xcode project), but signals success.
I tried to generate the Xcode project from "swift package generate-xcodeproj" but the resulting project is not correct (App subfolders like Controllers are not created and the file contained in them have the name of the folder prefixed).

Mac OSX El Capitan.

DEVELOPMENT-SNAPSHOT-2016-08-18-a
Vapor Toolbox v0.10.0
Vapor Framework v0.17.0

**Comment by LazyBoy72** [comment]
**Update**:
Using Vapor Framework v0.16 for the project, the command "vapor xcode" worked, but the project cannot be compiled on Xcode because the Jay package cannot be found.
After changing the framework version I've launched a "vapor build --clean", to be sure that the dependencies will be fetched again.

**Comment by tannernelson** [comment]
@LazyBoy72 did the toolbox install to `/usr/local/bin/vapor`? Maybe that is not in your PATH

**Comment by LazyBoy72** [comment]
@tannernelson no, the toolbox Executable were not copied on /usr/local/bin/vapor, but the installation script print success messages. I had to copy it manually after stopping the deletion of the source folder.

**Comment by wallstead** [comment]
Using DEVELOPMENT-SNAPSHOT-2016-08-18-a I keep getting the following:
<img width="682" alt="screen shot 2016-09-06 at 12 05 32 pm" src="https://cloud.githubusercontent.com/assets/9662992/18287018/431b316c-742a-11e6-8886-558118a9b744.png">
I followed [these instructions](https://vapor.github.io/documentation/getting-started/install-swift-3.html) exactly, with the only difference being the version of the snapshot I installed.

**Comment by LoganWright** [comment]
@wallstead we updated the script today, would you mind giving it another try and reporting back 👍

**Comment by wallstead** [comment]
https://github.com/vapor/toolbox/commit/6aae427234c9d7354503c59d9be3fff510510214 solved the issue for me. Many thanks! 🙇

**Comment by LazyBoy72** [comment]
It worked for me but it gave the message "Install failed, trying sudo" at the end even if the vapor executable was successfully copied (without using sudo)

**Comment by tannernelson** [comment]
That message is normal. It means it worked after trying sudo.

**Comment by jnozzi** [comment]
I'm also getting the "error: invalid inferred toolchain" today. Swift is installed just fine but vapor does not get installed to its expected location.

**Comment by tannernelson** [comment]
@jnozzi do you have Xcode 8 and Swift 3 installed? Did you have Swiftenv installed previously?

**Comment by jnozzi** [comment]
@tannernelson Sorry,  I should have mentioned I am installing it on Ubuntu 16. It turns out (late last night) my remote Bash profile wasn't updated. This seems to uave resolved everything.
