### ISSUE TITLE
Memory usage in Performance vs App

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#571]
On Mac OS X, I have notice while running wrk and monitoring processes using ```top```, Performance memory keep increasing from 30MB+ while App memory stay at 3000KB+ = 3MB+. How did the Performance use that much memory?

./.build/debug/Performance --env=Production
./.build/debug/App --env=Production

**Comment by LoganWright** [comment]
@wildfiremedia would you mind running this again on 0.18 and letting us know the results? Some screenshots of profiling would be great as well 👍

**Comment by wildfiremedia** [comment]
Using vapor new project, I don't see Performance anymore but App on "hello, world" without middleware bring back the score, with middleware, it seem to fare ~50% slower?

I suggest we should have an option to indicate which functions or routes do not need enquiry on middleware so it won't have to make one full cycle to return the results.

**Comment by LoganWright** [comment]
@wildfiremedia we broke out our routing module, so those feeling so inclined can manually implement as to your suggestion!

Thanks for participating as always 👍
