### ISSUE TITLE
No docker image available for tag DEVELOPMENT-SNAPSHOT-2016-08-18-a

### ISSUE THREAD

**Issue by m-revetria** [vapor/vapor#572]
I'm having  troubles when running vapor docker in Ubuntu 16.04.

I just updated to Vapor 0.17.1 and swift to DEVELOPMENT-SNAPSHOT-2016-08-18-a.

When I run the docker command `docker run --rm -it -v $(pwd):/vapor -p 8080:8080 qutheory/swift:DEVELOPMENT-SNAPSHOT-2016-08-18-a` I get next error:

```
Unable to find image 'qutheory/swift:DEVELOPMENT-SNAPSHOT-2016-08-18-a' locally
Pulling repository docker.io/qutheory/swift
docker: Tag DEVELOPMENT-SNAPSHOT-2016-08-18-a not found in repository docker.io/qutheory/swift.
See 'docker run --help'.
```

**Comment by m-revetria** [comment]
Something else, the command suggested by `vapor run docker` doesn't work in Ubuntu, it prints:

```
docker run --rm -it -v $(PWD):/vapor -p 8080:8080 qutheory/swift:DEVELOPMENT-SNAPSHOT-2016-08-18-a
```

But if I run that command I get the error `PWD: command not found`, changing `PWD` with `pwd` make it works but with the error commented in the description of this issue

**Comment by LoganWright** [comment]
@m-revetria we recently moved to gold master, we're in the process of setting all of that up. This is going to need some updates at that time, so we'll need people w/ good docker expertise. If you'd be willing to join us in slack at http://vapor.team  and join the `development` channel, it'd be a big help to get all of this configured properly.
