### ISSUE TITLE
Xml parser

### ISSUE THREAD

**Issue by Casperhr** [vapor/vapor#575]
Like the .json on Response

Have a .xml

Fx use a library 
https://github.com/drmohundro/SWXMLHash

I tested their swift 3 branch and works just fine

Maybe there is another?

**Comment by LoganWright** [comment]
Any eta on when it's intended to be merged? I have used and like SWXMLHash when they get it in there.

**Comment by tannernelson** [comment]
We could easily make an XML provider or something like that.

**Comment by nickskull** [comment]
@LoganWright Seems like it's merged now :)
