### ISSUE TITLE
App crashes when sending multipart/form-data POSTs

### ISSUE THREAD

**Issue by rugaard** [vapor/vapor#577]
When submitting a form with `enctype="multipart/form-data"` and trying to retrieve the posted value in the way the documentation states - `request.data["name"] as? String` the app crashes.

The crash appears to happen on the following line inside the `Utilities/Byte/Data.swift` file on `line 45`:
```swift
parts.append(self[range.to..<nextRange.from].array)
```

**Comment by robertBojor** [comment]
I've had no problems pulling data into the app from multipart/form-data posts - the only difference is that I use
```swift
guard let lookingFor = request.data["lookingFor"]?.string else {
    throw someError
}
```
... and if the parameter is present no errors are thrown and no crashes.

**Comment by syky27** [comment]
I am using this:

```
guard let image = request.multipart?["image"]?.file else {
    throw Abort.badRequest
}
```

**Comment by LoganWright** [comment]
@syky27 thanks! Sounds like it's resolved 😄
