### ISSUE TITLE
"vapor fetch" is not downloading any packages

### ISSUE THREAD

**Issue by dhamukrish** [vapor/vapor#582]
`vapor fetch` is not downloading any packages as I can see no packages folders are created. But message in console says
```
No Packages folder, fetch may take a while...
Fetching Dependencies [Done]
```

Even I have tried with `swift build` as well

```
<unknown>:0: error: Swift does not support the SDK 'MacOSX10.11.sdk'
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: invalid manifest format
```
Please advise.

**Comment by tannernelson** [comment]
@dhamukrish are you using the Xcode 8 GM? If so, make sure `Xcode 8` is selected in `Xcode > Preferences > Locations > Command Line Tools`

**Comment by dhamukrish** [comment]
Thanks Tanner and you are right. This issue can be closed.
