### ISSUE TITLE
views dir

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#585]
Allow the views dir (relative or not to the work dir) to be passed as an init arg to the Droplet. 

Example:

```swift
let drop = Droplet(viewsDir: "VaporBackend/Resources/Views")
```

**Comment by LoganWright** [comment]
@tannernelson I'm wondering if this should be the responsibility of the renderer:

```
let viewRenderer = LeafRenderer(viewsDirectory: "./VaporBackend/Resources/Views")
let drop = Droplet(view: viewRenderer)
```

**Comment by tannernelson** [comment]
I think the droplet should pass the renderer the fully qualified views directory because only the droplet knows what the working directory is.

**Comment by LoganWright** [comment]
Ohhh, when you say views directory, you mean the suffix that will be attached to work dir. That makes sense on droplet then, I get it.

**Comment by tannernelson** [comment]
Yup. Though, if it starts with a leading `/` we should probably treat as an absolute path.

**Comment by LoganWright** [comment]
This has moved to view renderer and is flexible/customizable 👍
