### ISSUE TITLE
empty example

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#586]
Make an empty example project that will be the default for `vapor new X`

**Comment by rvlieshout** [comment]
Empty and Example do contradict. You could ask what 'template' a new project would like to use:
* Web API (JSON, no template engines)
* With template engine
* With DB support

**Comment by LoganWright** [comment]
@rvlieshout We do currently support some templating! It's still early stages, but here's some examples:

```
vapor new Foo --template=light
vapor new Foo --template=basic
vapor new Foo --template=example
vapor new Foo --template=todo-example
```

For non vapor libraries, you can do: `--template=organization/repository` and for non github, you can do `--template=http://custom.com/repo`

**Comment by LoganWright** [comment]
We have a more diverse set of templates that will continue to expand as community requests.
