### ISSUE TITLE
Storage feature

### ISSUE THREAD

**Issue by Casperhr** [vapor/vapor#590]
- Foundation file driver
- S3

**Comment by zyxep** [comment]
what about almost everything from http://flysystem.thephpleague.com/ ?

**Comment by Casperhr** [comment]
Something like that. Was more referring to the Storage facade

**Comment by JustinM1** [comment]
Hey, I wrote a Provider for vapor to help with V4 auth headers and pre-signed URLs. https://github.com/JustinM1/VaporS3Signer

**Comment by LoganWright** [comment]
@BrettRToomey can you also post your Vapor S3 library here!
