### ISSUE TITLE
Abort exceptions are always returned as JSON

### ISSUE THREAD

**Issue by rugaard** [vapor/vapor#595]
When throwing an exception - i.e. `Abort.custom(.preconditionFailed, "Required data is missing")` - in a controller it always generates the response as JSON.

This is very inconvenient when working in a controller action that returns HTML views (Leaf).  
## Proposed solution

When generating the response from the exception, look at the request's `Content-Type`. If it's `application/json` then return the response as JSON, otherwise return it as HTML.

**Comment by tannernelson** [comment]
@rugaard We'll definitely do this with the updated error pages from Nodes.

But you can always remove the Abort middleware and catch the error yourself to provide whatever response you like.
