### ISSUE TITLE
improved of resources routing

### ISSUE THREAD

**Issue by VikinDev** [vapor/vapor#612]
# problem

Now I can not see directly the specific routing the corresponding controller method；<br/>
so use

``` swift
app.resource("yourResource", Controller())
```

 is not very convenient
# opinion

Add a similar laravel's artisan command;

---

resource route

``` php
Route::resource('/demo','DemoController');
```

command

``` php
php artisan route:list
```

output
![image](https://cloud.githubusercontent.com/assets/14308107/18612381/e906151a-7d8a-11e6-8145-047fe50052b9.png)

---

So that people can clearly see each routing, it is very friendly；

**Comment by tannernelson** [comment]
The way to achieve that is through resources which we need some docs for!

**Comment by LoganWright** [comment]
We now support listing routes through `vapor run routes`
