### ISSUE TITLE
GD2/ImageMagick support for HTTP based manipulations 

### ISSUE THREAD

**Issue by zyxep** [vapor/vapor#613]
Hi Guys,

It would be nice to see a driver/provider for GD2/ImageMagick.
So something like PHP League Glide can be ported to Swift.
http://glide.thephpleague.com/

**Comment by LoganWright** [comment]
We'd definitely love this, right now imagemagick appears to be a python lib, so someone will need to wrap a c component, or do a rewrite in Swift.

For now, this is not a part of the vapor roadmap internally unless we get more resources.
