### ISSUE TITLE
log "something went wrong" in production

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#614]

**Comment by skreutzberger** [comment]
That can be achieved with [SwiftyBeaver-Vapor](https://github.com/SwiftyBeaver/SwiftyBeaver-Vapor) including sending to file or cloud when hooked into a 500 middleware for example. Do you have specs?

**Comment by tannernelson** [comment]
Right here before we return the view we should be doing a log of what the error was: https://github.com/vapor/vapor/blob/master/Sources/Vapor/Droplet/Droplet%2BResponder.swift#L40

**Comment by skreutzberger** [comment]
I created the `ErrorPageMiddleware` based on the `AbortMiddleWare` with the following additional functionality:

1. all 404 errors are logged at info level
2. all other errors are logged at error level (fulfills the issue’s requirement)
3. rendering of a default template on error (the template name can be set in `init`)
4. optional rendering of a specific template per error (template:status pairs can be set in `init`)

Here is the source code:
- [ErrorPageMiddleware.swift](https://github.com/SwiftyBeaver/SBWebsite/blob/master/Sources/SBWebsite/Middleware/ErrorPageMiddleware.swift)
- Example use [main.swift](https://github.com/SwiftyBeaver/SBWebsite/blob/master/Sources/SBWebsite/main.swift)

What do you think?

**Comment by tannernelson** [comment]
Those are awesome!

**Comment by skreutzberger** [comment]
What do you want to do with ErrorPageMiddleware? Merge in Vapor core, replace AbortMiddleWare? Or just leave it outside as reference?

**Comment by tannernelson** [comment]
AbortMiddleware was always meant to be replaceable so I think your middleware package stands well on its own as a nice optional package.

**Comment by LoganWright** [comment]
@tannernelson this seems resolved here:

https://github.com/vapor/vapor/blob/master/Sources/Vapor/Droplet/Droplet%2BResponder.swift#L61

Can this be closed?

**Comment by tannernelson** [comment]
Yup.
