### ISSUE TITLE
[Discussion] Rename main.swift to Follow File Naming Convention

### ISSUE THREAD

**Issue by JustinJiaDev** [vapor/vapor#617]
# Rename main.swift to Follow File Naming Convention

* Author: [Justin](https://github.com/JustinJiaDev)

## Introduction

The project generated by default through vapor toolbox contains a `main.swift` file, which acts as the entry point of the application. However, all other files are capitalized. We should rename `main.swift` to follow this convention.

## Motivation

We want a consistent naming convention. The only outlier is `main.swift`.

## Proposed solution

Rename `main.swift` to `Main.swift`.

## Impact

Docs need to be updated.

## Alternatives considered

We can use names other than `main.swift`, such as `Vapor.swift`, `Application.swift`, `App.swift`, `Entry.swift`.

**Comment by tannernelson** [comment]
`main.swift` must be named as such to work with the Swift Package Manager. This feature request would need to be filed to http://bugs.swift.org.
