### ISSUE TITLE
Auth support multiple User types

### ISSUE THREAD

**Issue by Casperhr** [vapor/vapor#621]
In my company we always have 2 user tables

users -> which is the frontend users for the apps
backend_users -> this is the admin users for the backend / cms

users auth through the api
backend_users auth through session, but also have the option to auth through api, since we sometimes creates ipad apps for admin features etc

Right now I can see a easy way to have 2 user types authing in same app.

**Comment by tannernelson** [comment]
I may be able to find a way to do this that doesn't break public API.

**Comment by Casperhr** [comment]
That would be lovely! Thanks! @tannernelson

**Comment by Casperhr** [comment]
Can be added on the routes manually
