### ISSUE TITLE
Can't compile MySQL on Heroku.

### ISSUE THREAD

**Issue by seivan** [vapor/vapor#622]
I found https://github.com/vapor/vapor/issues/525 and https://github.com/vapor/mysql/issues/29 but they don't seem to resolve the issue. 

For me, one of the benefits of Vapor has been how amazing the API is (very close to Rails, which I like) but also how easy it was to get to heroku out of the box. However that last one failed for me with MySQL today

Here's the build log and my Package.swift
https://gist.github.com/seivan/42bea1e7cf6a5a3ae14e068c0a65bc92

**Comment by tannernelson** [comment]
Looks like the version of MySQL that is getting installed on rails doesn't have JSON support (< MySQL 5.7).

You will need to pass the flag `-Xswiftc -DNOJSON` during the build phase to prevent it from using JSON. Let me know if you need help figuring out how to add that flag.

**Comment by android1989** [comment]
I am in the same boat, and cant seem to find where to add the flag.

**Comment by android1989** [comment]
I figured it out, I copied the buildpack and changed it to include the `-DNOJSON`
@seivan https://github.com/android1989/heroku-buildpack-swift if you want to try

**Comment by seivan** [comment]
@android1989 @tannernelson Looks like doing a `vapor fetch` resolves this for me :) 
I'm closing this if you guys don't mind. It's not an actual issue it seems.
