### ISSUE TITLE
need driver for Oracle and MSSQLSERVER, any Python expert  out there to convert python codes to swift ?

### ISSUE THREAD

**Issue by h1257977** [vapor/vapor#625]
users need drivers for enterprise RDBMS such as oracle and mssqlserver, so if you are a python export help us to migrate the "cx_oracle" code to swift.
here is the link for cx_oracle source code:
https://bitbucket.org/anthony_tuininga/cx_oracle/src

and this for mssqlserver:
https://github.com/michiya/django-pyodbc-azure

**Comment by LoganWright** [comment]
Would love to work on these, but don't have bandwidth to add them to the pipeline quite yet. Hopefully someone w/ experience here is interested in getting these started soon. In the meantime, we're going to close this issue to clean up our board a bit.
