### ISSUE TITLE
Default Middleware non-deterministic

### ISSUE THREAD

**Issue by remko** [vapor/vapor#629]
When not providing a `server.json`, `Droplet.swift` does the following:

          // if not config was supplied,
          // use whatever middlewares were
          // provided
          serverEnabledMiddleware += Array(middleware.values)

The order in `values` is nondeterministic; as a result, on some platforms (e.g. Ubuntu 14.04), `abort` middleware will come before `file` middleware, and this will break serving static files.

**Comment by tannernelson** [comment]
This is being addressed in 1.1. We're making the middleware stuff a lot simpler.

**Comment by LoganWright** [comment]
@tannernelson @remko this is currently fixed in latest version and anything 1.1.x 👍
