### ISSUE TITLE
Socket failed with code 54 ("Exchange full") [readFailed]

### ISSUE THREAD

**Issue by dhamukrish** [vapor/vapor#630]
# Bugs
I have done Vapor load testing in my system (macOS Sierra) using wrk tool. I could see this error when test ends. I haven't introduced any new code apart from Vapor basic template fetched by `vapor new` command.

## Error
`Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 54 ("Exchange full") [readFailed] "Unknown error") `

## Command Used
`wrk -t12 -c400 -d30s http://0.0.0.0:8080`

Please advise.

**Comment by wildfiremedia** [comment]
There was a long discussion in Slack for months and will still need to resolve soon.

**Comment by tannernelson** [comment]
I think it's normal to see this kind of error under such extreme load. 

/cc @czechboy0

**Comment by wildfiremedia** [comment]
Is this also similar to the timeout or error in wrk benchmark?

If that is related, this error should allow to turn off by default that is
annoying in many release and provide false impression to our clients.

**Comment by LoganWright** [comment]
I think this is normal under heavy load, and wrk is notorious about not being good about closing connections etc. I'm going to close this unless something else comes up. Feel free to re-open if applicable!
