### ISSUE TITLE
No middleware fare lower performance?

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#631]
In middleware.json, after commenting out all middleware and leave the main.swift source code unchanged, the performance fare worse with 139K+ vs 250K+ using default middleware, what was affected?

```
{ 
    "server": [
    ],
    "client": [

    ]
}
```

bechmark

```
Running 30s test @ http://localhost:8080
  1 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.50ms   10.98ms 252.53ms   93.96%
    Req/Sec     4.66k     4.67k   11.47k    67.67%
  139101 requests in 30.01s, 148.18MB read
Requests/sec:   4634.52
Transfer/sec:      4.94MB
```

**Comment by tannernelson** [comment]
Can you print the `drop.middleware` to make sure it's empty?

This may be a bug.

**Comment by wildfiremedia** [comment]
I tried to compile ```print(drop.middleware)``` in main.swift and the code below. As far as I encountered in the last few versions it appear to have "no member" error unlike it used to work in the earliest Vapor version like ```drop.middleware = []```.

```
/Users/jtest/hello103/Sources/App/main.swift:13:7: error: value of type 'Droplet' has no member 'middleware'
print(drop.middleware())
      ^~~~ ~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
```

**Comment by wildfiremedia** [comment]
```
import Vapor

let drop = Droplet()

drop.get { req in
    let lang = req.headers["Accept-Language"]?.string ?? "en"
    return try drop.view.make("welcome", [
        "message": Node.string(drop.localization[lang, "welcome", "title"])
    ])
}

print(drop.middleware)

drop.run()
```

**Comment by wildfiremedia** [comment]
After testing with the Engine 1.0.2 it seems to solve the issue that now fare higher score. This can be close but still there are more work to optimise as far as Perfect 2 could get 1.4 million reqs/minute secs vs 720K reqs/minute on Vapor, both are still impressive.

**Comment by tannernelson** [comment]
@wildfiremedia last time I checked Perfect's request parsing violated some parts of the HTTP spec which made it faster. We opted for full conformance to the spec over speed with Engine.

**Comment by wildfiremedia** [comment]
Yes, I do found Kitura and Perfect are similar to each other in performance. I would be interested to know which parts of the HTTP spec were violated?

**Comment by wildfiremedia** [comment]
This issue can be closed.
