### ISSUE TITLE
Generate static webpage method 

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#640]
Hugo is popular and we should generate static website that really help to reduce traffic if the router do not received any new data in the database. Caching web contents maybe similar or different idea?

https://gohugo.io/

**Comment by LoganWright** [comment]
@wildfiremedia we do some view pre-rendering on leaf docs in an effort to help, but caching is definitely something we're working on. We're mostly setting down on an api that gives control as caching can be tricky to get right on client side. 

I've used sites that get it wrong, and even on updates I can't get past the existing cache on something like chrome without deleting specific cookies.

I'm going to close this in preference for caching issues for now, but maybe bring up Hugo in chat, it'd be cool if someon's feeling spunky and wanted to make a similar generater system for Vapor.
