### ISSUE TITLE
Running async code in provider

### ISSUE THREAD

**Issue by skreutzberger** [vapor/vapor#641]
Guys, you know I am working on my logging provider and a part of it is sending logs to our cloud servers for further processing but that seems not to work.

The async sending request via `session.dataTask()` is never finished, maybe because Vapor does not "wait" for it? 

How can I let Vapor wait for my provider to finish its async callback?

Here a quick test which shows what my code is doing but in a route and not in a provider  https://gist.github.com/skreutzberger/ab8f6aa7d4b222e99f24f28e47c0a68b - the callback is never executed.

Thanks!

**Comment by tannernelson** [comment]
If you want it to wait then just call `.wait()` right there. You're free to block the thread that a request comes in on.

**Comment by skreutzberger** [comment]
thanks, I’ll give it a try!
