### ISSUE TITLE
Client file uploads

### ISSUE THREAD

**Issue by JohnEstropia** [vapor/vapor#648]
I've dug through the Vapor documentation but the only method shown to make Client requests is through `drop.client.get` and only with JSON serialization. Nowhere was it mentioned if `multipart/form-data` is supported, and there seems to be no way to pass file streams to any `HTTP.Client`. 

Is this supported/abstracted in Vapor?

**Comment by tannernelson** [comment]
We have a `MultiPart` class that might be able to help you in serializing the data. 

Re: file streams, you will have to send the file data to the client as a chunk of bytes. So just fetch the file and then send using the client.

**Comment by LoganWright** [comment]
@JohnEstropia we now have multipart serialization, check it out and let us know if it isn't adequate to solve your needs.

**Comment by JohnEstropia** [comment]
@LoganWright Awesome, thanks!
