### ISSUE TITLE
Controller destroy resource func ain't working

### ISSUE THREAD

**Issue by syky27** [vapor/vapor#652]
Hi guys,

I have a controller, and I implemented destroy resource, the thing is that when I call the endpoint the item will get deleted, however the code in resource func wont get evaluated.

Checkout the source code here:
https://github.com/syky27/LostSocks-api/blob/86d5e114ed666f213dff4de60269c809da647700/Sources/App/Controllers/SockController.swift#L62

Here is postman collection to make your testing easier:
https://www.getpostman.com/collections/a60d3204f05470b97dd5

Thank you.

**Comment by LoganWright** [comment]
@syky27 trying to look into this a little bit, what do you mean `resource func`, just trying to figure it out. 

Is the `destroy` function getting called?

**Comment by syky27** [comment]
No it is not...

**Comment by syky27** [comment]
This doen't get called when requesting `DELETE ../[id]`

https://github.com/syky27/LostSocks-api/blob/86d5e114ed666f213dff4de60269c809da647700/Sources/App/Controllers/SockController.swift#L62

**Comment by LoganWright** [comment]
@syky27 but it's being deleted from the database successfully? I'm not sure how that's possible, any thoughts?

**Comment by syky27** [comment]
Yes it gets deleted, and the print wont print anything...

**Comment by LoganWright** [comment]
@syky27 I have very rarely seen print statements compiled out weirdly. Can you try returning something other than empty JSON to see if it's calling through?

**Comment by syky27** [comment]
Uhhh.... It is not happening now... Not sure if it was lack of focus or tiredness when I wrote this issue....

Sorry for taking your time
