### ISSUE TITLE
Add SwiftLint support

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#653]
# Feature, Enhancement, or Optimization
# SwiftLint
- Author(s): [Jeroen Wesbeek](https://github.com/4np)
- Subject: [SwiftLint Support](https://github.com/realm/SwiftLint)
## Introduction

[SwiftLint](https://github.com/realm/SwiftLint) is the Swift Linter developed by [Realm](https://realm.io). Using an Xcode script phase is will provide warnings and/or errors in Xcode enforcing common code quality rules. It would be a nice addition if the Vapor xcode template would come out of the box with SwiftLint support.

SwiftLint can be installed using HomeBrew:

```
$ brew install swiftlint
```
## Motivation

Using SwiftLint enforces a common coding style which is very useful when working in larger teams.
## Proposed solution

Add the [SwiftLint Run Script Phase](https://github.com/realm/SwiftLint#xcode):

```
if which swiftlint >/dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

Add a [.swiftlint configuration file](https://github.com/realm/SwiftLint#configuration) to the Xcode template.
## Impact

Currently linting the Vapor code is throwing 2969 issues (of which 999+ warnings and 263 errors), most of which have to do with trailing whitespaces, newlines, colon violations, etcetera. Probably some of the code needs to be updated to comply to the linting rules, while some of those can be disabled in the configuration file if it makes sense.

**Comment by LoganWright** [comment]
We tried this and it was too spammy w/ bots.
