### ISSUE TITLE
Xcode proj created with weird file names like Controllers/PostController.swift

### ISSUE THREAD

**Issue by hyouuu** [vapor/vapor#656]
Followed the instruction to create the Xcode project by doing 'vapor xcode', and the folder structure is created correctly, i.e there is a Hello/Sources/App/Controllers/PostController.swift, and Hello/Sources/App/Models/Post.swift. However, when opening the Xcode project, a file called "Controllers/PostController.swift" is added under the group App wihout a sub-group called Controller

![screen shot 2016-10-19 at 10 04 40 am](https://cloud.githubusercontent.com/assets/5061867/19529253/fb71865a-95e3-11e6-9a6d-b381d0256485.png)

**Comment by sroebert** [comment]
This is solved in the latest Swift snapshot. If you download and use that in the terminal, it will actually created proper groups.

**Comment by marcosgriselli** [comment]
@sroebert preview (Swift 3.0.1 Preview 3) or release?

**Comment by LoganWright** [comment]
@hyouuu closing this since this is SwiftPM and we don't have control over it. It also appears to be resolved in subsequent Swift versions, so hopefully you won't have to deal with it much going forward.
