### ISSUE TITLE
Crashing Swift compiler when using grouped method

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/vapor#662]
On a fresh Vapor project having this main.swift crashes the compiler on the `let api` line:

``` swift
import Vapor

let drop = Droplet()

let api = drop.grouped("api")

drop.run()
```

**Comment by LoganWright** [comment]
Is anyone on pre-release versions of Swift that might be willing to give this a test to see if it's possibly been resolved?

**Comment by tannernelson** [comment]
Can you report this to bugs.swift.org?

**Comment by rustymagnet3000** [comment]
FYI, I hit the same Linker error.   

`Apple Mach-O Linker (ld) Error Group`

Undefined symbols for architecture x86_64:
  "type metadata accessor for Routing.RouteGroup", referenced from:
      type metadata accessor for Routing.RouteGroup<HTTP.Responder, Vapor.Droplet> in main.o
  "protocol witness table accessor for <A, B where B: Routing.RouteBuilder, A == B.Value> Routing.RouteGroup<A, B> : Routing.RouteBuilder in Routing", referenced from:
      lazy protocol witness table accessor for type Routing.RouteGroup<HTTP.Responder, Vapor.Droplet> and conformance <A, B where B: Routing.RouteBuilder, A == B.Value> Routing.RouteGroup<A, B> : Routing.RouteBuilder in Routing in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rustymagnet3000** [comment]
xCode 8.1 Toolchain.
.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 1)

**Comment by LoganWright** [comment]
@rustymagnet3000 thank you for letting us know. At this point, I'm not sure what to do since it seems like the Swift compiler is unable to handle this type.

For the record, explicitly typing the object seems to work. I think for now that's the best solution.

```
let explicit: RouteGroup<Responder, Droplet> = drop.grouped("v1")
```

**Comment by kdawgwilk** [comment]
@LoganWright even `let explicit: RouteGroup = ...` is working for me

**Comment by kdawgwilk** [comment]
@tannernelson Reported here: https://bugs.swift.org/browse/SR-3105

**Comment by LoganWright** [comment]
@kdawgwilk sorry, two steps:

```swift
import Routing

let explicit: RouteGroup<Responder, Droplet> = drop.grouped("v1")
```

**Comment by LoganWright** [comment]
Closing since this is a swift compiler issue, we have workarounds, and there's nothing we can do.
