### ISSUE TITLE
Share prefix for route and resource not works

### ISSUE THREAD

**Issue by quen2404** [vapor/vapor#665]
If i share a route prefix with a routing parameter between a route and a resource, the route is never executed.

A simple example: let's start with this project https://github.com/vapor/basic-template
edit `Sources/App/main.swift`:

```
drop.resource("posts", PostController())
drop.get("posts", Int.self, "comments") { request, post in return "test" }
```

If you send a `GET /posts/1/comments`, the response will be `404 Not found`.
The param of the request is of type `Int` to validate the bug without db. But it can be changed to `Post`
If you reverse the two lines, the request `GET /posts/1/comments` will return `200 OK` but all requests associated to the `PostController` won't work.
Tested with `Vapor-1.1.3`

**Comment by kdawgwilk** [comment]
I am also having a similar issue 👍

**Comment by quen2404** [comment]
@LoganWright give me a temporary workaround:
replace my 2nd line by:
```
drop.get("posts", ":id", "comments") {  request in 
    guard let postId = request.parameters["id"].int else {
        throw Abort.badRequest
    }
    return "test" 
}
```
It could help pending the fix

**Comment by tannernelson** [comment]
@quen2404 Does changing the order of the routes being registered affect it at all?

**Comment by quen2404** [comment]
Yes it seems that only the first route registered works. Next are skipped

**Comment by LoganWright** [comment]
@quen2404 @tannernelson @kdawgwilk 

Unfortunately, this is an issue with our fundamental routing model. Let's take these two routes:

```
foo/:a
foo/:b/bar
```

The way many routers work is to have two routes like this:

```
| foo |  :a |
| foo |  :b | bar |
```

The way our router works is more like this:


```
                 foo
                  |
                  :a
                  |
                  bar
```

This gives us really amazing performance as number of routes increases, unfortunately it makes multiple slugs of different names difficult. Here's some potential solutions off hand:

### Naming Conventions

We enforce some sort of naming convention where slugs are always named consistently.

### Ordered List

We remove named slugs altogether and use some type of ordered list approach

### Something Else

I'm still brainstorming alternative options. Happy to hear suggestions! I'd prefer to keep our branch based data model for performance reasons.

**Comment by LoganWright** [comment]
This has the integrated warning to help in interim:

https://github.com/vapor/vapor/releases/tag/1.1.7

**Comment by kdawgwilk** [comment]
I think what I am wanting to do seems related to this.  I created an issue here #676

**Comment by LoganWright** [comment]
@kdawgwilk definitely very much related, I see it as two issues though. 1 is the inability to redefine the key of a slug parameter, 2. is the inability to use type safe routing with generics.

I don't think solving this would necessarily make #676 easier since either way we need to generate keys.

**Comment by LoganWright** [comment]
This is all supported now.
