### ISSUE TITLE
Unable to test application code with basic template

### ISSUE THREAD

**Issue by skyweb07** [vapor/vapor#667]
Is there any way of testing the application code with the default template?. The default template automatically exclude the Tests https://github.com/vapor/basic-template/blob/master/Package.swift#L14 and even after removing that exclusion I can't find a way to proper test my application becaue the framework generated by vapor is not available on the test target. Do you guys know any way to fix this?

Thanks for this amazing framework!

**Comment by LoganWright** [comment]
@skyweb07 it's a few steps 👍 

# Step 1: Displace Droplet creation Logic

Move the droplet logic out of main.swift

```swift
func load(_ drop: Droplet) throws {
    drop.get { _ in return "put logic in this `load` function" }
}
```

At this point, your `main.swift` should look something like this:

```swift
let drop = Droplet(...
try load(drop)
drop.run()
```

# Step 2: Initialize for Tests

Now we need to initialize for tests, I make a little function for this as well


```swift
func makeTestDroplet() throws -> Droplet {
    let drop = Droplet(arguments: ["path/to/exe", "prepare"], ...
    try load(drop)
    try drop.runCommands()
    return drop
}
```

- Notice the `arguments` parameter in the initializer. You can put whatever else you need to in initialization, but the arguments parameter is a requirement.

- Notice that we're calling runCommands. This will execute prepare without blocking main or exiting.

# Step 3: Use

Now you can test as normal

```swift
func testEndpoint() throws {
    let drop = try makeTestDroplet()
    let request = ...
    let expectedBody = ...
    let response = try drop.respond(to: request)
    XCTAssertEqual(expectedBody, response.body.bytes)
}
```

Adjust as necessary 👍

**Comment by skyweb07** [comment]
Wow, thanks for the detailed explanation, it's a little work but it worth it to have a fully tested application and go to production with more confidence, I'll try this approach and check if this works . Thanks you again!!! 👍

**Comment by cwoloszynski** [comment]
Thank you! This goes a long way to helping folks like myself!

**Comment by LoganWright** [comment]
@cwoloszynski I'm going to work out a slightly expanded version of this and put it into documentation for others to reference/improve 👍

**Comment by LoganWright** [comment]
Merged testing docs today.
