### ISSUE TITLE
When initializing a Droplet the default resources are not availably anymore

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#669]
When starting a new project and initializing a `Droplet` the non-default way, the resources are not available anymore. Initializing a `Droplet` the default way and then adding a provider afterwards _does_ work:

*Does not work*:

```
let drop = Droplet(
    providers: [VaporMySQL.Provider.self]
)
```

*Works*:

```
let drop = Droplet()
try drop.addProvider(VaporMySQL.Provider.self)
```

# Steps to reproduce

### 1. Create a new project

```
vapor new someproject
```

### 2. Add the MySQL driver to Package.swift

```
...
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 1),
        .Package(url: "https://github.com/vapor/mysql-provider.git", majorVersion: 1)
    ],
...
```

### 3. Add a Config/mysql.json configuration file

```
{
    "host": "localhost",
    "user": "root",
    "password": "",
    "database": "test"
}
```

and create the database:

```
echo "create database test" | mysql -u root
```

### 4. Update main.swift to add the MySQL Provider

Change the file and add the `VaporMySQL` import and configure the `Droplet` to use the MySQL Provider.

```
import Vapor
import VaporMySQL

// initialize Droplet
let drop = Droplet(
    providers: [VaporMySQL.Provider.self]
)

drop.get { req in
    return try drop.view.make("welcome", [
    	"message": drop.localization[req.lang, "welcome", "title"]
    ])
}

// resource for registering new devices
drop.resource("devices", DeviceController())

drop.run()
```

### 5. Run the app

```
vapor build --clean; vapor run serve
```

### 6. Navigate to http://localhost:8080

Notice that the CSS is not being loaded. Also note that when you remove the provider (e.g. initialize the Droplet the default way: `let drop = Droplet()`) _does_ work.

![screen shot 2016-10-27 at 17 11 31](https://cloud.githubusercontent.com/assets/1049693/19773269/33942386-9c69-11e6-8f50-f614f46abf07.png)

Both resources ([css](http://localhost:8080/styles/app.css) and [image](http://localhost:8080/images/vapor-logo.png)) result in a 404.

**Comment by LoganWright** [comment]
@4np are you seeing any logs matching to: 

`Could not initialize provider Provider: noMySQLConfig`?

Follow up, can you try the updated syntax of:

```swift
let drop = Droplet()
try drop.addProvider(VaporMySQL.Provider.self)
```

**Comment by 4np** [comment]
Hi @LoganWright,

I have tried both. Initializing the Droplet with a provider does not work while initializing a Droplet the default way and then _adding_ a provider _does_ work properly. Both don't throw any errors about missing MySQL configurations... 

### let drop = Droplet(providers: [VaporMySQL.Provider.self])

```
$ vapor build; vapor run serve
Fetching Dependencies [Done]
Building Project [Done]
Running server...
No preparations.
Server 'default' starting at 0.0.0.0:8080
GET /
GET /styles/app.css
```

### let drop = Droplet() and try drop.addProvider(VaporMySQL.Provider.self)

```
$ vapor build; vapor run serve
Fetching Dependencies [Done]
Building Project [Done]
Running server...
No preparations.
Server 'default' starting at 0.0.0.0:8080
GET /
GET /styles/app.css
```

**Comment by 4np** [comment]
By the way, I forgot to mention in the issue above, I _do_ have a `mysql.json` configuration...

**Comment by 4np** [comment]
Same thing happens when initializing a `Droplet` by passing in `Model` preparations:

```
let drop = Droplet(preparations: [SomeModel.self])
```

**Comment by LoganWright** [comment]
@4np that won't even run for me w/o a db, but I'd like to follow up similarly. My goal is to get you around the deprecated initializer to see if that's part of the issue. Can you try:

```
let drop = Droplet()
drop.preparations.append(SomeModel.self)
```

**Comment by 4np** [comment]
@LoganWright that does indeed work fine as well. I wasn't aware though the initializer is deprecated?

**Comment by LoganWright** [comment]
@4np awesome! It should be logging deprecation warnings in your build logs and showing yellow in Xcode. The underlying issue that I suspect you're hitting is a little tricky to fix in current api. Part of the reason for the deprecation 😄 

Let me know if you have other problems!
