### ISSUE TITLE
Vapor self update never finishes

### ISSUE THREAD

**Issue by Ponyboy47** [vapor/vapor#670]
I was on vapor 1.1.0 and noticed I could update to 1.1.5. I ran the vapor self update command and it did a lot of work at first, but then once it hit a mv command it's been stuck there for hours...I'm fairly certain no move command should take this long and I'm wondering if there is something I could do to help it move past this?

I have tried stopping the update with ctrl-c and restarting it, but it gets to the mv part again and then just runs forever...

**Comment by Ponyboy47** [comment]
I've realized that it is the vapor self install command that is run at the end of updating and is never finishing

**Comment by LoganWright** [comment]
@Ponyboy47 Hey, two things on this.

Looks you've got something going on w/ your toolbox, I'm not sure what. We can deal with that separately, first I want to see what you're trying to do.

Vapor is 1.1.5, but Toolbox is 1.0.3 I believe. If you are trying to update your project from 1.1 to 1.1.5, simply update your Package.swift (this is likely unnecessary!). Then just do

```
vapor clean
```

Now we've cleaned out, regenerate xcode or rebuild and it'll pull latest!

```
vapor build
or
vapor xcode -y
```

You can check by doing this _after_ build or xcode gen:

```
ls Packages/
```

And look for `Vapor-1.1.5`

**Comment by LoganWright** [comment]
@Ponyboy47 I'm going to close this for now, if you're still having issues, please re-open and tag me!
