### ISSUE TITLE
Support type safe routing with groups

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/vapor#676]
# Support type safe routing with groups

* Author(s): [Kaden Wilkinson](https://github.com/kdawgwilk)

## Introduction

It would be nice to form RouteGroups that had types built into them

## Motivation

I was hoping to do something similar to this: 
```swift
v1.group("users", User.self) { user in
    user.resource("group", GroupController())
}
```
Which would allow me to create collections attached to another resource, but I was getting the following error:  `Ambiguous reference to member 'group(_:closure:)'`

## Impact

I would hope this could be done as adding support rather than removing any support to allow full backwards compatibility

## Alternatives considered

I am not aware of any obvious alternatives but would love to have one as a temporary workaround

-----

As I finished typing this issue I realized there is quite a bit of complexity to this problem.  The group controller would need to know which user was being requested so that the right groups could be returned...I will look at other frameworks to see if this is even something that is a common use case.

**Comment by kdawgwilk** [comment]
What I am trying to do is get a url like the following `/users/:user_id/groups/:group_id` etc.  This is idea is pulled from the "REST API Design Rulebook"

**Comment by kdawgwilk** [comment]
Well I did hack something together but its ugly and only allows me to go 2 levels deep :( Still have no idea how I can get a route like this and have it be elegant:
`/users/:user_id/groups/:group_id/tasks/:task_id`

**Comment by LoganWright** [comment]
@kdawgwilk this is definitely something we'd love to have. I've personally sunk huge amounts of time into it, so I'm happy to let you know everything that I tried. It's definitely possible, but it is unfortunately extremely difficult to setup a pattern that can be replicated ad infinitum, so we usually get stuck w/ more generated code, or something that doesn't go very deep.

We've been encouraging the use of `:slug` syntax, in grouped types. Feel free to keep working, I'm hoping that some future generic additions will make this a more feasible option.

**Comment by LoganWright** [comment]
I'm going to close this issue for now, I gave it another go and I'm convinced this can't be done w/o generation right now. Let's reopen this when we start getting more generic support w/ Swift 4. I want this to exist 🙌
