### ISSUE TITLE
Resource Deadlock Avoided

### ISSUE THREAD

**Issue by LoganWright** [vapor/vapor#678]
We need to investigate this error

```
15:27 $ vapor run serve
Running Trivia...
[DEPRECATED] Providers should implement the `boot(_: Droplet)` method to register dependencies. The `provided` property will be removed in a future update.
Database prepared
Server 'default' starting at 0.0.0.0:8080
GET /questions
Optional(Node.Node.string("d80819581d90247542916c52"))
Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource deadlock avoided") [readFailed] "Unknown error"))
```

It seems like a good thing to avoid a deadlock, so maybe it's not so much a problem. Either way, we'll need an answer.

**Comment by hyouuu** [comment]
Chime in related issues:

Followed the Sessions section, then I used Chrome to open localhost:8080/remember, but it gives:
GET /remember
Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource deadlock avoided") [readFailed] "Unknown error"))

However, if I use postman to do a GET at the same url, the correct result is returned

**Comment by skreutzberger** [comment]
I have the same error. It seems to occur exactly 30 seconds after a route sent a string via `return`.

```swift

app.get("/") { request in
  return "hello"
}
```
-> sends a normal HTTP 200 with the content "hello" and after 30 seconds throws that error. SwiftyBeaver tells me that the issue is in `Droplet.serverErrors()` line 319.

**Comment by 4np** [comment]
Same here, I am seeing these lines at regular intervals as well:

```
10:44:21.391 ❤️ ERROR Droplet.serverErrors():319 - Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource deadlock avoided") [readFailed] "Unknown error"))
```

**Comment by LoganWright** [comment]
We'll keep working on it guys, thanks for the input

**Comment by PorterHoskins** [comment]
I am seeing this error when trying to use WebSockets. The WebSocket will disconnect at exactly 30 seconds.

```
Server error: dispatch(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource deadlock avoided") [readFailed] "Unknown error"))
```

**Comment by AlexKel** [comment]
Got the same issue as @PorterHoskins .. The issue seems to be related to the socket's `stream` object. If I use `setTimeout:` function of `stream` object inside `WebSocket.swift`- this doesn't disconnect the socket (until specified timeout), but I do still get the error :)

**Comment by AlexKel** [comment]
@PorterHoskins the actual timeout default value seems to be set inside `HTTP+Server.swift` on line 76 (in my build): `try stream.setTimeout(30)`

**Comment by PorterHoskins** [comment]
Good find. I should probably log another issue about making the timeout configurable.

**Comment by LoganWright** [comment]
@hyouuu @skreutzberger @4np @AlexKel 

After further research, this error is a result of us adding a read timeout to our sockets that should have been there in the beginning. I can confirm that all requests are being handled properly on my end, and the socket doesn't fail until it times out after remaining stale for 30 seconds.

Internally we need to figure out how to properly understand and catch timeouts from the socket layer, but in the meantime, this shouldn't have a negative effect on your projects.

@PorterHoskins this is also related to your WS issue, we're setting up a ping api that you will be able to enable and should be merged soon. We'll keep you informed.

**Comment by skreutzberger** [comment]
Since it is not really an error or issue, what do you think about removing the `log.error()` for it? My logs are currently filling up with each request  😳

**Comment by LoganWright** [comment]
@skreutzberger I'm trying to find the best way to do it to make sure there's nothing we're not handling properly. In short term, it might be worth just silencing until we have a more long-term solution.

If others are on board, I'll try and get that in tonight/first thing tomorrow morning.
