### ISSUE TITLE
Doc needs lots of update - e.g. the Model section refers to deprecated methods

### ISSUE THREAD

**Issue by hyouuu** [vapor/vapor#679]
e.g. this line:
let drop = Droplet(preparations: [User.self])

Is no longer  applicable since it's deprecated, but couldn't find any reference to how to do it correctly

**Comment by 4np** [comment]
+1, this was also causing issue #669

**Comment by tannernelson** [comment]
Good catch. That should have been updated a while ago.

Here is a PR for the updates: https://github.com/vapor/documentation/pull/71

Also here is a migration guide from 1.0 to 1.1 for those interested: https://github.com/vapor/vapor/releases/tag/1.1.0
