### ISSUE TITLE
Leaf: negating statements

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#680]
# Feature, Enhancement, or Optimization
# Negating statements and conditions
- Author(s): [Jeroen Wesbeek](https://github.com/4np)
- Subject: [Leaf templating](https://vapor.github.io/documentation/guide/leaf.html) 🍃

## Introduction

While it is currently possible to use `if`, `then`, `else` statements (see the [documentation](https://vapor.github.io/documentation/guide/leaf.html#if---else)), you can only use statements that evaluate to true. It would be great to use negating statements.

```
#if(entering) {
  Hello, there!
} ##if(leaving) {
  Goodbye!
} ##else() {
  I've been here the whole time.
}
```

## Motivation

Evaluating false statements currently requires you to write dummy else constructs which are rather inconvenient:

```
#loop(elements, "element") {
    <option value="#(element.id)" #if(element.enabled) { } ##else() { disabled }>#(element.name)</option>
}
```

Additionally a condition containing an evaluation (e.g. `#if(device.enabled == false) { disabled }`) also does not work.

## Proposed solution

Introduce negating statements:

```
#if(!element.enabled)
```

Applying this to the above example this would lead to the more convenient code:

```
#loop(elements, "element") {
    <option value="#(element.id)" #if(!element.enabled) { disabled }>#(element.name)</option>
}
```

## Extra

It would also be great if evaluating expressions would work so that `#if(device.enabled == false) { disabled }` would work as well.

**Comment by tannernelson** [comment]
Off the top of my head `!`, `==`, etc look like Leaf 2.0 features to me.

Something like `#ifNot()` and `#notEqual()` would work for `!`. We have `#if` and `#equal()`.
