### ISSUE TITLE
Leaf: nesting templates

### ISSUE THREAD

**Issue by 4np** [vapor/vapor#681]
# Feature, Enhancement, or Optimization
# Nesting templates
- Author(s): [Jeroen Wesbeek](https://github.com/4np)
- Subject: [Leaf templating](https://vapor.github.io/documentation/guide/leaf.html) 🍃

## Introduction

Currently it is possible to `extend` base templates and `export` sections, but you cannot template specific elements that make up page. 

## Motivation

Very commonly pages consist of commonly re-used elements that might include their own templating logic. Consider for example headers, footers and menus (look at [Bootstrap's sticky header example](http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/)). It would be great if a template can include child templates that in turn contain their own templating logic.

### base.leaf

```
<!DOCTYPE html>
<html>
<head>
    #import("head")
</head>
<body>
    <!-- navbar //-->
    #import("base-navbar")

    <!-- Begin page content -->
    <div class="container">
      #import("body")
    </div>

    <!-- footer //-->
    #import("base-footer")
</body>
</html>
```

# base-navbar.leaf 
_(inspired by Bootstrap's [sticky footer example](http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/))_

```
<div class="pos-f-t">
  <div class="collapse" id="navbar-header">
    <div class="container bg-inverse p-1">
      <h3>Collapsed content</h3>
      <p>Toggleable via the navbar brand.</p>
    </div>
  </div>
  <nav class="navbar navbar-light navbar-static-top bg-faded">
    <div class="container">
      <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-expanded="false" aria-controls="exCollapsingNavbar2" aria-label="Toggle navigation"></button>
      <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
        <a class="navbar-brand" href="#()">Home</a>
        <ul class="nav navbar-nav">
        #loop(elements, "element") {
          <li class="nav-item #if(element.active) { active }">
            <a class="nav-link" href="#(element.url)">#(element.title)</a>
          </li>
        }
        </ul>
      </div>
    </div>
  </nav>
</div>
```

# base-footer.leaf
_(inspired by Bootstrap's [sticky footer example](http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/))_

```
    <footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>
```

## Proposed solution

Allow a Leaf template to include child templates, effectively nesting templates. Regardless of the template being a base template (which is extended by child templates), a child template (which extends a base template) or a nested template (imported by a base or a child template).

### Option a: Import a child template using the `import` statement

```
#import("child-template")
```

### Option b: Import a child template using a new `template` statement

As the `import` statement is currently already used by importing sections that are `exported` by child template it might lead to confusion if the same statement will also import child templates. If so, therefore it might be better to import child templates using a different syntax to distinguish between the two.

```
#template("child-template")
```

**Comment by wallstead** [comment]
I was just trying to do this. I was surprised that it wasn't already implemented.

**Comment by rymcol** [comment]
I would also love to see this. +1

**Comment by tanner0101** [comment]
Is this not achievable with `#embed`? https://vapor.github.io/documentation/guide/leaf.html#embed

**Comment by BrettRToomey** [comment]
@4np Could you respond to @tanner0101, please? Feel free to reopen this when you're ready.
