### ISSUE TITLE
Make stream timeout configurable

### ISSUE THREAD

**Issue by PorterHoskins** [vapor/vapor#684]
I am trying to build an application with WebSockets but the socket keeps closing on me.

The timeout default value seems to be set inside `HTTP+Server.swift` on line 76 (in my build): `try stream.setTimeout(30)`. It seems setting it to 0 won't automatically close the socket. Is there a proper way of specifying this for web sockets?

**Comment by LoganWright** [comment]
@PorterHoskins That's odd, are you using a server or client socket? Also, I'm unclear about setting timeout to 0. Are you trying to do that to close it?

Right now I'm thinking that whatever you're using could benefit from some sort of ping/pong every ~30 seconds to keep the connection active. If vapor receives a ping, you can hook into it, but the library should respond automatically according to spec.

**Comment by PorterHoskins** [comment]
So I am using:
```
drop.socket("socket") { _, ws in

}
```
to make a socket with a client. If nothing is sent over the wire for 30 seconds then the socket will close. Is that how it is supposed to work? Do I have to send something every 30 seconds to keep it alive?

**Comment by tannernelson** [comment]
Is it possibly related to this? https://github.com/vapor/socks/pull/85

That's the only thing that has changed with sockets recently and it's related to the timeout code.

As far as I can tell it's doing the exact same thing, though...

**Comment by tannernelson** [comment]
@PorterHoskins are you using SSL at all or just plaintext?

**Comment by PorterHoskins** [comment]
@tannernelson just using plaintext at the moment.

**Comment by tannernelson** [comment]
@PorterHoskins Just realized that we don't send pings automatically. The WebSocket spec recommends against it. 

I'll add an easier way to send pings in a minor update to WebSockets but basically if you want to keep the connection open for more than the timeout, you must send pings.

```swift
import Vapor

let drop = Droplet()

drop.socket("test") { req, ws in
    try background {
        if ws.state == .open {
            print("ping")
            try? ws.ping()
            drop.console.wait(seconds: 10)
        }
    }

    ws.onText = { ws, text in
        let rev = String(text.characters.reversed())
        print(rev)
        try ws.send(rev.bytes)
    }

    ws.onClose = { ws, code, reason, clean in
        print("closed")
    }
}

drop.run()
```

This is what the code should look like. 

I'm looking into an API like

```swift
try ws.ping(every: 10)
```

For easily adding an automatic ping to the connection.

**Comment by tannernelson** [comment]
Updated docs here: https://vapor.github.io/documentation/websockets/droplet.html

**Comment by tannernelson** [comment]
Issue: https://github.com/vapor/engine/issues/70

**Comment by PorterHoskins** [comment]
Awesome. Thanks!
