### ISSUE TITLE
Testing documentation

### ISSUE THREAD

**Issue by plu** [vapor/vapor#695]
In the [testing documentation](https://vapor.github.io/documentation/testing/basic.html) it is suggested to do this:

```swift
import Vapor

func makeTestDroplet() throws -> Droplet {
    let drop = Droplet(arguments: ["dummy/path/", "prepare"], ...)
    try load(drop)
    try drop.runCommands()
    return drop
}
```

Unfortunately `runCommands`'s visibility is `internal`, so this does not work (anymore?).

**Comment by mcdappdev** [comment]
You need to add 

`@testable import Vapor`

**Comment by plu** [comment]
Ah. Shame on me that I didn't think about that. Thanks :).

**Comment by LoganWright** [comment]
@plu I need to fix that in docs!
