### ISSUE TITLE
Vapor Docker run / compile problem

### ISSUE THREAD

**Issue by andrew804** [vapor/vapor#697]
I'm having a few issues running vapor with docker. Using the vapor hello world example I can build and run the server locally all fine. I then use vapor's docker init command `vapor docker init 3.0` to generate the Docker file. It then prompts me to build which goes okay and then run using the docker run command `docker run --rm -it -v $(PWD):/vapor -p 8080:8080 vapor/swift:swift-3.0-RELEASE`. The first few times I try and run, a number of exceptions are generated when it tries to compile some of the CLibreSSL files, for example:

> Compile CLibreSSL a_sign.c
Compile CLibreSSL a_strex.c
Compile CLibreSSL a_strnid.c
/vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/a_sign.c:123:10: fatal error: 'include/x509.h' file not found
#include "include/x509.h"
         ^
Compile CLibreSSL a_time.c
In file included from /vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/a_strnid.c:63:
In file included from /vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/include/asn1.h:67:
In file included from /vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/include/bio.h:69:
/vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/include/crypto.h:126:10: fatal error: 'stack.h' file not found
#include "stack.h"
         ^
Compile CLibreSSL a_time_tm.c
error: error opening '/vapor/.build/debug/CLibreSSL.build/a_set.c.d': Transport endpoint is not connected
fatal error: error in backend: IO failure on output stream.
In file included from /vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/a_strex.c:64:
/vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/include/x509.h:73:10: fatal error: 'evp.h' file not found
#include "evp.h"
         ^
Compile CLibreSSL a_type.c
Compile CLibreSSL a_utf8.c
0  swift-build-tool 0x000000000050bade llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 46
1  swift-build-tool 0x000000000050ca49
2  swift-build-tool 0x000000000050cd53
3  libpthread.so.0  0x00007fe1d29c1330
4  libc.so.6        0x00007fe1d1bfec37 gsignal + 55
5  libc.so.6        0x00007fe1d1c02028 abort + 328
6  swift-build-tool 0x00000000004f91f4
7  swift-build-tool 0x00000000004e0ce3
8  swift-build-tool 0x00000000004d965d
9  swift-build-tool 0x00000000004d955b llbuild::core::BuildEngine::build(std::string const&) + 43
10 swift-build-tool 0x00000000004b99a0
11 swift-build-tool 0x00000000004b9823 llbuild::buildsystem::BuildSystem::build(llvm::StringRef) + 67
12 swift-build-tool 0x000000000049150d llbuild::buildsystem::BuildSystemFrontend::build(llvm::StringRef) + 1405
13 swift-build-tool 0x000000000048e086
14 swift-build-tool 0x000000000048dc7a main + 170
15 libc.so.6        0x00007fe1d1be9f45 __libc_start_main + 245
16 swift-build-tool 0x000000000048db04
error: no build YAML found: /vapor/.build/debug.yaml

After a few attempts and without changing anything these finally compile with no exceptions. Then it starts trying to compile the swift modules. Exceptions are generated for a number of modules like SMTP, Vapor, App etc, for example:

> Compile Swift Module 'URI' (10 sources)
Compile Swift Module 'HTTP' (37 sources)
Compile Swift Module 'SMTP' (21 sources)
0  swift           0x000000000333cb08 llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 40
1  swift           0x000000000333b2d6 llvm::sys::RunSignalHandlers() + 54
2  swift           0x000000000333d63a
3  libpthread.so.0 0x00007f9174261330
4  libc.so.6       0x00007f9172b48ca4
5  swift           0x000000000119f765 swift::moveFileIfDifferent(llvm::Twine const&, llvm::Twine const&) + 517
6  swift           0x0000000000d5285e
7  swift           0x0000000000d5259b swift::serialize(llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::SerializationOptions const&, swift::SILModule const*) + 235
8  swift           0x00000000007e062d
9  swift           0x00000000007dbab7 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 2887
10 swift           0x00000000007a7568 main + 2872
11 libc.so.6       0x00007f9172a0af45 __libc_start_main + 245
12 swift           0x00000000007a4f66
Stack dump:
> 0.	Program arguments: /usr/bin/swift -frontend -c /vapor/Packages/Engine-1.2.0/Sources/HTTP/Async/Response+Async.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Chunk/Body+Chunk.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Chunk/ChunkStream.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Chunk/Response+Chunk.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Client/Client.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/FoundationClient/Client+Foundation.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/FoundationClient/Request+Foundation.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/FoundationClient/Response+Foundation.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/FoundationClient/URI+Foundation.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Middleware/Middleware+Chaining.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Middleware/Middleware.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Parser/HTTPParser+Method.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Parser/HTTPParser+Version.swift -primary-file /vapor/Packages/Engine-1.2.0/Sources/HTTP/Parser/HTTPParser.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Parser/HTTPParserProtocol.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Program/Program.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Serializer/Serializer+Headers.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Serializer/Serializer+URI.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Serializer/Serializer.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Serializer/SerializerProtocol.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Server/Server.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Server/ServerError.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Body/Body+Bytes.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Body/Body.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Body/BodyRepresentable.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Client/HTTP+Client.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Headers/Headers.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Messages/Message+CustomStringConvertible.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Messages/Message.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Method/Method.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Request/Request.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Responder/Responder.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Response/Response.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Response/ResponseRepresentable.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Server/HTTP+Server.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Status/Status.swift /vapor/Packages/Engine-1.2.0/Sources/HTTP/Models/Version/Version.swift -target x86_64-unknown-linux-gnu -disable-objc-interop -I /vapor/.build/debug -enable-testing -g -module-cache-path /vapor/.build/debug/ModuleCache -D SWIFT_PACKAGE -Xcc -fmodule-map-file=/vapor/Packages/CLibreSSL-1.0.0/Sources/CLibreSSL/include/module.modulemap -emit-module-doc-path /vapor/.build/debug/HTTP.build/HTTPParser~partial.swiftdoc -Onone -parse-as-library -module-name HTTP -emit-module-path /vapor/.build/debug/HTTP.build/HTTPParser\~partial.swiftmodule -emit-dependencies-path /vapor/.build/debug/HTTP.build/HTTPParser.d -emit-reference-dependencies-path /vapor/.build/debug/HTTP.build/HTTPParser.swiftdeps -num-threads 8 -o /vapor/.build/debug/HTTP.build/Parser/HTTPParser.swift.o 

Running the command a few more times eventually makes everything compile okay without any exceptions. The server starts at 0.0.0.0:8080. Yay. Go to load in the browser and suddenly the server stops running logging ‘buss error’ in the console.

This behaviour seems unstable but I have no idea what is going wrong.

**Comment by LoganWright** [comment]
Docker commands didn't add anything to toolbox, and have been removed see vapor/docker for info on using Vapor w/ docker 👍

**Comment by patchthecode** [comment]
@LoganWright vapor/docker .. where is the link?
I'm not finding it.

**Comment by vzsg** [comment]
https://github.com/vapor/docker
