### ISSUE TITLE
Outgoing HTTPS calls fail on Heroku

### ISSUE THREAD

**Issue by maciejtrybilo** [vapor/vapor#699]
There seems to be an issue making HTTPS calls when running on Heroku. The snippet below illustrates the issue. It returns the Google page html when I run the server either on macOS or Ubuntu locally, but on Heroku it returns `The operation could not be completed`. 

It does work on Heroku when I try to make a call to an HTTP endpoint.

```
typealias HollaClient = Client<TCPClientStream, Serializer<Request>, Parser<Response>>

drop.get("holla") { request in
    
    let response: Response
    
    do {
        
        response = try HollaClient.get("https://www.google.co.uk")
        
    } catch let error {
        
        response = Response(body: error.localizedDescription)
    }
    
    return response
}
```

What would be the best way to get more information on that?

**Comment by LoganWright** [comment]
@maciejtrybilo we're having problems loading underlying SSL certificates on Heroku, in the meantime, can you try `FoundationClient` to see if you have the same problem?

```swift
typealias HollaClient = FoundationClient
```

Alternatively to set on drop

```swift
drop.client = FoundationClient.self
```

**Comment by maciejtrybilo** [comment]
@LoganWright Thanks! My example works now on Heroku. The FoundationClient seems to have an issue of its own however. When I'm trying to POST, on Linux something is wrong with passing the message body. The endpoint is complaining that I'm not passing parameters. It works on macOS, but not on Heroku or my local Ubuntu box. I'll investigate further and maybe will open another issue.

**Comment by LoganWright** [comment]
@maciejtrybilo if you can give me repro steps, I can try to recreate it and take a look on my end!

**Comment by maciejtrybilo** [comment]
@LoganWright thanks, there must've been something with URLSession. Updating to Swift 3.0.1 sorted it.

**Comment by valeriomazzeo** [comment]
I have noticed that disabling `verifyCertificates` in `client.json` makes `drop.client` work:
`"verifyCertificates": false,`

**Comment by maciejtrybilo** [comment]
Disabling a function called `verifyCertificates` doesn't fill me with confidence...

**Comment by valeriomazzeo** [comment]
@maciejtrybilo  I didn't suggest disabling it, just pointed out additional information.

The problem is the `#file` directive used in `Certificates.swift`, on heroku everything gets build inside a `tmp` directory then it gets moved into `app`, but `#file` gets replaced at compile time so then it can't load the certificates :)

Same issue for the error pages.

**Comment by valeriomazzeo** [comment]
@maciejtrybilo perhaps this issue should be reopen

@LoganWright do you have any idea of when this could be taken care of?

**Comment by shial4** [comment]
to use `FoundationClient ` remember to import `import HTTP`

**Comment by Ze-ro-G** [comment]
Have the same issue here. Did anyone find a solution ?
