### ISSUE TITLE
Vapor server usage memory is growing day by day

### ISSUE THREAD

**Issue by dhamukrish** [vapor/vapor#700]
I am not sure what causes this issue as I can see memory usage is growing higher (20.4MB) every day and below screenshots taken different intervals. Also note that my site is getting monitored every 5 min via https://uptimerobot.com.

Site only have few routes with 6 Leaf templates

This Vapor site (http://www.efficientdriver.net) is running on Digital Ocean 1CPU, 512MB RAM, Ubuntu 16.04.1, Nginx as Reverse Proxy.

10 Days Later (17.2MB)
<img width="910" alt="screen shot 2016-11-13 at 1 47 27 pm" src="https://cloud.githubusercontent.com/assets/9908852/20244435/e5921c14-a9a7-11e6-8cc5-3f7a05512704.png">

12 Days Later (20.4MB)
<img width="905" alt="screen shot 2016-11-12 at 1 12 50 pm" src="https://cloud.githubusercontent.com/assets/9908852/20244434/e5915d2e-a9a7-11e6-927f-6525d7e6d6a8.png">

After Server Restart (4.7MB)
<img width="906" alt="screen shot 2016-11-13 at 1 50 56 pm" src="https://cloud.githubusercontent.com/assets/9908852/20244445/48c9804c-a9a8-11e6-95d3-5334a2d24125.png">

Please advise.

**Comment by ipconfiger** [comment]
memory leak?

**Comment by andreasley** [comment]
@dhamukrish Is `environment` set to `development`? If so, the problem might be fixed with [Leaf 1.0.3](https://github.com/vapor/leaf/releases/tag/1.0.3). Older versions of `Leaf` contained a memory leak, which was exacerbated by the fact that recent versions of Vapor disabled caching in `development` mode.

**Comment by dhamukrish** [comment]
@andreasley. Yes, it was set to development and now changed to production and updated Leaf to 1.0.3. Let me watch for next 3 days and advise.

Below is the current snapshot.
<img width="1054" alt="screen shot 2016-11-15 at 6 10 07 am" src="https://cloud.githubusercontent.com/assets/9908852/20288637/bfb2f51e-aafa-11e6-9c60-0836e4e035b7.png">

**Comment by dhamukrish** [comment]
I have observed for few days and issue disappears now. Thanks for your help @andreasley.

**Latest memory snapshot**
<img width="1060" alt="screen shot 2016-11-20 at 7 06 16 am" src="https://cloud.githubusercontent.com/assets/9908852/20459672/04fc647c-aef0-11e6-835e-7d7dd814fb3b.png">

**Comment by dhamukrish** [comment]
This can be closed.
