### ISSUE TITLE
Toolbox fails to install on MacOS10.12.1 Xcode8.1

### ISSUE THREAD

**Issue by ipconfiger** [vapor/vapor#702]
~/workspace/swift_proj> sudo curl -sL toolbox.vapor.sh | bash
Password:
✅  Compatible
Downloading...
Compiling...
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/module.modulemap:116:11: error: header 'stdatomic.h' not found
                        header "stdatomic.h" // note: supplied by the compiler
                               ^
<unknown>:0: error: could not build Objective-C module 'Darwin'
error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain/usr/bin/swiftc --driver-mode=swift -I /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain/usr/lib/swift/pm -L /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain/usr/lib/swift/pm -lPackageDescription -target x86_64-apple-macosx10.10 /Users/liming/workspace/swift_proj/.vapor-toolbox-temporary/vapor-toolbox/Package.swift
Installing...
bash: line 22: .build/release/Executable: No such file or directory
Use vapor --help and vapor <command> --help to learn more.

**Comment by proyb6** [comment]
Look like you are still using an outdated compile?
"swift-DEVELOPMENT-SNAPSHOT-2016-03-01" and you could try with the Swift 3 stable release?

**Comment by ipconfiger** [comment]
I use swiftenv upgrade to 3.01 stable, seen to be resolved
