### ISSUE TITLE
Syntax error in 1 config file will fail silent and all configs will be nil

### ISSUE THREAD

**Issue by Casperhr** [vapor/vapor#703]
I discovered that if you have an syntax error in the json in just one config file.
All configs will be nil 

I suggest either failing hard

**Comment by zdenektopic** [comment]
yes its annoying, I couldnt figure out why my app crashes. It reports config file missing in console.
👍

**Comment by LoganWright** [comment]
We merged a fix w/ better logs when config file parsing fails 👍
