### ISSUE TITLE
Documentation -> Config

### ISSUE THREAD

**Issue by norricorp** [vapor/vapor#704]
🚀 Thanks for contributing!

# Bugs

If you find a bug, please submit a pull request with a failing test case displaying the bug or just create an issue with as much information as possible.

let customValue = app.config["server", "http", "custom-key"].string
should be
let customValue = app.config["servers", "http", "custom-key"]?.string

let name = app.config["keys", "test-names", 0].string
let mongoUrl = app.config["keys", "mongo", "url"].string
.string => ?.string

**Comment by tannernelson** [comment]
@norricorp thanks! Any chance you want to make a PR to the documentation with these changes?

**Comment by norricorp** [comment]
Hi Tanner I know I will feel dumb when you answer this but PR? (Public Relations?)

**Comment by tannernelson** [comment]
Pull Request! https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

:)

**Comment by guillaumemaiano** [comment]
Pull Request :)

**Comment by norricorp** [comment]
OK - try an do that in the next few days.

**Comment by Casperhr** [comment]
seems to be fixed, closing
