### ISSUE TITLE
Add support for GZIP

### ISSUE THREAD

**Issue by wildfiremedia** [vapor/vapor#705]
Closed.

**Comment by andreasley** [comment]
Compression is a good idea, but this needs some thinking about. Off the top of my head:

- Header `Accept-Encoding` needs to be parsed to determine if the client supports compression (and if so, which one)
- Ability to configure which content types should be compressed (makes sense for text-based stuff like XML, JSON, SVG etc.; not so much for JPEG or videos)
- Compressed static content should be cached
- Cached compressed static content should be recreated if the original file is modified

If you need a short-term solution, use nginx as a reverse proxy and let it do the compression with configuration like this:
```
gzip             on;
gzip_proxied     any;
gzip_types       text/css text/plain text/xml application/xml application/javascript application/x-javascript text/javascript application/json text/x-json;
gzip_vary        on;
gzip_disable     "msie6";
```

**Comment by proyb6** [comment]
I would suggest to compress text-based files to compile code before serving would safe lot of bandwidth and CPU processing.

**Comment by andreasley** [comment]
> compress text-based files to compile code

What do you mean by that? There's no such thing as compiled code for HTML, JavaScript, CSS, SVG etc.

However, integration with, for example, a LESS/SASS compiler or a JavaScript minifier could be considered.

**Comment by proyb6** [comment]
There is such thing as compile HTML code.

```
app.get("/") { request in
    return try app.view("welcome.html")
}
```

Compile HTML in binary:
```
drop.get("hello") { request in
    return "<h1>Hello, world!</h1>"
}
```

**Comment by andreasley** [comment]
@proyb6 There's no compilation happening in your example. If `welcome.html` contains the UTF8 string `<h1>Hello, world!</h1>`, the content returned is identical.

Compression would happen afterwards in both cases.

**Comment by wildfiremedia** [comment]
Already have GZIP in middleware
https://github.com/vapor/gzip-provider/blob/master/Sources/gzip-vapor/GzipMiddleware.swift
