### ISSUE TITLE
Wrong request.uri value in https requests

### ISSUE THREAD

**Issue by hikelee** [vapor/vapor#706]
The protocol part of request.uri is wrong when handling https requests.  Refer to the code below, when I use "https://localhost:8443/hello" to access the server, I expect get the same url in the response , but actually, "http://localhost:8443/hello" was printed out

import Vapor
import TLS
let drop = Droplet()
let config = try TLS.Config(
  mode: .server,
  certificates: .files(
    certificateFile: "cert.pem",
    privateKeyFile: "key.pem",
    signature: .selfSigned
  ),
  verifyHost: true,
  verifyCertificates: true
)
drop.get("/hello") { request in
  return "\\(request.uri)"
}
drop.run(servers: [
    "plaintext": ("0.0.0.0", 8080, .none),
    "secure": ("0.0.0.0", 8443, .tls(config)),
])

**Comment by LoganWright** [comment]
@hikelee if you visit 8080, it logs correctly, yes? If so, I think you've found a bug, let me think through it a bit.

**Comment by hikelee** [comment]
yes，8080 is correct

**Comment by LoganWright** [comment]
@hikelee I originally thought you were saying ports were being reported incorrectly, I misunderstood that you were trying to say the scheme is the one being mis-reported.

I don't have a solution yet, it's a small problem at the bottom, but there's a lot between us getting a solution to know when it's on a TLS port. For now, I found the line in question:

[here](https://github.com/vapor/engine/blob/master/Sources/HTTP/Models/Request/Request.swift#L81)

**Comment by LoganWright** [comment]
I believe this is resolved 👍
