### ISSUE TITLE
Bump to swift 3.0.1 when deploying to Heroku?

### ISSUE THREAD

**Issue by petrpavlik** [vapor/vapor#710]
I believe that your Heroku buildpack still uses swift 3.0, any plans to update it to swift 3.0.1? I'd probably take updating the buildpack.

**Comment by tannernelson** [comment]
Help updating it to 3.0.1 would be appreciated. :)

**Comment by petrpavlik** [comment]
@tannernelson I've just realized that there already is a pull request by @codegefluester https://github.com/vapor/heroku-buildpack/pull/2. I swapped the buildpack on Heroku with his fork to test it, and successfully compiled and deployed my app using Swift 3.0.1 http://pastebin.com/quZvEuTc.

**Comment by codegefluester** [comment]
So I run 3.0.1 locally without any issues so far and my Heroku instance also uses 3.0.1 with no issues so far. I'm actually not sure if it really fixes the issue I referenced in my PR

**Comment by tannernelson** [comment]
@petrpavlik thanks for the link. I've merged the pr there.
