### ISSUE TITLE
Guide to install on Fedora and other linux distros

### ISSUE THREAD

**Issue by KeizerDev** [vapor/vapor#711]
Hi, 
I was wondering if there is support for Fedora, linux and if yes, I would I set it up. It looks very promising to me and I really want to use it but I'm running Fedora. 

Thanks in advance!

**Comment by skreutzberger** [comment]
Maybe you can orient on the [guide for Ubuntu](https://medium.com/swiftybeaver-blog/deployment-of-a-vapor-app-to-aws-ec2-f577eaa6c38c#.jhxa14t0n).

**Comment by tannernelson** [comment]
Vapor will work anywhere Swift can compile and Foundation is available. Swift doesn't officially support Fedora yet but that doesn't mean it won't work. Follow the Ubuntu instructions and let us know.

**Comment by LoganWright** [comment]
Closing this for now since it's not an official swift supported operating system. If there's any success, please report here for others who might be searching.

Perhaps we should open up an experimental section for people deploying to systems other than ubuntu official.

**Comment by jtligon** [comment]
fedora 31 silverblue with swift-lang rpm package layered succeeded with this output:
```
eval "$(curl -sL check.vapor.sh)"
✅ Swift 4.1 or later is compatible with Vapor 3
✅ Swift 5.1 or later is compatible with Vapor 4
```
Which makes me believe it would work fine on vanilla Fedora with that rpm installed.

running inside a toolbox container on the same system failed with:
```
cat: /etc/lsb-release: No such file or directory
Only Ubuntu 14.04, 16.04, 16.10, 18.04 and 18.10 are supported.
You are running  () [Linux]
```
so inside a container, beware.
