### ISSUE TITLE
Some questtions about the documentation

### ISSUE THREAD

**Issue by lycaste** [vapor/vapor#712]
i read docs about the route ，when i want to build these code in xcode，xcode always  has some errors

```
 Ambiguous reference to member 'get(_:handler:)'
```

```
drop.get("v1", "users", ":userId", "posts", ":postId", "comments"， ":commentId") { request in
  let userId = try request.parameters.extract("userId") as Int
  let postId = try request.parameters.extract("postId") as Int
  let commentId = try request.parameters.extract("commentId") as Int

  return "You requested comment #\(commentId) for post #\(postId) for user #\(userId)"
}
```

but then i read the source code about the  typesaferouting,i see the **get** funcs can only recive three parameters like
```
/a/b/c 
or something else like these
```

is the doc outdated，or i write the error code？

**Comment by tannernelson** [comment]
That should be supported. Perhaps the compiler is getting confused somewhere else. 

Try doing `drop.get("v1/users/:userId...")`

That will do the same thing.
