### ISSUE TITLE
JSON parser fails on array parsing

### ISSUE THREAD

**Issue by fhensley** [vapor/vapor#713]
# Bugs

If you find a bug, please submit a pull request with a failing test case displaying the bug or just create an issue with as much information as possible.

-------------------------------------------------------------------------------

I think the following bug is a high priority bug

I created a json file containing the following information:

{
	"name": "Test",
	"users": [
		{
			"id": 1337,
			"email": "foo@gmail.com"
		}, 
		{
			"id": 42, 
			"email": "bar@gmail.com" 
		}, 
		{
			"id": 500, "email": "baz@gmail.com"
		},
	]
}

As you can see there is a dangling comma in the array. When running the following code:

drop.post("input") { request in
  do {
    guard let id = request.data["users", 1, "id"]?.string else {
      throw Abort.badRequest
    }
    return JSON([
      "second_user_id": Node(id)
      ])
  } catch let error {
    print("Error \(error)")
    throw Abort.badRequest
  }
}

an error is caught in the catch section, and a invalid character exception is thrown. This is wrong as this is a valid json file and should be parsed correctly.

The expected outcome should be:

{"second_user_id":"42"}

should be returned.

If you remove the dangling comma, the code executes as expected.

**Comment by hhanesand** [comment]
> this is a valid json file and should be parsed correctly

I don't think that is a valid json file, as all the linters I paste that json into spit it out as invalid json. I tried http://jsonlint.com/ and https://jsonformatter.curiousconcept.com/.

**Comment by fhensley** [comment]
Fair Point. It’s just strange that the same json file works fine with kitura using SwiftyJSON.

Kind Regards,

Francois Hensley - CEO
Prododgenous Services Pty. Ltd. <http://www.prododgenous.com/>

landline: +61 2 9188 7075
e-mail: francois.hensley@prododgenous.com <mailto:francois.hensley@prododgenous.com>

**Comment by sroebert** [comment]
SwiftyJSON uses Apple's `JSONSerialization`, maybe that one is more forgiving than Jay. However, the JSON is invalid, so you were lucky that it is working with SwiftyJSON.

**Comment by tannernelson** [comment]
Dangling commas are invalid JSON.
