### ISSUE TITLE
Xcode - no such module Vapor

### ISSUE THREAD

**Issue by shayneptorres** [vapor/vapor#714]
Hello, when I was trying to set up a small a vapor project I ran into an issue with the xcode project that gets created. I ran `vapor new dragons`, `cd dragons`, `vapor xcode`. When the xcode project opened up, I added a new file "Battles.swift" to the models folder, and edited the main.swift file to code in the image below. When I tried to build the app via xcode, I got this error "No such module 'Vapor'. "  However, I was still able to build and run the vapor project via the command line. Not quite sure what the problem is. It might just be my machine. Any help would be appreciated. Thanks

**Comment by shayneptorres** [comment]
<img width="759" alt="screen shot 2016-11-22 at 11 30 01 am" src="https://cloud.githubusercontent.com/assets/8507231/20538908/0a095f1a-b0a8-11e6-94a8-9dfabe28a88e.png">

**Comment by shayneptorres** [comment]
Also, any other file I try to import Vapor gives me the same bug
<img width="760" alt="screen shot 2016-11-22 at 11 37 54 am" src="https://cloud.githubusercontent.com/assets/8507231/20538978/49f73ce6-b0a8-11e6-9d53-cb551f04713c.png">

**Comment by makoni** [comment]
When you open your file (Battle.swift) in Xcode it should belong only to your app in File Inspector:

![2016-11-23 10 13 05](https://cloud.githubusercontent.com/assets/234015/20553409/89f818fc-b165-11e6-8c8d-a25bd11b49bb.png)

**Comment by e-jam** [comment]
@makoni This solved my compiler error. Can you please explain to me what was going on and why the file in question must only belong to the app?

**Comment by linqingmo** [comment]
@e-jam please have a look at Package.swift. App depends on Vapor.

**Comment by vzsg** [comment]
@e-jam the issue is caused by Xcode selecting the wrong Target automatically when you create a new source file. You either need to be careful, and do one of the following:
- select the correct target (typically YourAppName or App) in the new file dialog;
- fix the Target membership manually as described previously;
- or regenerate the Xcode project after creating a source file in the correct folder.

**Comment by RARUTO21** [comment]
Hi, I'm having the same error after generating the Xcode project with $vapor xcode 

The main.swift file is contained in Proyect/Sources/Run/ and the first line has an "import App" statement.

When I try to compile, it says 'No such module App', when it belongs only to Run in the File Inspector
If I only check the App option in the File Inspector, it says: 'Could not launch Run' and if I check both (Run & App) it says the same error: 'No such module App',

I just installed Vapor to play around and learn a few thing in vacations by watching the following tutorial: https://www.youtube.com/watch?v=62Tt4u7LNiY&t=776s but I can't reach minute 4:13 successfully.

<img width="1302" alt="captura de pantalla 2017-06-24 a las 23 03 10" src="https://user-images.githubusercontent.com/12564522/27513748-f9ff31ea-592f-11e7-903e-2c9068f4c5b6.png">

**Comment by MarcusReuber** [comment]
<img width="1512" alt="screen shot 2017-09-14 at 10 46 24" src="https://user-images.githubusercontent.com/17995647/30433333-959266be-993a-11e7-9883-01dd4e971092.png">

The imported "App" is a framework located in the /Dependencies folder, add "/Dependencies" to your "Framework Search Paths" at your project "Build Settings" and it should be fine after this or rebuilding your project.

**Comment by vzsg** [comment]
You are _not_ supposed to change search paths or other project settings with SPM, as a regeneration will clear them out ruthlessly. The Xcode project is an ephemeral sideproduct.

@RARUTO21 what is your Xcode version, Vapor dependency version, and when did you create your project from which template (if you just used the default, that's okay too.)

**Comment by nhatlee** [comment]
Hi all
I got the error `No such module`, And I think it have same root cause with this thread. So I posted here, please help me to fix:
<img width="1417" alt="screen shot 2017-09-23 at 9 27 01 am" src="https://user-images.githubusercontent.com/7148482/30769401-9fbada32-a041-11e7-994a-309d2e003a87.png">

**Comment by linqingmo** [comment]
@nhatlee Hi. Can you paste your Package.swift here?

**Comment by nhatlee** [comment]
@linqingmo : Sorry about this report, it's not vapor error, just my mistake. I forgot to add `postgresql-provider` to `Package.swift `. Sorry for stupid mistake, I am new with Vapor :)

**Comment by linqingmo** [comment]
@nhatlee :)

**Comment by shehrya** [comment]
<img width="849" alt="bildschirmfoto 2017-09-26 um 14 19 43" src="https://user-images.githubusercontent.com/26958985/30859918-c76e1068-a2c5-11e7-8917-6e7a3417d4eb.png">
Hello i have the same problem as @linqingmo , but I already added the Postgresql-provider to Package.swift .i am new at vapor,using Xcode 9, Swift 4,
i also regenerate the vapor xcode .
thanks 
<img width="891" alt="bildschirmfoto 2017-09-26 um 14 17 00" src="https://user-images.githubusercontent.com/26958985/30859903-b603a18a-a2c5-11e7-9f4d-098401699c6b.png">

**Comment by vzsg** [comment]
Did you also run `vapor update` (or `swift package update`) to actually pull in the new dependency? Just regenerating the Xcode project is not enough.

**Comment by shehrya** [comment]
wow, Thanks a lot, vapor update work for me @vzsg now new dependencies actually pulled.

**Comment by bidiko** [comment]
I create new vapor api project but i can import PostgreSQLProvider. I try swift package update, vapor update, changed .swift files target membership with app.

Vapor version 2.3.0
Xcode 9.0
Swift 4.0

Swift Package File
![screen shot 2017-11-01 at 16 19 53](https://user-images.githubusercontent.com/25009957/32276594-52a67418-bf18-11e7-9345-aa3c8142d822.png)

Error
![screen shot 2017-11-01 at 16 20 25](https://user-images.githubusercontent.com/25009957/32276608-62eacf36-bf18-11e7-816a-36c38a0238f5.png)

After vapor update, swift package update,vapor xcode commands I can't see any new Dependencies folder. (like PostgresSqlProvider)
![screen shot 2017-11-01 at 16 22 48](https://user-images.githubusercontent.com/25009957/32276743-bd4767be-bf18-11e7-9a31-824e42f05f74.png)

**Comment by vzsg** [comment]
@bidiko You missed a required step for Swift 4: you must also list `"PostgreSQLProvider"` as a dependency of the App _target_. (Just like how "Vapor" and "FluentProvider" are added on your screenshot.)

**Comment by bidiko** [comment]
@vzsg Thanks for helping. I add new target and problem solved.

Swift Package File
![swiftpostgresqlprovider](https://user-images.githubusercontent.com/25009957/32277951-c9c3f4fe-bf1c-11e7-9955-7f3fe7ccd8bd.png)

**Comment by bupojung** [comment]
Have the same issue with @RARUTO21 after create Hello Project and run the run scheme.
 it says 'No such module App' in the main.swift file

Vapor Toolbox: 2.0.4
Vapor Framework: 3.0.1
swift: 4.1
xcode: 9.3

**Comment by 0xTim** [comment]
@bupojung have you tried building the project? Xcode can get confused if the project has never been built before

**Comment by bupojung** [comment]
I fixed the error by ran 'vapor upgrade' and regenerate with 'vapor xcode'.

**Comment by kuskovrodion** [comment]
@vzsg Hi! Could u help me please with this one? I've download mysql 5.7.22 and install cmysql. Also, I run vapor update/clean/xcode and there is an
<img width="1680" alt="screen shot 2018-07-16 at 23 23 50" src="https://user-images.githubusercontent.com/27081983/42781634-576a5ab2-894f-11e8-9a67-fb795c75d31e.png">
 error ...
