### ISSUE TITLE
Can't Install MySql

### ISSUE THREAD

**Issue by J4awesome** [vapor/vapor#715]
I installed my sql but when I run `swift build` this is the error log.

`Linking ./.build/debug/App
ld: library not found for -lmysqlclient for architecture x86_64
<unknown>:0: error: link command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
error: exit(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/JJ/Desktop/Swift\ Projects/ArtServer/ArtServer/.build/debug.yaml
`

**Comment by tannernelson** [comment]
Use `vapor build` instead. It will take care of linking MySQL.

If you want to use `swift build`, check out the instructions [here](https://github.com/vapor/mysql) for linking.
