### ISSUE TITLE
makeNode compile times doesn't scale

### ISSUE THREAD

**Issue by kdawgwilk** [vapor/vapor#716]
The following function does not scale at all when it comes to compile times:
```
/**
     Serializer for Fluent
     */
    override func makeNode(context: Context) throws -> Node {
        return try Node(node: [
            "id": id,
            "created_on": createdOn,

            "username": username,
            "password": password,

            "access_token": accessToken,
            "api_key_id": apiKeyID,
            "api_key_secret": apiKeySecret,

            "digits_id": digitsID,
            "phone_number": phoneNumber,
            
            "first_name": firstName,
            "last_name": lastName,
            "email": email,
            "image_url": imageURL,
        ])
    }
```
this took ~120 seconds to compile this single function (output from compiler flags I found here: http://irace.me/swift-profiling)
```
118124.3ms	Sources/App/Models/User.swift:66:19	override final func makeNode(context: Context) throws -> Node
```

**Comment by yuriferretti** [comment]
I think this is a swift compiler bug, not a vapor issue. You can try to explicitly type your JSON as [String : AnyObject] and check if compilation time is improved

**Comment by hansstolz** [comment]
I have the same issues. My code does not compile at all. I have 4 more fields in the Node argument. I tried to give them an explicit type as mentioned above. But this does not help.
Is there another work around?
I really love swift, but  I´m tired of the poor tools from Apple.

**Comment by gomfucius** [comment]
Making the variables an optional was a workaround for me.

**Comment by hansstolz** [comment]
Thank you. I just found another solution:

var node=[String:Any]()
        
        node["id"]=id
        node["title"]=title
        node["title_en"]=title_en
        node["subtitle"]=subtitle
        node["subtitle_en"]=subtitle_en
        node["short_description"]=short_description
        node["short_description_en"]=short_description_en
        node["img_url"]=img_url
......

return try Node(node: node as! NodeRepresentable)

**Comment by kdawgwilk** [comment]
I realize that this issue is mostly a Swift compiler issue but I figured that maybe Vapor could find a workaround the compiler issue for the time being.  I have seen a few workarounds now and the issue is now documented where others can easily find it.

**Comment by Casperhr** [comment]
Agree there could be a section in the doc about it. Feel free to do a PR with some of the methods posted in here

https://github.com/vapor/documentation

**Comment by MartinW** [comment]
@hansstolz Your approach worked for me to improve compile times but did also cause a run time crash on the affected model. I am using your formatting for an initial compile, then switching to the original formatting for running the app. This clearly isn't workable ongoing. 

@kdawgwilk @Casperhr I'm not sure that this is fixed or clearly documented yet. Consider reopening.

**Comment by eltonf** [comment]
@hansstolz Thanks for the suggestion!!! My project had become uncompilable after making a model with 13 properties. I was worried I would have to completely abandon Vapor.

@MartinW I assume you had a crash because of an optional NodeRepresentable value. Try initializing your node var like this: 

`var node = [String : NodeRepresentable?]()`

**Comment by MartinW** [comment]
@eltonf Thanks for the suggestion but crash still occurs. Amended my comment above - crash is in Fluent PostgreSQLSerializer.

**Comment by kdawgwilk** [comment]
@MartinW Can you describe the crash in the above-linked issue?

**Comment by MartinW** [comment]
@kdawgwilk Done. Thanks.
