### ISSUE TITLE
Vapor Installation fails with XCode Version 8.1 (8B62), with swift 3.0.1

### ISSUE THREAD

**Issue by ankitthakur** [vapor/vapor#718]
:~ ankitthakur$ _swiftenv versions_
  3.0.1
  2.2
:~ ankitthakur$ _swiftenv version_
3.0 (set by /Users/ankitthakur/.swiftenv/version)
:~ ankitthakur$ _swiftenv version 3.0.1_
3.0 (set by /Users/ankitthakur/.swiftenv/version)
:~ ankitthakur$ _**curl -sL check.vapor.sh | bash**_
swiftenv: version `3.0' (set by /Users/ankitthakur/.swiftenv/version) is not installed
❌  Incompatible
Reason: Swift 3.0 is required.

'swift --version' output:
no such command: swift

Output does not contain '3.0'.

📖  Visit our docs for step-by-step instructions on installing Swift correctly.
http://docs.vapor.codes

👋  or Join our Slack and we'll help you get setup.
http://vapor.team

**Comment by makoni** [comment]
Are you sure that you have Command Line Tools installed and selected 8.1 in Xcode Settings?

![2016-11-25 13 51 40](https://cloud.githubusercontent.com/assets/234015/20622961/532aa422-b316-11e6-8d74-5cea815a0c5a.png)

That's what it should look like when you execute 'swift --version' command in terminal:

$ swift --version
Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9

**Comment by ankitthakur** [comment]
This is working fine now.

**Comment by JohnEstropia** [comment]
Just to bump this issue, Vapor still fails on Xcode 8.2 (Swift 3.0.1)
(Above was probably resolved by installing Xcode 8.1)
