### ISSUE TITLE
WebSockets - error immediately after connect in 1.2

### ISSUE THREAD

**Issue by zdenektopic** [vapor/vapor#738]
When I use example code from https://vapor.github.io/documentation/websockets/droplet.html and try to connect to server with Javascript or terminal client I immediately get the socket was closed and error.

> closed
> Server error: respond(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource temporarily unavailable") [readFailed]))

The example code works fine on Vapor 1.1

**Comment by jazzmac93** [comment]
Getting the same error after I updated vapor to 1.2. I was testing the sample chat app provided here:
https://github.com/vapor/chat-example

The web socket connection seems to be closed immediately after it is established. On debugging, the call to close the connection appears to have come from the call to _completeCloseHandshake_ in the catch block of the following function (in Model/WebSocket.swift). 

`private func loop(with parser: FrameParser) throws {
        while state != .closed {
            // not a part of while logic, we need to separately acknowledge
            // that TCP closed w/o handshake
            if stream.closed {
                try completeCloseHandshake(statusCode: nil, reason: nil, cleanly: false)
                break
            }

            do {
                let frame = try parser.acceptFrame()
                try received(frame)
            } catch {
                // TODO: Throw for application to catch
                // or pass logger
                // Log.error("WebSocket Failed w/ error: \(error)")
                try completeCloseHandshake(statusCode: nil, reason: nil, cleanly: false)
            }
        }
    }`

Running OS X 10.11.5

**Comment by mjmsmith** [comment]
For what it's worth, I'm still on 1.1.3 because I get this error intermittently with all subsequent versions. I'm not using web sockets, just the usual request/response, and the responses are typically very small (JSON API results, not full HTML web pages).

**Comment by zdenektopic** [comment]
i had to roll back too. 1.2 and above is unusable for me.

**Comment by tannernelson** [comment]
I can confirm this is still happening with:

```
Socks-1.2.2
Engine-1.3.4
Vapor-1.3.0
```

**Comment by tannernelson** [comment]
Potential fix here: https://github.com/vapor/engine/pull/84

**Comment by tannernelson** [comment]
https://github.com/vapor/vapor/releases/tag/1.3.1
