### ISSUE TITLE
Heroku buildpack compile error: unresolved identifier 'DispatchQueue'

### ISSUE THREAD

**Issue by panchenks** [vapor/vapor#742]
([heroku-buildpack](https://github.com/vapor/heroku-buildpack) does not have Issues enabled, so submitting bug here)

Code containing `DispatchQueue` fails to build when submitted to Heroku:
```
...
Compile Swift Module 'App' (5 sources)
/tmp/build_334217ac8fdf4e7efb64aad4b9865a5c/Sources/App/Controllers/AppController.swift:18:13: error: use of unresolved identifier 'DispatchQueue'
            DispatchQueue.global().async { [weak self] in
            ^~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
swift-build: error: exit(1): /app/.swiftenv/versions/3.0/usr/bin/swift-build-tool -f /tmp/build_334217ac8fdf4e7efb64aad4b9865a5c/.build/release.yaml
Fetching Dependencies [Done]
...
```

Same code builds and runs fine on macOS 10.12.1, both in Xcode and via command line. `import Foundation` is declared in the file, and other `Foundation` classes such as `Date` build and run as expected as well.

**Comment by andreasley** [comment]
Not really a Vapor problem. :)
You need to `import Dispatch` when using GCD under Linux.

**Comment by panchenks** [comment]
Awesome! Thanks so much!
