### ISSUE TITLE
Plugin for AppCode

### ISSUE THREAD

**Issue by Codenator81** [vapor/vapor#743]
# Feature, Enhancement, or Optimization

# Add support for AppCode

## Introduction

AppCode is better than xcode for html,css and js coding.
Will be great to have plugin which support leaf syntax at starting point.

**Comment by LoganWright** [comment]
@Codenator81 unfortunately, we're unable to prioritize this at the moment and are reliant on a 3rd party solution until we can get some more resources.

Until then, there is plugin support for visual studio and atom provided by the community. There was also work started on AppCode at one point, but there were limitations that were being addressed with the AppCode team. We'll try and publicize when and if we get this support.

Thanks for your support of Vapor and happy coding 👍

**Comment by kubabialy** [comment]
Any updates on the topic @LoganWright ?
