### ISSUE TITLE
Files are not coming through in 1.2

### ISSUE THREAD

**Issue by rafiki270** [vapor/vapor#744]
Multipart is empty when I send a file from a form:
```
<html>
    <body>
        <form action="http://localhost:8080/v1/apps?token=AFE2BA61-C2B9-4091-822E-425F406F6FBA" method="post" enctype="multipart/form-data">
            <p>
                <label>File</label>
                <input type="file" name="file" />
            </p>
            <p>
                <button type="submit">Send</button>
            </p>
        </form>
    </body>
</html>
```
Call get's through, I can see a message:
```
Server error: respond(Transport.StreamError.receive("There was a problem while receiving data.", Socket failed with code 35 ("Resource temporarily unavailable") [readFailed]))
```
And the ```request.multipart``` part of the request is empty

**Comment by rafiki270** [comment]
seems very related to https://github.com/vapor/vapor/issues/738

**Comment by andreasley** [comment]
Under what OS is this happening?
Your example works fine for me (OS X 10.11).

**Comment by rafiki270** [comment]
macOS 10.12

**Comment by rafiki270** [comment]
after downgrading to Vapor 1.1 I am able to get the file content, same applies to #738

**Comment by andreasley** [comment]
Very strange. I've set up a test system with macOS 10.12 and your example works there, too. 
Are you using a proxy or are you sending the POST request directly to a Vapor instance?
Is the file you're sending very large?

**Comment by wallstead** [comment]
I'm having the exact server error with a similarly simple file upload situation. I am using no proxy, just direct POST requests. This is with images in my case and it happens for any image size.

**Comment by andreasley** [comment]
After some more testing:

- Works fine in Safari
- Works fine in Chromium
- **Doesn't** work properly in Firefox; looks like the connection is closed halfway through the request

What browsers/clients were you using?

**Comment by rafiki270** [comment]
Safari, I'll try to get you a full Charles request tomorrow.

**Comment by rafiki270** [comment]
Also, I wasn't sure about the filesize either so I tried different sizes same result

**Comment by andreasley** [comment]
Today, I suddenly did receive errors when using Safari, too. After clearing all caches in Safari, the problem went away and now I'm unable to reproduce it?!

This is the code I'm using to create the `Droplet`:

```swift
import Vapor
import Foundation

let drop = Droplet(environment: .production)

drop.post("upload") { request in
    if let multipartFile = request.multipart?.first?.value.file {
        return "Peer: \(request.peerAddress)\nName: \(multipartFile.name)\nSize: \(multipartFile.data.count) Bytes"
    }

    return "No multipart files received"
}

drop.run()
```

**Comment by rafiki270** [comment]
Have you tried to downgrade and than upgrade again while testing the calls in both instances?

**Comment by andreasley** [comment]
@rafiki270 Not sure what you mean. Could you give my code a go and see if that works in your environment?

**Comment by sroebert** [comment]
For me this also happened when connecting from Android and performing a POST request.

**Comment by tannernelson** [comment]
https://github.com/vapor/vapor/releases/tag/1.3.1
