### ISSUE TITLE
Fork in CodePen feature is broken

### ISSUE THREAD

**Issue by frederik-labbe** [vapor/vapor#745]
**Issue:**
When forking an example in CodePen, the markup lacks the `coveo-styleguide` class so the css isn't working as expected. The result is a broken UI. Ex:  Clicking on "Fork in CodePen" there: http://coveo.github.io/vapor/controls/#dropdown

**Potential fix:**
Solution would probably be to wrap the example inside a `.coveo-styleguide` container so the css rules can be targeted correctly.

**Comment by wallstead** [comment]
I think you're looking for https://github.com/coveo/vapor, not https://github.com/vapor/vapor

**Comment by frederik-labbe** [comment]
Yes, indeed. Sorry.
