### ISSUE TITLE
Add regex support for URIs

### ISSUE THREAD

**Issue by CraigRhodes** [vapor/vapor#747]

**Comment by LoganWright** [comment]
@CraigRhodes sorry about delayed reply, would you mind elaborating this a bit for us? (Even an example or something would be great)

I'm going to close this for now so we know which ones to check. Go ahead and reopen on update and we can start a discussion 👍

**Comment by CraigRhodes** [comment]
For examples, Django and other Web App frameworks allow you to specify regexes that match specific URIs. Perhaps it would be something like:

```
let app = Droplet()
app.get("foo", Regex("[a-z]+"), Regex("[A-Z][0-9]")) { request in
     // code here
}
app.run()
```
which would match URIs such as /foo/bar/C3
