### ISSUE TITLE
Inconsistencies when request data is an array

### ISSUE THREAD

**Issue by fwgreen** [vapor/vapor#750]
When reading the values of checkbox inputs using`request.data["boxes"]?.array` , there are three possible return types:
```Swift
nil //if nothing was selected

Optional(["1"]) //if, in this case, a single checkbox with a value of 1, was selected

Optional([Node.Node.string("1"), Node.Node.string("2")]) //if multiple checkboxes were selected
```
The first and third cases surprised me, as my expectations were:
```Swift
Optional([]) //in the case of no selection

Optional(["1"]) //in the case of one selection

Optional(["1", "2"]) //in the case of multiple selections
```

**Comment by LoganWright** [comment]
@fwgreen I think this is more or less how the data is received by us from the front end, I don't think there's much we can do there unfortunately.

Would you mind attaching the request you're using and reopening when you get a chance 👍
