### ISSUE TITLE
Errors not working after 1.2 upgrade

### ISSUE THREAD

**Issue by Casperhr** [vapor/vapor#751]
Getting: Server error: respond(Transport.StreamError.send("There was a problem while sending data.", Socket failed with code 0 ("Undefined error: 0") [sendFailedToSendAllBytes]))

on all the default error screens, and browser is hanging

After upgrading from 1.1 to 1.2

any ideas?

changing back to 1.1 fixes the error, so it’s 100% related to that

**Comment by andreasley** [comment]
Does this happen with every response or just ones over 50kb or so?

**Comment by Casperhr** [comment]
It seems to be something with size. I think @tannernelson is hotfixing it as we speak

**Comment by tannernelson** [comment]
Related to https://github.com/vapor/socks/pull/97.

**Comment by tannernelson** [comment]
https://github.com/vapor/vapor/releases/tag/1.3.1
