### ISSUE TITLE
Could not open Xcode project.

### ISSUE THREAD

**Issue by josercc** [vapor/vapor#756]
➜  SiJiaChe vapor xcode
Fetching Dependencies [Done]
Generating Xcode Project [Done]
Select the `App` scheme to run.
Open Xcode project?
y/n>y
Opening Xcode project...
Error: Could not open Xcode project.

**Comment by LoganWright** [comment]
Is everything latest, latest Swift/Vapor/Xcode? If so, then try completely deleting your xcode project, close Xcode completely, restart computer, then run `rm -rf *.xcodeproj` before trying `vapor xcode` again.

If this doesn't resolve it, join us in slack or comment on here. It's usually the above stuff that fixes this though.

**Comment by josercc** [comment]
@LoganWright 
I think probably I have find the problem
1.When I open a terminal
2.Execute the commands below directly
`Vapor new demo`
3. When performing **Vapor xcode command** can generate and open project
4. But when I create specified path is not ok
`Vapor new /Users/zhangxing/Desktop/demo`
5. My problems will occur
