### ISSUE TITLE
Caching of compiled dependencies on Linux

### ISSUE THREAD

**Issue by swizzlr** [vapor/vapor#757]
When building a Vapor project under Linux (Ubuntu 16 on Docker) I've noticed that my dependencies aren't caching fully – the source code is cached, but it seems to recompile everything. Vapor core, for instance, doesn't exhibit this behaviour – I suspect it may be something to do with CLibreSSL, since its compilation seems to occur out of order. Has anyone else encountered this? I'd very much like to reduce my build cycle times!

**Comment by LoganWright** [comment]
@swizzlr we saw that a loooonnngggg time ago on one of the first 3.0 releases w/ one of the earliest vapor releases. Swift changed the way they compile c libraries, so it had to go fresh each time. (osx too, but not in Xcode). Update your Swift and Vapor to latest.

**Comment by swizzlr** [comment]
Yep, that's it exactly. Problem solved by updating to 3.0.2 (problem occurred on 3.0.0, unsure about 3.0.1).

Thanks for the help!
