### ISSUE TITLE
Query values with = or + are not parsed correctly

### ISSUE THREAD

**Issue by sroebert** [vapor/vapor#758]
Currently, as Engine already decodes URI characters when parsing the requested URI, there is a bug when trying to parse the query values using `formURLEncoded`. If you have a plus sign or an equals sign in the value of the query, it already gets decoded before parsing the query string. This results in the query string not being parsed correctly.

I was looking in how to fix this. It is not very difficult, but it requires an update to Core, Vapor and Engine, which is quite annoying. Any help would be appreciated.

**Comment by dolphinsue319** [comment]
I'd like to help, how we start? From your repo?

**Comment by sroebert** [comment]
You can checkout an example project and simply call an endpoint with a query including a value with `%2B` in it (which is a plus).

**Comment by LoganWright** [comment]
@sroebert just to make sure I understand, what you really want is to be able to still have access to the unencoded version of the query string?

**Comment by sroebert** [comment]
No, it is a bug. If I use a `+` inside the value of a query string, using `%2B` it is replaced with a space, instead of getting a value with a plus in the string.

This is happening because the query string is decoded before being split into key-value pairs and plus and equal signs are then also already decoded. The key value pairs should be decoded separately.

I wanted to make a pull request for this. But to fix it I have to make changes in several repositories.

**Comment by vzsg** [comment]
Are you sure it's not your client causing this behavior?
The template project plus the following request works without a hitch:

```
$ curl -X POST -d "fizz=bu%3Dzz%2Bzz&aaa=bb%2Bccc%26dd" localhost:8080
```

Result:

```
(lldb) e req.formURLEncoded
(Node.Node?) $R2 = object {
  object = 2 key/value pairs {
    [0] = {
      key = "fizz"
      value = string (string = "bu=zz+zz")
    }
    [1] = {
      key = "aaa"
      value = string (string = "bb+ccc&dd")
    }
  }
}
```

**Comment by sroebert** [comment]
It is not about form data, it is about query data in the url.

**Comment by vzsg** [comment]
I see. This sentence really confused me: "there is a bug when trying to parse the query values using `formURLEncoded`"...

Now the bug is clear, the following request:

```
curl -X POST -d "" localhost:8080?fizz=bu%3Dzz%2Bzz\&aaa=bb%2Bccc%26dd
```

returns the following `query` node:

```
(lldb) e req.query
(Node.Node?) $R1 = object {
  object = 1 key/value pair {
    [0] = {
      key = "aaa"
      value = string (string = "bb ccc")
    }
  }
}
```

Even though it should be the same as above.

**Comment by vzsg** [comment]
This line is the culprit: https://github.com/vapor/engine/blob/master/Sources/URI/Parser/Parser.swift#L67

**Comment by sroebert** [comment]
@vzsg Exactly, probably that one should simply leave the key value parts encoded. The thing is that then the code for parsing the query has to decode each key value pair separately. So the fix will have to be done over multiple repositories.

**Comment by vzsg** [comment]
I don't see why the change would have to be propagated through anywhere. The form-encoded parsing done for converting the string to a Node already handles everything (I could think of).

**Comment by JohnEstropia** [comment]
Any updates on this? We are encountering problems where email addresses with `+` in them are turning into spaces whenever we send through `get()` queries.

**Comment by LoganWright** [comment]
@vzsg @sroebert 

Ok, parsing through this, the line you posted @vzsg does seem to be the culprit, but that was added originally by request, and is now expected behavior. Here's my proposed solution.

`uri.query`  will function as it currently does, pre-parsing the query string for usage. 

We'll add to the URI struct a `rawQuery: String` parameter that will not be percent decoded so that things like formUrlEncoded can work with the unprocessed string.

Would this be an acceptable solution?


@JohnEstropia just to confirm, this is emails w/ + when passed through a query param and not some other way?

**Comment by vzsg** [comment]
@LoganWright I think that's a workable solution. Especially if Request.query is updated to use the raw version in the same tag.

**Comment by LoganWright** [comment]
@vzsg that's the plan, here's [part 1](https://github.com/vapor/engine/pull/96)

**Comment by LoganWright** [comment]
@vzsg @sroebert @JohnEstropia @dolphinsue319 merged and ready to go. If you're already on 1.4 or higher, just rebuild 👍
