### ISSUE TITLE
"multipart/form-data" bug

### ISSUE THREAD

**Issue by kateinoigakukun** [vapor/vapor#760]
# Bugs
When I try to post file and text with `enctype="multipart/form-data"`, Vapor displays this.
`Uncaught Error: JayError.parseStringFromCharsFailed`

I think it is caused by Jay's parse flow. 
How do I post image and text at same time.

**Comment by tannernelson** [comment]
@kateinoigakukun could you include the data you were attempting to send so I can recreate the bug?

**Comment by Casperhr** [comment]
Grab a form field: req.data["field"]
Grab a file: req.multipart?["fileToUpload"]

Hope that helps
