### ISSUE TITLE
vapor xcode generates project that shows external packages in sources section

### ISSUE THREAD

**Issue by SebastianBoldt** [vapor/vapor#762]
If I use _**xcode vapor**_ to create the xcodeproject, the structure seems to be a little bit off.
I would not expect that all external packages  show up in the sources section.
All the Tutorials I have seen just showing the App Folder, so I think something is wrong here. 
Is this behavior on purpose?

I am currently using Xcode 8.2 and Vapor 1.0.3

![bildschirmfoto 2016-12-18 um 16 55 26](https://cloud.githubusercontent.com/assets/2922440/21294684/cccace4a-c542-11e6-95ae-baff092299e4.png)

**Comment by rafiki270** [comment]
This I believe is a functionality of the Swift package manager and I think I overheard @LoganWright this is marked as a bug and should be fixed (hopefully soon)

**Comment by tannernelson** [comment]
This bug has been reported to the Swift Package Manager team here: https://bugs.swift.org/browse/SR-3327?jql=text%20~%20%22packages%20xcode%22
