### ISSUE TITLE
Getting "noDatabase" error when retrieving database content from command

### ISSUE THREAD

**Issue by rasmusebbesen** [vapor/vapor#767]
When interacting with mysql in a command, Vapor exits with an Error saying "noDatabase"

The error can be reproduced from this [git repo](https://github.com/nodes-vapor/sandbox) by runnig command `admin-panel:seeder`

Database interactions through HTTP requests works fine

edit:

Worth mentioning is that querying the database with

`drop.database.driver.raw("SELECT * FROM ...")` 

from a command also works fine, so the issue is when querying through the model.

**Comment by Casperhr** [comment]
@rasmusebbesen 

I figured out a small fix until it gets implemented correct

You can apply the db to the model manually

MyModel.database = drop.database

**Comment by rasmusebbesen** [comment]
Brilliant! thanks

**Comment by Skyback** [comment]
@tannernelson How can we execute a command with prepare?

Currently the above suggestion works, but it would be nice to avoid that kind of logic on the command itself.

**Comment by BrettRToomey** [comment]
I believe this is fixed in Vapor 2.0. Feel free to reopen if that's not the case.
