### ISSUE TITLE
Docker: Vapor application hangs without a pseudoTTY

### ISSUE THREAD

**Issue by vzsg** [vapor/vapor#775]
When running a Vapor-based application on Docker, I found that unless the container is created with the `-t` argument (allocate a pseudo-TTY), the application hangs during initialization, causing even the Docker client to freeze hard until the container is manually stopped.

To reproduce, I pushed an image of the starting template to Docker Hub.

The following command demonstrates the problem:

```
$ docker run --rm -p 8080:8080 vzsg/vapor-helloworld:latest
(... no output, ^C doesn't work, port 8080 is not bound ...)
```

While the following command works:

```
$ docker run --rm -p 8080:8080 -t vzsg/vapor-helloworld:latest
No command supplied, defaulting to serve...
No preparations.
Server 'default' starting at 0.0.0.0:8080
```

---

One would expect the application to work "headlessly" without the `-t` option, as neither regular Swift executables which use `print`, nor the pretty printing from vapor/console show this hanging symptom. (I played around with them inside containers.)

I could reproduce the issue with Docker for Mac (using `swiftdocker/swift:3.0.2` as base image) and on ARM Linux (using `vzsg/arm-swift:latest`) as well.

---

An alternative to researching the cause would be adding a warning in the documentation that containers need the `-t` flag to work. (Debugging a frozen container is not a nice user experience.)

**Comment by swizzlr** [comment]
As a temporary measure I wonder if using `isatty()` (http://man7.org/linux/man-pages/man3/isatty.3.html) against stdout would accurately determine whether a TTY is attached to stdout, and if so, we could add a quick couple of lines of code to check and warn?

**Comment by LoganWright** [comment]
@vzsg is this still a thign?

**Comment by vzsg** [comment]
Good question. Let me test again.

**Comment by tanner0101** [comment]
Please re-open if you're still seeing the issue @vzsg

**Comment by vzsg** [comment]
I tested it now, the issue seems to be gone. Yay!
