### ISSUE TITLE
A first-class backend for sending transactional emails

### ISSUE THREAD

**Issue by bygri** [vapor/vapor#781]
# MailClient

* Author(s): [bygri](https://github.com/bygri)

## Introduction

The ability to send transactional email is a key requirement for many web applications: sign up, password reset, onboarding etc.

But SMTP is an outdated protocol (Wright L, 2016). Mailing platforms such as Sendgrid and Mailgun implement their own APIs to allow the transmission of transactional email with greater reliability and more features.

I propose the following:

1. creating a `MailClient` protocol allowing mail platform clients to be used interchangeably, whether SMTP or not;
2. using the Provider system to implement these clients in a simple, swappable and configurable manner; and
3. promoting email to the same level of treatment as databases in Vapor, e.g. universal access to `drop.mailer`, so that other Providers can make use of email without having to be aware of the platform used.

## Motivation

In my own project, when sending moderate amounts of transactional mail, I found I could not rely on `SMTPClient` due to a series of intermittent and unpredictable errors and instead had to create a wrapper for Sendgrid's JSON API.

[@loganwright](https://github.com/loganwright) encouraged me to contribute that wrapper to Vapor. In further discussion the scope and utility of the work was expanded, and I think this proposal brings with it a number of extra benefits.

## Proposed solution

Vapor currently has an `SMTPClient` to handle the sending of email. I propose creating a new protocol, based on the public interface of `SMTPClient`, and providing implementations of `SendgridClient`, `MailgunClient` and `SparkPostClient` that allow them to be used in place of `SMTPClient` with minimal friction. This protocol would be very limited in scope, covering simple mail sending only.

At the same time, these mail providers have special features such as click tracking, address lists or stored templates with variable substitutions. Each client would implement these features in their own fashion, but they would not be part of the mail client protocol.

I propose to store a reference to the mail client on the Droplet so that third party providers can implement useful features like login and password reset forms knowing that the droplet will be able to send mail (with correct configuration). The end user is free to select their client.

## Code snippets

Using the built-in SMTP client. Configuration provided in `Config/smtp.json`.

```swift
try drop.addProvider(SMTPClient.Provider.self)

let email = Email(...)
try drop.mailer.send(email)
```

Using the Sendgrid client which sends using JSON. Configuration provided in `Config/sendgrid.json`.

```swift
try drop.addProvider(SendgridClient.Provider.self)

let email = Email(...)
try drop.mailer.send(email)
```

Using advanced features of Sendgrid.

```swift
try drop.addProvider(SendgridClient.Provider.self)

guard let sendgrid = drop.mailer as? SendgridClient else { exit(1) }
sendgrid.send(template: "welcome", variables: ["firstName": "Engelbert", "lastName": "Humperdinck"])
```

## Impact

The new mail client protocol will not be able to exactly replicate `SMTPClient`'s public interface. For example the `send()` method has a `credentials` argument which may not be required for all mailing implementations (sendmail?).

I do not foresee any problems implementing this proposal as described while maintaining the current public interface to `SMTPClient` to avoid any disruptions to existing applications. However, I would strongly suggest deprecating and then removing these properties and methods in a future release of Vapor.

The rest of Vapor's current email implementation, such as `Email`, `EmailAddress`, `EmailAttachment`, `EmailBody` should be able to remain unchanged.

## Alternatives considered

A perfectly valid alternative is to do nothing. Contributors can create their own Swift clients to mailing provider APIs and these can be integrated into Vapor, or indeed any Swift application.

I feel this proposal is superior because it allows developers of Vapor add-ons to implement the sending of emails without locking the end-user into any specific mailing backend. Much like Fluent lets a developer create models without regard for the storage mechanism, a Provider will be able to call `drop.mailer.send()` and be reasonably certain of success. This key feature will help the Vapor ecosystem grow.

**Comment by Casperhr** [comment]
@bygri Agree this is needed down the line. The API for mailgun is also 10x faster than the SMTP client

Nodes can contribute with the mailgun client if you create the protocol / pattern for sendgrid, we follow up

**Comment by bygri** [comment]
Cheers @Casperhr. I'll make the protocols and make reference implementations for Sendgrid and SMTP. SparkPost as well if I get a chance. I don't have a Mailgun account to test with so thank you for offering to implement it.

I might leave this open another week or so for suggestions and then get started on an implementation.

**Comment by steffendsommer** [comment]
What's the status on this @bygri? I'm really looking forward to use this.

**Comment by bygri** [comment]
I have no impediments to starting now. I have a four hour train ride ahead of me tonight, so happy to work on it right away. If you have any specific goals in mind, or pre-existing implementations in other frameworks you like, I would appreciate links or comments.

**Comment by natebird** [comment]
I am willing to contribute a Mandrill (MailChimp) client. I also know some of the folks at MailChimp. I'll reach out and see if they are interested in developing an official client.

**Comment by steffendsommer** [comment]
Sounds great @bygri. The specific need I have right now is to use it in a reset-password-feature in a package where the email-sending part should be SMTP-agnostic (or any other client for that matter). So, being able to inject a mail instance conforming to some mail protocol into a package basically. But no, I don't have any implementations nor frameworks in mind.

**Comment by bygri** [comment]
I have completed the very basic protocol and two development-only implementations of the mail client.

My inspirations were Laravel, Django, Vapor's Client and Fluent. I have worked hard to have as little impact on existing code as possible. To this end, I have spent two days adapting the existing SMTP client to the protocol, and though I haven't yet been successful there is no reason not to proceed with other implementations.

## Guidelines for use

We use the Provider paradigm for installation and configuration of the mail backend, and, inspired by Vapor's existing Client we keep only a reference to the Type and instantiate as needed.

The end-user syntax therefore looks like this:
```swift
let drop = Droplet()
try drop.addProvider(SMTPClient.Provider.self)
let email = Email(...)
// Simple sending
try drop.mailer.send(email)
// Keep a reference for advanced usage
let smtp = try drop.mailer.make()
try smtp.send(email)
```

Implementations of the mail client protocol require only a few things:

- a Provider, which will load needed configuration;
- an empty initialiser;
- a single `send(_ email: Email)` method.

It is expected that advanced features, such as sending templated emails, or requesting open/click tracking, will be implemented as overloads to the `send` function by the individual libraries.

I would suggest that configuration loaded by the Provider be stored in static vars on either the MailClient implementation or the Provider itself. See the `SMTPClient` in the development branch of the repo below for an example.

## Current status

The protocol is at [bygri/mail](https://github.com/bygri/mail). It uses models taken directly from Engine/SMTP. It builds and tests correctly as it stands. Because Vapor's Droplet doesn't currently have a `mailer` property, the Providers' `boot(_:)` methods are commented out.

## Implementors

The following have offered to build implementations, and I gratefully accept:

| Who | What |
|-|-|
| @Casperhr | Mailgun |
| @natebird | Mandrill |
| @akeskiner | Sendgrid |

## Future plans

Once I have the SMTP client building properly, the following needs to be done:

- A new version of Engine must be released, with the SMTP target removed;
- The Mail package must be released, including the SMTPClient;
- A new version of Vapor must be released, with a `var mailer: MailClientProtocol?` property added to the Droplet, and a dependency on the new Mail package

## Feedback

Very much appreciated.

**Comment by bygri** [comment]
## Sendgrid implementation

A near-complete example of an implementation for Sendgrid is available at [the sendgrid branch of bygri/mail](https://github.com/bygri/mail/tree/sendgrid/Sources/SendGridClient). @akeskiner and I have been working on it these past few hours.

We implemented a new class, `SendGridEmail`, which has the capabilities of all SendGrid's features. The backend can also convert a basic Vapor `Email` into SendGrid format.

Therefore, a third party framework can send simple emails like this:
```swift
let email = Email(from: "me@me.com", to: "you@you.com", subject: "Hello", body: "Message")
drop.mailer?.send(email)
```
but equally, someone using SendGrid can send emails like this:
```swift
let email = SendGridEmail(from: "me@me.com", to: "you@you.com", subject: "Hello", templateId: "welcome")
email.substitutions = [
  "firstName": "John",
  "lastName": "Smith",
]
if let sendgrid = drop.mailer?.make() as? SendGrid.MailClient {
  sendgrid.send(email)
}
```

**Comment by caiofbpa** [comment]
I would greatly benefit from this proposal, and I offer my help providing the PostmarkProvider as well as the PostmarkEmail classes.

**Comment by bygri** [comment]
Thanks @caiofbpa - please, feel free to begin using [SendGrid](https://github.com/bygri/mail/tree/sendgrid/Sources/SendGridClient) as a general guide.

**Comment by bygri** [comment]
I have neither the timezone nor the temperament to get this integrated into Vapor proper, so, I have reconfigured this proposal into a third party Provider instead.

Currently SendGrid is implemented, Postmark is in progress. I would be pleased to receive and include implementations for other APIs.

The library is located at [bygri/vapor-mail](https://github.com/bygri/vapor-mail).
