### ISSUE TITLE
Docker build failed, running vapor docker build

### ISSUE THREAD

**Issue by doronkatz** [vapor/vapor#783]
Hi Guys,

So I came across an issue first time running **vapor docker build**. I initially ran **vapor docker init** prior which worked but, but upon running build I got the following error:

`
Docker build failed: The command '/bin/sh -c SWIFT_ARCHIVE_NAME=$SWIFT_VERSION-$SWIFT_PLATFORM &&     SWIFT_URL=https://swift.org/builds/$SWIFT_BRANCH/$(echo "$SWIFT_PLATFORM" | tr -d .)/$SWIFT_VERSION/$SWIFT_ARCHIVE_NAME.tar.gz &&     wget $SWIFT_URL &&     wget $SWIFT_URL.sig &&     gpg --verify $SWIFT_ARCHIVE_NAME.tar.gz.sig &&     tar -xvzf $SWIFT_ARCHIVE_NAME.tar.gz --directory / --strip-components=1 &&     rm -rf $SWIFT_ARCHIVE_NAME* /tmp/* /var/tmp/*' returned a non-zero code: 8
`

I have no idea what to look for in diagnosing it. Any help would be greatly appreciated.. Thanks!

**Comment by jaisontj** [comment]
Hi @doronkatz were you able to figure out why this was happening ?

**Comment by guillaumemaiano** [comment]
I'd be interested in this too!

**Comment by jaisontj** [comment]
Hey,

So I got this working. The Docker file being auto generated by Vapor is causing the problem. More specifically, the ENV variables.

I have created a gist with the fixed Dockerfile (not much of a big fix, really) , kindly use it to build your docker image and it should work. If not, ping me and I can try to help you out. 

https://gist.github.com/jaisontj/9581b305e61f8b193b5bf20af529dccd

**Comment by tannernelson** [comment]
The file pointed to by the toolbox is stored here: https://github.com/vapor/toolbox/blob/master/Dockerfile

@jaisontj can you make the changes from your Dockerfile to the toolbox in a PR?

**Comment by jaisontj** [comment]
@tannernelson I have submitted a PR.

**Comment by daniel-upzzle** [comment]
I have the same error as commented by @doronkatz with the current version revised by @jaisontj .

Any ideas on this?

Thanks!

**Comment by jaisontj** [comment]
Hey @daniel-upzzle, the SWIFT_URL variable is not getting set strangely. @tanner0101 Any idea why that is happening ? I think the easiest fix would be to just set the url without any process involved in building it (taking off the "." from the SWIFT_PLATFORM"

**Comment by daniel-upzzle** [comment]
Neither putting the URL by hand worked for me:

RUN SWIFT_URL=https://swift.org/builds/swift-3.0.2-release/ubuntu1404/swift-3.0.2-RELEASE/swift-3.0.2-RELEASE-ubuntu14.04.tar.gz

RUN wget $SWIFT_URL

Maybe a Docker neetwork configuration problem?

I ended up using a Ubuntu 16 following some article that I can't find right now.

**Comment by jaisontj** [comment]
Hey guys, I have submitted another PR which should solve the issue. Until then you can go to my forked repo and copy the Dockerfile. It will work. I tested it out today.

**Comment by tanner0101** [comment]
Just merged the PR. Let me know if it works.

**Comment by LoganWright** [comment]
check out vapor/docker for more info on how to use docker w/ vapor. The toolbox commands were becoming too problematic to maintain w/o adding much value 👍
