### ISSUE TITLE
Install Vapor On Raspberry Pi?

### ISSUE THREAD

**Issue by J4awesome** [vapor/vapor#787]
I tried install swift 3 on raspberry pi along with vapor.When trying to install vapor this happened.

`^[<unknown>:0: error: build had 3 command failures
error: exit(1): /home/ubuntu/swift-3.0/usr/bin/swift-build-tool -f /home/ubuntu/.vapor-toolbox-temporary/vapor-toolbox/.build/release.yaml
Installing...
bash: line 22: .build/release/Executable: No such file or directory
Use vapor --help and vapor <command> --help to learn more.`

Here is the link I downloaded swift from.

http://dev.iachieved.it/iachievedit/swift-3-0-on-raspberry-pi-2-and-3/

**Comment by goranche** [comment]
that doesn't really sound like a Vapor issue 😉

**Comment by LoganWright** [comment]
@J4awesome We don't have explicit installation instructions, but know of some members in our slack community who have successfully done this.

I'm going to close this issue for now as it's not currently prioritized in the Vapor roadmap, but feel free to [join us to chat](http://vapor.team) with some others who have worked on this 👍 

Also, comment here any solutions you might find for others googling this type of thing.
