### ISSUE TITLE
Hey how about shipping vapor with laravel mix?

### ISSUE THREAD

**Issue by Evertt** [vapor/vapor#792]
With all the cool stuff you can do with javascript these days I can imagine that a lot of people would love to create apps where they use vapor as a (restful) api backend and javascript on the frontend with frameworks like react or vue or angular.

And all that can be made so much easier with laravel mix. Laravel mix is the next evolutionary step from laravel elixir. Elixer uses gulp and the new mix uses webpack. And the great thing is, it's not dependent on laravel! You can use it just as easily with vapor. We might need to provide some boilerplate config code to make it work with vapor's folder-structure and stuff like that, I don't know, but that's peanuts.

So what do you guys think?

**Comment by LoganWright** [comment]
@Evertt this sounds less like an addition to the framework, and more like a template we'd offer to get setup with this style more quickly?

Can you correct me if I'm misinterpreting?

**Comment by Evertt** [comment]
Oh yes you are totally right. I should have put this into the basic-template repository. My bad. Is there a way to move it? Or should I just close this issue and reopen it in the basic-template repo?

**Comment by LoganWright** [comment]
Let's close for now, I'm not sold on the basic-template, but maybe a laravel-mix template on it's own would be appreciated 🙌 I'm sure people would use it.
