### ISSUE TITLE
Support for real-time logging on Heroku

### ISSUE THREAD

**Issue by yoshimkd** [vapor/vapor#796]
I had an issue on Heroku where the logging from the app was buffered.
I tried the Vapor droplet logging and the print() function but it didn't show the logs in real-time.
My analysis showed that the app logs were flushed when making the 79th request since the last flush. Since real-time Heroku logging is an important feature for me, I was looking for a solution and found this answer:

[http://stackoverflow.com/questions/37249787/how-to-print-on-stderr-with-swift](url)

So, in my App module I wrote a file where the print() function is overridden with one that prints directly to stderr which is in real-time:

```
#if os(Linux)
    import Glibc
#else
    import Darwin
#endif


func print(_ items: Any...,
    separator: String = " ",
    terminator: String = "\n") {
    
    var stream = StderrOutputStream()
    print(items,
          separator: separator,
          terminator: terminator,
          to: &stream)
}

struct StderrOutputStream: TextOutputStream {
    
    func write(_ string: String) {
        var filteredString =
            string.replacingOccurrences(of: "\"", with: "")
        
        let stringStartsAndEndsWithBrackets =
            string.characters.first == "[" &&
                string.characters.last == "]"
        
        if !string.isEmpty &&
            string != "\n" &&
            stringStartsAndEndsWithBrackets {
            
            filteredString = filteredString.susbtring(
                offestFromStart: 1, offestFromEnd: 1)
        }
        
        fputs(filteredString, stderr)
    }
    
}

extension String {
    
    func susbtring(offestFromStart: Int,
                   offestFromEnd: Int) -> String {
        let start = index(
            self.startIndex, offsetBy: offestFromStart)
        let end = index(
            self.endIndex, offsetBy: -offestFromEnd)
        let range = start ..< end
        
        return substring(with: range)
    }
    
}
```

It's not perfect or anything and I don't know whether overriding the print() function is the best way to go if this is implemented in Vapor itself, but I think like this could be done and given as an option.

Maybe the best way would be to specify whether the logging should be real-time or buffered in some of the configuration files.

**Comment by gomfucius** [comment]
I reproed the same issue on Heroku.
It looks like the Swift's `print()` uses `stdout`'s default buffering. ->  https://bugs.swift.org/browse/SR-1127

To workaround this, you can import `import Foundation' and call `fflush(stdout)` right after the `print()` statements and you'll see realtime logs from Heroku using the usual `heroku logs -t`

**Comment by yoshimkd** [comment]
I think it would be best if the `fflush(stdout)` be put right after `Swift.print(output, terminator: terminator)` which is on line 50 in Console/Terminal/Terminal.swift. Then all the internal Vapor logs will also be shown in real-time and everyone using the droplet logging in the app will get the same real-time logging. At least, this should be an option I think.

**Comment by joscdk** [comment]
@yoshimkd Sounds like a reasonable solution, and will also help in other cases than heroku, but i think it should be made as an option e.g. in a config file, but would help in a lot of cases as i see it :-)

**Comment by joscdk** [comment]
@yoshimkd i have some things i need to do right now, but i might try to make a PR later today :-)

**Comment by LoganWright** [comment]
@joscdk @yoshimkd I'm concerned with overriding a standard library feature. We have the logging protocol for a reason, I think the default log should use the stdoutput instead of print under the hood so that when users call `drop.log` it is realtime, but otherwise if they use `print`, they'd have to opt-in. 

There's also going to be inherent conflict if this is in a 3rd party module. When it's in _your_ app, the compiler knows to use your implementation. When it's from a separate module and also exists in stdlib, the compiler won't be able to differentiate which to use.

**Comment by yoshimkd** [comment]
@LoganWright So the best solution would be to make the logging real-time when called with `droplet.log` and not mess with the `print` in general right? And probably have a configuration setting whether the logging should be real-time or not?
If this is what you meant, I agree :)

**Comment by LoganWright** [comment]
@yoshimkd this is merged, should be good to go!

**Comment by yoshimkd** [comment]
@LoganWright I just tried it, it works. Thanks a lot.
