### ISSUE TITLE
Vapor serve ignores the --port argument

### ISSUE THREAD

**Issue by st3fan** [vapor/vapor#798]
Starting a minimal hello world Vapor 1.4.0 app like this works:

```
$ .build/debug/HelloWeb serve
No preparations.
Server 'default' starting at 0.0.0.0:8080
```

But changing the port with the `--port` option does not seem to have any effect:

```
$ .build/debug/HelloWeb serve --port=8888
No preparations.
Server 'default' starting at 0.0.0.0:8080
```

I have tried different port specifications like `:8888`, `8888`, `*:8888` and `0.0.0.0:8080` but they are all ignored.

**Comment by vzsg** [comment]
Where did you find that this parameter should work?
Try this instead: `--config:servers.default.port=8888`

**Comment by vzsg** [comment]
I found in the Toolbox sources that the help of the `serve` command incorrectly lists `--port` as a supported argument. It's probably a leftover from the pre-1.0 times.

**Comment by tannernelson** [comment]
iirc, we wanted to leave `--port` in as a shortcut for `--config:servers.default.port=8888`. It's possible this got removed at some point. Do you remember @LoganWright?

**Comment by BrettRToomey** [comment]
Fixed.
