### ISSUE TITLE
Deploy on Heroku doesn't work

### ISSUE THREAD

**Issue by DBocksteger** [vapor/vapor#804]
I hit the 'Deploy on Heroku' button, but it fails while the build step.

# Build-log
```
-----> Swift app detected
Cloning into 'swiftenv'...
-----> Installing 3.0-GM-CANDIDATE
Downloading https://swift.org/builds/swift-3.0-GM-CANDIDATE/ubuntu1404/swift-3.0-GM-CANDIDATE/swift-3.0-GM-CANDIDATE-ubuntu14.04.tar.gz
3.0-GM-CANDIDATE has been installed.
-----> Installing clang-3.7.0
xz: (stdin): File format not recognized
 !     Push rejected, failed to compile Swift app.
 !     Push failed
```

<img width="560" alt="bildschirmfoto 2017-01-25 um 19 39 30" src="https://cloud.githubusercontent.com/assets/1019812/22304056/33a5a43a-e336-11e6-9a98-bd371b6a4dc3.png">

I hope someone knows this issue or nows a workaround?

**Comment by vzsg** [comment]
It seems to have been caused by a temporary outage of llvm.org (where clang is downloaded from by the buildpack), it's working again. Try restarting the build.
