### ISSUE TITLE
Vapor and Heroku Issue

### ISSUE THREAD

**Issue by doronkatz** [vapor/vapor#808]
Hi guys,

I am trying to deploy my app onto heroku, for the second time with an update, from Vapor's MySQL to PostGres. In doing so, even though locally my app works fine when changed, when I push to heroku, i still get an error and it concerns MySQL. To me that means there's a cache issue. I've downloading the heroku plugin to purge the repo etc, clear cache but it still happens. The error I get is as follows:

`remote: Compile Swift Module 'HMAC' (2 sources)
remote: /tmp/build_cf0c672f743de6e302b0526aa7be138f/Packages/MySQL-1.1.1/Sources/MySQL/Field+Variant.swift:26:24: error: use of unresolved identifier 'MYSQL_TYPE_JSON'
remote:             if self == MYSQL_TYPE_JSON {
remote:                        ^~~~~~~~~~~~~~~
remote: CMySQLLinux.MYSQL_TYPE_BLOB:1:12: note: did you mean 'MYSQL_TYPE_BLOB'?
remote: public var MYSQL_TYPE_BLOB: enum_field_types { get }
remote:            ^
remote: CMySQLLinux.MYSQL_TYPE_LONG:1:12: note: did you mean 'MYSQL_TYPE_LONG'?
remote: public var MYSQL_TYPE_LONG: enum_field_types { get }
remote:            ^
remote: CMySQLLinux.MYSQL_TYPE_SET:1:12: note: did you mean 'MYSQL_TYPE_SET'?
remote: public var MYSQL_TYPE_SET: enum_field_types { get }
remote:            ^
remote: /tmp/build_cf0c672f743de6e302b0526aa7be138f/Packages/MySQL-1.1.1/Sources/MySQL/Bind+Node.swift:44:31: error: use of unresolved identifier 'MYSQL_TYPE_JSON'
remote:                 if variant == MYSQL_TYPE_JSON {
remote:                               ^~~~~~~~~~~~~~~
remote: CMySQLLinux.MYSQL_TYPE_BLOB:1:12: note: did you mean 'MYSQL_TYPE_BLOB'?
remote: public var MYSQL_TYPE_BLOB: enum_field_types { get }
remote:            ^
remote: CMySQLLinux.MYSQL_TYPE_LONG:1:12: note: did you mean 'MYSQL_TYPE_LONG'?
remote: public var MYSQL_TYPE_LONG: enum_field_types { get }
remote:            ^
remote: CMySQLLinux.MYSQL_TYPE_SET:1:12: note: did you mean 'MYSQL_TYPE_SET'?
remote: public var MYSQL_TYPE_SET: enum_field_types { get }
remote:            ^
remote: Compile Swift Module 'Hash' (3 sources)
remote: Compile Swift Module 'BCrypt' (1 sources)
remote: <unknown>:0: error: build had 1 command failures
remote: swift-build: error: exit(1): /app/tmp/cache/swiftenv/versions/3.0.2/usr/bin/swift-build-tool -f /tmp/build_cf0c672f743de6e302b0526aa7be138f/.build/release.yaml
remote:  !     Push rejected, failed to compile Swift app.
remote: 
remote:  !     Push failed
remote: Verifying deploy....
remote: 
remote: !	Push rejected to actively-staging.
remote: `

**Comment by vzsg** [comment]
We discussed this issue in Slack, and it was a local deployment problem, not related to Vapor. The change from MySQL to PostgreSQL was committed to a different local branch instead of `master`, but `git push heroku` pushes `master` to the remote `master`.

The fix is to explicitly specify the source branch, e.g.:

```
# git push heroku develop:master
```
