### ISSUE TITLE
Best practice for managing the makeNode function

### ISSUE THREAD

**Issue by dalu93** [vapor/vapor#810]
Actually mine is not a feature request, but could be.
I find the `makeNode(context: Context)` function a bit unclear since it's used by `Fluent` for generating the insert query and it's used by the middleware to generate the `JSON` response.
I have a lot of models that have some properties in the database table that I wouldn't like to show in the JSON response and the only solution I found is to use that `Context` conforming parameter.

For example, a newly created `Todo` model by an user has to contain the `user_id` in the db table.
But the response at the `POST /todo` endpoint shouldn't include it because the user_id is implicit since the user just created it and the client doesn't need that information at all in this case.

Is there a best practice for doing something like this?
I thought a good idea could be separate the `makeNode` function for rendering the JSON and the one for creating the insert query in db.

**ADDING**

This is how the `makeNode(_: Context)` function looks like in my examples

```swift
func makeNode(context: Context) throws -> Node {
        guard
            let todoContext = context as? TodoContext,
            todoContext.includeUserInfo == false else {
            return try _makeCompleteNode()
        }
        
        return try _makeNodeWithoutUserInfo()
    }
```

And this can get much more complicated with the time.

**Comment by tannernelson** [comment]
You can override `makeJSON()` specifically for returning JSON responses. The default implementation calls `makeNode()` and that's why you see that behavior.

You should also be able to cast the `Context` as the `JSON.JSON` type or the `Vapor.Model` type to detect what kind of makeNode call is being made. Although I don't know if this is implemented yet.

**Comment by dalu93** [comment]
Overriding the `makeJSON()` function seems the right choice for me. In this way I get rid of a lot of checks for the context type. Thanks @tannernelson

**Comment by dalu93** [comment]
Hey @tannernelson, I gave it a try and it works nicely when I have to return a single object instance.
But in case I have to return an array of objects, it keeps calling the `makeNode()` function instead of the `makeJSON()` one.

This is how the request handler looks like

```swift
func getAll(using request: Request) throws -> ResponseRepresentable {
    let todos = try Todo.query().filter("user_id", userId).run()
    let node = try Node(node: [
                "todos": todos.makeNode()
            ])
        
    return JSON(node)
}
```

**Comment by dalu93** [comment]
The only thing seems working is to map the array of `Todo` in an array of `JSON` and then wrap this array in a `JSON` instance

```swift
let todosJSON = try todos.map { try $0.makeJSON() }
return JSON(todosJSON)
```

Is there a better way to handle this?

**Comment by tannernelson** [comment]
Using the context is probably a better way to achieve this (the second method I mentioned in my comment). This is something we're wanting to make easier in the next version of Vapor (when we can make breaking changes to the current API).

Until then, this is useful information to keep track of. Could you open an issue on vapor/node detailing this issue? Basically just copy paste what you have here in the last comment.
