### ISSUE TITLE
`Node.NodeError 0` is vague

### ISSUE THREAD

**Issue by tannernelson** [vapor/vapor#811]
The `Node.NodeError 0` appears to be showing up when trying to extract a key that doesn't exist. This error message is vague and could be improved.

Something like `Could not extract key "foo"` in development would be nice.

<img width="962" alt="zllvy" src="https://cloud.githubusercontent.com/assets/1342803/22542851/276e3f6c-e92e-11e6-873e-6f493287c07a.png">

http://stackoverflow.com/questions/41994883/fluent-entityerror-error-0

**Comment by vzsg** [comment]
There are many other instances of this issue, where the Error subtype has the proper, descriptive message, but printing it out shows only an unusable number.

For example, any SQL error will end up as `PostgreSQLError 1`, despite the fact that the driver received _and_ stored the real error message too.

**Comment by tannernelson** [comment]
@vzsg can you create an issue for that in the vapor/postgresql repo? I believe that is where those error messages are rendered.

`Node.NodeError` rendering is either in vapor/vapor or vapor/node.

**Comment by vzsg** [comment]
I'd rather not. Messing with every single Error subclass in every single repository is a pointless stuggle.

The string rendering is done by AbortMiddleware [here](https://github.com/vapor/vapor/blob/master/Sources/Vapor/Error/AbortMiddleware.swift#L29).

Consider the following:

```swift
let err = DatabaseError.invalidSQL(message: "Table FOO does not exist")
let current = err.localizedDescription // "The operation couldn't be completed. (DatabaseError error 1.)"
let shouldBe = String(describing: err) // "invalidSQL("Table FOO does not exist")"
```

**Comment by tannernelson** [comment]
Oh good point, didn't realize that. That seems like a great fix.

**Comment by vzsg** [comment]
I just found that this problem is more elegantly handled in [Droplet+Responder.swift](https://github.com/vapor/vapor/blob/master/Sources/Vapor/Droplet/Droplet%2BResponder.swift#L59-L71).

I think the same logic should be copied into AbortMiddleware, especially as it's a default middleware. This would immensely speed up people helping themselves and others.
