### ISSUE TITLE
Clarify documentation regarding "arguments" passed into Droplet initializer

### ISSUE THREAD

**Issue by mz2** [vapor/vapor#812]
At https://vapor.github.io/documentation/testing/basic.html there's a following statement made about setting up a Droplet for testing:

> Droplet(arguments: ["dummy/path/", "prepare"], ...
> The arguments: parameter in our Droplet creation. This is rarely used except for advanced situations, but we'll use it here in testing to ensure that our Droplet doesn't try to automatically serve and block our thread. You can use arguments besides "prepare", but unless you're doing something specific for an advanced situation, these arguments should suffice.

It would be helpful if the documentation here, and also in Droplet initialization, would explicitly make it clear that the 1st argument in that argument list maps to the argv passed into the app (and such the first argument is the executable name – therefore it's just "dummy/path" when you initialize a Droplet in context of tests).

**Comment by tannernelson** [comment]
Moved to vapor/documentation.

**Comment by mz2** [comment]
Ah, sorry. Will make sure to file there next time.
