### ISSUE TITLE
Struggling with Droplet client

### ISSUE THREAD

**Issue by Lukaz32** [vapor/vapor#813]
This used to work fine. Now it just doesn't.
Does anyone know what I am missing?

http://stackoverflow.com/questions/42008299/struggling-with-vapor-client

**Comment by Lukaz32** [comment]
`drop.client = FoundationClient.self`
is required for it to work.
Should consider including that in the docs :T

**Comment by MartinW** [comment]
Vapor Slack #help channel is great for answering questions too http://vapor.team
