### ISSUE TITLE
Feature: Add `sum` to Fluent to sum the values of a column

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#819]
# Feature, Enhancement, or Optimization

# Add `sum` to Fluent

* Author(s): [kgn](https://github.com/kgn)

## Introduction

I'd like to be able to access the database function `sum`, but we can do with `count` today.

## Motivation

I've run into a use case where I want to return the total number of items, and their total cost. I can use `count`, but am having to run raw sql in order to retrieve the sum of their cost.

## Proposed solution

I propose that `sum` be added, similar to how `count` is implemented, but `sum` would take the name of the column to sum.

## Code snippets

*Assume a `ShoppingCart` model with `Item` model children.*

```swift

let numberOfItems = shoppingCart.items.count()
let totalCost = shoppingCart.items.sum("price")

```

## Impact

This change would allow me to remove the raw sql code in my controllers, running raw sql also requires me to add the `Droplet` to the controllers just for this one part, so I could remove that requirement too.

## Alternatives considered

This seems like the right solution as it matches a paradigm already laid out by `count`.

**Comment by vzsg** [comment]
I think this is a good idea, and shouldn't stop at `SUM`. The `AVG`, `MIN` and `MAX` aggregate functions are also universally supported and behave exactly the same.

**Comment by vzsg** [comment]
On a second thought, implementing either on Mongo will require tapping into the aggregation pipeline, but possible nevertheless.

**Comment by tanner0101** [comment]
Moving to https://github.com/vapor/fluent/issues/246
