### ISSUE TITLE
Compilation on linux very slowly

### ISSUE THREAD

**Issue by Droppix** [vapor/vapor#822]
Hi,

On linux (AWS -> t1.micro), when I re-modify a single file (main.swift), "vapor build --verbose" recompile all modules, is this normal? (The compilation is really slowly for a little demo -> 20/30 minutes)

```
Fetching Dependencies [Done]
Building Project...
warning: minimum recommended clang is version 3.6, otherwise you may encounter linker errors.
Linking CLibreSSL
Compile Swift Module 'TurnstileCrypto' (3 sources)
Compile Swift Module 'Jay' (21 sources)
Compile Swift Module 'SocksCore' (15 sources)
Compile Swift Module 'Polymorphic' (2 sources)
Compile Swift Module 'PathIndexable' (2 sources)
Compile Swift Module 'libc' (1 sources)
Compile Swift Module 'Socks' (5 sources)
Compile Swift Module 'Core' (28 sources)
Compile Swift Module 'Turnstile' (13 sources)
Compile Swift Module 'Node' (22 sources)
...
```

Thanks

**Comment by LoganWright** [comment]
@Droppix this was a bug in the Swift3.0/SwiftPM release that I believe has since been amended. Would you be able to update your Swift version on your instance and try again?

**Comment by Droppix** [comment]
Unfortunately it doesn't work!

I've upgraded from swift-3.0.1 to swift-3.0.2 (https://swift.org/builds/swift-3.0.2-release/ubuntu1404/swift-3.0.2-RELEASE/swift-3.0.2-RELEASE-ubuntu14.04.tar.gz)

**Comment by Droppix** [comment]
Ok, I fixed the problem by doing an update "clang" (from 3.4 to 3.6).
