### ISSUE TITLE
Bug: cookie name not used in factory?

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#824]
I'm implementing a custom cookie as the default `vapor-auth` cookie is `http only`. I also wanted to change the name of the cookie to something specific to my app. 

First I tried this because `name` and `value` are required parameters so this seemed like the logical place to set the name. This still results in `vapor-auth` being set in the headers.
``` swift
drop.middleware.append(AuthMiddleware(user: User.self) { value in
    return Cookie(
        name: "custom-auth", value: value
    )
})
```

After digging into the source I saw the `cookieName` parameter on `AuthMiddleware`, this works to change the cookie name, but is confusing which `name` will be used especially because you you still have to specify a name when creating a `Cookie.`
```swift
drop.middleware.append(AuthMiddleware(user: User.self, cookieName: "custom-auth") { value in
    return Cookie(
        name: "custom-auth", value: value
    )
})
```

**Comment by hhanesand** [comment]
@kgn  I solved this problem by creating my own middleware. I needed to have 2 types of users to log in, so I created my own middleware, some helper methods, and a login controller.

You can see it all here : https://gist.github.com/hhanesand/310ff975ee1f1142a84ef11b7b5a3620

**Comment by tannernelson** [comment]
I think the solution here would be to pass `name, value` to the closure. That way it's clear that the cookie you return in the factory should use the cookie name from the middleware.

**Comment by kgn** [comment]
@tannernelson is there a reason the default cookie factory makes a cookie that is `httpOnly: true`? That's the issues that started this. I needed to make my own cookie because I couldn't access the cookie from my web app.

**Comment by tannernelson** [comment]
@kgn If that was a blocker for you then possibly changing the default to false is the best fix. I can't think of a good reason why it was set to be true other than erring on the side of overly safe.

**Comment by kgn** [comment]
If you are cool with that, then I'd just need to implement my `AuthMiddleware` as:

`drop.middleware.append(AuthMiddleware(user: User.self, cookieName: "my-app-auth")`

Which would be great, that way I, and others, won't need to mess with the cookie factory.

The default for `httpOnly` is already `false` in  `Cookie.init`.

**Comment by tannernelson** [comment]
Sounds good to me. Would you want to make that PR @kgn?

**Comment by kgn** [comment]
@tannernelson done! https://github.com/vapor/vapor/pull/831

**Comment by kgn** [comment]
Before you merge, lemme see if I can fix the other issue of the name of the cookie in the cookie factory not being used.

This case:
``` swift
drop.middleware.append(AuthMiddleware(user: User.self) { value in
    return Cookie(
        name: "custom-auth", value: value
    )
})
```

**Comment by kgn** [comment]
@tannernelson I looked for a way to use the cookie name from the cookie created in the factory, but it would have to set `self.cookieName` from the factory closure which seems wrong. So I implemented your idea of passing the cookie name to the factory. Lemme know if this looks good and I'll merge it into my PR: https://github.com/kgn/vapor/commit/1caf0b38d7f5cfca393f2955717da556e0f253f2
