### ISSUE TITLE
Drop Client Bug?!

### ISSUE THREAD

**Issue by J4awesome** [vapor/vapor#825]
Hi,
I'm using vapor to write some server side code to create a shipping object in API called [moltin](https://www.moltin.com/).I tried to use vapor's built in client which did work for generating the token like so 

``` 
let response = try drop.client.post("https://api.molt.in/oauth/access_token", headers: [:], body:    Body.data( Node(["client_id":"XXXXX", "client_secret":"XXXXX","grant_type":"XXX"]).formURLEncoded()))
```

However, after getting the token and creating the shipping object using the same method uses above this happened.

```
Optional([JSON.JSON(node: Node.Node.string("Title is required")), JSON.JSON(node: Node.Node.string("Slug is required")), JSON.JSON(node: Node.Node.string("Company is required")), JSON.JSON(node: Node.Node.string("Status is required")), JSON.JSON(node: Node.Node.string("Tax Band is required")), JSON.JSON(node: Node.Node.string("Price is required"))])
```

Even though I already specified in the JSON.Here is the code i'm using thats gives the error

```
let json = try JSON(node:["company":"USPS", "tax_band":"1","title":uuid,"price":"\(price)","slug":uuid + "a"])
let response = try drop.client.post("https://api.molt.in/v1/shipping", headers: ["Authorization":"Bearer \(self.shippingBearer)"], body: Body.data( Node(bytes: json.makeBytes()).formURLEncoded()))
print(response.json?["errors"]?.array)
```
To my surprise using curl works fine
``
curl -X POST https://api.molt.in/v1/shipping -H "Authorization: Bearer XXX" -d "title=test" -d "slug=test1" -d "company=0" -d "status=0" -d "tax_band=0" 
``

**Comment by vzsg** [comment]
You should decide if you are posting the body as JSON or as `x-www-form-urlencoded` key-value pairs. This fragment: `Body.data( Node(bytes: json.makeBytes()).formURLEncoded())` is a weird amalgamation of the two approaches, and completely unnecessary.

I suggest joining the [Slack team](http://vapor.team) and the `#help` channel for questions like this.

**Comment by vzsg** [comment]
After some discussion on Slack, the requirement is sending an URL-encoded form, which can be implemented along the lines of:

```swift
let body: Node = [
    "company": "USPS",
    "tax_band": "1",
    "title": .string(uuid),
    "price": .string("\(price)"),
    "slug": .string(uuid + "a")
]

let request = try Request(method: .post, uri: "https://api.molt.in/v1/shipping")
request.formURLEncoded = body
request.headers[.authorization] = "Bearer \(self.shippingBearer)"
let response = try drop.client.respond(to: request)
```

The takeaway is that if the body is a form, there's no place for any JSON-related classes, and there's no need to manually encode the bytes. The Request class will handle it all automatically.

**Comment by AgoniNemo** [comment]
@vzsg Is there an example of uploading a file?

**Comment by vzsg** [comment]
There is now, lol. [See my comment here.](https://github.com/vapor/vapor/issues/1117#issuecomment-322715606)

**Comment by maximedegreve** [comment]
This is actually the same for Instagram, if people run into issues with this...
