### ISSUE TITLE
Error: "could not bind to"

### ISSUE THREAD

**Issue by Droppix** [vapor/vapor#835]
Hi,

I have an issue when i run my vapor server : vapor run serve (without nginx)
could not bind to 'test.mydomain.com':8080, it may be in use or require sudo.

servers.json:
```
{ 
        "default": {
        "port": "$PORT:8080",
        "host": "test.mydomain.com",
        "securityLayer": "none"
    }
}
```

Any idea?

**Comment by vzsg** [comment]
Another process is using port 8080 on your system. It might be another instance of your Vapor app, or something else completely.

Run the following command to see which process is it:

```
lsof -i :8080
```

And act upon what you find (kill that process, etc.)

**Comment by Droppix** [comment]
No, already check all ports...Also, I try another ports (80, 443, 8443)

**Comment by vzsg** [comment]
Oooo. I didn't notice that you had a domain name there – this is about IP binding, you need to set the IP address of the _network interface_ you want the server to listen on, or `0.0.0.0` if you want to listen on all interfaces.

DNS happens at a higher level and has nothing to do with this.

**Comment by BrettRToomey** [comment]
Closing. Feel free to reopen if you have more questions.
