### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by mtgomes** [vapor/vapor#840]
I'm currently having an issue with one of my vapor projects.

Basically, the compilation never ends and I keep on seeing the swift process memory occupation going up until I have to kill the process. 

This is both using xcode and vapor build. I stopped being able to compile my project with this. 

I know the description is quite vague so I can submit any default / logs that you guys need to fix this issue.

Can you guys please help!

Cheers!

**Comment by rfdickerson** [comment]
Are you using MongoKitten?

**Comment by LoganWright** [comment]
@mtgomes can we also get some environment info?

osx/linux
swift version
vapor version
xcode version

If it's on Linux, particularly DO or something, it might be swap space

**Comment by mtgomes** [comment]
Nope, I'm using the postgresql provider by Vapor.

**Comment by mtgomes** [comment]
@LoganWright here's the info:
OSX Sierra
Swift 3.0.2 
Xcode 8.2.1
Vapor toolbox 1.0.3

Here's the package information:
`
.Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 5),
        .Package(url: "https://github.com/vapor/postgresql-provider.git", majorVersion: 1),
        .Package(url: "https://github.com/BrettRToomey/Jobs.git", majorVersion: 0),
        .Package(url: "https://github.com/SwiftyBeaver/SwiftyBeaver-Vapor.git", majorVersion: 1)
`

**Comment by vzsg** [comment]
Have you tried building in Xcode and checking the Report navigator, where you can actually pinpoint which file is the build getting hung up?

**Comment by mtgomes** [comment]
@vzsg Good tip, thanks. 

The issue is in my model class.

You can find here a demo of the issue occurring [here](https://github.com/mtgomes/VaporIssue840)

Sorry for all the "test" naming but this is the closest I can to the real code without getting into trouble. 

In the demo you'll find a Model example. If you remove the "issueHere" the code compiles correctly. If not the compiler just get's stuck until I have to cancel it.

I've also included a screenshot of the Activity Monitor at the time I have to stop the compilation.

Can you guys figure out what I'm doing wrong?

Thanks!

**Comment by azeff** [comment]
@mtgomes you killing swiftc by complex type inference in your `makeNode` method.
Try explicitly create node for each field. Something like this should help
``` swift
func makeNode(context: Context) throws -> Node {
  return try Node(node: [
    "id": id,
    "test": Node(test),
    "test2": Node(test2),
    "test3": Node(test3),
    "test4": Node(test4),
    "test5": Node(test5),
    "test6": Node(test6),
    "test8": Node(test8),
    "test9": Node(test9),
    "test10": Node(test10),
    "test11": Node(test11),
    "test12": Node(test12),
    "test13": Node(test13),
    "issuehere": Node(issueHere)
  ])
}
```

**Comment by mtgomes** [comment]
Gotcha! It works! Nicely done! Thanks!
