### ISSUE TITLE
Confusing Children method

### ISSUE THREAD

**Issue by xiangyu-sun** [vapor/vapor#841]
# Bugs

```
extension Children: QueryRepresentable {
    public func makeQuery() throws -> Query<T> {
        guard let ident = parent.id else {
            throw RelationError.noIdentifier
        }        
       let foreignId = foreignKey ?? "\(T.name)_\(T.idKey)"
        return try T.query().filter(foreignId, ident)
    }
}

```

for example, 
users
 -id
 - name

dogs
- user_id
- name

if I call user.children(nil,Dog.self)
things would go totally wrong,  it will provide dog_id as a query id to search in  dog for user.

**Comment by tanner0101** [comment]
These relations are being updated in Fluent 2.0. https://github.com/vapor/fluent/blob/master/Sources/Fluent/Relations/Children.swift

Should be a lot less confusing!
