### ISSUE TITLE
include internal arg in Provider protocol

### ISSUE THREAD

**Issue by LoganWright** [vapor/vapor#851]
we have `func beforeRun(_: Droplet)` which works fine, but if we do `_ drop: Droplet` it'll autocomplete w/ args which is really nice.

**Comment by kandelvijaya** [comment]
Thanks for the task. Can you just update me if this is done else it could be a perfect introduction to vapor for me?

**Comment by tanner0101** [comment]
@kandelvijaya I did a search for `_:` and it looks like it still appears in the source files. (aka not fixed yet)

**Comment by kandelvijaya** [comment]
Thanks for the info. I will take this task and work on tomorrow evening hopefully.

**Comment by kandelvijaya** [comment]
Can we close this issue?

**Comment by tanner0101** [comment]
thanks @kandelvijaya :)
