### ISSUE TITLE
more thorough error pattern

### ISSUE THREAD

**Issue by LoganWright** [vapor/vapor#852]
flush out a more thorough and predictable error pattern from Swift, current working idea is something like:

```swift
protocol VaporError: Swift.Error, CustomStringConvertible {
    var possibleCauses: [String] { get }
    var suggestedFixes: [String] { get }
}
```

Also other metadata we might find useful. 

This will greatly improve the debugging experience for users and help ensure things like printing an error are formatted better than standard swift reflection logs.

It also encourages showing how to fix the error rather than just what's wrong which will help users be more productive.

**Comment by tanner0101** [comment]
I was thinking something like

```swift
protocol SuggestedFixable {
    var suggestedFixes: [String] { get }
}
```

Then depending on what types of errors want to conform to different parts of that, we can create dynamic error responses.

Also, these protocols would need to go somewhere like core or perhaps a separate error package that all of our dependencies (even the lowest level ones) can conform to so we get great errors everywhere.

**Comment by LoganWright** [comment]
I'm open to another errors package if it seems reasonable to do so, picking which protocols to conform to is great, but might require more casting internally than something like providing sensible defaults. We could always default an empty array for suggestedFixes and when formatting a greater error response we can skip empty instead of casting to see if it's a certain protocol type

**Comment by LoganWright** [comment]
resolved w/ debugging pack 👍
