### ISSUE TITLE
Ambiguous reference to member 'get(_:_:_:handler:)'

### ISSUE THREAD

**Issue by justbane** [vapor/vapor#853]
Fully up-to-date environment (literally installed everything yesterday).

I am going through a walk through on Ray Wenderlich - I have this code.

```
import Vapor

let drop = Droplet()

drop.get("template1") { request in
    return try drop.view.make("hello", Node(["name": "Justin"]))
}

drop.get("template2", String.self) { request, name in
    return try drop.view.make("hello", Node(["name": name]))
}

drop.run()
```

I get the error  "Ambiguous reference to member 'get(_:_:_:handler:)'" on the second drop.get route.

Vapor Toolbox v1.0.5-4-gd20c424
XCode: Version 8.2.1 (8C1002)
Swift: version 3.0.2

Will not build, will not clean and build. Will not quit and build.

**Comment by tanner0101** [comment]
try changing `Node(["name": "Justin"])` to `try Node(node: ["name": "Justin"]`

**Comment by justbane** [comment]
That got it: thanks!

**Comment by jkmathew** [comment]
I have a similar issue, I am following raywenderlich tutorial here https://videos.raywenderlich.com/screencasts/509-server-side-swift-with-vapor-getting-started (time around 2:30)

when I try a code like 
```
try drop.get("something", Int.self) { request, something in
    let m = "something is \(something)"
    return try JSON(node: [
        "message" : m
        ])
}
```
Xcode is giving error `ambiguous reference to member 'get(_:handler:)'`

Full error trace
```
/path/to/main.swift:25:9: error: ambiguous reference to member 'get(_:handler:)'
    try drop.get("something", Int.self) { request, something in
        ^~~~
Routing.RouteBuilder:5:17: note: found this candidate
    public func get(_ segments: String..., handler: @escaping Routing.RouteHandler)
                ^
Vapor.Responder:3:17: note: found this candidate
    public func get(_ uri: String, query: [String : NodeRepresentable] = default, _ headers: [HTTP.HeaderKey : String] = default, _ body: BodyRepresentable? = default, through middleware: [Middleware] = default) throws -> HTTP.Response
                ^
```
```
$ swift --version
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9
$ vapor --version
Vapor Toolbox: 2.0.3
```

Whats wrong with the implementation?

**Comment by vzsg** [comment]
The toolbox version is not as important as the framework version (from your Package.swift).

If you are in a Vapor 2 project, you can no longer use the old type-safe syntax to declare the Int parameter on the path.

Instead, check the [docs](https://docs.vapor.codes/2.0/routing/parameters/#type-safe) for the new syntax. Most notably, the closure only gets one argument (the request), and you need to use `parameters.next(Type)` to access the value.

**Comment by jkmathew** [comment]
Thanks @vzsg 
I am new to vapor, I didn't knew that tutorial following vapor 1.0 and I am using vapor 2.0
