### ISSUE TITLE
Simple project takes always over 5 mins to build

### ISSUE THREAD

**Issue by maximedegreve** [vapor/vapor#854]
The whole day I'm trying to figure out why my project takes every time over 5 mins to build.

I've published the project here so you could try it yourself. https://github.com/maximedegreve/Walllpaper

Steps to reproduce:
- Build using "vapor xcode -y"
- Run in Xcode
- Now change a line in the User.swift model
- Run in Xcode again (again takes over 5mins to build)

I've tried:
- vapor clean
- removed derived data
- removed the whole build folder manually

This happens both when building in Xcode and normal building through vapor's toolbox.

This doesn't happen with my other Vapor project.

I'm on the latest MacBook Pro with touchbar.

**Comment by maximedegreve** [comment]
Using

```
var dict: [String: Node] = [:]
dict["id"] = id
dict["access_token"] = accessToken
// ... set every field one by one ...
return .object(dict)
```

Speeds it up massively, I think it's because [String: Node] was set on it too.
It might be worth further investigating this since this could probably massively improve build times....

**Comment by tanner0101** [comment]
This would be a great thing to report to bugs.swift.org. They are looking for slow compiling code samples that they can analyze.

**Comment by Turtlex** [comment]
I have the same thing know, happened just after updating toolbox!

**Comment by vzsg** [comment]
And the solution is most likely the same too: if you have _huge_ conversions inside the makeNode functions, break them up into multiple, simple expressions like [this change](https://github.com/maximedegreve/Walllpaper/commit/022bfd6cdf35376f4e2f178cd2d10351f0b297f4).

**Comment by BrettRToomey** [comment]
As @vzsg said: make sure to break up complex dictionary literals that have lots of inference. The overload resolution totally kills the compiler.
