### ISSUE TITLE
feature request: `vapor new` should include at least a single base test

### ISSUE THREAD

**Issue by heckj** [vapor/vapor#855]
# Enhancement

# `vapor new` would benefit from including an initial test

* Author(s): [Developer](https://github.com/heckj)

## Introduction

I was walking through the vapor project tutorial, and the sequence of:
 - `vapor new vaportst`
 - `vapor build`
 - `vapor test`

Didn't result in seeing any tests complete. The code all still works, is there, and the documentation at https://vapor.github.io/documentation/testing/basic.html covers how to set up a basic test case, but I think it would be advantageous to have this logic split up even in the very first example (e.g. using an `AppLogic` module)

## Motivation

I think it's beneficial for both the project, and for projects built, to include some amount of testing and validation that can be easily and immediately run by the developer to be highly valuable. Including this mechanism up front leaves example code traces immediately for how to do that.

## Proposed solution

Make the modifications described in the documentation under https://vapor.github.io/documentation/testing/modules.html (for Linux) and https://vapor.github.io/documentation/testing/basic.html to the template code generated from `vapor new`

## Impact

This should be negligible impact, none to existing projects, and the documentation would be well served to include a "vapor test" command in the tutorial/walk-through sequence to make it clear it's included.

**Comment by BrettRToomey** [comment]
I'm perfectly fine with this, but I know that some people are worried about the confusion caused by having multiple modules.

Alternatively, there are templates that are fully testable and you can create a new project using those.

**Comment by vzsg** [comment]
The new default template's [beta](https://github.com/vapor/api-template/tree/beta) version already has the modular, testable layout, so I think this is done 👍

**Comment by BrettRToomey** [comment]
done is done.
