### ISSUE TITLE
Add Vapor to Techempowers Web Framework Benchmark

### ISSUE THREAD

**Issue by kaspergrubbe** [vapor/vapor#856]
# Add Vapor to Techempowers Web Framework Benchmark

## Introduction

I watched a nice introduction of Vapor by my ex-colleague and now Technical Director of Nodes (sponsor of Vapor), Oliver Wang Hansen here: https://vimeo.com/193549098 , and in that introduction the claim was made that Vapor was way faster than other comparable frameworks.

The exact quote was: "It's around 100 times faster than your normal web framework such as PHP, Python, Ruby, etc." taken from the 04:01 mark from the Vimeo video.

As a Ruby and Rails developer that sounds really exciting.

## Motivation

If Vapor is 100 times faster than other frameworks (and languages!) it would indeed help the project get more eyeballs, and it would help the adoption since a lot of people would switch over to reap the benefits of such a fast framework.

By submitting the test-cases described here: https://www.techempower.com/benchmarks/#section=code&hw=ph&test=fortune Vapor would be able to be compared with other languages, and hopefully take the first position: https://www.techempower.com/benchmarks

## Proposed solution

We should implement the requirements described here: https://www.techempower.com/benchmarks/#section=code&hw=ph&test=fortune and add the solution to the repo here: https://github.com/TechEmpower/FrameworkBenchmarks

## Impact

More PR, more adoption and more eyeballs.

**Comment by LoganWright** [comment]
@BrettRToomey nail it, just tag the PR here when you get it 👍 closing for now ..

**Comment by kaspergrubbe** [comment]
Cool to see this picked up, I hope to see what you come up with.

I am not sure why the PR was closed if you want to work on it, it feels a bit backwards, but hey, it's your project! 👍
