### ISSUE TITLE
Bug: Int.makeNode() and Double.makeNode() crash on linux

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#862]
I've been working on deploying my vapor app with Docker and was running into some crashes that were the result of using `.makeNode()` on integer and double variables. Please see the below examples:

``` swift
let people = 12
people.makeNode() // crashes on linux, ok on mac
Node(people) // ok on linux and Mac

let money = 54.23
money.makeNode() // crashes on linux, ok on mac
Node(money) // ok on linux and Mac

let name = "David"
name.makeNode() // ok on both
```

**Comment by vzsg** [comment]
Can you make an [MCVE](http://stackoverflow.com/help/mcve), for example a main.swift and a Package.swift and a Dockerfile uploaded to a Gist?

**Comment by LoganWright** [comment]
@kgn can we also get some environment info?

- Node version
- Linux Version
- Crash Logs if they exist

**Comment by tanner0101** [comment]
Also Swift version.

**Comment by kgn** [comment]
I put together a small three file test case, however I'm not able to reproduce the problem I was seeing with my full app. Closing for now, if I see this again I'll try to reproduce in a small test case.

Here are the three files in my test app:

**main.swift**
``` swift
import Vapor

let people = 12
print("double")
print(try people.makeNode()) // ok on linux and Mac
print(Node(people)) // ok on linux and Mac

let money = 54.23
print("int")
print(money.makeNode()) // ok on linux and Mac
print(Node(money)) // ok on linux and Mac

let name = "David"
print("string")
print(name.makeNode()) // ok on linux and Mac

print("JSON")
let node = JSON([
    "name": name.makeNode(),
    "people": try people.makeNode(), // why does only double need try?
    "money": money.makeNode()
])
print(node)
```

**Package.swift**
``` swift
import PackageDescription

let package = Package(
    name: "makeNode",
    dependencies: [
        .Package(url: "https://github.com/vapor/vapor.git", majorVersion: 1, minor: 5)
    ]
)
```

**Dockerfile**
```
FROM vapor/vapor:1.0.5-xenial

WORKDIR /vapor
COPY . /vapor

RUN vapor build

RUN vapor run
```
