### ISSUE TITLE
Bug: relations don't seem to be working on linux

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#863]
I've been working getting my vapor app running on linux in a docker container and ran into a strange difference on linux that seems to cause relationships to not work.

I put together the comparison below of what I'm seeing on Mac vs linux. One query has it's own filtered query for `admin_id`, the other uses my `func logs() throws -> Children<Log>` function on `Admin`. As you can see, the resulting sql for the child query is somehow getting the `log_id` foreign key on linux indeed of the `admin_id` foreign key.

``` swift
let query1 = try Log.query().filter("admin_id", admin.id!).sort("created_at", .descending)
print(query1.sql)
// Mac: select("logs", [(Log) admin_id equals number(2)], [], [Fluent.Sort(entity: BusinessCore.Log, field: "created_at", direction: Fluent.Sort.Direction.descending)], nil)
// Linux: select("logs", [(Log) admin_id equals number(2)], [], [Fluent.Sort(entity: BusinessCore.Log, field: "created_at", direction: Fluent.Sort.Direction.descending)], nil)
        
let query = try admin.logs().sort("created_at", .descending)
print(query.sql)
// Mac: select("logs", [(Log) admin_id equals number(2)], [], [Fluent.Sort(entity: BusinessCore.Log, field: "created_at", direction: Fluent.Sort.Direction.descending)], nil)
// Linux: select("logs", [(Log) log_id equals number(2)], [], [Fluent.Sort(entity: BusinessCore.Log, field: "created_at", direction: Fluent.Sort.Direction.descending)], nil)
```

**Comment by hhanesand** [comment]
Noticed this issue too!! I monkey patched it by using the following code...

```swift
extension Entity {
    public func fix_children<T: Entity>(_ child: T.Type = T.self) -> Children<T> {
        return Children(parent: self, foreignKey: "\(Self.name)_\(Self.idKey)")
    }
}
```

**Comment by kgn** [comment]
@hhanesand is this something you think could be fixed in the main repo? Maybe we could work on a PR for this?

I fixed it in a more hacky way, by making new functions that just return a `Query`.

``` swift
func logs() throws -> Query<Log> {
    return try Log.query().filter("\(Admin.name)_id", self.id!)
}
```

**Comment by vzsg** [comment]
A repro project, or a PR with a test would be pretty nice either way.

**Comment by tanner0101** [comment]
The addition of `Entity.foreignIdKey` fixes this in Fluent 2. A failing repro would help a lot to fix for Fluent 1.

**Comment by hhanesand** [comment]
@kgn Are you sure that you're using the same version of vapor on both computers? Mine was failing locally on osx and remotely on ubuntu. I took a look at the code in `Children` and thought I could spot the mistake pretty quick, but it seems weird to me that it would work on Linux?

**Comment by kgn** [comment]
@hhanesand looks like you are right! I tried to recreate this but multiple multiple times and was not able to: https://github.com/kgn/vapor-tests/tree/master/relations

So I switched my hacked functions back and all my unit tests are passing in my docker image now!
