### ISSUE TITLE
Is there any easy way to remote debug a vapor application running on an (develpoment) server?

### ISSUE THREAD

**Issue by jensliebau** [vapor/vapor#871]
Using Xcode it’s quite easy to debug a vapor application running on the local machine. Unfortunately it’s not always easy to run a server application on the local workstations cause of datebase connections and various other interactions that are difficult to „emulate“ on a local machine. To make the application behave more like in production use, I would prefer to do some kind of remote debugging of the vapor application running on the server.

It seams like lldb is able to support remote-debugging. Is there any option to attache Xcode Debugger to the remote application (running on the server), or is there any other IDE capable of doing this?

**Comment by tanner0101** [comment]
I'd also be interested in a solution to this. Sad to say, my go to method for debugging issues like these is `vim`, add `print(#line)`, save, recompile, run, repeat.

**Comment by BrettRToomey** [comment]
I don't know about any UI with remote debugging support, but you can easily use LLDB for command line. Check the documentation here: https://lldb.llvm.org/remote.html

**Comment by BrettRToomey** [comment]
Feel free to reopen if you have more questions/information on the topic. Thanks!
