### ISSUE TITLE
Initial routine with access to models from DB

### ISSUE THREAD

**Issue by lorsulic** [vapor/vapor#876]
# Enhancement

# Init routine

## Introduction

I'd like to do some initial work like fetching data from the db and preparing it only once, which is then available to my basicController and so for all routes defined here, something before the app gets visited via browser but with access to the models in the db.

## Motivation

Trying to access/ fetch items from the database is not possible from within the main.swift, for example if you got a basicController with the typical:

> main.swift

`let basic = BasicController()`
`basic.addRoutes(drop: drop)`
Trying to do some initial work inside addRoutes like fetching data from the database is not possible. There is a need for a routine where the data can be fetched, maybe modified and used for things like a menu or similar. This routine should be executed only once.

**Comment by BrettRToomey** [comment]
Using models before running the droplet is supported in Vapor 2. As for running code once on startup there are many ways you could accomplish this. Maybe try using a provider?
