### ISSUE TITLE
Usage of "Bytes" which is deprecated

### ISSUE THREAD

**Issue by jaisontj** [vapor/vapor#887]
CryptoRandom.bytes(16).base64String 

The above code is used in 

- Packages/Vapor-1.1.13/Sources/Sessions/CacheSessions.swift:24:29

- Packages/Vapor-1.1.13/Sources/Sessions/MemorySessions.swift:44:29

- Packages/Vapor-1.1.13/Sources/Auth/Authentication/CacheSessionManager.swift:29:39

.bytes is deprecated: Use the throwing method `bytes(count: Int)` instead.

**Comment by tanner0101** [comment]
@jaisontj upgrading to Vapor 1.5 will fix that error.
