### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by calebkleveter** [vapor/vapor#894]
As I look through the [API documentation](http://api.vapor.codes/) I see some very low numbers on the percent documented in the packages. Here are the numbers:

HTTP: 9%
Auth: 8%
Cache: 22%
Cookies: 38%
Sessions: 64%
SMTP: 29%
Transport: 19%
Vapor: 50%
WebSockets: 4%

This gets to an average of 27% documented. This is terribly low. I think if we work together on this we can get to an average of at least 98% in a few days.

This would be very helpful for a lot of people (including me) to be able to understand the APIs better.

P.S. Once we get this to at least 95% I would be willing try creating a [DevDocs](http://devdocs.io/) scraper.

**Comment by BrettRToomey** [comment]
Let's get started 🐎
