### ISSUE TITLE
error running: curl -sL toolbox.vapor.sh | bash

### ISSUE THREAD

**Issue by andyfen** [vapor/vapor#895]
error
```
bash: line 2: syntax error near unexpected token `newline'
bash: line 2: `<?xml version="1.0" encoding="utf-8"?>'
```

system info

> Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
> Target: x86_64-apple-macosx10.9

**Comment by vzsg** [comment]
Can you try running the command again? There might have been a temporary outage, as right now, `curl -sL toolbox.vapor.sh` returns the correct script.

**Comment by andyfen** [comment]
yup works now, thanks.
