### ISSUE TITLE
Link model object to existing MySQL table

### ISSUE THREAD

**Issue by alexfromalps** [vapor/vapor#898]
I have a database with some complex relationships mapped and populated with a large amount of data. My requirement is that I need to use this database with Vapor server.
So that I created a model object (with Fluent) similar to the database schema, in order to handle data flows between the server database.

When it comes the time to link database table(users table) with the model(User model), I found this method, which should implement inside the model class.

```
static func prepare(_ database: Database) throws {
    try database.create("users") { users in
        users.id()
        users.string("name")
    }
}
```

Since I don't need to define a schema for the already existing database, this prepare method just left unimplemented. The result is that I just can't interact with database, for any operations like userObj.save()

The same thing I achieved with Swift-Perfect Server with the help of the following method implementation inside the model object. This was done with the help MySQLStORM in Perfect.

  ```
// Map the model to the database table "user"
  override open func table() -> String {
    return "user"
  }
```
What I'm looking for is a solution like in the perfect server implementation, Is there any way it can be achieved with fluent?

**Comment by vzsg** [comment]
(Copying my response from vapor.team for the record.)

 It's not the `database.create` call that is important. The `prepare`/`revert` functions can be completely empty, especially in this case.

If you want to associate the class with a database table, two things have to be done:

1. In the model class, add a static field `entity` to tell Fluent the name of the table:

```
final class User: Model {
    static let entity = "users"
    ...
}
```

2) Add the model class to the droplet's array of preparations:

```
drop.preparations.append(User.self)
```

The second step is what actually associates the database with the model class.

**Comment by alexfromalps** [comment]
Thanks @vzsg, this is what I was searching for. Issue resolved.
