### ISSUE TITLE
Vapor does not handle URL encoded paths correctly

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#899]
Vapor doesn't seem to handle URL encoded paths properly and seems to decode the string leading to bugs if you have URL-encoded reserved characters in (like a `/`).

There's a small demo project at https://github.com/0xTim/VaporSlashBug which demos the bug with failing tests.

**Comment by BrettRToomey** [comment]
@0xTim Any updates on this?

**Comment by 0xTim** [comment]
Just tried running the tests again and it still happens. Haven't had a chance to dig into it yet to work out what's going on

**Comment by BrettRToomey** [comment]
@0xTim thanks. I'll mark this so they can look into it.

**Comment by tanner0101** [comment]
This should be fixed in my latest PR to engine: https://github.com/vapor/engine/pull/126. We are no longer percent decoding paths.

**Comment by 0xTim** [comment]
Can confirm that this is now fixed. Thanks! 👍
