### ISSUE TITLE
Is there anyway JSON(node: ) can be called with [String: Any] type

### ISSUE THREAD

**Issue by alexfromalps** [vapor/vapor#900]
I have a method, which will return a [String: Any] dictionary as below,
```
func getDetailDictionary() -> [String: Any] {
    // demo code
    let followers = [1, 2, 3, 4, 5]
    return [
      "name": "sample name",
      "followers": followers
    ]
  }

```
I need to convert this object to JSON, so that I can send it back to the client as a ResponseRepresentable object.

I used the following to prepare the json object     
`let jsonData = try JSON(node: getDetailDictionary())`

But this giving error, telling this doesn't match any available overloads. I don't think `[String:Any]` type is not handled in `JSON(node: )` method implementation.  Is there any better way I can get this issue resolved?

**Comment by tanner0101** [comment]
@alexfromalps unfortunately there's no way to support that safely. If the dictionary ended up containing a type that was not supported by Node there's not a clear solution. We could append a description of the object (e.g., `"\(item)"`), we could skip it, we could throw an error, etc. This is infact the exact reason `Node` was created in the first place.

The better solution here would be to change your method to `func getDetailDictionary() -> [String: Node]`
It will continue to work with String/Int literals.

**Comment by tanner0101** [comment]
Also using `Any` is relatively slow.

**Comment by alexfromalps** [comment]
Okay @tanner0101 , thanks for following up this issue. I think my issue will be solved with the use of `[String: Node]` type as you said. Could you say why the use of `Any` type is not recommended?

**Comment by tanner0101** [comment]
A couple of reasons:
- When using `Any` the compiler has no metadata about what type you're using and can't provide warnings or errors about mis-using the type.
- `Any` requires runtime checks / runtime casting which is slow and requires more code
- The actual implementation of `Any` under the hood in Swift requires carrying around extra metadata with the object. For example, and `Int` which only needs 8 bytes to be stored, will need much more (like 64 bytes or something) to hold the type info when stored as an `Any`

**Comment by jkmathew** [comment]
Hi @tanner0101 , As you said if I use string interpolation in a dictionary, then also its giving me the error  `Contextual type 'StructuredData' cannot be used with dictionary literal` My code sample is

```
let errorDescription = "here is the description"
json = JSON(["success": false, "error": "\(errorDescription)"])
```

Whats wrong with this?

**Comment by vzsg** [comment]
While I'm not sure why the compiler complains (I'll leave that for someone else to answer), being more explicit will make it compile:

```swift
let errorDescription = "here is the description"
let json = JSON(["success": false, "error": JSON.string("\(errorDescription)")])
```
