### ISSUE TITLE
Vapor build link MySQL failing on Xcode

### ISSUE THREAD

**Issue by quachdev** [vapor/vapor#903]
I am building the project through Xcode and I keep receiving this error:

`Command/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

I am running `vapor xcode --mysql -DNOJSON`, when I don't run it without the `-DNOJSON` I receive another error that was fixed by passing in that flag.
Any help would be great.

I am using a MySQL version through Homebrew if that matters as well.

Inspecting the logs, this is the command to build, 
`build -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib -Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib`

This doesn't seem to link it to the homebrew installation of mysql, could this be the issue?

**Comment by vzsg** [comment]
Is Homebrew installed at a non-default location on your system? What you see in the command is actually correct for the default location (`/usr/local`).

**Comment by quachdev** [comment]
@vzsg 

```
which mysql
/usr/local/bin/mysql
```

I assume that's correct?

**Comment by tanner0101** [comment]
@quachdev try doing `hombrew link mysql --force` and building again.

**Comment by BrettRToomey** [comment]
Closing due to staleness. If you still have an issue, feel free to reopen. Thanks!
