### ISSUE TITLE
Proposal: expiration time support for CacheProtocol and Sessions

### ISSUE THREAD

**Issue by vzsg** [vapor/vapor#907]
# Expiration time support for CacheProtocol and Sessions

* Author(s): [vzsg](https://github.com/vzsg), following up on the idea of [mcdappdev](https://github.com/mcdappdev)

## Motivation

As of Vapor 1.x and the current 2.x master, values stored with CacheProtocol are alive unless manually evicted, or destroyed along with the cache itself. It would be beneficial to automate this for some use cases: e.g. sessions with time limits, obeying Cache-Control in HTTP responses, enhancing periodic data fetching.

## Proposed solution

One possible solution is adding expiration time to CacheProtocol, changing the `set` method to expect a third, optional argument. (This is a breaking change as protocols cannot declare default values), and turn the current two-parameter `set` into a convenience extension.

Out of the three built-in implementations of the protocol:
- MemoryCache can be extended (see #906) to not return values which have expired;
- FluentCache could do the same with an extra column (not implemented now);
- and redis-provider could use the `SETEX` command instead of `SET` if an expiration time is set.

---

Adding expiration time to sessions is a different story, and could happen on the implementation level. I added it (without breaking changes) to CacheSessions.

## Code snippets

See #906.

## Impact

Only custom CacheProtocol implementations are affected by the breaking change, applications which just use this are not affected either in source compatibility, nor in behavior.

Otherwise, this is all opt-in, both for caches and sessions.

## Alternatives considered

Perhaps with some smart juggling of the protocol and the extensions, the third-parameter `set` could be the extension while the original stays the mandatory option. (I admit I did not spend too much time on such a combination.)

Also, the aforementioned use cases can be implemented by ignoring the related abstractions, middleware and providers of the framework and working directly with the cache driver.

**Comment by mcdappdev** [comment]
This is awesome. My only comment is that I think this should definitely be implemented on Sessions as well because remove both is necessary in some cases. Thanks for writing this up!

**Comment by vzsg** [comment]
Closing as the PR has been merged and Redis is already updated to boot 🙌
