### ISSUE TITLE
How to use routing parameter?

### ISSUE THREAD

**Issue by one-Stone** [vapor/vapor#918]
How to use routing parameter? It do not work.My code is
```
drop.get("users", Int.self) { request, userId in
    return "You requested User #\(userId)"
}
```
and load url in chrome with "http://0.0.0.0:8080/users/:id"
Thanks!

**Comment by tanner0101** [comment]
@one-Stone that code should work. Can you please provide more information about the system you are running on and what the error you got was?

**Comment by vzsg** [comment]
Just to be sure, try to use a real number in Chrome, like `http://localhost:8080/users/1`.

**Comment by one-Stone** [comment]
@vzsg It works.Thank you!
