### ISSUE TITLE
error: use of undeclared type 'SSL',   ubuntu 

### ISSUE THREAD

**Issue by lokimx88** [vapor/vapor#924]
I have installed openssl library into my system;but there are still errors;
Could anyone help me????

Packages/TLS-2.0.0-alpha.4/Sources/TLS/Context.swift:6:46: error: use of undeclared type 'SSL'
public typealias CSSL = UnsafeMutablePointer<SSL>

test/Packages/TLS-2.0.0-alpha.4/Sources/TLS/Context.swift:4:50: error: use of undeclared type 'SSL_CTX'
public typealias CContext = UnsafeMutablePointer<SSL_CTX>

error: use of unresolved identifier 'SSL_library_init'
            SSL_library_init()

/test/Packages/TLS-2.0.0-alpha.4/Sources/TLS/Context.swift:39:13: error: use of unresolved identifier 'OPENSSL_add_all_algorithms_conf'
            OPENSSL_add_all_algorithms_conf()

test/Packages/Crypto-2.0.0-alpha.4/Sources/Crypto/Cipher/Cipher.swift:71:34: error: use of undeclared type 'EVP_CIPHER_CTX'
            UnsafeMutablePointer<EVP_CIPHER_CTX>,

**Comment by eimanavicius** [comment]
@lokimx88 what was missing on your system? I have the same issue on ubuntu 17.04

**Comment by vzsg** [comment]
Please check the version what are the version numbers of the `openssl` and the `libssl-dev` packages on your system. It should be 1.0.2g. (1.1.x is not supported)

**Comment by eimanavicius** [comment]
ok, I have newer versions. Can I somehow statically link to older version?
```
$ apt policy openssl
openssl:
  Installed: 1.1.0f-2~ubuntu17.04.1+deb.sury.org+1
  Candidate: 1.1.0f-2~ubuntu17.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0f-2~ubuntu17.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu11.2 500
        500 http://ubuntu-archive.mirror.serveriai.lt zesty-updates/main amd64 Packages
     1.0.2g-1ubuntu11 500
        500 http://ubuntu-archive.mirror.serveriai.lt zesty/main amd64 Packages
```
```
$ apt policy libssl-dev
libssl-dev:
  Installed: 1.1.0f-2~ubuntu17.04.1+deb.sury.org+1
  Candidate: 1.1.0f-2~ubuntu17.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0f-2~ubuntu17.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu zesty/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu11.2 500
        500 http://ubuntu-archive.mirror.serveriai.lt zesty-updates/main amd64 Packages
     1.0.2g-1ubuntu11 500
        500 http://ubuntu-archive.mirror.serveriai.lt zesty/main amd64 Packages
```
