### ISSUE TITLE
Determine AJAX requests

### ISSUE THREAD

**Issue by omidgolparvar** [vapor/vapor#928]
I want to have different behavior for regular requests and AJAX requests for some URLs.

For example, normal request to `/home?page=2` will render view and send it to client, but AJAX request to `/home?page=2` will send JSON data to client.

How can I determine a request is AJAX in this framework?

**Comment by tanner0101** [comment]
Try `if request.accept.prefers("json")` to give an ajax response or `...prefers("html")` for a client response.
