### ISSUE TITLE
🐛 - filter .notEquals null fails with VaporMemory

### ISSUE THREAD

**Issue by kgn** [vapor/vapor#932]
Hey Guys,

While testing my app I came across a bug when querying if a column contains a non-null value.

Example:
``` swift
.filter("uuid", .notEquals, Node.null)
```

In my app I'm using `VaporPostgreSQL` for my real database, but using `VaporMemory` for my unit tests so it's easy to run them over and over again. While doing this, I was testing some queries that use `.notEquals, Node.null`, these queries work with `VaporPostgreSQL` but return nothing when used with `VaporMemory`.

I made a reproducible tests case to demonstrate this and hopefully help us get to the bottom of what's going wrong.

https://github.com/kgn/vapor-tests/tree/master/notEqualsNull

Failing test:
``` swift
func testEqualsNotNull() throws {
    var part1 = Part(name: "Motherboard", uuid: UUID().uuidString)
    try part1.save()
    
    var part2 = Part(name: "Memory", uuid: nil)
    try part2.save()
    
    var part3 = Part(name: "Hard Drive", uuid: UUID().uuidString)
    try part3.save()
    
    let query = try Part.query().filter("uuid", .notEquals, Node.null)
    
    XCTAssertEqual("\(query.sql)", "select(\"parts\", [(Part) uuid notEquals null], [], [], nil)")
    
    // TEST FAILS
    XCTAssertEqual(try query.count(), 2)
}
```

**Comment by tanner0101** [comment]
Fluent 1.0's memory driver is fairly limited in what it can do. Fluent 2.0 will use SQLite in-memory instead. 

As a workaround, you can use the SQLite driver and specify the path as `:memory:` to use SQLite instead of the Fluent 1.0 memory driver. This will recreate the behavior of Fluent 2.0 in 1.0.

**Comment by kgn** [comment]
Ah cool, that's likely a better solution overall as I have some raw queries as well in my app that I haven't been able to write unit tests for.

**Comment by kgn** [comment]
@tanner0101 this is how I was setting up my test, how would I switch this over to sqlite?

``` swift
    override func setUp() {
        let driver = VaporMemoryDriver()
        let database = Database(driver)
        Employer.database = database
        Admin.database = database
        Invite.database = database
    }
```

**Comment by tanner0101** [comment]
You'll need to add the [SQLite driver](https://github.com/vapor/sqlite-driver/) package and then `import FluentSQLite` and you'll have access to the `SQLiteDriver` which accepts a `path: String` in the init.

**Comment by kgn** [comment]
@tanner0101 I started working on migrating my tests to SQLite instead of VaporMemory and I'm running into a number of issues. [One bug that I reported](https://github.com/vapor/sqlite-driver/issues/18), but more difficult to migrate are some of my migrations that alter columns which SQLite doesn't support. Could we re-open this issue and look into a solution to get `.filter("uuid", .notEquals, Node.null)` working with the `VaporMemoryDriver`?

**Comment by kgn** [comment]
Here's the solution I came up with, I'm not sure which branch to submit a pull request against, I forked my changes off of the `1.4` release tag: https://github.com/kgn/fluent/commit/ca3c1a775472fc3375cf09b50b30caca6077203b

Do you guys see any issue with this solution? I only updated the case for `.notEquals`, but I wonder if the other cases should be updated as well? To just directly compare the node values?

Please let me know if you think I should make any changes and which branch would be appropriate to file the PR against.

**Comment by kgn** [comment]
I brought this code into my main app where I have many more unit tests and made some improvements after my original change caused some tests to fail. I updated `.equals` in addition to `.notEquals` and updated the logic so that the `Node.null` check only runs if val is null, this should be a much safer change as it falls back on the original logic in all other cases: https://github.com/kgn/fluent/commit/f7159be337f30b204a2c74407939e1e9c2e64ea1

**Comment by tanner0101** [comment]
@kgn if you want to submit that as a PR to Fluent on the [1.4.x branch[(https://github.com/vapor/fluent/tree/1) i can approve 👍

**Comment by kgn** [comment]
@tanner0101 PR submitted

**Comment by BrettRToomey** [comment]
It looks like this has been fixed or at least worked on. Closing for now 🎩
