### ISSUE TITLE
Can't build with latest beta

### ISSUE THREAD

**Issue by treaves** [vapor/vapor#937]
🚀 Thanks for contributing!

# Bugs

A sample, skeleton project with only vapor as a dependency fails to build with Xcode.  

/project.build/checkouts/ctls.git-9210868160426949823/shim.h:4:10: 'openssl/conf.h' file not found
/project/ci-s/.build/checkouts/crypto.git-7980259129511365902/Sources/Crypto/Cipher/Cipher+Method.swift:1:8: Could not build Objective-C module 'CTLS'

**Comment by hhanesand** [comment]
take a look at this : http://stackoverflow.com/questions/43070534/openssl-ctls-trouble-with-vapor-2

**Comment by treaves** [comment]
Yes.  And?  That link doesn't resolve this issue.  For many reasons.  First, that single overly long response isn't marked as accepted.  Perhaps because it's not one suggestion, but, a list of many things that may impact.

In my case, I have CTLS installed, via brew.  And it had zero impact on the errors above.

**Comment by Alex293** [comment]
Have a look at https://github.com/vapor/jwt/issues/34

**Comment by treaves** [comment]
Thanks, but, that does not change the outcome.  openssl/conf.h is not being found. It is in two places installed via brew:
/usr/local/Cellar/openssl/1.0.2d_1/include/openssl/conf.h
/usr/local/Cellar/openssl/1.0.2k/include/openssl/conf.h

The failure is in building the Crypto package.

**Comment by tanner0101** [comment]
@treaves did you re-generate your Xcode project after doing `brew install ctls` ?

**Comment by treaves** [comment]
Yes.  I even deleted it completely and regenerated.

**Comment by woguan** [comment]
I'm having the same issue

**Comment by vzsg** [comment]
Are you on the High Sierra beta?

**Comment by woguan** [comment]
Yes, I am.

**Comment by vzsg** [comment]
On High Sierra, you need to:
1. install `openssl` with Homebrew:

    ```
    brew install openssl
    ```

1. manually specify the include and library path to both the build and Xcode project generator tasks:

    ```bash
    swift build -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib
    swift package -Xswiftc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib generate-xcodeproj
    ```

**Comment by woguan** [comment]
Thank you very much!

I just did the second step since I had done the first step before.

It worked perfectly 👍

System: macOS High Sierra, Xcode 9.0 Beta 2.

**Comment by tanner0101** [comment]
https://github.com/vapor/ctls/pull/5
