### ISSUE TITLE
Vapor Docs v2

### ISSUE THREAD

**Issue by lorsulic** [vapor/vapor#939]
# A collection for vapor docs v2

> use comments for further suggestions for what should be documented

### init routine, hook for initial work after starting the app/ access to db ensured but before drop.run()
- description see #876 

### Fluent -> Model -> Node Representable:
Maybe when to use
```
func makeNode(context: Context) throws -> Node {
        return try Node(node: [
            "id": id,
            "name": name
        ])
    }
    ...
}
```

vs
```
func makeNode(context: Context) throws -> Node {
        var node = Node([:])
        node["id"] = id
        node["name"] = name.makeNode()
        ...
}
```
respectively, i think someone mentioned for v2 something like
```
func makeNode(context: Context) throws -> Node {
        try node.set("id", id)
        try node.set("name", name)
        ...
}
```

**Comment by lorsulic** [comment]
currently only this is mentioned: 
```
try JSON(node: [        
    "version": "1.0"    
])
```
would be helpful, to show the creation of a more complex JSON structures like: 
```
{                
    "actions" : [                    
        { "add" : { "index" : "items_v1", "alias" : "items" } }                
    ]            
}
```

**Comment by BrettRToomey** [comment]
Thanks! We'll make sure to have better docs on this subject for 2.0
