### ISSUE TITLE
Caching Dependencies

### ISSUE THREAD

**Issue by Harley-xk** [vapor/vapor#941]
Every time I made a new vapor project, It will take several minutes on fetching dependencies from github. It's even becoming endless when my network is poor.
It will be a very nice feature if there is a way to fetching dependencies from local disk from cache.

**Comment by flyweights** [comment]
You are right

**Comment by tanner0101** [comment]
This is unfortunately impossible with the way the Swift Package Manager is setup. We have tried really hard :( 

Good news is Vapor 2.0 has less code and should fetch faster. 

I'd recommend reaching out to bugs.swift.org to request this feature. The more people that ask, the more they will work on it! :)

**Comment by Harley-xk** [comment]
So sad :(
