### ISSUE TITLE
openssl not found in Vapor beta

### ISSUE THREAD

**Issue by treaves** [vapor/vapor#949]
A sample project will not compile, with a single dependency on Vapor itself.  The build fails on compilation of the transitive dependency CTLS:

```
.build/checkouts/ctls.git-9210868160426949823/shim.h:4:10: error: 'openssl/conf.h' file not found
#include <openssl/conf.h>

.build/checkouts/crypto.git-7980259129511365902/Sources/Crypto/Cipher/Cipher+Method.swift:1:8: error: could not build Objective-C module 'CTLS'
import CTLS
```

My machine is running the current version of Xcode, which includes Swift 3.1.

I have vapor/tap/ctls-1.0.0-beta.3 already installed. 'locate openssl/conf.h' shows this output:

```
/usr/local/Cellar/openssl/1.0.2d_1/include/openssl/conf.h
/usr/local/Cellar/openssl/1.0.2k/include/openssl/conf.h

```

**Comment by treaves** [comment]
If I cd into the checkout of the CTLS module under build, and checkout beta 2, this error goes away.  Unfortunately, it then fails on building Fluent...

**Comment by LoganWright** [comment]
@treaves does a clean build not pull beta 2 automatically?

**Comment by tanner0101** [comment]
You can run `swift package update` to get the latest versions of all packages. My guess is the `Package.pins` file you had was pointing to an old version of the CTLS package from before the switch to Homebrew/APT installation. The api-template has been updated since.
