### ISSUE TITLE
No error message on wrong cipher / hash key size in production mode

### ISSUE THREAD

**Issue by truemetal** [vapor/vapor#952]
The following `crypto.json` placed in `secrets` would issue no error message on production:

```
{
    "hash": {
        "method": "sha256",
        "key": "hello"
    },
    "cipher": {
        "method": "aes256",
        "key": "there"
    }
}
```

The following probably should be `log.error` or terminate startup if cipher is critical for operations. 

![droplet_configurable_swift](https://cloud.githubusercontent.com/assets/2472186/24680374/5e84f2fc-1999-11e7-8223-a9c9438c76d9.png)

---

N.B. probably unrelated to the above, there's no error message for `sha256`'s wrong key size even in `development` mode

---

Here's an output for `drop.log.error("secrets \(String(describing: drop.config["crypto"]))")`: 

```
secrets Optional(Settings.Config(node: Node.Node.object(["hash": Node.Node.object(["key": Node.Node.string("hello"), "method": Node.Node.string("sha256")]), "cipher": Node.Node.object(["key": Node.Node.string("there"), "method": Node.Node.string("aes256"), "iv": Node.Node.string("password")])])))
```

**Comment by vzsg** [comment]
I'm not aware of a minimum key size requirement for HMAC-SHA256, to be honest, can you cite something on the topic?

Otherwise, I agree with the crypto part, failing fast on boot is definitely safer than deferring it to the actual requests.

**Comment by truemetal** [comment]
@vzsg I've no idea about that to be honest, I'd trust you on this; if there's no requirement though maybe some minimum should be imposed? e.g. 2-symbol key might not just make sense

**Comment by tanner0101** [comment]
We've changed the `addConfigurable`s to be able to fail too in Vapor 2.0 (`drop.run()` is throwing now). 

We can change to `.error` in Vapor 1, but throwing (besides crashing) is not possible w/o breaking public API.

**Comment by BrettRToomey** [comment]
Any updates on this?

**Comment by tanner0101** [comment]
This has been fixed.
