### ISSUE TITLE
Parse dictionary from request query parameters

### ISSUE THREAD

**Issue by ezescaruli** [vapor/vapor#955]
# Parse dictionary from request query parameters

## Introduction

As my first project in Vapor, I am writing an API that can be used as the backend for a 📝  to-do list app.

The first two endpoints that I added were `POST /todos` to create to-dos, and `GET /todos` to fetch them as a list.

## Motivation

Something I would like my API to support is pagination. That way, if there are many to-dos, they can be split in pages when returning them to the client.

To follow a standard of how to send pagination parameters to the API, I am basing off the JSON API specification: http://jsonapi.org/format/#fetching-pagination. The examples that they show recommend that my paginated endpoint should look like this:
```
GET /todos?page[number]=1&page[size]=10
```

## Issue

I called the endpoint as shown above, and set a breakpoint to inspect the `Request` object, particularly its `query` property. I expected it to look like this dictionary:
```
[
  "page": [
    "number": "1",
    "size": "10"
  ]
]
```
but the `page` value instead looks like an array:
```
[
  "page": ["1", "10"]
]
```
so the `number` and `size` keys in the query parameters are ignored.

I am not sure if parsing query parameters into dictionaries is something that Vapor should support, or if it should be implemented exclusively in the apps that need it. However, I thought that it was worth to bring it into discussion. We went over the topic a bit in the Slack channel too: https://qutheory.slack.com/conversation/C0N6LGM0W/p1491301268142857

## Proposed solutions

Having a look at the codebase, I found that this might be the function where to add support to dictionaries in query parameters, if wanted:
https://github.com/vapor/vapor/blob/144bcb849ffcb0eb77a0f704e0d105faf4b7e98b/Sources/Vapor/FormURLEncoded/StructuredData%2BFormURLEncoded.swift#L39

So, apart from keys indicating an array (`keyIndicatedArray`), keys could also indicate a dictionary.

**Comment by hhanesand** [comment]
This issue also borders on the issue of array initialization, which is something we probably want to nail down as well. This [StackOverflow answer](http://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string) provides a good reference point.

Maybe the following parsing semantics for query parameters would make sense?

'?q=foo[bar1]=1&foo[bar2]=2'
is parsed as a dictionary with named keys
consider how many levels of nesting to support

'?foo[]=1&foo[]=2' and '?foo=1,2'
are parsed as an array of 2 objects

Any cases that I've missed?

**Comment by ezescaruli** [comment]
@hhanesand Good point about array initialization!

As far as I can tell, the current code already covers the case of `?foo[]=1&foo[]=2` to be parsed as
```swift
["foo": [1, 2]]
```
You can have a look at https://github.com/vapor/vapor/blob/144bcb849ffcb0eb77a0f704e0d105faf4b7e98b/Sources/Vapor/FormURLEncoded/StructuredData%2BFormURLEncoded.swift#L43

I am not sure about whether `?foo=1&foo=2` and/or `?foo=1,2` should also be covered by Vapor. In my opinion it would not be necessary, as the above already handles arrays as query parameters and that might be enough. However, I am of course open to discussion about this.

**Comment by BrettRToomey** [comment]
@tanner0101 @LoganWright @vzsg thoughts?

**Comment by ezescaruli** [comment]
Great, much appreciated! 👌
