### ISSUE TITLE
Error: Could not open Xcode project

### ISSUE THREAD

**Issue by ACChe** [vapor/vapor#956]
Select the `App` scheme to run.
Open Xcode project?
y/n>yes
Opening Xcode project...
Error: Could not open Xcode project.
-------------------------------------

"vapor xcode -y" does nothing (do not generate the Xcode project), but signals success.
Xcode 8.3 (8E162)

What did I go wrong? HELP!

**Comment by 0xTim** [comment]
@ACChe what folder are you in when you run the command? If you run `swift package generate-xcodeproj` what does it say?

**Comment by ACChe** [comment]
@0xTim I run the command under the project folder. 
If I run `swift package generate-xcodeproj` it will prompt  `Illegal instruction: 4`

**Comment by 0xTim** [comment]
@ACChe if you run `swift -version` what does it say? And what is the output of `ls -l` in the folder you are trying to run the commands?

**Comment by ACChe** [comment]
@0xTim 
1 -> Apple Swift version 3.1 
2 -> 
￼
![172](https://cloud.githubusercontent.com/assets/1592763/24750812/d59a93ae-1af9-11e7-8dc0-979d31fbe6d6.jpeg)
￼

**Comment by vzsg** [comment]
For the first question, please include the whole output. It should be something like:

```
12:13 $ swift -version
Apple Swift version 3.1 (swiftlang-802.0.48 clang-802.0.38)
Target: x86_64-apple-macosx10.9
```

**Comment by ACChe** [comment]
Hi Team, Any solution?

**Comment by tanner0101** [comment]
@ACChe `Illegal instruction: 4` is a definitely Swift bug. Can you report that to http://bugs.swift.org ?

Not much we can do about it unfortunately :(

**Comment by ACChe** [comment]
Cause not support 3.1 right now ?

**Comment by vzsg** [comment]
Have you tried cleaning up any leftovers from previous attempts?

```
# rm -rf .build
# rm -rf Packages
# rm -rf *.xcodeproj
# rm -rf Package.pins
```

Then try `vapor xcode` again.

**Comment by ACChe** [comment]
@vzsg Packages, *.xcodeproj and Package.pins not exist.

**Comment by ACChe** [comment]
after reinstall vapor then work normal.

**Comment by psmortal** [comment]
got same issue

**Comment by calebkleveter** [comment]
@psmortal What version of Xcode?
