### ISSUE TITLE
Project Dependencies updates

### ISSUE THREAD

**Issue by fabrijp** [vapor/vapor#961]
Is possible to update a project to get new dependencies releases ? For example I created a project with Vapor 1.15.13 and I want to update it to Vapor 1.15.14..

**Comment by fabrijp** [comment]
I don't know if this is the right way to do it but manually updating the version of the package in the file *Package.pins*, clean and building the project seems to get it updated.

**Comment by hhanesand** [comment]
`swift package update` will update dependencies to the latest version. I've had issues with the corresponding vapor command (`vapor update`).

Please make sure you've updated to the latest version of the toolbox if you run into trouble.

**Comment by fabrijp** [comment]
It worked. Thank you!
