### ISSUE TITLE
swift.vapor.sh/ubuntu installs old Swift toolchain

### ISSUE THREAD

**Issue by seandougall** [vapor/vapor#962]
Running `curl -sL swift.vapor.sh/ubuntu | bash` under Ubuntu, as specified in the Getting Started section of the docs, results in Swift 3.0.1 being installed. Only some parts of the Vapor toolbox will run under Swift 3.0.1; e.g. `vapor new <projectname>` succeeds. Others, notably `vapor build` and `vapor run`, require Swift 3.1 and will fail under the given instructions.

Manually installing Swift 3.1 clears up the error; however, the manual install instructions in the docs still point to 3.0.

**Comment by tanner0101** [comment]
Those scripts have been replaced with APT repos. Check out http://beta.docs.vapor.codes/getting-started/install-on-ubuntu/
