### ISSUE TITLE
Need help with saving image to mysql database

### ISSUE THREAD

**Issue by Leklef** [vapor/vapor#963]
a model of an employee and he has a property `Image`. What type of property should the image be? On the client side, `nsdata` is passed
Sorry for my English

**Comment by fabrijp** [comment]
Have you tried custom type ?

` data.custom("image", type: "blob")`

**Comment by Leklef** [comment]
I think, you have misunderstood me. I don't know what type it is necessary to set for the image in model
![screen copy](https://cloud.githubusercontent.com/assets/17198014/24838711/317d5e6e-1d56-11e7-8b9d-b74b1cfbd3a6.jpg)

**Comment by vzsg** [comment]
Use the type Bytes (which is an alias for `[UInt8]`).

**Comment by Leklef** [comment]
When I set image:Bytes , the mistake in node appears
<img width="839" alt="2017-04-09 19 21 05" src="https://cloud.githubusercontent.com/assets/17198014/24838926/06c33ba4-1d5a-11e7-86b4-84deff11b8e1.png">

**Comment by vzsg** [comment]
In the `makeNode` function, you could use `Node.bytes(image)`.

**Comment by Leklef** [comment]
Ok. Thank you
