### ISSUE TITLE
Droplet workDir is relative to build location not the actual working directory.

### ISSUE THREAD

**Issue by pumplerod** [vapor/vapor#969]
# Bugs
If the App executable is moved after it is built, the Droplet() workDir is still relative to the original build location.  Not the new location from where the command is called.

in main.swift:
```
import Vapor
let drop = Droplet()
print("WORKING DIR: \(drop.workDir)")
drop.run()

```
```
%> pwd
/home/USER_NAME/src/myWebApp/beta
%> sudo swift build
Linking ./.build/debug/App
%> cp .build/debug/App /home/USER_NAME/appServer/myWebApp/bin/.
%> cd /home/USER_NAME/appServer/myWebApp/
%> bin/App serve
WORKING DIR: /home/USER_NAME/src/myWebApp/beta
```

**Comment by vzsg** [comment]
Just for the record, what Vapor version were you using for this test?

**Comment by pumplerod** [comment]
Vapor version 1.5

**Comment by tanner0101** [comment]
@pumplerod this is expected behavior. You can pass the `--workdir=` flag to the executable to specify a different working directory.

```sh
.build/debug/App serve --workdir=/home/USER_NAME/appServer/myWebApp/
```
