### ISSUE TITLE
How to setup Vapor for iOS projects?

### ISSUE THREAD

**Issue by alickbass** [vapor/vapor#978]
What is the proper way of running Vapor server from iOS app? So what I want is to run a local server on iOS device. What is the preferable way to do so?

**Comment by vzsg** [comment]
The preferable way currently is "Don't do it."

The framework is heavily dependent on SPM modules, which is close to impossible to replicate for an iOS project; and even if it was possible, the low-level APIs it is built upon are either not supported and/or not recommended on iOS.

**Comment by alickbass** [comment]
@vzsg thanks for such fast answer! However, once the `SPM` gets proper iOS support, do you think it's some that would be on the roadmap for `Vapor`?

**Comment by vzsg** [comment]
As far as I know, some components are planned to have podspecs for installing into iOS projects (Node in particular), but I don't know of any plans for more to be supported in the future – SPM or otherwise.

**Comment by tanner0101** [comment]
This is possible related to: https://github.com/vapor/vapor/issues/108

**Comment by alickbass** [comment]
Thanks guys for your fast response! I'm gonna close the issue.

**Comment by siempay** [comment]
@alickbass  Hi did find solution for running a server side framework onto iOS ?

**Comment by alansmid** [comment]
Hello! Is [this](https://github.com/vapor/vapor/commit/ad3fb7f87d47eaca4d97bf515c0d7e93093b38ad) related?

**Comment by 0xTim** [comment]
Yes you can add Vapor to your iOS project with SwiftPM. Note that it's very experimental at the moment
