### ISSUE TITLE
500Error:  fileLoad("./Resources/Views/welcome.leaf")

### ISSUE THREAD

**Issue by danil-z** [vapor/vapor#985]
- Vapor Toolbox v1.0.9
- Vapor Framework v1.1.0

* OS:  MacOS
* OS Version: 10.12

### Expected Behavior

Expected to see:
 It works.

### Current Behavior

500Error: 
fileLoad("./Resources/Views/welcome.leaf")

### How to Reproduce

1. vapor new sample
2. vapor xcode
3. run app target in Xcode
4. open http://localhost:8080

**Comment by danil-z** [comment]
it works fine from **vapor run serve**. I believe the problem is relative paths, you probably need to add cd to srcroot into scheme scripts or something...

**Comment by tanner0101** [comment]
@danil-z Try upgrading to Vapor 1.5+. Version 1.1 is fairly old and does not support Swift 3.1.
