### ISSUE TITLE
v2.0.0-beta22 has growing memory consumption and lower throughput than v1.5.15

### ISSUE THREAD

**Issue by pruthvikar** [vapor/vapor#986]
* Vapor Version: v2.0.0-beta22 & v1.5.15
* OS: Mac OSX 
* OS Version: 10.12.4

### Expected Behavior

v2.0.0-beta22 and v1.5.15 to have similar throughput and memory consumption when benchmarking with wrk using 
`wrk -d 10m -t 8 -c 100 http://0.0.0.0:8080/hello`
and checking memory consumption on the Activity monitor

## v1.5.15
Throughput from wrk

```
wrk -d 10m -t 8 -c 100 http://0.0.0.0:8080/hello
Running 10m test @ http://0.0.0.0:8080/hello
  8 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    19.33ms   49.89ms 441.45ms   89.17%
    Req/Sec     5.07k     3.83k   24.71k    68.85%
  2819425 requests in 1.91m, 250.06MB read
  Socket errors: connect 0, read 0, write 0, timeout 1
Requests/sec:  24589.91
Transfer/sec:      2.18MB
```

Memory consumption on Activity monitor sits at around 2.2MB

## v2.0.0-beta22

```
wrk -d 10m -t 8 -c 100 http://0.0.0.0:8080/hello
Running 10m test @ http://0.0.0.0:8080/hello
  8 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.56ms  439.55us  19.95ms   88.91%
    Req/Sec     2.25k     1.25k    4.52k    51.89%
  1439476 requests in 1.34m, 178.46MB read
Requests/sec:  17909.59
Transfer/sec:      2.22MB
```

Memory consumption on Activity monitor grows linearly with time

N.B. both wrk tests were terminated early.

## v1.5.15

Start a new vapor project

main.swift
```
import Vapor

let drop = Droplet()
drop.get("hello") { request in
    return "Hello, world!"
}

drop.run()
```

build
`swift build --configuration release`

run
`<path/to/exe> --env=production`

benchmark
`wrk -d 10m -t 8 -c 100 http://0.0.0.0:8080/hello`

## v2.0.0-beta22

Start a new vapor project

main.swift
```
import Vapor

let config = try Config()
config.environment = .production
let drop = try Droplet(config: config)

drop.get("hello") { request in
  return "Hello, world!"
}

try drop.run()
```

build
`swift build --configuration release`

run
`<path/to/exe>`

benchmark
`wrk -d 10m -t 8 -c 100 http://0.0.0.0:8080/hello`

**Comment by tanner0101** [comment]
This looks like an issue with Foundation.Date in the Date Middleware. 

While you're doing benchmarks, take a look at: https://github.com/vapor/engine/pull/126

**Comment by pruthvikar** [comment]
> vapor/engine#126

What a lovely pull request to see!

I disabled the Date middleware by commenting out the following line in Droplet.swift
`//        config.addConfigurable(middleware: DateMiddleware.init, name: "date")`

It still has a growing memory footprint.

I went ahead and commented out the rest of the middleware and set the middleware to an empty array.
```
//        config.addConfigurable(middleware: ErrorMiddleware.init, name: "error")
//        config.addConfigurable(middleware: SessionsMiddleware.init, name: "sessions")
//        config.addConfigurable(middleware: DateMiddleware.init, name: "date")
//        config.addConfigurable(middleware: FileMiddleware.init, name: "file")
//        config.addConfigurable(middleware: CORSMiddleware.init, name: "cors")
self.middleware = []

```
 and still see a growing footprint.

**Comment by tanner0101** [comment]
This should be fixed in beta 23. Let me know if you see it again.
