### ISSUE TITLE
[DISCUSSION] Sessions Middleware doesn't allow Cookie options to be specified

### ISSUE THREAD

**Issue by 0xTim** [vapor/vapor#989]
## Sessions Middleware Cookie Customisation

* Author(s): [0xTim](https://github.com/0xTim)

### Introduction

The current `SessionsMiddleware` only sets a value on a cookie and there is no way to set any extra settings on the cookie (e.g. expiry date). By default a cookie should have HTTP only set to true as well to stop XSS from stealing login cookies.

### Motivation

Currently, if you would like to allow users to log into your web application using Vapor in Vapor 2, you would use a combination of the `PersistMiddleware` and `SessionsMiddleware` to set cookies after a log in. The standard `SessionsMiddleware` only sets the value on the cookie, and does not set any of the other parameters. `HTTPOnly` should be set to `true` unless the developer has a good reason not to. `Secure` should also be set in production so that the cookie is only transmitted over HTTPS.

Furthermore, it would be useful to allow for an expiry date to be set on the cookie to allow logons to persist across sessions, such as with the use of a 'Remember Me' check box on the login page. Again, this is not possible and the cookie is only valid for the session, meaning that if a user closes their tab or browser, they will need to log in again.

### Proposed solution

The proposed solution would be to add an optional parameter to the constructor containing a `CookieOptions` struct or similar. The customised cookie expiration date could be set as a property on the request storage and used when needed, defaulting to the current session as per the current behaviour.

### Code snippets

TBC

### Impact

It should be simple enough to keep the current behaviour as standard and have any additions be backwards compatible.

### Alternatives considered

The workaround is to have the standard `SessionsMiddleware` be simple and developers who need to customise the cookie roll their own Session Middleware.

**Comment by hhanesand** [comment]
yeah, this is a priority for 2.0 imo

**Comment by tanner0101** [comment]
Marked this as a bug. Thanks for reporting!
