### ISSUE TITLE
Reading traditional Chinese (正體中文), page not found

### ISSUE THREAD

**Issue by Jinxiansen** [vapor/vapor#990]
When I click on the button Chinese jump page page not found, the problem has existed for a long time.
No one repair it? 🤔

https://vapor.github.io/documentation/

<img width="854" alt="1" src="https://cloud.githubusercontent.com/assets/16829428/25779120/42cab4f2-3343-11e7-8ba0-26e26fad3c20.png">
<img width="862" alt="2" src="https://cloud.githubusercontent.com/assets/16829428/25779121/430ebbc0-3343-11e7-8101-b392209dd893.png">

**Comment by vzsg** [comment]
Updating the current documentation has some issues right now, sorry. You can access the Chinese front page [here](https://github.com/vapor/documentation/blob/master/1.5/README.zh-hant.md) until it is resolved.

**Comment by Jinxiansen** [comment]
@vzsg  oh, thanks !

**Comment by Jinxiansen** [comment]
@vzsg  I fix this problem, and increase the Chinese simplified documentation, but the need to review, please help me, thank you !

https://github.com/vapor/documentation/pull/142

<img width="706" alt="2" src="https://cloud.githubusercontent.com/assets/16829428/25780841/88e4321a-3361-11e7-83e6-1694e1376dff.png">

**Comment by LoganWright** [comment]
Thanks @Jinxiansen looks like that PR is merged, so I'm going to close this.
