### ISSUE TITLE
Bootstrap Navbar

### ISSUE THREAD

**Issue by iminier** [vapor/vapor#992]
* Vapor Version: 1.5
* OS: OS X
* OS Version: 10.12.4

### Expected Behaviour
Expected for Bootstrap Navbar to be displayed on the screen.

### Current Behaviour
Error 500 when you load the page with difficult to decipher text. View source reveals the text below. 

<div class="message">ParseError: tagTemplateNotFound("navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n                <span class=\"navbar-toggler-icon\"></span>\n            </button>\n            <a class=\"navbar-brand\" href=\"#\">Navbar</a>\n            <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n                <ul class=\"navbar-nav\">\n                    <li class=\"nav-item active\">\n                        <a class=\"nav-link\" href=\"#\">Home <span class=\"sr-only\">")</div>

### How to Reproduce

https://github.com/iminier/Server-Side-Swift/tree/VaporTestProject-Bootstrap_Error

I created a route to the "/" with: 

drop.get { req in
    return try drop.view.make("base")
}

In base.leaf I copied and pasted all the bootstrap code and saved file.

Run the web app, point browser to 0.0.0.0:8080 and I get the error. If I remove the Navbar from the base.leaf the file loads without any problems.

**Comment by tanner0101** [comment]
Leaf tags start with `#`, for example `#(foo)`. 

Because of that, leaf thinks you are writing a leaf tag declaration here:
```leaf
data-target="#navbarNav"
```

You can fix this by escaping `#` using `#()`.

```leaf
data-target="#()navbarNav"
```

Note: Leaf 2.0 will have better tag detection and should prevent issues like this.

**Comment by iminier** [comment]
Thanks for the quick reply. I tried that and now I am getting a new error 
ParseError: ExpectedOpenParentesis. 
I'll keep trying. Worst case I'll add the issue to the Leaf repo.

**Comment by calebkleveter** [comment]
@iminier Try this:

```html
 #raw(){ <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> }
```

**Comment by iminier** [comment]
Found the issue in my case at least. Sample html from bootstrap site below.

```
<div class="jumbotron">
<h1>Jumbotron heading</h1>
<p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
<p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
</div>

```
The last <p> tag line has a # that is stopping the page from loading when it reaches the #. I tried 

```
<p><a class="btn btn-lg btn-success" href="()#" role="button">Sign up today</a></p>
```
but that didnt work. The only thing that worked was removing the # completely. I tested this with my previous navbar issue and it worked. Once the # is gone the pages load.
